package.json, packages/unleash-api/.eslintrc, packages/unleash-frontend/.eslintrc, packages/unleash-frontend/public/.eslintrc, packages/unleash-frontend/public/js/__tests__/.eslintrc
Should be the last one before full release.
Not necessary to merge this I suppose, could morph into stable pretty soon
=> Use latest (hopefully last) alpha of eslint config

packages/unleash-api/app.js, packages/unleash-api/lib/routes/index.js, packages/unleash-api/migrations/sql/009-create-client-strategies.up.sql, packages/unleash-api/test/e2e/event-api.test.js, packages/unleash-api/test/e2e/feature-api.test.js, packages/unleash-api/test/e2e/feature-archive-api.test.js, packages/unleash-api/test/e2e/strategy-api.test.js, packages/unleash-api/test/unit/routes/strategies.test.js
Some endpoints are provided on both `/` and `/api` to support older clients.
What do you think @sveisvei ?
=> Introduces the /api path.

lib/server-impl.js
This is the responsibility of the app
For us, this is really annoying in fiaas, as it doesn't produce JSON.
=> Remove uncaught exception logging

CHANGELOG.md, docs/api/client/metrics-api.md, docs/api/client/register-api.md, lib/db/client-instance-store.js, lib/routes/client-api/metrics-schema.js, lib/routes/client-api/register-schema.js, lib/routes/client-api/register.js, lib/routes/client-api/register.test.js, migrations/20170628205541-add-sdk-version-to-client-instances.js
This PR adds support for a sdkVersion field to the client registration. This should be sent by official clients in future version to ease debugging. 
Format: `"sdkVersion" : "unleash-client-java:2.2.0"`
closes #221
=> Add support for sdkVersion in client registration

lib/routes/admin-api/feature.js
This PR adds support for underscores in strategy names, allowing for const style naming conventions (`FOO_BAR`).
See related PR in `Unleash/unleash-frontend` - https://github.com/Unleash/unleash-frontend/pull/93
=> Allow underscores in name validation

lib/routes/admin-api/feature.js, lib/routes/admin-api/feature.test.js
Those underscores broke when support for underscores was added in https://github.com/Unleash/unleash/pull/267. The `-` was no longer at the end of the expression, and thus changed meaning to `from \ to \`.
I found no tests for valid names; how do I best write a test for this?
=> Fix feature name validation regex

.travis.yml, lib/db/feature-toggle-store.js, lib/routes/admin-api/feature.js, test/e2e/api/admin/feature.e2e.test.js, test/fixtures/fake-feature-toggle-store.js
Fixed name-validation to also check archived feature toggle names.
Inline validation works again:
API error message shown again:
closes #284
=> Should not allow creation of archived toggle

lib/db/feature-toggle-store.js, lib/routes/admin-api/feature.js, lib/routes/admin-api/feature.test.js, test/fixtures/fake-feature-toggle-store.js
Will know tell the user if the toggle name is already
in use by an active feature toggle or an archived toggle.
Also brings lates unleash-frontend fix, which prevents an
invalid form from submitting.
closes: #290, #291
=> Bugfix: more informative name validation errors

docs/api/internal-backstage-api.md, lib/metrics.js, lib/metrics.test.js, lib/server-impl.js
Allows us to create nice annotations in grafana when a toggle has been updated:
closes #323 
TODO: 
:heavy_check_mark:  write a test for it?
:heavy_check_mark:  Document how to create annoations
=> feat(metrics): Expose toggle updates to prometheus

docs/api/client/feature-toggles-api.md, lib/routes/client-api/feature.js, lib/routes/client-api/feature.test.js, yarn.lock
Allows the client to limit the response to name with the given prefix.
Closes #251
=> fix(clientApi): Add namePrefix paramter to /api/client/features

yarn.lock
All but nyc were within semver range, but it also adds the sha512 integrity field from yarn 1.10
=> chore: upgrade all dependencies

docs/activation-strategies.md, docs/beta-features.md, docs/client-sdk.md, docs/client-specification.md, docs/database-backup.md, docs/database-schema.md, docs/developer-guide.md, docs/getting-started.md, docs/migration-guide.md, docs/securing-unleash.md, docs/unleash-context.md, website/pages/en/index.js
I ran the docs through a spell checker to fix the typos and punctuation issues. I also improved sentence structure and word usage in several places.
In the case of spelling, there seems to be a mix of American and British English, e.g. `standardise` (Br.E.) and `authorized` (Am.E.). Is there a variant you prefer more, @ivarconr ?
=> Fix typos in documentation

lib/db/client-metrics-store.js, lib/db/client-metrics-store.test.js
Currently if the initial metrics-fetch fails unleash will not setup a metrics-poller. This fix ensures that the metrics-poller will start regardless of whether the initial fetch fails or succeeds.
closes #396
=> fix: Metrics poller should start even if inital fetch fails.

lib/routes/admin-api/feature.js, lib/routes/admin-api/feature.test.js
This PR makes the Admin API expose two new endpoints:
`/api/admin/features/:featureName/toggle/on` - Enable the toggle, regardless of current state. 
`/api/admin/features/:featureName/toggle/off` - Disable the toggle, regardless of current state. 
Both endpoints will in addition return the current state of the feature toggle.
We also need to update unleash-frontend to take advantage of these two new endpoints, see:
https://github.com/Unleash/unleash-frontend/pull/169
closes #394 
cc @Catuna
=> fix: Add explicit endpoints for toggle on/off

docs/getting-started.md
The example provided in the docs doesn't work (see #429)
=> fix: require path of logger

docs/securing-unleash.md, examples/keycloak-auth-hook.js, examples/keycloak-auth-unleash.js
When implementing Unleash we had to create a custom Keycloak authentication hook. This was not very straight-forward to do (broken npm packages regarding passport strategies), so I thought it might be best to include this in the Unleash documentation.
=> Add sample Keycloak Authentication hook

lib/options.js, lib/options.test.js
Due to deploy unleash to kubernetes cluster, I would like separate DATABASE_URL to use multiple DATABASE_*, which help us to reuse current configmap, and protect DATABASE_PASSWORD by using vault secret.
Setting DATABASE_URL still available due to backward compatible
=> feat: Separate DATABASE_URL to multiple DATABASE_* variable

lib/app.js, lib/middleware/no-authentication.js, lib/middleware/no-authentication.test.js, test/e2e/api/admin/feature.e2e.test.js
I believe Unleash should provide a dummy user with admin permissions in the `adminAuthentication=none` scenario. 
fixes #453
=> fix: none authentication should have a mock user

docs/getting-started.md, lib/event-hook.js, lib/event-hook.test.js, lib/server-impl.js
As discussed in Slack.
The goal of this change is to allow users an easy way to run custom code when changes happen to features. (e.g. post to Slack).
=> feat: add option and functionality that allows a user to hook into feature mutations

lib/db/client-applications-store.js, lib/db/client-instance-store.js, lib/db/client-metrics-store.js, lib/db/client-metrics-store.test.js, lib/db/index.js, lib/db/metrics-helper.js, lib/events.js, lib/metrics.js, lib/metrics.test.js, lib/server-impl.js, lib/timer.js, lib/timer.test.js, test/e2e/helpers/database-init.js
**What this PR does**
This PR adds the `db_query_duration_milliseconds` metric to track the database query latency.
**Why do we need this?**
I want to monitor the timing of the DB queries to see if high http response times correlate with slow database queries. Without these metrics i can not tell whether the node process, the network to the DB or the DB itself is slow.
**Additional Notes**
While connecting more teams with the feature toggle we've seen latency issues on the following API paths:
Request volume on the Feature Toggle API Server: ~25 requests per second at peak times.
| call | 90th percentile | 99th percentile |
|---|---|---|
| POST /api/client/register  | 10ms -> 21ms  | 88ms -> 186ms  |
| POST /api/client/metrics  |  9ms -> 20ms| 100ms -> 120ms  |
| GET /api/client/features …
=> feat: add db query latency metrics

examples/keycloak-auth-hook.js
This fixes three things in the keycloak example:
- host can be secured
- client id case problem
- realm variable wasn't actually used
=> fix: update keycloak example

README.md
Added in readme unleash-client-core as official sdk and removed unofficial ones
=> chore: Added unleash-client-core as official sdk

docs/activation-strategies.md, migrations/20191023184858-flexible-rollout-strategy.js, migrations/flexible-rollout-strategy.json, package.json, yarn.lock
fixes #516
This will also require new UI to make it simple(r) to use.
=> feat: Add new Flexible Rollout Strategy

docs/getting-started.md
I thought it would be nice to let developers know of the useful `baseUriPath` option, as I found this very useful.
=> chore: Add baseUriPath support to docs

README.md
Noticed that this is listed further down the README under supported client SDKs. I also changed the casing of .Net to .NET which is how it is written by `dotnet --info` so I guess that's the official way 😄 
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
Version:   3.0.100
Commit:    04339c3a26
```
=> chore: Add .NET Core to top sentence about supported platforms

docs/getting-started.md, docs/securing-unleash.md, examples/basic-auth-unleash.js, examples/google-auth-unleash.js, examples/keycloak-auth-unleash.js, lib/db/db-pool.js, lib/db/index.js, lib/db/setting-store.js, lib/options.js, lib/options.test.js, lib/server-impl.js, lib/server-impl.test.js, migrations/20200329191251-settings-secret.js, migrator.js, package.json, server-dev.js, test/e2e/helpers/database-config.js, test/e2e/helpers/database-init.js, test/e2e/stores/setting-store.e2e.test.js, test/fixtures/fake-setting-store.js, test/fixtures/store.js, yarn.lock
It's kind of stupid that you have to configure these stuff manually. We have now introduces the setting table where we can store persistent settings. 
In this PR we auto-generate the session secret in the database and use that. It is still possible for the user to override the secret used to encrypt sessions if he likes. 
(We assume encrypted postgres db and that the user protects the db credentials.)
**Todo:**
=> feat: move secrets to settings

lib/options.js
Defining "enableLegacyRoutes" as "true" is less secure than setting it to "false" by default, according to the documentation in "Securing Unleash" (https://unleash.github.io/docs/securing_unleash).
Happy to hear criticisms/explanations of current state! <3
=> feat: Update "enableLegacyRoutes" to false

lib/options.js
As described in https://node-postgres.com/features/ssl , `ssl` is an object which will be passed to Node TLS socket.
Also:
```
(node:1) DeprecationWarning: Implicit disabling of certificate verification is deprecated and will be removed in pg 8. Specify `rejectUnauthorized: true` to require a valid CA or `rejectUnauthorized: false` to explicitly opt out of MITM protection.
```
This change makes it possible to configure accepted SSL CA certificate, or to accept self-signed certificate.
=> fix: Support SSL settings

docs/getting-started.md
Updated baseUriPath documentation to make it clearer it needs a starting slash. Also mentioning the alternative usage through BASE_URI_PATH environment variable
=> chore: Updated baseUriPath documentation

docs/getting-started.md, examples/express-parent-app.js, lib/options.js, lib/server-impl.js, lib/server-impl.test.js
Creates a new method on the server implementation, `create()` which functions identical
to `start()` but does not auto-start the express server.
PR includes tests + docs.
Closes #605
=> Feat: Adds server.create()

docs/api/admin/feature-toggles-api.md, docs/api/admin/feature-types-api.md, docs/api/client/feature-toggles-api.md, docs/database-schema.md, lib/db/feature-toggle-store.js, lib/db/feature-type-store.js, lib/db/index.js, lib/routes/admin-api/feature-schema.js, lib/routes/admin-api/feature-schema.test.js, lib/routes/admin-api/feature-type.js, lib/routes/admin-api/index.js, migrations/20200805091409-add-feature-toggle-type.js, migrations/20200805094311-add-feature-type-to-features.js, package.json, test/e2e/api/admin/feature.e2e.test.js, test/fixtures/fake-feature-toggle-store.js, yarn.lock
Introduces feature toggle types:
```yaml
--- 
- id: release
name: Release
description: Used to enable trunk-based development for teams practicing Continuous
Delivery.
lifetimeDays: 40
- id: experiment
name: Experiment
description: Used to perform multivariate or A/B testing.
lifetimeDays: 40
- id: ops
name: Operational
description: Used to control operational aspects of the system behavior.
lifetimeDays: 7
- id: killswitch
name: Kill switch
description: Used to to gracefully degrade system functionality.
lifetimeDays: Infinity
- id: permission
name: Permission
description: Used to change the features or product experience that certain users
receive.
lifetimeDays: Infinity
```
Todo:
=> feat: Add support for toggle types

app.json
Heroku Postgres doesn't support version 9.5 anymore. Available versions are 9.6, 10, 11, 12
=> fix: Heroku Postgres add-on version change

docs/getting-started.md, lib/db/db-pool.js, lib/options.js, lib/options.test.js
knex cannot detect the database version when a non-standard postgres database is used. See https://github.com/knex/knex/issues/1477#issuecomment-668965455.
knex offers support for explicitly declare the database version to overcome this issue, See [knex documentation](http://knexjs.org/#Installation-client)
> Note: The database version can be added in knex configuration, when you use the PostgreSQL adapter to connect a non-standard database.
```javascript
var knex = require('knex')({
client: 'pg',
version: '7.2',
connection: {
host : '127.0.0.1',
user : 'your_database_user',
password : 'your_database_password',
database : 'myapp_test'
}
});
```
This pull request aims to expose the version configuration.
=> feat: Add support for explicitly set database version.

.github/workflows/build.yaml, lib/db/client-applications-store.js, lib/db/client-metrics-store.test.js, lib/routes/admin-api/metrics.js, lib/routes/admin-api/strategy.test.js, lib/routes/client-api/register.test.js, lib/routes/health-check.test.js, test/e2e/helpers/database-init.js, test/fixtures/fake-metrics-store.js, test/fixtures/no-logger.js
After this change output is now cleaned and shows the following:
```bash
npm run test                         
> unleash-server@3.9.0 pretest /home/ivaosthu/code/unleash
> npm run lint
> unleash-server@3.9.0 lint /home/ivaosthu/code/unleash
> eslint .
> unleash-server@3.9.0 test /home/ivaosthu/code/unleash
> NODE_ENV=test PORT=4243 ava
285 tests passed
```
=> fix: cleanup test console output

CHANGELOG.md, lib/db/feature-toggle-store.js, lib/routes/client-api/feature.js, lib/services/feature-toggle-service.js, test/e2e/api/client/feature.e2e.test.js, test/fixtures/fake-feature-toggle-store.js
3.10.0 introduced the lastSeenAt property on the feature toggle.
This causes 304 to never happen, as the feature toggles will
constantly update lastSeenAt field.
This commit removes the following fields from the /api/client/features
responses:
- createdAt
- lastSeeenAt
- description
These fields are unessary for the client SDKs to do their job.
=> fix: remove fields from /api/client/features respnse

docs/api/client/feature-toggles-api.md
This PR just fixes a small typo on this paragraph: https://unleash.github.io/docs/api/client/features#variants
=> Fix typo in /api/client/features docs

lib/metrics.test.js, lib/routes/backstage.js, package.json, yarn.lock
I guess this is a breaking change in some very specific cases if you expose the Prometheus metrics in your own code. I don't see that being a remotely common use case, though, so it's possibly not necessary to wait for a major release of Unleash(?).
I "need" this change because our metrics library depends on prometheus ^13.0.0 and is used by our logging library to measure log messages by severity/level. That doesn't work since I end up with two versions of `prom-client`, with separate registers.
=> fix: upgrade prom-client from 12.0.0 to 13.1.0

lib/db/feature-toggle-store.js, lib/error/db-error.js, lib/error/feature-has-tag-error.js, lib/routes/admin-api/util.js, package.json, test/e2e/api/admin/feature.e2e.test.js, yarn.lock
- After seeing frontend behaviour where the user could add the same
tag multiple times, and not get errors or be stopped doing so, we'll
change the backend to return a 409 if you tag a feature with a tag it
already has.
- Previous to this commit, the setup was to do `onConflict().ignore()`
which caused the frontend to not get any help from the backend as to
whether or not the operation was allowed
- This fix adds a custom error and adds a branch to the handleError util
method for handling just that error type with a 409.
- This caused a couple of tests to receive 409, probably due to
insufficient cleanup between tests. Adding faker as a dev-dependency and randomising
toggle names and tag values for each test reduces the chance that
we'll run into duplicate issues in the future for the …
=> Make feature-toggle-store return 409

docs/activation-strategies.md, docs/feature-toggle-variants.md, lib/db/context-field-store.js, lib/routes/admin-api/context-schema.js, lib/services/feature-schema.js, lib/services/feature-schema.test.js, migrations/20210208203708-add-stickiness-to-context.js, test/e2e/api/admin/context.e2e.test.js
This feature actually started in the node-sdk:
https://github.com/Unleash/unleash-client-node/pull/201
=> feat: allow stickiness on context-fields

package.json, tsconfig.json, yarn.lock
This allows us to run start:dev and develop inside `src` and see changes immediately, rather than having to remember to stop, run `yarn build` and then `start:dev`.
=> Setup tsc-watch for dev build

src/lib/middleware/response-time.js
Changes from:
```
http_request_duration_milliseconds_sum{path="/api/admin/features/myFeature/toggle/on",method="POST",status="200"} 51.16884
http_request_duration_milliseconds_count{path="/api/admin/features/myFeature/toggle/on",method="POST",status="200"} 2
```
to
```
http_request_duration_milliseconds_sum{path="/api/admin/features/:featureName/toggle/on",method="POST",status="200"} 51.16884
http_request_duration_milliseconds_count{path="/api/admin/features/:featureName/toggle/on",method="POST",status="200"} 2
```
Note `:featureName`.  I didn't adopt the `express-prometheus-middleware` technique, because it just tried to regex out IDs and didn't seem to really solve it. The req had what we needed instead. (Just had to read the docs ;) )
=> fix: gh-720 Use express path templates for prometheus metrics

src/lib/db/client-metrics-db.js, src/lib/db/db-pool.js, src/lib/db/event-store.js, src/lib/metrics.js, src/lib/metrics.test.js, src/lib/routes/admin-api/archive.js, src/lib/routes/admin-api/context.js, src/lib/routes/admin-api/event.js, src/lib/routes/admin-api/feature-type.js, src/lib/routes/admin-api/feature.js, src/lib/routes/admin-api/feature.test.js, src/lib/routes/admin-api/metrics.js, src/lib/routes/admin-api/strategy.js, src/lib/routes/admin-api/strategy.test.js, src/lib/routes/admin-api/tag-type.js, src/lib/routes/admin-api/tag.js, src/lib/routes/admin-api/tag.test.js, src/lib/routes/client-api/feature.js, src/test/fixtures/fake-feature-toggle-store.js, src/test/fixtures/fake-strategies-store.js, src/test/fixtures/fake-tag-store.js, src/test/fixtures/store.js
- If database goes away while unleash is running, unleash now stays
running, but all api endpoints will return 500.
- This includes our health endpoint, which allows k8s or similar
orchestrators to decide what should be done, rather than Unleash
terminating unexpectedly
=> feat: Handle database connection errors with 500

package.json
Noticed this came in when upgrading 🙂 We already use TS so doesn't affect us, but still
=> fix: TypeScript should be a dev dependency

src/lib/db/client-applications-store.js, src/lib/services/client-metrics/index.js, src/migrations/20210304141005-add-announce-field-to-application.js, src/migrations/20210304150739-add-created-by-to-application.js, src/test/e2e/helpers/database.json, src/test/e2e/services/client-metrics-service.e2e.test.js
Tried to get the test working with fake clocks, but just ended up in a weird pending state, as such, this isn't optimal and I'm more than happy if someone can think of a better way of checking that we do announce the created applications, and just once.
=> fix: publish events about unannounced applications

src/lib/event-differ.js, src/lib/event-type.js, src/lib/events.ts, src/lib/routes/admin-api/user-admin.ts, src/lib/routes/auth/reset-password-controller.ts, src/lib/services/user-service.test.ts, src/lib/services/user-service.ts, src/test/e2e/api/admin/user-admin.e2e.test.ts, src/test/fixtures/fake-event-store.ts
This PR introduces events for add/update/delete user. It does not report password changes etc. We might want to introduce such events later. 
It should be noted that this information in the event log might be a bit more sensitive than updating a feature toggle. We should evaluate if we should introduce specific privileges for the root-event log, as you light not want all user to be have access to this information.
=> feat: add user events

src/lib/create-config.ts, src/test/e2e/helpers/database-init.js
this will make Unleash "just work" on envrionments like
Heroku where SSL is required, but uses a self-signed
certificate.
=> fix: set default DATABASE_SSL to not rejectUnauthorized

src/lib/routes/admin-api/util.js
I noticed nameType is used in multiple places. Do we want to change nameType for all validations where it is used, or should we create a new nameType for variants specifically?
=> fix: set name type to be min 1 character

src/lib/db/feature-toggle-store.js, src/lib/routes/admin-api/archive.test.js, src/lib/routes/admin-api/archive.ts, src/lib/routes/admin-api/feature.ts, src/lib/services/feature-toggle-service.js, src/test/e2e/api/admin/feature-archive.e2e.test.js, src/test/fixtures/fake-feature-toggle-store.js
- To provide a way to run end-to-end tests without cluttering
our demo instance with way too many feature-toggles, making this
endpoint available will allow end-to-end tests to clean up properly
after themselves
=> chore: expose an endpoint to really delete a toggle

src/lib/routes/admin-api/user-admin.ts
If email is configured but somehow fails to send, we do not want to fail the entire API call because the user is still created and it creates a situation in the frontend where we do not progress from the view. When you then try to recreate the user it already exists - which creates quite a confusing situation. 
These changes allow us to fall back to invite link if something happens with the email distribution, so that the frontend can naturally progress
=> fix: report email as not sent to fe if it throws

README.md
I think the deploy getting started link may have changed and right now points to a 404 page, I updated it to what I think is the right page
=> Update getting started to point to the right page

README.md
Hi,
Just found that the link to Docker was broken. Here is a "fix".
=> fix: fix broken link to docker image

websitev2/docs/sdks/unleash-proxy.md
removed duplicate curl in the health endpoint example call.
curl curl --> curl
=> fix curl health call

websitev2/docs/deploy/import-export.md
Hello !
Just a modest improvement in documentation.
Document query params in import API (/api/admin/state/import) according to source code : https://github.com/Unleash/unleash/blob/v4.0.10/src/lib/routes/admin-api/state.ts#L67
=> doc: add import query params in doc (#673)

package.json, src/lib/services/state-util.ts, yarn.lock
Due to this error unleash.start({import: {file: './some_file.yaml'}}) is currently not possible
Originally done here
https://github.com/Unleash/unleash/commit/c66545e11e08c90d47bfda0fe051dec03a7a40be
=> fix: update mime library method signature to 2.X

website/docs/sdks/unleash-proxy.md
This PR tries to clarify that the Unleash proxy does not expose any data about flags that are not enabled for a particular user.
A potential point of improvement would be to expand on why it doesn't and why that might be a security concern.
As a bonus, the PR also fixes a typo: the word 'preformat' doesn't make any sense in that context, so I have assumed it was supposed to be 'performant' and changed it accordingly.
=> Clarify that the proxy does not expose disabled flags

website/docs/user_guide/quickstart.md
This is a follow-up to https://github.com/Unleash/unleash-proxy-client-js/pull/43. Checking the feature toggles right after initializing the client can be misleading. The rest of the document already suggests using event emitter.
There's one thing I'm unsure about though: the `synchronized` event is not listed in the [Readme of unleash-proxy-client](https://github.com/Unleash/unleash-proxy-client-js#available-events). Is/was there such an event?
=> Wrap the client into an event listener in the quickstart doc

src/lib/db/client-metrics-store-v2.ts, src/test/e2e/api/admin/client-metrics.e2e.test.ts
In client metrics v2 we utilize postgres to count the usage
across a few dimensions (feature_name, app_name, environment).
It turns out that if the UPDATE values are not executed in a predictable
order we can end up in a deadlock scenario with postgresql.
**We discovered this while testing in production, behind a feature flag.** 
In this fix we thus sort the metrics on the `feature_name`, `app_name` and
`environment`, to make sure they always are executed in a predictable
order, and thus avoiding independent inserts colliding in to a deadlock
waiting for each-other.
=> fix: prevent deadlock for batchinserting usage metrics

website/docs/sdks/java.md
From 5.0 java sdk we've moved our maven coords to `io.getunleash`
=> docs: Updated maven coordinates for java sdk

app.json
Heroku no longer supports Postgres 10. Upped to version number to the latest version supported, 13.
=> chore: upped postgres version for Heroku.

src/lib/db/feature-strategy-store.ts, src/lib/db/feature-toggle-store.ts, src/lib/routes/admin-api/project/variants.ts, src/lib/schema/feature-schema.ts, src/test/e2e/api/admin/project/variants.e2e.test.ts
Since the old schema did validate variants uniqueness, we need to make sure new endpoint also validates it
=> fix: make new variant api validate name uniqueness

src/lib/services/project-health-service.ts, src/test/e2e/api/admin/project/project.health.e2e.test.ts
- Since the archived toggles are not visible in the health dashboard,
including them in the health rating calculation makes for some really
confusing dashboards. This PR makes sure we only include non-archived
toggles when calculating health.
=> fix: Stop healthrating from including archived

src/lib/error/operation-denied-error.ts, src/lib/routes/admin-api/feature.ts, src/lib/routes/util.ts, src/lib/schema/feature-schema.ts, src/lib/services/feature-toggle-service.ts, src/test/e2e/api/admin/feature.e2e.test.ts, src/test/e2e/api/admin/project/features.e2e.test.ts
After adding the new `/variants` endpoint for features we now have a way
to access control adding/modifying variants, so the /:featureName
endpoint should no longer allow editing/adding variants.
This removes variants as a known field from the featureMetadata schema
and tells joi to stripUnknown, thus making sure we never include
variants in the initial creation or future update calls.
For the old features v1 API we allow it to declare that it has already
validated the data coming with its own schema, so we should use the data
we get from it. Thus keeping the old v1 functionality intact
Co-authored-by: Simon Hornby <simon@getunleash.ai>
=> task: Ban changes to variants through feature

website/docs/user_guide/environments.md, website/sidebars.js
This PR adds the environment page in the docs to the sidebar so that it's easier to find, and updates the content to reflect that environments are now GA.
=> docs: List environment article and prep it for release

website/docs/user_guide/technical-debt.md
Previously, when you searched for 'stale toggle' in the docs, the
first result would be the API docs and it'd be hard to find any form
of explanation of what a stale toggle is at all.
To combat that, this PR adds a section to the tech debt chapter
explaining what they are.
=> docs: Add section on (potentially) stale toggles to tech debt

website/docs/sdks/android-proxy.md, website/docs/sdks/proxy-ios.md, website/docs/sdks/proxy-javascript.md, website/docs/sdks/proxy-react.md, website/docs/sdks/unleash-proxy.md, website/docs/user_guide/native-apps.md
This PR adds more information about what UNLEASH_PROXY_SECRETS and client keys are.
To the proxy docs I have added a description of what the configuration variables are and how they are used. To the client SDK docs, I have added more information about how the clients are configured and what the configuration values are.
I have also slightly restructured the docs where appropriate and added some extra syntax highlighting.
=> Add more info about UNLEASH_PROXY_SECRETS and client keys

src/lib/db/feature-toggle-store.ts, src/lib/routes/admin-api/project/variants.ts, src/lib/services/feature-toggle-service.ts, src/lib/types/events.ts, src/lib/types/stores/feature-toggle-store.ts, src/test/e2e/api/admin/feature.e2e.test.ts, src/test/fixtures/fake-feature-toggle-store.ts
This triggers when we update or overwrite variants, and will include the
previous variants and the new variants.
Co-authored-by: Ivar Østhus <ivarconr@gmail.com>
=> fix: Adds feature-variant-updated event.

website/docs/user_guide/activation-strategies.md
It appears that we've forgotten to update this bit of info regarding
the SDKs' compatibility. To avoid having the same data in multiple
places, let's instead point the user to the compat table.
=> docs(sdks): gradual rollout: custom stickiness -> point to SDK table

website/docs/user_guide/quickstart.md
The issue was that the image link was encased in an extra set of
brackets. However, the extra bracket set was added because docusaurus
wouldn't compile otherwise. Instead it complained about an
unterminated string literal in the alt text.
As it turns out, this had nothing to do with the contents of the alt
text, but rather with the fact that the alt text was split over
multiple lines.
=> docs(fix): fix quickstart image not being displayed.

src/lib/services/user-service.ts, src/lib/types/user.test.ts, src/lib/types/user.ts, src/test/e2e/services/user-service.e2e.test.ts
This fixes an issue where the updateUser call would allow null email
addresses, then update the email to null and then raise an exception,
leaving the db in a state where no user could be resolved.
=> fix: Update updateUser code to reject empty emails

website/docs/how-to/how-to-use-custom-strategies.md
As mentioned in [this issue comment on the previous changes](https://github.com/Unleash/proxy-client-react/issues/25#issuecomment-1000260964), we could clarify the steps for custom strategies when running the proxy with Node.
This PR adds separate steps for the different ways of running the proxy.
Before merging, I'd love to know whether this is indeed the right way of passing custom strategies when running as a Node process.
=> docs: add steps for running the proxy in node with custom strats.

website/docs/how-to/how-to-use-custom-strategies.md
Remove some extra line breaks in the source file and change all instances of 'node' to 'Node.js' in the how-to for custom strategies.
=> docs(chore): remove spacing, change 'node' -> Node.js

website/docs/deploy/getting-started.md, website/docs/how-to/how-to-use-custom-strategies.md, website/docs/sdks/node.md, website/docs/sdks/proxy-javascript.md, website/docs/sdks/proxy-react.md, website/docusaurus.config.js, website/package.json
This lets us show both `npm` and `yarn` versions of the commands to all users. It's implemented as a tabs component and will sync across the docs site. This means that if you've indicated a preference for one or the other, all other `npm` commands will display using the same tool (`npm` or `yarn`).
This is what it looks like:
=> docs: add `npm2yarn` annotation to all npm commands

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/create-config.test.ts, src/lib/create-config.ts, src/lib/db/api-token-store.ts, src/lib/services/api-token-service.test.ts, src/lib/services/api-token-service.ts, src/lib/types/models/api-token.ts, src/lib/types/option.ts, src/lib/types/stores/api-token-store.ts, src/server-dev.ts, src/test/fixtures/fake-api-token-store.ts, website/docs/deploy/configuring-unleash.md
Issue: https://github.com/Unleash/unleash/issues/1153
fixes #1153
=> feat: Add init api tokens option

website/docs/deploy/configuring-unleash.md
This PR adds some extra information regarding the difference between creating admin tokens in code and via env vars.
It also adds a missing definition for `authentication.type`: `open-source` didn't have a definition.
=> docs: explain difference between using `initApiTokens` and `INIT_ADMIN_API_TOKENS`

src/lib/db/feature-toggle-store.ts, src/lib/routes/admin-api/feature.ts, src/lib/services/feature-toggle-service.ts, src/lib/services/state-service.ts, src/lib/types/model.ts, src/test/e2e/api/admin/project/features.e2e.test.ts, src/test/e2e/api/admin/project/variants.e2e.test.ts, src/test/e2e/api/admin/state.e2e.test.ts, src/test/e2e/api/client/feature.e2e.test.ts, src/test/e2e/services/environment-service.test.ts
Todo: 
Are there any other places we update feature toggles that needs to be addressed?
=> fix: Should not remove variants when updating feature toggle metadata

website/docs/deploy/import-export.md
This PR expands the section on startup imports to also explain how the environment variables work.
=> docs: add information on using env vars for startup imports.

website/docs/deploy/import-export.md
This groups ways of importing together and ways of dropping together
instead of grouping the instructions by whether they use env variables
or command line options.
Should (?) make it easier to find what you want, but most importantly:
means we only need to explain the database drops once.
=> docs: restructure startup import section to group actions by intent

website/docs/sdks/index.md
In doing so, change the link from pointing at Cognite's old repo (which redirects) to pointing at Unleash's repo and sort the lists of SDKs.
=> docs: move Rust SDK to list of official SDKs

website/docs/sdks/index.md, website/docusaurus.config.js, website/sidebars.js
When I accidentally (🙈) pushed the deletion of the community SDKs page yesterday, I hadn't thought of adding a redirect from the old page. This PR takes care of that and cleans up the structure of the community SDKs section.
=> docs: redirect old community SDKs url to new /sdks

website/docs/sdks/ruby.md
Hi, thank you for awesome software 👍 
I found that official document of Ruby SDK has wrong example code. It occurred syntax error like below.
And more we can improved for markdown notation a little :)
```sh
$ ruby unleash.rb
unleash.rb:6: syntax error, unexpected ',', expecting =>
...Authorization': '<API token>'},
```
So I fixed its.
1. Fixed Ruby syntax of `custom_http_headers`
1. Deleted unnecessary indent
1. Updated syntax highlighting from `sh` to `ruby`
Thanks!
=> docs: Fixed syntax error for Ruby SDK example

README.md, website/docs/sdks/dot_net.md, website/docs/sdks/index.md, website/sidebars.js
This PR groups the SDKs into server-side and client-side sdks.
I have made the categories non-collapsible for now, but would be happy to make them collapsible if anyone has any strong feelings towards it.
I have also updated all uses of ".net"/".Net" and changed them to ".NET" as is the standard.
Finally, though it's a little on the side, I've added a link to the Rust SDK in the sidebar. It's an external link for now.
New sidebar:
=> docs: group sdks into non-collapsible categories: server and client

website/docs/sdks/unleash-proxy.md
Also: restructure the steps relating to running it via docker to align
better and to avoid repeating information.
=> docs: add steps for running the proxy via Node

website/src/css/custom.css
This increases the contrast from 3.42 to above 4.5, in compliance with
the AA standard. It also uses the same shade of purple that we have in the Unleash admin UI 🎉
=> fix: use the Unleash purple for links / increase contrast

website/src/css/custom.css
This commit changes the hover color of links in the footer to keep it
accessible.
The color will be the exact same as the un-hovered version. This is in
line with the other links in the documentation. The links _do_ get
underlined when hovered, so there is still a visual distinction
between the states.
I've added the variable in the `footer` section instead of in `:root`
because the variable I assign it to (`--ifm-footer-link-color`) gets
overridden closer to the footer, so if you set it in `:root`, you end
up with the wrong value.
addresses and closes https://github.com/Unleash/unleash.github.io/issues/8
=> fix(docs/a11y): fix lack of contrast in on hovered links in footer

website/docs/how-to/how-to-create-and-assign-custom-project-roles.md
For simplicity I've added them as separate sections, but I'd love for
them to be listed higher up.
=> docs: Add how-to videos to cpr how-tos

src/migrations/20220125200908-convert-old-feature-events.js
When we change the feature events we introduced a new column
on the events table to ease resolving of feature related events,
instead of knowing the types and require the data object to include
a name property. This commit adds a migration to make sure we
convert all feature events.
fixes: #1299
=> fix: add migration for old feature events

src/lib/error/base-error.ts, src/lib/error/disabled-error.ts, src/lib/error/password-mismatch.ts, src/lib/routes/auth/reset-password-controller.ts, src/lib/routes/auth/simple-password-provider.js, src/lib/routes/util.ts, src/lib/services/user-service.ts
Unleash is an API and it would simplyfy a lot of the specific
errors could carry the expected HTTP status code for this error.
This would eliminate the need for a gigantic switch/case in the
handle-errors function.
=> fix: improve API error-handling

website/docs/sdks/index.md
Hello,
I'd like to add a reference of my SDK for C++ to the Community SDK list.
Thanks!
=> Doc: Add Unleash SDK for C++ to Community SDKs list.

website/docs/sdks/unleash-proxy.md
The rest of the docs all use `some-secret`, so having only this **one**
place use `some-public-key` is really misleading.
=> docs: use `some-secret` instead of `some-public-key`

website/src/css/custom.css
This hides the 'back to main menu' button from the narrowed site menu.
There is no main menu to speak of, so having it take you back to
'unleash enterprise' and the GitHub icon seems unnecessary.
=> docs: hide 'back-to-main-menu' entry in narrow menu

website/sidebars.js
I keep getting confused and clicking the link to the how-to guides
when I wanna go to the API reference docs and I _wrote_ the damn thing
🙈 In other words, I betcha someone else is struggling with the same
thing.
So let's try and change it to something that's harder to click by mistake.
=> docs: change API how-tos label from "API" to "Using the APIs"

website/docs/sdks/unleash-proxy.md, website/docusaurus.config.js, website/src/css/custom.css
It seems that some changes (some recent, some older) have introduced a number of contrast issues to the doc dark theme. This PR fixes issues with:
- the sidebar
- urls
Most changes should be pretty uncontroversial, but it might be worth discussing the new `--ifm-color-primary` gradient at some point.
Optionally: we should develop a dark mode palette for Unleash and use that.
=> docs(a11y): fix a number of contrast issues with the dark theme

website/src/css/custom.css
Without this modifier, the border, background color, etc, also applies
to logos in the header and footer, and that's not what we want.
=> fix: don't apply extra image styling to images outside the main

website/src/css/custom.css
This changes the darker end of the primary color scale to make it even
darker. This means that at the lower end of the scale, white text also
gets enough contrast to be accessible.
For the record: these variables do not seem to be in use anywhere else
in the code base (based on a text search), so it shouldn't affect any
other bits or pieces.
**Before**:
**After**:
=> docs: adjust primary color scale, fix search dropdown a11y issues

src/lib/routes/admin-api/client-metrics.ts, src/lib/services/client-metrics/metrics-service-v2.ts, src/test/e2e/api/admin/client-metrics.e2e.test.ts
Needed by the the new feature toggle metrics page.
=> refactor: add an hoursBack query param to the raw metrics endpoint

website/docs/user_guide/environments.md
These things are either implemented or just around the corner now. I
suggest removing them to not be misleading anymore. Case in point: we
just had a customer asking us when the permissions system would be
ready because the docs say it's planned as a future improvement.
=> docs: remove "future enhancements" section of environments doc

website/docs/sdks/unleash-proxy.md
As reported in slack, the description here was wrong. This is a little fix.
=> fix: correct the description of disabled variants

website/docs/api/admin/user-admin.md
Adds an explanation of what the various properties in the payload
object to the `user-admin` endpoint does. Most seem fairly
self-explanatory, but I'm not entirely sure what `sendEmail` does.
Requires validation by a third party before merging.
=> docs: Add payload properties for user-admin post payload

website/docs/api/admin/feature-toggles-api-v2.md
This PR adds documentation for the endpoints relating to adding and removing users to/from a project.
As a bonus (scout's rule!) it also updates syntax highlighting and formatting on other code samples in this article.
I have wrapped the responses in a `details` element for now. It makes the descriptions a bit more compact and gives the responses a nice blue background. However, it might also make it harder to use if the user needs to check out the responses often. Options would be to remove the details element or to make it open by default. I'm open to input here.
=> docs: describe `/api/admin/projects/:projectId/users/:userId/roles/:roleId` endpoint

website/docs/user_guide/activation-strategies.md
This PR clarifies how and where activation strategies are implemented and evaluated in terms of the server, server-side sdks, the proxy, and front-end sdks.
=> docs: reword and add additional deets re: activation strategy impl

website/docs/deploy/configuring-unleash.md
This can be confusing for new users, especially if they don't speak Norwegian. Adding a note about this, should hopefully clear it up.
Relates to #1424
=> docs: add a note saying passord is Norwegian for password

website/docs/advanced/strategy-constraints.md
This PR adds a note to the strategy constraints reference documentation about undefined behavior in older version of the client SDKs.
=> docs: Add note to strategy constraints about undefined behavior

src/lib/schema/constraint-value-types.ts, src/lib/schema/feature-schema.test.ts, src/lib/schema/feature-schema.ts, src/lib/services/feature-toggle-service.ts, src/test/e2e/api/admin/project/features.e2e.test.ts
https://trello.com/c/MRIBNNFX/963-unleash-backend-include-values-from-the-unleash-client-api-as-an-empty-array
=> refactor: always add values to constraints

src/lib/experimental.ts, src/lib/services/segment-service.ts, src/lib/util/segments.ts, src/test/e2e/api/client/segment.e2e.test.ts
https://trello.com/c/j8M6VnPi/992-segments-backend-add-basic-limits-to-segments-and-constraint-values
=> feat: add segment limits

website/.storybook/main.js, website/docs/api/admin/segments.mdx, website/docs/reference/segments.mdx, website/package.json, website/sidebars.js, website/src/components/ApiRequest/ApiRequest.stories.jsx, website/src/components/ApiRequest/index.tsx
This PR adds reference documentation and API documentation for the new segments feature.
It also adds some minor work with storybook to add the API request component and converts it to TS.
I'd like to ask @olav to pay special attention to the API documentation: are the return codes correct? Is the returned data correct? I've used the segments controller as reference, so I think it's all there, but I might have missed something. 
Thank you! 😄
=> Add reference and API docs for segments

website/docs/sdks/android-proxy.md
To coincide with the changes introduced in [this PR](https://github.com/Unleash/unleash-android-proxy-sdk/pull/17)
=> docs: change android docs to use `clientKey`, not `clientSecret`

src/migrations/20220408081222-clean-up-duplicate-foreign-key-role-permission.js
We already created the foreign key when we created the table back in src/migrations/20210217195834-rbac-tables.js
=> fix: remove duplicate foreign key

src/lib/create-config.ts, src/lib/db/api-token-store.ts, src/lib/routes/client-api/feature.ts, src/lib/schema/api-token-schema.test.ts, src/lib/schema/api-token-schema.ts, src/lib/services/api-token-service.ts, src/lib/types/api-user.ts, src/lib/types/models/api-token.ts, src/lib/types/option.ts, src/migrations/20220331085057-add-api-link-table.js, src/test/e2e/api/admin/api-token.e2e.test.ts, src/test/e2e/services/api-token-service.e2e.test.ts, src/test/fixtures/fake-api-token-store.ts, src/test/fixtures/fake-feature-strategies-store.ts, src/test/fixtures/fake-feature-toggle-client-store.ts
This adds support for multi project tokens to be created. Backward compatibility is handled at 3 different layers here:
- The API is made backwards compatible though a permissive data type that accepts either a project?: string or projects?: string[] property, validation is done through JOI here, which ensures that projects and project are not set together. In the case of neither, this defaults to the previous default of ALL_PROJECTS
- The service layer method to handle adding tokens has been made tolerant to either of the above case and has been deprecated, a new method supporting only the new structure of using projects has been added
- Existing compatibility for consumers of Unleash as a library should not be affected either, the ApiUser constructor is now tolerant to the the first …
=> feat: Implement multi token support for client tokens

website/docs/sdks/index.md
When the title is only "Introduction" it's super hard to find via
search. Changing it to something more descriptive should make that easier.
=> docs: update client sdk overview title

.github/stale.yml, .github/workflows/flag-no-response.yaml
This adds two configuration files for Stalebot and the No-Response Action (No-Response bot has been deprecated and the No-Response Action is the recommended alternative).
The No-Response Action config has been left as default (more details on the defaults can be found here: https://github.com/lee-dohm/no-response/blob/main/action.yml and more details on the action itself in the root project).
The stalebot config has been slightly altered (original config here: https://github.com/probot/stale). Notably, the message for PRs and Issues has been customised and the time until being marked as stale has been reduced from 60 days to 30. Default config for exempt issues remains, which means that issues that are pinned, marked with a security label or a "[Status] Maybe Later" label won't be marked …
=> Add Stalebot and No-Response Action Config

.github/workflows/update_contributors.yaml
This adds very basic a generation of a contributors image workflow and pushes the resulting SVG to our CDN
=> feat: add contributors image generation workflow

CONTRIBUTING.md
This adds a little bit of detail to the contribution guidelines on how our we use and configure the stale and no-response bots
=> docs: Update contribution guidelines with info about our bots

README.md
This PR adds a link to the auto-generated contributors svg to the contributors section.
Here's what it looks like today:
=> docs: Add contributors svg with link to /graphs/contributors

website/docs/guides/feature-updates-to-slack.md
This PR adds a deprecation notice to the old Slack integration docs, pointing the user at the new(er) Slack add-on docs instead.
=> docs: Add deprecation notice to old slack guide

src/lib/routes/client-api/register.test.ts, src/lib/services/client-metrics/schema.test.ts, src/lib/services/client-metrics/schema.ts
Allows "instanceId" to be missing in client registrations and metrics. Will set it to "default".
=> fix: allow missing instanceId in client metrics

website/docs/api/admin/feature-toggles-api-v2.md, website/docs/api/admin/feature-toggles-api.md, website/src/components/ApiRequest/ApiRequest.stories.jsx, website/src/components/ApiRequest/index.tsx
This PR adds more deprecation notices to the old feature toggle API doc.
Closes #1523.
Additionally, it:
- adds how to disable endpoints to the new features API (this was missing)
- adds more thorough documentation to all the endpoints in the new API doc using the `ApiRequest` component. This lets the user see the raw http data, the curl command, OR the HTTPie command.
- Updates the `ApiRequest` component to allow for empty POST requests (to facilitate the on/off requests.)
~~Some of the endpoints don't seem to have clear mappings in the new API, so I'll need some help to figure out exactly where to link them to~~ **Done**
The new deprecation notices
The additional request data in the new API docs:
=> docs: Add deprecation notices to features v1

package.json, setupJest.js, src/lib/addons/addon.test.ts, src/lib/addons/addon.ts, src/lib/services/version-service.test.ts, src/lib/services/version-service.ts, src/lib/util/load-index-html.ts, tsconfig.json, yarn.lock
So we've had a couple of issues left hanging, one is that our http client usage for addons doesn't actually return the retried response (it does retry, but keeps the original response).
This PR switches to npm/make-fetch-happen, and replaces jest-node-fetch with nock to mock the http endpoints. Personally I find the tests to be more readable now, and we can now support retries the correct way.
=> task: Use make-fetch-happen

website/docs/user_guide/unleash-context.md
This PR fixes a duplicated description in the Unleash Context's field overview: `remoteAddress` seems to use the `sessionId` description.
Is this correct? And is it the right way to phrase it?
=> fix(docs): change the remoteAddress description

src/lib/openapi/spec/constraint-schema.ts, src/lib/openapi/spec/feature-schema.ts, src/lib/openapi/spec/features-schema.ts, src/lib/openapi/spec/override-schema.ts, src/lib/openapi/spec/strategy-schema.ts, src/lib/openapi/spec/variant-schema.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
Avoids a tricky index signature in the generated Response types.
=> refactor: disallow additionalProperties in response schemas

src/lib/types/stores/project-store.ts
Hi! :wave:
This is a super small change, but it broke my upgrade, so I figured I'd send a patch.
I think this is the only place in the `unleash-server` module's code that uses an import from the `baseUrl`, so it probably makes sense to align it with the rest.
This also makes my build work:
Before:
After:
I could avoid the issue by turning on the `skipLibCheck` option, but I don't want to do that :smile:
=> fix: don't import from tsconfig's baseUrl

website/docs/advanced/custom-activation-strategy.md
This PR fixes the listed types for custom activation strategy parameters.
=> docs(fix): correct custom activation strategies param types

website/docs/deploy/configuring-unleash.md
I added the "schema" option to the Database configuration in the Configuring unleash documentation page.
This is related to https://github.com/Unleash/unleash/issues/1565 which can be closed after.
The schema option was not available in the docs, now it should be complete
=> added db-schema to the docs page

src/lib/addons/datadog.ts
When adding a tag to a specific feature toggle, as shown below. I would expect the format to show up as `tag.type:tag.value`
When receiving a notification in Datadog Events the tags shows up backwards...
Closes #1568  .
src/lib/addons/datadog.ts is the only changed file
=> 1568 fix datadog type/value order in addon

website/docs/api/admin/feature-toggles-api-v2.md
This PR adds more details to the variant creation endpoint including payload, stickiness and overrides.
=> docs: add more details to variant creation API

website/docs/addons/webhook.md
We've had customers self-hosting reporting issues with webhooks erroring out with 500 errors due to custom SSL certificates. This PR adds a note to the webhook addon documentation orienting users about the possibility of setting the NODE_EXTRA_CA_CERTS environment variable when starting their application to support custom SSL certs for webhook endpoints.
=> docs: Add NODE_EXTRA_CA_CERTS documentation for webhook addons

package.json, src/lib/db/feature-toggle-store.ts, src/lib/db/project-store.ts, src/lib/db/user-store.ts, yarn.lock
This upgrade Knex to 2.0.0, in the process they've reordered the builder pattern, so this applies reorders to a few stores to make them compile and run
=> fix: Upgrade knex to 2.0.0

website/docs/sdks/proxy-react.md
The install instructions didn't previously add the
`unleash-proxy-client` package (presuming it'd be implicitly installed
by `npm`). This doesn't seem to be the case, so we'll list it explicitly.
=> docs: Update the react client install instructions

.github/workflows/add-to-project.yml
This change adds a workflow file that references the reusable workflow
in the unleash/.github repo. It should (if all goes well),
automatically add new issues and prs to the project board.
=> chore: Add workflow file to auto-add items to project board

src/lib/services/email-service.test.ts, src/lib/services/email-service.ts, src/lib/types/option.ts
When not supplying a username or password to email options it will now default to empty string for both.
Also added a new optional argument called `transportOptions` to allow users to configure SMTP in more detail.
Closes #1583.
`email-service.ts`
Not sure if using empty string (`''`) for auth works like expected, but in our smtp server (which has no auth configured) this seems to work.
=> Added ability to set additional transport options to email service

website/docs/sdks/python.md
This PR fixes syntax highlighting and header levels in the python SDK docs. It also changes previously invalid toggle names in examples.
Turns out that `Python` doesn't work for syntax highlighting, but `python` (lowercase `p`) _does_ 💁‍
The headers also jumped from level 1 to level 3. Now they go from 1 to 2 instead.
Some of the examples also used "My Toggle" as the toggle name. We don't allow spaces in toggle names, so I changed them for consistency.
=> docs: fix python sdk syntax highlighting, header levels

website/docs/sdks/index.md, website/docs/user_guide/index.md, website/docusaurus.config.js
This PR replaces all join.slack links in the docs with slack.unleash.run links, as we have full control over how they work.
=> docs: switch all slack links to slack.unleash.run

website/docs/sdks/proxy-react.md
Updated docs to specify using the named `FlagProvider` export instead of the default export, which was causing issues with Vite prod builds.
See: https://github.com/Unleash/proxy-client-react/pull/58
- `website/docs/sdks/proxy-react.md`
We might want to remove the default export at a later major version and only use named exports.
=> docs: update import to use named export instead of default

website/docs/sdks/proxy-vue.md
Updated the docs to specify using the named FlagProvider export instead of the default export.
Keeps proxy-client usage consistent with `proxy-client-react`. See: https://github.com/Unleash/proxy-client-react/pull/58
We might want to remove the default export at a later major version and only use named exports.
=> docs: use named export instead of default

src/lib/db/feature-strategy-store.ts, src/lib/db/project-store.ts, src/test/e2e/services/project-service.e2e.test.ts
Environments in `/api/admin/projects/$id` are not sorted. Having it in correct order from backend will make new _Single Project Overview - Features list_ table easier to implement.
`src/lib/db/project-store.ts`
=> fix: project environments order

src/lib/db/access-store.ts, src/test/e2e/services/access-service.e2e.test.ts
Fix an issue in changing project roles when the user also has a root role present
=> fix: Allow project roles to be changed when the relevant user has a root role

src/lib/db/feature-toggle-client-store.ts, src/lib/routes/client-api/feature.test.ts, src/lib/routes/client-api/feature.ts, src/lib/types/model.ts, src/test/e2e/api/client/global.segment.e2e.test.ts, src/test/e2e/api/client/segment.e2e.test.ts, src/test/e2e/helpers/database-init.ts
This implements global segments as an alternative to inline segments. The approach here is to make two modifications. Firstly, to the the toggle response itself, to add in add relevant global segments (segments that are defined but not in use are not delivered).  This is an optional property and will only appear if `inlinesegments` is turned off. The second change here is to insert onto each strategy a `segments` property that contains a list of IDs mapping back to the global segments in the base response. This is purely to conserve network resources and the intent is that the SDKs translate this back to a constraint.
=> feat: Add support for global segments

src/lib/services/project-service.ts, src/test/e2e/services/project-service.e2e.test.ts
Thomas found that project-change-events are not stored if created by users without a username. this fix makes sure that we either use email or username to store who makes the changes.
=> fix: use getCreatedBy to set created by on events stored

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/create-config.ts, src/lib/middleware/session-db.ts, src/lib/routes/index.ts, src/lib/routes/logout.test.ts, src/lib/routes/logout.ts, src/lib/types/option.ts
Adds an option to disable "Clear-Site-Data" header to be set on logout request. This is useful when you only want Unleash logout to clear local unleash session, but not clear all cookies and session data on the same domain. 
Can be disabled by setting the following environment variable `SESSION_CLEAR_SITE_DATA_ON_LOGOUT=false`.
=> feat: add option to disable 'Clear-Site-Data' header on logout

src/lib/services/state-service.ts, website/docs/api/admin/events-api.md
This PR updates the docs for the events endpoint of the admin API. It more clearly describes the existing endpoints and it documents **all** the existing event types.
=> Update /api/admin/events doc

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/create-config.test.ts, src/lib/create-config.ts, src/lib/routes/client-api/feature.test.ts, src/lib/routes/client-api/feature.ts, src/lib/types/option.ts, src/test/config/test-config.ts, src/test/e2e/api/client/segment.e2e.test.ts, website/docs/deploy/configuring-unleash.md
So this PR makes client features memoization a default, and moves configuration of it to the root config object rather than hiding it behind the experimental catch-all group.
=> task: default to memoizing client features

.github/workflows/build.yaml, .github/workflows/build_coverage.yaml, .github/workflows/build_prs.yaml, .github/workflows/build_prs_jest_report.yaml, .github/workflows/release.yaml
So, to reduce buildtimes, this PR updates setup-node to activate it's 'yarn' cache method, allowing us to cache yarn dependencies for our builders
=> chore: update setup-node task to activate yarn cache

src/lib/openapi/index.ts, src/lib/openapi/spec/tag-type-schema.ts, src/lib/openapi/spec/tag-types-schema.ts, src/lib/openapi/spec/update-tag-type-schema.ts, src/lib/openapi/spec/validate-tag-type-schema.ts, src/lib/routes/admin-api/tag-type.ts, src/test/e2e/api/admin/tag-types.e2e.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
This adds openApi specs for the tag types. Currently we have a couple of tests expecting validation to fail for a tagtype with numbers for description and icon, since we expect them to be string, but openapi seems to be coercing these values to be strings before we hit joi validation.
=> task: add open-api for tag-types

website/docs/sdks/dot_net.md, website/docs/sdks/java.md, website/docs/sdks/node.md
We've seen multiple users complain that their client does not yield the correct enabled result. Most of the time this is due to the client not being synchronized with the server yet. This updates the docs for the clients we've seen the most cries for help with to include a more visible tip about synchronous initialization.
Co-authored-by: Thomas Heartman <thomas@getunleash.ai>
=> docs: SDK Synchronization tips

website/docs/api/admin/user-admin.md
This change updates the documentation for the user creation API, fixing errors mentioned in #1717:
-   it's either `username` or `email` that is required on creation. `name` is not required.
-   `name` is the only required field when updating a user.
=> Docs: Update description for create + update user

src/lib/openapi/index.ts, src/lib/openapi/spec/tag-with-version-schema.ts, src/lib/routes/admin-api/tag.test.ts, src/lib/routes/admin-api/tag.ts, src/test/e2e/api/admin/tags.e2e.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
This adds openApi schema for tags.
2 things, 
- we now return the tag as the response in the create and get tag endpoints.
- Open api again coerces numbers to strings, so we now allow numbers as tag values.
=> task: add openapi for tags

website/docs/api/admin/segments.mdx, website/docs/reference/segments.mdx
The notices say segments are an "experimental feature", but with 4.13, they are now GA. These changes update the docs to match that.
=> docs: update segments availability notices

website/docs/sdks/python.md
This PR updates the Python documentation to remove examples using `default_value`, which has been obsolete for a while. As a replacements, it shows examples using the `fallback_function` kwarg instead.
Based on the changes suggested and introduced in #1582 and https://github.com/Unleash/unleash-client-python/pull/207.
=> docs: update python.md re: fallback function / default values

README.md, website/docs/sdks/index.md, website/docs/sdks/proxy-react.md, website/docs/sdks/proxy-svelte.md, website/docs/sdks/proxy-vue.md, website/docs/sdks/unleash-proxy.md, website/docs/user_guide/quickstart.md
Also re-ordered them and made them more consistent on the `bootstrapping` section.
=> docs: add svelte and vue front-end SDKs

website/docs/reference/segments.mdx
This change adds the new segments explainer video to the Segments documentation. It also fixes some formatting that prettier was unhappy with and does some minor restructuring of the segment capability list.
=> Docs: add segments explainer video + fix formatting

src/test/e2e/api/client/segment.e2e.test.ts
I had a test named `should send all segments that are in use by feature` failing, because expected was [1,2] and actual was [2,1].
In reality the order of ids should not matter, so test should ignore the ID order.
Fixed it with this PR.
=> Fix failing segment test

.eslintignore
Docker folder was added to project couple days ago.
Intellij was giving me linting errors for `index.js` in `docker` folder. 
```
/home/jaanus/Git/unleash/docker/index.js
0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
```
I am guessing we dont need to lint it. So added it to `.eslintignore` file.
=> Removed docker folder from linting

.dockerignore, Dockerfile, docker/package.json, docker/yarn.lock, package.json
This changes the unleash-server node module to be as little as it can,
resulting in a much smaller docker container. From 383M -> 11M.
=> feat: slim down docker container

src/lib/db/feature-toggle-client-store.ts
This PR fixes a bug where empty row appeared in features list. 
`FULL OUTER JOIN` was joining null rows and after joining segments, that were not linked to any features, empty row appeared.
Fixed it by replacing it with `LEFT JOIN`, which allows all features to appear, but only shows segments, that are linked to features.
=> Fix an empty row appearing in features list

src/lib/db/feature-toggle-client-store.ts, src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts
We discovered a bug, where features query from database is broken and returning empty rows. 
**It was hidden for some time due to accidental code, that removed the empty rows.**
This PR contains following:
1. Outer join replaced with left join, which helps to not create empty rows.
2. Also added test that no rows will be returned, when there is segment that is not linked to any features.
=> Fix features returning empty row

website/docs/user_guide/activation-strategies.md
Fixing a typo in `Multiple activation strategies` section
Removes necessary article in paragraph
=> Update activation-strategies.md | Fixing a typo in "Multiple activation strategies" section

src/lib/services/playground-service.ts, src/test/e2e/api/admin/playground.e2e.test.ts
This PR fixes a bug in the playground, wherein variants on toggles with constraints on the context would show as the disabled variant.
This happened because the `getVariant` call didn't receive the provided context as an argument. This has now been rectified and a test added.
The two main changes are:
1. Add a test for variant values with constraints
2. Pass the context into the `getVariant` call.
I also took the opportunity to switch from using the raw string `'*'` to using the constant `ALL` in the test suite. While they have the same value for now, they might change in the future. This should make keeping the tests up to date easier.
This was discovered during internal testing of the playground feature.
=> fix: Playground variants don't show correctly

website/docusaurus.config.js, website/package.json
This PR updates docusaurus to the most recent 'stable' version (well, at least it's not a beta anymore, right? 😅).
In addition to just updating the packages, it also requires adding an algolia app ID as [described in this migration guide](https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration#upgrading-your-docusaurus-site). As also mentioned in the guide, app IDs 'are not secrets and can be added to your Git repository'.
Further, the PR also updates the minimum required node version to run this. This is due to some of the changes in docusaurus requiring at least 16.14 to function.
Supersedes #1398.
=> docs: Update docusaurus to 2.0.0-rc.1

src/lib/openapi/spec/playground-feature-schema.test.ts, src/lib/openapi/spec/playground-feature-schema.ts, src/lib/openapi/spec/playground-response-schema.test.ts, src/lib/openapi/spec/playground-response-schema.ts, src/lib/services/playground-service.ts, src/test/arbitraries.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/e2e/services/playground-service.test.ts
This PR adds all variants that exist on a feature toggle to the playground payload for that toggle.
Being able to see which variant a feature has received is nice, but it would be more helpful if you could also see what other variants exist for that toggle and how they are weighted or overridden.
Because this PR changes the output of the playground API, most of the changes are to schemas related to that API. There are also updates to arbitrary generators for related property tests and to the snapshot of the openapi schema.
Additionally, this PR removes some of the additionalProperties: false annotations on some of the existing schemas. This is done so that the schemas can be extended via OpenAPI's 'allOf' property as documented in [the swagger docs on polymorphism and …
=> feat: add all feature variants to the playground payload

src/lib/db/event-store.ts, src/lib/services/setting-service.ts, src/lib/services/user-service.test.ts, src/lib/types/events.ts, src/test/e2e/api/auth/reset-password-controller.e2e.test.ts, src/test/e2e/services/reset-token-service.e2e.test.ts, src/test/e2e/services/setting-service.test.ts, src/test/e2e/stores/event-store.e2e.test.ts
https://linear.app/unleash/issue/2-11/changing-sso-settings-does-not-appear-in-event-log
This PR at least adds SettingCreated, SettingUpdated and SettingDeleted events. However, it does not reveal the data, since we can't know what data for our generic settings table is sensitive.
=> task: Add events for setting-service

src/lib/metrics.test.ts, src/lib/metrics.ts, src/lib/services/client-metrics/instance-service.test.ts, src/lib/services/client-metrics/instance-service.ts, src/lib/types/events.ts
So I know we have this in the database, but it's come up a couple of times in user discussions where the user asks how they're supposed to keep track of which SDK versions are being used. I don't think we currently expose a top level sdk version usage, so you need access to the database to do your own queries for figuring out which sdk version strings the server has seen.
This PR exposes this as a prometheus metric.
I'm a tad worried about the cardinality of this metric, but I've at least made sure that a client registration needs to include an sdkVersion field in the format `<sdkName>:<sdkVersion>`. So as to not accept anything into the labels for the metric. 
Maybe it would be better to parse the <sdkVersion> using the semantic library and then use major, minor, patch as separate …
=> task: add sdk version metric

src/lib/routes/health-check.test.ts, src/lib/routes/health-check.ts
To avoid our health check failing due to the db pool being busy, this PR makes the health endpoint simply return `200: { "health": "GOOD" }`.
We've been using this for our hosted version for quite some time, since hard errors still restarts the process, we don't need to check the database connection every 10 seconds.
=> task: update health endpoint to only say if express is ready

src/lib/db/group-store.ts, src/lib/services/group-service.ts, src/lib/services/project-service.ts, src/lib/types/group.ts
Implemented `changeGroupRole` instead of using general access method, because access method was using merge, which doesnt play nicely with our primary keys.
=> Implement group access edit for project

src/lib/db/feature-strategy-store.ts, src/lib/openapi/index.ts, src/lib/openapi/spec/__snapshots__/set-strategy-sort-order-schema.test.ts.snap, src/lib/openapi/spec/set-strategy-sort-order-schema.test.ts, src/lib/openapi/spec/set-strategy-sort-order-schema.ts, src/lib/routes/admin-api/project/features.ts, src/lib/services/feature-toggle-service.ts, src/lib/types/stores/feature-strategies-store.ts, src/test/e2e/api/admin/project/features.e2e.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/fixtures/fake-feature-strategies-store.ts
Co-authored-by: Fredrik Strand Oseberg <fredrik.no@gmail.com>
* Adds an endpoint that allows you to change the sort order of strategies
* Uses the UPDATE_FEATURE_STRATEGY permission
* Is tested in features.e2e.test.ts
=> Strategy sort order endpoint

package.json, yarn.lock
Fixing modules is being flagged as malware https://github.com/Unleash/unleash-docker/issues/74
Because of postinstall script of a dependency printing out a message to users in Russian time zones. https://github.com/medikoo/es5-ext/issues/116
Relevant to https://github.com/medikoo/es5-ext/issues/186 ("package being detected as a virus")
=> fix: force resolution of es5-ext

src/lib/openapi/spec/update-user-schema.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
So, currently you're not allowed to update users due to openapi validation breaking on additional unkown fields.
=> fix: Make additionalProperties true

package.json, src/lib/middleware/session-db.ts, yarn.lock
As the commit message said, ts-expect-error now errors since we now longer have a type checking error
=> fix: Remove unneeded ts-expect-error now that types in knex are in sync

src/lib/util/feature-evaluator/client.ts, src/lib/util/offline-unleash-client.test.ts
This PR changes how the Playground treats the 'application hostname' strategy. In short, it makes the playground evaluate it like any other strategy it doesn't know about.
The hostname strategy will not work correctly with the playground because it depends on external state. In its constructor, it tries to query the environment or use the `os.hostname` function to determine what its current hostname is. This means that no matter what the user does in the playground, they can’t affect the results of this strategy. It’s also unlikely that it will be true. And if it is, it probably won’t be true for their clients.
In theory, we could accept a hostname property on the Unleash context and use the provided hostname in the address. However, I’m afraid that it’ll make users think that they can …
=> Feat(#1873): return 'unknown' for application hostname strategies

src/lib/openapi/util/standard-responses.ts
Adding new standard errors that are used widely across multiple endpoints. This should help improve OpenAPI documentation
Relates to:  https://github.com/Unleash/unleash/issues/1391
409 is also being used for things like wrong status: `ProjectWithoutOwnerError`
=> feat: add new standard errors

website/docs/how-to/how-to-use-custom-strategies.md, website/docs/user_guide/quickstart.md
This PR removes references to the deprecated configuration option `proxySecrets` from all code samples in the documentation.
The config option was superseded by `clientKeys` a while ago, but it turns out we forgot to update some of the docs. This PR fixes the remaining code samples.
=> docs: remove references to deprecated proxy config variable

website/docs/advanced/impression-data.md, website/docs/sdks/index.md
Updated the compatibility table for php, `namePrefix` and `tags` filters and IP CIDR syntax were added some time ago, impression data just today (not released yet but will be during today, more specifically after https://github.com/Unleash/unleash-client-php/pull/104 gets merged).
- Will the global segments be added to the compatibility table? If so, should it be added as part of this PR or a separate one?
=> Docs: Update compatibility matrix for php

website/docs/advanced/impression-data.md
This PR provides a little bit of polish/maintenance/upkeep on the impression data reference doc:
I don't think we need the extra caution under the "example setup" section, so I've removed that.
I've also applied some formatting and added some minor rewording changes.
=> Docs: remove extra warning from impression data doc

src/lib/db/project-store.ts
This PR fixes the **slowest query in Unleash** (the average execution time on specific client was **~171ms**, where normal time would be 5-10ms), which is
```
SELECT count(DISTINCT "user_id") AS "members"
FROM "role_user"
WHERE "role_id" in
(SELECT DISTINCT "role_id"
FROM "role_permission"
WHERE "project" = 'default')
LIMIT 1
```
There is interesting thing happening, the **inner query** is querying **project** column, but the column does not exist in that table. So through some magic, Postgres seems to make it work through **SubPlans**. This means that the inner query will be ran for every row in parent query. This makes the query with a big cost of **~31.35**.
```
"Limit  (cost=31.35..31.36 rows=1 width=8)"
"  ->  Aggregate  (cost=31.35..31.36 rows=1 width=8)"
"        ->  Seq Scan on …
```
=> Fix Project members SQL query performance issue

src/lib/util/offline-unleash-client.ts
Our type says that variants should always exists as an array, but we have bad data in some instances where variants may be set to null if they were created before we fixed it in a previous release. This checks that feature.variants exists before mapping over it.
It remains to be discussed if we can should the underlying data with a migration.
=> fix: check variants before mapping

src/lib/db/api-token-store.ts, src/lib/openapi/spec/__snapshots__/api-token-schema.test.ts.snap, src/lib/openapi/spec/api-token-schema.test.ts, src/lib/openapi/spec/api-token-schema.ts, src/lib/routes/index.ts, src/lib/schema/api-token-schema.test.ts, src/lib/schema/api-token-schema.ts, src/lib/services/api-token-service.ts, src/lib/types/models/api-token.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/fixtures/fake-api-token-store.ts
Allow for creating new type of token for client-side API access. Add test coverage for it.
Relates to roadmap item: #1875
=> Feat: Create frontend API key

src/lib/middleware/api-token-middleware.ts, src/lib/schema/api-token-schema.test.ts, src/lib/schema/api-token-schema.ts, src/lib/services/api-token-service.test.ts, src/lib/services/api-token-service.ts, src/lib/services/proxy-service.ts, src/lib/types/models/api-token.ts, src/lib/types/permissions.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/e2e/api/proxy/proxy.e2e.test.ts, src/test/fixtures/fake-api-token-store.ts
Rename `PROXY` key to `FRONTEND` key
Relates to roadmap item: #1875
=> Refactor: rename frontend api key

src/test/e2e/api/admin/feature.e2e.test.ts
Multiple tests use `faker.lorem.word()` to create tag values. If they happen to pick the same `word`, they may fail. 
Ideally the tests would clean up after themselves. For now we can use values that are less likely to collide.
=> fix: attempt to unflake the feature e2e tests

src/lib/services/access-service.test.ts, src/lib/services/access-service.ts
Role validation only requires id and environment from each permission to validate, but `IRoleCreation` refers to `IPermission` that has other mandatory fields. This should help create more accurate OpenAPI specs where we use this method from an API
=> chore: type improvements

src/lib/proxy/proxy-repository.ts, src/test/e2e/api/proxy/proxy.e2e.test.ts
Admin tokens have `"*"` as their environment, which must be resolved.
=> fix: resolve correct environment for admin tokens

src/lib/routes/admin-api/api-token.ts, src/lib/services/proxy-service.ts
When a proxy key gets deleted, we should also remove its proxy client.
=> fix: clean up proxy clients on API key deletion

src/lib/openapi/util/standard-responses.ts
Add a standard error used when the user has not enough privileges to execute an operation
=> docs: add more standard errors

src/lib/services/project-service.ts, src/test/e2e/services/project-service.e2e.test.ts
We've been having a couple of problems with our event store not being able to save events, due to createdBy being `null`. We've even had comments telling us to remove the optional nature of these arguments. 
This PR makes these arguments (createdBy, modifiedBy) non-nullable/compulsory, we'll just have to fix enterprise once we've merged and released this.
That should solve these instances of our EventStore not being able to save the events.
=> fix: enforce non-nullability for createdBy/modifiedBy arguments

src/lib/app.ts, src/lib/middleware/api-token-middleware.ts
Since we are mounting the current proxies under the following paths:
* /clientId/api/environment/proxy
And the current clientKeys are being migrated to frontend keys, we need to amend the api-token middleware to get access to the new endpoints.
#1875
=> fix: proxy api check

frontend/src/component/App.tsx, frontend/src/component/providers/SWRProvider/SWRProvider.tsx, frontend/src/hooks/api/getters/httpErrorResponseHandler.ts, frontend/src/utils/apiUtils.ts
We currently handle login redirects in both `SWRProvider` and `ProtectedRoute`. The latter should be enough.
Also removes some API retry logic that I don't think we'll need.
=> refactor: simplify login redirect logic

frontend/src/component/feature/FeatureStrategy/FeatureStrategyEnabled/FeatureStrategyEnabled.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx
Ensures that `FeatureStrategyEnabled` uses fresh feature data, and not what's cached in the form.
https://linear.app/unleash/issue/1-199/the-general-message-inside-strategies-if-feature-toggle-is-enabled-in
=> fix: avoid stale feature strategy enabled status message

frontend/src/component/events/EventLog/EventLog.tsx, frontend/src/hooks/api/getters/useEventSearch/useEventSearch.ts, src/lib/db/event-store.ts, src/lib/openapi/spec/events-schema.ts, src/lib/routes/admin-api/event.ts, src/lib/services/event-service.ts, src/lib/types/events.ts, src/lib/types/stores/event-store.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/fixtures/fake-event-store.ts
This PR adds a totalEvents counter to the responses on the events endpoints. I think it should be fine, seems to add 1-2ms to response time when testing locally. Part of standardising list pages to include counts
=> feat: add count to event list

frontend/src/component/feature/CreateFeatureButton/CreateFeatureButton.tsx, frontend/src/component/feature/CreateFeatureButton/useCreateFeaturePath.ts
Closes https://linear.app/unleash/issue/1-72/missing-the-lock-icon-and-the-tooltip-on-the-feature-toggles-page
=> refactor: use permission button for new toggle

frontend/src/component/feature/FeatureStrategy/FeatureStrategyEmpty/FeatureStrategyEmpty.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx, frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsStats/FeatureMetricsStats.styles.ts, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.styles.ts, frontend/src/themes/dark-theme.ts, frontend/src/themes/theme.ts, frontend/src/themes/themeTypes.ts
https://linear.app/unleash/issue/1-188/environment-cards-ui-adjustments
- Removed the padding from the environment cards
- Removed the background color for the Exposure boxes
- Make these two buttons for new (first) strategy equal
=> fix: toggle strategies ui adjustments

frontend/src/component/feature/StrategyTypes/StrategyParameter/StrategyParameter.tsx
There was an inconsistency on custom strategy parameter input. Some values where trimmed, some not, and value sent to server was different from the contents of an input field.
https://linear.app/unleash/issue/1-144/custom-strategies-required-params-can-introduce-empty-space-at-the-end
=> fix: strategy parameters - trim string value

src/lib/db/environment-store.ts, src/lib/metrics.ts, src/lib/types/stores/environment-store.ts, src/test/fixtures/fake-environment-store.ts
As an attempt from our Customer Success representatives, we'd like to keep track of how much use of our Pro/Enterprise features our customers are making. This PR adds number of environments as a metric (we already had number of projects). If we have users that have more than 2 environments, this will tell us they're using an upgraded feature.
=> Add a counter for total number of environments

website/docs/sdks/index.md
The doc link appears to have pointed at an address that is no longer reachable. Instead, let's point to the equivalent GitHub link
Relates to and closes #2047
=> Fix symfony link

.github/workflows/release_changelog.yml
When merging `frontend` and `backend` we kept all the commits. This meant all `frontend` commits were added to this repository.
This brought up an issue, where release notes started failing, because the release notes included the whole history of `frontend`.
To bypass this, we disabled `backend` release notes until a minor release was done, which was 4.15.
Now we can reenable the full release notes. **This PR reverts the workflow to initial state.**
=> Revert workflow

src/lib/services/api-token-service.ts
This method is necessary to add because we're migrating the proxy keys in unleash cloud and we have instances with proxies enabled for environments that might be disabled. The current method will throw a bad data error in this instance, because we do not allow you to create API token for disabled environments. Caused by this line: https://github.com/Unleash/unleash/pull/2056/files#diff-c7747d86059ec3422885e79411b8ef7323c0804df081c110268dd3250ace3696R167
This is a useful validation to have, but in this instance it's blocking a migration that needs to happen regardless of whether or not the environment is disabled, because we might have users that have added configuration and are actively using that configuration in environments that have later been disabled.
=> feat: add method for migrating proxies without environment validation

src/lib/openapi/spec/validate-edge-tokens-schema.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
This change fixes the description of the 'tokens' array of the validate edge tokens schema.
The source of the error was a simple inverson of anyOf and items.
Swap `anyOf`and `items` ordering
So that the swagger editor and openapi tools don't complain about invalid schemas.
=> Fix validate-edge-tokens OpenAPI schema

.github/workflows/build_prs_jest_report.yaml
External builds are failing to upload coverage report
=> Update to pull_request_target

src/lib/routes/logout.test.ts, src/lib/routes/logout.ts, src/lib/routes/unleash-types.ts
This change introduces support for using `unleash-server` with passport version `0.6.0`. Currently logout from unleash-server fails with that version, due to a change in the API of the passport library for `req.logout`. Issue #1947 describes this in detail.
Closes #1947  .
The change is rather small. What should be noted though is a small change for the session handling. Passport >= `0.6.0` requires the session to still exist before `req.logout` is being called. Therefore I moved the session termination behind the logout.
=> Add support for `req.logout` with passport version 0.6.0 and onwards

src/lib/openapi/index.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/e2e/api/openapi/openapi.e2e.test.ts
Expose the current Unleash version in the generated OpenAPI docs, even when running via docker or other processes.
An OpenAPI spec without a version isn't valid. This causes some of our generation tools (such as the one for documentation) to fail.
By changing how we fetch the current version:
Previously, we used `process.env.npm_package_version!`. However, when you're not running with yarn or npm, this is `undefined`. That causes the version number to not be included when running tests and when running using the official docker image.
Instead, we now use `version` from `lib/util/version`. This is the same version as the one used by the UI config endpoint, so it should be the same one as what the front end displays. To the best of my knowledge, this _is_ the version of the API.
It _may_ be …
=> Fix(#1391): Expose API version even when not running via npm/yarn

src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/e2e/api/openapi/openapi.e2e.test.ts
remove the version from the received specification. The version _is_ a required field, but having the version listed in automated testing causes issues when trying to deploy new versions of the API (due to mismatch between new tag versions etc). That's why we remove it.
=> Refactor(#1391): don't check for OpenAPI version in snapshot tests

website/clean-generated-docs.js, website/docusaurus.config.js, website/package.json, website/yarn.lock
The cleaning script replaces all references to the Unleash ushosted instance in the generated OpenAPI docs. It removes extra path segments (such as leading `/ushosted` instances) and replaces the ushosted base url with something user-agnostic.
When we host the OpenAPI docs in our official documentation, the generated docs shouldn't necessarily point at _one specific instance_, and especially not one that the reader is unlikely to ever use. Instead, we can remove all the bits that are specific to the generation source we use, and make the docs easier to use. In particular, removing the leading `/ushosted` is likely to save us loooots of questions.
By adding a new dev dependency (`replace-in-file`) and running the script after doc generation. 
This PR also changes which environment variable …
=> #1391: add generated doc cleaning script

website/clean-generated-docs.js
This change fixes URLs in code samples for endpoints that don't start with /api. Most endpoints do, but there are some edge cases, such as the edge and auth endpoints that don't. This change makes sure that those code samples are also correct.
So that code samples don't present the wrong URL. That'd be really confusing to users.
By loosening one of the replacement regexes.
=> Fix(#1391): fix edge case URLs in code samples

frontend/src/component/admin/groups/Group/Group.tsx, frontend/src/component/admin/users/UsersList/UsersList.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx, frontend/src/component/project/ProjectAccess/ProjectGroupView/ProjectGroupView.tsx
When a user has never been logged in "last login: never" reads better
than "last login: Never logged".
=> fix: s/Never logged/Never/g in frontend

website/docs/user_guide/rbac.md
This PR moves the permissions section of the RBAC documentation and places it before the user groups section. The permissions section was originally a subsection of CPR, and that seems to be where it should remain.
The permissions section is a subsection of the CPR section and shouldn't be separated. This seems to have been an oversight.
---
That said, I'm happy to take input that says otherwise 😄
=> docs: Move user groups section to after permissions section

src/lib/routes/index.ts, src/lib/routes/logout.test.ts, src/lib/routes/logout.ts, src/lib/services/user-service.ts, src/test/e2e/api/admin/user-admin.e2e.test.ts
To ensure we clean up sessions on logout this PR does two things:
1. When users changes password, it deletes all sessions for user
2. When logging out, it deletes all sessions for user, not just the current one in the request.
Will add a test before moving from draft
=> fix: deletes all sessions for user on logout

src/lib/openapi/spec/create-api-token-schema.ts
This change reverts the spec change to create-api-token-schema that was introduced in 97c2b3c089c29c79f97b30a2417333efcd4f631c
That commit changed the endpoint from allowing any string to only allowing strings that match the values of the ApiTokenType value.
Because we already validate this on the backend, I didn't think it would break anything. However, because OpenAPI enums are case sensitive (and do not currently support anything else), it _did_ break the API. ([stack overflow post that explains how this works](https://stackoverflow.com/questions/60772786/case-insensitive-string-parameter-in-schema-of-openapi))
This should have been caught by the tests, but it didn't show up until it was merged to the main branch. I think it might be worth looking into how we do the PR testing.
=> fix: Revert breaking change for incoming token creation reqs

src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
Seems to be related to https://github.com/Unleash/unleash/pull/2084, OpenAPI spec was changed but new snapshot was not generated.
=> Fix openapi snapshot so tests will not fail

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/db/public-signup-token-store.ts
There is a problem with the return object when inserting the public-signup-token in the db: The connection to `roles` table is not fetched
Solved by calling `get` after insert so that all the db table joins are used
Closes # .
=> fixed missing role by calling get after insert

src/lib/metrics.test.ts, src/lib/metrics.ts
Client registration events are on eventStore and not on eventBus. This change makes us have sdk name and version metrics in unleash.
=> fix: client registration events are on eventStore

website/docs/reference/front-end-api.md
This change fixes a broken link to front-end API tokens from the front-end API page. The anchor had changed
=> docs(fix): fix broken link to front-end API tokens

src/lib/db/feature-strategy-store.ts
Currently the query to list featureStrategies is only sorted by sortOrder.  
When we create feature strategies the sort order is not specified.
This creates a bug where editing any other than the first feature strategy, moves it to the top of the list.  Essentially being sorted by updated_at (since sort order is not defined,  all the feature strategies have the same value for sort order)
Fix: Sort by createdAt before sorting with sortOrder in store
Closes # .
=> sort feature strategies by created_at first and then sort_order

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/app.ts, src/lib/metrics.test.ts, src/lib/metrics.ts, src/lib/middleware/response-time-metrics.ts, src/lib/types/experimental.ts, src/server-dev.ts
This small fix adds a appName label to the `http_request_duration_milliseconds` Prometheus metrics. It is taken from the `unleash-appname` header, used by all official Unleash SDKs. This makes it easier to debug chatty applications.
=> fix: add appName to http response time metrics

src/lib/db/project-store.ts
The project name was being used in the query and was being mapped with `id` to get the `memberCount` which resulted in wrong counts
Closes #2123
=> fix: use correct column name for correct member count

frontend/src/component/strategies/StrategiesList/StrategiesList.tsx
Simple accessor change to use the `formatStrategyName(row.name)` string, the same string we are using to render the cell.
Closes #2129.
=> fix: strategy name sort

website/docs/advanced/strategy-constraints.md, website/docs/how-to/how-to-add-strategy-constraints.md, website/docs/how-to/how-to-define-custom-context-fields.md, website/docs/user_guide/unleash-context.md, website/docusaurus.config.js, website/src/css/custom.css
This PR updates the docs with the new constraints availability changes introduced by #2112
It also adds a little (dismissable) banner at the top of the docs that announce this change.
To keep the docs up-to-date with what's actually available.
=> docs: Update docs with new constraint availability

README.md
This adds a short section on Unleash migration and a link to the migration guide to the readme.
There was some concern that the readme was too focused on new users and that existing users (especially ones who are still on v3) might not find what they need. To try and make their life easier, this PR adds a short section on upgrading and migrating and links to the official guide.
=> docs: add link to migration guides

frontend/src/component/project/Project/ProjectInfo/ProjectInfo.tsx, frontend/src/component/project/ProjectCard/ProjectCard.tsx
As discussed, for now we will remove member count from default project, because default project is special compared to other projects. Access tab is not available to them and members can not be added or removed
=> Remove member count for default project

src/lib/routes/admin-api/project/features.ts, src/lib/services/feature-toggle-service.ts, src/lib/services/index.ts, src/lib/types/stores/access-store.ts, src/lib/util/feature-evaluator/helpers.ts, src/test/e2e/api/admin/project/features.auth.e2e.test.ts, src/test/e2e/api/admin/project/features.e2e.test.ts, src/test/e2e/services/access-service.e2e.test.ts, src/test/e2e/services/api-token-service.e2e.test.ts, src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts, src/test/e2e/services/playground-service.test.ts, src/test/e2e/services/project-health-service.e2e.test.ts, src/test/e2e/services/project-service.e2e.test.ts
This makes it easier for the user to enable a feature in an env, simplifying UI and reduces number of steps. 
**Before:**
**After:**
=> fix: auto add stratgy when enabling empty env.

src/lib/db/project-store.ts
Previously project member count relied on this logic:
```
1. Exclude global admin and global viewer
2. Include everyone that is on the access tab , whether is user or group
3. Include global editor  ( from role_user, role_id 2)
```
This PR removes simplifies the logic. Global roles are not counted at all. The rules is following
```
1. Include everyone that is on the access tab , whether is user or group
```
=> Update how project member count works

frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.tsx, frontend/src/component/feature/FeatureStrategy/featureStrategy.utils.ts, frontend/src/hooks/useCollaborateData.tsx
When we added equality checks on feature strategies, we failed to account for the fact that `lastUpdatedAt` will update on the feature toggle every time an SDK has asked for that feature. This triggers the stale data notification, because the feature toggle has in fact changed, but not in any meaningful way. Furthermore, it will trigger on every polling interval, which can be annoying for the user. 
This adds a formatter to the hook that allows you to decide how the data should look before performing the equality check.
Closes # .
=> fix: equality check on feature strategy

src/lib/db/pat-store.ts, src/lib/openapi/spec/pat-schema.ts, src/lib/routes/admin-api/user/pat.ts, src/lib/services/pat-service.ts, src/lib/types/models/pat.ts, src/lib/types/stores/pat-store.ts, src/migrations/20221010114644-pat-auto-increment.js, src/test/e2e/api/admin/user/pat.e2e.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/fixtures/fake-pat-store.ts
Previously primary key was secret, which should not be shared after creation. This creates a need for new primary key, which will be serial number.
=> Change PAT primary key from string to number

frontend/src/component/user/Profile/PersonalAPITokensTab/CreatePersonalAPIToken/CreatePersonalAPIToken.tsx, frontend/src/component/user/Profile/PersonalAPITokensTab/DeletePersonalAPIToken/DeletePersonalAPIToken.tsx, frontend/src/component/user/Profile/PersonalAPITokensTab/PersonalAPITokenDialog/PersonalAPITokenDialog.tsx, frontend/src/component/user/Profile/PersonalAPITokensTab/PersonalAPITokensTab.tsx, frontend/src/hooks/api/actions/usePersonalAPITokensApi/usePersonalAPITokensApi.ts, frontend/src/interfaces/personalAPIToken.ts
https://linear.app/unleash/issue/2-315/adapt-front-end-to-use-id-instead-of-secret-for-the-pats
=> fix: PAT secret no longer returned (except new), use id instead

website/docs/sdks/unleash-proxy.md
This change adds a note to the custom activation strategies section of the proxy docs, clarifying that the hosted proxy can not use custom activation strategies.
We had a customer asking whether this was possible and realized it's not stated explicitly anywhere.
=> docs: add note about custom activation strats in hosted proxies

frontend/src/component/project/Project/Project.tsx, frontend/src/component/project/Project/ProjectLog/ProjectLog.styles.ts, frontend/src/component/project/Project/ProjectLog/ProjectLog.tsx
Adding Event log tab to Project view to show all events within a project at one place
Closes #2060
Initially thought that a new `useProjectEvents` would be needed, but getting onto the code realised, it might not be. The current `useEventSearch` hook relies on the common event API and if a feature isn't passed to that it provides all project-level events. Just adding a new component and tab on the Project view seemed to work. Tested it with a few cases of search and multiple toggles and projects, seemed to work fine. Not sure if this is all that was needed
=> feat: add event log to project

frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx, frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx, frontend/src/component/admin/auth/SsoGroupSettings.tsx, frontend/src/interfaces/uiConfig.ts, src/lib/__snapshots__/create-config.test.ts.snap, src/lib/types/experimental.ts, src/server-dev.ts, src/test/config/test-config.ts
Adds front end properties to the OIDC and SAML pages to allow group syncing to be turned on or off by the user. Requires related PR in enterprise to actually save the settings
=> feat: Add group sync settings to front end

website/docs/reference/feature-toggles.mdx
This change adds a the min and max lengths allowed for a feature toggle name to the feature toggle docs.
As was mentioned in #2185, this isn't documented anywhere as of today, making it a potentially surprising issue to come across.
=> docs: Document the min and max lengths of a feature name.

frontend/src/component/admin/users/InviteLink/InviteLink.tsx, frontend/src/hooks/usePlausibleTracker.ts
Proper link to documentation on "invite link" page.
=> fix: invite link page docs

frontend/package.json, frontend/yarn.lock
Seems like some `codemirror` dependencies were requesting @codemirror/state v6.1.1 while others requested v6.1.2 - This PR adds a resolution so we use `6.1.2`, fixing the issue.
=> fix: sandbox codemirror/state 6.1.2

src/lib/routes/client-api/metrics.test.ts, src/lib/services/client-metrics/last-seen-service.ts, src/lib/services/client-metrics/metrics-service-v2.ts, src/lib/services/index.ts, src/lib/types/services.ts, src/test/e2e/api/client/metricsV2.e2e.test.ts, src/test/e2e/services/last-seen-service.e2e.test.ts
This PR fixes two things related to lastSeen details for feature toggles.
1. Only update lastSeen when `yes` or `no` count is larger than 0. 
2. Allow batching of lastSeen updates, hidden behind feature flag named `batchMetrics`. With the flag enabled lastSeen will only be updated every 30th second. 
fixes: #2104
=> fix: filter empty metrics before we collect last seen toggles.

website/docusaurus.config.js
This change updates the details used for the doc search integration we use.
Algolia has migrated to a new doc search platform. The old credentials still work, but the crawlers stopped working months ago. This is why new articles don't show up in the search at all.
This update _should_ allow us to update our indices and get search working properly again.
=> docs: update appId and apiKey to new DocSearch

src/lib/proxy/create-context.test.ts, src/lib/proxy/create-context.ts, src/lib/routes/proxy-api/index.ts, src/test/e2e/api/proxy/proxy.e2e.test.ts
This PR fixes an issue with the new frontend API where we would override environment set on the context to what the environment of the API key was. This will break feature toggles for older users of unleash because some might still be using the deprecated environment field on the SDKs.
Closes # .
=> fix: respect environment if set on context

src/lib/db/project-store.ts, src/lib/services/feature-toggle-service.ts, src/lib/services/state-service.ts, src/lib/types/stores/project-store.ts, src/test/e2e/api/admin/state.e2e.test.ts, src/test/examples/import-state.json, src/test/fixtures/fake-feature-environment-store.ts, src/test/fixtures/fake-project-store.ts
Should fix the issue https://github.com/Unleash/unleash/issues/2186.
Changes:
1. When importing **featureEnvironments**, it created `feature_environments` always, now only if `project_environments` exists(is enabled).
2. When importing **projects**, it created a `project_environment` only for default project, now creates a `project_environment` for each new project and environment that is new.
=> Import of feature still showing env on feature, when environment is disabled on project

.lycheeignore
Instagram started to throttle us (i.e. #2248). Links that are well known such as our Instagram page, don't need to be checked every time. By explicitly ignoring the correct link we reduce noise but at the same time we continue checking other Instagram links that may help us identify a typo
Closes #2248
=> docs: remove instagram url from link checker

package.json, yarn.lock
Just to use a non-beta version https://www.npmjs.com/package/@unleash/express-openapi?activeTab=versions no changes from v0.2.1-beta.0 meaning that the [change we were testing](https://github.com/Unleash/express-openapi/pull/5) is stable now
=> chore: Use last version of @unleash/express-openapi

src/lib/db/suggest-change-store.ts, src/lib/types/model.ts, src/lib/types/stores/suggest-change-store.ts, src/test/fixtures/fake-suggest-change-store.ts
This PR adds two endpoints to suggest change
1. Update status of change set
2. Get all change sets per project that are not drafts
=> Suggest change - update status and get per project

src/lib/openapi/util/openapi-tags.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
This change adds a new Segments tag to the list of valid OpenAPI tags.
When updating tags for the enterprise version of Unleash, I realized we didn't have any tags that were appropriate for the segments endpoints.
=> OpenAPI(feat): add new 'Segments' tag

.github/workflows/build.yaml
When the commit message has a single quote `'`, it breaks our curl command that encloses the request body between single quotes. A similar issue was reported in https://github.com/actions/runner/issues/1656 and the suggestion is to use an environment variable that when used in bash will use bash's built-in escaping of env variables that should help us here as well.
For testing purposes the title of the PR includes also a single quote
=> fix: escape single quotes ' for curl

website/docs/api/internal/internal-backstage-api.md
Prometheus metrics should not be exposed to the public. Added a note about this to inform people that internal endpoints should be dropped on external access. 
https://unleash-community.slack.com/archives/CGP2MCHPF/p1666688295670459
=> [docs]: Update Prometheus docs with security info

frontend/src/component/common/PrettifyLargeNumber/PrettifyLargeNumber.test.tsx
We recently accepted a PR that includes some tests to prettify large numbers in the front end project. However, these tests are not locale independent and so fail on machines where the number separator is not a comma. This patches those tests to rather check that the length of the output string matches the expected length i.e. that the input strings have had a separator injected into them.
This doesn't touch the tests that use millify for the number formatting. Since we don't set any options on the millify function itself, this should be locale independent already (possibly something to talk about in future). 
I'm not 100% we actually want to keep these tests but if we do this is an option to preserve the logic while keeping them locale independent.
=> make prettify large number tests independent of locale

frontend/src/component/environments/EnvironmentTable/EnvironmentActionCell/EnvironmentCloneModal/EnvironmentCloneModal.tsx
https://linear.app/unleash/issue/2-371/small-ui-fixes-on-the-clone-environment-modal
UI/UX requests to make the flow a bit more understandable at a quick glance:
- Change the "Generate an API token later" label to "I want to generate an API token later";
- Show the "Generate an API token now" secondary description even if that option is not selected;
Goes against the change we made in https://github.com/Unleash/unleash/pull/2245#discussion_r1007697439 - But that's a conscious decision from UX to make the options more distinct at a quick glance.
=> fix: small UI fixes to the clone environment modal

frontend/src/component/segments/SegmentEmpty/SegmentEmpty.tsx
https://linear.app/unleash/issue/2-360/segments-bug
=> fix: only show link to create segment if you have permission

src/lib/services/email-service.test.ts, src/lib/services/email-service.ts
Currently it is possible to send links through emails to users during invitation.
As a workaround, we will start stripping special characters from name, but still leaving language specific letters.
=> Hyperlink Injection in People Invitation Emails

frontend/src/hooks/api/actions/useUiConfigApi/useUiConfigApi.ts
Fix a small UI bug that incorrectly formats the API url, making the CORS update fail when "baseUriPath" is configured.
=> fix: remove duplicate formatApiPath in userUiConfigApi hook

frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx, frontend/src/component/changeRequest/DraftBanner/DraftBanner.tsx, frontend/src/hooks/api/getters/useChangeRequestOpen/useChangeRequestOpen.ts, frontend/src/hooks/useChangeRequestToggle.ts
This is small PR that aligns with the latest API paths.
`/change-requests/draft` changed to` /change-requests/open`
=> Change request API draft to open

frontend/src/component/project/Project/Project.tsx
This PR adds a conditional to the Change Request Tab in Project so that it can be hidden when not enterprise
Closes #
=> Fix: Conditionally hide Change Requests tab

src/migrations/20221103125732-change-request-remove-unique.js
The unique constraint was too restrictive and we were not able to add multiple `addStrategy` or `editStrategy` actions.
=> Remove uniqueness from change requests merging

frontend/src/component/environments/EnvironmentTable/EnvironmentActionCell/EnvironmentCloneModal/EnvironmentCloneModal.tsx
Cloning an environment was creating a token every time, even when not choosing the respective option.
=> fix: clone environment creating token everytime

src/lib/routes/admin-api/project/features.ts, src/lib/services/feature-toggle-service.ts, src/test/e2e/api/admin/project/features.e2e.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
This PR fixes a bug where fetching a feature toggle via the `/api/admin/projects/:projectId/features/:featureName` endpoint doesn't validate that the feature belongs to the provided project. The same thing applies to the archive functionality. This has also been fixed.
In doing so, it also adds corresponding tests to check for edge cases, updates the 403 error response we use to provide clearer steps for the user, and adds more error responses to the OpenAPI documentation.
As mentioned in #2337, it's unexpected that the provided project shouldn't matter at all, and after discussions internally, it was also discovered that this was never intended to be the case.
It might be worth rethinking this for Unleash v5. Why does the features API need the projects part at all when features are …
=> Fix: validate that the project is correct when getting feature by project

website/docs/deploy/import-export.md
This change updates the availability notice and the code samples in the import/export docs.
Specifically, the code samples have been moved to using the ApiRequest component (and thus get examples in HTTP, cURL, and HTTPie), and the import code sample now says which version it's using (version 3).
The import code sample didn't say which version of the data it used, so Unleash would assume it was version 1 if you tried to run it. However, the actual data was incompatible with the v1 data format, so you'd get an error if you tried to actually import it.
While fixing this, I figured it'd also be alright to add some other minor updates to bring the docs a bit more up to recent standards.
=> docs: update export/import examples

src/lib/routes/admin-api/state.ts, src/test/e2e/api/admin/state.e2e.test.ts
This PR updates the `paramToBool` function to first check whether the incoming argument is a boolean. This fixes the bug where using `true` or `false` (e.g. `Strategies=false`) in the query would cause the server to crash.
I've also added a test case to check for these values.
While working on the import/export API docs, I noticed that using `false` in an export request caused the server to crash.
As we want to allow `true` and `false` (and use these values in the documentation), we should ensure that they work as expected.
It's likely that this bug was introduced when we added the new OpenAPI query parameters to the export endpoint. Because of the way that the OpenAPI service we use does conversion, we now get `true` and `false` converted to actual boolean values instead of strings. The …
=> Fix(export API): accept `true` and `false` as param values

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/create-config.test.ts, src/lib/create-config.ts
From Thomas and mine testing. BaseUriPath can't be set as an environment variable because we override it when trying to format the URI from the server config. This PR makes sure we only format if the custom server options actually have baseUriPath set.
=> If baseUriPath is set format it, but if it's not, don't override default with empty string

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx, frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx, frontend/src/component/changeRequest/ChangeRequestStatusBadge/ChangeRequestStatusBadge.tsx, frontend/src/component/changeRequest/DraftBanner/DraftBanner.tsx
* change request sidebar has a number of feature toggles affected and navigation to change request overview page
* fixing change request banner overflow
* adding draft banner
Please check if I'm doing navigation right
=> styling change request sidebar

frontend/src/component/playground/Playground/PlaygroundGuidance/PlaygroundGuidance.tsx
I have removed a lexical illusion lexical illusion in this guidance step, where "context field" was repeated.
Because it's unintended and doesn't make any sense in the the sentence.
=> fix: remove lexical illusion in playground guidance

frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx, frontend/src/component/common/SidebarModal/SidebarModal.tsx
Sidebar was stretched too wide. Not it's 50% of the screen.
Existing SidebarModal has a fixed width of 1300. It's not good for reusability. Since I don't want to touch all usages of the existing sidebar I added DynamicSidebarModal that has a width affected by its children. Both modals share most of the code.
=> fix sidebar width

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsChart/createChartOptions.ts, frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx
This PR does one thing, it sets the y-axis to start at "0" when showing request counts over time. 
fixes #2107
=> fix: set suggested min value to 0

website/docs/advanced/impression-data.md
This change updates the description of when impression events are fired to clarify that impression events are **not** fired in front-end SDKs if the toggle is enabled.
It also adds a 'caution' admonition repeating this information with some more info on why.
We've had a couple questions about this as it hasn't been clearly stated before. Additionally, I, as a member of the team and the original author of this document, thought that impression events **did** fire for disabled toggles in the front-end.
As such, I consider this to be unexpected and different from what was originally written.
=> Docs: Impression events only fire on enabled front-end toggles

src/lib/db/project-store.ts
Currently rows were returned as a list of promise, but we need to await for them.
=> Fix async issue

src/lib/openapi/endpoint-descriptions.ts, src/lib/routes/public-invite.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, website/clean-generated-docs.js
This change removes the use of double quotes in the 'addPublicSignupTokenUser' endpoint summary. It also changes the original summary to a description and adds a new, shorter summary.
The OpenAPI / docusaurus integration errors out (refer to [this failed build](https://github.com/Unleash/unleash/actions/runs/3434792557/jobs/5726445104)) if the frontmatter contains invalid characters. In this case, it's because the automatic sidebar label contains double quotes, which it interprets as a new key having been declared:
```
Error:  Error while parsing Markdown front matter.
This can happen if you use special characters in front matter values (try using double quotes around that value).
Error:  Loading of version failed for version current
Error:  Unable to build website for locale en.
Error: …
```
=> fix: Fix broken OpenAPI

frontend/src/hooks/useDragItem.ts
Fixes a small bug that caused the item to be draggable when clicking outside of the handle, when using a handle. Basically resets the draggable state when (re)entering the container.
=> fix: improve drag behaviour when using handle

src/lib/db/access-store.ts, src/lib/services/access-service.ts, src/lib/services/feature-toggle-service.ts, src/lib/types/stores/access-store.ts, src/test/fixtures/fake-access-store.ts
This PR adds permission guards for operations.
1. Toggling feature flag
2. Adding a strategy
3. Updating a strategy
4. Deleting a strategy
=> Permission guards in existing endpoints interacting with feature toggle configuration

frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyEmpty/FeatureStrategyEmpty.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/CopyStrategyIconMenu/CopyStrategyIconMenu.tsx, frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/StrategyList/StrategyItem/FeatureStrategyItem.tsx, frontend/src/interfaces/strategy.ts, src/lib/db/feature-strategy-store.ts, src/lib/openapi/spec/create-feature-strategy-schema.ts, src/lib/routes/admin-api/project/features.ts, src/lib/services/feature-toggle-service.ts, src/lib/services/segment-service.ts, src/lib/types/model.ts, src/test/e2e/api/admin/project/features.e2e.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
* This PR refactors segments to be directly added when creating or editing a strategy. Instead of making a separate call to the segments API, we directly accept a list of segment ids and apply them when we receive the edit / create call on the strategy. 
Discussion points: 
* To not break existing API, the segmentIds are optional. In the controller we default the segmentIds if they don't exist.
* There is some uglyness in this code, fixing it will be more invasive than I'd like in this PR. But something to look into for the future.
Closes #
=> feat: update strategy segments with edit / create strategy

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx, frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
By setting a fixed width in the tags column we can save some extra space.
=> fix: make the tags column have a fixed width

frontend/src/component/common/Table/cells/FeatureTagCell/FeatureTagCell.tsx
Search is already case insensitive, so it makes sense that the highlight style is as well.
=> fix: tags highlight case sensitivity

src/test/e2e/api/admin/instance-admin.e2e.test.ts
This test fails from time to time due to a race condition between the http statement and the creation of the new project.
Adding an await statement should fix this.
=> fix: flaky test on number of projects statistic

frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestConfiguration.tsx
Users w/o project update permission should not change number of approvers.
It was a tricky one. When I put the access context at the root level after page refresh it was broken.
The context has to be inside the cell component.
=> disable approvers select when no access

src/test/e2e/api/admin/project/features.e2e.test.ts
This test fails randomly, example: https://github.com/Unleash/unleash/actions/runs/3496006349/jobs/5853415518#step:5:376 
It's not so frequent but I tested locally one out of 4 or 8 runs fails because the rows returned are in the wrong order.
If the order of segments is relevant, we should look into how we're fetching them or applying a `sort()` before returning from the query. I've validated on my machine that even if the segments are sent in order, when pulled from the db sometimes they are processed in a different order
=> fix: flaky tests on segments order

src/lib/routes/admin-api/project/variants.ts, src/lib/services/feature-toggle-service.ts, src/lib/types/events.ts
Our EnvironmentVariant needs project name so this PR makes sure our service accepts the project id as one of the arguments.
=> fix: Updated event to include project

src/lib/services/feature-toggle-service.ts, src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts
This patches an issue where cloning a feature would clone variants for it's last found environment in the db. This now will clone the feature environments correctly
=> fix: force clone feature to correctly copy variant environments

src/lib/db/access-store.ts, src/lib/db/user-store.ts, src/lib/services/access-service.ts, src/lib/services/user-service.ts, src/lib/types/stores/access-store.ts, src/migrations/20221121133546-soft-delete-user.js, src/test/e2e/api/admin/user-admin.e2e.test.ts, src/test/e2e/services/user-service.e2e.test.ts, src/test/e2e/stores/user-store.e2e.test.ts, src/test/fixtures/fake-access-store.ts
Previously we hard deleted the users, but due to change requests and possibly other features in future, we really want to hard-link user table and have meaningful relationships.
But this means, when user is deleted, all linked data is also deleted.
**Workaround is to soft delete users and just clear users data and keep the relationships alive for audit logs.**
This PR implements this feature.
=> Add possibility to soft delete users

src/lib/services/feature-toggle-service.ts, src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts
Creating a strategy has been updated to also clone segments for Suggest Changes reasons, however, the code for cloning a toggle was not updated in tandem. This means that when cloning a feature toggle with a segment, the toggle would be created with a strategy and automatically get the segments copied across, then the promise chain would resolve and attempt to create the exact same segment a second time, which caused a write of a duplicate entry into the db on a set of columns that have a uniqueness constraint.
This PR removes the callback for handling the segment cloning, allowing the create strategy method to do it right the first time
=> fix: resolve an issue where cloning a feature toggle with a segment

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/app.ts, src/lib/create-config.ts, src/lib/middleware/cors-origin-middleware.ts, src/lib/routes/proxy-api/index.ts, src/lib/types/option.ts, src/test/e2e/api/proxy/proxy.e2e.test.ts, website/docs/reference/deploy/configuring-unleash.md
* This PR adds a configurable maxAge header to the CORS middleware. This allows the preflight request to be cached so that we can reduce the request load on our end for the frontend clients starting to utilise the frontend api.
=> fix: adds cors caching

frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/AddCommentField.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx, frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx, frontend/src/hooks/useChangeRequestsEnabled.ts
When ChangeRequests are disabled and we go to change request overview:
* disable review button
* disable approve button
* disabled add comment button
* disable cancel button
Also: fixed hook deps so that change request config is picked on feature toggles project list
=> disable change request overview actions when CR are disabled

src/lib/db/api-token-store.ts, src/lib/routes/admin-api/api-token.ts, src/lib/services/api-token-service.test.ts, src/lib/services/api-token-service.ts, src/lib/types/events.ts, src/test/e2e/services/api-token-service.e2e.test.ts
We need a way to have an audit log for operations made on Api Tokens. These changes add three new event types, API_TOKEN_CREATED, API_TOKEN_UPDATED, API_TOKEN_DELETED and extends api-token-service to store these to our event store to reflect the action being taken.
I'd love to have an discussion on the event format. 
I'm currently exporting the token (minus the secret) as data, and then using it as preData for deletion events and both preData and data in the update events.
Also, not too fond of the Omit use here, since if you pass in an object with the secret that will still be kept. Now I have tests in place for our current three places where we add these three events.
=> task: Make operations on the API Token store auditable.

src/migrations/.eslintrc
When adding a new migration, we might run out of memory. Migrations have only JS files and we're running these through TS parser. Removing TS config reference from `.eslintrc` proved to solve the issue while running local manual tests
This still lint the migration files but using JS syntax
Not sure if this is the best shape of our `.eslintrc` file
=> Fix OOM with eslint in migrations

frontend/src/component/common/HtmlTooltip/HtmlTooltip.tsx, frontend/src/component/common/ProFeatureTooltip/ProFeatureTooltip.tsx, frontend/src/component/common/TooltipResolver/TooltipResolver.tsx, frontend/src/component/project/ProjectList/ProjectList.tsx
Related: https://github.com/Unleash/unleash/pull/2544
From: https://linear.app/unleash/issue/1-414/add-a-badge-for-oss-users-on-the-projects-page-to-see-that-extra
Includes some fixes and suggestions:
- Should only show when OSS (icon was showing every time);
- Link now works correctly, opens on new tab;
- Improves styling to be more aligned with original design: https://www.figma.com/file/qdwpPfuitJUNinm6mvmCmG/Unleash-application?node-id=6961%3A38443&t=zsXNAnOurapoLm9j-0;
- Fixes text to be like in the design;
- Improves `HtmlTooltip` look and behaviour: white arrow, custom width, etc;
- Some refactoring and cleanup;
Let me know if I should change anything 👍
=> Fix plan upgrade tooltip

frontend/src/component/addons/AddonForm/AddonForm.tsx
https://linear.app/unleash/issue/2-408/addon-parameter-validation
=> fix: addon parameter validation on empty strings

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/AddCommentField.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/ChangeRequestComment.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx, frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
Adding change request tooltips for all user avatarts. 
There's an existing UserAvatar with native browser tooltip, but it's using some custom code instead of MUI tooltip and also makes too many assumptions about the user data structure.
=> change request tooltips

src/lib/db/api-token-store.ts, src/lib/services/api-token-service.ts
https://linear.app/unleash/issue/2-448/update-last-seen-column-for-api-tokens
=> Feat update token seen at

website/docs/contributing/ADRs/front-end/preferred-data-mutation-method.md
This PR updates the example for the hook to use the export format that is recommended in the ADR we've written on export types.
=> Change to preferred export format

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
* This PR adds a dialog for cancelling changes, and explains what happens once you move a change request into the cancelled state.
=> fix: add dialog for cancel

frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestConfiguration.tsx
Fixes an issue where `PermissionSwitch` would not update because we passed in environmentId and the UPDATE_PROJECT permission is only project specific. Also fixes an issue where hasAccess didn't take in projectId for UPDATE_PROJECT which is a project specific permission.
=> fix: cr permission actions

src/lib/routes/admin-api/project/features.ts, src/lib/services/project-health-service.ts, src/test/e2e/api/admin/favorites.e2e.test.ts
Small update, that single project endpoint would also return features with favorites.
=> Make single project endpoint also return all features favorites

frontend/vite.config.ts
I noticed we had a Vite error when trying to run the front-end locally bound to `unleash-cloud` due to the new `@server` import. This fixes it by allowing serving fs from one level up.
Docs: https://vitejs.dev/config/server-options.html#server-fs-allow
=> fix: allow import @server

src/lib/db/feature-strategy-store.ts, src/lib/routes/admin-api/project/variants.ts, src/lib/services/feature-toggle-service.ts, src/test/e2e/api/admin/project/variants.e2e.test.ts
This PR addresses some issues when working with variants after migrating to variants per environment.
**Problem:** since PATCH `/api/admin/projects/default/features/${featureName}/variants` does not take into account `featureEnvironments`, when variantsPerEnvironment gets enabled, this method will override the variants in other environments (i.e. not doing a patch). This method has to be maintained because of backward compatibility but it has to be adapted to deal with variants per environment
https://linear.app/unleash/issue/2-476/when-using-patch-for-variants-without-environments-it-wipes-out
=> Fix PATCH variants (old endpoint) when variants per environment are enabled

frontend/src/component/common/Table/FavoriteIconHeader/FavoriteIconHeader.tsx, frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx, frontend/src/hooks/usePinnedFavorites.ts
Favorites column did not work because of `react-table` reloading `initialState` if `columns` change.
=> fix: favorites column visibility

frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectRoleDescription/ProjectRoleDescription.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectRoleDescription/ProjectRoleDescriptionEnvironmentPermissions/ProjectRoleDescriptionEnvironmentPermissions.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectRoleDescription/ProjectRoleDescriptionProjectPermissions/ProjectRoleDescriptionProjectPermissions.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessRoleCell/ProjectAccessRoleCell.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx, frontend/src/hooks/api/getters/useChangeRequestConfig/useChangeRequestConfig.ts, frontend/src/hooks/api/getters/useConditionalSWR/useConditionalSWR.ts, frontend/src/hooks/api/getters/useEnterpriseSWR/useEnterpriseSWR.ts, frontend/src/hooks/api/getters/usePendingChangeRequests/usePendingChangeRequests.ts, frontend/src/hooks/api/getters/usePendingChangeRequestsForFeature/usePendingChangeRequestsForFeature.ts, frontend/src/hooks/api/getters/useProjectRole/useProjectRole.ts
https://linear.app/unleash/issue/2-485/bug-pro-access-page-the-tooltip-on-the-roles-is-not-working
Fixes an issue where we would not show anything for project role permissions since we're not serving that specific endpoint below Enterprise level. This way we fallback to the access role descriptions, which are also nice and informative:
PR also adds support for SWR options in ConditionalSWR and EnterpriseSWR.
=> Fix pro project role descriptions

frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestConfiguration.tsx
https://linear.app/unleash/issue/2-487/bug-change-request-badge-is-not-working-on-pro
Using the new `isPro()` from `useUiConfig()` seems to fix this in Pro, correctly showing the premium feature info:
The errors described in the issue should be fixed by the new `useEnterpriseSWR`. See: https://unleash-internal.slack.com/archives/C046LV6HH6W/p1670337216187539?thread_ts=1670331887.521059&cid=C046LV6HH6W
=> fix: isPro check on change request configuration

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/create-config.ts, src/lib/routes/backstage.ts, src/lib/types/option.ts, src/server-dev.ts
Is protected behind a config option called `enableHeapSnapshotEnpoint`. When API endpoint is triggered it will write a heapSnapshot to disk. 
Steps to create heap snapshot:
1. Add env variable `ENABLE_HEAP_SNAPSHOT_ENPOINT=true`. 
2. Call this endpoint: `/internal-backstage/heapSnapshot`
3. Download the created heapdump from the server. 
The snapshot can be loaded in the chrome dev-tool to analysis.
=> feat: add capability to write heap snapshot.

frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx
Bug description: 
Add strategy screen has a concept of empty feature. 
Empty string projectId is propagated and ends up in usePendingChangeRequest: `api/admin/projects/${project}/change-requests/pending`.
Since project is empty we get `api/admin/projects/change-requests/pending` and this one hits the health overview endpoint.
This PR basically stops rendering when feature is empty
=> Fix strategy screen 404

website/docs/reference/deploy/securing-unleash.md
Noticed there is missing link to the azure sso implementation example.
=> Add azure example to the documentation page

frontend/src/hooks/api/getters/useInstanceStatus/useInstanceStatus.ts
Same as https://github.com/Unleash/unleash/pull/2650 but for `useInstanceStatus`, since it followed a similar pattern.
=> fix: use instance status too many reqs

website/docs/reference/front-end-api.md, website/docs/reference/impression-data.md, website/docs/reference/unleash-proxy.md, website/docusaurus.config.js
This PR contains a number of minor fixes to the docs in terms of formatting and redirects. The changes are:
-   Adding an availability notice for the front-end API reference docs (with links to the release blog post).
-   Fix malformed admonition headers in the Unleash proxy docs and impression data docs.
-   Add missing redirects:
-   `/advanced/custom_activation_strategy` -> `/reference/custom-activation-strategies`
-   `/docs/deploy/configuring_unleash` -> `/reference/deploy/configuring-unleash`
-   `/docs/user_guide/connect_sdk` -> `/reference/sdks`(this one goes to the SDKs doc instead of the quickstart because there's more comprehensive information there and because `/user_guide/connect_sdk` already goes there)
-   `/sdks/proxy-javascript` -> `/reference/sdks/javascript-browser`
- …
=> docs: various fixes

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/Change.tsx, frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx, frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ToggleStatusChange.tsx, frontend/src/component/changeRequest/ChangeRequest/Changes/FeatureToggleChanges.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.styles.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewers/ChangeRequestReviewer.tsx, frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx, frontend/src/component/changeRequest/ChangeRequestSidebar/ReviewChangesHeader/ReviewChangesHeader.tsx, frontend/src/component/common/FormTemplate/FormTemplate.styles.ts, frontend/src/utils/strategyNames.tsx
This PR contains multiple UI fixes for the change request. It changes font sizes, icon colors, margins and paddings to be more consistent.
=> Fix/cr UI fixes

frontend/cypress/integration/projects/access.spec.ts, frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCard.tsx, frontend/src/component/project/Project/Project.tsx, frontend/src/component/project/Project/ProjectInfo/ProjectInfo.tsx
1. Now all redirect to access tab are going to narrow access tab
2. Remove wide access tab completely, so now it is not possible to access it via url
3. Project settings tab is visible by default now for **ALL USERS**
=> Remove full width access tab

frontend/src/component/common/Table/VirtualizedTable/VirtualizedTable.styles.ts, frontend/src/component/common/Table/cells/FavoriteIconCell/FavoriteIconCell.tsx
Fixes an issue where the tooltip would flash on the top left when going through the rows.
=> fix: favorite tooltip topleft flash

frontend/src/component/common/Table/cells/FavoriteIconCell/FavoriteIconCell.tsx
https://linear.app/unleash/issue/2-510/favorite-cell-tooltips-is-buggy-when-pinned-remove-tooltips
Tooltips were buggy when using the pinned feature, so I aligned with @NicolaeUnleash and decided to remove them for now:
Also includes a slight refactor on this component.
=> fix: remove tooltip from favorites cell, some refactoring

.github/workflows/publish-new-version.yaml
We cannot hard code the branch to be "main" if we want to allow the release script to also run from branch (e.g. 4.18 maintenance branch)
=> fix: allow publish-new-version action to run from branch

src/lib/db/feature-strategy-store.ts, src/lib/openapi/index.ts, src/lib/openapi/spec/admin-features-query-schema.test.ts, src/lib/openapi/spec/admin-features-query-schema.ts, src/lib/openapi/spec/index.ts, src/lib/routes/admin-api/project/features.ts, src/test/e2e/api/admin/project/features.e2e.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/e2e/stores/feature-strategies-store.e2e.test.ts
The deprecated /api/admin/features endpoint supported querying with tag and namePrefix parameters. 
This PR adds this functionality to /api/admin/projects/<project>/features as well, allowing to replicate queries that used to work.
Closes #2306
src/lib/db/feature-strategy-store.ts
src/test/e2e/stores/feature-strategies-store.e2e.test.ts
I'm extending our query parameters support for /api/admin/projects/<projectId>/features endpoint. This will be reflected in our open-api spec, so I also made an adminFeaturesQuerySchema for this.
Also, very open for something similar to what we did for the modifyQuery for the archived parameter, but couldn't come up with a good way to support subselects using the query builder, it just ended up blowing the stack. If anyone has a suggestion, I'm all ears.
=> feature: add query support to features endpoint

src/lib/db/client-instance-store.ts, src/lib/metrics.test.ts, src/lib/metrics.ts, src/lib/services/instance-stats-service.ts, src/lib/types/stores/client-instance-store.ts, src/test/fixtures/fake-client-instance-store.ts
This metric will expose an aggregated view of how many client applications are registered in Unleash. Since applications are ephemeral we are exposing this metric in different time windows based on when the application was last seen. 
The caveat is that we issue a database query for each new range we want to add. Hopefully, this should not be a problem because:
a) the amount of ranges we'd expose is small and unlikely to grow
b) this is currently updated at startup time and even if we update it on a scheduled basis the refresh rate will be rather sparse
This is how metrics will look like
```
client_apps_total{range="allTime"} 3
client_apps_total{range="30d"} 3
client_apps_total{range="7d"} 2
```
=> feat: expose number of registered applications metric

frontend/package.json, frontend/src/component/admin/network/Network.tsx
Adds lazy loading to the network routes, so we end up with smaller chunks in the build.
Also adds a `start:prod` script that can prove useful to test the chunk loading behaviour locally.
=> Feat lazy loading network

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx
Fix missing label.
Closes [1-511](https://linear.app/unleash/issue/1-511/small-bug-with-the-dropdown-from-metrics-when-we-pick-last-hour-option)
=> fix: metrics one hour select label

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/types/experimental.ts, src/lib/util/flag-resolver.test.ts, src/lib/util/flag-resolver.ts
Adding stricter types to `FlagResolver` can possibly help improve our DX - Help us prevent errors like typos, guide us to correctly add a flag when needed, and warn us of stray checks whenever we do a clean up at a later stage.
=> refactor: flag resolver should use stricter types

src/lib/db/strategy-store.ts, src/lib/services/state-service.test.ts, src/lib/types/stores/strategy-store.ts, src/test/e2e/services/state-service.e2e.test.ts, src/test/fixtures/fake-strategies-store.ts
Previously when importing strategies we've used the same data type we've used for creating strategies (the minimal, a name, an optional description, optional parameters and an optional editable column). This meant that exporting strategies and then importing them would reactivate deprecated strategies. This PR changes to allow the import to preserve all the data coming in the export file.
Added four new tests, two new unit tests using our fake stores and two new e2e tests. Interestingly the ones in the fake store ran green before this change as well, probably because we just insert the parsed json object in the fake store, whereas the real store actually converts the object from camelCasing to the postgresql snake_casing standard.  
This is inevitable since storing things in javascript …
=> fixes 2-456: Preserve all data from strategy import

frontend/src/component/application/ApplicationList/ApplicationList.tsx, frontend/src/component/common/Highlighter/Highlighter.tsx, frontend/src/component/project/ProjectList/ProjectList.tsx, frontend/src/hooks/useFeaturesFilter.ts, src/lib/proxy/create-context.test.ts, src/lib/util/escape-regex.ts
If you enter characters like ()[] in the search, following error occurs:
**This PR escapes regex characters and makes the app not crash.**
=> Fix crashing search bars

frontend/src/utils/formatPath.test.ts, frontend/src/utils/formatPath.ts
Today we have two functions that wrap our paths with the subpath. Since all of our customers are hosted on a subpath, such as /eubb1001, we need to account for this path when building API paths and asset paths. 
These functions could be smarter, we could, for example detect if we have already added the base path and ignore it if it already exists.
**This PR implements this and adds 2 capabilities:**
1. If there is list of paths that need to be joined and one is subset of another, it is removed.
2. All duplicate paths in the list are removed
=> formatApiPath / formatAssetPath - Implement smart functionality to detect double subpath

src/lib/openapi/validate.ts, src/lib/services/openapi-service.ts
Now respondWithValidation<T, S = SchemaId> can be called in oss and enterprise to validate against needed schema.
=> Make it possible to validate enterprise schema with respondWithValidation

README.md, website/docusaurus.config.js
This change removes the Unleash 4.16 constraints announcement from readme and from the docs.
It feels like 4.16 has been out for long enough now. Gearing up for version 4.19, it may be time to take this away.
However, open-sourcing constraints was (and still is) a big deal, so it might be worth keeping the banner around, but maybe in a more subdued format? Something like "did you know Unleash's constraints feature is open source, now?".
=> chore: remove constraints announcements from readme and docs

website/docs/reference/sdks/node.md
This change does two things:
It **removes the `environment` option** from the initialization examples. This option is deprecated and only causes confusion. There's no good reason to have it lying around in the examples.
It also **updates the explanation of the code samples**, telling you that you need to generate an API key and linking you to the reference doc and how to guide.
Relates to: #2782.
=> docs: clarify node sdk instructions wrt envs and tokens

website/docs/about-the-docs.md
This change fixes some broken links in the "about the docs" document. Most of these links go to concrete documents and have been replaced with their appropriate relative file links. The few links that go to auto-generated pages have been corrected.
Unfortunately, there does not seem to be an easy way to link safely to generated pages.
=> Docs(fix): broken links

website/docs/reference/sdks/android-proxy.md
This change fixes a formatting issue which causes the entire document to be rendered inside of the admonition.
=> docs: fix android admonition formatting

frontend/src/component/user/Login/Login.tsx, frontend/src/component/user/UserProfile/UserProfileContent/UserProfileContent.tsx, website/docs/how-to/how-to-add-sso-google.md, website/docs/how-to/how-to-add-sso-open-id-connect.md
This change updates some places in the docs where we use the terms "login" and "logout" incorrectly.
A "login" is a noun, typically referring to the set of credentials you need to _log in_ to a service. The verb form, the act of signing in, is written in two words: to "log in".
A similar logic applies to "logout" and "log out", although I don't find the term "logout" in my dictionary. However, I think it makes sense to talk about "logout requests" (and I see references to logout in other services and documentation), so I'm happy to use that as a noun. Regardless, the act of logging out is to "log out".
=> Fix(typo): Fix "login"/"log in", "logout"/"log out" issues

frontend/src/component/admin/network/NetworkTraffic/NetworkTraffic.tsx, src/lib/services/client-metrics/instance-service.ts
To avoid showing too much data in the traffic screen, limit the number of results to `topk`. 
Top 10 is a rule of thumb, but maybe we could do top 25. Until we gather more data, I believe this should be good enough
=> feat: limit the amount of results coming from Prometheus

frontend/src/component/segments/SegmentDelete/SegmentDelete.tsx
Prevent flashing of another dialog when deleting a segment.
Closes [1-501/delete-segment-double-dialog](https://linear.app/unleash/issue/1-501/delete-segment-double-dialog)
=> fix: segment delete confirmation double dialog flash

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantModal/EnvironmentVariantModal.tsx, src/lib/schema/feature-schema.test.ts, src/lib/schema/feature-schema.ts
According to our docs, we only support up to 1 decimal place for weights. This is to use integers to represent the percentages (we divide them by 10) and supporting more decimals results in bad maths due to floating point arithmetics. 
This PRs adds Frontend and Backend validations to enforce this restriction
Closes #2222
Should we reconsider supporting more decimal places, that door remains open, but for now we'll just adhere to our documentation because that change would require some development.
=> fix: enforce weight precision to 1 decimal

renovate.json
Some dependency updates we receive are recent releases with a low adoption rate. It's fine to be early adopters but this can also introduce unintended bugs. This PR adds a 7 days grace period before we consider a dependency as ready to be upgraded. It doesn't guarantee its stability but it improves it.
Ideally, I'd like to also use adoption and confidence to automatically merge or delay the creation of the PR, but I haven't found a way of doing that
It also protects us from:
> npm packages less than 72 hours (3 days) old can be unpublished
Documentation: https://docs.renovatebot.com/configuration-options/#stabilitydays
=> feat: wait for deps to be somewhat stable

src/lib/db/project-store.ts
When health report is 0% we should report 0%. Previously we were reporting 100%.
=> fix: when health is 0 we should not show 100

website/docs/contributing/ADRs/ADRs.md
This should have been caught by the build system (and it _is_ on this [unrelated docs PR](https://github.com/Unleash/unleash/actions/runs/3847684144/jobs/6554451234)). 
@Tymek , you're listed as the author of the commit that introduced it; can you link me to the PR? I'd like to try and figure out why this went through 🕵🏼
=> Docs(fix): fix broken link to sdk-generator ADR

website/docusaurus.config.js
For each defined doc redirect path (that doesn't start with `/docs/`), this PR adds an additional redirect that starts with `/docs`. The rest of the path is otherwise identical.
For instance, if we have a redirect that goes from `/user_guide/x`, then this change will ensure that we also have redirect that goes from `/docs/user_guide/x`.
As reported by Roman, we've had some 404s recently when people have tried to access pages that used to exist (wayyyy back) and that used to redirect.
The reason these redirects stopped working is that we changed the url structure recently. Before then, the `createRedirects` function would go and create redirects that started with `/docs/` for all the paths that required it. However, now that we've changed the structure of the URLs, a blanket implementation …
=> docs: add `/docs` redirects to _all_ redirect paths

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvSwitches/FeatureOverviewEnvSwitch/FeatureOverviewEnvSwitch.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvSwitches/FeatureOverviewEnvSwitches.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitch/FeatureOverviewSidePanelEnvironmentHider.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitch/FeatureOverviewSidePanelEnvironmentSwitch.tsx
This feature was already implemented, but this PR adds couple of fixes to it.
1. Currently it was only visible, when **variantsPerEnvironment** flag was enabled. Now it is visible always.
2. Now the hide button is more centered on the line.
=> Allow hiding environments from the feature overview screen fix

src/lib/openapi/validate.ts
Previously there was no way to add AJV schemas in runtime. This PR adds to availability.
=> Ability to add AJV schemas runtime

frontend/src/component/admin/users/UsersList/UsersList.tsx
Small UI/UX change. 
After discussing with @NicolaeUnleash we decided that moving this column in the users table over to the right next to "last login" would improve readability and consistency.
=> feat: move createdAt col on users

frontend/src/component/admin/apiToken/ApiTokenTable/ApiTokenTable.tsx, frontend/src/component/admin/groups/GroupForm/GroupFormUsersTable/GroupFormUsersTable.tsx, frontend/src/component/admin/projectRoles/ProjectRoles/ProjectRoleList/ProjectRoleList.tsx, frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountModal/ServiceAccountTokens/ServiceAccountTokens.tsx, frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountsTable.tsx, frontend/src/component/admin/users/UsersList/UsersList.tsx, frontend/src/component/archive/ArchiveTable/ArchiveTable.tsx, frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx, frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx, frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsTable/FeatureMetricsTable.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsTable/EnvironmentVariantsTable.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureVariantsList/FeatureVariantsList.tsx, frontend/src/component/playground/Playground/PlaygroundResultsTable/PlaygroundResultsTable.tsx, frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx, frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx, frontend/src/component/project/ProjectAccess/ProjectGroupView/ProjectGroupView.tsx, frontend/src/component/segments/SegmentTable.tsx, frontend/src/component/user/Profile/PersonalAPITokensTab/PersonalAPITokensTab.tsx
https://linear.app/unleash/issue/2-563/fix-issue-with-useconditionallyhiddencolumns-and-react-table
It seems like we should add `autoResetHiddenColumns: false` to `useTable` whenever we use `useConditionallyHiddenColumns`.
Basically the thought is that, if we're controlling column visibility in our own way, we should not want other things to change that state unpredictably, otherwise this may make React go _brrrrrr_. And it can be very hard to pinpoint what exactly may be causing React to go _brrrrrr_.
First detected this issue apparently randomly while developing the new SA table. Around 10-20 page refreshes would eventually trigger it. Was not easy to find, but hopefully this fixes it permanently. At least I haven't been able to reproduce it since. Maybe someone has a better idea of …
=> fix: disable autoResetHiddenColumns when useConditionallyHiddenColumns

frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountsTable.tsx
Seems like merging both https://github.com/Unleash/unleash/pull/2851 and https://github.com/Unleash/unleash/pull/2848 made us end up with a duplicate `autoResetHiddenColumns` option in the `ServiceAccountsTable` table component.
=> fix: SA duplicate autoResetHiddenColumns

frontend/src/component/layout/Error/Error.tsx, frontend/src/hooks/usePlausibleTracker.ts
https://linear.app/unleash/issue/2-567/add-plausible-tracking-to-unknown-uncaught-frontend-errors
Based on the discussion from https://github.com/Unleash/unleash/pull/2851, something like this could help us track uncaught/unknown errors on the frontend.
Just a quick suggestion, since there might be something better we could use for this.
=> feat: track uncaught UI errors in plausible

frontend/src/component/common/PageContent/PageContent.styles.ts, frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
https://linear.app/unleash/issue/1-546/project-overview-table-is-missing-overflow-x-auto
Fixes an issue where the PageContent body doesn't scroll horizontally when needed.
This regression seems to have been included with https://github.com/Unleash/unleash/pull/2811, more specifically:
https://github.com/Unleash/unleash/pull/2811/files#diff-a1c10fdcd539d988f74d4c3742cc6b8844152999a6c7e509ed8b1765c604524fL491
=> fix: PageContent bodyContainer overflowX

src/lib/addons/addon.ts
This uses log-level warning so we can turn off the log without turning off all error logs. This could potentially be tweaked further by using log categories in the log configuration.
Closes #2057
=> feat: add error logs for addons

src/lib/openapi/spec/__snapshots__/feature-schema.test.ts.snap, src/lib/openapi/spec/feature-environment-schema.test.ts, src/lib/openapi/spec/feature-environment-schema.ts, src/lib/openapi/spec/feature-schema.test.ts, src/lib/openapi/spec/feature-schema.ts, src/lib/openapi/spec/features-schema.ts, src/lib/openapi/spec/health-overview-schema.ts, src/lib/routes/admin-api/project/features.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
This PR fixes the admin feature schema by moving the `strategies` (featureStrategySchema) from the root of `feature` object to `feature.environment`
Closes #
=> fix feature-schema.ts

frontend/src/component/common/SidebarModal/SidebarModal.tsx
Make close button visible in sidebar when a device screen is small
Changes:
* increase zIndex to 1
* extracted styled component (cleanup)
=> fix: make close button visible on small devices

frontend/src/component/layout/MainLayout/MainLayout.tsx
After styled component migration we broke the header. Grid element margin was going outside the main parent element and entering the area of the header (margin collapsing). Added display: flex to main element to prevent child elements escaping with their margins.
Fixed:
Before:
Solution: Added flex to parent of the element that was collapsing its margin.
=> fix: prevent margin collapsing

frontend/src/themes/app.css
[`Sen` font](https://fonts.google.com/specimen/Sen) adds smiley for keywords like `:D`, `tantan`, `kosal` and `starlee`.
Downslide is we are loosing the `tt` ligature.
=> fix: unexpected ligatures

frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitch/FeatureOverviewSidePanelEnvironmentHider.tsx
Root cause: segments are returned as empty array. Empty array in useEffect caused infinite re-render because it was a different instance of empty array.
=> fix: infinite rendering due to wrong effect deps

src/lib/services/state-service.ts, src/test/e2e/api/admin/state.e2e.test.ts, src/test/examples/exported3-with-default-disabled.json
When exporting v3, for variants backward compatibility, we need to find one featureEnvironment and fetch variants from there. 
In cases where the default environment is disabled (therefore does not get variants per environment when added), it can be still be selected for the export process. Therefore variants don't appear in the feature when they should be there.
An e2e test that fails with the previous implementation was added to validate the behavior
This comes from our support ticket 404
=> fix: found an edge case exporting variants

frontend/src/component/common/BreadcrumbNav/BreadcrumbNav.tsx, frontend/src/themes/theme.ts, frontend/src/themes/themeStyles.ts
https://linear.app/unleash/issue/2-577/small-breadcrumb-adjustments
Includes small adjustments to the breadcrumb navigation component.
=> fix: small breadcrumb adjustments

website/docs/reference/change-requests.md
This change adds the change requests explainer video to the change requests reference documentation.
As a bonus, it also cleans up some redundant whitespace.
=> docs: add change requests video

website/docusaurus.config.js
This PR:
-   adds a footer link to GitHub discussions
-   updates the link to the public roadmap
Because we want more people to use discussions as a resource and because the old roadmap link leads to a deprecated roadmap.
=> docs: update footer links

frontend/src/component/events/EventCard/EventCard.tsx
Some changes recorded in the event log apply only to one particular environment. This is currently not visible in the event log card, but it is present in the recorded event:
| Full event | Event card |
| --- | --- |
| ![Screenshot from 2023-01-17 14-22-55](https://user-images.githubusercontent.com/455064/212910227-77b5e81c-60fe-4891-bfad-e3358e5a0ba5.png) | ![image](https://user-images.githubusercontent.com/455064/212910207-7cae700b-3f50-4035-9bcd-897de62d76d2.png) |
This PR makes that information visible on the event card
- **Should the environment name have a link?** I believe this depends on what resource we're modifying. Between linking to the resource (a link that already exists in the event card) and not adding a link I'm inclined to don't include a link
=> fix: add environment to event log card

frontend/src/component/admin/groups/GroupForm/GroupFormUsersSelect/GroupFormUsersSelect.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessCreate/ProjectAccessCreate.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessEditGroup/ProjectAccessEditGroup.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessEditUser/ProjectAccessEditUser.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx, frontend/src/hooks/api/getters/useAccess/useAccess.ts, frontend/src/hooks/api/getters/useProjectAccess/useProjectAccess.ts, frontend/src/interfaces/user.ts, src/lib/db/user-store.ts, src/lib/openapi/spec/user-schema.ts, src/lib/routes/admin-api/user-admin.ts, src/lib/services/user-service.ts, src/lib/types/stores/user-store.ts, src/lib/types/user.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/fixtures/fake-user-store.ts
https://linear.app/unleash/issue/2-579/improve-user-like-behaviour-for-service-accounts-accounts-concept
Makes SAs behave more like users. 
Even though they share the same `users` database table, the `is_service` column distinguishes them. This PR makes the distinction a bit less obvious by not filtering out SAs for some methods in the user store, returning both account types and their respective account type information so we can handle them properly on the UI.
We felt like this was a good enough approach for now, and a decent compromise to move SAs forward. In the future, we may want to make a full refactor with the `accounts` concept in mind, which we've experimented with in the [accounts-refactoring](https://github.com/Unleash/unleash/tree/accounts-refactoring) branches (both OSS and …
=> feat: adapt user logic to better adapt to SAs

frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx, frontend/src/hooks/api/getters/useAccess/useAccess.ts, frontend/src/hooks/api/getters/useProjectAccess/useProjectAccess.ts, src/lib/db/account-store.ts, src/lib/db/index.ts, src/lib/middleware/pat-middleware.test.ts, src/lib/middleware/pat-middleware.ts, src/lib/routes/admin-api/user-admin.ts, src/lib/services/access-service.ts, src/lib/services/account-service.ts, src/lib/services/group-service.ts, src/lib/services/index.ts, src/lib/services/project-service.ts, src/lib/services/user-service.ts, src/lib/types/services.ts, src/lib/types/stores.ts, src/lib/types/stores/account-store.ts, src/test/fixtures/access-service-mock.ts, src/test/fixtures/fake-account-store.ts, src/test/fixtures/store.ts
https://linear.app/unleash/issue/2-579/improve-user-like-behaviour-for-service-accounts-accounts-concept
Builds on top of https://github.com/Unleash/unleash/pull/2917 by moving the responsibility of handling both account types from `users` to `accounts`.
Ideally:
- `users` - Should only handle users;
- `service-accounts` - Should only handle service accounts;
- `accounts` - Should handle any type of account;
This should hopefully also provide a good building block in case we later decide to refactor this further down the `accounts` path.
=> feat: add the account abstraction logic

frontend/src/component/common/HtmlTooltip/HtmlTooltip.tsx, frontend/src/component/common/TooltipLink/TooltipLink.tsx, frontend/src/component/environments/EnvironmentTable/EnvironmentNameCell/EnvironmentNameCell.tsx
Fixes an issue where the `HtmlTooltip` arrow would no longer work after a regression included with https://github.com/Unleash/unleash/pull/2891
Also adds the arrow prop to most usages of the tooltip to keep consistency.
=> fix: tooltip arrow regression after last scroll max size feat

frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
Fixes an issue where environments were not filtered correctly on the search, most likely due to some regression accidentally introduced with changes in the meantime.
=> fix: filtering environments in the project features table

website/docs/reference/unleash-proxy.md
This change removes a notice from the proxy documentation saying that users should reach out to support@getunleash.io if they want the Unleash team to host it.
Unleash ships with the front-end API now, so we don't want people reaching out to support for this anymore.
=> docs: don't tell users to contact support for proxy hosting

frontend/src/component/common/HtmlTooltip/HtmlTooltip.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitches.tsx, frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
Small UI-centric suggestions for things I identified:
- Links now open on a new tab by default;
- Small refactoring opportunities;
- Improves the spacing in the feature overview toggles (1);
- Improves the alignment of the environment switch on the project overview (2);
Also includes some small `HtmlTooltip` changes - I noticed `fontSize` was different between tooltips so this aligns the default and includes some refactoring with the default values.
=> fix: small UI-centric suggestions

frontend/src/constants/values.ts
Currently we have a soft limit of 15 environments, there's no technical or business reason for this, only that it's handled inelegantly in the UI. Users are asking for more
=> chore: increase max number of environments from 15 to 50

.lycheeignore
Removing perfect match on our Twitter account URL
Closes #2958
=> chore: ignore Twitter link from being checked

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantModal/EnvironmentVariantModal.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsTable/EnvironmentVariantsTable.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsTable/VariantsActionsCell/VariantsActionsCell.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/FeatureEnvironmentVariants.tsx, frontend/src/constants/variantTypes.ts
This blocks the UI from allowing you to attempt to delete the last fixed variant in environment variants, this was previously possible, but the UI catch an error and then never make a request. For bonus points this removes the problematic try catch, which allows the error message to bubble correctly to the handler
=> fix: prevent deleting the last variable variant on the ui

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/Change.tsx, frontend/src/component/changeRequest/ChangeRequest/Changes/Change/VariantPatch/Diff.tsx, frontend/src/component/changeRequest/ChangeRequest/Changes/Change/VariantPatch/VariantPatch.tsx, frontend/src/component/changeRequest/changeRequest.types.ts, frontend/src/component/events/EventDiff/EventDiff.tsx
https://linear.app/unleash/issue/2-582/display-the-change-request-created-with-variants-in-the-ui
Includes a basic diff visualisation on variants change requests.
It seems like components like `CodeSnippetPopover` and `PopoverDiff` are currently very tightly coupled together with strategies, so I preferred to follow my own approach and leave those alone for now instead of trying to refactor them. `patchVariant` could also be renamed to a more fitting name in the future as well, since we're now doing more of an override than applying a patch.
`Diff` is a generic diff component that uses `EventDiff` internally and simply takes into account a "before" and "after" state, as `preData` and `data`.
I made some changes to `EventDiff` that made some sense to me:
- Cover edge cases where `path` is …
=> feat: visualize variants diff in CR

website/docs/tutorials/quickstart.md
This change adds instructions on how to use the front-end API for client-side SDKs to the quickstart guide. It also organizes the content so that this info is presented before the proxy info.
The front-end API is easier to use, so it should be preferred over the proxy for people who are just getting started.
=> docs: Add front-end API setup to the quickstart guide

frontend/src/component/changeRequest/ChangeRequestConfirmDialog/ChangeRequestConfirmDialog.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantModal/EnvironmentVariantModal.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/FeatureEnvironmentVariants.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/PushVariantsButton/PushVariantsButton.tsx, frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts, frontend/src/interfaces/featureToggle.ts, frontend/src/interfaces/uiConfig.ts
https://linear.app/unleash/issue/2-585/add-cr-to-variants-per-environment-ui
Adds CR to the variants per environment UI. This is basically the point where we have CRs integrated but can e.g. only update the weight once per CR. Adapting the UI to better fit CR logic will come next.
=> feat: adds CR to variants per env UI

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsTable/EnvironmentVariantsTable.tsx
Fixes a bug where some variant tables did not render properly if scrolled all the way down.
Since we are not expecting to need virtualisation in these tables anyways (each table should hopefully have a relatively low amount of variants), reverting the `VirtualizedTable` usage to a normal one seemed like the most straightforward solution at this stage, fixing the issue without any noticeable side effects.
=> fix: revert table virtualization in variants per env

website/readme-fns.js
This change adds the next.js sdk's readme to the client-side SDKs section in the docs.
Because we have a new and official SDK 🙌🏼
=> docs: add next.js docs

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx
Small fix on the tooltip for the "delete variant" button in the new environment variants form.
=> fix: delete variant button tooltip

src/lib/db/project-store.ts, src/test/e2e/services/project-service.e2e.test.ts
While trying to count only features that are not archived to display the amount of features of a project, accidentally we filtered out projects with all features archived (they should show up in the list but with count of features zero)
Improves: #2923
=> fix: list projects with all archived toggles

frontend/src/component/strategies/StrategyView/StrategyDetails/StrategyDetails.tsx
Hide "toggles using this strategy" since it was not not working for a while.
Closes https://linear.app/unleash/issue/1-570/toggles-using-this-strategy-table-in-the-strategy-types-view-is-empty
=> fix: remove toggles using this strategy

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx, src/lib/middleware/response-time-metrics.ts
This fixes response time metrics with app names when the app just starts and has zero which is falsy. We want to compare against undefined (which means the snapshot is not yet ready)
=> fix: when app count is zero because it just started

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx
We've found that 60000 was just 1 minute and we wanted it to be 10 minutes so we were missing 1 zero and sometimes in 1 minute we didn't have data. This is still an assumption we'll verify in sandbox
Co-authored-by: Nuno Góis <github@nunogois.com>
=> fix: use utc to compare time

website/docs/reference/deploy/getting-started.md
This change updates the docker compose instructions to match what is currently in the Unleash/unleash repo itself.
Because the old version was out of date.
=> docs: update old docker compose instructions

website/docs/topics/the-anatomy-of-unleash.mdx
This change updates the "variants" section of the Anatomy of Unleash document with more information about how variants work with multiple environments.
At the moment, it states that variants per env are GA from 4.21, but that might need to be changed.
With the upcoming release of variants per environment, the doc should reflect the current state of things. However, it should also still contain info for those not yet on v4.21
=> docs: update Anatomy doc with variants per environment notice

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx
We noticed in our instance that when we have same label it shows duplicated in the overview:
We're changing to this way of displaying info:
when the data in traffic looks like this:
=> feat: aggregate by label and type

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/PushVariantsButton/PermissionCheckboxMenuItem.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/PushVariantsButton/PushVariantsButton.tsx, frontend/src/hooks/useHasAccess.ts
When checking for permissions we have 2 methods, one that is not change request aware and one that is. We were using the one that is not aware of CR while the feature we developed is aware of CR.
This PR switches to the correct method and documents the hooks
=> fix: use the correct hook for permissions and CR

.github/workflows/generate-docs.yaml
This change fixes the `generate-docs` workflow, so that they'll run daily as a cron job. The `schedule` property had been erroneously listed as a sub-property of the `workflow_dispatch` property.
The way the docs are set up at the moment, they source a lot of their content from external repos. As it stands, we don't listen for update events in all of those external dependencies, so we don't know when they update. We do still want the docs to be reasonably fresh, though.
So to achieve this, we can run this workflow once a day to make sure that no docs are more than 24 hours old.
=> docs: generate docs daily

.github/workflows/continuous-publish-new-version.yaml
Introducing **continuous npm version release**. Every conventional commit to main triggers a new version automatically.
Consequences: 
* for day to day beta releases we don't need to take any manual actions
* for official releases you can still use https://github.com/Unleash/unleash/actions/workflows/publish-new-version.yaml
How it works?
* you squash your commit with a conventional commit **feat:** or **fix:** or **refactor:**
* this action bumps up the beta version
* this action pushes the bumped up version back to the **github repo** and to **npm registry**
Corner cases:
* how will it work after official release of e.g. 4.22.0? new version: 4.23.0-beta.0
* how will it work after previous beta release e.g. 4.23.0-beta.0? new version 4.23.0-beta.1
Why is it using beta.0, beta.1? 
* …
=> feat: continuous beta version npm release

.github/workflows/build.yaml
We do not need this trigger anymore as we auto-release beta versions from this repository and auto bump the dependency in unleash-enterprise.
=> feat: remove CI build trigger

src/lib/services/feature-toggle-service.ts, src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts
Spotted some issues in logs:
```json
{
"level":"warn",
"message":"Failed to store \"feature-environment-variants-updated\" event: error: insert into \"events\" (\"created_by\", \"data\", \"environment\", \"feature_name\", \"pre_data\", \"project\", \"tags\", \"type\") values (DEFAULT, $1, $2, $3, $4, $5, $6, $7) returning \"id\", \"type\", \"created_by\", \"created_at\", \"data\", \"pre_data\", \"tags\", \"feature_name\", \"project\", \"environment\" - null value in column \"created_by\" violates not-null constraint",
"name":"lib/db/event-store.ts"
}
```
In all other events we're doing the following: https://github.com/Unleash/unleash/blob/b7fdcd36c08fcd9461fef930767606962e73d59c/src/lib/services/segment-service.ts#L80
So this is just mimicking that to quickly release a patch, but I'll …
=> fix: make sure we have a user in event store

src/lib/services/proxy-service.ts
This PR changes the behavior of checking the incoming token on the `/api/frontend` path. Instead of using assert resulting in a 500 error we are throwing an error that is caught by the default controller and emitted back to the user as JSON. 
This should be the correct behaviour, since the endpoint can not give you any meaningful data without the environment that the API token holds.
=> fix: replace assert with error

src/lib/routes/admin-api/export-import.ts
We are not using downloadFile flag. Frontend is generating the json file from payload and handling the naming.
Removed the issue that stream was accessed when closed.
=> fix: export failing because stream closed

frontend/cypress/integration/feature/feature.spec.ts, frontend/cypress/integration/import/import.spec.ts, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitches.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/EnvironmentVariantsModal.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/FeatureEnvironmentVariants.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureVariants.tsx, frontend/src/hooks/api/getters/useFeature/useFeature.ts, frontend/src/interfaces/uiConfig.ts, src/lib/__snapshots__/create-config.test.ts.snap, src/lib/services/environment-service.ts, src/lib/services/state-service.test.ts, src/lib/services/state-service.ts, src/lib/types/experimental.ts, src/server-dev.ts, src/test/config/test-config.ts, src/test/e2e/api/admin/state.e2e.test.ts
https://linear.app/unleash/issue/2-428/clean-up-feature-flag-once-were-done-with-the-migration
Cleans up the variants per environment feature flag due to GA.
=> refactor: remove variants per environment feature flag

src/lib/services/export-import-service.ts
Now context fields that are used for stickiness are also exported.
=> fix: also export context fields used for stickiness

website/docs/reference/segments.mdx, website/docs/reference/strategy-constraints.md
This PR adds a note to the constraint and the segment docs about using a large number of constraint values.
This is a fairly common question in slack, and there is no clear documentation around this at the moment. As such, it's likely that people do this a fair bit without telling us. We don't think this is the right approach, so adding this bit of documentation should hopefully make it a little clearer.
=> docs: add notes to constraints and segment docs about large values

website/docs/reference/sdks/index.md
This change removes the "unleash proxy" column from the SDK compat table.
Because the proxy isn't technically an SDK. Having the column there can be misleading to users.
In the latest case, a user pointed out that the table says the proxy supports `isEnabled` with fallback values, but that there is no way to use this via the API (or via client-side sdks) at the moment.
I think we should add a section to the proxy doc about its capabilities instead.
In fact, I think we should do the same thing with the proxy that we did with the SDKs: merge the docs.getunleash content with the github readme and instead source it from there.
=> docs: remove the proxy from the sdks overview table

website/docs/reference/deploy/configuring-unleash.md
Adds environment variable equivalents for remaining authentication options.
Also reformats the list silghtly.
Because the `AUTH_TYPE` and  `AUTH_ENABLE_API_TOKEN` variables hadn't been previously mentioned and we get questions about this from time to time.
The reformat is primarily for using `monospace font` where appropriate.
=> docs: mention env var options for auth config

src/migrations/20230222154915-create-notiications-table.js
Since `user_notifications` references `notifications`, it makes sense to drop `user_notifications` before dropping `notifications` and not the other way around. This should fix the failing tests on Enterprise with latest main.
Thanks @gastonfournier for the help finding the bug 👍
=> fix: notifications tables drop order

website/docs/how-to/how-to-clone-environments.mdx, website/docs/reference/environments.md
This update does three things:
1. Adjusts the environment cloning feature availability notice: because this has been released.
2. Updates the availability notice for environments (to conform with the standard docusaurus way of doing things): for consistency
3. Add a brief explanation of environment types: because this isn't documented anywhere
The note about how environment types work is sourced from this old [slack thread (internal to the team)](https://unleash-community.slack.com/archives/G01MU2Q49QC/p1659600175175769)
=> docs: slight update to environment docs

website/docs/reference/change-requests.md, website/docs/reference/rbac.md
This change updates the "change requests permissions" section of the change request doc to explicitly call out a few things we've seen confusion around recently.
These are:
-   project owners can't approve/apply change requests. You must create custom roles
-   viewers can create change requests. This is intentional
-   skip change requests only works via the API
It also:
-   elaborates a little on the circumventing change requests section to clarify how it works.
-   adds the change requests project roles to the project roles list. This section should be kept up to date with all the relevant roles that exist for projects.
=> docs: Update change requests permissions docs

frontend/src/component/common/Table/cells/TimeAgoCell/TimeAgoCell.tsx, frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap, frontend/src/component/menu/routes.ts, frontend/src/component/signOnLog/SignOnLog.tsx, frontend/src/component/signOnLog/SignOnLogTable/SignOnLogActionsCell/SignOnLogActionsCell.tsx, frontend/src/component/signOnLog/SignOnLogTable/SignOnLogDeleteDialog/SignOnLogDeleteDialog.tsx, frontend/src/component/signOnLog/SignOnLogTable/SignOnLogSuccessfulCell/SignOnLogSuccessfulCell.tsx, frontend/src/component/signOnLog/SignOnLogTable/SignOnLogTable.tsx, frontend/src/hooks/api/actions/useSignOnLogApi/useSignOnLogApi.ts, frontend/src/hooks/api/getters/useSignOnLog/useSignOnLog.ts, frontend/src/interfaces/signOnEvent.ts, frontend/src/interfaces/uiConfig.ts
https://linear.app/unleash/issue/2-719/display-basic-sign-on-log-in-frontend
Adds a basic, naïve way of displaying sign-on history. 
We can be OK with merging this for now if we want, given that it's behind a feature flag, and then iterate over it and implement the features and improvements we need in the meantime.
Relates to [roadmap](https://github.com/orgs/Unleash/projects/10) item: #2951
=> feat: display sign on log

frontend/src/component/common/Notifications/EmptyNotifications.tsx, frontend/src/component/common/Notifications/Notification.tsx, frontend/src/component/common/Notifications/Notifications.tsx, frontend/src/component/common/Notifications/NotificationsHeader.tsx, frontend/src/component/common/Notifications/NotificationsList.tsx, frontend/src/component/menu/Header/Header.tsx, frontend/src/hooks/api/actions/useNotificationsApi/useNotificationsApi.ts, frontend/src/hooks/api/getters/useNotifications/useNotifications.ts, frontend/src/openapi/models/createEnvironmentSchema.ts, frontend/src/openapi/models/notificationsSchemaItem.ts
This PR adds more capabilities to the notification UI. Including: 
* Displaying new notification types
* Update visual expression based on whether it's read or not
* Mark items as read
* Follow the items link to go to the notification destination
* Cleanup and styled components
=> Feat/notifications UI followup

.github/workflows/gradual-strict-null-checks.yml
This is a small improvement adding more context to the comment message when this action fails. This is what it'll comment:
https://github.com/Unleash/unleash/pull/3198#issuecomment-1446172703
=> docs: better comment in strictNullCheck action

frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingPlan.tsx
Previously Admin user was also billed, but it was never synced to auth-app. Make it unified, so only email users are billable.
=> feat: only email users billable

frontend/src/component/signOnLog/SignOnLogTable/SignOnLogTable.tsx, frontend/src/hooks/api/getters/useSignOnLog/useSignOnLog.ts
Adds `auth` as a table filter.
Also fixes the hook to correctly fetch the events based on the new return type.
=> feat: add authentication as a table filter

frontend/src/component/common/Feedback/Feedback.tsx, frontend/src/component/common/Notifications/Notifications.tsx, frontend/src/component/project/Project/ProjectStats/HelpPopper.tsx, frontend/src/hooks/usePlausibleTracker.ts
Adds plausible event tracking for notifications. Refactors Feedback component to be reusable and to ask whether or not this functionality is useful.
=> feat: implement plausible tracking

src/lib/services/access-service.ts
I have a use case where I need to check permissions for all project users. I only know their IDs. This new type will allow me to use this method. We only list parts of the IUser that are used inside the check.
=> refactor: make permission check type less demanding

frontend/src/component/signOnLog/SignOnLogTable/SignOnLogTable.tsx
https://linear.app/unleash/issue/2-729/adapt-signontable-to-use-querystored-sortsearch-params
Adds the feature where the current sort + search are reflected in the URL.
(notice the URL at the top)
=> feat: add url/query sort/search to sign on log table

frontend/src/component/signOnLog/SignOnLogTable/SignOnLogTable.tsx
Small change to make the `Authentication` column in the Sign-on Log table display nice-to-read labels for the multiple authentication types.
=> feat: smarter auth type labels on sign-on log table

frontend/src/component/project/Project/ProjectStats/ProjectStats.tsx
Display total changes correctly.
https://linear.app/unleash/issue/1-747/project-stats-displays-wrong-number-for-freshly-created-project
=> fix: project stats

src/lib/openapi/index.ts, src/lib/openapi/spec/bulk-metrics-schema.ts, src/lib/openapi/spec/client-metrics-env-schema.ts, src/lib/routes/client-api/feature.ts, src/lib/routes/edge-api/index.ts, src/lib/services/client-metrics/metrics-service-v2.ts, src/lib/services/client-metrics/schema.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
Change /edge/metrics endpoint to accept list of ClientMetricsEnv
We originally made the assumption that we probably didn't need to keep splitting from a map of features into ClientMetricsEnv for bulk, instead the bulk poster could post ClientMetricsEnv directly. However, Unleash still expected the old client metrics format with a dictionary of featurename -> metricsForFeature. This PR changes that to now accept the list of ClientMetricsEnv (preprocessed data from downstream) instead of expecting metrics to be in the old single application metric format.
=> fix: Make sure we agree on format for bulk metrics.

frontend/src/component/signOnLog/SignOnLogTable/SignOnLogDeleteAllDialog/SignOnLogDeleteAllDialog.tsx, frontend/src/component/signOnLog/SignOnLogTable/SignOnLogTable.tsx, frontend/src/hooks/api/actions/useSignOnLogApi/useSignOnLogApi.ts
Adds `Download sign-on log` and `Clear sign-on log` buttons to the UI, making it easy for admins to manage their sign-on log.
=> feat: add download and delete all buttons to sign-on log UI

src/lib/db/event-store.ts, src/lib/event-hook.ts, src/lib/features/export-import-toggles/createExportImportService.ts, src/lib/features/feature-toggle/createFeatureToggleService.ts, src/lib/services/index.ts, src/lib/types/stores/event-store.ts, src/lib/util/anyEventEmitter.ts, src/test/fixtures/fake-event-store.ts
EventStore is used as part of DB transactions (events should be stored when business operations succeed) and EventStores are used as EventEmitters to notify other modules (including notifications module).
We want to have correctness of DB transactions (impossible to store event after failed business operation) and correctness of notifications (impossible not to get a notification). This PR combines those 2 architectural drivers. 
Problem in a diagram:
Solution in code:
Composition over inheritance. Each EventEmitter should have HAS-A relationship to a shared EventEmitter. Previously it was IS-A relationship so we were getting a new emitter per EventStore instance. By making this dependency a singleton we make it impossible not to be notified about events no matter if we have one …
=> feat: shared event emitter

src/migrations/20230306103400-remove-direct-link-from-segment-permissions-to-admin.js
Tested manually as admin in enterprise:
Admin should have a special permission that gives super-powers. There's no need to have specific permissions linked to it.
Based of: https://github.com/Unleash/unleash/blob/a077967760f39df2f0fd7adf1db64d14df039326/src/migrations/20220307130902-add-segments.js#L32-L46
=> Remove link that's not necessary

src/lib/db/feature-toggle-client-store.ts, src/test/e2e/api/client/feature.e2e.test.ts
Client API should not return favorites.
Enabling check in tests so that we don't make the same mistake again.
For now moved favorites inclusion in the admin if path. Separate PR may split the store into client and admin if this turns out to be a viable strategy.
=> fix: exclude favorites from the client api

frontend/src/component/user/Profile/Profile.tsx
https://linear.app/unleash/issue/2-764/change-password-should-be-disabled-when-password-login-is-disabled
Hides "Change password" option on the profile page when "Password based login" is disabled.
=> fix: hide change password when simple auth is disabled

package.json
This allows us to run start:dev
=> fix: ignore null check on tsc-watch

src/lib/db/segment-store.ts, src/lib/services/segment-service.ts
~~Should we handle this on the store layer instead~~? 🤔
Fixing this on the store layer. Effectively, frontend is able to send `project: null` and even if that gets magically converted to `""` it's OK since we're covering that use case on the store layer. Backend response will be `project: null` as well, so it should be consistent.
=> fix: segment project null handling

frontend/src/component/segments/SegmentForm.tsx, frontend/src/component/segments/SegmentFormStepOne.tsx, frontend/src/component/segments/hooks/useSegmentForm.ts, frontend/src/interfaces/segment.ts, src/lib/db/segment-store.ts
Assume `undefined` instead of `null` for project in terms of interfacing with segments: If the `project` field is not present, that means that it is not set, which means we're dealing with a "global" segment. If we want to unset `project` and make a segment global, we simply don't send the `project` property on our PUT method.
=> fix: assume undefined instead of null on segment project

src/lib/services/access-service.test.ts, src/lib/services/access-service.ts, src/lib/types/stores/role-store.ts, src/lib/util/unique.test.ts, src/lib/util/unique.ts, src/test/e2e/services/access-service.e2e.test.ts, src/test/fixtures/fake-role-store.ts
Exposing project members and checking if a user is a member. We need this in the notifications service to send notifications to all project members. We also need this for checking who should be able to submit change requests in a protected model. Access service seems to be the holder of the core information so he owns the membership check.
Also fixed TS errors in all the files I touched.
=> feat: expose project members

src/lib/services/access-service.ts, src/lib/services/project-service.ts, src/test/e2e/services/access-service.e2e.test.ts, src/test/e2e/services/project-service.e2e.test.ts
Project user checking move from access service to project service. It was misplaced before. Calling it a project user to distinguish it from a member that has established meaning in our domain.
=> refactor: move project membership check from access to project

frontend/src/component/admin/Admin.tsx, frontend/src/component/admin/groups/EditGroup/EditGroup.tsx
This PR fixes an issue that would manifest when you navigated directly to the groups and tried to edit the group from the group card. When you were redirected to the edit groups view, the data fields would be empty. The root cause of this issue is that the data has not arrived over the wire before we load the UI, resulting in the UI showing an empty dataset. 
Normally, if this data came directly from useSWR, the app would re-render and display the data correctly. However, in this instance we are passing the data to an intermediary hook (useGroupForm) which does not have the same re-render logic. Therefore we are effectively working from stale data. We solve this issue by adding a container that resolves the group before the edit form is rendered, and that invokes the intermediary hook …
=> fix: add container for EditGroups

src/lib/routes/admin-api/project/index.ts
This PR fixes a bug where the api call to getProjectSettings was left hanging because no `end` was specified on the server
Closes #
=> fix: bug fix - `end` the response when projectScopedStickiness is disabled

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategySegment/FeatureStrategySegment.tsx
https://linear.app/unleash/issue/2-737/when-listing-segments-project-specific-segments-should-also-be-present
Simple filter on the UI for segments that are either global or for the specific project.
=> feat: filter segments by project on the strategy

frontend/src/component/project/Project/ProjectStats/ProjectStats.tsx, frontend/src/component/project/Project/ProjectStats/StatusBox.tsx, src/lib/db/project-stats-store.ts, src/lib/openapi/spec/project-stats-schema.ts, src/lib/services/project-service.ts, src/migrations/20230316092547-remove-project-stats-column.js, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/e2e/services/project-service.e2e.test.ts
This PR changes how we calculate average time to production. Instead of calculating fleeting 30 day windows and calculating the past and current window, we now calculate a flat average across the entire project life. This is less error prone as each feature will be tied to the earliest time it was turned on in a production environment.
=> fix: remove column

frontend/src/component/feature/StrategyTypes/FlexibleStrategy/StickinessSelect/StickinessSelect.tsx, frontend/src/hooks/useDefaultProjectSettings.ts
Code was failing on create project because project id is empty
=> fix: remove stickiness error

frontend/src/component/common/FormTemplate/FormTemplate.tsx, frontend/src/component/common/PageHeader/PageHeader.tsx, frontend/src/component/common/PremiumFeature/PremiumFeature.tsx, frontend/src/component/project/Project/ProjectSettings/ProjectSegments/ProjectSegments.tsx, frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx, frontend/src/component/segments/CreateSegment/CreateSegment.tsx, frontend/src/component/segments/CreateSegmentButton/CreateSegmentButton.tsx, frontend/src/component/segments/EditSegment/EditSegment.tsx, frontend/src/component/segments/EditSegmentButton/EditSegmentButton.tsx, frontend/src/component/segments/SegmentFormStepOne.tsx, frontend/src/component/segments/SegmentFormStepTwo.tsx, frontend/src/component/segments/SegmentTable.tsx, frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
https://linear.app/unleash/issue/2-743/have-a-project-specific-configuration-section
Adds the "segments" option to project settings, providing the usual CRUD operations but scoped to the specific project.
=> feat: implement project-scoped segments in project settings

website/docs/reference/deploy/configuring-unleash.md
This PR updates the docs to clarify that we don't support multi-host strings in the databaseUrl configuration variable.
The docs used to just mention that we accept libpq strings, but as reported in #3221, we **don't** support multi-host strings.
I did some digging and found that this is because [node-postgres -- the library we use to connect to postgres -- itself does not support multi-host strings](https://github.com/brianc/node-postgres/issues/2308).
To fix this, we would need to replace the library we use or otherwise wrap it. While this would be a better long-term solution, we don't have the capacity to it right now. But we can update the docs to better reflect reality.
=> docs: clarify that we don't support multi-host db urls

website/docs/tutorials/quickstart.md, website/docusaurus.config.js
This PR changes the syntax highlighting theme we use in the docs. The reason for the change is that the previous theme we used didn't have sufficient color contrast between its comment strings and its background.
I decided to use the Oceanic Next color theme that is included with docusaurus. Looking through, the only other dark theme that also passed AA contrast checks was VS Dark. The reason I picked Oceanic over VS Dark is simply that I like it better.
For demonstration, here's what the Oceanic theme looks like:
And here's the VS Dark theme:
The PR also includes a fix to render a pricing admonition correctly. It's not related to the PR, but I noticed it rendered incorrectly while I was working on it.
=> docs(a11y): update syntax highlighting theme to fix contrast issues

frontend/src/component/common/FormTemplate/FormTemplate.tsx, frontend/src/component/project/Project/ProjectSettings/ProjectSegments/ProjectSegments.tsx, frontend/src/component/segments/CreateSegment/CreateSegment.tsx, frontend/src/component/segments/EditSegment/EditSegment.tsx
Small fix that reverts https://github.com/Unleash/unleash/pull/3335/files#r1138829014 - Turns out it wasn't totally harmless and broke some modals that had more than 100% height and no overflow.
This approach maintains the original logic and adds a new prop for the segment forms to make them proper modals when used in the project context.
=> fix: revert form section 100 height

src/lib/features/export-import-toggles/export-import.e2e.test.ts, src/test/e2e/helpers/test-helper.ts
The idea of this PR is to propose a way of centralizing API calls while doing E2E tests to avoid repeating ourselves. 
In many places in our e2e tests, we end up doing the same thing over and over. I.e. to create features:
https://github.com/Unleash/unleash/blob/bc011e987673fa44cd72776bbc3d456eb03dfcb5/src/lib/features/export-import-toggles/export-import-permissions.e2e.test.ts#L47-L55
https://github.com/Unleash/unleash/blob/bc011e987673fa44cd72776bbc3d456eb03dfcb5/src/lib/features/export-import-toggles/export-import.e2e.test.ts#L134-L142
https://github.com/Unleash/unleash/blob/bc011e987673fa44cd72776bbc3d456eb03dfcb5/src/test/e2e/api/admin/project/project.health.e2e.test.ts#L36-L51
This PR is using the new API showing how it'd look like.
=> chore: PoC test API helper (DRY)

website/remote-content/edge-proxy.js
In preparation for Edge's stabilization, this PR removes the "under construction" admonition that was placed on the edge docs.
=> docs: remove "under construction" message for edge

frontend/src/component/segments/SegmentFormStepOne.tsx, frontend/src/component/segments/SegmentProjectAlert.tsx, frontend/src/hooks/api/getters/useStrategiesBySegment/useStrategiesBySegment.ts, src/lib/segments/segment-service-interface.ts, src/lib/services/segment-service.ts, src/test/e2e/api/client/segment.e2e.test.ts
https://linear.app/unleash/issue/2-811/ability-to-move-project-specific-segments
Provides some safeguards to project-specific segments when managing them on a global level (segments page):
- You can always promote a segment to global;
- You can't specify a project if the segment is currently in use in multiple projects;
- You can't specify a different project if the segment is currently already in use in a project;
=> Feat segments project safeguards

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx
Network overview was not escaping square brackets from app names and that caused mermaid graph to break. We've also identified problems with quotes and some characters not showing properly when using utf-8 (but still no solution for this). We're going to be testing the utf-8 issue in our sandbox instances.
=> fix: properly escaping app names

frontend/src/component/menu/Header/Header.tsx
https://linear.app/unleash/issue/1-802/replace-the-dark-mode-switch
**Note**: The second screenshot does not show the dark theme because that's part of https://github.com/Unleash/unleash/pull/3298
Improves the dark mode switch to be a simple IconButton that acts as a flip switch.
=> feat: dark mode switch

src/lib/middleware/rbac-middleware.test.ts, src/lib/middleware/rbac-middleware.ts
Previously every time there was permission **DELETE_FEATURE** or **UPDATE_FEATURE** needed, it expected to have `featureName` in path parameters.
Now that we introduced batch operations, for example batch deletion of features, the `featureName` will not be in parameters, but instead the `projectId` is provided as path parameter.
This PR makes following change:  now `projectId` from path parameters will be used instead of making a database call to find the `projectId` from feature.
=> fix: use projectId from param

frontend/src/component/project/Project/ProjectForm/CollaborationModeTooltip.tsx, website/sidebars.js
This change does to things:
-   Adds project collaboration mode docs to the sidebar
-   Fixes a casing inconsistency in the collaboration mode tooltip: previously, one of the explanations started with a lowercase character and the other with an uppercase character. Now they both start with lowercase characters.
=> Add collab mode docs to side bar + fix casing inconsistency in tooltip

frontend/src/component/common/BatchSelectionActionsBar/BatchSelectionActionsBar.tsx
Currently the component was not on top of all elements in feature table. Can be seen in enterprise instance.
This PR fixes it.
=> fix: fix transparancy of sticky component

frontend/src/component/common/SkipNavLink/SkipNavLink.tsx, frontend/src/component/menu/Header/Header.tsx
- when introducing dark mode icon in the header, on tablet the menu items don't have enough space anymore, and this fix it
- fixing also the color for dark mode of the keyboard nav button "skip to content"
=> fix: header-responsiveness

src/lib/routes/client-api/feature.ts, src/test/e2e/api/client/feature.optimal304.e2e.test.ts
According to the
[RFC](https://www.rfc-editor.org/rfc/rfc7232#section-2.3) Etags should be enclosed in double quotes. This PR makes sure we do actually wrap it in double quotes
=> task: enclose ETag in double quotes.

src/lib/db/event-store.ts, src/lib/server-impl.ts, src/lib/services/index.ts, src/lib/services/project-service.ts, src/lib/types/stores/event-store.ts, src/test/e2e/services/project-service.e2e.test.ts, src/test/fixtures/fake-event-store.ts
Refactor project events to use count instead of loading the events in memory
=> fix: count events instead of loading them in memory

frontend/src/component/App.tsx
Move plausible available for the error boundary.
Previously:
* plausible provider was much deeper than the error boundary so the error handler didn't get access to the tracker
After:
* error boundary moved below the plausible provider 
* another error boundary added for the plausible provider itself
This is just a few LOC but the formatting kicked in
=> fix error boundary

frontend/src/component/admin/apiToken/ApiTokenForm/EnvironmentSelector/EnvironmentSelector.tsx, frontend/src/component/admin/apiToken/CreateApiToken/CreateApiToken.tsx, frontend/src/component/project/Project/ProjectSettings/ProjectApiAccess/CreateProjectApiTokenForm.tsx
Makes the api token environment selector accept options to allow different environment to be passed in according to the use case ie use all envs when creating api tokens and use project envs when creating project scoped tokens
Closes [# 1-811](https://linear.app/unleash/issue/1-811/change-environment-dropdown-to-show-all-environments-enabled-for-the)
=> fix: Make api token environment selector accept environments

frontend/src/component/common/Notifications/Notification.tsx, website/docs/reference/deploy/environment-import-export.mdx
This PR fixes the issue that long feature names did not break line and created a horizontal scrollbar to notifications.
=> fix: notifcations word break

src/lib/db/project-store.ts
Profile projects were not showing correctly in most cases. This fixes the query to only take into consider whether you have access to the project (either directly or through a group).
=> fix: show profile projects correctly

website/docusaurus.config.js
This change adds google tag manager to docusaurus using the [plugin-google-tag-manager](https://www.docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-tag-manager) plugin.
The current analytics integration we've got in the docs is being sunset this year, so this is the replacement. It should only collect the same kind of data that we already collect. It does not require user consent, and it is used only for aggregation. The point is to help us understand our users' needs and usage patterns so that we can make a better product.
=> docs: add google tag manager

frontend/src/component/admin/users/CreateUser/SeatCostWarning/SeatCostWarning.tsx
https://unleash-community.slack.com/archives/C033ES94QMT/p1680236503981349
Fixes the user creation extra seat billing alert to only show when the total users exceed the number of free seats.
=> fix: proper check for billing seats on user creation

website/docs/reference/deploy/getting-started.md
This link used to post to the now-outdated unleash-docker repo. They should instead go directly to the unleash repo now.
=> docs: point link to unleash/unleash instead of unleash-docker

src/lib/routes/admin-api/api-token.ts, src/lib/routes/admin-api/project/api-token.ts, src/lib/services/proxy-service.ts, src/test/e2e/api/proxy/proxy.concurrency.e2e.test.ts
Running multiple calls to the frontend concurrently creates many instances of unleash SDK client.
The test added in commit 34004b5be5f41d5cad646ce9e18cd1e307119ceb is to verify we can reproduce the issue with a test case, and we can see the error [here](https://github.com/Unleash/unleash/actions/runs/4596689332/jobs/8118467530?pr=3442#step:5:571)
The next commit introduces a fix for the issue
1. Start Unleash (it has to be a fresh application: to retry the test, first restart Unleash)
2. Run: 
```shell
#!/usr/bin/env bash
i=0
while [ $i -ne 15 ]
do
curl http://localhost:4242/api/frontend -H 'Authorization: *:development.5487836a72f472d3494d92134fab6b4e07fcffe84c6c81a1d78448d0' &
echo $i
(( i=i+1 ));
done
```
You should see some errors, such as: 
```shell
[2023-04-03T10:48:49.818] [ERROR] …
```
=> fix: concurrency issue when running multiple requests

src/lib/services/reset-token-service.ts, src/lib/services/user-service.ts, src/lib/types/stores/reset-token-store.ts, src/test/e2e/api/auth/reset-password-controller.e2e.test.ts
Usecase:
1. User requests a forgot password link
2. User changes password normally
3. User can still reset password through the link
This is a security risk and now reset password tokens are invalidated.
=> feat: changing password will expire reset password tokens

frontend/src/component/user/UserProfile/UserProfileContent/UserProfileContent.tsx, src/lib/app.ts, src/lib/middleware/authorization-middleware.ts, src/lib/middleware/oss-authentication.test.ts, src/lib/middleware/oss-authentication.ts, src/lib/middleware/session-db.ts, src/lib/routes/logout.test.ts, src/lib/routes/logout.ts, src/test/e2e/api/admin/user/pat.e2e.test.ts
1. Added `sameSite: 'lax'`or CSRF.
2. Added authorization middleware to also have authentication on` /logout` endpoint.
=> feat: authorization middleware

src/lib/db/feature-toggle-store.ts, src/lib/services/project-service.ts, src/lib/types/stores/feature-toggle-store.ts, src/test/fixtures/fake-feature-toggle-store.ts
Counting stats at the DB level instead of loading whole features into memory. Result: less memory used.
Potential next steps:
* more savings in other queries (I started with the lowest hanging fruit)
* extract project stats store/read model
=> feat: save memory on reading stats

docker/package.json, docker/yarn.lock
path-scurry 1.6.4 needs node version 16. Fixed to 1.6.3.
=> fix: fix path-scurry resolution

src/lib/openapi/index.test.ts, src/lib/openapi/index.ts, src/lib/openapi/meta-schema-rules.test.ts, src/lib/openapi/spec/meta-schema.test.ts
This enables us to validate the shape of our OpenAPI schemas by defining specific json-schema rules that will be evaluated against all our open API schemas.
Because we know there are things we need to improve, we've added a list of `knownExceptions`. When fixing some of the known exceptions the tests will force us to remove the exception from the list, that way contributing to reducing the number of violations to our own rules.
Co-authored-by: Mateusz Kwasniewski <kwasniewski.mateusz@gmail.com>
Co-authored-by: Thomas Heartman <thomas@getunleash.io>
=> chore: test requirements for openapi

frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.test.tsx, frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx, frontend/src/component/changeRequest/ChangeRequest/Changes/Change/Change.tsx, frontend/src/component/changeRequest/changeRequest.types.ts
When CR is not applied we show a default strategy that will be added:
The default one doesn't count into all the changes count since it's not something a user added.
After applying the default one goes away:
=> feat: visualize adding a default strategy

src/lib/openapi/index.test.ts, src/lib/openapi/index.ts, src/lib/openapi/spec/bulk-metrics-schema.ts, src/lib/openapi/spec/bulk-registration-schema.ts, src/lib/openapi/spec/client-metrics-env-schema.ts, src/lib/openapi/spec/edge-token-schema.ts, src/lib/openapi/spec/index.ts, src/lib/openapi/spec/token-string-list-schema.ts, src/lib/openapi/spec/validate-edge-tokens-schema.ts, src/lib/openapi/spec/validated-edge-tokens-schema.ts, src/lib/openapi/util/standard-responses.ts, src/lib/routes/edge-api/index.ts, src/lib/services/edge-service.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
Adding documentation for the edge endpoints. Also separating request and response schema for our validate endpoint to make clear that we expect a list of strings as input, but yield tokens as output.
=> docs: Added docs for edge endpoints

src/lib/services/project-service.ts, src/lib/types/api-user.ts, src/lib/types/group.ts, src/lib/types/user.ts
This change removes uses of the `TypeError` type from user-facing code. Type errors are used by typescript when you provide it the wrong type. This is a valid concern. However, in the API, they're usually a signal that **we've** done something wrong rather than the user having done something wrong. As such, it makes more sense to return them as validation errors or bad request errors.
Note that because of the way we handle errors, some of these changes will be made visible to the end user, but only in the response body.
```ts
{ "name": "TypeError", "message": "Something is wrong", "isJoi": true }
```
will become
```ts
{ "name": "ValidationError", "message": "Something is wrong", "isJoi": true }
```
Technically, this could be considered a breaking change. However, as we're gearing up for …
=> chore: remove uses of type errors from user-facing code

CONTRIBUTING.md, scripts/docker-compose.yml, src/server-dev.ts, src/test/e2e/helpers/database-config.ts, website/docs/contributing/backend/overview.md, website/docs/reference/deploy/configuring-unleash.md, website/docs/reference/deploy/securing-unleash.md
Update `passord` documentation with `password`. Note this was not a typo but just Norwegian: https://dictionary.cambridge.org/dictionary/english-norwegian/password
```shell
grep passord * -R -l | grep -v .git | grep -v dist | grep -v v3 | xargs sed -i 's/passord/password/g'
```
The script above avoids updating v3 because of legacy reasons
Related to #1265
=> docs: update documentation and dev server use of passord

src/lib/db/feature-tag-store.ts, src/lib/routes/admin-api/feature.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/e2e/stores/feature-tag-store.e2e.test.ts
From the discussion here https://github.com/Unleash/unleash/pull/3496#discussion_r1163745860
This PR checks the existence of the feature before trying to get tags for the feature. Doing so by stealing the exists method from the feature store, since that's what we need to know exists, and avoiding having the feature store as a dependency to the featureTagStore seemed reasonable.
=> fix: return 404 when gettings tags for a non existing feature

package.json, src/test/e2e/seed/segment.seed.ts
Seed setup fails because of compilation errors, we need to skip errors until we fix them. Also, this removes one usage of `/api/admin/features` that was used only for testing
=> fix: seed setup and remove admin/features call

frontend/src/component/strategies/StrategiesList/StrategiesList.tsx, src/lib/routes/admin-api/strategy.test.ts, src/lib/routes/admin-api/strategy.ts, src/migrations/20230420125500-v5-strategy-changes.js, src/migrations/default-strategies.json, src/test/e2e/api/admin/strategy.e2e.test.ts, src/test/e2e/api/client/feature.optimal304.e2e.test.ts
Improvements around strategies to steer users toward using [strategy constraints](https://docs.getunleash.io/reference/strategy-constraints) instead of [custom strategies](https://docs.getunleash.io/reference/custom-activation-strategies)
Related to #1265 
Important changes:
1.[ Ability to deprecate default strategy](https://github.com/Unleash/unleash/pull/3575/files#diff-3b49e566565b01580ff7a15f662d2cb824547fdfb3935d0a0baa7fae326d28d6L232-L235)
2. [Remove strategies that were deprecated in v4 only if they're not used](https://github.com/Unleash/unleash/pull/3575/files#diff-a04de7adf327c48d54b030bed70d9b1d62ff14df3efc668eb6897a210124ebe0R7-R10)
3. [Fresh Unleash installations will not include deprecated strategies from v4](https://github.com/Unleash/unleash/pull/3575/files#diff-46265b0d517 …
=> chore: remove deprecated strategies and allow deprecate default

website/sidebars.js
It seems that we forgot to add this doc to the sidebar. This PR fixes that
=> docs: add sidebar entry for project API tokens guide

frontend/src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/ConstraintAccordionEditBody.tsx, frontend/src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/FreeTextInput/FreeTextInput.tsx, frontend/src/component/common/ConstraintAccordion/ConstraintAccordionList/ConstraintAccordionList.tsx, frontend/src/component/demo/DemoSteps/DemoSteps.tsx, frontend/src/component/demo/demo-topics.tsx
https://linear.app/unleash/issue/2-961/update-demo-guide-steps-to-not-include-a-userids-strategy
Updates the user-specific toggle topic to use a standard strategy with a constraint instead (deprecate UserID strategy).
=> feat: update the user-specific topic

src/lib/app.ts, src/lib/error/api-error.test.ts, src/lib/error/api-error.ts, src/lib/error/no-access-error.ts, src/lib/features/export-import-toggles/export-import-service.ts, src/lib/features/export-import-toggles/export-import.e2e.test.ts, src/lib/middleware/authorization-middleware.ts, src/lib/middleware/content_type_checker.test.ts, src/lib/middleware/content_type_checker.ts, src/lib/openapi/util/standard-responses.ts, src/lib/routes/admin-api/addon.ts, src/lib/routes/admin-api/strategy.test.ts, src/lib/routes/proxy-api/index.ts, src/lib/routes/util.ts, src/lib/services/addon-service.ts, src/lib/services/openapi-service.ts, src/lib/services/user-service.ts, src/test/e2e/api/admin/api-token.e2e.test.ts, src/test/e2e/api/admin/feature.e2e.test.ts, src/test/e2e/api/admin/project/environments.e2e.test.ts, src/test/e2e/api/admin/project/features.e2e.test.ts, src/test/e2e/api/admin/project/variants.e2e.test.ts, src/test/e2e/api/admin/tag-types.e2e.test.ts, src/test/e2e/api/admin/tags.e2e.test.ts, src/test/e2e/api/admin/user-admin.e2e.test.ts, src/test/e2e/api/auth/reset-password-controller.e2e.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/e2e/services/access-service.e2e.test.ts, src/test/e2e/services/project-service.e2e.test.ts
This PR implements the first version of a suggested unification (and documentation) of the errors that we return from the API today.
The goal is for this to be the first step towards the error type defined in this internal [linear task](https://linear.app/unleash/issue/1-629/define-the-error-type 'Define the new API error type').
As things stand, we currently have no (or **very** little) documentation of the errors that are returned from the API. We mention error codes, but never what the errors may contain.
Second, there is no specified format for errors, so what they return is arbitrary, and based on ... Who knows? As a result, we have multiple different errors returned by the API depending on what operation you're trying to do. What's more, with OpenAPI validation in the mix, it's …
=> feat: unify error responses

src/lib/error/api-error.ts, src/test/e2e/api/admin/feature.e2e.test.ts
This PR fixes a broken e2e test by relaxing what it checks for. It must have been developed in parallel so that the test wasn't included before merging into main.
=> fix: broken feature.e2e test + make error message clearer

src/lib/error/api-error.test.ts, src/lib/error/api-error.ts, src/lib/features/export-import-toggles/export-import-service.ts, src/lib/features/export-import-toggles/export-import.e2e.test.ts, src/lib/routes/admin-api/strategy.test.ts, src/test/e2e/api/admin/project/features.e2e.test.ts, src/test/e2e/services/access-service.e2e.test.ts, src/test/e2e/services/project-service.e2e.test.ts
A number of `expect` calls didn't have a thing they expected, so they always passed.
This was due to a wrong assumption on my part, where I assumed `expect(false)` would fail a test. It doesn't.
=> fix: add truth checks to a number of jest tests.

frontend/src/component/demo/Demo.tsx, frontend/src/component/demo/DemoBanner/DemoBanner.tsx, frontend/src/component/demo/DemoDialog/DemoDialogPlans/DemoDialogPlans.tsx, frontend/src/component/demo/DemoDialog/DemoDialogWelcome/DemoDialogWelcome.tsx, frontend/src/component/demo/DemoSteps/DemoSteps.tsx, frontend/src/hooks/usePlausibleTracker.ts
https://linear.app/unleash/issue/2-946/explore-and-implement-options-for-user-tracking
Adds user tracking to the interactive demo, so we can measure how users are using this feature and improve it in the feature.
- **start** - When the user starts the demo by clicking on the "Try Unleash Demo" button;
- **finish** - When the user finishes the demo by seeing the "You finished the demo" dialog;
- **restart** - When the user decides to restart the demo on the "You finished the demo" dialog;
- **close** - When the user closes a demo dialog;
- **topic** - In what topic this happened (topic title, can also be `start` if user closes on the start dialog);
- **step** - In what step this happened (step number, `1` would mean first step);
- **start_topic** - When the user decides to start a specific …
=> feat: add user tracking to demo

src/lib/error/api-error.test.ts, src/lib/error/api-error.ts
This fixes a bug where the owasp validation response that came back from the server no longer contained all its validation errors. This caused the UI to slightly break and for the password validation box not to update correctly.
This is a quick fix (but with tests!). I'm working on a better design for this on the side, but it seemed pertinent to get this out ASAP.
=> fix: ensure that the owaspvalidationerrors always contain all errors

src/lib/db/context-field-store.ts
When adding a strategy using a context field that did not exist, we threw an unknown error. 
This changes to throw NotFoundError so that our users can better know what they did wrong.
=> fix: correct error for missing context field

src/lib/db/feature-tag-store.ts, src/test/e2e/api/admin/tags.e2e.test.ts
Currently if you had multiple tags and wanted to remove a tag from a batch of features, the request failed.
This PR fixes it.
=> fix: fix bulk removal of tags

frontend/src/component/demo/DemoBanner/DemoBanner.tsx, frontend/src/component/demo/DemoSteps/DemoSteps.tsx, frontend/src/component/demo/DemoTopics/DemoTopics.tsx, frontend/src/component/demo/demo-topics.tsx
https://linear.app/unleash/issue/2-975/small-ui-adjustments
Adds some small UI adjustments we identified in the meantime:
- "Get Unleash" -> "Get started" in the top banner;
- Topics list header is now the same color as the top banner;
- Added `focus` capabilities to steps, added it to the appropriate steps;
- No longer closes tooltip when clicked when using `anyClick`;
- Reversed the topics list header arrow rotation;
=> feat: demo small UI adjustments

frontend/src/component/demo/DemoSteps/DemoSteps.tsx, frontend/src/component/demo/demo-topics.tsx
https://linear.app/unleash/issue/2-983/can-we-we-reverse-order-of-the-toggles
This PR makes it so that, on topic navigation to the project overview page, we assume a feature toggle name sorting by default:
=> feat: demo sorts features by name

Dockerfile, package.json
If Unleash is running in a timezone other than UTC, the metrics bucket values will be incorrect by the corresponding number of hours. We need to decide whether we should allow Unleash to run in other timezones or if we should modify the code to enforce UTC.
We decided to set timezone to UTC. There are two ways to do it, during runtime and before starting node. We decided to go with environment variable, because setting at runtime produces non-deterministic behaviour. Source https://github.com/nodejs/node-v0.x-archive/issues/3286. 
An example, metrics was posted at 13:00+3, and was stored in database 13:00+0. After setting application timezone, it is now stored 10:00+0
=> feat: set timezone to utc

src/lib/routes/admin-api/event.ts, src/lib/routes/admin-api/events.test.ts
https://linear.app/unleash/issue/2-987/unleash-is-not-correctly-anonymizing-emails-in-the-project-events
Context: https://unleash-internal.slack.com/archives/C048ELND3QD/p1683097636083299
We should also anonymize email fields in `data` and `preData` of event objects when `anonymiseEventLog` is enabled.
=> fix: anonymize email in event payload

frontend/src/component/demo/Demo.tsx, frontend/src/component/demo/DemoSteps/DemoStepTooltip/DemoStepTooltip.tsx, frontend/src/component/demo/DemoSteps/DemoSteps.tsx, frontend/src/component/demo/DemoTopics/DemoTopics.tsx, frontend/src/component/demo/demo-topics.tsx, frontend/src/themes/dark-theme.ts, frontend/src/themes/theme.ts, frontend/src/themes/themeTypes.ts
https://linear.app/unleash/issue/2-986/feedback-from-sebastian
Implements the items mentioned in the task:
- Refactors logic to track completion separately;
- When finishing a topic, jumps to the next unfinished topic it can find;
- Shows the finish dialog when finishing a topic, as long as completion is 100%;
- Changes the guide overlay behavior and implements the necessary changes to adapt to light and dark mode;
- Fixes an issue where some guide dialogs would close when clicking outside;
- Added a final "toggle" step for each topic (still needs alignment, different task);
- Improve navigation logic to hopefully fix the feature toggle name sorting;
=> feat: demo guide improvements

frontend/src/component/demo/DemoSteps/DemoSteps.tsx, frontend/src/component/demo/DemoTopics/DemoTopics.tsx, frontend/src/component/demo/demo-setup.ts, frontend/src/component/demo/demo-topics.tsx
https://linear.app/unleash/issue/2-1005/small-ui-improvements
https://linear.app/unleash/issue/2-1020/fix-issues-with-interactive-demo-guide
Tackles the 2 tasks above, which include items such as:
- Change drop-shadow of step tooltips;
- Change transparency of overlay;
- Change box-shadow of topics "widget";
- Gradual rollout should use `default` stickiness;
- Improve last step behavior when redirecting (add optional delay);
=> fix: small fixes for the interactive demo guide

src/lib/routes/admin-api/event.ts, src/lib/routes/admin-api/events.test.ts, src/lib/services/project-service.ts, src/lib/types/events.ts, src/lib/util/anonymise.ts
https://linear.app/unleash/issue/2-992/register-event-when-granting-access-to-a-project
- Correctly registers a new `project-access-added` event;
- Adds an anonymization method that supports anonymizing objects, recursively searching for keys to anonymize;
- Fixes the event label used by `ProjectUserUpdateRoleEvent` to be `PROJECT_USER_ROLE_CHANGED`;
=> fix: log project access events

frontend/src/component/common/common.module.scss
https://linear.app/unleash/issue/2-1021/bug-dark-mode-application-screen-name-of-the-application-not-visible
Applies the styling changes mentioned in the task above, fixing the style in dark mode and making these links more consistent in general.
Closes https://github.com/Unleash/unleash/issues/3718
=> fix: application name link styling

frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.test.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.tsx
Fixes a small issue where the "API Command" for edit strategy was showing the strategyId as `undefined`:
`/api/admin/projects/demo-app/features/demoApp.step1/environments/dev/strategies/undefined'`
=> fix: strategyId in edit strategy API command endpoint

src/lib/middleware/pat-middleware.test.ts, src/lib/middleware/pat-middleware.ts
When using PATs if the user that the PAT is for has been removed, we currently log the missing user at ERROR level. Since this is not something our SREs can fix, this PR downgrades the NotFoundError to WARN, instead of ERROR.
=> fix: log missing user at warn level

frontend/src/component/admin/apiToken/ConfirmToken/ConfirmToken.tsx, frontend/src/component/admin/instance-admin/InstanceStats/InstanceStats.tsx, frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountModal/ServiceAccountModal.tsx, frontend/src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/DateSingleValue/__snapshots__/DateSingleValue.test.tsx.snap, frontend/src/component/common/InstanceStatus/__snapshots__/InstanceStatusBar.test.tsx.snap, frontend/src/component/common/MessageBanner/MessageBanner.tsx, frontend/src/component/common/PremiumFeature/PremiumFeature.tsx, frontend/src/component/demo/DemoBanner/DemoBanner.tsx, frontend/src/component/demo/DemoDialog/DemoDialogPlans/DemoDialogPlans.tsx, frontend/src/component/demo/demo-topics.tsx, frontend/src/component/environments/EnvironmentTable/EnvironmentActionCell/EnvironmentCloneModal/EnvironmentCloneModal.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategySegment/FeatureStrategySegmentChip.tsx, frontend/src/component/feedback/FeedbackCES/__snapshots__/FeedbackCESForm.test.tsx.snap, frontend/src/component/menu/Footer/ApiDetails/__snapshots__/ApiDetails.test.tsx.snap, frontend/src/component/menu/Footer/Footer.tsx, frontend/src/component/menu/Footer/__snapshots__/Footer.test.tsx.snap, frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap, frontend/src/component/segments/SegmentProjectAlert.tsx, frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
https://linear.app/unleash/issue/2-1043/ensure-that-links-with-target=-blank-include-rel=noreferrer-to-prevent
Ensures that links with `target="_blank"` include `rel="noreferrer"` to prevent warnings such as:
https://mathiasbynens.github.io/rel-noopener/#recommendations
=> fix: ensure rel=noreferrer on target=_blank

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/create-config.ts, src/lib/features/feature-toggle/config-client/toggle-config-change-emitter.ts, src/lib/features/feature-toggle/configuration-revision-service.ts, src/lib/proxy/proxy-repository.ts, src/lib/routes/client-api/feature.test.ts, src/lib/routes/client-api/feature.ts, src/lib/services/event-service.ts, src/lib/services/index.ts, src/lib/services/proxy-service.ts, src/lib/types/services.ts, src/test/e2e/api/client/feature.optimal304.e2e.test.ts
This PR reuses the revision Id information from the "optimal 304 for server SDKs" to improve the freshness of the frontend API config data. 
In addition it allows us to reduce the polling (and eventually remove it when we are confident).
=> feat: improve frontend config freshness to < 1s

frontend/src/component/demo/Demo.tsx, frontend/src/component/demo/DemoDialog/DemoDialog.tsx, frontend/src/component/demo/DemoDialog/DemoDialogWelcome/DemoDialogWelcome.tsx
Improves the dialogs behavior to address https://linear.app/unleash/issue/2-1053/bug-when-big-dialog-is-open-if-you-click-on-a-step-the-flow-is-broken
Also prevents close on backdrop click for the welcome dialog.
=> fix: demo guide dialogs behavior

src/lib/error/unleash-error.test.ts, src/lib/types/authentication-required.ts
This PR adds the missing serialization of the AuthenticationRequired response back in. It was mistakenly removed in #3633.
This PR also adds another test to verify that it the options property is present.
=> fix: add missing options parameter back in

src/lib/routes/admin-api/user-admin.ts, src/lib/util/anonymise.ts, src/test/e2e/api/admin/user-admin.e2e.test.ts
In the demo when listing possible users to grant access to your project, we inadvertently expose emails when listing users you can grant access to. This PR anonymises the access list on the way out.
=> fix: anonymise PII fields in user access if flag is set

src/lib/db/group-store.ts, src/lib/services/group-service.ts, src/lib/types/stores/group-store.ts, src/test/e2e/services/group-service.e2e.test.ts, src/test/fixtures/fake-group-store.ts
Blocks adding a root role to a group that already has a project role.
This is a bug and a confusing one at that. The group role mapping is an either/or - you either get project permissions _or_ you get a root role, but not both. Blocking this flow makes this a little saner to use.
=> fix: block adding a root role to a group with a project role

frontend/src/component/common/MessageBanner/MessageBanner.tsx, frontend/src/hooks/useVariant.ts, frontend/src/interfaces/uiConfig.ts, frontend/src/utils/variants.ts, package.json, src/lib/__snapshots__/create-config.test.ts.snap, src/lib/openapi/index.ts, src/lib/openapi/meta-schema-rules.test.ts, src/lib/openapi/spec/index.ts, src/lib/openapi/spec/proxy-feature-schema.ts, src/lib/openapi/spec/ui-config-schema.ts, src/lib/openapi/spec/variant-flag-schema.ts, src/lib/types/experimental.ts, src/lib/util/feature-evaluator/variant.ts, src/lib/util/flag-resolver.test.ts, src/lib/util/flag-resolver.ts, src/lib/util/offline-unleash-client.ts, src/server-dev.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, yarn.lock
- https://linear.app/unleash/issue/2-546/fetch-the-payload-from-a-real-feature-flag
- https://linear.app/unleash/issue/2-547/adapt-ui-to-use-the-feature-flag-information-were-fetching
Tackles the 2 tasks above. 
Adapts our `FlagResolver` logic to support variants, so we can use them for our message banner project but also anything else in the future. Also adapts MessageBanner to the new logic.
- Add support for variants in `FlagResolver`;
- Adapt `MessageBanner` to a variants flag;
- Adds `sticky` support for the `MessageBanner`;
- Adds our first variants flag to `uiConfig` and `experimental`: `messageBanner`;
- Adds a `variant-flag-schema` to make it easy to represent the variant output that we specify in `uiConfig`;
- Adapts `experimental` to be able to represent default variants while …
=> feat: message banner (variants)

frontend/src/component/demo/Demo.tsx, frontend/src/component/demo/DemoBanner/DemoBanner.tsx, frontend/src/component/demo/DemoDialog/DemoDialogPlans/DemoDialogPlans.tsx, frontend/src/component/demo/DemoDialog/DemoDialogWelcome/DemoDialogWelcome.tsx, frontend/src/component/demo/DemoSteps/DemoSteps.tsx, frontend/src/hooks/usePlausibleTracker.ts
Splits the `demo` event into multiple more specific events so it's easier to track on Plausible (fix `(none)` in Plausible).
=> refactor: change plausible events to be more specific at the top level

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/MenuStrategyRemove/DisableEnableStrategyDialog/DisableEnableStrategyDialog.tsx, frontend/src/component/strategies/CreateStrategy/CreateStrategy.tsx, frontend/src/component/strategies/CustomStrategyInfo/CustomStrategyInfo.tsx, frontend/src/component/strategies/StrategiesList/AddStrategyButton/AddStrategyButton.tsx, frontend/src/component/strategies/StrategiesList/StrategiesList.tsx
- split strategies table in two
- one for predefined strategies
- one for custom strategies
- move custom strategy button
- add guidance why custom strategies are not recommended
https://linear.app/unleash/issue/1-894/improve-the-list-of-strategies
=> Update strategies table

.github/workflows/gradual-strict-null-checks.yml
This action started to fail and despite being safe to ignore it's still annoying. I'm disabling it for now until I can look into what's going on with it
Example:
https://github.com/Unleash/unleash/pull/3829#issuecomment-1557372501
=> chore: disable null checks until we have time to fix this

.github/workflows/notify_enterprise.yaml
These logs will help us identify what should we use instead of https://github.com/Unleash/unleash/blob/e55e7feed36345c64fee976bc042cb5fb58e94de/.github/workflows/notify_enterprise.yaml#L56 which is being set to web-flow https://github.com/Unleash/unleash/actions/runs/5055463116/jobs/9071696845#step:7:12
=> test: Add debug logs

frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.tsx
Related to [linear task 1-954](https://linear.app/unleash/issue/1-954/disabling-last-strategy-in-change-request-shows-strikethrough).
This PR changes the display logic for showing titles as changed: it previously fell back to always being `true` if there was a custom title set for a strategy. This PR makes it so that it only shows as changed if the title has actually changed, either from one custom title to another, or to and from the display name.
To accommodate the last bit, it also shows display names with a strikethrough if the strategy had no title previously, but now it does.
Here's a number of different examples:
=> fix: Only show names as changed when titles have changed.

frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx, frontend/src/component/admin/auth/PasswordAuth/PasswordAuth.tsx, frontend/src/component/admin/auth/PasswordAuth/PasswordAuthDialog.tsx, frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx, frontend/src/hooks/api/getters/useAdminCount/useAdminCount.ts, src/lib/db/account-store.ts, src/lib/openapi/index.ts, src/lib/openapi/meta-schema-rules.test.ts, src/lib/openapi/spec/admin-count-schema.ts, src/lib/openapi/spec/index.ts, src/lib/routes/admin-api/user-admin.ts, src/lib/services/account-service.ts, src/lib/types/stores/account-store.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap, src/test/fixtures/fake-account-store.ts
https://linear.app/unleash/issue/2-1071/prevent-users-from-disabling-password-authentication-when-there-are-no
Improves the behavior of disabling password based login by adding some relevant information and a confirmation dialog with a warning. This felt better than trying to disable the toggle, by still allowing the end users to make the decision, except now it should be a properly informed decision with confirmation.
- **Password based administrators**: Admin accounts that have a password set;
- **Other administrators**: Other admin users that do not have a password. May be SSO, but may also be users that did not set a password yet;
- **Admin service accounts**: Service accounts that have the admin root role. Depending on how you're using the SA this may not necessarily mean locking …
=> fix: add confirmation to disable password login

.github/workflows/notify_enterprise.yaml
Delay static asset generation to speed up the CI/CD pipeline.
Next, we should add a validation step before deployment to validate that the static assets were properly published
=> chore: delay static asset generation

src/lib/error/unleash-error.test.ts, src/lib/types/authentication-required.ts
https://linear.app/unleash/issue/2-1085/bug-password-based-login-still-shows-on-the-login-page-even-if
Fixes a regression introduced with the changes related with #3633 where we still show the password login even though it's disabled.
=> fix: hide password login when it's disabled

frontend/src/component/user/Profile/Profile.tsx
Small change that makes it so that the profile page waits for the loaded state before rendering.
E.g. Before this, there was a flash of the "change password" tab being visible for a very short time before the auth settings loaded.
=> fix: profile should wait for loaded state before rendering

frontend/src/component/user/Profile/PasswordTab/PasswordTab.tsx
Accessing `/profile/change-password` directly would still allow you to change your password on the UI when "password based login" is disabled.
This PR makes it so we show an alert in that scenario explaining why you're not allowed to change your password.
We still allow users to change their password on the API level, but I think that's fine. The UI should be consistent though.
=> fix: change password alert when password based login is disabled

frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectDefaultStrategySettings.tsx, frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/ProjectDefaultStrategyForm.tsx, frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/ProjectEnvironmentDefaultStrategy.tsx
Fixes the default strategy modal.  
The bug was the placement of the route component to `edit`
Closes # https://linear.app/unleash/issue/1-965/fix-default-strategy-modal-re-render
=> fix: default strategy screen not loading

src/lib/db/event-store.ts
We had a small typo where we looked for `segment-update` event instead of `segment-updated`. Changed to use the event constant.
=> fix: use correct event type for maxRevisionId

.github/workflows/release.yaml
Minor improvement to communicate the author of a commit as `Name <Email>`
Another option is to send email and name in different fields but we're only using it here https://github.com/ivarconr/unleash-enterprise/blob/master/.github/update_dependency_version.sh#L39 so this should be fine
=> chore: name and email convention

.github/workflows/notify_enterprise.yaml, .github/workflows/release.yaml
Sync fails https://github.com/Unleash/unleash/actions/runs/5174602051/jobs/9321118800#step:3:23 due to https://github.com/ivarconr/unleash-enterprise/pull/562 because we now assume the repository is Unleash/unleash
This removes the repository from the payload
=> fix: Remove repository which is no longer needed

frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.test.tsx, frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.tsx
* displaying strategy name and type at the same time
* when configuring default strategy also description is added as it was before
* added a test as this piece of code wasn't covered before
=> feat: display strategy title and type

Dockerfile
This removes unnecessary build that's already triggered as part of the prepare script https://github.com/Unleash/unleash/blob/0efaa346c45b1d8aea064c7649ad617c9da1f499/package.json#L41
This should reduce the build time of this action: https://github.com/Unleash/unleash/actions/workflows/docker_publish.yaml (currently at 30m)
We can see the double execution from the log files of one execution:
```shell
$ grep " #14 " 1_build\ \(18-alpine\).txt  | grep "build:frontend" | grep built
2023-06-06T11:20:25.6513037Z #14 1198.7 [build:frontend] ✓ built in 7m 48s
2023-06-06T11:28:35.0518703Z #14 1688.1 [build:frontend] ✓ built in 7m 34s
```
_That is step 14 executing build:frontend twice_
=> chore: remove unnecessary build

src/lib/routes/util.ts
This change lowers the log level from warning to debug for when we see unexpected error types.
Right now this triggers for Joi errors, which we still rely on pretty heavily. Lowering this should clear up logs for most users.
=> chore: lower log-level for unexpected errors

src/lib/error/bad-data-error.ts, src/lib/error/from-legacy-error.ts, src/lib/error/unleash-error.test.ts, src/lib/error/unleash-error.ts, src/lib/routes/admin-api/strategy.test.ts, src/lib/routes/util.ts, src/test/e2e/api/admin/tag-types.e2e.test.ts, src/test/e2e/api/admin/tags.e2e.test.ts
This PR improves our handling of internal Joi errors, to make them more sensible to the end user. It does that by providing a better description of the errors and by telling the user what they value they provided was.
Previous conversion:
```json
{
"id": "705a8dc0-1198-4894-9015-f1e5b9992b48",
"name": "BadDataError",
"message": "\"value\" must contain at least 1 items",
"details": [
{
"message": "\"value\" must contain at least 1 items",
"description": "\"value\" must contain at least 1 items"
}
]
}
```
New conversion:
```json
{
"id": "87fb4715-cbdd-48bb-b4d7-d354e7d97380",
"name": "BadDataError",
"message": "Request validation failed: your request body contains invalid data. Refer to the `details` list for more information.",
"details": [
{
"description": "\"value\" must contain at least …
```
=> chore: improve joi errors

.github/workflows/release.yaml
Running `yarn install` without the `dist` folder will trigger a `yarn build` automatically as part of the `prepare script`
As we can see here: https://github.com/Unleash/unleash/actions/runs/5200272004/jobs/9378770279
```
[build:frontend] ✓ built in 41.10s
// more output
[build:frontend] ✓ built in 39.81s
```
=> chore: avoid building frontend twice

frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/ManageTagsDialog.tsx
Fixes `simple` tag type still visible in dropdown even after deleted
Closes # [1-997](https://linear.app/unleash/issue/1-997/simple-tag-type-still-visible-in-dropdown-after-deletion)
=> fix: only show simple tag type if there are no tag types in the server

src/lib/util/collapseHourlyMetrics.test.ts, src/lib/util/collapseHourlyMetrics.ts
Currently, Unleash is storing metrics every 5 seconds. However, a problem arises when multiple SDKs query the same feature flag, and one of them sends variants data while the other does not. If the SDK that does not send variants data is registered first, it leads to a error in the system.
This PR fixes the issue, by always storing variants object.
=> fix: fix variant metrics

src/lib/openapi/spec/create-application-schema.ts, src/lib/routes/admin-api/metrics.test.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
Edit application under https://app.unleash-hosted.com/demo/applications/test-app is currently not working as the appName is expected to come in the request body, but it's actually part of the url. We have two options here:
1. We change the UI to adapt to the expectations of the request by adding appName to the request body (and eventually removing appName from the URL, which would be a breaking change)
2. We remove the restriction of only sending the appName in the body and take the one that comes in the URL. We have a validation that verifies that at least one of the two sets the appName ([here](https://github.com/Unleash/unleash/blob/e376088668428b3ec9016de9fd481fbbb03ad5cb/src/lib/services/client-metrics/instance-service.ts#L208) we validate using [this …
=> fix: allow empty appName as it may come in the url

src/lib/services/feature-toggle-service.ts, src/lib/types/stores/feature-toggle-store.ts, src/test/e2e/api/admin/project/features.e2e.test.ts
When a feature is not found in a project we should fail with a NotFound error. If the feature belongs to a different project, it should not be a permission issue, because the user might not be aware (lack of permissions/visibility) of that other project, so even in this case the error should be NotFound (this also works if we ever allow the same feature name in different projects)
Fixes #3726
=> fix: feature not found in project yields 404

package.json
Rationale: we're doing continuous deployment of every commit. We don't want to bump versions with every deployment because it doesn't add value. 
Having a `-beta.xx` is also not relevant now, as any commit is deployed, but the repository on itself is not published on npm as a different version
We discussed some options: `rc` for release candidate, `beta`, but we thought main reflects better that this version does not change unless there's a reason for changing it (i.e. we're preparing the next version)
=> chore: rename version to reflect next candidate

src/lib/features/playground/playground-service.ts
* instead of making hundreds of DB calls in parallel to fetch project id for every feature we can look it up in memory
* we could make it even faster if we stored input bootstrap data with project and returned it as part of the getFeatureToggleDefinitions output interface
=> refactor: read project ids in memory

src/lib/openapi/spec/__snapshots__/client-metrics-schema.test.ts.snap, src/lib/openapi/spec/client-metrics-schema.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
This change adds a little more detail to the client metrics schema. The description for variants felt a
little unclear.
=> docs: mark 'yes' and `no` as required, add more details to variants

src/migrations/20230615122909-fix-env-sort-order.js
This query reorganizes the existing environments based on their current sort order and creation date, ensuring a unique and sequential order starting from 1.
=> fix: fix sort order for environments

frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.tsx, frontend/src/component/environments/EnvironmentTable/EnvironmentIconCell/EnvironmentIconCell.tsx
Handle icon for reordering environments was not showing up.
**Before:**
**After**
=> fix: show environment reorder handle

frontend/src/component/admin/projectRoles/ProjectRoleForm/PermissionAccordion/PermissionAccordion.tsx, frontend/src/component/admin/roles/RoleForm/RoleForm.tsx, frontend/src/component/admin/roles/RoleForm/useRoleForm.ts, frontend/src/component/admin/roles/RoleModal/RoleModal.tsx, frontend/src/component/common/RoleBadge/RoleBadge.tsx, frontend/src/hooks/api/getters/usePermissions/usePermissions.ts, frontend/src/hooks/api/getters/useRole/useRole.ts, frontend/src/interfaces/role.ts, frontend/src/utils/permissions.ts
https://linear.app/unleash/issue/2-1135/address-3975-pr-comments-by-refactoring-some-of-the-new-custom-root
This pull request addresses the majority of the comments raised in issue #3975 and lays the groundwork for unifying roles. The idea is for project roles to also be managed in the "Roles" tab, and several components, such as `RoleForm` and the `useRoleForm` can potentially be reused.
I'll leave the further investigation and implementation of unifying roles to be addressed in a separate task.
As a mostly unrelated UI fix, this also adds an arrow to the tooltip in the `RoleBadge` component.
=> refactor: address custom root roles PR comments

src/lib/features/export-import-toggles/export-import-service.ts
Will be filtering out usage counts for export, because:
1. This is the same pattern we are doing for other objects. Filtering out not needed fields.
2. Reducing the payload. This data is not needed for importing.
=> fix: filter out usage for export

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/create-config.ts, website/docs/reference/deploy/configuring-unleash.md
As requested in [Linear](https://linear.app/unleash/issue/2-1147/unleash-cloud-make-keepalive-configurable) this PR makes the serverKeepAliveTimeout configurable via the SERVER_KEEPALIVE_TIMEOUT environment variable. This was already configurable when starting Unleash programmatically, but it's nice to have as an env variable as well
=> task: Make keepalive configurable via an environment variable

frontend/src/component/playground/Playground/AdvancedPlayground.tsx, src/lib/features/playground/playground-service.ts, src/lib/features/playground/validateQueryComplexity.test.ts, src/lib/features/playground/validateQueryComplexity.ts
This PR adds capability to reject playground queries that are too complex (over 30k results)
Details:
* complexity calculated by multiplying number of features, envs, context combinations
* complexity is calculated in the backend code and results are returned to UI
* UI alert box is reset after another form resubmission, not when the input data is changed. You may want to see the error for some time and not have it disappear instantly after the first change
Next PR:
* UI tests for failed form submission
=> Query complexity validation

src/lib/features/export-import-toggles/export-import-api-usage.test.ts, src/lib/features/export-import-toggles/export-import-controller.ts
This PR fixes an issue where trying to use an admin token to import features via the API resulted in a 500 (due to missing properties).
The solution is to catch when the user is using and admin token in the controller, throw a 400, and tell them to use personal access tokens or service accounts.
The PR includes a new test file for this specific use case. We don't really test these cases many other places, so it seemed the logical choice.
=> fix: reject API admin tokens when importing features

website/docs/topics/data-collection.md, website/sidebars.js
This adds documentation for how we collect data in Unleash. Previously this had been a very small amount of data but it was quite hidden in our docs in terms of what it did and why. This makes this extremely explicit, with guidelines on how to disable it and confirmation that previously disabling data collection will continue to work as expected
=> docs: document how and why we collect data when using Unleash

src/lib/db/group-store.ts, src/lib/services/group-service.ts, src/lib/types/stores/group-store.ts, src/test/fixtures/fake-group-store.ts
1. Now groups can be created without providing empty list of users
2. Some cleanup
=> fix: creating groups should work without users

src/lib/routes/admin-api/api-token.ts
https://github.com/Unleash/unleash/pull/4019 introduced a bug where API token filtering was not taking into account ADMIN permissions, which means the API tokens were not being displayed on the UI.
=> fix: consider ADMIN in API tokens fetch permissions

src/lib/openapi/spec/advanced-playground-request-schema.ts, src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
This PR changes the OpenAPI schema for the advanced playground to not accept empty lists of environments and to not accept environment names that don't match the env name pattern we use.
The pattern is the same as the one we use for controlling environment names on creation.
However, there is a (small) chance that these may get out of sync later, so we could do something to only define this pattern once (and import it in the enterprise package), but that may be more work than is necessary, and I'd suggest we do that later.
I've also added a minLength to the string items although it isn't strictly necessary. It's primarily to give the users better feedback if the name is empty.
=> fix: disallow empty list of envs and invalid env names in advanced playground

frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.tsx
This PR adds links from the strategy evaluation results directly to the strategy edit screen.
If the code doesn't find any links, nothing changes.
The link text will be the name of the strategy and the title (if it exists).
=> feat: link to strategy edit screens from playground strategy results

frontend/src/component/admin/groups/GroupsAdmin.tsx
Adds an admin guard to groups: It is an admin feature and should be guarded on the UI the same way other admin features are.
=> fix: add admin guard to groups

src/lib/features/access/createAccessService.ts, src/lib/services/access-service.test.ts, src/lib/services/access-service.ts, src/lib/types/model.ts, src/test/fixtures/fake-access-store.ts, src/test/fixtures/fake-role-store.ts
`getUserRootRoles` should also consider custom root roles
This introduces test cases that unveiled a dependency between stores (this happens actually at the DB layer having access-service access tables from two different stores but skipping the store layer).
https://linear.app/unleash/issue/2-1161/a-user-with-custom-root-role-and-permission-to-create-client-api
=> fix: fetching user root roles include custom ones

frontend/src/component/admin/roles/Roles.tsx
https://linear.app/unleash/issue/2-1162/read-roles-permissions-should-give-you-access-to-read-roles
This updates the roles page permission guard to be the `READ_ROLES` permission instead of `ADMIN`, which better reflects on the UI the real permissions of the user.
Our current `AdminAlert` component is pretty limited however, and I plan to improve it in https://linear.app/unleash/issue/2-1165/improve-adminalert-usage-to-be-more-generic-accept-non-admin to better reflect the permission we're missing (instead of alerting that you need to be an admin).
=> fix: update roles permission guard

frontend/src/component/playground/Playground/AdvancedPlayground.tsx
Before:
* when try configuration was clicked in playground and the results fetching was over there was a quick moment where playground guidance/instructions showed up before the result table was rendered
After:
* instruction if only shown before form submission
* after form submission loaded appears
* when loading finishes table starts rendering
=> fix: remove playground results flip

frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx, frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.tsx, frontend/src/interfaces/strategy.ts
Fixes 2 bugs after the recent strategy improvements v2 changes:
- When creating a strategy the `groupId` param of the Gradual Rollout strategy now populates the groupId (when using default strategy, the groupId will only be overwritten when it is an empty string ) with the feature name (as it was before)
- When editing/setting a default strategy for an environment the `groupId` param should be an empty string, but editable.
Closes #
=> fix: add strategy bug when strategySplittedButton flag is on

frontend/package.json, frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundResultsTable.tsx, frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/combinationCounter.test.ts, frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/combinationCounter.ts, frontend/src/hooks/usePlausibleTracker.ts, frontend/yarn.lock
This PR adds plausible tracking of the number of feature combinations that we get from the advanced playground API.
The event type has been added to plausible
Relates to #3545
=> feat: count number of combinations from playground

src/lib/db/access-store.ts
This makes these permissions not available for selection. In particular `UPDATE_ROLE`, `CREATE_API_TOKEN`, `UPDATE_API_TOKEN`, `DELETE_API_TOKEN`, `READ_API_TOKEN` are long-lived and should be taken out with special care which is why we have https://linear.app/unleash/issue/2-1158/add-delete-migration-to-clean-up-no-longer-used-permissions
If a role has this permission assigned, it will be displayed but will not be able to remove it. Because the application code does not rely on these permissions, this shouldn't be a problem. Later when we remove them from the DB, the permission will be removed as well from the role by the migration
=> chore: filter out deprecated permissions

website/docs/reference/sdks/index.md
Hi! Adding a link to a some-batteries-included Haskell Unleash SDK. It uses a "core" library underneath that adheres to your [Client Specifications](https://github.com/Unleash/client-specification). Could add a link to that too, but from what I can tell, it's overlapped by your Yggdrasil project. We have been using the SDK for a handful of months now and we're happy with how it works. Hope you'll have it :)
=> docs: Add reference to Haskell SDK

src/lib/db/event-store.ts
The previous query utilized an ID limit for the "type" condition but not for the "feature_name" condition.
The improved query now correctly handles both conditions by ensuring that the "feature_name" is not null or the "type" matches the specified value, and then checking if the ID is greater than or equal to the provided value.
```
OLD: select max("id") from "events" where "feature_name" is not null or "type" = $1 and "id" >= $2 limit $3
NEW: select max("id") from "events" where ("feature_name" is not null or "type" = $1) and "id" >= $2 limit $3
```
=> fix: max revision query order

.github/workflows/release.yaml
When we do releases on the release branch we should not sync that back to master on unleash-enterprise repo. At most we can trigger a different process to automate the release of unleash-enterprise, but that'd be a different story.
=> chore: remove sync to enterprise from release branches

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/create-config.ts
As part of the move to a unified domain this PR updates the default EMAIL_SENDER to noreply@getunleash.io . Should not be merged/deployed until we've verified DMARC, DKIM for the new domain.
=> fix: Default email sender to getunleash.io domain

frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundResultsTable.tsx
Seems I missed a couple in the last PR. `yarn lint` doesn't report anything more now.
=> chore: remove unused imports from `yarn lint`

src/lib/services/client-metrics/metrics-service-v2.ts
In our **hosted** instance, we faced issue of metrics loading 5-10 seconds. We had two environments, around 70 applications, and 48 hour buckets, resulting in ~7000 permutations.
The main issue arose when the metrics.filter function was called, which involved running the compare function on all metrics for each permutation. With 3000 metrics in total, this led to **over 20 million calls** to the compareAsc function worse case scenario, causing a delay of 5-10 seconds for metric loading.
To improve performance, I optimized the logic by prefiltering the metrics based on the environment and appName. This eliminated the need to run the same function on all metrics repeatedly. Now, the compareAsc function is expected to be called only around 5000 times, resulting in a significant **tenfold …
=> fix: metrics performance patch

frontend/src/component/common/PermissionButton/PermissionButton.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyIcon/FeatureStrategyIcon.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyIcons/FeatureStrategyIcons.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx, frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
https://linear.app/unleash/issue/2-1167/multiple-strategies-breaking-the-environment-card
https://linear.app/unleash/issue/2-1179/buttons-have-an-extra-space-if-the-icon-its-not-visible
This fixes the broken UI when we have too many strategies.
Before:
After:
We also added the new strategy type to the tooltips:
This also fixes an extra margin we caught on our `PermissionButton` when it had no endIcon set.
Co-authored by: @daveleek
=> feat: responsive strategy icons

src/lib/db/segment-store.test.ts, src/lib/db/segment-store.ts
Catch cases where the segment doesn't exist and populate that error message with more info: it now says that a segment
with <id> doesn't exist instead of just 'No row'.
=> ux: return better error message if a segment doesn't exist

src/lib/db/access-store.ts, src/migrations/20230630080126-delete-deprecated-permissions.js
https://linear.app/unleash/issue/2-1158/add-delete-migration-to-clean-up-no-longer-used-permissions
Cleans up the filter in https://github.com/Unleash/unleash/pull/4083 and deletes the deprecated permissions from the database.
=> refactor: clean up deprecated permissions

frontend/src/component/demo/demo-topics.tsx
This fixes the demo flow by making the strategy popup step optional. 
This way the demo works whether the flag is enabled or not. Once we make the split strategy button GA, we can remove this step entirely.
Feel free to re-enable the flag once this is deployed to demo.
=> fix: demo flow with split strategy button by making step optional

src/lib/create-config.ts
This changes SERVER_KEEPALIVE_TIMEOUT to take in seconds instead of milliseconds.
=> fix: SERVER_KEEPALIVE_TIMEOUT env variable should be seconds

website/docs/how-to/how-to-enable-openapi.mdx
**We need to merge it together with 5.2.0 release.**
Since 5.2.0 Unleash will have OpenAPI enabled by default. Docs should be updated accordingly. Since people are still running older versions I'd like to leave most of the docs for now. 
Should we enabled OAS for proxy by default? My current stance is for OAS to be opt-in for proxy.
=> docs: not on latest unleash with openapi enabeld

website/docs/reference/api/legacy/unleash/admin/metrics.md
Mark some legacy endpoints as deprecated (they are long deprecated but documentation was out of date) and fix some of the URLs
=> docs: Documentation around metrics API

website/docs/reference/api/legacy/unleash/index.md, website/sidebars.js
Also adds a caution admonition to the legacy doc index page
=> docs: switch order of api doc sidebar items; put legacy docs under legacy header

frontend/src/component/admin/users/UsersList/UsersList.tsx
https://linear.app/unleash/issue/2-1187/fix-two-extra-columns-in-users-list
This fixes a regression introduced in https://github.com/Unleash/unleash/pull/4131 where two extra columns were added for search only but were not properly hidden.
Thanks @nicolaesocaciu for the heads up!
Before:
After:
=> fix: hide users list extra searchable columns

src/lib/addons/__snapshots__/datadog.test.ts.snap, src/lib/addons/__snapshots__/slack.test.ts.snap, src/lib/addons/__snapshots__/teams.test.ts.snap, src/lib/addons/datadog-definition.ts, src/lib/addons/datadog.test.ts, src/lib/addons/datadog.ts, src/lib/addons/slack-definition.ts, src/lib/addons/slack.test.ts, src/lib/addons/slack.ts, src/lib/addons/teams-definition.ts, src/lib/addons/teams.test.ts, src/lib/addons/teams.ts, src/lib/addons/webhook-definition.ts, src/lib/addons/webhook.test.ts, src/lib/addons/webhook.ts, src/lib/types/model.ts
###What
Adds an optional sensitive parameter for customHeaders to all current addons. When formatted as a valid json object, the object will be included as headers in the request the addon makes upstream to it's target URL
=> task: Add customHeaders as possible parameter.

frontend/src/component/demo/demo-setup.ts, frontend/src/component/demo/demo-topics.tsx
https://linear.app/unleash/issue/2-1168/demo-ensure-userid-context-field-in-setup-steps
This ensures that the `userId` context field exists when we reach specific demo topics that require it in order to be successfully completed. This uses the `setup` property on those topics, where we'll check for the existence of this context field and create it if it's not found.
=> fix: ensure userId context exists when running demo

.github/workflows/build.yaml, .github/workflows/notify_enterprise.yaml
Avoids code injection via the committer name or email
Also removes pushing to s3 on `main` folder as it's not used and we're already pushing to `commits` folder
=> chore: avoids code injection through git commit

.github/workflows/notify_enterprise.yaml
Using toJSON should escape any potentially harmful content from the username and email input
=> fix: avoid expression injection

src/lib/error/unleash-error.test.ts
Apparently Jest doesn't like it when you use multiple stringContaining
statements for one property. Only the last `stringContaining`
statement is evaluated while the others are ignored.
This means that a lot of these assertions were never checked. To fix
that, I've extracted them into separate assertions.
=> tests: don't use multiple expect.stringContaining in one statement

src/lib/types/events.ts
We're using this in enterprise as well, so we need to add events that could happen there as well.
=> fix: added service-account events

frontend/src/component/admin/apiToken/ApiTokenForm/useApiTokenForm.ts, src/lib/routes/admin-api/project/api-token.ts, src/test/e2e/api/admin/api-token.auth.e2e.test.ts
This fixes the creation of project only tokens (done through the project settings). When we redesigned the way tokens are created, we missed project specific tokens, which have their own permission set that wasn't respected. This forces only the project api for token creation to use the CREATE_PROJECT_API_TOKEN instead of the global CREATE_CLIENT_API_TOKEN or CREATE_FRONTEND_API_TOKEN
=> fix: project tokens can now be created with the correct permissions

frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ManageTags.tsx, frontend/src/hooks/api/actions/useTagApi/useTagApi.ts, src/lib/routes/admin-api/project/project-features.ts, src/lib/routes/admin-api/tag.ts, src/test/e2e/api/admin/tags.e2e.test.ts
Previously creation of tags required UPDATE_FEATURE permission, but creating tags is not related to feature or project, so it was not able to work.
Also bulk update tags was missing projectId from url, so it also did not work properly.
=> fix: bulk tags will work now with project permissions

frontend/src/component/admin/groups/Group/Group.tsx, frontend/src/component/admin/groups/GroupForm/GroupFormUsersTable/GroupFormUsersTable.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx, frontend/src/component/project/ProjectAccess/ProjectGroupView/ProjectGroupView.tsx
https://linear.app/unleash/issue/2-1197/merge-columns-name-and-username-in-one-column-for-all-the-tables
Shows `email` and/or `username` in the `name` column of users tables. This provides a more consistent look across the UI while saving some space for other columns.
Before:
After:
=> feat: show username and email in name column (users tables)

src/lib/openapi/spec/constraint-schema.ts, src/test/arbitraries.test.ts
Previously constraint values were validated inside the feature toggle service not in the openapi. What it means is that change requests that are using the same schema, don't get a validation since it's inside the feature service. So I'm moving the validation of values min length to the openapi schema. Since this field is optional the validation only kicks in when values are provided, not when single value is provided.
Solves: https://linear.app/unleash/issue/1-1095/cr-allows-0-values-for-constraints
=> fix: validate min constraint values in openapi

frontend/src/component/common/Highlighter/Highlighter.tsx
With using dangerouslySetInnerHTML we are often vulnerable to different injections. Lets try to avoid it until really necessary.
=> fix: remove dangerouslySetInnerHTML

frontend/src/component/project/Project/DeleteProject/DeleteProjectDialogue.tsx, frontend/src/component/project/ProjectCard/ProjectCard.tsx
https://linear.app/unleash/issue/2-1204/delete-project-dialog-cancel-button-wrong-redirect
Fixes an issue where the project deletion dialog would redirect if canceled.
=> fix: delete project dialog cancel redirect

frontend/src/component/common/VerticalTabs/VerticalTab/VerticalTab.tsx
https://linear.app/unleash/issue/2-1206/we-need-focus-state-for-vertical-menu
Adds a `focus-visible` style to vertical tabs in order to improve keyboard navigation.
=> fix: add focus style to vertical tabs

frontend/src/component/providers/PlausibleProvider/PlausibleProvider.tsx, src/lib/util/load-index-html.ts
Stringified JSON still needs to be escaped before being placed in an HTML attribute.
=> fix: correct escaping of ui flags for plausible

src/lib/db/event-store.ts, src/lib/services/event-announcer-service.ts, src/lib/services/index.ts, src/lib/types/services.ts, src/lib/types/stores/event-store.ts, src/migrations/20230706123907-events-announced-column.js, src/test/e2e/stores/event-store.e2e.test.ts, src/test/fixtures/fake-event-store.ts
This PR fixes an issue where events generated during a db transaction would get published before the transaction was complete. This caused errors in some of our services that expected the data to be stored before the transaction had been commited. Refer to [linear issue 1-1049](https://linear.app/unleash/issue/1-1049/event-emitter-should-emit-events-after-db-transaction-is-commited-not) for more info.
Fixes 1-1049.
The most important change here is that the `eventStore` no longer emits events when they happen (because that can be in the middle of a transaction). Instead, events are stored with a new `announced` column. The new event announcer service runs on a schedule (every second) and publishes any new events that have not been published. 
Parts of the code have largely been lifted …
=> 1-1049 Emit events after db transaction is complete

src/lib/error/forbidden-error.ts, src/lib/error/index.ts, src/lib/error/permission-error.ts, src/lib/error/unleash-error.test.ts, src/lib/error/unleash-error.ts, src/lib/routes/admin-api/project/variants.ts, src/lib/routes/controller.ts, src/lib/services/feature-toggle-service.ts, src/lib/services/project-service.ts, src/test/e2e/services/access-service.e2e.test.ts, src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts
In some of the places we used `NoAccessError` for permissions, other
places we used it for a more generic 403 error with a different
message. This refactoring splits the error type into two distinct
types instead to make the error messages more consistent.
=> refactor: split NoAccessError into ForbiddenError + PermissionError

.gitignore
I've seen this one pop up a couple times. It's part of our openapi docusaurus integration and should be ignored.
=> chore: add auto-generated doc index to gitignore

src/lib/error/bad-data-error.ts, src/lib/error/content-type-error.ts, src/lib/error/disabled-error.ts, src/lib/error/feature-has-tag-error.ts, src/lib/error/forbidden-error.ts, src/lib/error/from-legacy-error.ts, src/lib/error/incompatible-project-error.ts, src/lib/error/invalid-operation-error.ts, src/lib/error/invalid-token-error.ts, src/lib/error/minimum-one-environment-error.ts, src/lib/error/name-exists-error.ts, src/lib/error/not-implemented-error.ts, src/lib/error/notfound-error.ts, src/lib/error/operation-denied-error.ts, src/lib/error/owasp-validation-error.ts, src/lib/error/password-mismatch.ts, src/lib/error/password-undefined.ts, src/lib/error/permission-error.ts, src/lib/error/project-without-owner-error.ts, src/lib/error/role-in-use-error.ts, src/lib/error/unauthorized-error.ts, src/lib/error/unleash-error.ts, src/lib/error/used-token-error.ts, src/lib/types/authentication-required.ts
Make each error class have to define its own status code. This makes
it easier for developers to see which code an error corresponds to and
means less jumping back and forth between files. In other words: improved locality.
Unfortunately, the long switch needs to stay in case we get errors
thrown that aren't of the Unleash Error type, but we can move it to
the `fromLegacyError` file instead.
=> refactor: move status codes into classes

website/docs/topics/proxy-hosting.mdx
We had a customer wonder why `/api/proxy/development` wasn't configured for them. After some digging it was found that they'd followed our documentation and assumed that the proxy was configured for them. However, since we no longer host proxies, this was not the case. This PR updates the documentation to point out that "Unleash hosts everything" now means that our clients should use Frontend API keys and the `/api/frontend` endpoint to get what they used to get from embedded proxies.
We should make a new illustration in the same vein as the other illustrations on this page to demonstrate what the Frontend API really is. This PR removes the reference to the picture of the topology of having Unleash hosting proxies.
=> docs: Update proxy hosting to point to Frontend API

src/lib/middleware/api-token-middleware.ts
This isn't something our on-calls can do something about when it fails, so downgrading to WARN seems like the right level.
=> fix: reduce severity of api token middleware errors

website/docs/topics/proxy-hosting.mdx
Highlight edge in the first paragraph.
Not sure if we should suggest that it should be the preferred choice, but at least this helps to realize there's an alternative already in the first paragraph.
=> docs: highlight unleash edge

src/lib/openapi/index.ts, src/lib/openapi/spec/client-feature-schema.ts, src/lib/openapi/spec/client-features-schema.ts, src/lib/openapi/spec/create-feature-strategy-schema.ts, src/lib/openapi/spec/create-strategy-variant-schema.ts, src/lib/openapi/spec/environment-project-schema.ts, src/lib/openapi/spec/export-result-schema.ts, src/lib/openapi/spec/feature-environment-schema.ts, src/lib/openapi/spec/feature-schema.ts, src/lib/openapi/spec/feature-strategy-schema.ts, src/lib/openapi/spec/features-schema.ts, src/lib/openapi/spec/health-overview-schema.ts, src/lib/openapi/spec/import-toggles-schema.ts, src/lib/openapi/spec/index.ts, src/lib/openapi/spec/project-environment-schema.ts, src/lib/openapi/spec/project-overview-schema.ts, src/lib/openapi/spec/state-schema.ts, src/lib/openapi/spec/strategy-variant-schema.ts, src/lib/openapi/spec/variant-schema.ts
Introducing a new openapi concept for the strategy variant. It differs from the old variant in two ways:
* overrides are not supported
* ['name', 'weight', 'weightType', 'stickiness'] are required so weightType and stickiness were added. 
I don't know why weightType and stickiness were not required for the old variants but it makes types align with the application services (tested in a separate POC).
Added WIP in description so that people don't have expectations that it's already implemented.
Create and read variant differ by additionalProperties requirement.
=> feat: strategy variant schema openapi

src/lib/db/feature-toggle-store.ts, src/lib/services/feature-toggle-service.ts, src/lib/services/index.ts, src/lib/types/stores/feature-toggle-store.ts, src/migrations/20230711094214-add-potentially-stale-flag.js, src/test/e2e/stores/feature-toggle-store.e2e.test.ts, src/test/fixtures/fake-feature-toggle-store.ts
This PR lays most of the groundwork required for emitting events when features are marked as potentially stale by Unleash. It does **not** emit any events just yet. The summary is:
- periodically look for features that are potentially stale and mark them (set to run every 10 seconds for now; can be changed)
- when features are updated, if the update data contains changes to the feature's type or createdAt date, also update the potentially stale status.
It is currently about 220 lines of tests and about 100 lines of application code (primarily db migration and two new methods on the IFeatureToggleStore interface). 
The reason I wanted to put this into a single PR (instead of just the db migration, then just the potentially stale marking, then the update logic) is:
If users get the db …
=> #4205: mark potentially stale features

src/lib/openapi/spec/event-schema.ts, src/lib/routes/admin-api/project/project-features.ts, src/lib/services/feature-toggle-service.ts, src/test/e2e/api/admin/project/features.e2e.test.ts
This reverts commit 16e3799b9a399d79b2a025eaa4b2d5957a012349.
Closes #
=> Revert "Feat/add strategy update event on strategy ordering (#4234)"

src/lib/db/feature-toggle-store.ts, src/lib/services/feature-toggle-service.ts, src/lib/services/index.ts, src/lib/types/events.ts, src/lib/types/stores/feature-toggle-store.ts, src/test/e2e/stores/feature-toggle-store.e2e.test.ts, src/test/fixtures/fake-feature-toggle-store.ts
This PR adds updates the potentially stale status change events whenever the potentially stale update function is run.
No events are emitted yet. While the emission is only a few lines of code, I'd like to do that in a separate PR so that we can give it the attention it deserves in the form of tests, etc.
This PR also moves the potentially stale update functionality from the `update` method to only being done in the `updatePotentiallyStaleFeatures` method. This keeps all functionality related to marking `potentiallyStale` in one place.
The emission implementation was removed in https://github.com/Unleash/unleash/commit/4fb7cbde03b43320442633888f5ba4c0c3c77b31
While it would be possible to do the state updates in a single query instead of three separate ones, wrangling this into knex …
=> #4205: update to prepare for emitting potentially stale events

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/EnvironmentVariantsModal.tsx, frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx, frontend/src/component/feature/StrategyTypes/StrategyVariants.test.tsx, frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx, frontend/src/interfaces/featureToggle.ts, frontend/src/interfaces/strategy.ts
* Passing stickiness from the strategy to the variants so that they are always in sync for the strategy variants
* IFeatureStrategyVariant removed and back to IFeatureVariant with optional overrides. It is less invasive in the existing code
* Ability to disableOverrides in VariantForm since the new strategy variants don't need to override anythings (they have access to constraints and segments as first class citizens)
* stickiness param presence enables strategy variants support so any strategy that has it will automatically get variants
=> Strategy variants stickiness

website/docs/reference/deploy/configuring-unleash.md
Our documentation has mismatched code snippets when showing how to use self signed SSL certs. In the JS version, it specifies using a "ca" property, but in the bash version it uses "key" instead. "ca" is correct, so this PR just patches the bash snippet
=> docs: update postgres ssl docs to accurately use ca over key

package.json
We should have changed this with 5.2 release, but we forgot and I have plans of automating this
=> chore: prepare next release

frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundEnvironmentCell/AdvancedPlaygroundEnvironmentDiffCell.tsx, frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundResultsTable.test.tsx
This is both more correct in terms of what it does and also fixes an
issue where you couldn't navigate to the diff preview with the
keyboard previously.
It looks exactly the same as before except there's an additional paddingless button when you hover/focus it.
=> a11y: change the playground diff link to be a button.

website/docs/reference/feature-toggle-types.md
This change updates the existing feature toggle types document to add
a new `expected lifetime` section. This section explains better what
lifetimes are, where they come from, and that admins can (soon) change
the expected lifetimes for feature toggles.
=> docs(#4205): update feature toggle types doc to add lifetime info

website/docs/reference/event-types.mdx
Document new "feature-potentially-stale-on" events.
Relates to #4205
=> docs: document feature potentially stale on events

src/lib/openapi/spec/event-schema.ts, src/lib/openapi/validate.ts
This change makes the `eventData` object nullable (because it is),
and also removes all the properties that we had to declare to have an
example.
This should help us avoid a fair few warnings about data being
mismatched when it can really be anything.
The OpenAPI enforcer gives you warnings when you provide examples that use additional properties. But since we really don't know what the data is in this case, that's the best way forward. 
There's two options: either allow additional properties in all examples or use the `x-enforcer-exception-skip-codes` to allow it only in a single place.
I'm leaning towards the latter (and that's what's in this PR) because it can be useful to have the warning in other places, so I don't think we should ignore it completely. The tradeoff is that the …
=> openapi: remove all the extra data info

.do/Dockerfile, .do/deploy.template.yaml, Dockerfile, package.json
Instead of building from source (we require Node 18 but [DigitalOcean buildpack currently does not support it](https://www.digitalocean.com/community/questions/app-platform-node-build-pack-can-t-use-node-version-18)), we're going to use our Docker image from DockerHub: https://hub.docker.com/r/unleashorg/unleash-server
Additionally, I realized that our Dockerfile only works in our CI (or performing a pre-build step which consists of building the frontend). With this PR I've also made a change to build the frontend if needed. That way our CI will continue to be optimal while anyone trying to build it from source will be able to do it by just running `docker build .`
Closes #4261
=> fix: DigitalOcean template

src/lib/addons/__snapshots__/slack-app.test.ts.snap, src/lib/addons/addon.ts, src/lib/addons/slack-app.test.ts, src/lib/addons/slack-app.ts, src/lib/server-impl.ts, src/lib/services/addon-service.ts
https://linear.app/unleash/issue/2-1237/explore-slack-app-addon-scalability-and-limitations
Relevant document: https://linear.app/unleash/document/894e12b7-802c-4bc5-8c22-75af0e66fa4b
- Implements 30s cache layer for Slack channels;
- Adds error logging;
- Adds respective tests;
- Slight refactors and improvements for overall robustness;
=> feat: improve slack app addon scalability

package.json, src/lib/features/playground/feature-evaluator/client.ts, src/lib/features/playground/feature-evaluator/strategy/strategy.ts, src/lib/features/playground/feature-evaluator/variant.ts, src/lib/features/playground/offline-unleash-client.test.ts, src/lib/features/playground/offline-unleash-client.ts, src/lib/features/playground/playground-service.ts, src/lib/openapi/spec/__snapshots__/feature-schema.test.ts.snap, src/lib/openapi/spec/advanced-playground-environment-feature-schema.ts, src/lib/openapi/spec/client-features-schema.test.ts, src/lib/openapi/spec/create-strategy-variant-schema.ts, src/lib/openapi/spec/feature-schema.test.ts, src/lib/openapi/spec/playground-feature-schema.ts, src/lib/openapi/spec/playground-strategy-schema.ts, src/lib/openapi/spec/proxy-feature-schema.ts, src/lib/openapi/spec/variant-schema.ts, src/lib/types/model.ts, yarn.lock
* feature strategies variants in playground - based on Node SDK implementation 
* basic algorithm: for each strategy we calculate one variant and also return a list of all possible variants for the strategy. For the entire evaluation result we choose a first matching strategy and copy it's variant/variants
* by bumping up the Unleash Client SDK also frontend API gets support for strategy variants. It's thoroughly tested in the Node SDK. We can get feedback from prod how it works. After this I'd like to make node SDK non-beta. I prefer to go with frontend API first since we control it and can revert. Once we release Node SDK we don't control it anymore
I'm pretty confident of the change since the property based tests caught many errors as I was doing the refactor
=> feat: strategy variants in playground

src/lib/db/client-metrics-store-v2.ts
Same as https://github.com/Unleash/unleash/pull/1100 but for the variant metrics table.
In client variant metrics v2 we utilize postgres to count the usage
across a few dimensions (feature_name, app_name, environment, variant).
It turns out that if the UPDATE values are not executed in a predictable
order we can end up in a deadlock scenario with postgresql.
In this fix we thus sort the variant metrics on the feature_name, app_name,
environment and variant, to make sure they always are executed in a predictable
order, and thus avoiding independent inserts colliding in to a deadlock
waiting for each-other.
=> fix: variant table deadlocks

src/lib/addons/__snapshots__/slack-app.test.ts.snap, src/lib/addons/slack-app-definition.ts, src/lib/addons/slack-app.test.ts, src/lib/addons/slack-app.ts
https://linear.app/unleash/issue/2-1249/add-support-for-default-slack-channels
Adds support for default Slack channels (multiple, comma-separated). 
Some of the events we are handling do not have associated tags, or maybe the tags are empty. This adds a "default Slack channels" parameter to the addon configuration in order to post messages to those channels in those cases.
=> feat: slack app addon default channels

src/lib/db/event-store.ts
We are losing some events because of not having "created by" which is required by a constraint in the DB. One scenario where this can happen is with the default user admin, because it doesn't have a username or an email (unless configured by the administrator). 
Our code makes assumptions on the existence of one of these 2 attributes (e.g. https://github.com/Unleash/unleash/blob/248118af7c478f55d8583d95834fa022096d920c/src/lib/services/user-service.ts#L220-L222).
Event lost metrics:
The solution proposed here is falling back to a default value. I've chosen `"admin"` because it covers one of the use cases, but it can also be `"system"` mimicking https://github.com/Unleash/unleash/blob/248118af7c478f55d8583d95834fa022096d920c/src/lib/services/user-service.ts#L32 which is used as a default, …
=> fix: missing events in the event store

frontend/src/component/addons/AddonList/ConfiguredAddons/ConfiguredAddons.tsx
- When you you enable/disable an addon, in the same time another one is disabled/enabled
- Sometimes, when clicking enable/disable an addon the toggle switches quick back to the initial state
- Stable table sorting
- Switch toggle `key`
Closes https://linear.app/unleash/issue/1-1154/addons-enabledisable-action-misbehaves-changing-other-items
=> fix: Addons toggle

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/routes/client-api/metrics.ts, src/lib/services/client-metrics/metrics-service-v2.test.ts, src/lib/services/client-metrics/metrics-service-v2.ts, src/lib/types/experimental.ts
1. Add a test for the failing use case (we can see it [here](https://github.com/Unleash/unleash/actions/runs/5656229196/job/15322845002?pr=4339#step:5:783)):
```
FAIL src/lib/services/client-metrics/metrics-service-v2.test.ts
● process metrics properly even when some names are not url friendly
ValidationError: "name" must be URL friendly
```
2. Fix and handle this gracefully
Fixes: https://github.com/Unleash/unleash/pull/4193
=> fix: Client metrics name validation

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/services/client-metrics/metrics-service-v2.test.ts, src/lib/services/client-metrics/metrics-service-v2.ts, src/lib/types/experimental.ts
1. Add a test for the failing use case (we can see it [here](https://github.com/Unleash/unleash/actions/runs/5656229196/job/15322845002?pr=4339#step:5:783)):
```
FAIL src/lib/services/client-metrics/metrics-service-v2.test.ts
● process metrics properly even when some names are not url friendly
ValidationError: "name" must be URL friendly
```
2. Fix and handle this gracefully
3. Added a new toggle to silently ignore bad names: filterInvalidClientMetrics
Fixes: https://github.com/Unleash/unleash/pull/4193
=> fix: Client metrics name validation (#4339)

src/lib/features/playground/feature-evaluator/client.ts, src/lib/features/playground/feature-evaluator/feature-evaluator.ts, src/lib/features/playground/playground-service.ts
When we have non 100% gradual rollout with random stickiness enabled status and variant value were getting out of sync. This was because variant is checking isEnabled under the hood. In the new version we also verify isEnabled result (than contains enabled strategy variant). The new force version accepts the explicit evaluation result instead of a boolean flag.
=> fix: sync enabled and variant status

frontend/src/component/archive/ArchiveTable/ArchiveTable.tsx, frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
Prevent re-fetched state change from de-selecting rows.
=> fix: stable bulk updates

src/lib/openapi/meta-schema-rules.test.ts, src/lib/openapi/spec/admin-features-query-schema.ts, src/lib/openapi/spec/application-schema.ts, src/lib/openapi/spec/applications-schema.ts, src/lib/openapi/spec/create-feature-schema.ts, src/lib/openapi/spec/create-invited-user-schema.ts, src/lib/openapi/spec/date-schema.ts
Part of linear task 1-1167. Fixes the first slew of schemas missing descriptions/examples, etc.
=> OpenAPI: clean up remaining schemas, part 1

src/lib/openapi/spec/__snapshots__/token-user-schema.test.ts.snap, src/lib/openapi/spec/public-signup-token-schema.ts, src/lib/openapi/spec/token-user-schema.ts, src/lib/openapi/spec/user-schema.ts, src/lib/routes/admin-api/tag-type.ts, src/test/e2e/helpers/test-helper.ts
Enable strict schema validation by default. It can still be overridden by explicitly setting it to false.
I've also fixed the validation errors that appeared when turning it on. I've opted for the simplest route and changed the schemas to comply with the tests.
=> openapi: enable strict schema validation by default and fix

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/EnvironmentStrategyExecutionOrder/EnvironmentStrategyExecutionOrder.tsx
- make the blocks that hold the constraints full width
- remove the margin-top and margin-bottom from the parent div + increase the gap: 20px on this parent div
- remove the margin-bottom from the constraints containers
- add the strategies in a div and add a margin-bottom: 8px
=> fix: UI improvements on CR reorder strategy

src/lib/routes/admin-api/archive.ts, src/lib/routes/admin-api/client-metrics.ts, src/lib/routes/admin-api/project/environments.ts, src/lib/routes/admin-api/project/project-features.ts, src/lib/routes/admin-api/public-signup.ts, src/lib/routes/public-invite.ts, src/test/e2e/api/openapi/openapi.e2e.test.ts
This PR adds an e2e test to the OpenAPI tests that checks that all openapi operations have both summaries and descriptions. It also fixes the few schemas that were missing one or the other.
=> OpenAPI: add operation tests: require summaries and descriptions

src/lib/db/event-store.ts, src/lib/features/feature-toggle/configuration-revision-service.ts
In a new fresh Unleash instance with cache enabled this can cause feature toggles to never get updated.
We saw in our client that the ETag was ETag: "60e35fba:null" Which looked incorrect for us.
I also did manual testing and if the andWhere had a value of largerThan higher than whatever the id was then we would get back { max: null }.
This should fix that issue.
=> fix: EventStore#getMaxRevisionId can return null

src/lib/routes/index.ts, src/lib/services/user-service.ts, src/test/e2e/services/user-service.e2e.test.ts
We are giving a strange error message if the user does not have a password_hash defined in the database.
=> fix: Password hash is null should yield PasswordMissmatch

frontend/src/component/featureTypes/FeatureTypeEdit/FeatureTypeForm/FeatureTypeForm.tsx
This PR adds tracking of the feature type and the new lifetime to the
existing plausible event. This allows us extra insights into what users change it to.
=> 1-1192: track the feature type and the new lifetime

src/lib/routes/admin-api/user-admin.ts, src/lib/routes/index.ts
We have configured the trust proxy setting to true. With this configuration, the application places trust in the "X-Forwarded-For" header and considers the left-most entry in the header as the client's IP address. By doing so, the application relies on the proxy or load balancer to accurately set the "X-Forwarded-For" header with the correct client IP address.
However, it is important to be aware that this configuration also opens up the possibility of bypassing IP-based rate limiting. The rate-limiter system is currently logging this situation as a warning to alert us.
With this PR we are suppressing the warning.
=> feat: allow trust proxy

frontend/src/component/common/UpdateButton/UpdateButton.tsx, frontend/src/component/segments/EditSegment/EditSegment.tsx, frontend/src/interfaces/uiConfig.ts
Note: it doesn't work yet! It just throws an error.
This PR adds some logic to conditionally display "Add to draft" button for segments if the segment is part of a project that has change requests enabled and the flag is enabled.
Also adds a flag (`segmentChangeRequests`) to the frontend.
Holding off on actually adding the change to a draft until the API/orval has been updated with the most recent changes.
=> #4209: add 'add to draft' button for segments.

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ChangeActions.tsx, frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx, frontend/src/component/feature/StrategyTypes/StrategyVariants.test.tsx, frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx
When editing change request, there are no query params set, so need to pass in as props.
=> fix: environment id missing bug

CODEOWNERS
This change adds a CODEOWNERS file to the repository, which is used by
GitHub to automatically assign pull requests to the right people. It
also sets @thomasheartman as the owner of the docs directory (`/website`), which
means that he will be automatically assigned to pull requests that
touch docs.
=> meta: add CODEOWNERS and set thomas as docs owner

.github/workflows/build_prs_jest_report.yaml, package.json
~~Test if max-workers can speed up test runs~~ No, this didn't help.
Disabling the job that takes longer should help mitigate. We lose the coverage report but we still test our code: https://github.com/Unleash/unleash/actions/runs/5751945832/job/15591813034?pr=4405#step:7:2396
This cuts the build time by 50% and moving this to a daily schedule
=> chore: reduce build time

src/lib/features/change-request-access-service/change-request-access-read-model.ts, src/lib/features/change-request-access-service/fake-change-request-access-read-model.ts, src/lib/features/change-request-access-service/sql-change-request-access-read-model.ts, src/lib/features/feature-toggle/createFeatureToggleService.ts, src/lib/features/segment/createSegmentService.ts, src/lib/segments/segment-service-interface.ts, src/lib/services/index.ts, src/lib/services/segment-service.ts, src/test/e2e/services/access-service.e2e.test.ts, src/test/e2e/services/api-token-service.e2e.test.ts, src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts, src/test/e2e/services/playground-service.test.ts, src/test/e2e/services/project-health-service.e2e.test.ts, src/test/e2e/services/project-service.e2e.test.ts, src/test/fixtures/fake-project-store.ts
Update segment and delete segment now have protected mode which means that with CR enabled you can't change them willy-nilly. You either need skip permission for any project environment or go through a change request.
There's a corresponding enterprise change where I have tests and fix breaking changes.
I noticed that we have interface for the segment service. Since this is the only service with an interface it looks odd. I'm tempted to remove it since there's only one impl of the interface and TS is structurally typed. @gastonfournier since you added the interface WDYT?
=> feat: protect segment operations for change requests

src/lib/openapi/util/openapi-tags.ts
The new endpoints will be used to categorize and stabilize operations currently marked as unstable.
=> openapi: Add new tags for API operations.

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/SegmentChange.tsx, frontend/src/component/changeRequest/ChangeRequest/Changes/Change/SegmentChangeDetails.tsx
This PR fixes links to segments from change requests and the bottom border radius for segment change boxes.
Old border radius:
New border radius:
=> chore(#4209): minor front-end fixes

frontend/src/component/admin/instance-privacy/InstancePrivacy.tsx, src/lib/db/role-store.ts, src/lib/metrics.test.ts, src/lib/metrics.ts, src/lib/routes/admin-api/instance-admin.ts, src/lib/services/instance-stats-service.ts, src/lib/services/version-service.ts, src/lib/types/stores/role-store.ts, src/test/fixtures/fake-role-store.ts
https://linear.app/unleash/issue/2-1293/label-our-metrics-about-roles-to-include-also-if-the-role-is-a-root
Adds a Prometheus metric for total custom root roles. Also adds it to the instance telemetry collection.
Q: Should we use a `labeledRoles` kind of metric instead, similar to what we're doing for `clientApps` and their ranges?
=> feat: add prom metric for total custom root roles

src/lib/features/playground/playground.ts, src/lib/routes/admin-api/feature-type.ts
This PR stabilizes the playground and feature types endpoints by changing their tag from 'Unstable' to respectively 'Playground' and 'Feature Types'. It also moves the existing feature type endpoint (which was previously tagged as 'Features') to the 'Feature Types' tag.
=> openapi: stabilize playground + feature types endpoints

frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.test.tsx, frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.tsx
This change addresses two things that were done in
https://github.com/Unleash/unleash/pull/4004 and that I believe to be bugs.
1. It shows the previous strategy name also if there was no previous
title. So if there was no previous title, it'll show the strategy name
with a strikethrough and then the new title (see the discussion section).
2. It changes a `span` component to a [`del` component](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del). I believe the
span was erroneously changed from a `s` component (strikethrough
component) in the linked PR (based on a comment on the PR). This
caused the strikethrough to not be there anymore. However, the `del`
component is semantically more correct and reintroduces the
strikethrough, so it is a better change.
3. It uses [`ins` …
=> fix: CR strategy name changes code

src/lib/openapi/spec/playground-strategy-schema.ts, src/lib/routes/admin-api/strategy.ts
Open API is creating 2 resources under the same URL path, we want them aggregated:
```shell
$ curl -s https://us.app.unleash-hosted.com/ushosted/docs/openapi.json | jq '.paths."/api/admin/strategies/{name}" | keys'
[
"delete",
"get"
]
gaston@gaston-Summit-E16Flip-A12UCT: ~/poc/terraform-provider-unleash on main [!$]
$ curl -s https://us.app.unleash-hosted.com/ushosted/docs/openapi.json | jq '.paths."/api/admin/strategies/{strategyName}" | keys'
[
"put"
]
```
Note one is under `{name}` while the other is under `{strategyName}`
=> fix: proper aggregation of strategies

frontend/src/component/changeRequest/ChangeRequest/NameWithChangeInfo/NameWithChangeInfo.test.tsx, frontend/src/component/changeRequest/ChangeRequest/NameWithChangeInfo/NameWithChangeInfo.tsx, frontend/src/component/changeRequest/ChangeRequest/SegmentTooltipLink.tsx, frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.tsx, frontend/src/component/changeRequest/changeRequest.types.ts
Extract and reuse the component that we use for strategy name changes.
This impl only shows the new name in the second field (editing segment). Should we show it in both? Why do we have both? Do we have UI designs for this?
=> Add name with change info to segment changes (1-1230-update-name-change)

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx, frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx, frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx, frontend/src/component/changeRequest/UpdateCount.test.tsx, frontend/src/component/changeRequest/UpdateCount.tsx
Update count is used not just in sidebar but also the summary screen. I tried to extract a shared component.
=> feat: use update count in cr summary

src/migrations/20230814115436-change-request-timzone-timestamps.js
All change request tables use timestamps with timezones now.
I'm assuming that we don't need to specify default now() if it was specified originally. Also I'm assuming this is a nonbreaking change. Finally I don't provide back migration similarly to previous similar changes.
=> fix: add timezones to timestamps

package.json, src/lib/addons/slack-app.ts, yarn.lock
This PR changes the slack-app addon to use slack-api's scheduleMessage instead of postMessage.
When using postMessage we had to find the channel id in order to be able to post the message to the channel. scheduleMessage allows using the channel name instead of the id, which saves the entire struggle of finding the channel name. It did mean that we had to move to defining blocks of content instead of the easier formatting we did with postMessage.
=> fix: Change slackapp to using scheduleMessage

src/lib/openapi/spec/search-events-schema.ts
The indented formatting makes it interpreted as a markdown code block.
This isn't what we want. It's not as pretty, but putting it on one
line makes it render correctly.
What it looks like today:
=> chore: fix formatting of openapi description

src/lib/routes/admin-api/api-token.ts, src/test/e2e/api/admin/api-token.e2e.test.ts
* Get API tokens by name
* There can be 0, 1 or many tokens. I decided to always return 200 with either empty list, one element list, multi-element list. It feels the most idiomatic approach with a list returned. Originally the plan was to return 404 when the token doesn't exist but for the list/collection based APIs this feels wrong. 
* Current I'm adding in-memory filtering so that we don't have to over-invest in DB access code. Once the capability is found to be useful we can follow-up with more perf optimized solution.
* Also the existing code for tokens was mostly implemented in the controller layer instead of the service layer. I don't want to do massive refactoring and move everything to the service layer in this PR
=> feat: get api tokens by name

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.test.tsx, frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
When change request is rejected show rejected in red and previous stages in green.
Added extensive unit tests for timeline. Refactored color display logic.
=> feat: reject timeline state

frontend/vite.config.ts
After dependabot upgraded us to the new version of Vite, we started having failures on the preloading of CSS modules on certain lazy loaded modules. After investigation, it seems like Vite was adding another stylesheet into the head element when the lazy loaded modules were requested. These stylesheets had the wrong relative path when the assets were loaded from our CDN. We are not sure why this fails, but for now we are turning off cssPreloading. 
The impact is small, because we have few lazy loaded modules that preload the CSS.
=> fix: set css preload to false

src/test/e2e/api/openapi/openapi.e2e.test.ts
This change tests that all OpenAPI operations not only have summaries and descriptions, but that they are non-empty. This is important because empty summaries and descriptions (i.e. '') break the OpenAPI generation in our docs, blocking all doc builds.
=> fix: disallow empty summaries and descriptions

frontend/src/component/admin/adminRoutes.ts, frontend/src/component/admin/invoice/InvoiceList.tsx, frontend/src/component/admin/menu/AdminTabsMenu.tsx, frontend/src/component/admin/menu/CenteredNavLink.tsx, frontend/src/component/admin/network/Network.tsx, frontend/src/component/admin/roles/RolesPage.tsx, frontend/src/component/admin/useAdminRoutes.ts, frontend/src/component/menu/Header/NavigationMenu/NavigationMenu.tsx
https://linear.app/unleash/issue/1-1266/update-menu-for-billing-page
=> Update menu for billing page

frontend/src/component/common/Table/cells/FeatureSeenCell/FeatureEnvironmentSeenCell.tsx, frontend/src/component/common/Table/cells/FeatureSeenCell/LastSeenTooltip.tsx, frontend/src/component/feature/FeatureView/FeatureEnvironmentSeen/FeatureEnvironmentSeen.tsx
Last seen for toggles that have an old usage reported and no environment
Closes: # [1-1276] (https://linear.app/unleash/issue/1-1276/last-seen-for-toggles-that-have-an-old-usage-reported-and-that-are)
=> feat: Last seen for toggles that have an old usage reported

package.json
sets package.json version to 5.4
=> chore: prepare 5.4 release

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx
https://github.com/orgs/Unleash/discussions/4450
The textarea when adding JSON payload was of fixed size and did not allow resizing. Although MUI knows to render [TextareaAutosize](https://mui.com/material-ui/react-textarea-autosize/) when `multiline=true` as suggested in their docs - https://mui.com/material-ui/react-text-field/#multiline, but even in their examples in the docs, the resizing is not present. So perhaps some bug on their end  
With this PR we are adding `resize: vertical` styling if the `Input` component is rendering the native `textarea`. 
This solution will make both `json` and `csv` payload type inputs resizable since they both render as `textarea`
https://github.com/Unleash/unleash/assets/5814269/a484c457-25fc-47bc-bf92-5de4770d16cd
=> fix: multiline textarea resizing for json input

frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx, frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx, frontend/src/component/admin/auth/SsoGroupSettings.tsx
Adds a setting to OIDC SSO configuration that controls whether or not additional scopes are to be requested during login
=> feat: add a setting for toggling requesting additional scopes

frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx, frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx, frontend/src/component/admin/auth/SsoGroupSettings.tsx
Adds a setting to OIDC SSO configuration that controls whether or not additional scopes are to be requested during login
---------
Closes #
=> feat: add a setting for toggling requesting additional scopes (#4551)

src/lib/routes/admin-api/project/api-token.ts, src/test/e2e/api/admin/project/project.api.tokens.e2e.test.ts
Returns either 400 or 404 when token isn't found or doesn't match single project must be provided projectId criteria
Closes #
Linear 2-1003
Is projects.length > 1 a 400?
=> Fixes hangs when sending incorrect parameters to deleteProjectApiToken endpoint

src/lib/routes/admin-api/project/api-token.ts, src/test/e2e/api/admin/project/project.api.tokens.e2e.test.ts
Returns Not Found on create and get project api tokens when given a project id that doesn't exist
- This is an extra lookup per execution of the endpoint
=> chore: return 404 when projectid not found

src/lib/openapi/util/openapi-tags.test.ts, src/lib/openapi/util/openapi-tags.ts
This change sorts the tags in the tags file and tests that the list is sorted alphabetically. This makes it easier to
find tags in the file. 
#4580 already introduced a test to check that we have no duplicate
tags, so this isn't as necessary anymore, but it's still nice to have.
It also removes the previous auto-sorting before exporting. This is to ensure that entries are sorted in the source list. This might seem like a regression, but it makes it easier to spot near-duplicate tags:
> Despite having the test that validates there are no duplicates, you can always have Notifications and Notification API by mistake (tags that mean the same but are different). Keeping the list alphabetically sorted might help to prevent this before pushing the change to prod. In this case, we will eventually …
=> openapi: sort tags file

src/lib/services/project-service.ts
Adding an example when there is no pattern doesn't make any sense, so it should be an error.
Tests in https://github.com/ivarconr/unleash-enterprise/pull/721
=> 1-1329: return 400 when pattern is empty but example is not

frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
This PR adds descriptions of the various feature flag naming input fields in the project settings form. It also wraps the feature naming fields in a fieldset to group them semantically.
=> add descriptions in form

src/lib/openapi/spec/create-feature-naming-pattern-schema.ts, src/lib/services/project-schema.ts
Allow empty patterns and examples for feature naming. 
This fixes an issue where the form would break, not allowing you to create new projects at all.
=> feature naming patterns: allow empty values in examples and patterns

.github/workflows/e2e.frontend.yaml, frontend/cypress/integration/projects/access.spec.ts, frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx, src/lib/db/group-store.ts, src/lib/services/access-service.test.ts, src/lib/services/group-service.ts, src/lib/types/group.ts, src/lib/types/stores/group-store.ts, src/test/e2e/services/access-service.e2e.test.ts, src/test/e2e/services/group-service.e2e.test.ts, src/test/fixtures/fake-group-store.ts
Does what it says on the tin, should help with cleaning up https://github.com/Unleash/unleash/pull/4512 and respective schema changes.
=> fix: group roles assumption, refactor group types

src/lib/db/project-store.ts, src/lib/types/stores/project-store.ts
This change makes it so that you can save flag naming data on project
creation.
There was a mismatch between flattened and nested data in the creation
endpoint. Likely because we went back and forth a bit when we created
the feature originally.
=> 1-1333: fix type problems

frontend/src/component/feature/CreateFeature/CreateFeature.tsx, frontend/src/component/feature/FeatureForm/FeatureForm.tsx, frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
This PR adds info about a project's flag naming pattern to the flag creation form. This way, it's displayed before the user tries to create a flag, so that they have all the necessary information before making mistakes.
=> 1-1307: Show info about flag naming patterns before making mistakes

frontend/src/component/project/Project/ProjectForm/FeatureFlagNamingTooltip.tsx, frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx, frontend/src/component/project/Project/ProjectForm/validate-feature-naming.test.ts
While having a pattern when you have no example doesn't make a lot of sense, it's a problem that you can't delete the example after deleting the pattern: you previously had to remove the example before the pattern.
This PR fixes that by always allowing you to update the example, even if there is no pattern. Our server doesn't currently accept submitting an example with no pattern, but we could allow that if we want to (and probably just discard it on the back-end).
This PR also updates the validation of the example and the regex. There were more unhandled edge cases previously where the validation would disappear or be wrong. This should be fixed now. The new logic is that, whenever you update the either the pattern or the example, we check:
- if you have an error in your pattern, no …
=> 1-1320: allow you to update example with no pattern + update state better

frontend/src/component/feature/FeatureForm/FeatureForm.tsx
This change makes it so that the flag name is revalidated against the new
project pattern whenever you change the target project for a flag.
The validation is not run if the name is empty, if there is no
pattern, or if there is no validation method.
This solves the case where you input a name, then change the project,
and where the name isn't valid for the new project. Previously, it
wouldn't revalidate, but now it does.
=> 1-1315: revalidate feature name whenever the project changes

frontend/src/component/feature/CopyFeature/CopyFeature.tsx
Because you need to match the pattern when copying toggles, it's
important that we show the required information to the user.
This change adds information about the pattern to the page. This isn't
its final design, but it's more important that the information is
there (to avoid user frustration) than that it is pretty.
=> 1-1342: show flag naming pattern info when you copy toggles

src/lib/openapi/spec/__snapshots__/api-token-schema.test.ts.snap, src/lib/openapi/spec/api-token-schema.ts
Create api token schema can either provide the field `project` or its plural: `projects` so the joi validation makes them optional: https://github.com/Unleash/unleash/blob/2be77fb55ee85e18648afa455fbcee6b4d568f9d/src/lib/schema/api-token-schema.ts#L20-L24
This means that when returning the token, the response will either contain `project` or `projects` depending on what was provided as input. Therefore we need to make both fields optional in the response
=> fix: api token schema

website/docs/reference/sdks/index.md
Adds a line item to the SDK compatibility matrix to reflect strategy variants and marks custom stickiness as no longer in beta, since that's been stable for over a year.
=> docs: update compatibility matrix with strategy variants

frontend/src/component/admin/groups/GroupForm/GroupForm.tsx, frontend/src/component/admin/groups/GroupsList/GroupsList.tsx, frontend/src/component/common/RoleDescription/RoleDescription.tsx, frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx, frontend/src/component/project/ProjectAccess/ProjectGroupView/ProjectGroupView.tsx
https://linear.app/unleash/issue/2-1373/small-ui-fixes-and-improvements
- Update group root role `HelpIcon` tooltip to reflect the new behavior;
- Fixes a crash on groups search where `description` could be `undefined`;
- Improves `RoleDescription` design;
- Fixes the role label in `ProjectGroupView`;
=> fix: multi project roles UI improvements

frontend/package.json, frontend/src/component/common/Search/Search.tsx, frontend/src/component/common/Search/SearchSuggestions/SearchInstructions/SearchInstructions.tsx, frontend/src/component/common/Search/SearchSuggestions/SearchSuggestions.test.tsx, frontend/src/component/common/Search/SearchSuggestions/SearchSuggestions.tsx, frontend/src/component/common/Search/SearchSuggestions/onEnter.ts, frontend/src/hooks/useOnBlur.test.tsx, frontend/src/hooks/useOnBlur.ts
* tab navigation inside search suggestions and outside search suggestions
* when tab moves away from the search suggestions, the suggestions are hidden
* also supports escape key from the search suggestions
* added onUseBlur reusable hook that handles element loosing focus
* fix search and filter to filter our filters if they don't exists (previously it was undefined)
For now the elements we tab between are spans even though button would be more correct. Buttons add too many styles that we'd need to remove.
=> feat: keyboard navigation in search

frontend/src/component/common/util.ts, frontend/src/component/integrations/IntegrationForm/IntegrationForm.tsx, frontend/src/component/integrations/IntegrationList/AvailableIntegrations/AvailableIntegrations.tsx, frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap, frontend/src/component/menu/routes.ts, frontend/src/interfaces/route.ts
Fix submitting integrations form
=> Fix: integrations form

website/docs/how-to/how-to-create-and-assign-custom-project-roles.md, website/docs/reference/rbac.md
https://linear.app/unleash/issue/2-1130/documentation-about-multiple-project-roles
- Adds a section for the feature in the "Role-based Access control" reference doc;
- Removes the mention that "Groups that *do* have a root role can't be assigned to a project." which is no longer true;
- Adds a reference to multiple project roles in the "How to create and assign custom project roles" guide;
- Fixes a wrong sentence in the "Assigning custom project roles" section of the aforementioned guide;
=> docs: add mention of multiple project roles

src/lib/features/export-import-toggles/export-import-service.ts, src/lib/features/export-import-toggles/export-import.e2e.test.ts
Make the creation of toggles from import sequential so that we can count the toggles that already got created. 
The last import stage should fail on limit exceeded:
This PR is not touching the validation stage yet. 
This line from the toggle service is on the critical path and for 500 toggles it will run over and over again.
```ts
await this.projectStore.isFeatureLimitReached(projectId)
```
=> feat: check toggle limit on import

website/docs/reference/feature-flag-naming-patterns.mdx
Update docs to explain that ^ and $ are implicit in the regexes used.
=> 1-1360: explain implicit ^ and $ in docs

frontend/src/component/feature/CopyFeature/CopyFeature.tsx, frontend/src/component/feature/FeatureForm/FeatureForm.tsx, frontend/src/component/feature/FeatureNamingPatternInfo/FeatureNamingPatternInfo.tsx
This PR updates the design for the feature naming pattern info. In doing so, I've extracted the information into a single component.
It also, on @nicolaesocaciu's behest, makes the new toggle form inputs wider when they have room to grow.
Light mode:
Dark mode:
For copying features it looks like this:
=> ui: update design for feature naming pattern info

frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
This PR makes the project settings / creation forms grow to take up the full available width, so that it is in line with the new designs.
=> UI: make project settings / creation form full-width

frontend/src/component/integrations/IntegrationForm/IntegrationForm.tsx, frontend/src/component/integrations/IntegrationForm/IntegrationMultiSelector/IntegrationMultiSelector.tsx, src/lib/services/addon-service.test.ts, src/lib/services/addon-service.ts
https://linear.app/unleash/issue/2-1276/deal-with-events-without-an-environment
This makes it so that global events (events not tied to a specific environment) are always received, no matter the configured environment filter.
It also includes a respective test and small sentence on the UI explaining the behavior.
=> fix: post global events even when filtering by env

src/lib/openapi/spec/sdk-context-schema.ts
This was changed a month ago, but it ends up breaking the frontend when we regenerate the types because the playground needs to have this structure for now. We'll need to add this back until we can rewrite the playground to follow the schema.
=> fix: add additionalproperties to the sdkContextSchema

frontend/src/component/project/Project/ProjectForm/FeatureFlagNamingTooltip.tsx, frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
This PR simplifies the flag naming tooltip considerably. It now only contains an example of a pattern and what it will match. It also updates the link in the form section description to point directly to a regex cheat sheet instead of a general regex reference document.
There's a few reasons for doing this:
1. The text preceding the input already explains what the pattern does and explains that it is a regex.
2. The text preceding the input also contains a link to a regex cheat sheet (which is arguably a better place to explain regexes than a tooltip).
3. The tooltip was very long. While a lot of the information there was useful, it would also be hard to use. Imagine a user checking the tooltip, scrolling all the way down, but accidentally moving the mouse a bit and the tooltip …
=> refactor: simplify flag naming tooltip

src/lib/addons/slack-app-definition.ts, src/lib/addons/slack-app.test.ts, src/lib/addons/slack-app.ts, src/lib/services/addon-service.test.ts, src/lib/services/addon-service.ts
https://linear.app/unleash/issue/2-1392/fix-flaky-unhandled-events
- Reverts part of https://github.com/Unleash/unleash/pull/4490 and uses `postMessage` instead. This prevents an error where scheduling the message was flaky and some events ended up not being handled at all (see screenshot below). As a bonus, this simplifies our code and prevents having a delay. It seems like this method still works with the channel name instead of needing an id, which was the main motivation towards the changes in the aforementioned PR;
- Removes `FEATURE_UPDATED` from the event options for the Slack App addon, as [this event is deprecated](https://docs.getunleash.io/reference/environments#addons);
- Adds support for events without a specific project, including a test, similar to …
=> fix: use postmessage in slack app addon

frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx, frontend/src/hooks/usePlausibleTracker.ts
This PR adds plausible metrics for feature naming patterns. The changes are tracked whenever the form is submitted and the naming pattern has changed. We track three different actions:
- added :: if there was no pattern before and now there is one
- removed :: if there was a pattern before and now there is none
- changed :: if there was a pattern before and now there is a different one
The corresponding event type has been created in plausible.
=> feat: add feature naming pattern tracking

src/test/e2e/services/project-service.e2e.test.ts
This test enforces that descriptions and examples are cleared if they are not present in the feature naming data.
This behavior is already present, but it hasn't been encoded in any tests before.
=> test: enforce behavior via test

src/lib/services/feature-toggle-service.ts
https://linear.app/unleash/issue/2-1397/fix-environment-variants-change-event-does-not-include-changelogs
By running `applyPatch` without cloning the `oldVariants`, `applyPatch` would patch the `oldVariants` by reference, effectively making them the same as the `newVariants`. This fix `deepClone`s the oldVariants when sending them in as an `applyPatch` parameter so that the `oldVariants` variable is left untouched.
=> fix: env variants event changelog

frontend/src/component/integrations/IntegrationForm/IntegrationMultiSelector/IntegrationMultiSelector.test.tsx, frontend/src/component/integrations/IntegrationForm/IntegrationMultiSelector/IntegrationMultiSelector.tsx
Input should use state set outside and derive "all selected" from it. This was not the case causing issues when loading a form with "wildcard" pre-selected.
=> fix: integration multiselector

src/lib/openapi/spec/__snapshots__/api-token-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/change-password-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/client-application-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/client-features-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/feature-environment-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/feature-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/feature-type-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/me-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/role-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/set-strategy-sort-order-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/strategy-schema.test.ts.snap, src/lib/openapi/spec/__snapshots__/token-user-schema.test.ts.snap, src/lib/openapi/validate.ts
This was recently flagged as a security warning by our pipeline. AJV
also tells users not to use this in prouduction, which we must have
missed: https://ajv.js.org/security.html#security-risks-of-trusted-schemas
=> fix: disable all errors

src/lib/db/feature-toggle-store.ts
Seems like when 2 pods are trying to POST lastSeen metrics, the db gets into a deadlock state. 
This is an attempt to fix the deadlock by sorting the toggleNames before the update.
The hypothesis is that sorted toggle names will reduce the chance of working on the same row at the same exact time
Closes # [1-1382](https://linear.app/unleash/issue/1-1382/order-data-before-updating-the-lastseen-to-reduce-change-of-deadlock)
=> fix: sort toggleNames before updating last seen

frontend/src/interfaces/uiConfig.ts
I was a little confused because I couldn't find `useUiFlags` in the
codebase.
=> fix: point to `useUiFlag` instead of `useUiFlags`

frontend/src/component/feature/FeatureForm/FeatureForm.tsx
Previously, the front end would show info about the pattern if it
exists, regardless of whether the feature is active or not. The
pattern wouldn't be enforced, but it's confusing anyway, so let's hide
it.
=> 1-1385: hide display of pattern info behind a flag

src/lib/features/feature-naming-pattern/feature-naming-validation.ts, src/lib/services/project-service.ts
We already check for its presence before doing anything. We don't need to
check it twice (we're not Santa Claus, after all).
=> refactor: remove check for feature naming data object

frontend/src/component/integrations/IntegrationForm/IntegrationForm.styles.tsx, frontend/src/component/integrations/IntegrationForm/IntegrationMultiSelector/IntegrationMultiSelector.tsx, frontend/src/component/integrations/IntegrationHowToSection/IntegrationHowToSection.tsx, frontend/src/component/integrations/IntegrationList/AvailableIntegrations/AvailableIntegrations.tsx, frontend/src/component/integrations/IntegrationList/ConfiguredIntegrations/ConfiguredIntegrations.tsx, frontend/src/component/integrations/IntegrationList/IntegrationCard/IntegrationCard.tsx, frontend/src/component/integrations/IntegrationList/IntegrationCard/IntegrationCardMenu/IntegrationCardMenu.tsx, src/lib/addons/index.ts, src/lib/addons/slack-app-definition.ts, src/lib/addons/slack-definition.ts, src/lib/openapi/spec/addon-type-schema.ts
https://linear.app/unleash/issue/2-1401/misc-fixes-and-improvements-related-to-the-new-slack-app-integration
This includes multiple UI-related misc fixes and improvements that are not only related with the new Slack App integration but also integrations in general.
- Improves the styling in the "how does it work" section;
- Improves the text in the `IntegrationMultiSelector`s;
- Switches "Configure" and "Open" around to match designs;
- Properly handles click event on `IntegrationCardMenu` (fix navigation on dialog click);
- Fixes titles and contents for "enable/disable" and "delete" integration dialogs to match designs;
- Updates Slack App integration "how does it work" section to better reflect the intended behavior;
- Removes redundant alerts after previous point;
- Adds an alert in …
=> fix: misc integration-related fixes and improvements

src/lib/addons/slack-app-definition.ts, src/lib/addons/slack-app.test.ts, src/lib/addons/slack-app.ts
https://linear.app/unleash/issue/2-1393/drop-the-always-post-to-default-channels-field
This drops the "Always post to default channels" field in the Slack App integration in favor of always posting to the configured channels. This should simplify the configuration of this integration.
Here's a breakdown of the logic with this change:
- Always post to the configured Slack channels, regardless of tags;
- Tags are still respected. E.g. if we have a configured channel "channel-1" and a tag for "channel-2", then we post to both channels;
- As channels are optional, if you would like to skip default channels for certain events and handle everything through tags, you can just create a new configuration without any default channels;
This also updates the labels and changes the tests to better …
=> fix: simplify channels logic in slack app integration

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/PushVariantsButton/PushVariantsButton.tsx
Rename to `Copy to Environment`
Closes # [1-1388](https://linear.app/unleash/issue/1-1388/update-the-text-for-the-button-push-to-environment-from-variants)
=> fix: rename Push to Environment button

frontend/src/component/common/Search/Search.tsx, frontend/src/hooks/useOnBlur.ts
Selecting text in search suggestions was triggering blur and hiding all the suggestions:
=> fix: prevent blur when selecting text

src/lib/openapi/meta-schema-rules.test.ts, src/lib/openapi/spec/export-query-schema.ts
Open API code generator does not get along with `oneOf` alongside `properties`:
```shell
$ openapi-generator-cli validate -i modified-openapi.json --recommend
Validating spec (modified-openapi.json)
Warnings: 
- Schemas defining properties and oneOf are not clearly defined in the OpenAPI
Specification. While our tooling supports this, it may cause issues with other tools.
```
https://github.com/OpenAPITools/openapi-generator/blob/bab67e44e49422f51aca84d0ac1cc3987f443c62/modules/openapi-generator/src/main/java/org/openapitools/codegen/validations/oas/OpenApiSchemaValidations.java#L25-L29
This PR adds a meta-schema rule to validate this and fixes one issue
=> chore: merge one of with properties

src/lib/db/access-store.test.ts, src/lib/db/access-store.ts, src/lib/schema/role-schema.test.ts, src/lib/schema/role-schema.ts, src/lib/services/access-service.test.ts, src/lib/services/access-service.ts, src/lib/types/stores/access-store.ts, src/test/e2e/api/admin/api-token.auth.e2e.test.ts, src/test/e2e/services/access-service.e2e.test.ts, src/test/fixtures/fake-access-store.ts, src/test/fixtures/no-logger.ts
In https://github.com/Unleash/unleash/pull/4689 I forgot to add backward compatibility for a public method that was being used in Enterprise.
=> chore: Improve access service iter 2

src/lib/addons/index.ts, src/lib/services/addon-service.ts
Fixes what this breaks: https://github.com/Unleash/unleash/pull/4765 - The Datadog integration needs a `flagResolver`.
=> fix: datadog addon needs flagResolver

docker/yarn.lock
I run `yarn install --production=true` inside docker directory using yarn 1.22.19 (same as alpine version we use in docker).
I built a docker container, went inside it and checked the string-width version. It's 4.2.3 now (correct), previously it was 5.x.x (incorrect). 
If we have a similar problem in future:
* `docker build . -t localbuild:local` - pick whatever name you like
* `docker run -it localbuild:local /bin/sh` - go inside the container
* `cat node_modules/string-width/package.json` - check version if it matches your local node_modules version
=> fix: string-width issue when running docker container

website/docs/about-the-docs.md
While exploring the [About the docs](https://docs.getunleash.io) page for the first time, I observed the first bulleted list started with lowercase, which isn't consistent with other sections of the page. This minor PR capitalizes the first letter of the bullet lists in the "Documentation structure" section. This ensures the list follows the existing style across the page and the stable rule of written language ([reference](https://www.purchase.edu/editorial-style-guide/general-style-preferences/punctuation/bulleted-and-numbered-lists/#C)).
=> docs: update the bulleted list case in about-the-docs.md

.github/workflows/build_doc_prs.yaml, website/README.md
This fakes the build on docs-only PRs to be able to have a green build.
Touching a doc to validate it works
=> chore: Doc only should skip build

package.json, yarn.lock
Reverts https://github.com/Unleash/unleash/commit/ebc9cb20a93225293cfff338d01d62de1f4fc70a allowing us to test and debug the latest changes while excluding this version bump.
=> chore: pin @swc/core to v1.3.83

.github/workflows/update_version_for_version_checker.yml
This adds a workflow which automatically triggers on published releases to update the version number for our version checker. In addition it adds a workflow dispatch, in case the version number ended up wrong after an automatic run (for instance when patching an earlier released minor). 
Currently the version checker which receives the update only validates that the new version is also valid semver, it does not however check/verify that we're not suddenly telling it an older version is the newest (improvement available in the version updater repo).
=> task: Added workflow for calling update-version-action

frontend/src/component/segments/SegmentFormStepOne.tsx, frontend/src/component/segments/SegmentProjectAlert.tsx, src/lib/features/export-import-toggles/createExportImportService.ts, src/lib/features/segment/createSegmentService.ts, src/lib/features/segment/segment-controller.ts, src/lib/routes/admin-api/context.ts, src/lib/segments/segment-service-interface.ts, src/lib/services/context-service.ts, src/lib/services/index.ts, src/lib/services/segment-service.ts, src/test/e2e/services/access-service.e2e.test.ts, src/test/e2e/services/api-token-service.e2e.test.ts, src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts, src/test/e2e/services/playground-service.test.ts, src/test/e2e/services/project-health-service.e2e.test.ts, src/test/e2e/services/project-service.e2e.test.ts
1. GET single context field strategies will now hide private projects
2. GET single segment strategies will now hide private projects
This is just reusing the private project checker method, which is heavily tested in enterprise.
=> feat: context/segment usage private

package.json, yarn.lock
Reverts #4823 and bumps [@swc/core](https://www.npmjs.com/package/@swc/core) to the latest **v1.3.88**.
=> chore: revert #4823 and bump @swc/core to 1.3.88

.github/workflows/docker_publish.yaml, Dockerfile
We are pinning node to version 18.17.1 as we have seen some performance degregation on node 18.18.0 on arm64. We will investigate this further at a later point. This is to mitigate the issue.
Our next step in pinpointing the issue will be to compare between running on musl vs libc on arm64.
=> chore: pin node version 18.17.1

frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/FeatureToggleSwitch.tsx, frontend/src/component/project/Project/ProjectOverview.tsx
When loading don't keep initial state, but recalculate if after proper data is present
https://linear.app/unleash/issue/1-1432/project-overview-filtering-is-not-saved-correctly-4789
=> fix: project features table initial state

src/lib/features/dependent-features/createDependentFeaturesService.ts, src/lib/features/dependent-features/dependent-features-read-model-type.ts, src/lib/features/dependent-features/dependent-features-read-model.ts, src/lib/features/dependent-features/dependent-features-service.ts, src/lib/features/dependent-features/dependent-features-store-type.ts, src/lib/features/dependent-features/dependent-features-store.ts, src/lib/features/dependent-features/fake-dependent-features-read-model.ts, src/lib/features/dependent-features/fake-dependent-features-store.ts, src/lib/services/index.ts, src/test/e2e/api/client/feature.e2e.test.ts
Introducing read model separate from the write model using store. The read model can be used by the feature overview to get parents/children without exposing write DB operations.
=> feat: read model for dependent features

src/lib/features/dependent-features/dependent-features-read-model.ts
Make queries use explicit table names
Based on PR feedback here: https://github.com/Unleash/unleash/pull/4846#discussion_r1338518877
=> refactor: expicit names in queries

src/lib/db/event-store.test.ts, src/lib/db/event-store.ts
When the events table is large we might be doing a full table scan searching for unannounced events. We spotted it due to a performance alert and confirmed in AWS performance insights
The proposal is to limit this operation to 500 events (rule of thumb) per round https://github.com/Unleash/unleash/blob/f82ae354ebe6d3b0a3ddf15a051d6c8ed995c10e/src/lib/services/index.ts#L141-L147 and also ignore the events older than a day (because it seems reasonable)
**Idea**: split the `events` table into `recent_events` and `historical_events`. Recent can be anything from a day/week/month. This would help with recurrent queries that rely on recent data from the event's table such as optimal 304 calculation or event this scheduled task that sends unannounced events.
=> chore: limit the amount of unannounced events we announce

.github/workflows/build.yaml, .github/workflows/build_coverage.yaml, .github/workflows/build_prs.yaml, .github/workflows/build_prs_jest_report.yaml, .github/workflows/build_prs_test_report.yaml, .github/workflows/gradual-strict-null-checks.yml, .github/workflows/release.yaml, src/lib/db/event-store.test.ts, src/lib/db/event-store.ts, src/migrations/20230927172930-events-announced-index.js
Add partial index on events by announced. This should help avoid `Seq Scan on events` when the majority of events are announced=true
---
Co-authored-by: Ivar Østhus <ivar@getunleash.io>
Co-authored-by: Gard Rimestad <gard@getunleash.io>
=> fix: partial index on events announced

frontend/cypress/integration/projects/overview.spec.ts
Makes the Cypress project overview e2e spec less flaky by making the search action a 2 step process.
This test is now passing for me locally when before it wasn't.
=> test: makes overview spec less flaky by doing 2 step search

src/lib/db/event-store.ts
In our staging setup, we create ad-hoc environments and import Unleash state from production. After unleash is deployed on such environment, the import job kicks in and feeds Unleash instance with feature flags from production.
Between Unleash being up and running and the import job running, some applications start polling Unleash. They get an empty feature toggle list with `meta.revisionId=0`. Then apps use this as part of `eTag` header in subsequent requests. Even though after import Unleash server finally has toggles to serve, it doesn't because it calculates _max revision id_ based on toggle updates (not null `feature_name` column in query) or `SEGMENT_UPDATED`.
This change adds an extra condition to query so feature toggles import is considered something that should invalidate the …
=> Add condition for getting max revision id from store

frontend/src/hooks/api/actions/useAddonsApi/useAddonsApi.ts, frontend/src/hooks/api/actions/useInviteTokenApi/useInviteTokenApi.ts, frontend/src/hooks/api/actions/useRolesApi/useRolesApi.ts, frontend/src/hooks/api/actions/useServiceAccountsApi/useServiceAccountsApi.ts
Tiny refactor that bubbles promises instead of using `return await`. Should be more consistent with the rest of the changes in https://github.com/Unleash/unleash/pull/4903
=> refactor: bubble promise instead of return await

src/lib/db/group-store.ts, src/test/e2e/services/group-service.e2e.test.ts
Fixes an issue where SSO group sync would delete a syncable group that a user was manually added to
Is this the longterm fix for this? Or would we want another column in the mapping table for future-proofing this?
=> fix: only delete SSO-synced group membership where membership was added by SSO sync

frontend/cypress/integration/projects/overview.spec.ts
This PR fixes the overview.spec by relaxing the expectation on row count.
This expectation does not seem relevant enough for some tests
=> fix: make cypress list length checks more relaxed

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/FeatureEnvironmentVariants.tsx
Remove the info from the variants page
Closes # [UNL-231](https://linear.app/unleash/issue/UNL-231/remove-the-info-from-the-variants-page)
=> fix: Remove the info from the variants page

src/lib/__snapshots__/create-config.test.ts.snap, src/lib/create-config.ts, src/lib/services/user-service.test.ts, src/lib/services/user-service.ts, src/lib/types/option.ts, src/test/e2e/services/user-service.e2e.test.ts, website/docs/reference/deploy/configuring-unleash.md, website/docs/reference/deploy/getting-started.md
This PR adds a way of defining the username and password for the "default admin user" via environment variables. It defaults to using `admin` and `unleash4all`, so it should be completely backwards compatible.
Closes #4560
=> feat: allow defining initial admin user as env variable

frontend/src/component/admin/groups/CreateGroup/CreateGroup.tsx, frontend/src/component/admin/groups/EditGroup/EditGroup.tsx
Replaces the broken groups documentation link
CLoses: # [SR-75](https://linear.app/unleash/issue/SR-75/groups-documentation-link-broken)
=> fix: change broken link to groups documentation

src/lib/addons/feature-event-formatter-md.ts
Fixes a typo where we would send `disabled` for `enabled` events.
https://unleash-community.slack.com/archives/C03GWTN7XMG/p1696631381409369
=> fix: typo in enabled event

src/lib/addons/feature-event-formatter-md.ts, src/lib/services/feature-toggle-service.ts
Segment changes in predata and data columns were both showing the new segments list
Adds formatting of what's changed with segments to feature strategy update events, so when a user changes the strategy from using constraints, to using segments instead, it's communicated in event updates
results in: 
admin updated [sample-toggle](http://localhost/projects/default/features/sample-toggle) in project [default](http://localhost/projects/default) by updating strategy Sample Strategy in development constraints from [userId is one of (1,2,3)] to empty set of constraints; segments from empty set of segments to (1)
Closes #
#4912 
- `src/lib/services/feature-toggle-service.ts` - Segment changes in preData and data
- `src/lib/addons/feature-event-formatter-md.ts` - Formatting segments
This is an SR …
=> feat: render segments changes in feature strategy update event messages

website/package.json, website/yarn.lock
This rolls back docusaurus to 2.3.1, since 2.4.x seems to have broken something in the way we render generated markdown files
=> docs: rollback docusaurus upgrade so the docs work

.github/workflows/build_doc_prs.yaml
This is to bypass branch protection rules
=> chore: Rename validate step

src/lib/db/feature-strategy-store.ts, src/lib/services/project-service.ts
This PR cleans up and refactors the feature-strategy-store method getFeatureOverview to join on the new table and attempts to make the function more readable by extracting some of the logic into separate functions. Keeping the LastSeenMapper for now in case there is a reason to use it for the other endpoints.
=> fix: refactor getProjectOverview store method

website/docs/how-to/how-to-capture-impression-data.mdx, website/docs/how-to/how-to-create-and-assign-custom-project-roles.md, website/docs/reference/change-requests.md, website/docs/reference/sdks/index.md, website/docs/reference/segments.mdx, website/docs/reference/strategy-variants.md, website/docs/topics/proxy-hosting.mdx, website/src/components/VideoContent.jsx, website/src/css/custom.css
This PR changes the `VideoContent` component to:
- remove the extra text; keeps only videos
- makes videos take up the full article width
- multiple videos stack vertically (this may or may not be the best way to handle it, but we don't have any instances of using multiple videos as of right now, so we shouldn't touch this until we do).
By chance, it also removes a lot of trailing whitespace in files. I suggest checking out the diff with whitespace hidden.
Before (single video):
Before (if there were multiple videos): 
After (single video):
After (if there are multiple videos):
=> docs: make videos bigger

src/lib/db/event-store.ts, src/lib/features/instance-stats/getProductionChanges.e2e.test.ts, src/lib/features/instance-stats/getProductionChanges.ts, src/lib/features/instance-stats/instance-stats-service.test.ts, src/lib/features/instance-stats/instance-stats-service.ts, src/lib/metrics.test.ts, src/lib/metrics.ts, src/lib/openapi/spec/instance-admin-stats-schema.ts, src/lib/routes/admin-api/instance-admin.ts, src/lib/services/index.ts, src/lib/services/version-service.test.ts, src/lib/services/version-service.ts, src/migrations/20231004120900-create-changes-stats-table-and-trigger.js
As part of more telemetry on the usage of Unleash. 
This PR adds a new `stat_` prefixed table as well as a trigger on the events table trigger on each insert to increment a counter per environment per day.
The trigger will trigger on every insert into the events base, but will filter and only increment the counter for events that actually have the environment set. (there are events, like user-created, that does not relate to a specific environment).
Bit wary on this, but since we truncate down to row per (day, environment) combo, finding conflict and incrementing shouldn't take too long here.
@ivarconr was it something like this you were considering?
=> feat: feature changes counted in new table

website/remote-content/shared.js
This change adds custom edit urls for all the external readmes (sdks, edge, proxy) that we put in the docs. This makes it so that following the "edit this document" link takes you to the correct location, instead of to a file that doesn't exist in the main Unleash repo.
Important caveat: this will only work for repos where the readme is called `README.md` (capitalization matters). Currently, this is all our repos, but it's something to be aware of for later. 
We don't currently record what the readme files are called directly in the docs, so to know that for sure, we'd have to build an extra integration to check and fix that automatically. It may be worth doing in the future, but for now, I think it's fine. We could also just rename the readme files if we find any issues.
=> docs: add a custom_edit_url for sdks and edge/proxy

website/docs/how-to/how-to-troubleshoot-feature-not-available.md, website/docs/reference/login-history.md, website/docs/reference/service-accounts.md, website/sidebars.js
Adds a small troubleshooting guide for Unleash features availability.
This is not specific to features that have a visual component in the admin UI, but that's the most common scenario.
=> docs: add feature availability troubleshooting guide

frontend/src/interfaces/uiConfig.ts, src/lib/__snapshots__/create-config.test.ts.snap, src/lib/types/experimental.ts
https://linear.app/unleash/issue/2-1487/feature-flag-add-a-new-internalmessagebanner-feature-flag-for-this
Adds a new `internalMessageBanner` feature flag.
=> feat: add internalMessageBanner feature flag

website/docs/tutorials/getting-started.md, website/sidebars.js
Updated `sidebars.js` to incorporate `Getting Started` as top level doc, with Unleash Academy in child structure (order as discussed with @dgorton ). See screenshot.
Also added missing `id` to `getting-started.md`
=> docs: updated sidebars and added missing doc ID

frontend/src/component/App.tsx, frontend/src/component/messageBanners/externalMessageBanners/ExternalMessageBanners.tsx, frontend/src/component/messageBanners/internalMessageBanners/InternalMessageBanners.tsx, frontend/src/index.tsx, frontend/src/interfaces/uiConfig.ts, src/lib/__snapshots__/create-config.test.ts.snap, src/lib/types/experimental.ts
https://linear.app/unleash/issue/2-1494/re-order-message-banners
- Re-orders message banners to fit into this logic:
>1. Maintenance banner
>2. External message banner(s) - Most likely coming from Unleash
>3. Internal message banner(s)
- Renames the feature flag to better reflect the feature behavior;
- Lays a basic skeleton structure for this new feature;
=> feat: re-order message banners

frontend/src/interfaces/uiConfig.ts
Adds a missing uiFlag: `newInviteLink`
=> fix: missing uiFlag newInviteLink

website/docs/reference/deploy/environment-import-export.mdx, website/docs/reference/playground.mdx, website/docs/reference/strategy-constraints.md, website/docs/topics/a-b-testing.md, website/docs/tutorials/academy-advanced-for-devs.md, website/docs/tutorials/academy-foundational.md, website/docs/tutorials/academy-managing-unleash-for-devops.md
PR contains the following:
1) New video embeds for the following docs:
- website/docs/reference/deploy/environment-import-export.mdx
- website/docs/reference/playground.mdx
- website/docs/reference/strategy-constraints.md
- website/docs/topics/a-b-testing.md
2) Improvements to the Academy course playlist embedding for the three Academy courses. Tested the standard method of embedding video, and it seems this works well for playlists too.
Switching to the native Docusaurus embed solves the issue with dynamic resizing. Rather than a static embed size the video will now scale to the browser window size.
=> docs/video embed, academy video embed fixes

src/lib/features/export-import-toggles/export-import-controller.ts, src/lib/features/export-import-toggles/export-import-service.ts, src/lib/services/index.ts, src/lib/types/services.ts
This splits the interfaces for import and export, especially because the import functionality has to be replaced in enterprise repo.
This is a breaking change because of the service renames, but I'll have the PR for the other repository ready so we reduce the time to fix. I intentionally avoided doing it backward compatible because of time.
=> chore: split interfaces for import and export

frontend/index.html, frontend/src/themes/dark-theme.ts, frontend/src/themes/theme.ts
https://linear.app/unleash/issue/2-1502/add-support-for-custom-dynamic-icons-mui-icon-component
Adds support for custom dynamic icons by adding the [Material Symbols Outlined font](https://fonts.google.com/icons) and setting the MUI Icon component base class. See: https://mui.com/material-ui/icons/#icon-font-icons
Message banner use case: This will not only enable us to set custom icons for external message banners, but will also let users configure their desired icon from the set of options in the font.
=> feat: dynamic icons by adding material symbols font

frontend/src/component/messageBanners/MessageBanner/MessageBanner.tsx
https://linear.app/unleash/issue/2-1504/fix-message-banner-internal-link-assumption
Fixes the internal link assumption in message banner to `.startsWith('/')` - Any other links will be treated as external (normal `href`).
=> fix: message banner internal link assumption

frontend/src/component/messageBanners/MessageBanner/MessageBanner.tsx
https://linear.app/unleash/issue/2-1508/fix-message-banner-error-variant-icon
After aligning with @nicolaesocaciu, we fixed the `error` variant icon and removed irrelevant message variants for now.
=> fix: error icon, add only relevant variants

frontend/src/component/admin/maintenance/MaintenanceToggle.tsx
Makes the maintenance banner show right away when toggled. Includes some misc cleaning up.
=> fix: maintenance banner should show right away when toggled

frontend/src/component/common/Notifications/Notifications.tsx, frontend/src/component/menu/Header/Header.tsx, frontend/src/component/menu/Header/InviteLink/InviteLinkButton/InviteLinkButton.tsx, frontend/src/component/user/UserProfile/UserProfile.tsx
After aligning with @nicolaesocaciu, adds a new, cleaner, more consistent design to our header icons.
=> feat: adds a new design to the header icons

frontend/src/constants/statusCodes.ts, frontend/src/hooks/api/actions/useApi/useApi.ts, frontend/src/utils/apiUtils.ts, src/lib/middleware/maintenance-middleware.ts
This makes maintenance-related 503s more intuitive on our UI by mentioning that maintenance banner is currently enabled.
=> feat: make maintenance-related 503s more intuitive

website/README.md
This PR adds a small note to generate docs before running the docs locally.
=> meta: add note to generate openapi docs before starting local dev

src/lib/util/extract-user.test.ts, src/lib/util/extract-user.ts
This fixes a return type error by changing the logic of `extractUsernameFromUser` to never return undefined.
In the previous code, `user` could be truthy, but that doesn't mean `email` or `username` were defined. This assumes we always fallback to "unknown" in those scenarios.
=> fix: extract username from user should not return undefined

src/lib/features/feature-toggle/converters/feature-toggle-row-converter.ts, src/lib/features/feature-toggle/fakes/fake-feature-toggle-store.ts, src/lib/features/feature-toggle/feature-toggle-service.ts, src/lib/features/feature-toggle/feature-toggle-store.ts, src/lib/features/feature-toggle/types/feature-toggle-store-type.ts, src/lib/features/playground/advanced-playground.test.ts, src/lib/features/playground/feature-evaluator/client.ts, src/lib/features/playground/feature-evaluator/strategy/strategy.ts, src/lib/openapi/spec/playground-strategy-schema.ts, src/server-dev.ts
Adds the option to include disabled strategies (behind the playgroundImprovements flag
Closes # [1-1505](https://linear.app/unleash/issue/1-1505/return-disabled-strategies-in-the-playground-features-request)
=> feat: add option to return disabled strategies

src/lib/db/transaction.ts, src/lib/features/export-import-toggles/createExportImportService.ts
This small improvement aims to help developers when instantiating services. They need to be constructed without injecting services or stores created elsewhere so they can be bound to the same transactional scope. 
This suggests that you need to create the services and stores on your own
=> chore: introduce type to prevent potential issues

frontend/src/component/feature/Dependencies/AddDependencyDialogue.test.tsx, frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx, frontend/src/component/feature/Dependencies/DependenciesUpgradeAlert.tsx
=> feat: warn about sdk update with feature dependencies

package.json, src/lib/features/feature-toggle/deep-diff.ts, src/lib/features/feature-toggle/feature-toggle-service.ts, src/lib/features/feature-toggle/tests/deep-diff.test.ts
Add a deep diff function to investigate diff in logs
=> fix: log diff

frontend/src/component/messageBanners/MessageBanner/MessageBanner.tsx, frontend/src/component/messageBanners/externalMessageBanners/ExternalMessageBanners.tsx, frontend/src/interfaces/messageBanner.ts
https://linear.app/unleash/issue/2-1527/set-up-message-banner-interfaces
Tiny refactor to move the message banner interface to its own file, since it will be used in multiple places.
=> refactor: move message banner interface to common file

src/test/e2e/helpers/test-helper.ts, src/test/e2e/routes/routes.test.ts
This appears to be a bug. I can confirm that the base path did not take effect with the previous incarnation, but this should fix that.
=> fix(tests): correctly set baseUriPath in setupAppWithBaseUrl

src/lib/services/proxy-service.ts, src/test/e2e/api/proxy/proxy.e2e.test.ts
What problem are we solving?
* enabled info and variant info in the same feature have to be consistent when stickiness is set to default
* also we want to have consistency between parent and child features 
Solution:
* if the user didn't provide sessionId, generate one one the fly
Is Math.random() good enough?
=> feat: default session id in frontend api

package.json, src/lib/db/index.ts, src/lib/features/export-import-toggles/createExportImportService.ts, src/lib/features/feature-toggle/converters/feature-toggle-row-converter.ts, src/lib/features/feature-toggle/createFeatureToggleService.ts, src/lib/features/feature-toggle/deep-diff.ts, src/lib/features/feature-toggle/feature-toggle-store.ts, src/lib/features/feature-toggle/tests/deep-diff.test.ts, src/lib/features/project/createProjectService.ts, src/lib/services/client-metrics/last-seen/createLastSeenService.ts
Sort array items before running compare. Feature flag certain properties of strategy that were previously not present in the /api/admin/features endpoint.
=> fix: add sort to deep diff

frontend/src/hooks/api/actions/useMessageBannersApi/useMessageBannersApi.ts, frontend/src/hooks/api/getters/useMessageBanners/useMessageBanners.ts
https://linear.app/unleash/issue/2-1510/create-message-banner-hooks-that-connect-to-the-new-api-endpoints
Adds new message banner API hooks that will allow us to do CRUD operations for message banners in the UI.
=> feat: add message banner API hooks

src/lib/features/dependent-features/dependent-features-service.ts, src/lib/features/dependent-features/dependent.features.e2e.test.ts
Should not allow features depending on themselves
=> feat: prevent self dependencies

src/lib/features/feature-toggle/feature-toggle-service.ts, src/lib/services/project-service.ts, src/test/e2e/services/project-service.e2e.test.ts
This forces the project service to delete archived toggles when a project is deleted. Previously, when deleting a project, you were blocked if you had one or more active toggles but once they're archived the project can be deleted. Those archived toggles would persist indefinitely and when a new project was created that matched the old project name, they would immediately be bound to that project in an archived state. This was really confusing for users across teams, since they could create a project that someone else had created, used and then deleted and they would get a bunch of toggles in their project that they had never touched
=> fix: force deletion of archived toggles when deleting a project

src/lib/features/dependent-features/dependent-features-service.ts, src/lib/features/dependent-features/dependent.features.e2e.test.ts, src/lib/features/feature-toggle/fakes/fake-features-read-model.ts, src/lib/features/feature-toggle/features-read-model.ts, src/lib/features/feature-toggle/types/features-read-model-type.ts
Verify that child and parent features are in the same project.
=> feat: check if child and parent are in the same project

package.json, yarn.lock
Solves this https://github.com/Unleash/unleash/security/dependabot/76
=> chore: force tough-cookie to 4.1.3 due to vulnerability

src/lib/features/dependent-features/dependent-features-service.ts, src/lib/features/dependent-features/dependent.features.e2e.test.ts
Detect when you have GRAND_PARENT - PARENT dependency and you try to add GRAND_PARENT - PARENT - CHILD
Previously we only had grandparent detection, now we add grandchild detection.
=> feat: detect grandchild dependency

src/lib/features/project/createProjectService.ts, src/lib/services/access-service.ts, src/lib/services/project-service.ts, src/test/e2e/services/project-service.e2e.test.ts
This makes sure that projects have at least one owner, either a group or a user. This is to prevent accidentally losing access to a project.
We check this when removing a user/group or when changing  the role of a user/group
**Note**: We can still leave a group empty as the only owner of the project, but that's okay because we can still add more users to the group
=> feat: ensure at least one owner on remove user/group access

src/lib/addons/feature-event-formatter-md.ts, src/lib/addons/slack-app-definition.ts, src/lib/types/events.ts
https://linear.app/unleash/issue/2-1531/rename-message-banners-to-banners
Follow up to https://github.com/Unleash/unleash/pull/5098
This one adapts the existing events.
=> refactor: rename message banners to banners - events

frontend/src/component/banners/Banner/Banner.tsx, frontend/src/component/changeRequest/ChangeRequest.test.tsx, frontend/src/component/changeRequest/ChangeRequestPermissions.test.tsx, frontend/src/component/common/Sticky/Sticky.test.tsx, frontend/src/component/common/Sticky/Sticky.tsx, frontend/src/component/common/Sticky/StickyContext.tsx, frontend/src/component/common/Sticky/StickyProvider.test.tsx, frontend/src/component/common/Sticky/StickyProvider.tsx, frontend/src/component/demo/DemoBanner/DemoBanner.tsx, frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanel.tsx, frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx, frontend/src/component/maintenance/MaintenanceBanner.tsx, frontend/src/index.tsx, frontend/src/setupTests.ts
https://linear.app/unleash/issue/2-1509/discovery-stacked-sticky-elements
Adds a new `Sticky` element that will attempt to stack sticky elements in the DOM in a smart way.
This needs a wrapping `StickyProvider` that will keep track of sticky elements.
This PR adapts a few components to use this new element:
- `DemoBanner`
- `FeatureOverviewSidePanel`
- `DraftBanner`
- `MaintenanceBanner`
- `MessageBanner`
Pre-existing `top` properties are taken into consideration for the top offset, so we can have nice margins like in the feature overview side panel.
=> feat: add new sticky component to handle stacked stickies
