Unleash/unleash

src/migrations/20230803061359-change-request-optional-feature.js

In change request changes we had required feature name. Now we introduce segment changes that don't have any single feature attached. So I'm making the feature column optional. Segment id will be part of the payload same as strategy id is. In the long term we may even consider adding feature name to the payload.

feat: optional change request feature

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Closes:  [1-1193](https://linear.app/unleash/issue/1-1193/add-lastseenbyenvironment-flag)

feat: add lastSeenByEnvironment flag

---

frontend/src/component/changeRequest/ChangeRequest.test.tsx
frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.test.tsx
frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ChangeActions.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/FeatureChange.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/SegmentChange.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/SegmentChangeDetails.tsx
frontend/src/component/changeRequest/ChangeRequest/SegmentTooltipLink.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequestTitle.test.tsx
frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/component/changeRequest/changesCount.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.tsx

This is the first iteration of segments in pending CR screen.
Still need to add bunch of things, but those will be separate PR.

feat: segments in pending CR screen

---

package.json

This removes an unnecessary pre-step from the coverage report

chore: simplify coverage report

---

frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentDiffTable.tsx
frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentTable.tsx

Fixing react table accessors for context fields that contain "dot":
Inspired by: https://github.com/Unleash/unleash/pull/2863

Fix dot in context fields

---

frontend/src/assets/icons/usage-line.svg
frontend/src/assets/icons/usage-rate.svg
frontend/src/component/common/Table/cells/FeatureSeenCell/FeatureEnvironmentSeenCell.tsx
frontend/src/component/common/Table/cells/FeatureSeenCell/LastSeenTooltip.tsx
frontend/src/component/common/Table/cells/FeatureSeenCell/useLastSeenColors.ts
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/ProjectEnvironment/getEnabledEnvs.test.ts
frontend/src/hooks/api/getters/useEnvironment/defaultEnvironment.ts
frontend/src/interfaces/environments.ts
frontend/src/interfaces/featureToggle.ts
frontend/src/interfaces/uiConfig.ts

Implements last seen by environment UI
Closes # [1-1182](https://linear.app/unleash/issue/1-1182/ui-for-last-seen-per-environment)

Feat/last seen by env UI

---

frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/EditDefaultStrategy.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/ProjectDefaultStrategyForm.tsx

We can specify default strategy variants for new activation strategies.

feat: default strategy variant

---

src/lib/addons/slack-app.ts

We've been struggling with not getting hold of all channels. Reading the documentation I found the support for next_cursor in the response_metadata, as long as the response has a next_cursor, there are responses left, so this PR adds a loop for querying until the next cursor or the channels list is undefined or `''`. This should solve the issue Wayfair had as well.

fix: Added cursor pagination to slackapp conversations query

---

src/lib/db/access-store.ts
src/lib/features/access/createAccessService.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/services/access-service.test.ts
src/lib/services/access-service.ts
src/lib/types/stores/access-store.ts
src/test/e2e/services/access-service.e2e.test.ts
src/test/fixtures/access-service-mock.ts
src/test/fixtures/fake-access-store.ts

Fixes an issue where project role deletion validation didn't validate against project roles being connected to groups

fix: deletion validation didnt account for groups

---

frontend/src/component/common/FeatureArchiveDialog/FeatureArchiveDialog.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ArchiveButton.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ProjectFeaturesBatchActions.tsx

Adds a warning when about to archive features that have lastSeenAt of less than a week (green usage)
Closes # [1-224](https://linear.app/unleash/issue/1-1224/bulk-edit-show-last-seen-usage-warning)

feat: bulk archive usage warning

---

frontend/src/component/common/StrategyVariantsUpgradeAlert/StrategyVariantsUpgradeAlert.tsx
frontend/src/component/common/VariantInfoAlert/VariantInfoAlert.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/EnvironmentVariantsModal.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/FeatureEnvironmentVariants.tsx
frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx

Feature environment variants have a warning nudging for the strategy variant usage (behind a flag):
Added variant info to strategy variants, it's a shared component with the feature environment variants that explains how to use variants in the SDK:

feat: pointer to strategy variants

---

frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.test.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx

Show segments count in the change request sidebar

feat: cr sidebar segments count

---

frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestTitleCell.tsx

Count feature changes and segment changes:

feat: count segment changes

---

frontend/src/component/demo/demo-topics.tsx

Pointing to new variants docs in demo
From:
To:

fix: strategy variants in demo link to new variants

---

website/docs/reference/change-requests.md

Docs for change requests for segments

docs: change requests for segments

---

frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
frontend/src/hooks/usePlausibleTracker.ts

feat: track read about

---

frontend/src/component/changeRequest/ChangeRequest/SegmentTooltipLink.tsx
frontend/src/component/events/EventDiff/EventDiff.test.tsx
frontend/src/component/events/EventDiff/EventDiff.tsx

* omit createdAt and createdBy in segments
* rename variables for segments (they were copied from strategies)
* fixed our diff component as it was never showing (no changes) and was showing the entire new code on no changes.
* added missing tests for event diff
before:
after:

fix: diff no changes

---

src/lib/types/events.ts

Prepare event for change request rejection

feat: change request rejected event

---

src/migrations/20230814095253-change-request-rejections.js

A DB table migration for storing change request rejections. Table is identical to approvals table for now.

Change request rejections db table

---

frontend/src/component/common/Notifications/Notification.tsx

I noticed that our notifications were ticking every second. I changed it to similar approach as other time ago components.

feat: do not update every second

---

frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.styles.ts
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx

Link to CR configuration for people who try to configure it from change requests lists:

feat: link to change request configuration

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts
src/lib/server-impl.ts
src/lib/services/maintenance-service.test.ts
src/lib/services/maintenance-service.ts
src/lib/types/option.ts
src/test/config/test-config.ts
src/test/e2e/helpers/test-helper.ts

Sometimes our e2e tests are printing errors from the scheduler that is irrelevant to most of those tests. This PR adds an option to disable scheduler for tests.
disableScheduler is opt-in so all existing code is non-breaking

feat: disable scheduler for tests

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx

* review button has changes count
* added icons
* approve/reject buttons poppers has a width matching the review button width

feat: review buttons makeover

---

website/README.md

Add missing `yarn generate` command to docs

Update docs README.md to include `yarn generate`

---

src/migrations/20230817095805-client-applications-usage-table.js

Creates client_applications_usage table

feat: create client_applications_usage table migration

---

frontend/src/component/application/ApplicationList/ApplicationList.tsx
frontend/src/component/application/ApplicationList/OldApplicationList.tsx
frontend/src/component/application/ApplicationList/TemporaryApplicationListWrapper.tsx
frontend/src/component/menu/routes.ts
frontend/src/interfaces/uiConfig.ts
src/lib/types/experimental.ts
src/server-dev.ts

feat: application usage new ui

---

src/lib/features/export-import-toggles/export-import-permissions.e2e.test.ts
src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/features/export-import-toggles/import-toggles-store-type.ts
src/lib/features/export-import-toggles/import-toggles-store.ts
src/lib/features/export-import-toggles/import-validation-messages.ts

feat: features overwrite warning

---

src/lib/db/client-applications-store.ts
src/lib/routes/client-api/register.ts
src/lib/services/client-metrics/schema.ts
src/migrations/20230818124614-update-client-applications-usage-table.js

Closes # [1-1256](https://linear.app/unleash/issue/1-1256/backend-to-save-application-usage)
Adds client application usage persisting on upsert and bulkUpsert functions

feat: persist client application usage

---

frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx

Closes # [1-1277] (https://linear.app/unleash/issue/1-1277/update-health-page-with-the-new-designlogic-for-last-seen)

feat: Last seen per environment health

---

frontend/src/component/archive/ArchiveTable/ArchiveTable.tsx

Closes # [1-1280](https://linear.app/unleash/issue/1-1280/update-the-archive-toggle-page-with-the-new-design)

feat: Last seen per environment archive

---

frontend/src/component/common/Highlighter/Highlighter.test.tsx
frontend/src/component/common/Highlighter/Highlighter.tsx

Fixing a bug where search was affecting highlighter display. Also added tests showing correct behaior.

fix: highlighter casing

---

frontend/src/hooks/api/actions/useApi/useApi.ts
frontend/src/hooks/api/actions/useImportApi/useImportApi.ts
src/lib/db/feature-toggle-store.ts
src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/features/export-import-toggles/import-context-validation.ts
src/lib/types/stores/context-field-store.ts

* Import should fail when we have same feature twice
* fixing typechecker errors in all files that I touched
* added create or update semantics for feature toggles, previously we only had create
* improved feature toggle store to fail fast
* added UI errors collection for unknown errors
Next PR will also add validation state checking for duplicates.
Separate PR in the enterprise codebase soon.

fix: import duplicate features

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/EnvironmentStrategyExecutionOrder/EnvironmentStrategyExecutionOrder.tsx

Let the feature data load asynchronously before we use it

fix: diff component for ordering

---

src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/features/export-import-toggles/import-permissions-service.ts
src/lib/features/export-import-toggles/import-validation-messages.ts
src/lib/util/findDuplicates.test.ts
src/lib/util/findDuplicates.ts

Validate if we have duplicate feature in import.
Also preparing for duplication removal in the enterprise service by extracting shared methods.

feat: import service validate duplicates

---

website/docs/reference/strategy-variants.md

Added ruby and dotnet and php SDK versions supporting strategy variants

docs: strategy variants ruby and dotnet sdk versions

---

package.json
yarn.lock

updating unleash-client that correctly reports non-beta version to our metrics

chore: deps update unleash client

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ArchiveFeatureChange.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/FeatureChange.tsx
frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/component/common/FeatureArchiveDialog/FeatureArchiveDialog.test.tsx
frontend/src/component/common/FeatureArchiveDialog/FeatureArchiveDialog.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts

Archiving feature through change request. Single archive and bulk archive are supported.
Archiving single feature in change request overview
Archiving multiple features modal
* We're selecting first change request enabled env (with a preference for production) to add the change to. 
* Added brand new tests for the dialogue component to show different paths through the code
* Extracted hooks to separate logic from structure

feat: archive toggles in change request UI

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx
frontend/src/component/changeRequest/ChangeRequest/NameWithChangeInfo/NameWithChangeInfo.test.tsx
frontend/src/component/changeRequest/ChangeRequest/NameWithChangeInfo/NameWithChangeInfo.tsx

1. Default behaviour has now more room
2. New strategy title underline removed

feat: change request ui updates

---

frontend/src/component/changeRequest/ChangeRequest/SegmentTooltipLink.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
frontend/src/component/common/Table/cells/FeatureSeenCell/LastSeenTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx
frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx
frontend/src/component/featureTypes/FeatureTypeEdit/FeatureTypeForm/FeatureTypeForm.tsx
frontend/src/component/integrations/IntegrationList/AvailableAddons/AvailableAddons.tsx

Should help cleaning up some of these:

refactor: clean up some unused imports

---

src/lib/addons/slack-app-definition.ts

Add additional event that can be configured inside Slack App Addon

fix: Add feature environment variants updated event

---

frontend/src/component/integrations/IntegrationForm/IntegrationDeleteDialog/IntegrationDeleteDialog.tsx
frontend/src/component/integrations/IntegrationForm/IntegrationForm.styles.tsx
frontend/src/component/integrations/IntegrationForm/IntegrationForm.tsx

https://linear.app/unleash/issue/1-1268/add-remove-option-inside-configure-integration-page

Add "remove" option inside "configure integration" page

---

frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx
frontend/src/component/segments/EditSegment/EditSegment.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/services/segment-service.ts
src/lib/types/experimental.ts
src/server-dev.ts

Removing flags for change request reject and change request segments so that the features can go into GA.

Change request flags removed

---

src/lib/db/event-store.ts
src/test/e2e/api/admin/event.e2e.test.ts

Search event log by tags:
* tag type and tag value work
* supports spaces in tag values

feat: search event log by tags

---

frontend/package.json
frontend/src/component/archive/ArchiveTable/ArchiveBatchActions.tsx
frontend/src/component/archive/ArchiveTable/ArchiveTable.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ArchiveButton.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ProjectFeaturesBatchActions.tsx
frontend/yarn.lock

When archiving or reviving feature toggles, when toggles disappear from table, actions bar should also disappear.
Closes https://linear.app/unleash/issue/1-1293/bulk-revive-modal-doesnt-go-away

fix: reset selected toggle after archive or revive

---

frontend/src/component/feature/FeatureForm/FeatureForm.tsx

For consistency and readability.

refactor: use conditionally render instead of &&

---

frontend/package.json
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx
frontend/src/component/common/Search/Search.test.tsx
frontend/src/component/common/Search/Search.tsx
frontend/src/component/common/Search/SearchSuggestions/SearchInstructions/SearchInstructions.tsx
frontend/src/component/common/Search/SearchSuggestions/SearchSuggestions.tsx
frontend/src/component/common/Search/useSavedQuery.ts
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx

We remember last search/filter. 
Details:
* if your search has unique id you store your saved query in local storage
* if your search doesn't have unique id, then it stores the saved query in memory state 
* saved queries are clickable and can populate the input
* only non-empty queries are persisted

feat: persistent search queries

---

frontend/src/hooks/api/actions/usePersonalAPITokensApi/usePersonalAPITokensApi.ts

This cleans up some PAT-related methods that are no longer used.

refactor: clean up no longer used PAT methods

---

src/lib/openapi/spec/__snapshots__/api-token-schema.test.ts.snap
src/lib/openapi/spec/api-token-schema.ts

Reverts Unleash/unleash#4633 because of https://github.com/Unleash/unleash/pull/4633#issuecomment-1710122769

Revert "fix: api token schema"

---

src/lib/addons/addon-schema.ts

Fix addon schema breaking build

fix: addon schema validation

---

frontend/src/component/admin/apiToken/ApiTokenForm/ProjectSelector/ProjectSelector.tsx
frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/Settings.tsx

1. Hide project settings for OSS
2. Show nice message, when go to that page directly with URL

feat: hide project settings for OSS

---

src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/features/export-import-toggles/import-toggles-store-type.ts
src/lib/features/export-import-toggles/import-toggles-store.ts
src/lib/features/export-import-toggles/import-validation-messages.ts

Validate if the features limit will not be exceeded

Import limit validation

---

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx

Adds validation to number type for variants

fix: validation for variant payload number type

---

src/lib/db/project-store.ts
src/lib/routes/admin-api/archive.ts
src/lib/services/feature-toggle-service.ts

Archived features should not count towards the feature limit.
For now you can revive the feature outside of the limit so that in case of accidental archiving and limit exceeded you don't need to increase the limit. 
Also updated the method name to be consistent with the rest of the code.

Limit exclude archived features

---

src/lib/db/access-store.ts
src/lib/services/access-service.ts
src/lib/types/model.ts
src/lib/types/stores/access-store.ts
src/test/e2e/services/access-service.e2e.test.ts
src/test/fixtures/fake-access-store.ts

This allows us to get the project and group level access for all users in the system. This is built to support an enterprise feature

feat: add service method to retrieve group and project access for all users

---

src/lib/services/feature-toggle-service.ts
src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts

Even log is selecting which fields to log and variants were not added there.

fix: include strategy variants in the event log

---

frontend/src/component/project/Project/ProjectDoraMetrics/ProjectDoraMetrics.tsx

* Small change to round numbers in a table

fix: round dora metrics

---

src/lib/app.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/features/private-project/createPrivateProjectChecker.ts
src/lib/features/private-project/fakePrivateProjectChecker.ts
src/lib/features/private-project/privateProjectChecker.ts
src/lib/features/private-project/privateProjectCheckerType.ts
src/lib/features/private-project/privateProjectMiddleware.ts
src/lib/features/private-project/privateProjectStore.ts
src/lib/features/project/createProjectService.ts
src/lib/routes/admin-api/archive.ts
src/lib/routes/controller.ts
src/lib/services/feature-toggle-service.ts
src/lib/services/index.ts
src/lib/services/project-service.ts
src/lib/types/services.ts
src/test/e2e/services/access-service.e2e.test.ts
src/test/e2e/services/api-token-service.e2e.test.ts
src/test/e2e/services/project-health-service.e2e.test.ts
src/test/e2e/services/project-service.e2e.test.ts

**Filtering done for main endpoints**
GET /api/admin/features
GET /api/admin/archive/features
GET /api/admin/projects
**Added single store implementation:**
1. Takes all projects for users that are not root role viewers
2. Take all projects that are not private
3. Takes projects for user that has access directly or through group
NEXT BIG STEP. FULL AUTOMATED TESTS.

feat: private project filtering and store implementation

---

src/lib/services/index.ts
src/lib/services/scheduler-service.test.ts
src/lib/services/scheduler-service.ts

* Adds an ID to scheduled jobs so that they are easier to identify in the future

feat: add ids to scheduled jobs

---

src/lib/features/dependent-features/dependent-features-controller.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/lib/features/dependent-features/features.dependencies.e2e.test.ts
src/lib/routes/admin-api/project/index.ts
src/lib/routes/admin-api/project/project-features.ts
src/lib/services/feature-toggle-service.ts
src/lib/services/index.ts
src/lib/types/services.ts

Since feature toggle controller and service are already too big I decided to split feature dependencies write model into a separate directory. This change only moves things around, no new code is added.

refactor: feature oriented architecture for feature dependencies

---

src/lib/db/feature-toggle-client-store.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/lib/openapi/spec/client-feature-schema.ts
src/lib/openapi/spec/client-features-schema.ts
src/lib/services/feature-toggle-service.ts
src/lib/types/model.ts
src/lib/types/stores/feature-strategies-store.ts
src/test/e2e/api/client/feature.e2e.test.ts

Client API support for dependent feature toggles.
* behind a flag
* modelling dependencies as optional to make it very forgiving at the type level in the transitional period when we're adding a new feature
* the new left join with dependencies will only take effect if there are actual dependencies inserted. Since insert is also behind a flag it is safe to proceed

feat: Client api dependent features

---

.github/workflows/build_doc_prs.yaml
.github/workflows/generate-docs.yaml
website/README.md

This PR adds some troubleshooting information to the website readme and also makes it so that we get more readable errors in the build logs when something goes wrong.

docs: add info on how to troubleshoot and better errors

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.test.ts
src/lib/create-config.ts
src/lib/features/playground/playground-service.ts
src/lib/features/private-project/createPrivateProjectChecker.ts
src/lib/features/private-project/fakePrivateProjectChecker.ts
src/lib/features/private-project/privateProjectChecker.ts
src/lib/features/private-project/privateProjectCheckerType.ts
src/lib/features/private-project/privateProjectStore.ts
src/lib/features/private-project/privateProjectStoreType.ts
src/lib/services/client-metrics/instance-service.ts
src/lib/services/feature-toggle-service.ts
src/lib/services/index.ts
src/lib/services/project-service.ts
src/lib/types/no-auth-user.ts
src/lib/types/option.ts

1. Implement isEnterprise flag on backend
2. projectAccess now returns **ALL** project mode, so no filter will be applied to increase performance

feat: optimize private projects for enterprise

---

frontend/src/component/feature/Dependencies/AddDependency.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
frontend/src/hooks/api/actions/useDependentFeaturesApi/useDependentFeaturesApi.ts
frontend/src/interfaces/uiConfig.ts
src/lib/features/dependent-features/dependent.features.e2e.test.ts
src/server-dev.ts

UI stub for adding dependent features. Prod impl will differ but I need an easy way to test it for now
* everything behind a flag

feat: UI stub for adding dependent features

---

src/lib/services/group-service.ts
src/lib/types/events.ts

Adds a missing `group-deleted` event.

feat: add group-deleted event

---

src/lib/services/group-service.ts

As mentioned in https://github.com/Unleash/unleash/pull/4816#discussion_r1334162284

refactor: contract event group deleted after #4816

---

src/lib/features/dependent-features/createDependentFeaturesService.ts
src/lib/features/dependent-features/dependent-features-controller.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/lib/features/dependent-features/dependent-features-store-type.ts
src/lib/features/dependent-features/dependent-features-store.ts
src/lib/features/dependent-features/dependent.features.e2e.test.ts
src/lib/features/dependent-features/fake-dependent-features-store.ts
src/lib/routes/admin-api/project/index.ts
src/lib/services/index.ts
src/lib/types/services.ts

* checking if we can add dependency to a feature. If the feature has any children then it can have dependencies to any parents. 
* added transaction support for dependent features

feat: enforce no transitive parents

---

frontend/src/component/feature/Dependencies/AddDependency.tsx
src/lib/features/dependent-features/dependent-features-controller.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/lib/features/dependent-features/dependent-features-store-type.ts
src/lib/features/dependent-features/dependent-features-store.ts
src/lib/features/dependent-features/dependent-features.ts
src/lib/features/dependent-features/dependent.features.e2e.test.ts
src/lib/features/dependent-features/fake-dependent-features-store.ts

API for deleting feature dependency

feat: Delete dependency api

---

src/lib/features/dependent-features/dependent-features-controller.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/lib/features/dependent-features/dependent-features-store-type.ts
src/lib/features/dependent-features/dependent-features-store.ts
src/lib/features/dependent-features/dependent.features.e2e.test.ts
src/lib/features/dependent-features/fake-dependent-features-store.ts

API to delete all feature dependencies

feat: delete all feature dependencies

---

frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
frontend/src/hooks/api/getters/useParentOptions/useParentOptions.ts

Show available parent features and option to remove dependency for a feature:
Full UI test for this component in the next PR

feat: show available parent dependency options

---

frontend/package.json
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/ReactJSONEditor.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx
frontend/src/themes/app.css
frontend/yarn.lock

In this PR we are adding a JSON Editor that will be used for `json` variant payload type. Its using `vanilla-jsoneditor` package https://www.npmjs.com/package/vanilla-jsoneditor and is lazy loaded only when the `json` payload type is selected in the dropdown UI. 
Feature preview - https://recordit.co/p4Px9DNUIC
Closes #4450

feat: add json editor

---

frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundCodeFieldset/PlaygroundCodeFieldset.tsx

With empty object in code field and custom property selected JSON parser should not return any errors

fix: empty object playground

---

package.json

Bumps version to v5.6.0 as part of the release process.

chore: bump version to 5.6.0

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx

Small fix to account for array length in conditional check

fix: account for array length

---

website/docs/reference/strategy-variants.md

Added video embed for Strategy Variants reference

doc: Strategy variants video update

---

website/docs/reference/sdks/index.md

Added video embed into the SDK overview reference doc: https://docs.getunleash.io/reference/sdks

docs: add video to SDK overview reference

---

.github/workflows/build.yaml
.github/workflows/build_coverage.yaml
.github/workflows/build_prs.yaml
.github/workflows/build_prs_jest_report.yaml
.github/workflows/build_prs_test_report.yaml
.github/workflows/gradual-strict-null-checks.yml
.github/workflows/release.yaml
src/lib/db/event-store.test.ts
src/lib/db/event-store.ts
src/migrations/20230927172930-events-announced-index.js
src/test/e2e/api/admin/favorites.e2e.test.ts
src/test/e2e/api/admin/public-signup-token.e2e.test.ts
src/test/e2e/api/admin/user/pat.e2e.test.ts
src/test/e2e/api/auth/simple-password-provider.e2e.test.ts
src/test/e2e/custom-auth.test.ts
src/test/e2e/helpers/test-helper.ts

This fixes a bunch of openHandles from our tests
I've used this script to find out the ones that leave them:
`find src -name "*.test.ts" -printf "%f\n" | xargs -i sh -c "echo ===== {} && yarn test {}"`
If there's an issue, the script will halt and the last filename will be the one that has to be fixed. 
Each commit fixes one problem so it's easy to review

Fix open handles in tests

---

frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/DependencyRow.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/StyledRow.tsx
frontend/src/hooks/api/getters/useFeature/emptyFeature.ts
frontend/src/interfaces/featureToggle.ts
src/lib/features/dependent-features/dependent-features-read-model.ts

I have a parent UI:
I have some children UI:

feat: display dependencies and parents in project details

---

frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/DependencyActions.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/DependencyRow.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/StyledRow.tsx

When parent exists you can either delete it or edit:
I decided to read parents only when the modal is open. I assume adding dependencies will not be the most used feature so it makes no sense to slow down the feature overview screen.

feat: edit and delete dependencies menu

---

frontend/src/hooks/api/actions/useDependentFeaturesApi/useDependentFeaturesApi.ts
package.json
src/lib/features/dependent-features/createDependentFeaturesService.ts
src/lib/features/dependent-features/dependent-features-controller.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/lib/features/dependent-features/dependent.features.e2e.test.ts
src/lib/services/index.ts
src/lib/types/events.ts
src/test/e2e/api/client/feature.e2e.test.ts
yarn.lock

Dependency added, dependency removed and all dependencies removed have corresponding event entries
Also updated node client dependency so that frontend API can support dependent features automatically

feat: events for dependencies

---

USERS.md

chore: Unleash users page

---

.vscode/extensions.json

Adds [Biome](https://marketplace.visualstudio.com/items?itemName=biomejs.biome) as a recommended VSCode extension for our workspace.

chore: adds Biome as a recommended extension for vscode

---

frontend/src/component/common/FeatureArchiveDialog/FeatureArchiveNotAllowedDialog.tsx
frontend/src/component/feature/FeatureView/FeatureView.tsx
src/lib/features/dependent-features/dependent-features-read-model-type.ts
src/lib/features/dependent-features/dependent-features-read-model.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/lib/services/feature-toggle-service.ts
src/test/e2e/api/admin/project/features.e2e.test.ts

Prevent delete and archive of a parent feature.
We have both UI protection and backend API protection. 
In the UI we protect against single parent archive:
For the bulk archive and delete we rely on the backend validation for now:
Once we come up with a performant solution for dependencies info in bulk items/lists we can improve bulk archive UI.

feat: prevent delete and archive on parent feature

---

frontend/src/component/changeRequest/ChangeRequestPermissions.test.tsx
frontend/src/component/common/FormTemplate/FormTemplate.tsx
frontend/src/component/project/Project/CreateProject/CreateProject.tsx
frontend/src/component/project/Project/ProjectEnterpriseSettingsForm/CollaborationModeTooltip.tsx
frontend/src/component/project/Project/ProjectEnterpriseSettingsForm/FeatureFlagNamingTooltip.tsx
frontend/src/component/project/Project/ProjectEnterpriseSettingsForm/ProjectEnterpriseSettingsForm.tsx
frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/DeleteProjectForm.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/EditProject.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/UpdateEnterpriseSettings.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/UpdateProject.tsx

Running yarn lint:fix solves errors in frontend

fix: yarn lint:fix

---

.github/workflows/publish-new-version.yaml

This generates the changelog in the branch taking into account latest release (it's conditional to wether the release ends with .0 or not)

chore: automate changelog generation on release branch

---

frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportExpiredCell/formatExpiredAt.ts
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportStatusCell/formatStatus.ts
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx
frontend/src/component/project/Project/ProjectHealth/ReportTable/utils.ts
frontend/src/hooks/api/getters/useFeatureTypes/useFeatureTypes.ts
src/lib/services/project-health-service.ts

Fixes 2 bugs:
- project-health-service keeping the feature types as an instance variable and only updating it once was preventing real calculation to happen if the lifetime value changed for a feature toggle type
- the ui was reading from a predefined map for the lifetime values so they would never reflect the BE change
Closes #
[SR-66](https://linear.app/unleash/issue/SR-66/slack-question-around-potentially-stale-and-its-uses)
---------
(cherry picked from commit b07c032d56a428edecd5af5be21d6c981f16e800)
Closes #

fix: update potentially-stale status dynamically (#4905)

---

src/lib/services/feature-toggle-service.ts

Extra protection for copy dependencies. Theoretically when the flag is off the dependencies should not exist in the original feature but I want to exclude the whole code branch for extra safety.

feat: flag for clone dependencies

---

frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportExpiredCell/formatExpiredAt.ts
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportStatusCell/formatStatus.ts
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx

Fixes a bug with the UI where featureType comparison was using name instead of id

fix: ReportTable not updating status dynamically

---

frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportExpiredCell/formatExpiredAt.ts
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportStatusCell/formatStatus.ts
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx

Fixes a bug where the status and expiredAt columns where not updating dynamically

fix: ReportTable status column not updating

---

frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx

fix: linting

---

frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureDetails/FeatureDetails.tsx
frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureDetails/helpers.ts
frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/PlaygroundResultFeatureStrategyList.tsx
frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/StrategyList/playgroundResultStrategyLists.tsx
frontend/src/openapi/models/playgroundFeatureSchema.ts
src/lib/features/dependent-features/dependent-features-store-type.ts
src/lib/features/dependent-features/dependent-features-store.ts
src/lib/features/playground/advanced-playground.test.ts
src/lib/features/playground/feature-evaluator/client.ts
src/lib/features/playground/feature-evaluator/feature.ts
src/lib/features/playground/offline-unleash-client.ts
src/lib/features/playground/playground-service.ts
src/lib/openapi/spec/playground-feature-schema.ts

Playground can resolve dependent feature toggles
Parent dependency not satisfied UI
Parent dependency not satisfied and feature is disabled
* most of the code copied from the Node SDK with minor tweaks since the enabled/disabled resolution happens outside of the client in playground (in the service)
* UI tests will be added in the next PR since I need to add new tests for playground UI

feat: dependent features in playground

---

frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/FeatureToggleSwitch.tsx

Removes missed console log from FeatureToggleSwitch

fix: remove console from FeatureToggleSwitch

---

frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureDetails/FeatureDetails.test.tsx
frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/PlaygroundResultFeatureStrategyList.test.tsx

Test all new UI code that shows dependencies in playground. The focus is on the top message and the warning message in yellow.
Parent dependency not satisfied UI
Parent dependency not satisfied and feature is disabled

test: playground with dependencies

---

frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequestTitle.test.tsx
frontend/src/component/common/FeatureArchiveDialog/FeatureArchiveDialog.test.tsx
frontend/src/component/common/Search/Search.test.tsx
frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.test.tsx
frontend/src/component/context/ContextFieldUsage/ContextFieldUsage.test.tsx
frontend/src/component/context/ContextList/ContextList/ContextList.test.tsx
frontend/src/component/feature/Dependencies/AddDependencyDialogue.test.tsx
frontend/src/component/feature/FeatureView/FeatureSettings/FeatureSettingsProject/FeatureSettingsProjectConfirm/FeatureSettingsProjectConfirm.test.tsx
frontend/src/component/playground/Playground/AdvancedPlayground.test.tsx
frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundResultsTable.test.tsx
frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentDiffTable.test.tsx
frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentTable.test.tsx
frontend/src/component/segments/SegmentTable/SegmentTable.test.tsx
frontend/src/component/user/Profile/PasswordTab/PasswordTab.test.tsx
frontend/src/utils/testRenderer.tsx

Move boilerplate provider to the render method.
`<UIProviderContainer>` is around all your tested component so you don't have to type it yourself.
This is 2 LOC change + updated all tests that used it.

refactor: custom render should provide container

---

frontend/src/component/context/ContextList/ContextList/ContextList.test.tsx

Linting error that was not found by CI for some reason

fix: local linter did not find formatting error

---

src/lib/db/transaction.ts
src/lib/types/option.ts

chore: Improve UI Config type

---

.github/workflows/publish-new-version.yaml

This backports changes made in 5.5

fix: ignore errors on changelog generation and include token

---

src/lib/features/export-import-toggles/export-import-controller.ts
src/lib/types/services.ts

Limit import type to what matters

chore: improve type on import service

---

frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts
src/lib/features/dependent-features/createDependentFeaturesService.ts
src/lib/features/dependent-features/dependent-features-controller.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/test/e2e/api/client/feature.e2e.test.ts

When Change Requests are enabled do not allow to add and remove dependencies directly. 
It will be tested as part of the Change Request flow.
This will be a breaking change in change requests since they need to switch to unprotected method calls.

feat: do not allow to manage dependencies directly with cr enabled

---

tsconfig.json

Revive: https://github.com/Unleash/unleash/pull/3384

feat: generate declaration map

---

frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/DependencyRow.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.test.tsx
frontend/src/hooks/useHasAccess.ts

Delete dependency icon can select whether to use direct API or change request API.
A few interesting findings in this PR:
* I managed to find how to test toasts
* I managed to find how to test permissions with and without change requests

feat: delete dependnecy button through change request

---

.github/workflows/build.yaml
.github/workflows/build_coverage.yaml

Looks like we're building twice: https://github.com/Unleash/unleash/actions/runs/6468079228/job/17559391393#step:5:136

chore: avoid building frontend if not needed

---

website/docs/tutorials/academy-advanced-for-devs.md
website/docs/tutorials/academy-foundational.md
website/docs/tutorials/academy-managing-unleash-for-devops.md
website/docs/tutorials/academy.md

Set of four docs for Unleash Academy, with overview page and three course pages. Navigation to be updated separately.

initial docs for Unleash Academy

---

src/lib/error/index.ts
src/lib/internals.ts

export NotFoundError and ISegmentService in internals.ts

fix: export NotFoundError and ISegmentService in internals.ts

---

frontend/src/component/project/Project/Project.tsx
frontend/src/interfaces/uiConfig.ts

This should add some typesafety to our usage of uiFlags.

refactor: make uiFlags typesafe

---

src/migrations/20231012082537-message-banners.js

https://linear.app/unleash/issue/2-1485/db-create-migration-for-a-new-internal-message-banners-table
Adds a DB migration for a new `message_banners` table.

feat: message banners table migration

---

frontend/src/component/messageBanners/MessageBanner/MessageBanner.tsx

After aligning with @nicolaesocaciu, this fixes the message banner zIndex.

fix: message banner zIndex

---

src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts

Now OSS can import segments properly. Also updated tests.

fix: import segment test and fix

---

frontend/src/component/maintenance/MaintenanceBanner.tsx

After checking with @nicolaesocaciu we came to the conclusion that the maintenance banner should be sticky.
Co-authored-by Nicolae <nicolae@getunleash.ai>

feat: make maintenance banner sticky

---

src/lib/features/feature-toggle/feature-toggle-store.ts
src/lib/features/feature-toggle/query-builders/feature-toggle-list-builder.ts

Attempt to clean up huge query method

refactor: feature toggle list query

---

frontend/src/component/admin/users/InviteLinkBar/InviteLinkBar.tsx
frontend/src/component/admin/users/InviteLinkBar/InviteLinkBarContent.tsx
frontend/src/component/menu/Header/InviteLink/InviteLinkButton/InviteLinkButton.tsx
frontend/src/component/menu/Header/InviteLink/InviteLinkContent.tsx

Adding tracking for the new invite link shortcut

feat: header invite link tracking

---

frontend/src/component/archive/ArchiveTable/ArchiveTable.test.tsx
frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureReviveConfirm/ArchivedFeatureReviveConfirm.tsx
frontend/src/interfaces/uiConfig.ts

Fixes a bug with using the wrong feature name

fix: use correct flag name

---

src/lib/features/dependent-features/dependent-features-controller.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/lib/features/feature-toggle/feature-toggle-controller.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/routes/admin-api/project/project-archive.ts

When archiving/batch archiving features we should remove all parent dependencies
Additional changes:
* added transaction support for archive and batch archive so that we can remove dependencies inside a transaction

feat: remove dependency on archive

---

frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/DependencyRow.tsx
frontend/src/hooks/usePlausibleTracker.ts

Track when adding/removing dependencies in regular mode and change request mode.

feat: track add and remove dependencies

---

src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts

Adds test coverage for different feature flag paths temporarily

refactor: add test coverage

---

frontend/src/component/common/Notifications/Notifications.tsx
frontend/src/component/user/UserProfile/UserProfile.tsx

Some small UI adjustments to the new header icons.

fix: small adjustments on the new header icons

---

src/lib/addons/feature-event-formatter-md.ts
src/lib/addons/slack-app-definition.ts
src/lib/types/events.ts

https://linear.app/unleash/issue/2-1516/add-new-message-banner-events
Adds new message banner events to help us keep track of changes related to the new feature.

feat: add new message banner events

---

src/lib/features/client-feature-toggles/tests/client-feature-toggles.e2e.test.ts
src/test/e2e/helpers/test-helper.ts

add more robust tests for /api/client/features

refactor: add tests for /api/client/features

---

package.json
yarn.lock

Node SDK upgraded from beta to GA with dependent features support

chore: update node sdk to official ga version with dependent flags

---

frontend/src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionView.tsx

Now selecting the values is possible.

feat: allow selection of text in strategies for contexts

---

src/lib/features/dependent-features/createDependentFeaturesService.ts
src/lib/features/dependent-features/dependent-features-controller.ts
src/lib/features/export-import-toggles/createExportImportService.ts
src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/routes/admin-api/project/index.ts
src/lib/services/index.ts
src/lib/types/services.ts

Dependent features use new transaction mechanism
Added missing transactions in delete dependencies operations.

feat: dependent features use new transaction mechanism

---

frontend/package.json
frontend/yarn.lock

Fixing https://github.com/Unleash/unleash/security/dependabot/84

fix: server-side request forgery in @cypress/request@2.88.12

---

package.json
yarn.lock

Removing docusaurus as it breaks the build. Also it shouldn't be part of the app code and should stay in the website part.

fix: remove docusaurus from main package json

---

src/test/e2e/api/admin/project/projects.e2e.test.ts

Testing has strategies and has enabled strategies

test: added tests for has strategies and enabled strategies

---

website/docs/tutorials/academy-advanced-for-devs.md

Minor formatting fix for embedded play info box not displaying correctly

Docs - Formatting fix academy-advanced-for-devs.md

---

frontend/cypress/integration/projects/overview.spec.ts

wait for archive button to become enabled

fix: wait for bulk archive button to become enabled

---

src/lib/middleware/cors-origin-middleware.test.ts
src/lib/server-impl.ts
src/lib/services/index.ts
src/lib/services/proxy-service.ts

Proxy service is scheduled from the external scheduler

refactor: proxy service scheduler

---

src/test/e2e/migrator.e2e.test.ts

Our test logs were obscured by the migration test doing extensive console.log.
This PR applies the same trick as our production db migrator (copied code from the migrator.ts):
* sets log level to error
* removes verbose mode set by some IDEs e.g. WebStorm

test: silent migration test

---

frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/UpdateProject.tsx

Fixing curl command showing undefined as project id:

fix: read project id in edit project

---

frontend/src/component/feature/FeatureView/FeatureView.tsx

Making has parent/has children indicators more obvious:

feat: improved has children/has parent indicator

---

frontend/cypress/integration/projects/access.spec.ts
frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx
frontend/src/interfaces/uiConfig.ts

Follow up cleanup to https://github.com/Unleash/unleash/pull/5109
Based on https://github.com/Unleash/unleash/pull/5109#pullrequestreview-1689535863

refactor: slight clean up after GAing multiple roles

---

.github/workflows/build.yaml
.github/workflows/build_coverage.yaml
.github/workflows/build_prs_jest_report.yaml
.github/workflows/build_prs_test_report.yaml

Attempt to speed up DB tests by disabling fsync: https://dev.to/thejessleigh/speed-up-your-postgresql-unit-tests-with-one-weird-trick-364p

chore: disable fsync in gh action postgres to speed up the tests

---

src/test/e2e/api/auth/simple-password-provider.e2e.test.ts
src/test/e2e/api/proxy/proxy.concurrency.e2e.test.ts
src/test/e2e/stores/client-application-store.e2e.test.ts
src/test/e2e/stores/client-metrics-store-v2.e2e.test.ts
src/test/e2e/stores/feature-environment-store.e2e.test.ts

* avoid running db migration before each test
* concurrency test limit lowered

test: speed up the tests

---

frontend/src/component/project/Project/ProjectInfo/MetaWidget.tsx

fix: fix broken edit project link

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/openapi/spec/feature-search-query-parameters.ts
src/lib/openapi/util/from-query-params.ts

Type query params in a way so that we don't need to use type assertions (as X)

refactor: type query params

---

frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundConnectionFieldset/PlaygroundConnectionFieldset.test.tsx
frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundConnectionFieldset/PlaygroundConnectionFieldset.tsx

Rename `Api` to `API`
Add clear btn to token input
Add arrow to project and environment input tooltips
Closes # [1-1549](https://linear.app/unleash/issue/1-1549/token-input-improvements)

feat: token input improvements

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/fakes/fake-feature-strategies-store.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/test/e2e/helpers/test-helper.ts

Search by tag

---

frontend/src/component/playground/Playground/AdvancedPlayground.tsx
frontend/src/hooks/usePlausibleTracker.ts

Track usage of the new token input
Closes # [1-1551](https://linear.app/unleash/issue/1-1551/plausible-track-usage-of-token-input)

feat: playground token input usage tracking

---

src/lib/features/feature-toggle/converters/feature-toggle-row-converter.ts
src/lib/features/feature-toggle/feature-toggle-store.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/query-builders/feature-toggle-list-builder.ts

This commit will change the join to only get results for either archived or non-archived features based on the query

refactor: optimize queries

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/fakes/fake-feature-strategies-store.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/openapi/spec/feature-search-query-parameters.ts

Can filter search results by one or many feature types.
Based on this example it's easy to add other filter types. The important part of research here was handling multiple values in query params.

feat: filter features by type

---

src/lib/types/events.ts

This is a new event type that will be used to schedule a change
request. It's required in enterprise for the build to work as expected.

chore: add CHANGE_REQUEST_SCHEDULED to event types.

---

frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

add scheduledConfigurationChanges flag

feat: add scheduledConfigurationChanges flag

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/openapi/spec/feature-search-query-parameters.ts
src/test/e2e/helpers/test-helper.ts

Filter by environment status
* supports many environment statuses
* design is similar to tags
* status is enabled/disabled as in the existing search as opposed to enabled=true|false
`tag[]=simple:tag1&tag[]=simple:tag2` vs `status[]=production:enabled&status[]=development:enabled`

feat: filter by environment status

---

website/docs/how-to/how-to-create-and-assign-custom-project-roles.md
website/docs/reference/integrations/datadog.md
website/docs/reference/rbac.md

Maybe we should update availability in our docs, now that 5.6 is released.

docs: update availability due to 5.6 release

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/openapi/spec/feature-search-query-parameters.ts

Cursor based pagination in feature search
* add millis trick to exclude the previous cursor result
* currently only sorting by created_at is supported. We will extend this to other fields

feat: cursor based pagination in search

---

src/migrations/20231030091931-add-created-by-and-status-change-request-schedule.js

Adds 2 columns to change_request_schedule

feat: add created_by and status columns to change_request_schedule

---

package.json
yarn.lock

Node SDK update to fix variant hashing in frontend API

fix: variant hashing frontend API

---

CHANGELOG.md

Up-to-date changelog in 5.6. Same changes as in https://github.com/Unleash/unleash/pull/5170

chore: changelog into 5.6

---

src/lib/features/playground/feature-evaluator/strategy/flexible-rollout-strategy.ts
src/lib/features/playground/feature-evaluator/strategy/gradual-rollout-session-id.ts
src/lib/features/playground/feature-evaluator/strategy/gradual-rollout-user-id.ts
src/lib/features/playground/feature-evaluator/strategy/util.ts
src/lib/features/playground/feature-evaluator/variant.ts

Playground has synced variant hashing approach with Node SDK

fix: variant hashing in playground

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/tests/feature-toggle-last-seen-at.e2e.test.ts
src/test/e2e/helpers/test-helper.ts

Fixes an issue where the query in the feature toggle overview would return excess rows

fix: ft overview last seen at

---

CHANGELOG.md
package.json

Backport a few changes from 5.6 and brings changelog back to main

chore: changelog update into main

---

src/lib/db/setting-store.ts
src/lib/features/instance-stats/instance-stats-service.ts
src/lib/server-impl.ts
src/lib/services/setting-service.ts
src/lib/services/version-service.ts
src/lib/types/model.ts
src/lib/types/stores/settings-store.ts

A bit of boy scouting trying to expose the instanceId

chore: expose instanceId so it can be used from addons

---

website/docs/how-to/how-to-troubleshoot-flag-exposure.md

Adding details based on customer struggles

docs: improve troubleshooting

---

website/docusaurus.config.js

Redirect /unleash-academy/  to /unleash-academy/introduction

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/fakes/fake-feature-strategies-store.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/openapi/spec/feature-search-query-parameters.ts
src/lib/openapi/spec/search-features-schema.ts

Return total count of search and filter. In the UI table we need to show all matching results.

feat: total count in search results

---

frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectOverview.tsx
frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

When scrolling to the bottom of the features table, we trigger the next request based on the recorded cursor
Also fixes:
* limit respects that features belong to many environments
* displaying total items in the table results
still haven't decided on cursor pagination patterns:
* we can have next link and use it as a key
* we can have next cursors from the API (header or data field)

feat: infinite scroll API trigger

---

src/lib/features/dependent-features/dependent-features-read-model.ts
src/lib/features/dependent-features/dependent.features.e2e.test.ts

In parent feature dependencies dropdown I'd like the parent feature names to be sorted alphabetically.

feat: sort parent options alphabetically

---

frontend/src/component/project/Project/ProjectOverview.tsx

After extensive perf testing we realized that pagination is much more performant than infinite scroll.
Please set featureSearchFrontend to true in server-dev.ts to see this change.

feat: project overview pagination

---

src/lib/middleware/api-token-middleware.test.ts
src/lib/middleware/api-token-middleware.ts
src/lib/proxy/proxy-repository.ts
src/lib/routes/unleash-types.ts
src/lib/services/api-token-service.ts
src/lib/types/api-user.ts
src/lib/types/user.ts
src/test/e2e/api/auth/leading-slashes-are-stripped.e2e.test.ts

Expose types to be used in enterprise and cloud addons

chore: expose types so we can use them properly

---

frontend/src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/ConstraintAccordionEditBody.tsx

Patch constraint button to 5.6

Refactor/rename constraint button (#5260)

---

frontend/src/component/changeRequest/ChangeRequestOverview/ApplyButton/ApplyButton.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.styles.ts
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx
frontend/src/component/changeRequest/ChangeRequestStatusBadge/ChangeRequestStatusBadge.tsx
frontend/src/component/changeRequest/changeRequest.types.ts

Adds the scheduled state to ChangeRequestOverview.tsx

feat: scheduled change request state

---

src/lib/services/client-metrics/last-seen/last-seen-store.ts

Patch unleash last seen at logic

fix: last seen deadlocks (#5264)

---

website/docs/how-to/how-to-add-sso-open-id-connect.md

chore: fix typos in how-to-add-sso-open-id-connect.md

---

website/docs/topics/feature-flag-migration/planning-feature-flag-migration.md

- Small typo fix on the docs
#5284

fix(docs) small docs typo

---

src/lib/app.ts
src/lib/default-custom-auth-deny-all.ts
src/lib/server-impl.ts
src/lib/types/option.ts
src/test/fixtures/fake-user-store.ts

This will help us get type checking on the auth handler function

chore: expose custom-handler-auth type

---

frontend/src/component/project/Project/ProjectOverview.tsx
src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

Previously using tags:simple returned nothing. You needed to put tag exactly like tags:simple:mytag.
Now it works.

feat: also allow searching partial tags

---

src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

1. Created failing test
2. Fixed uniqueness identifier
3. Test green

fix: project overview and search returning just single tag

---

website/docs/contributing/backend/overview.md

I think this note may no longer make sense.

docs: remove password note

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/utils.ts
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestScheduledDialogs/ScheduleChangeRequestDialog.tsx
src/lib/types/events.ts

Change timezone format
Fixes a bug where the Edit button on hover being elongated
Before:
After:
Adds the missed onClick to the edit button to show the dialog
Fixes a bug with ScheduleChangesDialog onClose

Fix/scheduled request UI

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

Removed the concatenation from where statement, cause that makes the query inefficient.

chore: optimize sql query to not concatenate

---

src/lib/services/access-service.ts

Log the underlying DB error when changing a root role.

chore: log unerlying DB error in set user root role

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/openapi/spec/feature-search-query-parameters.ts
src/test/e2e/helpers/test-helper.ts

Now favorites will be always on first page, if pinned.

feat: sort favorites on the backend

---

website/docs/using-unleash/deploy/email-service.md
website/docs/using-unleash/troubleshooting/email-service.md
website/sidebars.js

https://linear.app/unleash/issue/SR-173/discussion-question-notification-from-email-doesnt-work
Adds a troubleshooting guide for [email service](https://docs.getunleash.io/using-unleash/deploy/email-service), which includes some knowledge shared in this discussion: https://github.com/orgs/Unleash/discussions/5323#discussioncomment-7554431

docs: troubleshooting email service

---

README.md

docs minimal edit into the desc

---

src/lib/services/access-service.ts

(cherry picked from commit ce7644e0af884f80887a179ccdc769d924c2d930)
Closes #

chore: log unerlying DB error in set user root role (#5324)

---

frontend/src/component/project/Project/ProjectFeatureToggles/PaginatedProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectOverview.tsx
frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/server-dev.ts

Now FE sorting is done in backend.

feat: connect sort table to backend

---

src/lib/db/access-store.ts

(cherry picked from commit 02da9b1d34690535f51ed86370972e522047741d)
Closes #

fix: handle concurrent service account updates (#5349)

---

frontend/package.json

chore: remove tsc when running tests (we do in GHA)

---

website/docs/reference/strategy-constraints.md

Fix a typo: explored -> explore

chore: Update strategy-constraints.md

---

website/docusaurus.config.js

Add more redirects from the docs refactor

Add redirects from 404 logs

---

frontend/src/component/feature/FeatureForm/FeatureForm.tsx
frontend/src/component/project/Project/ProjectEnterpriseSettingsForm/ProjectEnterpriseSettingsForm.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts
src/lib/types/experimental.ts
src/server-dev.ts
src/test/e2e/api/client/feature.e2e.test.ts

In preparation for this feature going GA

chore: remove usage of feature naming pattern flag

---

frontend/src/component/common/ExperimentalFeedback/ExperimentalFeedback.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/Project/ProjectDoraMetrics/ProjectDoraMetrics.tsx
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/routes/admin-api/project/index.ts
src/lib/types/experimental.ts
src/server-dev.ts

Discussion point:
* Is frontend protection enough for this feature?

refactor: remove feature flag for Dora

---

website/docs/reference/strategy-variants.md

Added info about using groupId for variant reassignment.

docs: variants reassignment

---

frontend/src/hooks/useTableState.test.ts
frontend/src/hooks/useTableState.ts

Simplified logic for handling interaction between URL (query), table state and localstorage.
Well, `useTableState.test.ts` - >2x LOC in tests
What do we do with new filters?

feat: useTableState hook

---

src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

Now calculates final ranks also, if there are some ranks missing from duplicates.

feat: sorting by last seen, environments now working properly

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts

1. Removing tag support in search
2. Adding multi keyword support for search

feat: support multiple terms in search, remove tag support in search

---

frontend/src/component/archive/ArchiveTable/ArchiveTable.test.tsx
frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureReviveConfirm/ArchivedFeatureReviveConfirm.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/archive-feature-toggles.e2e.test.ts
src/lib/services/client-metrics/last-seen/tests/last-seen-service.e2e.test.ts
src/lib/types/experimental.ts
src/server-dev.ts
src/test/e2e/api/admin/feature-archive.e2e.test.ts

Closes # [1-1646](https://linear.app/unleash/issue/1-1646/clean-disableenvsonrevive-flag-for-release)

Chore: remove disableEnvsOnRevive flag

---

frontend/src/component/admin/roles/RoleForm/PermissionAccordion/PermissionAccordion.tsx
frontend/src/utils/permissions.ts

https://linear.app/unleash/issue/2-1657/role-permissions-improvements
This PR includes 3 improvements:
- Sort permissions alphabetically
- Ensure we don't display duplicate permissions
- Improve alignment of columns by using a proper grid

fix: role permissions UI improvements

---

src/lib/db/feature-type-store.ts
src/lib/routes/admin-api/feature-type.ts
src/lib/services/feature-type-service.ts
src/lib/services/index.ts
src/lib/types/events.ts
src/test/e2e/api/admin/feature-type.test.ts
src/test/e2e/helpers/test-helper.ts

Added audit for feature type update
Short version:
Full event:
* FEATURE_TYPE_UPDATED event added instead of more granular LIFETIME_UPDATED. We may have other changes soon e.g. name change.
* added getRecordedEvents helper method to test app to easily check if the correct event got recorded
* added extra query in a service to get the preData status of the event type
* I decided to add tx support and refactor towards feature oriented architecture in a separate PR

feat: feature type updated audit log

---

src/lib/types/experimental.ts

This is a feature flag in unleash-enterprise

feat: add accessLogs feature flag

---

website/docs/reference/dependent-features.md

Show correct PHP and GO SDK versions that add dependent features support

docs: fix go and php versions with dependent flags support

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/openapi/spec/feature-search-query-parameters.ts

Added new operators INCLUDE, DO NOT INCLUDE, INCLUDE ALL OF, INCLUDE ANY OF, EXCLUDE IF ANY OF, and EXCLUDE ALL and now support filtering by tags.

feat: tag operators for search api

---

frontend/src/component/common/FeatureArchiveDialog/FeatureArchiveDialog.test.tsx
frontend/src/component/common/FeatureArchiveDialog/FeatureArchiveDialog.tsx
frontend/src/component/feature/Dependencies/AddDependencyDialogue.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/useShowDependentFeatures.ts
frontend/src/component/feature/FeatureView/FeatureSettings/FeatureSettingsProject/FeatureSettingsProjectConfirm/FeatureSettingsProjectConfirm.test.tsx
frontend/src/component/feature/FeatureView/FeatureSettings/FeatureSettingsProject/FeatureSettingsProjectConfirm/FeatureSettingsProjectConfirm.tsx
frontend/src/component/feature/FeatureView/FeatureView.tsx
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/client-feature-toggles/client-feature-toggle-store.ts
src/lib/features/client-feature-toggles/tests/client-feature-toggles.e2e.test.ts
src/lib/features/dependent-features/dependent-features-controller.ts
src/lib/features/dependent-features/dependent.features.e2e.test.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/features/feature-toggle/converters/feature-toggle-row-converter.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/feature-toggle-store.ts
src/lib/features/feature-toggle/tests/feature-toggle-last-seen-at.e2e.test.ts
src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts
src/lib/features/playground/advanced-playground.test.ts
src/lib/types/experimental.ts
src/server-dev.ts
src/test/e2e/api/admin/feature-archive.e2e.test.ts
src/test/e2e/api/client/feature.e2e.test.ts

Removing dependent features flag from:
* backend code
* UI code
* tests (flags + API calls)

chore: remove dependent feature flags

---

src/lib/features/feature-toggle/feature-toggle-service.ts

Formatting with upgraded biome

fix: format after biome update

---

src/lib/types/events.ts

Adds the events for create, update and delete environment
Relates to: [CTO-41](https://linear.app/unleash/issue/CTO-41/environment-mutation-not-in-event-log)

chore: Add environment mutation events (c.u.d)

---

src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts
src/lib/routes/admin-api/project/environments.ts
src/lib/services/environment-service.ts
src/lib/services/index.ts
src/lib/types/events.ts
src/test/e2e/services/environment-service.test.ts
src/test/e2e/services/project-service.e2e.test.ts

Project environment added and updated events
This is triggered by this part of the UI:
* I decided to create 2 new events and choose a naming that's close to what the backend is doing (in the UI we're "hiding" the project environment)

feat: project environment added and removed events

---

src/lib/routes/admin-api/project/environments.ts
src/lib/services/environment-service.ts
src/lib/types/events.ts
src/test/e2e/api/admin/project/environments.e2e.test.ts

Capturing default strategy updated events

feat: updated default strategy event

---

frontend/src/component/project/Project/ProjectOverview.tsx
frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts
frontend/src/hooks/useTableState.ts

- Updated `useFeatureSearch` to handle new project ID filters
- Modified `useTableState` hook - exported keys kept in query and localstorage by default and made type more relaxed

feat: update feature search

---

src/lib/types/events.ts

New event for tracking change request update events

feat: new event type for CR config update

---

frontend/src/component/admin/groups/Group/EditGroupUsers/EditGroupUsers.tsx

2 other group links were fixed before.

fix: groups link

---

website/docusaurus.config.js

Docs: Add redirect from '/advanced/groups' to '/reference/rbac#user-groups'

Docs: add redirect to docusaurus.config.js

---

frontend/package.json
frontend/src/hooks/usePersistentTableState.test.tsx
frontend/src/utils/testRenderer.tsx

Added tests for persistent table state reading data from local storage or URL with URL taking precedence. 
Also updated test renderer to reflect the order of providers in production setup

test: persistent table state

---

package.json
yarn.lock

Roll back unleash client to 5.0

fix: roll back client to 5.0

---

docker/yarn.lock

#5537 updated package.json but not yarn.lock

fix: docker deploy failing

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/PaginatedProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectOverview.tsx
frontend/src/utils/withTableState.ts

- Added `withTableState.ts`: New utility to centralize table state for paginated tables
- FeatureToggleListTable.tsx: Replaced manual table state code with withTableState utility
- Project Components: Cleaned imports, removed unused feature search and pagination code

refactor: table state management in withTableState

---

frontend/src/component/admin/roles/RoleForm/RoleForm.tsx
frontend/src/component/admin/roles/RoleForm/useRoleForm.ts
frontend/src/component/admin/roles/RoleModal/RoleModal.tsx

https://linear.app/unleash/issue/2-1717/improve-the-ux-when-all-the-required-fields-are-not-filled-in
Improves role form validation behavior.
We may want to look into a form validation library, like [react-hook-form](https://react-hook-form.com/), for future implementations.

feat: improve role form validation

---

frontend/src/component/common/FilterItem/FilterItem.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleFilters/FeatureToggleFilters.tsx

Segment operators set to expected values and correct enabled state.

feat: segments operators

---

frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts

Remove duplicated option in the menu.

fix: menu routes for new features page - mobile option

---

frontend/src/component/common/FilterItem/FilterItem.test.tsx
frontend/src/component/common/FilterItem/FilterItemChip/FilterItemChip.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleFilters/FeatureToggleFilters.tsx

Flex should flow to next lines when not enough space:
When more than 2 items are selected we do +n text:
On very small screens or with very long item names we can fall back to ellipsis:

feat: adjust styling for search filters

---

src/migrations/20231211122426-feature-strategies-created-by.js

Contains the migration that adds the column created_by to `feature_strategies`

chore: add migration for adding created_by to feature_strategies table

---

src/migrations/20231211122351-feature-tag-created-by.js

Contains the migration that adds the column created_by to `feature_tag`

chore: add migration for adding created_by to feature_tag table

---

src/migrations/20231211133920-add-created-by-to-roles.js

feat: add column created_by to roles table

---

src/migrations/20231211134633-add-created-by-to-apitokens.js

Adds a migration for adding created_by column to the api_tokens table.

feat: add created_by to api_tokens table

---

frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.test.tsx
frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts

Makes sure that only the latest search & filter key is cached. It will prevent old entries to pollute the cache.

feat: do not cache old search and filter results

---

frontend/src/component/common/FilterDateItem/FilterDateItem.tsx
frontend/src/component/common/FilterItem/FilterItem.tsx

Dropdown shows immediately upon adding a filter without extra clicking. Applied to list and date component.

feat: show dropdown immediately

---

frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ExperimentalColumnsMenu/ExperimentalColumnsMenu.styles.ts
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ExperimentalColumnsMenu/ExperimentalColumnsMenu.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ExperimentalProjectTable.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx

Simplified columns visibility menu.
`<ColumnsMenu />` is using it's own list of elements instead of inferring it from table columns definition. This component doesn't need it's internal structure to depend on react-table and it's interface.

feat: new columns visibility menu

---

src/migrations/20231212094044-event-created-by-user-id.js

Adds the column `created_by_user_id` to `events` table and adds index for it

chore: add created by user id to events

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ExperimentalProjectTable.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ProjectOverviewFilters.tsx

[Screencast from 2023-12-12 16-40-54.webm](https://github.com/Unleash/unleash/assets/964450/e35af54a-bae1-4092-9ee2-90761f8bc645)

feat: filters for project overview

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.test.tsx

Test initial display of features and then filtering features in a project with no features

test: feature toggle list table

---

frontend/src/component/common/FilterItem/FilterItem.styles.tsx
frontend/src/component/common/FilterItem/FilterItem.tsx

Search always stays on top. Filter options are scrollable. The entire filter item component takes 70% of viewport height so that it fits between the filter and the footer without obscuring anything

test: scrollable filter options and sticky search

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleFilters/FeatureToggleFilters.tsx

This is building block of abstraction for filters.

refactor: simplify configuration for filters

---

frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectFeatures.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ExperimentalColumnsMenu/ExperimentalColumnsMenu.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ExperimentalProjectTable.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/hooks/useDefaultColumnVisibility.ts
frontend/src/utils/withTableState.ts

In `ExperimentalProjectTable.tsx`, changes have been made to the columns configuration in order to handle column visibiilty. This includes adding id property to every column. Logic responsible for dynamically adjusts column visibility based on screen size was moved to new hook, `useDefaultColumnVisibility`

feat: project features - new columns visibility handling

---

frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ExperimentalProjectTable.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ProjectOverviewFilters.tsx

1. This is second table using the **Filters** component
Looks neat

refactor: project overview using filters component

---

frontend/src/component/filter/Filters.tsx

The unselected list should never allow for any elements that are already selected
This will need to be tested as part of another PR that adds tests for this component

fix: avoid duplicate unselected filters

---

src/migrations/20231213111906-add-reason-to-change-request-schedule.js

What it says on the tin.
Closes: # [1-1766](https://linear.app/unleash/issue/1-1766/add-reason-column-to-change-request-schedule)

feat: add reason column to change_request_schedule

---

frontend/src/component/filter/Filters/Filters.test.tsx

Makes sure that when we select filter items they disappear from the the selection list.

test: filter selection avoid duplicates

---

src/lib/app.ts
src/lib/middleware/conditional-middleware.ts
src/lib/middleware/cors-origin-middleware.ts
src/lib/middleware/secure-headers.ts

This commit enhances two aspects of CORS:
- Always support CORS preflight requests.
- Do not add additional secuity headers for prefligh calls.

fix: optimize cores headers

---

frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ExperimentalProjectTable.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/TablePlaceholder/TablePlaceholder.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/hooks/useRowActions.tsx
frontend/src/utils/withTableState.test.tsx
frontend/src/utils/withTableState.ts

- add table placeholder back
- add row actions column
- refactor actions into hook
- batch actions

Feat: row actions

---

frontend/src/component/filter/AddFilterButton.tsx
frontend/src/component/filter/FilterItem/FilterItemChip/FilterItemChip.tsx
frontend/src/component/filter/FilterItem/FilterItemChip/FilterItemOperator/FilterItemOperator.tsx
frontend/src/component/filter/Filters/Filters.tsx

* operator color adjustments
* hover text color for operators 
* hover for values same as for operators (it's a button now)
* button and badges heigh adjustments
* padding around the area
* make the icon inside the filter badges smaller
* make add filter button smaller

feat: adjust filter chips styling

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.test.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx

We should reset pagination on: search, filter, favorite first, sort order change
We need to make the same change on the other pages where we do new tables

feat: pagination reset on feature list

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/filter/AddFilterButton.tsx
frontend/src/component/filter/Filters/Filters.tsx
frontend/src/component/project/Project/ExperimentalProjectFeatures/ExperimentalProjectTable/ExperimentalProjectTable.tsx
frontend/src/hooks/usePersistentTableState.test.tsx
frontend/src/hooks/usePersistentTableState.ts

setTableState resets offset on every change internally so that if works automatically for all pages using the hook

feat: reset persistent table offset on change

---

frontend/src/component/common/Search/Search.test.tsx
frontend/src/component/common/Search/Search.tsx
frontend/src/component/common/Search/SearchSuggestions/SearchHistory.tsx
frontend/src/component/common/Search/SearchSuggestions/SearchSuggestions.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx

This is simple refactor. Just moving history part out of suggestions component.

feat: add history for search

---

frontend/src/component/common/TooltipLink/TooltipLink.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx

Do not sort on columns that backend doesn't support: tags, segments, stale
Also fixing word breaks on tags

feat: disable sorting on selected columns

---

frontend/src/component/common/FilterDateItem/FilterDateItem.test.tsx
frontend/src/component/common/FilterDateItem/FilterDateItem.tsx
frontend/src/component/filter/FilterItem/FilterItem.test.tsx
frontend/src/component/filter/FilterItem/FilterItem.tsx
frontend/src/component/filter/FilterItem/FilterItemChip/FilterItemChip.tsx
frontend/src/component/filter/Filters/Filters.tsx

Using different filter chips icons according to selection
Instead of passing icon string through layers I pass ReactNode label

feat: filter chips icons

---

frontend/src/component/common/Table/cells/FeatureTagCell/FeatureTagCell.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/PaginatedProjectFeatureToggles.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/hooks/useDefaultColumnVisibility.ts

- tags on project overview
- refactor of tags cell

feat: feature table tags

---

website/docusaurus.config.js
website/src/css/custom.css

Add Banner for New Years Community Party

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.test.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx

feat: update message with no feature toggles

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/PaginatedProjectFeatureToggles.tsx

fix: disable sort

---

frontend/src/component/filter/FilterItem/FilterItem.styles.tsx
frontend/src/component/filter/FilterItem/FilterItem.tsx

Tab navigation + you can select with enter (not just click)
Next PR will also add up/down arrow support

feat: keyboard navigation filter item

---

frontend/src/component/filter/FilterItem/FilterItem.test.tsx
frontend/src/component/filter/FilterItem/FilterItem.tsx

Navigation with up and down arrow in addition to tab that we supported before. 
https://github.com/Unleash/unleash/assets/1394682/bf96059f-22ad-433a-b864-3a809bed49c2

feat: up and down arrow navigation for filter items

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/PaginatedProjectFeatureToggles.tsx

- always show favorites and selection
- reset local storage columns cache

fix: column visibility

---

frontend/src/component/feature/FeatureToggleList/ExportDialog.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx
src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-store.ts
src/lib/openapi/spec/export-query-schema.ts

Project export allows to export all project features regardless of what's selected. Use bulk export for selection-based export.
Dialog shows that you're exporting all project feature toggles.
https://github.com/Unleash/unleash/assets/1394682/1ab6a0aa-161a-4492-8da8-871b7781c83a

feat: export all features in project

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/PaginatedProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ManageTags.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/MoreActions.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ProjectFeaturesBatchActions.tsx

Reload paginated features on project overview after batch action.

fix: project features batch actions refetch

---

silly-file
website/vercel.json

test: testing vercel docs build

---

frontend/src/component/common/FilterDateItem/FilterDateItem.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/feedbackNew/FeedbackComponent.tsx
frontend/src/component/feedbackNew/FeedbackContext.ts
frontend/src/component/feedbackNew/FeedbackProvider.tsx
frontend/src/component/feedbackNew/useFeedback.tsx
frontend/src/index.tsx

This adds component, which will allow to draw feedback component based on incoming data.

feat: feedback skeleton ui

---

src/lib/db/feature-strategy-store.test.ts
src/lib/features/change-request-segment-usage-service/change-request-segment-usage-read-model.test.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/fakes/fake-feature-toggle-store.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/feature-toggle-store.ts
src/lib/features/feature-toggle/tests/archive-feature-toggles.e2e.test.ts
src/lib/features/feature-toggle/tests/feature-toggle-store.e2e.test.ts
src/lib/features/feature-toggle/tests/feature-toggle-strategies-store.e2e.test.ts
src/lib/features/feature-toggle/tests/feature-toggles.auth.e2e.test.ts
src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts
src/lib/features/feature-toggle/types/feature-toggle-store-type.ts
src/lib/features/project-environments/environment-service.test.ts
src/lib/routes/client-api/metrics.test.ts
src/lib/schema/feature-schema.ts
src/lib/services/state-service.test.ts
src/lib/services/state-service.ts
src/lib/services/version-service.test.ts
src/lib/types/model.ts
src/test/e2e/api/admin/instance-admin.e2e.test.ts
src/test/e2e/api/admin/project/variants.e2e.test.ts
src/test/e2e/services/playground-service.test.ts
src/test/e2e/services/project-health-service.e2e.test.ts
src/test/e2e/services/project-service.e2e.test.ts
src/test/e2e/stores/feature-environment-store.e2e.test.ts
src/test/e2e/stores/feature-tag-store.e2e.test.ts

Implements setting values on the created_by_user_id column on the features table in the db

feat: implement createdByUserId for all features

---

frontend/src/component/application/ApplicationEdit/ApplicationEdit.tsx
frontend/src/component/application/ApplicationList/ApplicationList.tsx
frontend/src/component/application/ApplicationUpdate/ApplicationUpdate.tsx

- Fixed app icon rendering
- Added tooltip with link to MUI
https://linear.app/unleash/issue/UNL-222/icons-for-applications-arent-working

Fix: icon rendering issue in ApplicationList and add help to app update

---

frontend/src/component/feedbackNew/FeedbackComponent.tsx

Completes the main UI for feedback.
Next steps is to correct data flow and finetuning.

feat: feedback screen main ui

---

website/docs/reference/feature-toggle-variants.md

Hello,
I'd like to add a reference of the SDK for C++ to the supported Client list for Feature Toggle variants.
Thanks!

Doc: C++ client supports now feature toggle variants.

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.test.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/feedbackNew/FeedbackComponent.tsx
frontend/src/component/feedbackNew/FeedbackContext.ts
frontend/src/component/feedbackNew/FeedbackProvider.tsx
frontend/src/hooks/api/actions/useUserFeedbackApi/useUserFeedbackApi.ts

Added API hooks and now frontend actually sends data to database.

feat: ui now connects to backend, full e2e

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/feedbackNew/FeedbackComponent.tsx
frontend/src/component/feedbackNew/FeedbackContext.ts
frontend/src/hooks/api/actions/useUserFeedbackApi/useUserFeedbackApi.ts
frontend/src/hooks/useSubmittedFeedback.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Now it will track if feedback has been submitted in local storage.

feat: keep feedback submission in local storage

---

frontend/src/component/feedbackNew/FeedbackComponent.tsx
frontend/src/hooks/api/actions/useUserFeedbackApi/useUserFeedbackApi.ts
frontend/src/hooks/useSubmittedFeedback.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts
src/lib/openapi/spec/ui-config-schema.ts
src/lib/routes/admin-api/config.ts
src/lib/types/option.ts

Make storage work react way.
Make feedback url configurable by env variable.

feat: make local storage work and make feedback url configurable

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

Adds a database query timer for the client features query.

task: add timer for client feature query

---

frontend/src/component/App.tsx
frontend/src/component/admin/Admin.tsx
frontend/src/component/admin/adminRoutes.ts
frontend/src/component/admin/license/License.tsx
frontend/src/component/banners/externalBanners/ExternalBanners.tsx
frontend/src/component/banners/internalBanners/LicenseBanner.tsx
frontend/src/hooks/api/actions/useLicenseAPI/useLicenseApi.ts
frontend/src/hooks/api/getters/useLicense/useLicense.ts
frontend/src/interfaces/uiConfig.ts

Show banner for enterprise self-hosted if they violate their license.

wip: license checker for self-hosted

---

frontend/src/component/integrations/IntegrationList/IntegrationList.styles.tsx
frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx
frontend/src/component/layout/MainLayout/MainLayout.tsx
frontend/src/component/menu/Header/Header.tsx

https://linear.app/unleash/issue/UNL-309/1500px-width-ui-issues
UI fixes, improvements and adjustments related to the recent increase in width on the UI. Tried to follow the feature flag logic wherever it made sense.

fix: UI improvements related to the increase of width

---

frontend/src/component/feedbackNew/FeedbackComponent.tsx

feat: add click away handler to sidebar content

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetrics.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.test.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

Extended metrics options for week, month and 3 months
Changes:
* added flag
* conditionally adding new extended options
* testing new capability
* generalized parsing logic
Backend will need to support the new options and not erase the data after 48 hours.

feat: extended metrics options ui

---

website/docusaurus.config.js

Docs: Remove Community Party Banner

---

frontend/src/hooks/api/actions/useIncomingWebhooksApi/useIncomingWebhooksApi.ts
frontend/src/hooks/api/getters/useIncomingWebhooks/useIncomingWebhooks.ts
frontend/src/interfaces/incomingWebhook.ts

https://linear.app/unleash/issue/2-1813/create-new-incoming-webhook-hooks-on-the-frontend
Adds incoming webhook hooks to help us with CRUD operations on the frontend.

chore: incoming webhook hooks

---

frontend/src/hooks/api/actions/useIncomingWebhookTokensApi/useIncomingWebhookTokensApi.ts
frontend/src/hooks/api/getters/useIncomingWebhookTokens/useIncomingWebhookTokens.ts
frontend/src/interfaces/incomingWebhook.ts

https://linear.app/unleash/issue/2-1814/create-new-incoming-webhook-token-hooks-on-the-frontend
Adds incoming webhook token hooks to help us with CRUD operations on the frontend.

chore: incoming webhook token hooks

---

frontend/src/component/user/UserProfile/UserProfileContent/UserProfileContent.tsx

feat: overflow email when it's too long

---

src/migrations/20240109093021-incoming-webhooks-description.js

https://linear.app/unleash/issue/2-1822/incoming-webhooks-add-description
A description field will help us better distinguish incoming webhooks and their purpose.

chore: incoming webhooks description migration

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

Just a flag for an enterprise feature

feat: add automated actions flag

---

src/lib/features/project-environments/environment-store.ts

This will give us prometheus metrics on environment lookups in the database

feat: add db metrics for environment-store

---

frontend/cypress/integration/import/import.spec.ts

the wait was after fetching the feature page, should be before probably.

fix: import test wait should be between import and page load

---

src/lib/types/events.ts

To facilitate emitting this event in Enterprise

chore: add schedule suspended event type

---

.github/workflows/build_frontend_prs.yml

- Removes redundant lint check
- Runs linting before test

chore: remove redundant linting check, lint before test

---

frontend/src/component/App.tsx
frontend/src/index.tsx

We were unable to send plausible events from feedback. Now we can.

refactor: move plausible context on top of feedback

---

src/lib/metrics.test.ts
src/lib/metrics.ts

Add environmentType to feature_toggle_update metrics.

feat: include environment type label in feature_toggle_update metrics

---

frontend/cypress/integration/import/import.spec.ts

This will hopefully make the test faster and more stable

chore: wait for post to finish instead of waiting a fixed time

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.styles.ts
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx

These were introduced by prs created before the new biome update.

chore: fix lints on main

---

frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEdit.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/ResolveInput/ResolveInput.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/RestrictiveLegalValues/RestrictiveLegalValues.test.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/RestrictiveLegalValues/RestrictiveLegalValues.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditHeader/ConstraintAccordionEditHeader.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionHeaderActions/ConstraintAccordionHeaderActions.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.test.tsx

This PR adds undo functionality so you can restore the state of your constraint if you make a mistake. We also amend the autosave functionality to only apply when values are changed and you have a valid value. See demo: 
https://www.loom.com/share/da704da8aee94ac18d4caae697426802

feat: add undo

---

frontend/src/component/admin/roles/RoleForm/RoleForm.tsx
frontend/src/component/admin/roles/RoleForm/RolePermissionCategories/RolePermissionCategories.tsx
frontend/src/component/admin/roles/RoleForm/RolePermissionCategories/RolePermissionCategory.tsx
frontend/src/component/admin/roles/RoleForm/useRoleForm.ts
frontend/src/component/admin/roles/RoleModal/RoleModal.tsx

This seems to improve the performance in the role form while still maintaining the same validation logic.
A big factor was the memoization of the categories calculation and respective elements, which is especially impactful when there are many environments.

fix: role form sluggishness

---

frontend/src/component/admin/auth/AutoCreateForm/AutoCreateForm.tsx
frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx
frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx
frontend/src/component/common/RoleSelect/RoleSelect.tsx
src/lib/db/access-store.ts
src/test/e2e/services/user-service.e2e.test.ts

Lists all root roles in SSO config, including custom root roles.

feat: list all root roles in SSO config

---

frontend/src/component/common/Table/cells/DateTimeCell/DateTimeCell.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsTable/FeatureMetricsTable.test.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsTable/FeatureMetricsTable.tsx

Local time for hourly results
UTC for daily results

feat: feature metrics table timezone

---

src/migrations/20240111075911-update-system-user-email.js

Updates it from 'system@getunleash.io' to `null`. We don't have that address registered (and probably don't want it), so we'll leave it empty.
This is a companion PR to
https://github.com/Unleash/unleash/pull/5893. With both of those
merged, the system user in the DB should match the one defined in `core.ts`

chore: remove system user's email in db.

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx
frontend/src/hooks/usePlausibleTracker.ts

Event: feature-metrics
event type: change-period
hoursBack: e.g. 48

feat: hours back feature metrics tracking

---

src/lib/types/events.ts

Define event types for actions

feat: event types for actions

---

src/lib/features/index.ts

Overlooked on https://github.com/Unleash/unleash/pull/5910

chore: missing export

---

src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts

Do not import archived parent or archived child.

fix: should not import archived child and parent

---

src/lib/services/email-service.ts
src/mailtemplates/scheduled-change-conflict/scheduled-change-conflict.html.mustache
src/mailtemplates/scheduled-change-conflict/scheduled-change-conflict.plain.mustache

Updating the UI of the email template
Closes # [1-1940](https://linear.app/unleash/issue/1-1940/improve-scheduled-change-conflict-template)
Before
After:

Updated scheduled-change-conflict

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsChips/FeatureMetricsChips.tsx

feat: adjust height on applications list in metrics

---

frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionHeaderActions/ConstraintAccordionHeaderActions.tsx
frontend/src/component/common/NewConstraintAccordion/NewConstraintAccordionList/NewConstraintAccordionList.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/FeatureStrategyConstraints.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.test.tsx

Use id to resolve autosave constraints now that we have consistent id references

fix: refactor autosave to use the id to resolve the constraint

---

src/lib/services/api-token-service.test.ts
src/lib/services/api-token-service.ts
src/lib/services/event-service.test.ts
src/lib/services/event-service.ts
src/lib/types/events.ts

The new method makes it easy to store events without having to know the details about how we define the username or userId

chore: change event service method

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetrics.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsChips/FeatureMetricsChips.tsx

Checking inclusion not array length. Are all available apps contained by the actually selected apps.

fix: precise selected all chips check

---

frontend/src/component/common/Table/PaginatedTable/PaginatedTable.tsx

With 2 items there's no need for pagination:

fix: show pagination when enough items

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx

Setting 50% width to the name columns and 1% to the others. This is similar to project features view.

fix: prevent jumping columns in search view

---

frontend/src/hooks/usePersistentTableState.test.tsx

A test guarding that array params are correctly propagated from local storage to URL

test: show array param decoder

---

frontend/src/component/feedbackNew/FeedbackComponent.tsx
frontend/src/component/feedbackNew/FeedbackProvider.tsx

Add more comprehensive tracking of feedback

fix: add more comprehensive metrics for feedback

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsChips/FeatureMetricsChips.tsx

feat: show select all button when more than 1 item

---

src/mailtemplates/scheduled-change-conflict/scheduled-change-conflict.html.mustache

Fixing the mobile template (this is before the fix)
- reducing padding around the content
- fixing line-height for the content
- fixing the footer links

Fix email template scheduled change conflict

---

frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/IncomingWebhooksForm.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/IncomingWebhooksFormURL.tsx

Small UI improvements in the new incoming webhooks form after aligning with @nicolaesocaciu.

fix: incoming webhooks form UI adjustments

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/UsersChart/UsersChart.tsx
frontend/src/component/executiveDashboard/UsersChart/UsersChartComponent.tsx

Users chart with tooltip and legend

Feat: dashboard users chart frontend

---

frontend/src/component/executiveDashboard/FlagsChart/FlagsChart.tsx
frontend/src/component/executiveDashboard/FlagsChart/FlagsChartComponent.tsx
frontend/src/component/executiveDashboard/UsersChart/UsersChartComponent.tsx

Number of flags component is a copy paste of the number of users component with minor tweaks.
Details:
* the only change is label names and one field (inactive -> archived)
* added title for each chart
* following Write-Everything-Twice approach so that abstraction emerges with the 3rd similar usage. For now you can do diff on the components and see what differs

feat: number of flags component

---

website/README.md

Minor addition to set correct local dir context in terminal when setting up a local docs instance

docs/improve website README.md with local docs server installation step

---

frontend/src/hooks/api/actions/useActionsApi/useActionsApi.ts
frontend/src/hooks/api/getters/useActions/useActions.ts
frontend/src/interfaces/action.ts
frontend/src/interfaces/uiConfig.ts

https://linear.app/unleash/issue/2-1857/create-new-action-hooks-on-the-frontend
Adds action hooks to help us with CRUD operations on the frontend, similar to https://github.com/Unleash/unleash/pull/5788 and https://github.com/Unleash/unleash/pull/5790

chore: add new action hooks

---

website/docs/unleash-academy/academy.md

Fixed a small typo "Learnings Paths" -> "Learning Paths".

Small typo fix.

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/NewFeatureStrategyForm.tsx
frontend/src/component/feature/StrategyTypes/NewStrategyVariants.tsx

fix: update stickiness between tabs

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/NewFeatureStrategyForm.tsx

fix: move useEffect before renders

---

src/lib/server-impl.ts

Validate we're not using locks

chore: add logs

---

frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.test.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/featureStrategyFormTestSetup.ts
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/NewFeatureStrategyEdit.test.tsx

Checking if variants don't add meta info. 
Checking if stickiness in variants is propagated from the strategy settings.

test: variant edit corner cases

---

frontend/src/component/strategies/StrategiesList/StrategiesList.tsx

Hints:
* https://stackoverflow.com/questions/67534822/react-table-in-material-ui-dialog-causes-error-maximum-update-depth-exceeded
* https://stackoverflow.com/questions/63549751/react-maximum-update-depth-exceeded-using-react-table

fix: strategy screen re-rendering table bug

---

.floe/config.json
.floe/rules/spelling-and-grammar.md
website/docs/how-to/how-to-add-feature-flag-naming-patterns.mdx
website/docs/how-to/how-to-add-sso-open-id-connect.md
website/docs/how-to/how-to-create-and-assign-custom-project-roles.md
website/docs/how-to/how-to-define-custom-context-fields.md
website/docs/how-to/how-to-environment-import-export.mdx
website/docs/how-to/how-to-import-export.md
website/docs/how-to/how-to-schedule-feature-releases.mdx
website/docs/how-to/how-to-send-feature-updates-to-slack-deprecated.md
website/docs/how-to/how-to-set-up-group-sso-sync.md
website/docs/how-to/how-to-synchronize-unleash-instances.md

This is a demo that uses [Floe](https://www.floe.dev/) to review the `how-to` directory using the `spelling-and-grammar` rule.
You can read more about the tool here: https://www.floe.dev/docs

docs: spelling and grammar 

---

package.json
yarn.lock

fix: variant stickiness fix node client

---

frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/DeleteProjectForm.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/UpdateProject.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/Settings.tsx

Small fix to the project settings title, correcting it and making it consistent.

fix: project settings title

---

website/docs/using-unleash/deploy/getting-started.md

This pull request is a simple change in the document as follows.
put UNLEASH_DEFAULT_ADMIN_PASSWORD inside ``!
`unleash/website/docs/using-unleash/deploy/getting-started.md`

Getting Started Self-Hosting unleash

---

frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActions.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTable.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx

https://linear.app/unleash/issue/2-1858/add-new-actions-tab-to-project-settings
Adds the new actions tab to project settings, hidden behind the `automatedActions` feature flag.

chore: project actions tab

---

src/migrations/20240124123000-add-enabled-to-action-sets.js

Adds enabled to action sets table

feat(2-1879): add enabled to action sets

---

src/migrations/20240125085703-users-table-increae-image-url-size.js

Change the image_url column to text
Closes # https://github.com/orgs/Unleash/projects/8/views/1?pane=issue&itemId=51021534

chore: change users image_url column to text

---

src/migrations/20240125084701-add-user-trends.js

A table for storing user trends (stats over time). The PK is week_id (e.g. 2024-03 - year and week of the year). Inactive users can be calculated in memory and don't need to be stored. We keep separate created_at to know when the scheduler run. 
Based on https://github.com/Unleash/unleash/pull/5914/files.

feat: user trends migration

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsActionsCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsFiltersCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTriggerCell.tsx

Includes some small fixes and improvements to the actions table UI:
- Fix webhook icon not properly loading
- Make actions execution param names bold in the tooltip
- Make filters param names bold in the tooltip

fix: actions table UI improvements

---

src/lib/db/project-store.ts
src/lib/openapi/spec/project-schema.ts
src/lib/types/model.ts
src/test/fixtures/fake-project-store.ts

/projects returns not just each project feature count but also stale and potentially stale count. This resource is used in the projects screen but the underlying store will be used for trends calculation that also requires stale info.
This is the UI using the existing resource. 
Explain plan comparison before and after:

feat: stale flags count per project

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/FlagStats/FlagStats.tsx
frontend/src/themes/themeTypes.ts

feat: flag widget

---

src/migrations/20240126095544-add-flag-trends.js

feat: flag trends db migration

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
frontend/src/hooks/useHiddenEnvironments.ts

fix: hidden envs

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsForm.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/useProjectActionsForm.ts
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsModal.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTable.tsx

https://linear.app/unleash/issue/2-1882/ui-add-actions-modal-and-form
Adds actions modal and form, allowing users to create and edit actions.
The main thing that is missing is adding the remaining fields, which will be included in a later PR.

chore: actions modal form

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
frontend/src/hooks/useGlobalLocalStorage.ts
frontend/src/hooks/useHiddenEnvironments.ts
frontend/src/utils/storage.test.ts
frontend/src/utils/storage.ts

On Friday we fixed incorrect hidden environments persistence. This PR cleans things up.
* bring back Set persistence as Array
* fix type for hidden environments
* add code to recover from incorrect local storage

refactor: cleanup fix for persistent set

---

src/lib/features/feature-toggle/feature-toggle-store.ts

Change the sorting of features to migrate created_by_user_id for, and filter out unresolvable feature/users
Query tested manually in enterprise

chore: filter on token username and user id in SQL instead

---

website/docs/feature-flag-tutorials/react/examples.md
website/docs/feature-flag-tutorials/react/implementing-feature-flags.md

- Simplified wording
- More descriptive ALT text for images
- Included YouTube tutorial link
- Improve code indentation in some code blocks
YouTube link at the top of a tutorial or near the bottom?

fix: updating links across the React docs

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/FlagsChart/FlagsChartComponent.tsx
frontend/src/component/executiveDashboard/UserStats/UserStats.tsx

Align widgets properly on main screen. Responsive view in next PRs

fix: dashboard layout

---

src/mailtemplates/scheduled-change-conflict/scheduled-change-conflict.html.mustache
src/mailtemplates/scheduled-execution-failed/scheduled-execution-failed.html.mustache
src/mailtemplates/scheduled-execution-failed/scheduled-execution-failed.plain.mustache

Improving the email template design
- @andreas-unleash i need you to fix the button for the change request in case it's not correct like this
- also removing some leftover style from the "scheduled change conflict" email

improve:schedule-execution-failed-email

---

src/lib/db/project-store.ts
src/lib/openapi/spec/project-schema.ts
src/lib/types/model.ts
src/test/fixtures/fake-project-store.ts

Exposing average time to production for the project flag trends. This data will be also available here so we may consider adding it in addition to health in future:

feat: expose project time to production for project flag trends

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/db/segment-store.test.ts
src/lib/db/segment-store.ts
src/lib/features/segment/segment-controller.ts
src/lib/services/segment-service.ts
src/lib/types/experimental.ts
src/test/e2e/api/admin/segment.e2e.test.ts
src/test/e2e/api/client/segment.e2e.test.ts

What it says on the tin. Removes all uses of the detectSegmentUsageInChangeRequests flag.

chore: remove detectSegmentUsageInChangeRequests flag

---

src/lib/features/scheduler/scheduler-service.test.ts
src/lib/features/scheduler/scheduler-service.ts

Adding overrun protection. When there's the same job id already pending we wait for the next interval. 
I decided to keep pending jobs ids instead of replacing setInterval with setTimeout since it's less invasive.

feat: scheduler overrun protection

---

frontend/package.json
frontend/yarn.lock
renovate.json

Renovate upgraded react router again breaking navigation (however in a subtle way). To reproduce the error go to projects/default/metrics and manually update the end of url to /logs at the end of the URL. It should freeze and the process should start increasing memory usage. With the downgrade of router I can't reproduce it anymore.
We downgraded router in the past: https://github.com/Unleash/unleash/pull/5512
To prevent the same mistake I'm excluding router from the renovate bot.

fix: freezing navigation

---

frontend/package.json
frontend/yarn.lock
renovate.json
website/docs/unleash-academy/advanced-for-devs.md
website/docs/unleash-academy/foundational.md
website/docs/unleash-academy/managing-unleash-for-devops.md
website/package.json
website/yarn.lock

This PR changes the wording for the courses from "estimated time burden" to "estimated time".

docs: change "time burden" to "time investment"

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/LineChart/ChartTooltip/ChartTooltip.tsx
frontend/src/component/executiveDashboard/ProjectHealthChart/ProjectHealthChart.tsx
frontend/src/component/executiveDashboard/executive-dashboard-utils.ts

Adds the project health widget to the edb:

feat: project health widget

---

package.json

Set the version in package json to represent the new release

chore: set version

---

website/src/components/unleash-academy/Banner.jsx
website/src/components/unleash-academy/CourseBanner.jsx
website/src/components/unleash-academy/Links.jsx
website/src/css/custom.css

This PR cleans up the the CSS for the recent academy banners, sharing styles where it seemed suitable.
Main points:
- share styling of the level badge between the links and the course banner
- share styling of general banner shape, borders, spacing, between the main unleash academy banner and the course-specific banner

docs(refactor): clean up academy css

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/FlagsProjectChart/FlagsProjectChart.tsx
frontend/src/component/executiveDashboard/TimeToProductionChart/TimeToProductionChart.tsx
frontend/src/component/executiveDashboard/useProjectChartData.ts

Adding new chart
Also:
* removing duplication by extracting project data hook
* fixed initial undefined data error

feat: time to production chart

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx

Fixing: If you manually put invalid url with columns you may save an incorrect column name:

fix: exclude columns with commas

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetrics.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsTable/ApplicationsCell.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsTable/FeatureMetricsTable.tsx

Multiple apps selected:
Single app selected:

fix: show all selected application names

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetrics.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsTable/ApplicationsCell.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsTable/FeatureMetricsTable.tsx

(cherry picked from commit 1834f9f8bcee2535debffcd61318132555102f4d)
Closes #

fix: show all selected application names (#6110)

---

frontend/src/component/executiveDashboard/FlagsProjectChart/FlagsProjectChart.tsx
frontend/src/component/executiveDashboard/ProjectHealthChart/ProjectHealthChart.tsx
frontend/src/component/executiveDashboard/TimeToProductionChart/TimeToProductionChart.tsx
frontend/src/component/feedbackNew/FeedbackList.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts
frontend/src/hooks/api/getters/useFeedbackPosted/useFeedbackPosted.ts
frontend/src/interfaces/uiConfig.ts
src/server-dev.ts

The page can only be navigated if you know direct url `/feedback`

feat: add posted feedback table

---

frontend/src/component/demo/demo-topics.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/NewFeatureStrategyForm.tsx

This PR adds the necessary steps for the demo guidance to work properly with the new form

fix: add new steps to demo guide

---

src/lib/db/feature-tag-store.ts
src/lib/features/client-feature-toggles/client-feature-toggle-store.ts
src/lib/features/instance-stats/instance-stats-service.ts
src/lib/features/maintenance/maintenance-service.ts
src/lib/features/scheduler/scheduler-service.ts
src/lib/routes/admin-api/config.ts
src/lib/services/version-service.test.ts
src/lib/services/version-service.ts

https://github.com/Unleash/unleash/pull/6118 
https://github.com/Unleash/unleash/pull/6119 
https://github.com/Unleash/unleash/pull/6120
https://github.com/Unleash/unleash/pull/6124 
https://github.com/Unleash/unleash/pull/6125

chore: port db changes to 5.9

---

frontend/src/component/admin/apiToken/ApiTokenForm/useApiTokenForm.ts
frontend/src/component/common/ApiTokenTable/useApiTokenTable.tsx

Users should not guess that proxy and edge tokens are the same thing:

feat: make edge explicit in UI

---

src/lib/users/inactive/inactive-users-store.ts
src/test/e2e/users/inactive/inactive-users-service.test.ts

Knex wasn't formatting the query like I expected. This changes the query to use more AND, less ORs

fix: inactive users query was too wide

---

src/lib/users/inactive/inactive-users-controller.ts
src/lib/users/inactive/inactive-users-store.ts
src/test/e2e/users/inactive/inactive-users-service.test.ts

Also anonymises user list if running in demo.

fix: filter out service and system users from inactive users list

---

src/lib/services/proxy-service.ts

We found that proxy repository was started twice because unleash client has auto start enabled by default.

fix: disable double start

---

src/lib/proxy/proxy-repository.ts
src/lib/services/user-feedback-service.ts

* Log errors from proxy repository (currently it was empty information)
* rename event handler

fix: proxy repository error handling

---

frontend/package.json
frontend/src/utils/testServer.ts
frontend/yarn.lock

First update to 1.x before 2.x with breaking changes.

chore: update msw

---

frontend/package.json
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.test.tsx
frontend/src/utils/testServer.ts
frontend/yarn.lock

New way of mocking HTTP responses in msw 2.x: https://mswjs.io/docs/basics/mocking-responses#json-responses

chore: upgrade to msw 2.x with new response declaration

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx

fix: overflowing description

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

What it says on the box
Closes # [1-2030](https://linear.app/unleash/issue/1-2030/create-inmemoryscheduledchangerequests-flag)

chore: add inMemoryScheduledChangeRequests flag

---

website/docs/contributing/developer-guide.md

I played with the OpenAI APIs to see how easy it would be to get help improving the docs, and this is the results of getting it to improve the developer guide.

docs: Developer guide improvements

---

website/docs/reference/feature-flag-naming-patterns.mdx

We forgot to update this after the release, so just cleaning it up now.

docs: update availability notice to say patterns were released in 5.7

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

Adds the feature flag for use in request traffic counting

chore: add feature flag for request counting inside Unleash

---

src/lib/openapi/index.ts
src/lib/openapi/spec/project-application-schema.ts
src/lib/openapi/spec/project-applications-schema.test.ts
src/lib/openapi/spec/project-applications-schema.ts

Currently keeping flat structure and separate out into multiple requests(schemas) if needed.
In future, we will also add dates.

feat: preliminary project applications schema

---

frontend/src/component/admin/roles/RolesPage.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/access/createAccessService.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/services/access-service.test.ts
src/lib/services/access-service.ts
src/lib/types/experimental.ts
src/test/fixtures/access-service-mock.ts

https://linear.app/unleash/issue/2-1308/remove-customrootroleskillswitch-flag
Cleans up the `customRootRolesKillSwitch` flag.

chore: clean up customRootRolesKillSwitch

---

src/lib/features/project/project-controller.ts
src/lib/features/project/projects.e2e.test.ts
src/lib/openapi/spec/index.ts
src/lib/routes/admin-api/index.ts
src/lib/services/project-service.ts

Just adding controller/service layer, connecting with schema.
Next PR will implement store and e2e tests.

feat: project applications controller/service layer

---

package.json
yarn.lock

Upgraded dependency on http client in node unleash client (https://github.com/Unleash/unleash-client-node/pull/583).

chore: upgrade unleash client

---

frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/useIncomingWebhooksForm.ts
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/useProjectActionsForm.ts
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsModal.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTable.tsx
frontend/src/hooks/api/actions/useActionsApi/useActionsApi.ts
frontend/src/hooks/api/getters/useActions/useActions.ts

Action should be relative to a project (in general).

chore: Move actions inside projects

---

frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/useIncomingWebhooksForm.ts
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsActionsCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/InnerContainerBox.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsActionItem.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFilterItem.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsForm.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/useProjectActionsForm.ts
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsModal.tsx
frontend/src/hooks/api/actions/useActionsApi/useActionsApi.ts
frontend/src/hooks/api/getters/useActions/useActions.ts
frontend/src/hooks/api/getters/useIncomingWebhooks/useIncomingWebhooks.ts
frontend/src/interfaces/action.ts

https://linear.app/unleash/issue/2-1938/refactor-project-actions
Refactors project actions to not include the project in the payload.
Includes other misc scouting.

refactor: project actions

---

src/mailtemplates/scheduled-change-conflict/scheduled-change-conflict.html.mustache
src/mailtemplates/scheduled-execution-failed/scheduled-execution-failed.html.mustache

Fix: removing a css line that was blocking some style
Improvement: clean up some unnecessary comments 
Before the fix:
after:

fix-css-update-for-CR-email-template

---

USERS.md

Since we've been using Unleash to manage feature flags for a while, I'm adding a pull-request to be mentioned as a proud user. Thanks a lot for this tool! 🚀

chore: t-mobile added as a proud user

---

frontend/src/component/layout/Error/Error.tsx
frontend/src/index.tsx
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/project/project-applications.e2e.test.ts
src/lib/features/project/project-controller.ts
src/lib/features/project/project-store.ts
src/lib/features/project/projects.e2e.test.ts
src/lib/types/experimental.ts
src/server-dev.ts

1. Add flag
2. Add e2e test with more complete example
3. Some bug fixes

feat: sdk reporting flag and e2e test

---

website/docs/using-unleash/deploy/license-keys.mdx

Added statement to contact customer success for help

docs: Update license-keys.mdx

---

frontend/src/component/executiveDashboard/UsersChart/UsersChart.tsx
src/lib/features/feature-search/feature-search-store.ts
src/lib/features/feature-search/search-utils.ts
src/lib/features/project/project-applications.e2e.test.ts
src/lib/features/project/project-controller.ts
src/lib/features/project/project-service.ts
src/lib/features/project/project-store-type.ts
src/lib/features/project/project-store.ts
src/lib/openapi/spec/project-applications-schema.test.ts
src/lib/openapi/spec/project-applications-schema.ts
src/lib/types/model.ts
src/test/fixtures/fake-project-store.ts

Uses exactly same pattern as search-store. Nothing too crazy here.
Most code is in tests.

feat: project applications server side paging and sorting and filtering

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/Gauge/Gauge.tsx
frontend/src/component/executiveDashboard/LineChart/ChartTooltip/ChartTooltip.tsx
frontend/src/component/executiveDashboard/TimeToProduction/TimeToProduction.tsx
frontend/src/component/executiveDashboard/useProjectChartData.ts
frontend/src/themes/dark-theme.ts
frontend/src/themes/theme.ts
frontend/src/themes/themeTypes.ts

feat: dashboard lead time gauge

---

src/lib/features/scheduler/schedule-services.ts

Removing jitter from time sensitive jobs that need to run straight away.

fix: remove jitter from time sensitive scheduled jobs

---

frontend/src/component/application/ApplicationList/ApplicationUsageCell/ApplicationUsageCell.tsx

This is in the applications table.

fix: add missing key to list of application projects

---

frontend/src/component/featureTypes/FeatureTypeEdit/FeatureTypeForm/FeatureTypeForm.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooks.tsx
frontend/src/component/integrations/IntegrationList/IntegrationList.tsx
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportCard/ReportCard.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx
website/docs/reference/technical-debt.md

https://linear.app/unleash/issue/UNL-338/adjustments-incoming-webhooks-actions
Includes misc UI/UX fixes, including a typo, the vertical alignment of the Enterprise badge in project settings and the way incoming webhooks are displayed in non-Enterprise plans.

fix: misc UI/UX fixes

---

website/docs/using-unleash/troubleshooting/https.md
website/docusaurus.config.js
website/sidebars.js
website/vercel.json

Added troubleshooting how to run Unleash over HTTPS

docs: troubleshooting unleash over https

---

src/lib/util/metrics/createCounter.ts
src/lib/util/metrics/createGauge.ts
src/lib/util/metrics/createSummary.ts

Improves typing in our Prometheus metric helpers.

refactor: better prom metric helper types

---

frontend/src/component/application/ConnectedInstances/ConnectedInstances.tsx
frontend/src/component/application/ConnectedInstances/ConnectedInstancesTable.tsx
frontend/src/component/application/ConnectedInstances/useConnectedInstancesTable.tsx

Don't hide anything yet, so remove related code. Plus other code we don't need has been removed.

chore: don't hide columns in connected instances table

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsForm.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep.tsx

Small UI/UX adjustments to the actions form after aligning.

fix: small ui/ux adjustments to the actions form

---

docker/package.json
docker/yarn.lock
package.json
yarn.lock

Add resolution to IP library so transitive dependencies also use the latest library

chore: pin ip library

---

docker/yarn.lock

Regenerate yarn.lock from docker folder: `rm cloud/yarn.lock && cd cloud && yarn install`
Resolves: https://github.com/Unleash/unleash/security/dependabot/120

chore: regenerate yarn.lock of docker folder

---

frontend/src/component/application/ConnectedInstances/ConnectedInstances.tsx

This makes it more obvious to everyone what the buttons do.

feat: wrap buttons in a fieldset and add an explanatory legend.

---

frontend/src/component/application/ApplicationOverview.tsx

Initial boxes for the successful application and list of environments:
Next PR:
* connecting lines between the boxes
* warning box
* warning environment

feat: styled application environment boxes

---

frontend/src/component/changeRequest/ChangeRequestOverview/ApplyButton/ApplyButton.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.test.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx
frontend/src/component/common/MultiActionButton/MultiActionButton.tsx

Cherry-pick MultiActionButton fix to the 5.9 branch

fix: generalize multi action button (#6294)

---

frontend/src/component/application/ApplicationOverview.tsx

Success mode:
Warning mode:
Also: extracting components for cleanup

feat: warning mode app env styling

---

src/lib/openapi/spec/applications-query-parameters.ts
src/lib/openapi/spec/applications-schema.ts
src/lib/routes/admin-api/metrics.ts

* Enhancing existing request schema to support query parameters
* Adding total field currently reflecting all features returned (will need to change after pagination)
* Making fields in response schema required (not sure why they were optional before)
Next PRs:
* generate orval types
* switch frontend to use the query params

feat: schema for paginated applications

---

frontend/src/component/application/ApplicationList/PaginatedApplicationList.tsx
frontend/src/component/strategies/StrategyView/StrategyDetails/StrategyDetails.tsx
frontend/src/hooks/api/getters/useApplications/useApplications.ts
frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts
frontend/src/hooks/api/getters/useProjectApplications/useProjectApplications.ts
frontend/src/hooks/useClearSWRCache.ts

* passing query params to applications query
* reading total from the orval schema
* clear swr hook extracted and reused (applications, project applications and feature search)
* disabled sorting on one column
* hiding header name for icon
Next PRs:
* after backend is merged switch the old page to this one
* add tests for the entire page
* consider creating a reusable hook for paginated data

feat: paginated hook for applications list

---

frontend/src/component/application/ApplicationList/PaginatedApplicationList.test.tsx
frontend/src/component/application/ApplicationList/PaginatedApplicationList.tsx

Testing rendering of the applications list

test: applications list ui

---

frontend/src/component/project/ProjectApplications/ProjectApplications.test.tsx

Project applications table test
Simulating similar scenario to the one shown here (but with different data):

test: project applications table

---

frontend/src/component/strategies/StrategyView/StrategyDetails/StrategyDetails.tsx

Info when strategy in application usage exceeds 1000. When apps < 1000 then we don't show this info.

feat: capped at limit strategy in application usage

---

frontend/src/component/application/ApplicationOverview.tsx
frontend/src/component/common/Table/cells/StringArrayCell.tsx
frontend/src/hooks/api/getters/useApplicationOverview/useApplicationOverview.ts

Connected to real backend. It revels some data issues that we need to fix. 
During loading we show only the app name box.

feat: connect application envs to backend

---

frontend/src/component/application/ApplicationOverview.test.tsx
frontend/src/component/application/ApplicationOverview.tsx

Testing this part:
DOM improvements:
* added missing keys
* wrapped tr in tbody

refactor: application overview dom improvements and tests

---

frontend/src/component/application/ApplicationList/PaginatedApplicationList.tsx

Show total applications, not current page rows count.

fix: show total applications

---

frontend/src/component/application/ApplicationList/PaginatedApplicationList.tsx
frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/LineChart/ChartTooltip/ChartTooltip.tsx
frontend/src/component/executiveDashboard/LineChart/LineChartComponent.tsx
frontend/src/component/executiveDashboard/ProjectHealthChart/ProjectHealthChart.tsx

Initial refactoring for custom tooltips

Dashboard custom tooltips

---

frontend/src/component/project/ProjectApplications/ProjectApplications.tsx
frontend/src/hooks/api/getters/useApplications/useApplications.ts
frontend/src/hooks/api/getters/usePaginatedData/usePaginatedData.test.tsx
frontend/src/hooks/api/getters/usePaginatedData/usePaginatedData.ts
frontend/src/hooks/api/getters/useProjectApplications/useProjectApplications.ts

Extracted pagination to a common hook so that user code doesn't have to remember:
* to pass query params
* to clear the SWR cache
* to propagate total and data separately
This hook is now used by project applications and applications.
There's still useFeatureSearch that hasn't been migrated since it adds some total caching. It can be done separately by creating a new hook that composes the pagination hook with a caching behavior.

refactor: paginated data hook

---

src/lib/db/client-applications-store.ts
src/lib/openapi/spec/application-overview-issues-schema.ts
src/lib/openapi/spec/application-overview-schema.test.ts
src/lib/openapi/spec/application-overview-schema.ts
src/test/e2e/api/admin/applications.e2e.test.ts

This PR adds a property issues to application schema, and also adds all the missing features that have been reported by SDK, but do not exist in Unleash.

feat: application missing features backend

---

src/lib/db/client-applications-store.ts
src/test/e2e/api/admin/applications.e2e.test.ts

Now also showing missing strategies, that SDK sends, but do not exist in Unleash.

feat: application missing strategies

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/hooks/useDefaultColumnVisibility.ts

feat: set default env columns in project overview to 3

---

src/lib/db/client-instance-store.ts
src/lib/features/metrics/instance/instance-service.ts
src/lib/openapi/index.ts
src/lib/openapi/spec/application-environment-instance-schemas.ts
src/lib/openapi/spec/application-environment-instances-schema.ts
src/lib/openapi/spec/index.ts
src/lib/routes/admin-api/metrics.ts
src/lib/types/stores/client-instance-store.ts
src/test/e2e/api/admin/applications.e2e.test.ts
src/test/fixtures/fake-client-instance-store.ts

App env instances API
Decisions:
* currently no sorting other than by last seen
* currently limiting results to 1000 (no pagination)
* instead of returning a list I added top level instances field so that if we decide to add pagination we can add a total field to the root level object
* separate PR should move this code to feature oriented architecture
* added missing type for path params in the applications overview

feat: app env instances api

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/Gauge/Gauge.tsx
frontend/src/component/executiveDashboard/HealthStats/HealthStats.tsx
frontend/src/component/executiveDashboard/ProjectSelect/ProjectSelect.tsx
frontend/src/component/executiveDashboard/UserStats/UserStats.tsx

- style for headers in Insights dashboard and project selector
- fixed React element key issue in gauge chart
- fixed React attribute issue in Health stats
- active/inactive user stats from backend

Insights UI

---

frontend/src/component/application/ConnectedInstances/ConnectedInstances.tsx
frontend/src/component/application/ConnectedInstances/useConnectedInstancesTable.tsx
frontend/src/hooks/api/getters/useConnectedInstances/useConnectedInstances.ts

* fetching envs from the app overview (previous screen should already load those, for direct URL access we'll load them from scratch)
* fetching instances from the new API
* removed custom CSS and using toggle button group instead
* fixed table header by removing the owl operator on the container
* changed sorting by last seen date desc
Next PRs:
* add tests
* extract custom hook hiding low level details
* generate orval types and replace manually written API type

feat: connected instance ui api integration

---

frontend/src/component/application/ApplicationIssues/ApplicationIssues.test.tsx
frontend/src/component/application/ApplicationIssues/ApplicationIssues.tsx
frontend/src/component/application/ApplicationList/ApplicationList.tsx
frontend/src/component/application/ApplicationList/ApplicationUsageCell/ApplicationUsageCell.tsx
frontend/src/component/application/ApplicationList/PaginatedApplicationList.test.tsx
frontend/src/component/application/ApplicationList/PaginatedApplicationList.tsx
frontend/src/component/application/ApplicationOverview.test.tsx
frontend/src/component/application/ApplicationOverview.tsx
frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/feedbackNew/FeedbackComponent.tsx
frontend/src/component/feedbackNew/FeedbackList.tsx
frontend/src/component/project/ProjectApplications/ProjectApplications.test.tsx
frontend/src/component/project/ProjectApplications/ProjectApplications.tsx
frontend/src/hooks/api/getters/useApplicationOverview/useApplicationOverview.ts

feat: application issues

---

frontend/src/component/application/Application.tsx
frontend/src/component/application/ApplicationChart.tsx
frontend/src/component/application/ApplicationIssues/ApplicationIssues.tsx
frontend/src/component/application/ApplicationOverview.tsx

feat: projects using this application

---

frontend/src/component/executiveDashboard/DashboardHeader/DashboardHeader.tsx
frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/hooks/useSubmittedFeedback.ts

feat: insights feedback

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

Adds a flag for SCIM so we can build incrementally without breaking other things

chore: add a flag for scim

---

frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.test.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.test.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/executiveDashboard/MetricsSummaryChart/MetricsSummaryChart.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.test.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsCard.test.tsx
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestProcessHelp/ChangeRequestProcessHelp.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

chore: remove scheduledConfigurationChanges flag

---

frontend/src/component/application/ApplicationList/PaginatedApplicationList.tsx

fix: application list padding

---

frontend/src/component/application/ConnectedInstances/ConnectedInstances.test.tsx
frontend/src/component/application/ConnectedInstances/ConnectedInstances.tsx
frontend/src/hooks/api/getters/useConnectedInstances/useConnectedInstances.ts
src/lib/routes/admin-api/metrics.ts
src/test/e2e/api/admin/applications.e2e.test.ts

When switching tabs for envs we should update query params. Also query params should allow to go directly from apps overview to the instance env. 
Updated backend API to have /environment/:envName that matches other APIs

feat: connected instances support query param for env

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ChangeOverwriteWarning/ChangeOverwriteWarning.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestProcessHelp/ChangeRequestProcessHelp.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

chore: remove changeRequestConflictHandling flag

---

frontend/src/component/application/ApplicationChart.tsx
frontend/src/component/common/HelpIcon/HelpIcon.tsx

Info about instances stored for 2 days
I had to change the help icon to allow for size adjustments (@nunogois FYI)

feat: info icon instances for 2 days

---

frontend/src/component/application/ApplicationChart.tsx
frontend/src/component/common/HelpIcon/HelpIcon.tsx

Information tooltip instances

---

frontend/src/component/application/ConnectedInstances/ConnectedInstances.tsx
frontend/src/component/application/ConnectedInstances/useConnectedInstancesTable.tsx

Last seen for instances should respect the timezone. Previously we were removing timezone information.

fix: last seen instance with timezone

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx

fix: break on words not on all

---

frontend/src/component/application/Application.tsx

- remove application icon
- Update font for created text
- change "Delete" button into a trash can button

feat: new application header design

---

src/migrations/20240229093231-drop-fk-and-cascade-in-trends.js

Relaxing trends constraints so that historical project insights don't disappear after project deletion.

fix: relax trends tables constraints

---

frontend/src/component/application/ApplicationIssues/ApplicationIssues.tsx
frontend/src/component/application/ApplicationOverview.test.tsx

feat: add creation buttons to application features and strategies

---

frontend/src/component/common/PermissionButton/PermissionButton.tsx
frontend/src/component/segments/SegmentTable/SegmentTable.tsx

Fixes a bad link which leads to editing a global segment from project settings mimicking https://github.com/Unleash/unleash/blob/67928209eff0c00c22919007b860de5c3d0119e9/frontend/src/component/segments/EditSegmentButton/EditSegmentButton.tsx#L22-L28

fix: bad segment edit link

---

frontend/src/component/application/ApplicationChart.tsx
frontend/src/component/application/ApplicationIssues/ApplicationIssues.test.tsx
frontend/src/component/application/ApplicationIssues/ApplicationIssues.tsx
frontend/src/openapi/models/applicationOverviewEnvironmentSchema.ts
frontend/src/openapi/models/applicationOverviewIssuesSchemaType.ts
src/lib/features/metrics/instance/findOutdatedSdks.ts

feat: outdated SDKs UI

---

frontend/src/component/admin/users/LinkField/LinkField.tsx

Add ability to reuse "copy link" dialogue in other places

refactor: improve link field customizability

---

src/lib/features/export-import-toggles/createExportImportService.ts
src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/segment/fake-segment-read-model.ts
src/lib/features/segment/segment-read-model-type.ts
src/lib/features/segment/segment-read-model.ts

Extracted segment read model based on the usage in export-import-service.
I found that we don't need usage information in most of the code and it was the most complex part of the query.
Next PR:
* enterprise import change
* proxy-repository
* playground
* client feature toggles

refactor: segment read model used in export-import

---

frontend/src/component/menu/Header/Header.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts

feat: add menu item for insights

---

frontend/src/component/executiveDashboard/componentsChart/MetricsSummaryChart/MetricsSummaryChart.tsx
frontend/src/component/executiveDashboard/hooks/usePlaceholderData.ts

feat(insights): placeholder for empty metrics

---

src/migrations/20240304160659-add-environment-type-trends.js
src/migrations/20240305121426-add-created-at-environment-type-trends.js

Add created_at to environment_type_trends table for easy sorting

Fix: add created at to environment type trends

---

src/lib/db/index.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts
src/lib/features/instance-stats/createInstanceStatsService.ts
src/lib/features/instance-stats/instance-stats-service.ts
src/lib/features/segment/admin-segment.e2e.test.ts
src/lib/features/segment/client-segment.e2e.test.ts
src/lib/features/segment/createSegmentService.ts
src/lib/features/segment/segment-controller.ts
src/lib/features/segment/segment-service-interface.ts
src/lib/features/segment/segment-service.ts
src/lib/features/segment/segment-store-type.ts
src/lib/features/segment/segment-store.test.ts
src/lib/features/segment/segment-store.ts
src/lib/internals.ts
src/lib/services/feature-service-potentially-stale.test.ts
src/lib/services/index.ts
src/lib/services/state-service.ts
src/lib/types/services.ts
src/lib/types/stores.ts
src/test/e2e/api/admin/segment.e2e.test.ts
src/test/fixtures/fake-segment-store.ts

Finished segment migration to feature oriented architecture. Will need to change the enteprise repo with breaking changes.
Manually dragged store and service for segments into the feature directory. All other directories are auto updated.

refactor: segment in feature oriented architecture

---

src/lib/create-config.ts

Some changes to fix compiler errors in create-config

chore: remove compiler warnings from create-config

---

src/lib/util/db-lock.ts

We should not try to release the migration lock if where unable to acquire it. By trying to close it when we have not successfully connected to the database we end up hanging for a while before the process is eventually killed. 
I did not add a better error-message, as Unleash now gives a better error stack and crashes immediate if you start without a database password. We should still consider if you need to specify db credentials or not. Technically it is possible to have a postgres without a password (but it is likely not common).
Closes: #6408

fix: only release migration lock if acquired

---

frontend/src/component/project/Project/ProjectSettings/Settings/DeleteProject.tsx

https://linear.app/unleash/issue/2-1831/what-happens-with-automated-actions-if-the-project-is-archived
Adds an actions-related warning to the project deletion.

chore: add actions warning to delete project

---

src/lib/features/segment/fake-segment-read-model.ts
src/lib/proxy/client-feature-toggle-read-model-type.ts
src/lib/proxy/client-feature-toggle-read-model.ts
src/lib/proxy/fake-client-feature-toggle-read-model.ts
src/lib/proxy/frontend-api-repository.ts
src/lib/proxy/global-frontend-api-cache.test.ts
src/lib/proxy/global-frontend-api-cache.ts

* renamed to fronted api cache
* added comprehensive test suite
* added state transitions to make it testable and easier to use for production code

feat: stabilize global frontend api cache

---

src/lib/db/crud/crud-store.ts
src/lib/db/crud/default-mappings.ts

Small fix to make mapper function partial as it should be

fix: mapper function should be partial

---

website/docs/using-unleash/deploy/upgrading-unleash.md

Upgrading to 5.7 and above from earlier versions is a little problematic. Let's document it.

docs: add note about upgrading to version 5.7 and above

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsForm.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsActionItem.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsFormStepActions.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepSource/ProjectActionsFormStepSource.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/useProjectActionsForm.ts
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsModal.tsx
frontend/src/hooks/api/getters/useServiceAccountAccessMatrix/useServiceAccountAccessMatrix.ts
src/lib/util/constants/actions.ts

https://linear.app/unleash/issue/2-2022/improve-actions-validation
Improves our current actions form validation. 
Empty actions are now ignored on the payload and we get errors in actions where any of the required fields are empty.
Also refactored our current actions into a constant map that can be shared across frontend and backend.

fix: add actions validation

---

src/lib/proxy/proxy-controller.ts
src/lib/proxy/proxy-service.test.ts
src/lib/proxy/proxy-service.ts
src/lib/routes/admin-api/api-token.ts
src/lib/routes/index.ts
src/lib/services/index.ts
src/lib/types/services.ts

Proxy/Frontend API in one directory to get feature-oriented architecture. Move service and controller. Next PR will move it into feature directory.

refactor: proxy/frontend api in feature oriented architecture

---

frontend/src/component/executiveDashboard/componentsChart/MetricsSummaryChart/MetricsChartTooltip/MetricsChartTooltip.tsx
frontend/src/component/executiveDashboard/componentsChart/MetricsSummaryChart/MetricsSummaryChart.tsx

Changes the xAxis from 'week' to 'date' (timeline fix)
Replace null values with 0

fix: chart xAxis and null values

---

src/lib/features/feature-toggle/configuration-revision-service.ts
src/lib/proxy/createProxyService.ts
src/lib/services/index.ts

Configuration revision service is a singleton. Proxy observes revision updates and it always has to depend on the same instance passed around

fix: Configuration revision service singleton

---

src/lib/features/frontend-api/frontend-api-service.e2e.test.ts

Service test that compares frontend API implementations. We check returned features and events emitted.
I tried to cover interesting cases with multiple projects and multiple environments.

test: compare frontend api implementations

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/middleware/response-time-metrics.test.ts
src/lib/middleware/response-time-metrics.ts
src/lib/routes/admin-api/index.ts
src/lib/routes/controller.ts
src/lib/routes/index.ts
src/lib/types/experimental.ts
src/test/e2e/api/client/metrics.e2e.test.ts
src/test/e2e/helpers/test-helper.ts

Some of our metrics are not labeled correctly, one example is `<base-path>/api/frontend/client/metrics` is labeled as `/client/metrics`. We can see that in internal-backstage/prometheus:
This issue affects all endpoints that fail to validate the request body. Also, endpoints that are rejected by the authorization-middleware or the api-token-middleware are reported as `(hidden)`.
To gain more insights on our api usage but being protective of metrics cardinality we're prefixing `(hidden)` with some well known base urls: https://github.com/Unleash/unleash/pull/6400/files#diff-1ed998ca46ffc97c9c0d5d400bfd982dbffdb3004b78a230a8a38e7644eee9b6R17-R33
Make an invalid call to metrics (e.g. stop set to null), then check /internal-backstage/prometheus and find the 400 error. Expected to be at …

fix: path metric labels (#6400)

---

src/lib/features/frontend-api/frontend-api-controller.ts

Print projects and environment when discrepancies are found.

feat: better logging for old and new frontend api differences

---

website/docs/reference/project-collaboration-mode.md

add custom root roles to docs on private projects

---

frontend/src/component/executiveDashboard/components/LineChart/createChartOptions.ts

Switch charts to stretch X-axis to the full width

fix(insights): chart start date

---

src/lib/util/flattenPayload.test.ts
src/lib/util/flattenPayload.ts

https://linear.app/unleash/issue/2-2029/support-filtering-on-nested-properties
This will allow us to support and suggest payload subproperties in the action filters.

chore: flatten payload util

---

src/lib/db/client-applications-store.ts
src/lib/features/frontend-api/frontend-api-controller.ts

fix: fix frontend api timings

---

src/lib/db/client-instance-store.ts
src/lib/features/metrics/instance/findOutdatedSdks.ts
src/lib/features/metrics/instance/instance-service.ts
src/lib/openapi/spec/index.ts
src/lib/openapi/spec/outdated-sdks-schema.ts
src/lib/routes/admin-api/metrics.ts
src/lib/types/stores/client-instance-store.ts
src/test/e2e/api/admin/applications.e2e.test.ts
src/test/fixtures/fake-client-instance-store.ts

API for returning outdated SDKs and apps using those SDKs

feat: outdated sdks api

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsActionItem.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsActionParameter/ProjectActionsActionParameterAutocomplete.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsFormStepActions.tsx

https://linear.app/unleash/issue/2-2041/improve-action-parameters-ui
Improves the UI of action parameters, implementing a new `ProjectActionsActionParameterAutocomplete` component that allows search.

chore: improve action parameters UI

---

frontend/src/component/application/ApplicationOverview.tsx
frontend/src/component/banners/Banner/BannerDialog/BannerDialog.tsx
frontend/src/component/banners/OutdatedSdksBanner/OutdatedSdksBanner.test.tsx
src/server-dev.ts

Links in banner modal should close the modal on navigation.
https://github.com/Unleash/unleash/assets/1394682/e4ef03c7-679b-4465-a552-433eb4cc5373
Details:
* I use event propagation and capture the click on the ancestor
* I use event target node name to check if it's a link 
* this will work with markdown links so people can put links to the Unleash instance itself

feat: clickable banner modal links

---

frontend/src/component/application/ApplicationChart.tsx
frontend/src/component/application/ApplicationIssues/ApplicationIssues.test.tsx
frontend/src/component/application/ApplicationIssues/ApplicationIssues.tsx
frontend/src/component/executiveDashboard/components/DashboardHeader/DashboardHeader.tsx

Previously if multiple environments had same missing SDK, it was counted multiple times. Now it will take only unique.

fix: now issue count under application will show correctly

---

frontend/src/hooks/api/getters/useOutdatedSdks/useOutdatedSdks.ts

Adding base path to each API call for outdated sdks

fix: format api path for outdated sdks

---

src/lib/features/metrics/instance/findOutdatedSdks.test.ts
src/lib/features/metrics/instance/findOutdatedSdks.ts
website/docs/contributing/ADRs/back-end/frontend-api-design.md

chore: update outdated sdks list

---

src/lib/features/metrics/instance/findOutdatedSdks.test.ts
src/lib/features/metrics/instance/findOutdatedSdks.ts

fix: handle sdk versions with nulls

---

frontend/src/component/common/BreadcrumbNav/BreadcrumbNav.test.tsx
frontend/src/component/common/BreadcrumbNav/BreadcrumbNav.tsx

Gracefully handle breadcrumbs with URL encoded spaces

fix: uri decode breadcrumbs

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsActionItem.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsActionSelect.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsFormStepActions.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/useActionDefinitions.ts
src/lib/util/constants/action-parameters.ts
src/lib/util/constants/actions.ts

https://linear.app/unleash/issue/2-2046/implement-dynamic-action-parameters
Implements dynamic action parameters.
Also improves the action dropdown to better prepare for future actions.

chore: dynamic action parameters

---

frontend/src/component/application/ApplicationOverview.test.tsx
frontend/src/component/application/ApplicationOverview.tsx

Added loading indicator so that we don't show empty box during load

feat: application overview loading state

---

src/lib/features/frontend-api/frontend-api-controller.ts
src/server-dev.ts

Allow to return new frontend api path without touching old frontend api code. This way we can perf tests new and old path separately.

feat: separate new frontend api path for perf measurements

---

src/lib/features/metrics/instance/findOutdatedSdks.test.ts
src/lib/features/metrics/instance/findOutdatedSdks.ts

fix: outdated sdk version handles non semver versions

---

src/lib/features/metrics/instance/findOutdatedSdks.ts

refactor: make outdated sdk finding simpler

---

frontend/src/component/project/Project/Project.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Setup feature flag for the new refactoring of the project overview page

feat: setup ff

---

frontend/src/component/project/Project/ProjectInsights/ProjectHealthChart.test.tsx
frontend/src/component/project/Project/ProjectInsights/ProjectHealthChart.tsx

A circle chart for active, stale and potentially stale flags.
Important points:
* uses svg circles
* adds artificial gap between active and stale
* potentially stale flags are subset of active
Next PR will add a legend and the whole tile.

feat: project health chart

---

frontend/src/component/project/Project/ProjectInsights/ChangeRequests/ChangeRequests.tsx
frontend/src/component/project/Project/ProjectInsights/LeadTimeForChanges/LeadTimeForChanges.tsx
frontend/src/component/project/Project/ProjectInsights/ProjectInsights.tsx

Basic change request widget
Interesting points:
* two clickable areas
* responsive flex that wraps on smaller screens
Next PR:
* info for non enterprise UI version
Eventually:
* connect to real data when available

feat: change request insights widget

---

frontend/src/component/project/Project/ProjectInsights/ChangeRequests/ChangeRequests.test.tsx
frontend/src/component/project/Project/ProjectInsights/ChangeRequests/ChangeRequests.tsx
frontend/src/component/project/Project/ProjectInsights/ProjectHealth/ProjectHealthChart.tsx

feat: change request insights for oss and pro

---

frontend/src/component/project/Project/ProjectInsights/ProjectHealth/ProjectHealth.tsx
src/lib/features/project/createProjectService.ts
src/lib/features/project/project-controller.ts
src/lib/features/project/project-service.ts
src/lib/features/project/projects.e2e.test.ts

Exposing stats, health and flag types in project insights. I'm considering building a separate read model in a separate PR.

feat: expose stats, health and flag types insights

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/hooks/useDashboardData.ts

Fix hook usage react error (console)

chore: fix react errors

---

frontend/src/component/executiveDashboard/Charts.tsx
frontend/src/component/executiveDashboard/chart-info.ts

Centralises and improves the chart title and tooltip descriptions.  
Closes
[1-2199](https://linear.app/unleash/issue/1-2199/verify-tooltip-texts-and-explanations-are-clear-enough)
[1-2200](https://linear.app/unleash/issue/1-2200/verify-chart-naming)

chore: verify chart names and tooltips

---

src/lib/features/project-insights/createProjectInsightsService.ts
src/lib/features/project-insights/fake-project-insights-read-model.ts
src/lib/features/project-insights/project-insights-read-model-type.ts
src/lib/features/project-insights/project-insights-read-model.ts
src/lib/features/project-insights/project-insights-service.ts
src/lib/features/project-insights/projects-insights.e2e.test.ts
src/lib/features/project/project-service.ts

* introducing read model for project insights
* adding one method with change request counts
* removing unused code in project service
Next PR:
* add more tests with non zero values
* consider moving some of the code to the new store instead of coupling project insights service to stores and services from other subdomains

feat: read change requests for insights

---

frontend/src/component/project/Project/ProjectInsights/ProjectMembers/ProjectMembers.test.tsx
frontend/src/component/project/Project/ProjectInsights/ProjectMembers/ProjectMembers.tsx
frontend/src/hooks/api/getters/useProjectInsights/useProjectInsights.ts
frontend/src/openapi/models/projectInsightsSchemaMembers.ts
src/lib/features/project-insights/project-insights-service.ts
src/lib/openapi/spec/project-insights-schema.ts

feat: remove active/inactive members

---

src/lib/features/project-insights/createProjectInsightsService.ts
src/lib/features/project-insights/project-insights-service.ts
src/lib/features/project-insights/projects-insights.e2e.test.ts

Project insights service refactor to remove dependency on the project service and remove unused code.

refactor: reduce project insights coupling

---

src/lib/features/project-insights/project-insights-read-model.test.ts
src/lib/features/project-insights/project-insights-read-model.ts

Integration test for the project insights SQL read model

test: project insights read model test

---

frontend/src/hooks/api/getters/useInsights/useInsights.ts

What is says on the tin
Closes #[1-2217](https://linear.app/unleash/issue/1-2217/point-fe-to-new-endpoint)

chore: call new insights endpoint

---

src/lib/features/feature-toggle/fakes/fake-feature-toggle-store.ts
src/lib/features/project-insights/createProjectInsightsService.ts
src/lib/features/project-insights/fake-project-insights-read-model.ts
src/lib/features/project-insights/project-insights-service.e2e.test.ts
src/lib/features/project-insights/project-insights-service.test.ts
src/lib/features/project-insights/project-insights-service.ts
src/lib/features/project/project-controller.ts
src/lib/features/project/project-service.e2e.test.ts
src/lib/features/project/project-service.ts
src/lib/services/index.ts
src/test/fixtures/fake-project-stats-store.ts
src/test/fixtures/fake-project-store.ts

Testing project insights service test:
* e2e service test has code copied from the project service test for dora metrics
* service test uses fake dependencies and checks if the simple values are aggregated correctly

test: project insights service test

---

frontend/src/component/project/Project/ProjectOverviewChangeRequests.tsx

Project overview change requests UI widget.
Next PR:
* expose this data from backend (either overview API or a new resource)

feat: project overview change requests

---

frontend/src/component/project/Project/Project.tsx

feat: beta indicator for project insights tab

---

src/lib/addons/webhook-definition.ts
src/lib/addons/webhook.ts

You might want to include entire event, but as a different field.

feat(integrations): ability to add stringified event

---

frontend/src/component/common/Table/cells/FeatureSeenCell/FeatureEnvironmentSeenCell.tsx
frontend/src/component/common/Table/cells/FeatureSeenCell/LastSeenProgress.tsx
frontend/src/component/common/Table/cells/FeatureSeenCell/LastSeenProgress/LastSeenProgress.test.tsx
frontend/src/component/common/Table/cells/FeatureSeenCell/LastSeenProgress/LastSeenProgress.tsx
frontend/src/component/common/Table/cells/FeatureSeenCell/LastSeenTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureEnvironmentSeen/FeatureEnvironmentSeen.tsx
frontend/src/interfaces/featureToggle.ts

feat: last usage metrics in project table

---

frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.test.tsx
frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.tsx
frontend/src/openapi/models/featureSearchResponseSchema.ts

This PR builds a complete feature overview cell.
Details:
* handles all icon types (moved from previous component)
* handles feature type badges
* handles description with long length (capping above 40 and providing tooltip)
* handles 3 listed keys and the rest grouping on hover
* handles keyword highlighting in feature name and description

feat: feature overview cell

---

frontend/src/component/common/Table/PaginatedTable/PaginatedTable.tsx
frontend/src/component/common/Table/cells/FavoriteIconCell/FavoriteIconCell.tsx

Bringing back the spacing that was removed to make columns more compact.
Before
After

fix: adjust table spacing

---

frontend/src/component/App.tsx
frontend/src/component/banners/OutdatedSdksBanner/OutdatedSdksBanner.tsx

Moving outdated sdks check one level up so that we avoid making backend API calls when the flag is disabled.

fix: move outdated sdks check up

---

frontend/src/component/App.tsx

fix: remove duplicate banner

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

Brought up by https://github.com/Unleash/unleash/issues/6738

refactor: fix return type for getFeatureOverviewData

---

website/docs/reference/feature-flag-naming-patterns.mdx

found a small typo and fixed it.

fixed typo

---

frontend/src/component/feature/Dependencies/AddDependencyDialogue.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.test.tsx

test: manage variant dependency UI

---

frontend/src/hooks/useLoading.ts

Reviving the ref dependency in the useLoading hook. It fixes incorrect loading indicators on the project overview flags list.
Also added selector dependency so that exhaustive check is satisfied.

fix: loading state

---

website/docs/reference/dependent-features.md

Documenting variant dependencies.

docs: variant dependencies

---

frontend/src/component/project/Project/ProjectOverview.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

New project overview refactor feedback is behind a flag now

chore: project overview refactor feedback behind a flag

---

src/lib/features/metrics/instance/instance-service.test.ts
src/lib/features/metrics/instance/instance-service.ts
src/lib/features/private-project/fakePrivateProjectChecker.ts
src/lib/features/private-project/privateProjectChecker.test.ts
src/lib/features/private-project/privateProjectChecker.ts
src/lib/features/private-project/privateProjectCheckerType.ts
src/lib/routes/admin-api/metrics.ts

feat: private projects in application overview

---

src/test/fixtures/fake-project-store.ts

Mock implements function in fake project store

chore: add default implementation to fake methods

---

src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts

Found that client metrics are only emitted from the eventBus not the eventStore. Adjusting service code accordingly.
Improved e2e test to show some stages of the lifecycle.

feat: feature lifecycle metrics from event bus

---

frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

This PR adds the flag for the improved project creation flag to Unleash.

chore: add flag for improved project creation

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx

* Making labels similar to created at and dependency labels (lighter color)
* moving values to the right
* making header a bit smaller

feat: improve feature overview styling

---

frontend/src/component/feature/FeatureView/FeatureEnvironmentSeen/FeatureEnvironmentSeen.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleStageIcon.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx

feat: live and pre-live stages UI

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleStageIcon.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/LifecycleStage.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx

feat: completed stage button

---

frontend/src/component/project/Project/ProjectOverview.tsx

Removing the time based feedback

chore: clean up feedback component

---

website/docusaurus.config.js

Introduces a few more links to the global menu.

docs: adjust global menu with more links

---

src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts

When lifecycle captures metrics for non-existent features those should be ignored.

fix: ignore metrics for non-existent features

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
frontend/src/hooks/api/actions/useFeatureLifecycleApi/useFeatureLifecycleApi.ts

feat: rever to live connected to backend

---

frontend/src/component/project/Project/CreateProject/NewProjectForm.tsx

Imports and uses the same project icon used on the project cards. Also aligns the header better and makes the text lighter.

chore: add project icon to new form

---

src/lib/addons/feature-event-formatter-md.ts
src/lib/addons/webhook-definition.ts
src/lib/addons/webhook.ts
website/docs/reference/integrations/webhook.md

Now feature completed event can be used with webhook.

feat: add completed event as webhook event

---

src/lib/features/feature-search/feature-search-store.ts

Avoid duplicate column names in search query
Fixes: https://github.com/Unleash/unleash/issues/6988

fix: duplicate column name in search query

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts
src/lib/types/model.ts

We want to start showing same donut that we do show in project page. This is setting it up for UI.

feat: start exposing environment metrics from feature endpoint

---

frontend/src/component/project/Project/CreateProject/CreateProject.tsx
frontend/src/component/project/Project/CreateProject/NewProjectForm.tsx
frontend/src/component/project/Project/CreateProject/SelectionButton.tsx

This PR updates the documentation text in the new project form to show the documentation relating to the specific thing you're configuring.

feat: show documentation relating to the specific thing your configuring in the new project form

---

src/migrations/20240506141345-lifecycle-initial-stage.js

We are getting questions from engineers, why I do not see lifecycle. The same will happen with our customers. Now customers will see lifecycle component unified across features.

feat: create initial stages for features

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
frontend/src/interfaces/featureToggle.ts

feat: pass metrics to feature component

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/FeatureToggleCell/FeatureToggleCell.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx

Performance issues before: we were loading placeholder data (page size * number of environments) with real switch toggles that are doing full permission checks and contain many DOM elements to render. The placeholder data was hidden behind a loading indicator. As a result when clicking on the sorting column there was a significant delay.
After this optimization we're rendering simple divs hidden behind a loading indicator.
https://github.com/Unleash/unleash/assets/1394682/ee42e22a-efe9-4e96-bef5-f302968cf76a

fix: optimize table placeholder loading

---

src/lib/features/feature-lifecycle/fake-feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store-type.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/features/instance-stats/createInstanceStatsService.ts
src/lib/features/instance-stats/instance-stats-service.test.ts
src/lib/features/instance-stats/instance-stats-service.ts
src/lib/metrics.test.ts
src/lib/metrics.ts
src/lib/routes/admin-api/instance-admin.ts
src/lib/types/model.ts

Introduce a new concept. Duration in stage.
Also add it into prometheus metric.

feat: duration in stage, add feature lifecycle prometheus metrics

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/populateCurrentStage.test.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/populateCurrentStage.ts

Completed stage lists traffic from all environments not just production. Also adjusted revert to live placement and explanation.

feat: completed stage lists all environments

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx

feat: lifecycle is now navigatable by tab

---

frontend/src/hooks/api/actions/useFeatureLifecycleApi/useFeatureLifecycleApi.ts
src/lib/features/feature-lifecycle/feature-lifecycle-controller.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts
src/lib/openapi/spec/feature-lifecycle-completed-schema.test.ts
src/lib/openapi/spec/feature-lifecycle-completed-schema.ts
src/lib/openapi/spec/index.ts

1. Added new schema and tests
2. Controller also accepts the data
3. Also sending fake data from frontend currently
Next steps, implement service/store layer and frontend

feat: feature lifecycle completed schema

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycle.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx

Extracted feature lifecycle component with all the hooks so that we can share it easily with the search table.

refactor: extract feature lifecycle component

---

src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/metrics.test.ts

getAll was not properly tested, added test and fixed query. Now metrics should come up.

fix: fix prometheus metrics for lifecycle

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycle.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/populateCurrentStage.test.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/populateCurrentStage.ts

When pulling pre-live env usage we should also include prod SDK traffic for envs that are disabled

feat: pre-live should include disabled prod

---

src/lib/features/feature-lifecycle/calculate-stage-durations.test.ts
src/lib/features/feature-lifecycle/calculate-stage-durations.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/instance-stats/instance-stats-service.ts
src/lib/metrics.ts
src/lib/routes/admin-api/instance-admin.ts
src/lib/types/model.ts
src/lib/util/median.test.ts
src/lib/util/median.ts

When we pushed metrics per feature, it had too many datapoints and grafana could not handle it. Now I am taking median for a project.

feat: lifecycle prometheus metrics per project

---

website/docs/feature-flag-tutorials/python/implementing-feature-flags.md

Closes #
Adding the Python video tutorial to our docs for following along
https://youtu.be/-Rf0y2Gq8OA?si=udl3eIE9DdxQYGAY

docs: Add Python YouTube Video tutorial

---

frontend/src/component/common/Table/cells/FeatureSeenCell/FeatureEnvironmentSeenCell.tsx

fix: center last seen column

---

src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/types/events.ts

Now we post status and statusValue with webhook.

feat: webhook data for completed

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/MarkCompletedDialogue.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/hooks/useRowActions.tsx

1. Now completed modal works from project view
2. Changed text for modal
3. Now variant selection will only appear if there are any variants

fix: lifecycle improvements/fixes

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/MarkCompletedDialogue.tsx
frontend/src/hooks/usePlausibleTracker.ts

Track feature lifecycle completed event

feat: track complete event

---

frontend/src/component/common/Table/cells/FeatureSeenCell/FeatureEnvironmentSeenCell.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleStageIcon.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx

Lifecycle is a separate column from last seen.

feat: lifecycle column extracted

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycle.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/hooks/useDefaultColumnVisibility.ts
website/docs/reference/feature-lifecycle.md

* Uncomplete feature tracking
* adjusted wording in docs to emphasize feature, not environment lifecycle
* mentioned feature is beta in docs

feat: uncomplete tracking

---

src/lib/features/feature-lifecycle/fake-feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store-type.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts

When the application starts we run the backfill missing initial stage migration. This is the same one we had in the migrations but run from the code. It solves the issue for the newly created features after the migration and before the feature was enabled.

feat: backfill current stage on startup

---

website/docs/feature-flag-tutorials/java/implementing-feature-flags.md

Closes #
Adding our YouTube link: https://www.youtube.com/watch?v=Hq1g9QyPw14

Docs: Add Java YouTube Tutorial Video

---

frontend/src/component/project/Project/CreateProject/CreateProjectDialog/CreateProjectDialog.tsx

The loading state of the FormTemplate is causing the form glitch. This fixes it by removing the loading
Closes # [1-2362](https://linear.app/unleash/issue/1-2362/fix-visual-glitch-when-you-submit-the-form)
https://github.com/Unleash/unleash/assets/104830839/1782ca09-a8b4-4fd1-92c1-111843869b25

fix: loading is causing a glitch that changes the size of the dialog for a split second

---

frontend/src/component/project/Project/CreateProject/CreateProjectDialog/CreateProjectDialog.tsx

Prevends duplicate calls to api

fix: disable the create button when api call is made

---

website/docs/reference/feature-toggle-variants.md

Add documentation of feature flag variant types
Closes #7056

chore: update documentation for feature toggle variants

---

src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts

When we emit event with a state that we reached in a lifecycle a feature name should be included. This should remove flaky test.

fix: reached stage should emit feature name

---

package.json

chore: linter update

---

.github/workflows/publish-new-version.yaml
.github/workflows/update_version_for_version_checker.yml

Automate some of our manual release steps

chore: bring workflow changes from 5.12

---

.github/workflows/publish-new-version.yaml
.github/workflows/update_version_for_version_checker.yml

chore: update workflows

---

src/lib/db/client-instance-store.ts
src/lib/features/metrics/instance/instance-service.ts
src/lib/features/project/project-controller.ts
src/lib/types/stores/client-instance-store.ts
src/test/e2e/api/admin/applications.e2e.test.ts
src/test/fixtures/fake-client-instance-store.ts

This adds project level endpoint to catch outdated SDKs only for that project.

feat: outdated sdks project level

---

frontend/src/component/project/Project/Import/import/ImportStage.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/useProjectFeatureSearch.ts
frontend/src/component/project/Project/ProjectOverview.tsx

Refresh project after import. Extracted search hook so that it's easy to refresh in other places.
Replaces less elegant https://github.com/Unleash/unleash/pull/7081

fix: refresh project after import

---

frontend/src/component/banners/OutdatedSdksBanner/OutdatedSdksBanner.tsx
src/lib/services/access-service.ts

Fixing isAdmin method. It is not that critical, because that is mostly for system users not real usage.
Also fixing wording for outdated sdks.

fix: small improvements

---

frontend/src/component/admin/instance-admin/InstanceStats/InstanceStats.tsx
frontend/src/component/admin/instance-privacy/InstancePrivacy.tsx
frontend/src/component/archive/ArchiveTable/ArchiveTable.test.tsx
frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureActionCell.tsx
frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureReviveConfirm/ArchivedFeatureReviveConfirm.tsx
frontend/src/component/common/FeatureArchiveDialog/FeatureArchiveDialog.test.tsx
frontend/src/component/common/FeatureArchiveDialog/FeatureArchiveDialog.tsx
frontend/src/component/common/FeatureStaleDialog/FeatureStaleDialog.tsx
frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ProjectFeaturesBatchActions.test.tsx
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportExpiredCell/formatExpiredAt.ts
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportStatusCell/formatStatus.ts
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx
frontend/src/hooks/useSearch.test.tsx
frontend/src/interfaces/featureToggle.ts
frontend/src/interfaces/project.ts

Rename feature toggle to feature flag in the UI and code.
Starting with low hanging fruits.
Trying to keep these ~100 LoC.

chore: rename toggle to flag #1

---

src/lib/metrics.ts

It looks like failed prometheus metrics registration is breaking lifecycle listener. We want to find why it fails so adding a logger.

feat: add prometheus metrics error logging

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/metrics/client-metrics/metrics-service-v2.ts
src/lib/types/experimental.ts

feat: debug metrics flag

---

frontend/src/component/common/Input/Input.tsx
frontend/src/component/project/Project/CreateProject/NewProjectForm.tsx

Make sure that the main input fields have enough space between them and that their size is correct in both light and dark modes.

chore: update input field text sizes

---

frontend/cypress/integration/projects/access.spec.ts
src/lib/features/export-import-toggles/export-import-permissions.e2e.test.ts
src/migrations/20240523093355-toggle-to-flag-rename.js

Renaming also permissions with migration

feat: rename toggle to flag with db migration

---

website/docs/feature-flag-tutorials/dotnet/implementing-feature-flags-dotnet.md
website/docs/feature-flag-tutorials/java/implementing-feature-flags.md
website/docs/feature-flag-tutorials/java/spring-boot-examples.md
website/docs/feature-flag-tutorials/java/spring-boot-implementing-feature-flags.md
website/docs/feature-flag-tutorials/nextjs/implementing-feature-flags-nextjs.md
website/docs/feature-flag-tutorials/python/implementing-feature-flags.md
website/docs/feature-flag-tutorials/react/examples.md
website/docs/feature-flag-tutorials/react/implementing-feature-flags.md
website/docs/feature-flag-tutorials/ruby/implementing-feature-flags-ruby.md
website/docs/feature-flag-tutorials/ruby/ruby-examples.md
website/docs/feature-flag-tutorials/sveltekit/implementing-feature-flags-sveltekit.md
website/docs/quickstart.md

We are making a round of updates to change all references of "feature toggle" to "feature flag".
This is also under the assumption that "Create feature toggle" in the product UI will become "creature feature flag".
There are also formatting improvements to the docs included in this PR.
> Note: This does not include anchors and links for now.

docs: update quickstart and tutorials with flag reference

---

website/docs/feature-flag-tutorials/dotnet/implementing-feature-flags-dotnet.md
website/docs/feature-flag-tutorials/flutter/a-b-testing.md
website/docs/feature-flag-tutorials/java/implementing-feature-flags.md
website/docs/feature-flag-tutorials/java/spring-boot-implementing-feature-flags.md
website/docs/feature-flag-tutorials/python/examples.md
website/docs/feature-flag-tutorials/python/implementing-feature-flags.md
website/docs/feature-flag-tutorials/react/implementing-feature-flags.md
website/docs/feature-flag-tutorials/ruby/implementing-feature-flags-ruby.md

- update anchor link descriptions
- fix ordered lists across files
- formatting updates
Closes #

chore: update anchor toggle titles

---

README.md

Completing the docs updates to remove references of "feature toggle" to become "feature flag".
This does not include links.
Closes #

chore: remove toggle reference apart from existing links

---

website/docusaurus.config.js

We updated the website to include a new product page at https://www.getunleash.io/enterprise-feature-management-platform.  The only product links in the docs are no longer relevant.
Closes #

Update link to product section in Dos nav

---

frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx
frontend/src/component/layout/MainLayout/MainLayout.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx

misc UI improvements in the navigation sidebar. Screenshots and comments inline.

feat: UI tweak new sidebar

---

frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationList.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.test.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/ShowHide.tsx

Added tests for mode switching and navigation persistence (mode + expansion settings) in the local storage.

test: navigation sidebar

---

src/lib/routes/edge-api/index.ts

Removes /edge/metrics. This has been superseded by /api/client/metrics/bulk. Once this is merged, Unleash 6.0 will require Edge > 17.0.0. (We recommend at least v19.1.3)

task: Removed edge bulk metrics endpoint

---

frontend/src/component/project/Project/Project.tsx

feat: project insights out of beta

---

website/docs/how-to/how-to-import-export.md
website/docs/reference/api/legacy/unleash/admin/state.md

More removal notices for state service in docs

chore(docs): additional removal notices of state api/service

---

docker/package.json

If you still need passport/custom auth, you should use the community image https://github.com/Unleash/unleash-docker-community

chore: removed passport from docker package.json file

---

frontend/src/component/insights/InsightsCharts.tsx

Currently it was showing only users. Now showing 2.

fix: show 2 insights components to pro

---

frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationList.tsx
frontend/src/hooks/useCustomEvent.ts
frontend/src/hooks/useLastViewedProject.test.tsx
frontend/src/hooks/useLastViewedProject.ts

When you use this line in multiple places:
`const {lastViewed, setLastViewed} = useLastViewedProject();`
they are all synchronized and lastViewed is always kept in sync through the custom event emitted on document and values fetched from local storage.

feat: Synced last viewed projects

---

frontend/src/component/demo/DemoTopics/DemoTopics.tsx

Moving demo to the right so that it doesn't obscure the new navigation show/hide button

feat: move demo to the right

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationList.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.test.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx
frontend/src/hooks/useCustomEvent.ts
frontend/src/hooks/useLastViewedFlags.test.tsx
frontend/src/hooks/useLastViewedFlags.ts
frontend/src/hooks/useLastViewedProject.test.tsx
frontend/src/hooks/useLastViewedProject.ts

Shows recently used flags
Details:
when you visit a feature view you store it in the local storage. Up to 3 flags are stores. The change is propagated using custom event so that the sidebar can update automatically.

feat: Recent flags

---

src/lib/db/client-instance-store.ts

Joining might not always be the best solution. If a table contains too much data, and you later run sorting on top of it, it will be slow.
In this case, we will first reduce the instances table to a minimal version because instances usually share the same SDK versions. Only after that, we join.
Based on some customer data, we reduced query time from 3000ms to 60ms. However, this will vary based on the number of instances the customer has.

fix: increase performance of outdated SDK query

---

src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts
src/lib/features/metrics/client-metrics/metrics-service-v2.ts
src/lib/features/metrics/instance/metrics.ts
src/lib/metrics.test.ts
src/lib/metrics.ts

1. CLIENT_METRICS event will be emitted with new structure
2. CLIENT_METRICS event will be emitted from bulkMetrics endpoint

feat: now CLIENT_METRICS event will be emitted with new structure

---

frontend/src/component/demo/demo-topics.tsx

Select table links not recent flag links in demo steps. The selector is more specific now.

fix: demo steps should search the main table

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

When no flag is specified use new sidebar by default with an option to bring back the old one if needed.

feat: new sidebar by default for OSS

---

.github/workflows/dependency-review.yml

chore: change deny list to allow list

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyExecution/StrategyExecution.tsx
frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/StrategyList/StrategyItem/StrategyExecution/StrategyExecutionParameters/StrategyExecutionParameters.tsx

When someone chooses stickiness other than default SDK may not return expected results. Let's make it clear that non default strategy is being used.
Explain non default stickiness in strategy screen
Explain non default stickiness in playground results

feat: explain stickiness

---

.github/workflows/build.yaml
.github/workflows/build_frontend_prs.yml
.github/workflows/build_prs_jest_report.yaml
.github/workflows/dependency-review.yml
.github/workflows/docker_publish.yaml
.github/workflows/notify_enterprise.yaml
.github/workflows/publish-new-version.yaml
.github/workflows/release.yaml
.github/workflows/release_changelog.yml
.github/workflows/update_version_for_version_checker.yml
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/useShowDependentFeatures.ts

Check if project is provided because we don't want hooks making 404 requests during initial data load for the project.

fix: 5.12 remove 404 feature view

---

.github/workflows/publish-new-version.yaml
package.json

Based on https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows

chore: Inherit secrets for workflow calls

---

frontend/src/component/layout/MainLayout/NavigationSidebar/ListItems.tsx

Fix font and spacing in the last 3 links

fix: mobile menu font size

---

docker/package.json
docker/yarn.lock

Since this isn't inherited from our mother package, we needed to readd resolutions and overrides. I've just copied what we used to have here for now.

chore: readded resolutions for our docker package file

---

frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

Adds a feature flag + snapshot + ui flag for `commandBarUI`

chore: add a flag+ui flag for commandBarUI

---

biome.json
docker/yarn.lock
frontend/package.json
frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountsActionsCell/ServiceAccountsActionsCell.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestScheduledDialogs/ScheduleChangeRequestDialog.tsx
frontend/src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/ConstraintAccordionEditBody.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/ConstraintAccordionEditBody.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/PushVariantsButton/PermissionCheckboxMenuItem.tsx
frontend/src/component/insights/componentsChart/FlagsProjectChart/FlagsProjectChart.tsx
frontend/src/component/insights/componentsChart/MetricsSummaryChart/MetricsChartTooltip/MetricsChartTooltip.tsx
frontend/src/component/insights/componentsChart/ProjectHealthChart/ProjectHealthChart.tsx
frontend/src/component/insights/componentsChart/UsersPerProjectChart/UsersPerProjectChart.tsx
frontend/src/component/insights/hooks/usePlaceholderData.ts
frontend/src/component/loginHistory/LoginHistoryTable/LoginHistorySuccessfulCell/LoginHistorySuccessfulCell.tsx
frontend/src/component/playground/Playground/PlaygroundGuidance/PlaygroundGuidanceSection/PlaygroundGuidanceSection.tsx
frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/StrategyList/StrategyItem/StrategyExecution/DisabledStrategyExecution.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/SingleSelectConfigButton.tsx
frontend/src/component/project/Project/ProjectEnterpriseSettingsForm/ProjectEnterpriseSettingsForm.tsx
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestProcessHelp/ChangeRequestProcessHelp.tsx
frontend/src/hooks/api/getters/useResetPassword/useResetPassword.ts
frontend/src/hooks/useSearch.ts
frontend/yarn.lock
package.json
src/lib/addons/feature-event-formatter-md.ts
src/lib/features/feature-search/feature-search-store.ts
yarn.lock

Sorry for the extra noise here, but this seems to be the biome upgrade altering formatting slightly.

task: upgraded semver dependency (and biome)

---

src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature-search-store.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/openapi/spec/feature-search-query-parameters.ts

Previous search by type was an array and now we can use operators. Also the UI didn't use previous filter by type and now we can re-use one of the filters.

feat: more powerful feature search by type

---

frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.test.tsx
frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.test.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOverviewFilters.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/useProjectFeatureSearch.ts
frontend/src/openapi/models/searchFeaturesParams.ts

You can filter by clicking on the feature type icon
Or you can select types from a dropdown 
Backend already supports filtering by feature flag type.

feat: filter by feature type

---

.github/workflows/publish-new-version.yaml

Small detail I'd like to include which is to copy the changelog from the release branch to main. This way we'll only have major, minor and patch logs automatically in main

Checkout changelog from release branch into main

---

src/lib/db/index.ts
src/lib/features/project/createProjectService.ts
src/lib/features/project/fake-project-flag-creators-read-model.ts
src/lib/features/project/project-controller.ts
src/lib/features/project/project-flag-creators-read-model.ts
src/lib/features/project/project-flag-creators-read-model.type.ts
src/lib/features/project/project-flag-creators.e2e.test.ts
src/lib/features/project/project-service.ts
src/lib/openapi/spec/index.ts
src/lib/openapi/spec/project-flag-creators-schema.ts
src/lib/types/stores.ts
src/test/fixtures/store.ts

Adding a new endpoint that returns all users who created a flag in a given project. It includes those users who are deactivated. This API will be used for feature search based on flag creator (including those who left the project).
As a display name we use name, username with a fallback to email

feat: project flag creators api

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.test.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOverviewFilters.tsx

test: filter by created by/author

---

src/lib/features/project/project-flag-creators-read-model.ts

fix: remove null users in filter
