Unleash/unleash

src/lib/util/db-lock.test.ts
src/lib/util/db-lock.ts

* Adding Promise timeout in DB lock. Once the lock is acquired the function that we're locking (e.g. DB migration) has 60 seconds (default value) to do its job. After the timeout elapsed we unlock the lock.
* This change may also remove some flakiness in the tests since I noticed that the previous incorrect implementation of the timeout did not close the client in the timeout test
Is 60 second enough for the DB migrations to run?
for now I increase it to 30 minutes to be on the safe side.

feat: promise timeout on lock

---

frontend/src/component/admin/Admin.tsx
frontend/src/component/admin/adminRoutes.ts
frontend/src/component/admin/banners/Banners.tsx
frontend/src/component/admin/banners/BannersTable/BannerDeleteDialog.tsx
frontend/src/component/admin/banners/BannersTable/BannersActionsCell.tsx
frontend/src/component/admin/banners/BannersTable/BannersTable.tsx
frontend/src/component/banners/Banner/Banner.tsx
frontend/src/component/banners/internalBanners/InternalBanners.tsx
frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
frontend/src/component/common/Table/cells/ToggleCell/ToggleCell.tsx

https://linear.app/unleash/issue/2-1484/ui-create-an-admin-banners-configuration-page
Adds a new "Banners" page to the admin UI.
This first iteration allows admins to list and preview all configured message banners, toggle them (whether they are currently visible to all users or not), and remove them.
Next step will be creating the modal for "new" and "edit" operations.

feat: banners admin page

---

src/lib/db/project-store.ts
src/lib/services/project-service.ts
src/lib/types/model.ts

This fixes a bug updating a project, when optional data (defaultStickiness and featureLimit are not part of the payload).
Example:
```shell
curl -XPUT http://localhost:4242/api/admin/projects/default -H 'Authorization: *:*.unleash-insecure-admin-api-token' -H 'Content-Type: application/json' -d '{"description":"test description","name":"RenamedToThisString"}'
```
Then if you try to get the project with a PAT, the API will return a 403. The reason is that the **project mode** gets cleared (mode=null) because of the following update statement that does not check if defaultStickiness or featureLimit are present, resulting in an update without fields that clears the table https://github.com/Unleash/unleash/blob/main/src/lib/db/project-store.ts#L268-L281
Note that the project still exists, and …

fix: don't clean up settings when optional data is not present

---

src/lib/server-impl.ts
src/lib/services/client-metrics/last-seen/fake-last-seen-store.ts
src/lib/services/client-metrics/last-seen/last-seen-service.ts
src/lib/services/client-metrics/last-seen/last-seen-store.ts
src/lib/services/client-metrics/last-seen/tests/last-seen-service.e2e.test.ts
src/lib/services/client-metrics/last-seen/types/last-seen-store-type.ts
src/lib/services/index.ts
src/test/e2e/services/last-seen-service.e2e.test.ts
src/test/fixtures/store.ts

This PR adds a cleanup job that removes unknown feature flags from last_seen_at_metrics table every 24 hours since we no longer have a foreign key on the name column in the features table.

feat: add job that cleans last seen every 24 hours

---

package.json

In heroku our build breaks with:
```
[build:frontend] [vite:css] Preprocessor dependency "sass" failed to load:
[build:frontend] Cannot read properties of undefined (reading 'indexOf')
```
Root cause analysis:
* heroku installs node 21 which doesn't work with the sass dependency compiled from dart to js
More: https://stackoverflow.com/questions/77314799/vitecss-preprocessor-dependency-sass-failed-to-load-cannot-read-propertie

fix: one of our deps breaks on node 21

---

frontend/src/component/common/Sticky/Sticky.tsx
frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx

Tiny zIndex fix for the draft banner for a regression introduced in https://github.com/Unleash/unleash/pull/5088

fix: draft banner zIndex

---

src/lib/db/client-instance-store.ts
src/lib/server-impl.ts
src/lib/services/client-metrics/last-seen/last-seen-service.ts
src/lib/services/client-metrics/metrics-service-v2.ts
src/lib/services/index.ts
src/test/e2e/helpers/database-init.ts
src/test/e2e/services/last-seen-service.e2e.test.ts

Move metrics service scheduling to a scheduler

refactor: move metrics service scheduling

---

biome.json
package.json
src/lib/addons/feature-event-formatter-md.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/types/user.test.ts
src/lib/util/generateImageUrl.test.ts
src/lib/util/generateImageUrl.ts
yarn.lock

As #4475 says, MD5 is not available in secure places anymore. This PR swaps out gravatar-url with an inline function using crypto:sha256 which is FIPS-140-2 compliant. Since we only used this method for generating avatar URLs the extra customization wasn't needed and we could hard code the URL parameters.
fixes: Linear https://linear.app/unleash/issue/SR-112/gh-support-swap-out-gravatar-url-lib
closes: #4475

feat: replace gravatar-url with inline function

---

.github/workflows/check_links.yaml
.lycheeignore
src/lib/openapi/spec/application-schema.ts
src/lib/openapi/spec/create-application-schema.ts
src/lib/openapi/spec/reset-password-schema.ts

Fixed https://github.com/Unleash/unleash/issues/5115

bug: fix broken links from lychee

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

Fix an issue in the query where it would fetch uneccesary rows

fix: only get rows for toggles in project

---

frontend/src/component/admin/banners/BannerModal/BannerForm.tsx
frontend/src/component/admin/banners/BannerModal/BannerModal.tsx
frontend/src/component/admin/banners/BannersTable/BannersTable.tsx
frontend/src/component/banners/Banner/Banner.tsx
frontend/src/component/common/FormSwitch/FormSwitch.tsx
frontend/src/hooks/api/actions/useMessageBannersApi/useMessageBannersApi.ts
frontend/src/interfaces/banner.ts

https://linear.app/unleash/issue/2-1548/ui-create-banner-newedit-modal
Adds a new banner modal (and form) that allows admins to create and edit banners.
Also adds a new `FormSwitch` common component that may be helpful in different situations where we need a switch on a form.

feat: banner modal

---

frontend/src/component/feature/CopyFeature/CopyFeature.test.tsx
frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts
frontend/src/component/project/Project/ProjectFeatureToggles/ActionsCell/ActionsCell.tsx

bug: remove strategies from copy breadcrumbs

---

src/lib/db/project-store.ts
src/migrations/20231025093422-default-project-mode.js

Currently, when there was no entry in project settings table, the project_mode was left null, which broke some logic.
Now we will set it and enforce database level restrictions on it.

fix: project mode can not be set to null anymore

---

frontend/src/component/admin/banners/BannerModal/BannerModal.tsx
frontend/src/component/admin/banners/BannersTable/BannersTable.tsx
frontend/src/hooks/api/actions/useBannersApi/useBannersApi.ts

https://linear.app/unleash/issue/2-1556/adapt-toggles-in-banners-table-to-use-the-new-on-and-off-endpoints
Uses the new on/off endpoints in the banners table toggles.
Also includes a missing rename for the `useMessageBannersApi` hook, to `useBannersApi`.

feat: use new on/off endpoints in banners toggles

---

src/migrations/20231024121307-add-change-request-schedule.js

This PR adds a db table for CR schedules. The table has two columns:
1. `change_request` :: This acts as both a foreign key and as the primary key for this table.
2. `scheduled_at` :: When the change is scheduled to be applied.
We could use a separate ID column for these rows and put a `unique` constraint on the `change_request` FK, but I don't think that adds any more value. However, I'm happy to hear other thoughts around it.

1-1531: create db table for cr schedules

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/openapi/spec/feature-search-query-parameters.ts
src/lib/openapi/spec/index.ts

feat: feature search basic functionality

---

frontend/src/component/playground/Playground/AdvancedPlayground.tsx

do not track empty strings in playground token input

fix: do not track empty strings in playground token input

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/openapi/spec/feature-search-query-parameters.ts

feat: filter by tags

---

src/lib/routes/client-api/metrics.test.ts

This test seems to fail more than half the time on my machine and in the build. No idea why this ever worked correctly because it seems to have an inherent race condition with other tests in this file. This seems to make the problem go away

fix: flaky test

---

src/migrations/20231004120900-create-changes-stats-table-and-trigger.js

`EXECUTE FUNCTION` was introduced in Postgres v11. In Postgres v10 the syntax was `EXECUTE PROCEDURE`. This fix changes the syntax to `EXECUTE PROCEDURE`, which is perfectly fine sense our function does not return anything.

fix: make sure we are still pg10 compatible.

---

frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ActionsCell/ActionsCell.tsx

In ActionsCell.tsx file, 'Copy' with FileCopy icon is changed to 'Clone' with 'LibraryAdd' icon as this feature is used to clone a new feature from existing one. Upon copying the icon and text will change to 'Check' icon with 'Copied!' for one sec and closes automatically.
In FeatureView.tsx file, 'FileCopy' icon is introduced next to Feature flag name and the existing FileCopy icon is changed to 'LibraryAdd' icon which represents cloning a new feature.
Closes #4098 
ActionsCell.tsx
FeatureView.tsx

feat: add copy button to feature flag name (#4098)

---

src/lib/features/private-project/privateProjectStore.ts

If you are not root viewer, it should give instantly all access.
This PR fixes the issue and now it will early exit.

fix: private projects early exit when not root viewer

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-search/next-link.test.ts
src/lib/features/feature-search/next-link.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/openapi/spec/feature-search-query-parameters.ts

Generates link to the next page and allows for easy HATEOAS based navigation. 
Changes:
* added utility for calculating next page (eventually we'll move it up the directory tree if needed)
* changed cursor calculation logic to take the cursor of the next item instead of the cursor of the last used item
Currently only Link to next page is provided and it's easy to parse. We may add extra rel=next later to the header but it complicates parsing

feat: Cursor based hateoas

---

src/lib/features/segment/segment-controller.ts
src/lib/segments/segment-service-interface.ts
src/lib/services/segment-service.ts

Splitted the `getStrategies` into `getVisibleStrategies` and `getAllStrategies`, which will handle the permissions.
If we are deleting a segment, `getAllStrategies` will be used and private projects will not be counted.

fix: do not allow segment deletion when used in private projects

---

frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectOverview.tsx
frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Connecting project overview features list to the search API. Currently we only return the first results with no cursor increments. You can see that even though I have hundreds of feature we only show 26 results.
To make it work I had to refactor existing component for a table to allow for configurable onChange. We can either refresh project API or search API in this onChange handler.
The code is based on a new flag:
Next PRs:
* add infinite loader and cursor changes
* translate search and filter into query params
* sort server side instead of client side
* add tests

feat: connect project overview table to search api

---

website/docusaurus.config.js
website/remote-content/shared.js

Markdown generators (including GitHub) tend to lowercase the titles
when they create anchor links. It appears that the intra-doc links might not work correctly if they're incorrectly cased. 
This fixes the issue by lowercasing any links we find to internal headers in external documents (such as the SDKs and Edge/Proxy docs).
Now, there is one potential issue with this: if someone creates an explicit link in the SDKs that uses uppercase letters, then this might break the docs build in the future.
However, I think this is unlikely to happen any time soon, and I would think that it's more likely that people will incorrectly case the header link.

fix(docs): lowercase internal markdown links

---

frontend/src/component/common/Table/cells/FeatureSeenCell/FeatureEnvironmentSeenCell.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/createFeatureToggleCell.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/useFeatureToggleSwitch.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/RowSelectCell/RowSelectCell.tsx

This PR memoizes some of the heavier components in our project overview table

refactor: memoize heavy components in project overview

---

website/docs/reference/sdks/index.md

Added a detailed explanation into how frontend / client-side SDKs behave with regards to fetching multiple feature flags and network connectivity.
Content has been reviewed/approved by engineering rotation team (Simon and Chris).

Docs: Client-side feature flag querying behavior update

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
src/migrations/20231103064746-change-request-schedule-change-type.js

Changes the change_request_schedule `status` column to text. 
Drops the custom type

chore: remove enum type from db

---

frontend/src/component/changeRequest/ChangeRequestOverview/ApplyButton/ApplyButton.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/MultiActionButton/MultiActionButton.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx

The button doesn't do anything at the moment, but it's there visually.
Because this uses the same button as the dual-function button for approve/reject, I extracted that component into a reusable "multi-action" button. I could have copied the code wholesale, but it's a complex component, so I thought this would be a better solution.
I'll add the dialog in a follow-up PR. This one already has a lot of changes.
Visual:

chore: add schedule option to approved change requests

---

src/lib/openapi/util/openapi-tags.ts

https://linear.app/unleash/issue/2-1515/create-new-api-tag-banners-for-ga
Adds a new OpenAPI tag "Banners" in preparation for GA.

feat: add banners OpenAPI tag

---

frontend/src/hooks/api/getters/useFeatureSearch/searchToQueryParams.test.ts
frontend/src/hooks/api/getters/useFeatureSearch/searchToQueryParams.ts

As we're migrating from the client side search to server side search I created a pure function responsible for translating search and filter string into query params e.g.:
`searchString type:release,experimental tag:simple:web` should translate to `query=searchString&type[]=release&type[]=experimental&tag[]=simple:web`
This code handles all the corner cases I could think of:
* extra spaces around filter items (compared to our client side search we allows spaces after colon e.g. `type: release` and not just `type:release`)
* one and multiple filter values
* only search, only filter, search and filter
* special case for environment status enabled/disabled (any environment should be supported and we detect it by value of disabled/enabled)
As a result this code should also work for other …

feat: serach and filter input to query param parser

---

src/lib/services/client-metrics/last-seen/last-seen-store.ts

Sort the items before inserting them into the database in order to reduce the chance of deadlocks happening when multiple pods are inserting at the same time.

fix: last seen deadlocks

---

src/lib/middleware/demo-authentication.ts
src/lib/routes/proxy-api/index.ts
src/lib/server-impl.ts
src/lib/services/client-metrics/metrics-service-v2.ts
src/lib/services/proxy-service.ts

Expose new interface while also getting rid of unneeded compiler ignores
None of the changes should add new security risks, despite this report:
> Code scanning results / CodeQL Failing after 4s — 2 new alerts including 2 high severity security vulnerabilities
Not sure what that means, maybe a removed ignore...

chore: expose type and more fixes

---

package.json
src/lib/error/bad-data-error.ts
src/lib/error/unleash-error.test.ts
src/lib/openapi/spec/patch-schema.ts
src/lib/services/openapi-service.ts
src/test/e2e/api/admin/project/variants.e2e.test.ts
src/test/e2e/api/openapi/openapi.e2e.test.ts
src/test/e2e/helpers/test-helper.ts
yarn.lock

Switch the express-openapi implementation from our internal fork to the upstream version. We have upstreamed our changes and a new version has been released, so this should be the last step before we can retire our fork.
Because some of the dependencies have been updated since our internal fork, we also need to update some of our error handling to reflect this.

refactor: switch to upstream express-openapi

---

src/lib/features/change-request-access-service/change-request-access-read-model.ts
src/lib/features/dependent-features/dependent-features-service.ts
src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/import-permissions-service.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts
src/lib/routes/admin-api/api-token.ts
src/lib/routes/admin-api/project/api-token.ts
src/lib/routes/admin-api/project/variants.ts
src/lib/routes/client-api/register.ts
src/lib/routes/unleash-types.ts
src/lib/server-impl.ts
src/lib/services/client-metrics/metrics-service-v2.ts
src/lib/services/favorites-service.ts
src/lib/services/pat-service.ts
src/lib/services/user-feedback-service.ts
src/lib/services/user-service.ts
src/lib/services/user-splash-service.ts
src/lib/types/user.ts
src/test/fixtures/fake-user-store.ts

A very subtle change in the way we import IUser makes a huge difference because previously, instead of importing IUser interface we were importing User and naming it IUser here:
https://github.com/Unleash/unleash/blob/6f8f21fd488cfbf53a3526ffa138e40c3a43e27c/src/lib/routes/unleash-types.ts#L2
whereas the correct way of importing the interface is:
https://github.com/Unleash/unleash/blob/eec64b119e133813e4f4c4a42e9bdd0a8db65259/src/lib/routes/unleash-types.ts#L2

chore: import IUser instead of User for auth

---

website/docusaurus.config.js
website/package.json

This change sets `noRuntimeDownloads` to `true` for
`plugin-remote-content'` to avoid the infinite loop issue mentioned in
https://github.com/rdilweb/docusaurus-plugin-remote-content/issues/51,
as described in
https://github.com/rdilweb/docusaurus-plugin-remote-content#noruntimedownloads.
Note that this will require you to generate the files before
running the doc build, which may be more an issue, so it's a tradeoff.
To generate the files before building run:
```bash
yarn docusaurus download-remote-content-external
yarn docusaurus download-remote-content-sdks
```
We can of course write a simpler command that does this for us (or even make it part of the build step). In fact, I think we'll need to do exactly that. It seems to be failing now because the files are not generated by default …

docs: fix an issue where it goes into an infinite loop when building

---

src/lib/db/access-store.ts

Fixes / refactors the way roles are being fetched in `removeRolesOfTypeForUser` to be more consistent with the rest of our code base.

fix: correctly query roles to be removed

---

website/docusaurus.config.js

Adds a redirect rule for the Slack App integration (fix current broken link).

docs: add slack app redirect

---

src/lib/error/bad-data-error.ts
src/lib/error/unleash-error.test.ts

The `dataPath` was present (but not in the type) in previous versions of the
error library that we use. But with the recent major upgrade, it's
been removed and the `instancePath` property has finally come into use.
This PR removes all the handling for the previous property and
replaces it with `instancePath`. Because the `dataPath` used full
stops and the `instancePath` uses slashes, we need to change a little
bit of the handling too.

Chore: remove "dataPath" from data OpenAPI data errors.

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestScheduledDialogs/ChangeRequestScheduledDialog.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestScheduledDialogs/ScheduleChangeRequestDialog.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestScheduledDialogs/changeRequestScheduledDialogs.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts

Closes: # 
[1-1585](https://linear.app/unleash/issue/1-1585/reschedule-changes-dialog)
[1-1582](https://linear.app/unleash/issue/1-1582/change-apply-changes-apply-or-schedule-changes)
Manually tested e2e -> Approve -> Schedule -> Reschedule -> Apply/Reject: ui tests verifying it in next pr

feat: schedule changes dialog

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

As the title says, this PR adds a flag to unleash for detecting segment usage in CRs.

chore: add detect segment usage in CRs flag

---

src/lib/features/feature-toggle/tests/feature-toggle-last-seen-at.e2e.test.ts

This test was flaky because it relied on the order of the array
returned. To make it less flaky, we now turn the array into an object
instead and compare that.

fix: make test for last seen by env not rely on array order

---

frontend/src/component/segments/CreateSegment/CreateSegment.tsx
frontend/src/component/segments/EditSegment/EditSegment.tsx
frontend/src/hooks/api/actions/useApi/useApi.ts
src/lib/error/permission-error.ts
src/lib/features/segment/segment-controller.ts
src/lib/middleware/rbac-middleware.test.ts
src/lib/middleware/rbac-middleware.ts

https://linear.app/unleash/issue/SR-164/ticket-1106-user-with-createedit-project-segment-is-not-able-to-edit-a
Fixes a bug where the `UPDATE_PROJECT_SEGMENT` permission is not respected, both on the UI and on the API. The original intention was stated [here](https://github.com/Unleash/unleash/pull/3346#discussion_r1140434517).
This was easy to fix on the UI, since we were simply missing the extra permission on the button permission checks.
Unfortunately the API can be tricky. Our auth middleware tries to grab the `project` information from either the params or body object, but our `DELETE` method does not contain this information. There is no body and the endpoint looks like `/admin/segments/:id`, only including the segment id. 
This means that, in the rbac middleware when we check the …

fix: take into account project segments permission

---

src/lib/middleware/rbac-middleware.ts

This fixes an edge case not caught originally in https://github.com/Unleash/unleash/pull/5304 - When creating a new segment on the global level:
- There is no `projectId`, either in the params or body
- The `UPDATE_PROJECT_SEGMENT` is still a part of the permissions checked on the endpoint
- There is no `id` on the params
This made it so that we would run `segmentStore.get(id)` with an undefined `id`, causing issues.
The fix was simply checking for the presence of `params.id` before proceeding.

fix: segment project fetch when global

---

frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
frontend/src/component/project/Project/hooks/useProjectForm.ts
src/lib/db/project-store.ts

https://linear.app/unleash/issue/SR-169/ticket-1107-project-feature-flag-limit-is-not-correctly-updated
Fixes #5315, an issue where it would not be possible to set an empty flag limit. 
This also fixes the UI behavior: Before, when the flag limit field was emptied, it would disappear from the UI.
I'm a bit unsure of the original intent of the `(data.defaultStickiness !== undefined || data.featureLimit !== undefined)` condition. We're in an update method, triggered by a PUT endpoint - I think it's safe to assume that we'll always want to set these values to whatever they come as, we just need to convert them to `null` in case they are not present (i.e. `undefined`).

fix: project settings flag limit not properly set

---

src/lib/db/segment-store.test.ts
src/lib/db/segment-store.ts
src/lib/openapi/spec/admin-segment-schema.ts
src/test/e2e/api/admin/segment.e2e.test.ts
src/test/e2e/api/client/segment.e2e.test.ts

This PR updates the segment usage counting to also include segment usage in pending change requests. 
The changes include:
- Updating the schema to explicitly call out that change request usage is included.
- Adding two tests to verify the new features
- Writing an alternate query to count this data
Specifically, it'll update the part of the UI that tells you how many places a segment is used:
Implementing this was a little tricky. Previously, we'd just count distinct instances of feature names and project names on the feature_strategy table. However, to merge this with change request data, we can't just count existing usage and change request usage separately, because that could cause duplicates.
Instead of turning this into a complex DB query, I've broken it up into a few separate …

feat: include segment usage in CRs when showing usage in projects and flags

---

src/lib/types/events.ts

Rename event to SCHEDULED_CHANGE_REQUEST_EXECUTED
This event will be triggered when the executor runs a scheduled change request.
The ChangeRequestApplied event will remain as is (going out to project members - but will have a scheduled = true  property in the data if it scheduled.
This new event will fire on execution of the schedule and have a result = "failed" | "succeeded" property.
Because notifications are tied to events, this notification will go out to the creator and the applier

fix: new SCHEDULED_CHANGE_REQUEST_EXECUTED on scheduled cr execution

---

website/docs/contributing/ADRs/ADRs.md
website/docs/contributing/ADRs/back-end/POST-PUT-api-payload.md

While working on Terraform I identified some issues with how our backend handled some requests. This happened because the Terraform client was unaware of new fields and was not sending them. This resulted in bad behavior as some of those missing fields were treated in the backend as `null` and removed existing data from the DB.
This ADR aims to shed some light on the problem and specifies how our server should handle these requests.

docs: POST and PUT body handling

---

src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

Optimizations:
1. Removed extra round trip to database  to count environments
2. Removed extra round trip to database to count features
Fixes:
Currently, we were using a very optimistic query to set correct limit and offset. This breaks as soon we we join tags.
` query = query
.select(selectColumns)
.limit(limit * environmentCount)
.offset(offset * environmentCount);` 
The solution was to use common table expressions, so we could count and rank features.

feat: fix paging in sql by using common table expressions

---

src/lib/db/access-store.ts

How we replicated the problem (note this may happen in other endpoints as well). Check at the end we received some 500 errors:
```shell
$ hey -m PUT -H 'Authorization: *:*.unleash-insecure-admin-api-token'     -H 'Content-Type: application/json'     -d '{
"name": "sa1-mod",
"username": "sa1-mod",
"rootRole": 1
}' http://localhost:4242/api/admin/service-account/2
Summary:
Total:	0.7555 secs
Slowest:	0.2489 secs
Fastest:	0.0277 secs
Average:	0.1691 secs
Requests/sec:	264.7318
Total data:	46452 bytes
Size/request:	232 bytes
Response time histogram:
0.028 [1]	|■
0.050 [3]	|■■
0.072 [2]	|■
0.094 [6]	|■■■
0.116 [5]	|■■■
0.138 [12]	|■■■■■■■
0.160 [18]	|■■■■■■■■■■
0.183 [70]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.205 [73]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.227 [5]	|■■■
0.249 [5]	|■■■ …
```

fix: handle concurrent service account updates

---

frontend/src/component/segments/SegmentEmpty.tsx
frontend/src/component/segments/SegmentForm.tsx
frontend/src/component/segments/SegmentFormStepTwo.tsx

https://linear.app/unleash/issue/SR-184/ticket-1106-users-with-createedit-project-segment-dont-see-all-the
https://github.com/Unleash/unleash/pull/5304 did not take into account permissions further into the Segment form.
This PR fixes the remaining permission checks to take into consideration the project-level permission: `UPDATE_PROJECT_SEGMENT`.

fix: take into account project segments permission in form

---

frontend/src/component/segments/SegmentEmpty.tsx
frontend/src/component/segments/SegmentForm.tsx
frontend/src/component/segments/SegmentFormStepTwo.tsx

https://linear.app/unleash/issue/SR-184/ticket-1106-users-with-createedit-project-segment-dont-see-all-the
https://github.com/Unleash/unleash/pull/5304 did not take into account permissions further into the Segment form.
This PR fixes the remaining permission checks to take into consideration the project-level permission: `UPDATE_PROJECT_SEGMENT`.
(cherry picked from commit f8a9d7f3558e62962cd722dbda1539359f920003)
Closes #

fix: take into account project segments permission in form (#5352)

---

src/lib/db/project-store.ts
src/lib/services/project-service.ts
src/test/e2e/services/project-service.e2e.test.ts

This PR fixes an issue where project overview would return hardcoded project mode and stickiness fields.

fix: hardcoded stickiness and mode fields

---

src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts

Instead of throwing an error when the project doesn't exist, we say that the names are valid, because we have nothing to say that they're not. Presumably there is already something in place to prevent you from importing into a non-existent project.

fix: handle check against non existing projects

---

src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

The issue was that we all features were created exactly in same time, and our feature counter was expecting time to be unique to feature, which was not the case.

fix: total number should be correct now in search

---

src/lib/features/change-request-segment-usage-service/change-request-segment-usage-read-model.test.ts
src/lib/features/change-request-segment-usage-service/change-request-segment-usage-read-model.ts
src/lib/features/change-request-segment-usage-service/fake-change-request-segment-usage-read-model.ts
src/lib/features/change-request-segment-usage-service/sql-change-request-segment-usage-read-model.ts
src/lib/openapi/spec/admin-strategies-schema.ts
src/test/e2e/api/admin/segment.e2e.test.ts

This PR adds the ability to detect which strategies use a specific segment in active change requests.
It does not wire this functionality up to anything just yet. Follow-up PRs will integrate this with the segment service and eventually with the front end.

chore: find segment strategies in CRs

---

src/lib/features/scheduler/scheduler-service.test.ts
src/lib/features/scheduler/scheduler-service.ts
src/lib/metric-events.ts
src/lib/metrics.ts
src/lib/services/index.ts
src/lib/services/maintenance-service.test.ts
src/server-dev.ts

See linear issue: https://linear.app/unleash/issue/1-1656/add-scheduler-observability
As per post mortem actions, we are adding observability to scheduled functions.
This PR adds prometheus observability to our scheduled functions via a summary. In addition to timing these functions with the more accurate process.hrtime, we are getting a counter for free per scheduled job id.
Prometheus example:

feat: scheduled functions observability

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts

In short the issue is that after our last seen improvements, we did not update where we are getting last_seen field. It was still using features table, which is not the source of last seen anymore.

fix: last seen is now using last seen values from new table

---

.github/workflows/build.yaml

https://linear.app/unleash/issue/2-1434/unpin-node-18-when-a-fix-is-out
Unpins the node version in our build step.
Continues the work of https://github.com/Unleash/unleash/pull/5146

chore: unpin node version in build

---

src/lib/services/project-service.ts
src/test/e2e/services/project-service.e2e.test.ts

Removing a user from a project was impossible if you only had 1 owner. It worked fine when having more than an owner. This should fix it and we'll add tests later

fix: remove user from project

---

src/lib/features/change-request-segment-usage-service/change-request-segment-usage-read-model.test.ts
src/lib/features/change-request-segment-usage-service/change-request-segment-usage-read-model.ts
src/lib/features/change-request-segment-usage-service/fake-change-request-segment-usage-read-model.ts
src/lib/features/change-request-segment-usage-service/sql-change-request-segment-usage-read-model.ts

This change is in preparation for the upcoming implementation (working
in https://github.com/Unleash/unleash/pull/5369). However, because the
implementation is a lot of lines, this PR is to break it apart and
make it easier to merge.
In this stage, we refactor the segment usage read model. Instead of
checking just whether a segment is in use, we now extract the list of
strategies that use this segment. This is slightly more costly,
perhaps, but it will be necessary for the upcoming implementation.

chore: use query to get strategies instead of whether a segment is in use

---

src/lib/db/segment-store.test.ts
src/lib/db/segment-store.ts
src/lib/services/segment-service.ts
src/lib/types/stores/segment-store.ts

Otherwise, we might accidentally display CR data to open source users.
But more importantly, it might keep them from being able to delete a
segment that's in use by a CR in their database that they can't touch.
So by checking that they're on an enterprise instance, we avoid this
potential blocker.
I've added the `includeChangeRequestUsageData` parameter as a boolean now, but I'm open to other suggestions.

chore: only return change request data if the unleash instance is an enterprise instance

---

src/lib/services/segment-service.ts
src/test/e2e/api/admin/segment.e2e.test.ts

This PR changes the behavior of the API a little bit. Instead of
removing any strategies from `changeRequestStrategies` that are also
in `strategies`, we keep them in instead.
The reason for this is that the overview of where a segment is used is
incomplete if it shows only strategies but not CRs. Imagine this:
You want to delete a segment, but you're told it's only used in strategy S.
So you go and remove it from strategy S, but then you're told it's
suddenly used in CRs A, B, and C. This is now a two-step operation
with a bad surprise. Instead, we could show you immediately that this
segment is used in strategy S and CRs A, B, and C.

fix: if a strategy both uses a segment actively and in CRs, list it twice

---

src/migrations/20231122121456-dedupe-any-duplicate-permissions.js
src/test/e2e/dedupe-permissions.e2e.test.ts

https://linear.app/unleash/issue/2-1656/create-db-migration-that-ensures-correct-state-of-permissions
This adds a migration that dedupes any duplicate permissions.

fix: dedupe any duplicate permissions

---

src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature-search-service.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/openapi/spec/feature-search-query-parameters.ts

This is first iteration. When we add more fields to be filterable with operators, we can have more reusable components for this.

feat: allow filtering projects with operators

---

frontend/src/component/archive/ArchiveTable/ArchiveBatchActions.tsx
frontend/src/component/archive/ArchiveTable/ArchiveTable.tsx
frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureDeleteConfirm/ArchivedFeatureDeleteConfirm.tsx

This PR addresses 2 tasks that aim to fix and improve the UI/UX on archived feature toggle deletion:
- https://linear.app/unleash/issue/UNL-260/delete-feature-toggle-dialog-update-word-toggles-to-singular-toggle
- https://linear.app/unleash/issue/UNL-282/deleting-multiple-toggles-in-the-project-archive-the-batch-selector
Essentially:
- Makes it clearer that we're deleting a single feature toggle by changing the text to singular toggle
- Improves clarity further by adding a list of feature toggles about to be deleted
- Fixes a bug where the batch selector would not be cleared after deleting multiple feature toggles

fix: delete archived feature toggles in the UI

---

src/lib/features/export-import-toggles/export-import-service.ts
src/lib/util/allSettledWithRejection.test.ts
src/lib/util/allSettledWithRejection.ts

JS promises support Promise.all and Promise.allSettled. Promise.all rejects on the first rejecting promise. Promise.allSettled waits for all promises to settle and returns an array of resolved and rejected promises. I'm adding a new utility that behaves like Promise.all (rejects on the first rejection) but gives all promises a chance to finish. 
This new utility solves an issue where some of the promises were running after a transaction was closed because first rejected promise rejected much sooner than the other ones, the tx was closed and the remaining queries were left w/o a pending tx.

fix: prevent concurrent queries from running out of transaction

---

src/lib/segments/segment-service-interface.ts
src/test/e2e/api/client/segment.e2e.test.ts

Fix this error showing up in tests output:
Root cause:
* update segment verifies if change requests are enabled. Change request enabled check requires user id. The user id was not passed in unit tests even though in production code it is being passed
Solution:
* add user id in test
* update segment service interface to reflect the new requirement

fix: missing user id in segment update

---

website/docs/contributing/backend/overview.md
website/docs/using-unleash/deploy/database-setup.md

We've been caught out here, we added a migration that used PG>=11 syntax, but our docs still state that we support v10, when it reached EoL Nov 2022. This updates our docs to state v14 and newer, v14 came out in 2021 and as such won't be EoL until 2026 according to [Postgres 5 year versioning scheme support](https://www.postgresql.org/support/versioning/)

docs: Update recommended postgres to 14

---

scripts/resetdatabase.sql
website/docs/contributing/backend/overview.md

See [Linear issue 2-1627](https://linear.app/unleash/issue/2-1627/db-permissions-update-docs-and-migration-guides).
Since we now use functions, we need more permissions than just GRANT ALL PERMISSIONS ON DATBASE. In addition we need to be allowed to create functions in the schema that's actually being used. This PR takes the easy way out and say that we need OWNER privileges on the database. That guarantees that we can do all we do in our migration scripts.
We might encounter some pushback on this, if so, we'll need to say that we need
`GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN <schema>` in addition to GRANT ALL PRIVILEGES ON DATABASE, where <schema> is the schema selected in their configuration.

Updated scripts to use owner

---

frontend/src/component/playground/Playground/PlaygroundGuidance/PlaygroundGuidance.tsx

- Change "undestand" to "understand"
- Capitalize "Unleash"

fix: typo in Unleash playground frontend

---

src/lib/db/segment-store.ts
src/test/e2e/api/admin/segment.e2e.test.ts

The previous check would return `false` if the value was 0, causing a
bug where the usage data wouldn't be included.
This also adds tests to ensure that usage data for CR segments is propagated correctly because that's where I first encountered the issue.
Before this fix, if the values were 0, the data would display like the bottom element in the screenshot:

fix: check whether a usage data is defined

---

frontend/src/component/segments/SegmentDelete/SegmentDeleteUsedSegment/sort-strategies.test.ts
frontend/src/component/segments/SegmentDelete/SegmentDeleteUsedSegment/sort-strategies.ts

This PR adds a strategy sorting algorithm to be used for the segment deletion dialog. It assumes that you have a list of existing strategies and a list of change request strategies. Based on the content of these two lists, it will create one unified list sorted after a number of criteria (as listed in the test).
This impl does the sorting on the front end, but could we do it on the back end? Instead of adding a new property to the segment data, could we simply fold the change request strategies in with the existing segment strategies and return it using the old property? If the only place we do that is in this view, then that might be a good suggestion.

Chore: add strategy sorting algorithm

---

frontend/src/component/common/RoleDescription/RoleDescription.tsx
frontend/src/interfaces/permissions.ts
frontend/src/utils/permissions.ts
src/lib/db/access-store.test.ts
src/lib/db/access-store.ts
src/migrations/20231123155649-favor-permission-name-over-id.js
src/test/e2e/__snapshots__/favor-permission-name-over-id.e2e.test.ts.snap
src/test/e2e/dedupe-permissions.e2e.test.ts
src/test/e2e/favor-permission-name-over-id.e2e.test.ts

https://linear.app/unleash/issue/2-1664/create-db-migration-that-favors-the-name-column-over-id-for
Similar to https://github.com/Unleash/unleash/pull/5398, but non-breaking (semver).
This keeps the permissions `id` column intact, however favors the permission name whenever possible.

refactor: favor permission name over id

---

src/lib/services/tag-type-service.ts
src/test/e2e/api/admin/tag-types.e2e.test.ts

Before - green indicator for tag name:
After - red indicator for all fields:
When the new code tries to delete non existent tag it returns 404 and it should be fine since idempotency requirement applies to resource state not the HTTP code: https://stackoverflow.com/questions/24713945/does-idempotency-include-response-codes/24713946#24713946

fix: tag type deleted should indicate data deletion

---

src/lib/services/project-service.ts
src/test/e2e/services/project-service.e2e.test.ts

Before - all untouched settings were shown as deleted
After - only changing fields are shown

fix: naming pattern update event should keep old project settings

---

src/lib/db/access-store.ts

https://linear.app/unleash/issue/2-1672/hotfix-specify-table-in-permission-column-queries
This specifies the table that we are querying the `permission` column from, hopefully preventing ambiguity issues.
You can find the relevant changes here: [#5409](https://github.com/Unleash/unleash/pull/5409/files#diff-5cb4eca71e6a03ec3d123986d657368a3386f80e986dfef2e3feb0abb0673d87)

fix: specify permission table

---

src/lib/services/maintenance-service.ts
src/lib/services/proxy-service.ts
src/lib/services/setting-service.ts
src/lib/types/events.ts
src/test/e2e/services/setting-service.test.ts
src/test/e2e/services/user-service.e2e.test.ts

This adds more data to the setting events, so that its possible to see what has changed
Used to look like:
```
{
"id": "maintenance.mode"
}
```
Now it looks like this:
```
{
"id": "maintenance.mode",
"enabled": false
}
```

feat: include more data in setting event

---

src/lib/db/api-token-store.ts
src/lib/db/user-store.ts
src/lib/features/instance-stats/instance-stats-service.ts
src/lib/metrics.ts
src/lib/routes/admin-api/instance-admin.ts
src/lib/types/stores/api-token-store.ts
src/lib/types/stores/user-store.ts
src/test/fixtures/fake-api-token-store.ts
src/test/fixtures/fake-user-store.ts

This PR adds Prometheus metrics for the number of "service accounts" and "api tokens". 
Service Accounts:
Api tokens (label for type):

fix: add metrics for service account and api tokens

---

frontend/package.json
frontend/yarn.lock
website/package.json
website/yarn.lock

Latest version had a UI navigation bug where we wouldn't correctly navigate to the tab and instead it would add infinitely to the breadcrumbs / URL:
https://github.com/Unleash/unleash/assets/14320932/509fa528-7f9e-4476-a945-f74393e99dd5
This fixes the UI navigation by reverting https://github.com/Unleash/unleash/pull/5506

fix: UI navigation (reverts #5506)

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ChangeActions.tsx

Added 'Scheduled' state to the check for non-pending change requests
Closes # [1-1680](https://linear.app/unleash/issue/1-1680/remove-edit-change-ui-when-cr-is-scheduled)

feat: hide change actions when change request is scheduled

---

src/lib/services/email-service.ts
src/mailtemplates/scheduled-execution-failed/scheduled-execution-failed.html.mustache
src/mailtemplates/scheduled-execution-failed/scheduled-execution-failed.plain.mustache

What it says on the box.
Relates to # [1-1687](https://linear.app/unleash/issue/1-1687/send-an-email-when-the-scheduling-fails)

feat: new email template for scheduled-execution-failed email 

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleFilters/FeatureToggleFilters.tsx
frontend/src/component/project/Project/ProjectInfo/FlagTypesWidget.tsx
frontend/src/component/project/Project/ProjectInfo/ProjectInfo.tsx
frontend/src/component/project/Project/ProjectOverview.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectApiAccess/ProjectApiAccess.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectDefaultStrategySettings.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/Settings.tsx
frontend/src/hooks/api/getters/useProject/useProject.ts
frontend/src/hooks/api/getters/useProjectOverview/getProjectOverviewFetcher.ts
frontend/src/hooks/api/getters/useProjectOverview/useProjectOverview.ts
frontend/src/interfaces/project.ts

1. Created new hook for endpoint
2. Start removing useProject hook, when features not needed.

feat: update project overview endpoint

---

renovate.json

Schedule renovate to run and merge PRs before working hours to reduce noise. 
https://docs.renovatebot.com/presets-schedule/#schedulenonofficehours
From the documentation:

chore: schedule renovate to run early in the morning

---

src/lib/services/email-service.ts

Relates to # [1-1687](https://linear.app/unleash/issue/1-1687/send-an-email-when-the-scheduling-fails)
Removed `name` - not in template
Added missed `changeRequestTitle` for the html template context

fix: scheduled cr failed email

---

frontend/src/component/playground/Playground/AdvancedPlayground.tsx
frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundForm.tsx

Setting stacking context of the form to be on top of the results section. 
We're explicitly setting isolation to get an explicit stacking context for upper and lower div. The upper div is given higher zIndex. This way we can prevent global zIndex wars and everything in the upper part (form elements) always overlays the lower part (table results).
Before:
After:

fix: prevent search being stacked on top of the form dropdown

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/hooks/usePersistentTableState.ts
frontend/src/utils/serializeQueryParams.ts

This PR introduces a significant refactor in the handling of table states in the FeatureToggleListTable component. The changes focus on enhancing the persistence of table states and improving the management of query parameters.
Key Changes
- Created a new custom hook, `usePersistentTableState`, to manage the persistent state of table parameters. This hook leverages local storage to remember the user's table state across sessions.
- Replaced the existing useQueryParams hook with usePersistentTableState in FeatureToggleListTable.tsx to enable persistent state management.
- Replaced `BooleanParam` with utilities specific to our backend convention.

feat: Refactor Table State Persistence in Feature Toggle List

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanel.tsx

In the feature toggle overview screen, when you have a lot of environments, the sidebar getting sticky made it so you can't see other environments until you scroll to the end. This is now fixed.

fix: features sidebar scroll

---

frontend/src/component/common/ApiTokenTable/RemoveApiTokenButton/RemoveApiTokenButton.tsx

fix #5444
I have added an "environment" row to the file RemoveApiTokenButton.tsx to prompt users to confirm their intention before deleting a token. This enhancement aims to prevent accidental deletions and improve user experience.
Closes #5444 
The key file modified in this PR is RemoveApiTokenButton.tsx Reviewers should pay special attention to this file to understand the implementation of the "environment" row.
I would appreciate feedback on the implementation of the "environment" row and its impact on user interactions. Additionally, if there are alternative approaches or considerations that should be taken into account, please let me know.

fix(removeapitokenbutton.tsx): add environment name in delete token modal

---

frontend/src/component/common/FilterItem/FilterItem.test.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleFilters/FeatureToggleFilters.tsx

When navigating to features list, now it will respect the query params.

fix: state now persist to filters

---

frontend/src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/ConstraintViewHeaderOperator.tsx
frontend/src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/StyledIconWrapper.tsx

Includes some fixes to https://github.com/Unleash/unleash/pull/5565 after aligning with @nicolaesocaciu 
- Keeping the `isPrefix` prop is the correct thing to do here (it's also the only place in the whole codebase where it's being used)
- We should not add a `paddingRight` to the parent
- We don't need to set the color on the icon, since it's inherited by `StyledIconWrapperBase`
- After the changes above, the icon looks a bit tight in its box, so we fix that:
- We set `width` to `auto` in `StyledPrefixIconWrapper` to override the `width: 24` on `StyledIconWrapperBase`
- We set `paddingLeft` and `paddingRight` to `theme.spacing(1)` (8px)

fix: UI changes

---

website/docs/reference/segments.mdx

As discovered in the recent segments breakathon, the docs aren't very clear about how conflicts are handled. This PR better documents when they can't be deleted or moved. It also mentions the edge case where a segment is used in an archived flag (it still can't be deleted, so you must either delete the flag, or revive it and remove the segment)

docs: document how segment conflicts are handled

---

frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportCard/ReportCard.tsx
src/mailtemplates/schedule-change-conflict/scheduled-change-conflict.html
src/mailtemplates/scheduled-execution-failed/scheduled-execution-failed.html

Adds an info tooltip for potentially stale and a link to configure feature toggle type lifetime
Closes [UNL-215](https://linear.app/unleash/issue/UNL-215/improve-health-page-with-some-guidance-about-staleness)

feat: more info on staleness in health report

---

frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.test.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/NewFeatureStrategyEdit.test.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/NewFeatureStrategyEdit.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

This PR sets up the feature flag for the new strategy configuration and duplicates the components for the new setup

feat: initial setup

---

src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/openapi/spec/feature-search-query-parameters.ts

Now it is impossible to filter based on invalid tag syntax.

fix: added stronger tag validations

---

src/migrations/20231211122322-feature-types-created-by.js

Contains the migration that adds the column created_by to `feature_types`

chore: add migration for adding created_by to feature_types table

---

src/migrations/20231211121444-features-created-by.js

Contains the migration that adds the column created_by to `features`
replaces #5588

chore: migration for features created by

---

src/migrations/20231211132341-add-created-by-to-role-permission.js

As it says on the tin. In an attempt to make all operations in Unleash traceable to an originator. This PR adds created_by to role_permission, which will show which user assigned a permission to a role.

feat: add created_by to role_permission table

---

src/migrations/20231211133008-add-created-by-to-role-user.js

As it says in the title. Adds a created_by column to the role_user table to more easily track who's doing what.

feat: add column created_by to role_user table

---

src/lib/middleware/secure-headers.ts
src/lib/types/experimental.ts
src/server-dev.ts

Today we include a lot of "secutiry headers" for all API calls. Quite a lot of them are only relevent when we return a HTML document for the browser.
This PR removes and simplify these headers for API calls, so that we do not include unecessary data in the HTTP headers.
Each header have been carfully examied by following best practices from these source:
- https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html
- https://owasp.org/www-project-secure-headers/
This feature is protected with feature flag named 'stripHeadersOnAPI'.

fix: optimize headers we return for API calls.

---

frontend/src/component/common/FilterDateItem/FilterDateItem.test.tsx
frontend/src/component/common/FilterDateItem/FilterDateItem.tsx
frontend/src/component/common/FilterItem/FilterItem.test.tsx
frontend/src/component/common/FilterItem/FilterItem.tsx

Don't show open popover when there is existing state:

fix: show popover on empty state

---

website/docs/understanding-unleash/proxy-hosting.mdx

Adding links to definition of what frontend api is. Can be confusing for new users to read without seing what it is.

docs: proxy-hosting link to what frontend api is

---

website/docs/understanding-unleash/proxy-hosting.mdx

A benefit of hosting your own edge instance is that it will be as close to end users as you are.

docs: Clarify edge proximity to users

---

src/lib/addons/datadog-definition.ts
website/docs/reference/integrations/datadog.md

Datadog only supports know source_type_names, lets make that easy to figure out for the user.

feat: datadog integration - link to valid source type names

---

src/lib/db/access-store.test.ts
src/lib/db/access-store.ts
src/lib/services/access-service.test.ts
src/lib/services/access-service.ts
src/test/e2e/services/access-service.e2e.test.ts

This PR fixes the issue discussed in SR-234, where you would get a 200 OK response even if your POST request to `/api/admin/projects/<project-name>/access` contains invalid data (and nothing is persisted).

fix: return 400 on invalid POST data to project access endpoint

---

website/docs/reference/front-end-api.md

Proxy is superseeded by edge, lets compare to edge instead of the old proxy.

docs: Compare front-end api to edge, not proxy

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequestStatusBadge/ChangeRequestStatusBadge.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestStatusCell.tsx

Modifies the ChangeRequestStatusBadge to display the failed execution
Closes # [1-1767](https://linear.app/unleash/issue/1-1767/add-status-to-scheduled-badge)

Feat: show status of scheduled change request

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.test.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
frontend/src/component/changeRequest/changeRequest.types.ts

Adds an icon with a tooltip and changes the dot color to red for scheduled change requests 
Closes # [1-1768](https://linear.app/unleash/issue/1-1768/add-reason-and-icon-to-timeline)

feat: show failure reason for scheduled requests in timeline

---

frontend/package.json
src/server-dev.ts
test-migrations/Makefile
test-migrations/docker-compose.yml

This adds a Makefile to make it easy to test migrations from one version of Unleash to another. 
The script depends on [docker compose V2](https://docs.docker.com/compose/migrate/)
**Before starting**: make sure you're inside test-migrations folder and run `make clean` to be in a clean state.
We can run 2 versions of Unleash side by side with a shared database (the second version will apply migrations to the DB):
```shell
UNLEASH_DOCKER_IMAGE=unleashorg/unleash-server:5.6.10 make start-unleash # defaults to port 4242
UNLEASH_DOCKER_IMAGE=unleashorg/unleash-server:latest make start-another-unleash # defaults to port 4243
make test # run basic UI tests against port 4242 (first image)
EXPOSED_PORT=4243 make test # run basic UI tests against port 4243
```
This also enables us to test our …

chore: enable manual testing of migrations

---

frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

https://linear.app/unleash/issue/2-1683/feature-flag-add-a-new-incomingwebhooks-feature-flag-for-this-feature
Adds a new `incomingWebhooks` feature flag.

chore: add incomingWebhooks feature flag

---

frontend/src/interfaces/uiConfig.ts
src/lib/types/experimental.ts

Cleans up some leftover references to the `banners` feature flag. 
Related to https://github.com/Unleash/unleash/pull/5348

chore: clean up banners feature flag

---

src/lib/openapi/spec/user-schema.ts

I noticed I was getting warnings logged in my local instance when
visiting the users page (`/admin/users`)
```json
{
"schema": "#/components/schemas/publicSignupTokensSchema",
"errors": [
{
"instancePath": "/tokens/0/users/0/username",
"schemaPath": "#/components/schemas/userSchema/properties/username/type",
"keyword": "type",
"params": {
"type": "string"
},
"message": "must be string"
}
]
}
```
It was complaining because one of my users doesn't have a username, so
the value returned from the API was:
```json
{
"users": [
{
"id": 2,
"name": "2mas",
"username": null
}
]
}
```
This adjustment fixes that oversight by allowing `null` values for the username.

fix: make username nullable in user-schema

---

src/lib/features/feature-search/feature-search-store.ts
src/lib/features/feature-search/feature.search.e2e.test.ts

Two changes were needed to sort better
1. Since we are still using `last seen` from `features` table for backwards compatibility, we needed to add it to sort condition.
2. Nulls break the order, so now sorting nulls as last.

fix: last seen now sorts nulls last

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.test.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.styles.ts
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx

Show failure reason in change request overview
Closes [1-1769](https://linear.app/unleash/issue/1-1769/add-reason-and-icon-to-change-request-overview)

feat: show failure in cr overview

---

frontend/src/component/filter/Filters/Filters.tsx

When filters list is re-rendered a filter date item was always treated as a new element because of a missing key. New elements alway open on creation. This fix makes the identify of the date filter stable by adding a key.

fix: date filter item missing key

---

frontend/src/component/admin/users/UsersList/ResetPassword/ResetPassword.tsx
frontend/src/component/admin/users/UsersList/UsersActionsCell/UsersActionsCell.tsx
frontend/src/component/admin/users/UsersList/UsersList.tsx
frontend/src/hooks/api/actions/useAdminUsersApi/useAdminUsersApi.ts

This PR aims to add reset password to user manager. This will help those who do not intend to configure the email system.
I didn't find a test for this part of user management in the frontend. Do I need to do automated testing for this implementation?

feat: add reset password to user manager

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/hooks/usePlausibleTracker.ts

Adds plausible tracking with actions:
- scheduled-created
- scheduled-updated
- scheduled-rejected
- scheduled-applied
Closes # [1-1630](https://linear.app/unleash/issue/1-1630/add-plausible-metrics)

feat: add plausible tracking to scheduling

---

src/migrations/20231215105713-incoming-webhooks.js

https://linear.app/unleash/issue/2-1699/db-create-migration-for-a-new-incoming-webhooks-table
Adds a migration that creates 2 tables:
- `incoming_webhooks`
- `incoming_webhook_tokens`

chore: incoming webhooks and tokens migration

---

src/migrations/20231218165612-inc-webhook-tokens-rename-secret-to-token.js

Renames `secret` to `token` in `incoming_webhook_tokens` for consistency. This table is not being used yet, so this should be a very safe change.

chore: rename secret to token in incoming_webhook_tokens

---

src/lib/routes/admin-api/events.test.ts
src/lib/services/project-service.ts

Replaces #5509 
Changes the project access added event to list all users and groups added to each role instead of in root event.
- There are separate events that demonstrate access added, removed, etc for single instances of user and group, but none batched like this.
- Should this event be split up into one per instance of roleId? It kind of loses it's tie to a specific operation..

chore: list users and groups under each role in projectaccessadded event

---

package.json
src/test/e2e/api/openapi/openapi.e2e.test.ts

Replicate the change made to respect semver

chore: use semver compatible version

---

frontend/src/component/banners/Banner/Banner.test.tsx
frontend/src/component/banners/Banner/Banner.tsx

https://linear.app/unleash/issue/2-1760/prevent-banner-from-crashing-when-set-with-an-invalid-variant
This prevents the banner from crashing when set with an invalid variant. Instead, it default its styles to the default variant, which is `info`.
Also adds tests to validate our assumptions.

fix: prevent banner from crashing with invalid variant

---

frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/useFeatureToggleSwitch.tsx

Currently EnableEnvironmentDialog was loaded even if no feature was touched. Now it will only load, if feature toggle was selected.

fix: remove extra call to features on project load

---

frontend/src/component/common/Table/PaginatedTable/PaginatedTable.tsx

Table loaders were overflowing the sticky bar and footer. I moved the parent table into its own isolation context so that high z-index children don't escape it.

fix: move paginated table into isolation context

---

src/lib/types/events.ts

https://linear.app/unleash/issue/2-1748/create-new-incoming-webhook-events
Adds new events for write operations on incoming webhooks and their tokens.

chore: incoming webhook events

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/hooks/useLoading.ts

Removed `ref` dependency from `useLoading` hook, it was being overly reactive and breaking skeleton.

fix: now project overview has skeleton instead of placeholders

---

src/lib/services/context-service.ts

Now sortOrder and createdAt are not displayed on update.

fix: context updated event now does stores correct fields

---

frontend/src/component/common/AutocompleteBox/AutocompleteBox.tsx
frontend/src/component/common/ConstraintAccordion/ConstraintAccordionList/ConstraintAccordionList.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/FeatureStrategyConstraintAccordionList/FeatureStrategyConstraintAccordionList.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/FeatureStrategyConstraints.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.test.tsx
frontend/src/hooks/useWeakMap.ts

The ConstraintAccordionList component was used in multiple places: 
* Playground
* Segment form
* StrategyExecution
* Change requests
* Create strategy
* Edit strategy
This is problematic because some of the views are just pure visual representations, and other views allow you to interact with and edit the constraints. This causes a situation where the visual representation needs to be aware of the implementation details of editing and mutating constraints. In addition the ConstraintAccordionList is not just a pure rendering of the list, it also keeps internal state on when to show the create button and optional headers. This is makes it hard to make changes when stylings need to be subtly different across components. 
Taking on the full refactor for this is out of scope, but it's …

fix: separate concerns for ConstraintAccordionList

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx

Closes # [1-1813](https://linear.app/unleash/issue/1-1813/do-not-show-variants-table-in-change-request-when-no-variant-change)

fix: hide variant diff if no change in ChangeRequestOverview

---

frontend/src/openapi/models/featureTagSchema.ts
src/lib/db/feature-tag-store.ts
src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts
src/lib/openapi/spec/feature-tag-schema.ts
src/lib/schema/feature-schema.ts
src/lib/services/feature-tag-service.ts
src/lib/services/state-service.test.ts
src/lib/services/state-service.ts
src/lib/types/stores/feature-tag-store.ts
src/test/e2e/stores/feature-tag-store.e2e.test.ts
src/test/fixtures/fake-feature-tag-store.ts

Adds the new nullable column created_by_user_id to the data used by feature-tag-store and feature-tag-service. Also updates openapi schemas.

feat: implement column created_by_user_id in feature_tag

---

src/lib/util/extract-user.ts

With the recent changes it's common that we'll need both the id and processed username from the auth user in the request, so this PR provides some helper methods to simplify this.

chore: helper methods to extract user data from req

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx

Closes # [1-1825](https://linear.app/unleash/issue/1-1825/change-the-color-of-the-scheduled-and-pending-state-to-warningdark)

fix: review status title color

---

src/lib/services/email-service.ts

Fixes missing base url 
Relates to #[1-1827](https://linear.app/unleash/issue/1-1827/email-link-to-revive-feature-is-wrong)

fix: email link

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts
src/test/e2e/api/admin/project/projects.e2e.test.ts

Cherry picking last seen at fixes

fix: last seen cherrypick

---

src/lib/openapi/util/create-request-schema.ts
src/lib/openapi/util/create-response-schema.ts

This backwards compatible change allows us to specify a schema `id` (full path) which to me feels a bit better than specifying the schema name as a string, since a literal string is prone to typos.
```ts
requestBody: createRequestSchema(
'createResourceSchema',
),
responses: {
...getStandardResponses(400, 401, 403, 415),
201: resourceCreatedResponseSchema(
'resourceSchema',
),
},
```
```ts
requestBody: createRequestSchema(
createResourceSchema.$id,
),
responses: {
...getStandardResponses(400, 401, 403, 415),
201: resourceCreatedResponseSchema(
resourceSchema.$id,
),
},
```

chore: support full path schemas

---

website/docs/reference/change-requests.md

This commit updates the change request docs to talk about how the new
scheduled state works.
The subsection is marked as "in development", saying that it can
change at any moment until the feature is released.

docs: schedule change request docs, take 1

---

src/lib/features/export-import-toggles/export-import-service.ts

Some optional properties of `strategy` where not included after importing.
Internal issue: [SR-284](https://linear.app/unleash/issue/SR-284/wayfair-import-didnt-copy-title-of-strategies)

Fix: strategy import

---

src/lib/middleware/api-token-middleware.test.ts
src/lib/middleware/api-token-middleware.ts

This allows bulk metrics posted with a Client token to be accepted. Previously you needed an admin token to have bulk metrics accepted

Added a check that allows posting edge bulk metrics with a client token

---

src/lib/routes/edge-api/index.ts

We've had a couple of misunderstandings from people surprised that Unleash allows posts against the `/edge/validate` endpoint without an API key. It is intentional that this endpoint does not require an Authorization header, so this PR updates our OpenAPI spec to clarify that there is no security required for `/edge/validate`

chore: make security optional for /edge/validate endpoint

---

src/test/e2e/dedupe-permissions.e2e.test.ts
src/test/e2e/favor-permission-name-over-id.e2e.test.ts

Was having some trouble running these migration tests locally due to `dbm` not correctly picking up the passed in config. This fixes it by setting the custom config property after it has been initialized, always overriding any wrong values.
PS: I think I found the issue. `dbm` was prioritizing my `DATABASE_URL` for some reason, as I started having issues when it was set, and stopped having issues when I unset it. 
I still think this is a good change, as it prevents similar hard-to-debug issues in the future.
To help clarify this, running this locally:
- `export DATABASE_URL=postgres://unleash_user:passord@localhost:5432/unleash`
- `yarn test dedupe-permissions`
Fails on `main`, but passes on this branch. For some reason the `dbm` instance prioritizes whatever is set in `DATABASE_URL` …

test: specify custom config in dbm

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/EditChange.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/NewEditChange.tsx
frontend/src/component/common/ConstraintAccordion/ConstraintAccordionList/ConstraintAccordionList.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/NewFeatureStrategyForm.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.test.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/featureStrategyFormTestSetup.ts
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/NewFeatureStrategyEdit.test.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/NewFeatureStrategyEdit.tsx
frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx
frontend/src/hooks/usePlausibleTracker.ts

This PR refactores the StrategyVariants component to be passed in from the outside to the new form component. This allows us to pass in the StrategyVariants with an "editable" property in the create form which we use to determine the editable state of the name input field. If the editable field is not passed in we keep the old behavior. 
Notable changes:
* StrategyVariants is now passed in from the outside, allowing us to define different props at call time
* Added tests for the new behavior, and for keeping the old behavior (such as in edit strategy)
* Added tracking

feat: variant name change on create

---

src/migrations/20240102142100-incoming-webhooks-created-by.js

Creating an incoming webhook with an admin token means we can't correlate the action with a real user. In this case we should support null.

feat: support null created_by_user_id

---

src/migrations/20240102205517-observable-events.js

https://linear.app/unleash/issue/2-1773/db-create-migration-for-a-new-observable-events-table
Adds a new DB migration to create a new `observable_events` table. Even though we are thinking long term with the `source` columns, the short term purpose of this table will be to store incoming webhook calls.

chore: observable events db migration

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
frontend/src/utils/formatDate.ts

This pr uses the user's preferred timezone to display the scheduled times. If the user has no preferences, the default will be used.
With norwegian locale set as preference: 
With nothing set (falls back to my system setting):

chore: format schedule information according to user preferences

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestScheduledDialogs/ScheduleChangeRequestDialog.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestScheduledDialogs/changeRequestScheduledDialogs.tsx

This pr updates the text in some of the scheduling components to be more clear and consistent.

fix: update text in scheduling components

---

frontend/src/hooks/api/getters/useUiConfig/defaultValue.ts

We get a flash of the Unleash scaffold when we first load the page. For a brief moment, we display version 3 and then overwrite it with the correct version. Looks kinda silly, we know we're in version 5.x so let's just do that

chore: update default version in UI

---

frontend/vite.config.mts

After upgrading vite https://github.com/Unleash/unleash/pull/5703, small icons are not popping up anymore. Disabling inlining assets to make it work again.

fix: fix assets not showing up

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.styles.ts
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
frontend/src/component/changeRequest/ChangeRequestStatusBadge/ChangeRequestStatusBadge.tsx

This PR switches the notification icon to an exclamation mark (the Error icon). It updates three components:
1. The badge
2. The timeline
3. The review status
Screenshot with all the replaced icons

fix: use the correct icon for failed scheduled CRs

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/routes/edge-api/index.ts
src/lib/types/experimental.ts

As the title says. This adds a kill switch for the processing of Edge bulk metrics.
I was wondering if we should even add a kill switch fully around the router configuration as well, so that if the kill switch is already on when you start up you don't even map the route. WDYT?

task: add kill-switch for edge bulk metrics

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx

Aligns the icon to the end of the end of the box to make it match the text.
Also removes a redundant br element.

fix: align timeline icon for schedule failures

---

frontend/src/component/banners/Banner/Banner.tsx
frontend/src/component/banners/Banner/BannerDialog/BannerDialog.tsx
frontend/src/component/integrations/IntegrationHowToSection/IntegrationHowToSection.tsx

Adapts our current implementations of `ReactMarkdown` to always open markdown links in new tabs.

fix: adapts react markdown to open links in new tab

---

frontend/src/component/banners/Banner/Banner.tsx
frontend/src/component/banners/Banner/BannerDialog/BannerDialog.tsx
frontend/src/component/common/Markdown/Markdown.tsx
frontend/src/component/integrations/IntegrationHowToSection/IntegrationHowToSection.tsx

Iterates on https://github.com/Unleash/unleash/pull/5762
While on the previous PR we would always open markdown links on a new tab, we still want to navigate on the same tab when a relative link is specified.
This adds a new `Markdown` common component with this logic by default, which should make things a lot simpler and easier to maintain. The logic that was followed is similar to the existing internal/external links logic in our banners.

fix: properly handle markdown links

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/NewFeatureStrategyForm.tsx

This PR adds badges to display the amount of variants and constraints / segments.

feat: add badges to the new strategy configuration form

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/NewFeatureStrategyForm.tsx

Adds a conditional check so we don't display this tab for strategies that don't support it.

fix: add condition to show variants tab

---

src/lib/routes/client-api/register.test.ts
src/lib/routes/client-api/register.ts

Related to our work for making Edge bulk metrics a 1st class citizen of Unleash, this PR adds an X-Unleash-Version header to the response from client registration.
Based on when we add the new `/api/client/metrics/bulk` endpoint, Edge can use the response header from upstream to decide whether to post metrics to `/edge/metrics` or `/api/client/metrics/bulk`.

task: Add an X-Unleash-Version header to register response

---

frontend/src/component/App.tsx
frontend/src/component/demo/DemoBanner/DemoBanner.tsx
frontend/src/component/layout/MainLayout/MainLayout.tsx

This PR does 2 things:
- Fixes the `DemoBanner` zIndex to be the same as the sticky banners (no longer displays on top of modals)
- Moves the `Demo` wrapper to `App` instead of `MainLayout`, always displaying the demo banner before other banners

fix: demo banner zIndex, display on top

---

website/docusaurus.config.js
website/package.json
website/yarn.lock

This PR adds a zoom feature to the docs.
Interact with the images to blow them up to fill the screen. Still leaves the header for now, so some larger images are a bit wonky, but we can probably get around that.

docs: add image zoom to docs

---

src/migrations/20240108151652-add-daily-metrics.js

Business problem: we want to store up to 3 months of metrics data. Hourly storage is not feasible, so we go for the daily storage above 2 days.
Technical solution:
Adding 2 new tables to simulate time series DB in postgres. The idea is to store data in high resolution initially (the original tables) and then aggregate it to a lower resolution as it ages (2 new tables). 
The original metrics tables contain hourly data, the new tables will contain daily data. The structure is the same except from the timestamp column changing to date column.
Calculations for 90 days of data: https://gist.github.com/kwasniew/864bb6e5111b7de516b6e4454963d2d4#data-requirements-for-the-extended-90-days-scenario. New table should take twice as much space as the hourly table.
In the next PR I will create a …

feat: daily metrics db migration

---

src/lib/metrics.ts

This metric was used while developing the optimal304 feature. The feature flag has been removed and this data is not longer being collected and this will remove the metric from Prometheus.

fix: remove unsued metric 'optimal304DiffingCounter'

---

website/docs/using-unleash/deploy/configuring-unleash.md

This change adds a mention of frontend API tokens to the docs. We've
had this functionality for a while, but it appears not to have been documented.
Realized this as part of triaging #3005.

docs: describe frontend API tokens

---

src/migrations/20240109095348-add-reason-column-to-schedule.js

This PR adds a new `reason` column to the change request schedules table and populates it with the data that is in the `failure_reason` column. 
This is the expand phase of the expand/contract pattern. The code in enterprise will be updated to try and use the new column name, but fall back to the old one if no value is present.
The old column can be removed later.

chore: add `reason` column to change request schedule table

---

frontend/src/component/admin/roles/RolesPage.tsx
frontend/src/component/common/TabNav/TabLink.tsx
frontend/src/component/integrations/IntegrationList/AvailableIntegrations/AvailableIntegrations.tsx
frontend/src/component/integrations/IntegrationList/ConfiguredIntegrations/ConfiguredIntegrations.tsx
frontend/src/component/integrations/IntegrationList/IntegrationCard/IntegrationCard.tsx
frontend/src/component/integrations/IntegrationList/IntegrationList.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts
frontend/src/hooks/api/getters/useIncomingWebhooks/useIncomingWebhooks.ts

https://linear.app/unleash/issue/2-1823/adapt-integrations-page-to-incoming-webhooks-tab-layout
Adapts the current integrations page to the incoming webhooks feature, which includes things like:
- Displaying both configured and available integrations in a single "page block"
- Implement tabs
- Add "Incoming Webhooks" integration card
- Adapt the existing `IntegrationCard` component to support `onClick`
This also includes a small girl scouting fix: Some tabs (like on the roles page) did not correctly reflect the active tab.
Notice the new "Incoming webhooks" tab and integration card.

chore: adapt integrations layout for incoming webhooks

---

frontend/cypress/integration/import/import.spec.ts

Use the admin api to validate the feature toggle that has been imported.
This hopefully makes the test less fragile as we do not depend on the frontend to validate the import.

chore: validate import data using api

---

src/lib/types/core.ts

This change adjusts the exported `SYSTEM_USER` constant in `core.ts` to
match the one created in the migration in `src/migrations/20231222071533-unleash-system-user.js`
The slight discrepancy between these two caused me some minor headache
when trying to write a test in enterprise. 
It also removes the email because we have no inbox at that address (and we probably don't want one).
For reference, the migration looks like this:
``` sql
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT FALSE;
INSERT INTO users
(id, name, username, email, created_by_user_id, is_system)
VALUES
(-1337, 'Unleash System', 'unleash_system_user', 'system@getunleash.io', -1337, true);
```

chore: align the system user defined in `core.ts` with the one created in the migration

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/NewEditChange.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/NewFeatureStrategyForm.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.test.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyCreate/NewFeatureStrategyCreate.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/NewFeatureStrategyEdit.tsx
frontend/src/component/feature/StrategyTypes/NewStrategyVariants.tsx

This PR makes a change to how variants work in the new setup. Variants will now:
* Be removed if you change tab or unmount the component and it has no name
* Moved StrategyVariants into a separate component to isolate this change
* Add error handling around onSubmit and only trigger feedback if it's successful

fix: remove empty variants when changing tabs

---

src/lib/types/events.ts

Removes the SCHEDULED_CHANGE_REQUEST_EXECUTED event - replaced with CHANGE_REQUEST_SCHEDULED_APPLICATION_FAILURE, CHANGE_REQUEST_SCHEDULED_APPLICATION_SUCCESS events
Closes # [1-1900](https://linear.app/unleash/issue/1-1900/remove-old-schedule-executed-event)

chore: remove unused event

---

frontend/src/component/admin/roles/RolesPage.tsx
frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooks.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksActionsCell.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksDeleteDialog.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksTable.tsx
frontend/src/component/integrations/IntegrationList/IntegrationList.tsx
frontend/src/interfaces/incomingWebhook.ts

https://linear.app/unleash/issue/2-1817/ui-create-an-incoming-webhooks-configuration-page
This adds an incoming webhooks page with the respective table. We plan on possibly extending the table with a couple more columns in a future PR.
This allows us:
- View all configured incoming webhooks;
- Copy their URL to the clipboard;
- Remove them;
For "new" and "edit" operations we still need the incoming webhooks form/dialog, coming in a future PR.
**Note**: Even though we are showing the full URL in the table for now, we may end up truncating its start in the future (e.g. `.../api/incoming-webhook/<webhook-name>` - This decision depends on how it will look like after the rest of the columns are added.

chore: incoming webhooks table

---

src/migrations/20240111125100-automated-actions.js

Add tables to support automated actions based on the [design document](https://docs.google.com/document/d/15xPgn6B8gzMPk9RjMAUGu8XvozQ_45jjrsVl_Bm6Chg/edit?usp=sharinghttps://docs.google.com/document/d/15xPgn6B8gzMPk9RjMAUGu8XvozQ_45jjrsVl_Bm6Chg/edit?usp=sharing)

feat: add automated actions tables

---

frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.test.tsx
frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ChangeActions.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/FeatureChange.test.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/FeatureChange.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.test.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewers/ChangeRequestReviewers.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/ChangeRequestTitle.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequestTitle.test.tsx
frontend/src/component/changeRequest/ChangeRequestStatusBadge/ChangeRequestStatusBadge.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestStatusCell.tsx
frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/component/changeRequest/changesCount.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.test.tsx
frontend/src/component/feature/FeatureView/FeatureSettings/FeatureSettingsProject/FeatureSettingsProjectConfirm/FeatureSettingsProjectConfirm.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsCard.test.tsx
frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx
frontend/src/component/project/Project/ProjectInfo/ChangeRequestsWidget.tsx
frontend/src/hooks/api/getters/useChangeRequest/useChangeRequest.ts
frontend/src/hooks/api/getters/usePendingChangeRequests/usePendingChangeRequests.ts
frontend/src/hooks/api/getters/usePendingChangeRequestsForFeature/usePendingChangeRequestsForFeature.ts
frontend/src/hooks/useChangeRequestInReviewWarning.tsx

This changes the two interfaces IChangeRequest and IChangeRequestSchedule to be union types instead of interfaces. It also extracts the constituents of those union types into proper types themselves (so that they can be used in function type signatures etc). It also updates the type names.
This turned out to be more work than I had imagined, but I think the end result pays off, giving us more type safety and control. 
I wanted to use just `ChangeRequest` for the IChangeRequest type, but that caused issues due to naming collisions with the `ChangeRequest` component that we have, causing tests to fail. I've named it `ChangeRequestType` as a potential solution, but suggestions are welcome.
The relevant changes are in `frontend/src/component/changeRequest/changeRequest.types.ts`. Everything …

refactor: use union types for change request types

---

website/docs/reference/change-requests.md

This PR describes in closer detail what happens when the user who scheduled a change request is deleted. It mentions the new suspended state and what the user can do to get out of it.

docs: add a note about suspended change request schedules

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.test.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Introducing a new UI flag to control when to show old metrics. Separate backend flag will be used to start collecting metrics before we can show them.

feat: separate UI flag and backend flag for extended metrics

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetrics.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsChart/createChartData.ts
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsStats/FeatureMetricsStats.test.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/aggregateFeatureMetrics.test.ts
frontend/src/component/feature/FeatureView/FeatureMetrics/aggregateFeatureMetrics.ts
frontend/src/component/feature/FeatureView/FeatureMetrics/daysOrHours.ts
frontend/src/interfaces/featureToggle.ts

We want to add/aggregate metrics for the same timestamp instead of showing x different lines on top of each other
Also updated info about time settings:
* local time for hours
* UTC time for days

feat: aggregate metrics for the same timestamp

---

src/lib/features/maintenance/maintenance-service.ts
src/lib/features/scheduler/scheduler-service.test.ts
src/lib/features/scheduler/scheduler-service.ts
src/lib/services/scheduler-service.test.ts

Differentiate log lines so we can see if it happens on every call, or just on the initial call.

fix: differentiated interval and initial schedule call

---

src/lib/db/access-store.ts
src/test/e2e/services/access-service.e2e.test.ts

https://linear.app/unleash/issue/2-1844/fix-add-custom-root-roles-to-user-access-overview
I noticed our user access overview method did not take into account custom root roles, which meant only users with default root roles were being returned.
This changes the query to check for `IN ('root', 'root-custom')` instead, including both "root" and "custom root" roles.

fix: include custom root roles in user access overview

---

frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksActionsCell.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksTable.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksTokensCell.tsx
frontend/src/interfaces/incomingWebhook.ts

https://linear.app/unleash/issue/2-1827/add-remaining-columns-to-the-incoming-webhooks-table
Adds the "tokens" column to the incoming webhooks table.
Also includes some slight adjustments to the table, including a fix to center the actions button.

chore: add tokens column to incoming webhooks table

---

src/lib/features/access/createAccessService.ts
src/lib/features/dependent-features/createDependentFeaturesService.ts
src/lib/features/events/createEventsService.ts
src/lib/features/export-import-toggles/createExportImportService.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/features/group/createGroupService.ts
src/lib/features/project-environments/createEnvironmentService.ts
src/lib/features/segment/createSegmentService.ts
src/lib/features/tag-type/createTagTypeService.ts
src/lib/services/access-service.test.ts

EventsService is a dependency in most of our services. This creates helper methods to create them easily and replace a few places where we're creating them manually

chore: centralize events service creation

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/NewEditChange.tsx
frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/component/common/ConstraintAccordion/ConstraintAccordionList/createEmptyConstraint.ts
frontend/src/component/common/NewConstraintAccordion/NewConstraintAccordionList/NewConstraintAccordionList.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/NewFeatureStrategyEdit.tsx
frontend/src/interfaces/strategy.ts

This PR adds uuids as ids using a symbol in order to make sure we only use this to keep internal order in the viritual DOM. This makes us able to have predictable mutable lists on the frontend, and makes it easy to not pass this property along to the backend.

fix: add symbols as constraint ids

---

src/lib/db/client-metrics-store-v2.test.ts
src/lib/db/client-metrics-store-v2.ts
src/lib/features/instance-stats/instance-stats-service.ts
src/lib/services/client-metrics/metrics-service-v2.test.ts
src/lib/services/client-metrics/metrics-service-v2.ts
src/lib/types/stores/client-metrics-store-v2.ts
src/test/fixtures/fake-client-metrics-store-v2.ts

Prevent repeated calculation of previous day daily metrics. E.g. when multiple pods start calculation only the first pod should calculate the metrics.
Details:
* adding new method to count how many daily metrics buckets we have for the previous day
* heuristic: if we have more than count of hourly buckets / 24 of daily buckets then we do not proceed with daily metrics calculation
* added 3 test scenarios: too many hourly buckets, daily metrics already calculated and happy path calculate new daily metrics

feat: prevent double daily metrics insert

---

frontend/src/component/admin/auth/AutoCreateForm/AutoCreateForm.tsx
frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx
frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx

This improves the role resolution in the value of the default root role, preventing a bug where settings saved pre-https://github.com/Unleash/unleash/pull/5887 would show an empty default root role in the dropdown.
Also makes the role update more robust.

fix: improve SSO default role resolution

---

src/lib/types/core.ts
src/migrations/20240116154700-unleash-admin-token-user.js

This admin token user will help us differentiate actions performed by the system from actions performed with an admin token.
Events created with an admin token should have the id of this user as createdByUserId property and the username of the token used as the createdBy property. i.e.
```json
{
"id": 11,
"type": "pat-created",
"createdBy": "admin-token",
"createdAt": "2024-01-16T13:16:27.887Z",
"createdByUserId": -42,
"data": {
"description": "admin-pat",
"expiresAt": "2024-02-15T13:16:25.586Z",
"secret": "***",
"userId": 1
},
"preData": null,
"tags": [],
"featureName": null,
"project": null,
"environment": null
}
```

chore: add another system user for admin tokens

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetrics.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/useExtendedFeatureMetrics.ts

Select applications from the longest time span. Previously it was 48 hours. Now it's 3 months. Without this fix we're not showing all app names for longer time spans.

fix: metrics apps should be selected from the longest time span

---

frontend/src/component/admin/apiToken/ApiTokenForm/useApiTokenForm.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/routes/admin-api/api-token.test.ts
src/lib/routes/admin-api/api-token.ts
src/lib/types/experimental.ts

Since we've now added PAT's we really do recommend switching to those, or for enterprises, we recommend using service accounts. 
Admin tokens have an obvious disadvantage in that they're not connected to any user, so actions performed by them are harder to audit.
This PR adds a killswitch for turning it off, in preparation for deprecating them and ultimately removing them in the future.

feat: added killswitch for admin tokens

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetrics.tsx

We cannot select apps from the longest timespan (3 months) since we may have new app names in the last 24h that are not present in the longer timespan yet. So I decided to recalculate default application when the list of available applications changes.

fix: select default application based on timespan

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/FeatureStrategyConstraints.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx
src/lib/services/email-service.ts
src/mailtemplates/scheduled-change-conflict/scheduled-change-conflict.html.mustache
src/mailtemplates/scheduled-change-conflict/scheduled-change-conflict.plain.mustache

Makes the schedule conflict email button conditional to having the link present.
Closes # [1-1950](https://linear.app/unleash/issue/1-1950/modify-the-template-to-make-the-new-button-conditional)

fix: make the conflcit email template button conditionally render

---

website/docs/reference/api-tokens-and-client-keys.mdx

We want to deprecate and eventually remove the option for admin tokens. This PR updates the docs to inform readers about the deprecation as well as recommending what they can use instead.

docs: add deprecation notice to Admin tokens

---

src/lib/features/scheduler/scheduler-service.test.ts
src/lib/features/scheduler/scheduler-service.ts
src/lib/metrics.ts
src/lib/services/scheduler-service.test.ts

So, this was causing a lot of ERROR in our logs, due to the metric having gotten an extra label the last month.
Two things for this fix.
1. add the missing label to the two calls that did not have it added
2. update the log line to include the error as another argument to the logger, so we actually get a stacktrace from the error.

fix: feature toggle update total needs 4 labels

---

frontend/src/component/project/Project/Project.tsx

Bug: loaders in the table were cancelled before data arrived
Root cause:
Solution:
Give a loader at the top level (in Project) a very specific identifier for things it should load so that very deeply nested loaders are not affected and can have their local loading hooks.

fix: table loader

---

frontend/src/component/admin/banners/BannerModal/BannerForm.tsx
frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountModal/ServiceAccountTokens/ServiceAccountTokens.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/IncomingWebhooksForm.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/IncomingWebhooksFormURL.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/IncomingWebhooksTokens/IncomingWebhooksTokens.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/IncomingWebhooksTokens/IncomingWebhooksTokensCreateDialog.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/IncomingWebhooksTokens/IncomingWebhooksTokensDialog.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksForm/useIncomingWebhooksForm.ts
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksModal.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksTable.tsx
frontend/src/component/integrations/IntegrationList/AvailableIntegrations/AvailableIntegrations.tsx
frontend/src/hooks/api/actions/useIncomingWebhookTokensApi/useIncomingWebhookTokensApi.ts
frontend/src/hooks/api/actions/useIncomingWebhooksApi/useIncomingWebhooksApi.ts
frontend/src/hooks/api/getters/useIncomingWebhookTokens/useIncomingWebhookTokens.ts

https://linear.app/unleash/issue/2-1818/ui-create-incoming-webhook-newedit-modal
Adds the incoming webhooks modal form, which allows users to create and edit incoming webhooks, along with their respective tokens.
Follows a logic similar to service accounts and their tokens, and tries to use the newest form validation flow that we implemented in the roles form.

Chore inc webhooks modal form

---

src/migrations/20240118093611-missing-primary-keys.js

Follow up of https://github.com/Unleash/unleash/issues/4303
We are adding primary keys to all tables missing them, currently **role_permission**, **api_token_project**, and **project_stats**. 
By adding primary keys, the issue with migrations failing during upgrades in replicated database setups will be resolved.

feat: add primary keys to missing tables

---

src/lib/middleware/pat-middleware.test.ts
src/lib/middleware/pat-middleware.ts

chore: add types to pat middleware

---

frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.test.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx

If user types invalid hoursBack into the URL it always goes back to a default value of 48 hours. It prevents UI from freezing when someone tinkers with the URL.

fix: normalize hours back to prevent freezing UI

---

src/lib/features/scheduler/scheduler-service.test.ts
src/lib/features/scheduler/scheduler-service.ts
src/lib/metrics.ts
src/lib/services/scheduler-service.test.ts

So, this was causing a lot of ERROR in our logs, due to the metric having gotten an extra label the last month.
Two things for this fix.
1. add the missing label to the two calls that did not have it added
2. update the log line to include the error as another argument to the logger, so we actually get a stacktrace from the error.

fix: feature toggle update total needs 4 labels (#5946)

---

src/lib/routes/admin-api/api-token.ts
src/lib/routes/admin-api/project/api-token.ts
src/lib/util/extract-user.test.ts
src/lib/util/extract-user.ts

Applies a fix that is already in main with some modifications to adapt it to 5.8 release

fix: create tokens createByUserId

---

src/lib/metrics.ts
src/lib/util/metrics/createCounter.ts
src/lib/util/metrics/createGauge.ts
src/lib/util/metrics/createSummary.ts
src/lib/util/metrics/index.ts

https://linear.app/unleash/issue/2-1856/add-typesafe-wrappers-over-prom-clients-metrics
As discussed on the latest knowledge sharing session, this adds typesafe wrappers over prom client's metrics, requiring us to specify all the configured labels for each metric.
This uses a functional approach and only exposes the methods that are currently relevant to us, while also exposing the underlying instance of the metric for an easy access if needed.
Since we often chain `labels` with `inc` in counters, this adds a convenience `increment` method for counters which does both in a single call.

refactor: add typesafe wrappers for prom client metrics

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/strategy-change-diff-calculation.test.ts
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/strategy-change-diff-calculation.ts
frontend/src/component/changeRequest/changeRequest.types.ts

A strategy title can be either an empty string or undefined on the
type we use in the frontend. In the snapshot it can be an empty
string, null (presumably), and undefined.
This change updates the diffing logic to handle the various title diff
cases correctly. It also updates the type used for the snapshot to reflect this.

fix: handle title diffing correctly in strategy change diffs

---

frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.test.tsx
frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.tsx

This PR hides the "snapshot" data from the diff overview we show in the UI in a change request.

Chore: omit snapshot property from event payload

---

frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/FeaturesCell.tsx

This PR adds the `key` property to the features cell component where it renders lists of flags. This fixes a few rendering errors we've been getting in the console.

fix: add keys to the features cell component

---

frontend/src/component/common/Badge/Badge.tsx

This changes the badge element to prefer spans instead of divs. The
primary difference between spans and divs is that spans are inline and
divs are block. Styling-wise, we override the display property anyway.
Semantically, most all of the badges are used inline instead of on
their own block level, so this change seems sensible. You can still
provide `div` as the `as` prop if you need to.

refactor: prefer 'span' to 'div' in the badge element

---

src/migrations/20240119171200-action-states.js

Add action states table without an index yet

feat: add action states

---

src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/services/access-service.ts

This was spotted while testing automated actions. Steps to reproduce:
1. Add an editor user
2. Get a PAT for the editor user
3. As Admin create a feature in a project where the editor user is not a member and enable the feature
4. Try using the editor's PAT to modify the feature: ```$ curl -XPOST -H 'Authorization: user:editor-pat' https://sandbox.getunleash.io/enterprise/api/admin/projects/gaston-editor/features/editor-feature/environments/development/off | jq
{
"id": "444d157c-dd85-4953-afec-781cde9d029f",
"name": "PermissionError",
"message": "You don't have the required permissions to perform this operation. To perform this action, you need the \"UPDATE_FEATURE_ENVIRONMENT\" permission.",
"details": [
{
"message": "You don't have the required permissions to perform this operation. To …
```

fix: unauthorized disable feature

---

frontend/src/component/feedbackNew/FeedbackComponent.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/routes/admin-api/config.ts
src/lib/types/experimental.ts

This PR will allow us to use a feature flag with variants to control whether or not we should show the comments field of the feedback form. This will allow us to see whether we can increase feedback collection if we reduce the load on the customer.

feat: add option to use variants with feedback

---

src/lib/server-impl.ts

We should use the enhanced flagResolver
Tested locally:
```
9:44:13 AM - Starting compilation in watch mode...
[dev:backend] 
[dev:backend] 
[dev:backend] 9:44:26 AM - Found 0 errors. Watching for file changes.
[dev:backend] [2024-01-23T09:44:27.498] [INFO] server-impl.js - DB migration: start
[dev:backend] [2024-01-23T09:44:27.499] [INFO] server-impl.js - Running migration with lock
[dev:backend] [2024-01-23T09:44:29.884] [INFO] server-impl.js - DB migration: end
```

fix: enabled lock check

---

src/lib/types/option.ts

This option is not referenced in the code
I believe its original intent was to be able to override flagResolver, but it's currently not being used:
https://github.com/Unleash/unleash/blob/a46f54f48afffdaf06126fa2998e61280dee03a3/src/lib/create-config.ts#L490-L491
Instead, we're using `experimental`, `flags`, and `externalResolver`
https://github.com/Unleash/unleash/blob/a46f54f48afffdaf06126fa2998e61280dee03a3/src/lib/create-config.ts#L64-L73
https://github.com/Unleash/unleash/blob/f63581c03a3bd2d520f26c900876f88246fe88d2/src/lib/util/flag-resolver.ts#L12-L20

chore: remove flagResolver option

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts

Adds "Unleash" to the "noreply@getunleash.io" for default email sender

fix: add unleash to default email sender string

---

src/migrator.ts

This outputs to console.log but should be indexable:

chore: This helps output the migrations being applied

---

website/docs/feature-flag-tutorials/react/examples.md
website/docs/understanding-unleash/unleash-overview.md

docs: Minor typos

---

frontend/src/component/common/PermissionGuard/PermissionGuard.tsx

I noticed some manual `hasAccess` usages in permission guards due to the fact that `PermissionGuard` does not accept `project` and `environment`. This PR adds this support to `PermissionGuard` so we can adapt these `hasAccess` checks to use it instead, adding consistency and cleaning things up.
This PR does not include these adaptations however, it only adds the optional properties to the component. We can address these at a later point.

chore: add support for project and environment in PermissionGuard

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/strategy-change-diff-calculation.test.ts
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/strategy-change-diff-calculation.ts

This PR fixes a bug in the displayed value of the conflict list so that it shows the value it would update to instead of the snapshot value.
In doing so, it updates the logic of the algorithm to:
1. if the snapshot value and the current value are the same, it's not a conflict (it's an intended change)
2. If the snapshot value differs from the current value, it is a conflict if and only if the value in the change differs from the current value. Otherwise, it's not a conflict.
The new test cases are:
- it shows a diff for a property if the snapshot and live version differ for that property and the changed value is different from the live version
- it does not show a diff for a property if the live version and the change have the same value, even if the snapshot differs from the live version …

fix: show the updated value instead of the snapshot value

---

src/lib/util/flag-resolver.test.ts
src/lib/util/flag-resolver.ts

https://linear.app/unleash/issue/2-1880/fix-flag-resolver-getvariant-behavior
Fixes the flag resolver `getVariant` behavior when there's a variant object set in `experimental` - The flag resolver should call the external resolver `getVariant` when not overridden to be true, even if set as variant object in `experimental`.
Related: https://github.com/Unleash/unleash/pull/3808

fix: flag resolver get variant

---

frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.test.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx
frontend/src/hooks/usePlausibleTracker.ts

Adding tracking for 2 views, when users use the new search. 
For features view and project view.

feat: track search bar events

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/routes/edge-api/index.ts
src/lib/types/experimental.ts

Previously we used a killswitch and returned 404 if the feature was enabled. This flips that to a default disabled toggle, that has to be turned on to handle old Edge (pre 17.0.0) posting bulk metrics

task: Make /edge/metrics toggleable by toggle

---

frontend/src/component/App.tsx
frontend/src/component/banners/EdgeUpgradeBanner/EdgeUpgradeBanner.tsx
frontend/src/component/banners/internalBanners/InternalBanners.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/db/client-instance-store.ts
src/lib/features/metrics/instance/instance-service.ts
src/lib/routes/admin-api/config.test.ts
src/lib/routes/admin-api/config.ts
src/lib/types/stores/client-instance-store.ts
src/test/fixtures/fake-client-instance-store.ts

Only triggers if there is any rows in client instances that have
sdk_version: unleash-edge with version < 17.0.0
The function that checks this memoizes the check for 10 minutes to avoid scanning the client instances table too often.

task: Add banner encouraging edge upgrade

---

website/docs/feature-flag-tutorials/react/examples.md
website/sidebars.js

Let's update our tutorial titles in the left navigation menu so it's shorter and simpler.
This will _not_ change the metadata and doc titles when you click on them. Only the label in the nav.
BEFORE
AFTER
Closes #

Shorter nav names for tutorials while maintaining SEO titles

---

src/lib/features/index.ts
src/lib/features/instance-stats/createInstanceStatsService.ts
src/lib/services/index.ts
src/test/e2e/api/admin/instance-admin.e2e.test.ts
src/test/e2e/helpers/database-init.ts

Ability to create a dependency graph of the instance stats service in one method call. This PR shows high coupling to 10+ stores we have in this part of the code.

Instance stats service composition root

---

src/lib/db/feature-environment-store.ts
src/test/e2e/stores/feature-environment-store.e2e.test.ts

Fixes 2 bugs
- Strategy variants
- Feature env variants 
not being cloned when cloning an environment
Closes # [SR-350](https://linear.app/unleash/issue/SR-350/cloning-environment-does-not-clone-variants-or-strategy-variants)
Manual test verifies the fix

fix: clone variants (featureEnv and strategy) when cloning an env

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActions.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsActionsCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsActorCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsDeleteDialog.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsFiltersCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTable.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTableActionsCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTriggerCell.tsx
frontend/src/hooks/api/actions/useActionsApi/useActionsApi.ts
frontend/src/interfaces/action.ts

https://linear.app/unleash/issue/2-1877/ui-add-actions-table
Implements the new project actions table.

chore: project actions table

---

src/lib/db/client-instance-store.ts

This escape with `??` double escaped the LIKE query causing no results. This updates to using whereLike, which does the correct escaping for string query.

fix: Use knex whereLike instead of whereRaw to fix escaping

---

src/lib/error/archivedfeature-error.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts

Creates a new ArchivedFeatureError.
Throw this error when trying to toggle a feature environment for an archived feature.  
Closes https://github.com/orgs/Unleash/projects/8/views/1?pane=issue&itemId=51242922

fix: return 400 when enabling env of archived toggle

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/feature-toggle/feature-toggle-store.ts
src/lib/types/experimental.ts
src/test/config/test-config.ts

Sets data migration of features and events created_by_user_id to disabled by default

chore: default the data migration flag for createdbyuserid to false

---

src/migrations/20240125090553-events-fix-incorrectly-assigned-sysuser-id.js

We had a bug that would set created_by_user_id = -1337 even for some events that had an actual user, and the created_by would be the users email. To fix the data this PR introduces a migration that simply sets created_by_user_id to null when created_by is not the unleash system user but the created_by_user_id is. The other scheduled jobs should pick this up and assign the correct user id
The EXPLAIN of the previous version of this query with the created_by filter looking like this: `created_by NOT IN ('system_user', 'unleash_system_user', 'system@getunleash.io')` indicated that it would scan indexes and be fairly efficient

chore: add a migration that removes incorrectly set sysuserid

---

CODEOWNERS

Now that Drew isn't at Unleash anymore, he probably doesn't want to get review requests for docs stuff anymore 💁

chore: remove drew as a codeowner for docs

---

src/lib/db/index.ts
src/lib/features/events/createEventsService.ts
src/lib/features/events/event-created-by-migration.test.ts
src/lib/features/events/event-service.ts
src/lib/features/events/event-store.test.ts
src/lib/features/events/event-store.ts
src/lib/features/export-import-toggles/createExportImportService.ts
src/lib/features/instance-stats/createInstanceStatsService.ts
src/lib/features/project/createProjectService.ts
src/lib/features/scheduler/schedule-services.ts
src/lib/types/stores/event-store.ts
src/test/fixtures/fake-event-store.ts

Schedules a best-effort task setting the value of events.created_by_user_id based on what is found in the created_by column and if it's capable of resolving that to a userid/a system id. The process is executed in the events-store, it takes a chunk of events that haven't been processed yet, attempts to join users and api_tokens tables on created_by = username/email, loops through and tries to figure out an id to set. Then updates the record.
1. There's potentially a lot of events to process so this can go on for quite some time. We don't need this specifically for anything, so that should be fine. Currently set at 100 records every 2mins, open to suggestions on better frequency/update counts.
2. unknown, migration, init-api-tokens get translated to system user
3. Events with `created_by = …

chore: events created by userid migration

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts
frontend/src/utils/unique-change-request-id.ts

Added conflict count to CR metrics and CR id.
Something to think about:
There was idea that we can aggregate this data based on CR id, but CR id is just a number from 0 to x. So it will not be unique across instances.

feat: add CR id to plausible events

---

src/lib/features/feature-toggle/archive-feature-toggle-controller.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/playground/playground.ts
src/lib/features/private-project/privateProjectStore.ts
src/lib/features/segment/segment-controller.ts
src/lib/routes/admin-api/context.ts
src/lib/routes/admin-api/metrics.ts
src/lib/types/no-auth-user.ts

We were sending `user.id` to the service, but if an admin token is used, there is no `user.id.` Instead, there is `user.internalAdminTokenUserId`. so we need to use the special method `extractUserIdFromUser`.
This PR adds this implementation, and now the service correctly retrieves the appropriate ID for admins.
Related to: https://github.com/Unleash/unleash/pull/5924

fix: admin token should be passed forward from controllers 

---

website/docs/contributing/ADRs/back-end/breaking-db-changes.md

- **Separation of Migrations in PRs**: Migrations are now required to be carried out in separate pull requests. This change is intended to improve the monitoring and management of database schema changes during deployment.
- **Primary Key Requirement for New Tables**: A new paragraph mandates the inclusion of primary keys in all new tables, emphasizing the importance of data integrity, efficient data retrieval, and supporting table relationships. Additionally, by adding primary keys, we resolve the issue of migrations failing during upgrades in replicated database setups, as we are not using PostgreSQL replica identities. Exceptions to this rule require a compelling justification.
Also added better structuring and styling to ADR for better readability.

chore: update database migration ADR

---

frontend/src/component/admin/license/License.tsx
frontend/src/hooks/api/getters/useLicense/useLicense.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

- Shows the instanceName from the license
- add new feature flag `enableLicenseChecker` used to enforce a valid license.

fix: add instanceName to license display

---

src/migrations/20240130104757-flag-trends-health-time-to-production.js

Adding health and time_to_production columns to long term flag trends. Types are derived from the project and project_stats tables.  time_to_production is derived from the project_stats average time to production in the current window. Since in the context of trends we don't distinguish between current, previous and time_to_production is always avg for a project I decided to use a simple name.

feat: migration for health and time_to_production in flag trends

---

src/lib/features/scheduler/scheduler-service.test.ts
src/lib/features/scheduler/scheduler-service.ts

Adding scheduler init jitter to avoid too many DB operations running at once. Subsequent runs are not affected.
* default jitter calculated so that we don't need to change code using scheduler
* default jitter is 2s-30s
* if any scheduler runs more often than max jitter time (30 seconds) then no jitter is applied
* you can explicitly opt-out of jitter by passing 0ms jitter

feat: scheduler init jitter

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/FlagStats/FlagStats.tsx
frontend/src/component/executiveDashboard/FlagsChart/FlagsChartComponent.tsx
frontend/src/component/executiveDashboard/UserStats/UserStats.tsx
frontend/src/component/executiveDashboard/UsersChart/UsersChartComponent.tsx
frontend/src/component/executiveDashboard/Widget/Widget.tsx

- unified "Widget" component
- column order dependent on screen width

feat: executive dashboard responsive grid

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/FlagsChart/FlagsChartComponent.tsx
frontend/src/component/executiveDashboard/FlagsProjectChart/FlagsProjectChart.tsx
frontend/src/component/executiveDashboard/FlagsProjectChart/FlagsProjectChartComponent.tsx
frontend/src/hooks/api/getters/useExecutiveSummary/useExecutiveSummary.ts
frontend/src/openapi/models/executiveSummarySchema.ts
frontend/src/openapi/models/executiveSummarySchemaProjectFlagTrendsItem.ts
frontend/src/openapi/models/index.ts

This PR adds project flags line chart component

feat: add project flags component

---

website/src/css/custom.css

Sets the opacity of the navbar separators to 0.3

docs: make navbar separators partially transparent

---

website/package.json
website/yarn.lock

Reverting https://github.com/Unleash/unleash/pull/5819, because it is breaking docs

chore: revert docusaurus-plugin-openapi-docs

---

frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx

The `FeatureToggleListTable` is nested directly within `PageContent`. `PageContent` was cause for removing the skeleton from the table. However, this is unnecessary because the table has its own loader that manages the skeletons. Therefore, `PageContent` does not require a loader.

fix: fix skeleton not appearing on feature toggle list

---

src/lib/features/events/event-created-by-migration.test.ts
src/lib/features/events/event-service.ts
src/lib/features/events/event-store.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/features/feature-toggle/fakes/fake-feature-toggle-store.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/feature-toggle-store.ts
src/lib/features/feature-toggle/types/feature-toggle-store-type.ts
src/lib/metric-events.ts
src/lib/metrics.ts
src/lib/services/addon-service.test.ts
src/lib/services/state-service.test.ts
src/lib/types/stores/event-store.ts
src/test/e2e/api/admin/event.e2e.test.ts
src/test/e2e/features-created-by-user-id-data-migration.e2e.test.ts
src/test/fixtures/fake-event-store.ts

the created_by_user_id data migration from resolving events.created_by (for both events and features) now emits events on how many rows were updated.
Adds listeners for these events that records these metrics with prometheus

chore: scheduled created-by migrations metrics

---

website/sidebars.js
website/src/css/custom.css

This change adds links to Unleash Academy from the docs sidebar and
vice versa when the nav bar is collapsed (on narrow screens).

docs: show links to other sidebars when the navbar is collapsed

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/strategy-change-diff-calculation.ts

We had to make some updates to let the compiler know about the types and fix an issue with nested objects not being compared as objects (instead as strings), but this saves us a few lines and is hopefully more readable.

refactor: take chatgpt's suggestions for diff calc algorithm

---

src/lib/features/maintenance/maintenance-service.ts
src/lib/services/version-service.ts

Usually maintenance mode is disabled. If the call throws, which we see a lot of when a unleash instance is in terminating state, we should return a default value.
By having it throw inside of the memoizee function, the response is not cached, and it will trigger new calls until it return a cachable result.

fix: maintenance mode should assume disable if db call fails.

---

src/lib/db/feature-tag-store.ts
src/lib/features/client-feature-toggles/client-feature-toggle-store.ts

Queries on client-feature-toggle store have many purposes depending on the requestType, making the query more complex or not depending on the use case. Also, each use case has different frequencies (i.e. playground is expected to be used rarely).
The name for the store metrics was wrong, copy&pasted from:
https://github.com/Unleash/unleash/blob/7b04db054793a03e12bd92a53c24d5feb40c561d/src/lib/features/feature-toggle/feature-toggle-store.ts#L107
Which was also present in feature-tag metrics:
https://github.com/Unleash/unleash/blob/7b04db054793a03e12bd92a53c24d5feb40c561d/src/lib/db/feature-tag-store.ts#L37
With this, we'll have more granularity to understand the execution time and frequency of each

chore: split metrics by request type

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChangeOverwriteWarning.tsx
frontend/src/component/changeRequest/ChangeRequestContext.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts

Use React's context to track how many CRs are moved into their next state with conflicts present.
This PR wraps environment change requests and change request overviews in a change request plausible context that contains a `willOverwriteStrategyChanges` property. This property is updated by the diff calculation if there are any conflicts and then read by the `changeState` function in the `useChangeRequestApi` hook. 
As long as at least one of the strategies in the CR contain conflicts, it will be marked as overwriting changes.

chore: track metrics for how many CRs are moved into next state with conflicts

---

src/lib/features/scheduler/scheduler-service.ts

When a stop signal is sent to Unleash the scheduler-service should cancel any scheduled jobs. This also applies to the job scheduled for initial execution with jitter.
We observed that initial jobs was executed after the database connections are terminated. This appears after v5.9.0 of Unleash. 
```
Error: aborted
at Object.queryBuilder (/unleash/node_modules/knex/lib/knex-builder/make-knex.js:112:26)
at createQueryBuilder (/unleash/node_modules/knex/lib/knex-builder/make-knex.js:320:26)
at EventStore.knex [as db] (/unleash/node_modules/knex/lib/knex-builder/make-knex.js:101:12)
at EventStore.setUnannouncedToAnnounced (/unleash/node_modules/unleash-server/dist/lib/features/events/event-store.js:286:33)
at EventStore.publishUnannouncedEvents …
```

fix: schduler-service graceful shutdown

---

src/lib/features/instance-stats/instance-stats-service.ts
src/lib/routes/admin-api/config.ts
src/lib/services/version-service.test.ts
src/lib/services/version-service.ts

In the beginning we used process.nextTick() as a trick to load some data initally in the constructor of a service.
This is a bad pattern and we should generally avoid any async operations in the constructor. Today we have two alternatives:
1. Defer loading until data is needed (wrap it in async)
2. Use the schdule-service.

fix: version-service should not use process.nextTick

---

website/docs/using-unleash/deploy/configuring-unleash.md

So we have a place in the docs to refer users struggling with getting metrics from Edge after upgrade to Unleash v5.9.0, this PR adds a small troubleshooting note about two fixes. 
1. Upgrade Edge
2. Use environmental flag to re-enable old endpoint

docs: Add troubleshooting note about missing Edge metrics

---

website/docusaurus.config.js
website/src/css/custom.css

This change hides the quickstart and doc nav bar links when you're on
the docs pages.
This gets around the issue of both of those links being
highlighted when you're on the docs pages.
This should work on  91.66% of browsers (according to [canIUse's data for the `:has` selector](https://caniuse.com/?search=%3Ahas)). For older browsers, the links will still be visible.

docs: hide the quickstart and doc nav bar links when you're on the docs pages

---

.github/workflows/codeql-analysis.yml

We're getting deprecation warnings, and I checked the migration, the major change is node 16 -> node 20. since node 16 runners will be deprecated by Github sometime this year.

chore: update codeql tasks to v3 to remove deprecation warnings

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

We need to turn it false, because if it is true, it will not get any variants.
This solution is hacky, but good for now.

fix: default featureSearchFeedback to false

---

package.json
src/lib/proxy/proxy-repository.ts
yarn.lock

Upgrading Node SDK to a version with double start prevention. We already prevent the issue at the call site but now the SDK is also immune to the problem. Using beta version for now so that we can dogfood.

feat: sdk with double start prevention

---

src/lib/services/email-service.ts
src/mailtemplates/scheduled-change-conflict/scheduled-change-conflict.html.mustache
src/mailtemplates/scheduled-change-conflict/scheduled-change-conflict.plain.mustache

This PR updates the change request email sending method to handle the recent changes we have made. That means that the email now:
- says that change requests have been suspended instead of saying that application will fail.
- handles cases where segments or strategies have been updated causing potential conflicts.
I have updated the email templates and made some adjustments to the email sending method. To make the transition from one to the other easier, I have kept the original method as an interim solution until enterprise has switched over.

chore: update schedule emails to handle suspensions and segment updates

---

frontend/src/component/changeRequest/ChangeRequestConfirmDialog/ChangeRequestConfirmDialog.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestRejectDialog/ChangeRequestRejectDialog.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestScheduledDialogs/ChangeRequestScheduledDialog.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestScheduledDialogs/ScheduleChangeRequestDialog.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/MultiActionButton/MultiActionButton.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/useFeatureToggleSwitch.tsx
frontend/src/hooks/useChangeRequestToggle.ts

Simulation on Slow 3G:
https://github.com/Unleash/unleash/assets/1394682/a32df02b-a28e-4bea-891d-a62148673fb3
* low on abstraction (disabled state close to the async workflow that can set state changes)
* mark async steps that matter for the disabled state with await. disabled can stay disabled for a duration of a few async operations (e.g. update CR state and read new CR state)
* keep the disabled state handling close to the async operations that affect it and pass the operations and disabled state to components that need them
* async operations are only for the internal operations ordering within the long running operation. We should keep passing void returning functions to components so that they're not tempted to await on the actions.
So async action used for …

feat: add disabled state handling on slow network

---

website/docs/reference/change-requests.md

This change updates the change request scheduling docs to include
information about what happens when a strategy or segment is updated
in the background, as well as updated information about the emails
that it sends out.

docs: update change request doc to mention strategy/segment suspension

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTable.tsx
frontend/src/hooks/api/getters/useIncomingWebhooks/useIncomingWebhooks.ts

React can sometimes be non-intuitive and behave erratically due to the way it detects changes in hook dependencies.
This prevents infinite re-renders from `useIncomingWebhooks` by using a static `DEFAULT_DATA` constant, so that its reference is always the same, so no changes are detected when there are none.
Unrelated scouting, but this PR also removes an unneeded dependency in the memoized columns in `ProjectActionsTable`.

fix: prevent infinite rerenders in useIncomingWebhooks

---

src/migrations/20240208123212-create-stat-traffic-usage-table.js

Adds migration for creating table `stat_traffic_usage`.
This table primary-keys on day, traffic_group, and status_code_series.
Traffic group is the grouping for API endpoints for which traffic is counted.
status_code_series is 200/202 etc = 200, 304 etc = 300

chore: add migration for traffic data collection

---

frontend/src/component/common/Dialogue/Dialogue.tsx
frontend/src/component/layout/Error/Error.tsx

Adds the option for a 3rd button in the Dialogue component
Adds a button to open our zendesk support page
Closes # [1-2024](https://linear.app/unleash/issue/1-2024/review-the-ui-error-dialog)

Chore: add zendesk btn to error dialog

---

website/docs/reference/change-requests.md

Small update to extend an existing description.

docs: mention that environment-level variants also suspend CRs now

---

src/lib/services/email-service.ts

This change takes the (now rather involved) type used to send CR
schedule suspension emails and extracts it into a proper exported type.
This will allow us to import it in enterprise as well instead of
redefining it.

chore: extract and export type used by CR emails

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts
src/lib/types/option.ts

https://linear.app/unleash/issue/2-1942/rate-limit-incoming-webhooks-call-endpoint
Adds a configurable rate limit to calling incoming webhooks. We're setting a 1RPS limit for now, but I'm open to suggestions.

chore: rate limit calling inc webhooks

---

frontend/src/component/common/Table/cells/HighlightCell/HighlightCell.tsx
frontend/src/component/common/Table/cells/LinkCell/LinkCell.test.tsx
frontend/src/component/common/Table/cells/LinkCell/LinkCell.tsx

Adding tooltip when title+subtitle cell has a long subtitle (40 characters threshold)
Design decisions: 
* It's difficult to get info from CSS that ellipsis was used so we decided to use a simple heuristic instead.
* Adding tooltip to the cells instead of wrapping cells at call site so that all tables get this capability without modifying code in 30+ different places

fix: long descriptions should have tooltips

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/metric-events.ts
src/lib/metrics.ts
src/lib/services/proxy-service.ts

- Emits a new event on the eventBus when Proxy-service creates a new repository for a frontend token
- Adds a prometheus metrics counter for created proxy-repositories

chore: emit PROXY_REPOSITORY_CREATED event when creating new repo

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/FeatureChange.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx
frontend/src/component/common/ConstraintAccordion/ConstraintAccordionList/ConstraintAccordionList.tsx
frontend/src/component/common/SegmentItem/SegmentItem.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyExecution/ConstraintItem/ConstraintItem.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyExecution/StrategyExecution.tsx

This PR updates the way we show deleted strategies in the CR UI. Instead of showing just the strategy name and a diff on hover, we show the same strategy config as we do for new and updated strategies.
This makes it easier to see what you have deleted.
In doing so, it also fixes two issues:
1. inconsistent border radius for segment changes listed. Due to an override in `frontend/src/themes/theme.ts`, these would get a border radius of `theme.shape.borderRadiusLarge` instead of `theme.shape.borderRadiusMedium`. It does this by adding a class and making the selector more specific.
2. The background was unset for the strategy rollout box and constraint item boxes.
It looks like this:
Or with more kinds of strategies:
Note: I'm happy to isolate the color changes to a separate PR if that's …

feat: show info on what would be deleted

---

src/lib/features/metrics/client-metrics/metrics-service-v2.ts

No matter what time of the day it is we should fetch the first date of the daily range into the result. Previously it would only return data at midnight.

fix: include first day of range in the extended metrics

---

src/lib/features/export-import-toggles/export-import-service.ts

Backporting https://github.com/Unleash/unleash/pull/5731

fix: backport import all strategy fields

---

frontend/src/component/application/ApplicationEdit/ApplicationEdit.tsx
frontend/src/component/application/ConnectedInstances/ConnectedInstances.tsx
frontend/src/component/application/ConnectedInstances/ConnectedInstancesTable.tsx
frontend/src/component/application/ConnectedInstances/useConnectedInstancesTable.tsx

This PR adds a first iteration of the connected instances table on a new connected instances tab of the application page (hidden behind a flag).
As a first version, it only uses data that we currently return for each application (so no "connected through" or "last synchronized"). 
It also uses the existing version of the application data and just filters it for the "production" environment right now.
Adding query parameters (and potentially a new URL?) to the applications page (to save state and fetch data) will be done in a follow-up. This should lay the groundwork for adding a new API too.

feat: add connected instances table

---

package.json
yarn.lock

Reverts Unleash/unleash#6232
Husky 
-   Transitioned to `ESM` for module usage.
-   Dropped support for Node 14 and 16.
I believe the first is causing an issue with our build. I tried fixing this but didn't succeed, so I'm reverting

Revert "chore(deps): update dependency husky to v9"

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/ProjectSelect/ProjectSelect.tsx

Adds the same project selector Autocomplete as we use in the playground.
Implements the filtering 
Closes: # [1-2036](https://linear.app/unleash/issue/1-2036/api-project-filtering)

feat: dashboard project filtering

---

frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksTable.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTable.tsx

https://linear.app/unleash/issue/2-1954/make-names-clickable-in-actions-and-incoming-webhooks
Makes names clickable in the incoming webhook and action tables. When clicked, they open the edit form for that resource.

fix: clickable names in inc wh and action tables

---

frontend/src/component/application/Application.tsx
frontend/src/component/application/ApplicationEdit/ApplicationEdit.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts

This PR adds a new file "Application.tsx", which is analogous to the existing Project.tsx file in that it contains the base layout for the application page, as well as tabs pointing to sub pages. Currently, the overview tab uses a paragraph with some fallback text, while the connected instances table displays the instances table. 
I have mostly copied the existing ApplicationEdit component and used that as a base, assuming that we'll delete that component when we're done with this.

feat: add tabs

---

src/lib/routes/index.ts
src/lib/routes/proxy-api/index.ts
src/lib/services/proxy-service.ts

Our frontend API creates new instances of unleash-client-proxy. Because this is by-design, we don't want to log a warning that was designed to warn users about potential misconfiguration of Unleash Proxy.
As an extra, I'm renaming ProxyController to FrontendAPIController to better reflect the intent of this controller.

chore: avoid printing out warnings from known frontend proxies

---

frontend/yarn.lock

Just `cd frontend && yarn upgrade vite` to solve https://github.com/Unleash/unleash/security/dependabot/119

chore: upgrade vite dependency

---

website/docs/contributing/ADRs/overarching/logging.md

I've held an internal knowledge sharing session on this already. If someone can think of a better phrasing for the background, I'm all ears. I think it's just nice to have this documented, so people remember that our logging framework already has a good way to format errors when you use the API `logger.error("<message>", e)`

docs: add ADR for logging with error object

---

frontend/package.json
frontend/yarn.lock

Some transitive dependencies still depends on vite@5.0.0 so this should bring them up to 5.1.3

chore: add vite resolution

---

src/migrations/20240220130622-add-action-state-indexes.js

Adds some relevant indexes to `action_states`, useful for our new "action events" query.

chore: add action state db indexes

---

frontend/src/component/application/ConnectedInstances/ConnectedInstances.tsx

This PR adds warning icons to the environment selector for environments that have problems detected. However, because we don't have any way detect problems yet, this PR only adds the icons and the infrastructure to display them. They're always set to "not displayed" for now.
The icons have "problems detected" as accessible text.
It looks like this when you add them in (for every environment):

feat: add warning icons to environments in selector

---

frontend/src/component/changeRequest/ChangeRequestOverview/ApplyButton/ApplyButton.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.test.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx
frontend/src/component/common/MultiActionButton/MultiActionButton.tsx

This PR moves the CR specific logic out of the MultiActionButton and generalises so that we can re-use it across the application. The CR specific logic is moved into:
* ApplyButton.tsx
* ReviewButton.tsx
This fixes a bug where multi action button would be disabled if you tried to apply an approved change request that you had created yourself.

fix: generalize multi action button

---

src/migrations/20240221115502-drop-action-states.js

Follow up to: https://github.com/Unleash/unleash/pull/6298
We no longer need this table, since it was superseded by `action_events` and is no longer used.
I believe it's safe to drop this table right away since the feature is not being used yet.

chore: db drop action_states

---

src/lib/features/client-feature-toggles/client-feature-toggle-store.ts
src/lib/features/feature-toggle/fakes/fake-feature-strategies-store.ts
src/lib/proxy/proxy-repository.ts
src/test/e2e/api/proxy/proxy.e2e.test.ts

skips the fetching project names from db part in the proxy-repository that was done when the token had ALL_PROJECTS

chore: remove redundant check for project names in db

---

src/migrations/20240222123532-project-metrics-summary-trends.js

Adds a migration to create and fill the `project_metrics_summary_trends` 
This table is to be used in enterprise to update the metrics data daily per project (after the aggregation of the hourly data)
Driving force for this was doing performance testing on the executive dashboard.
This will allow to remove the expensive query to aggregate the data on demand and will drop the total response time from 2.5sec to 125ms (measurements done with 100 Projects, 10000 features and over 1M rows in `client_metrics_env_daily`
Closes # [1-2080](https://linear.app/unleash/issue/1-2080/create-the-project-metrics-summary-trends-table)

feat: create the project-metrics-summary-trends table

---

frontend/src/component/common/Table/PaginatedTable/PaginatedTable.tsx

When all paginated table results fit into a table (e.g. 65 items with 75 rows selected) we still need to show the pagination because someone may change rows size to 25. Out new heuristic for showing pagination is more than 25 results.

fix: minimum pagination size

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsActionItem.tsx

https://linear.app/unleash/issue/2-1969/actions-form-only-show-environments-scoped-to-the-current-project
Filters the environment options in actions to only show environments that are currently visible for that project, safeguarding users from configuring actions for invalid environments.

fix: only show visible environments for that project in actions

---

frontend/src/component/common/FormTemplate/FormTemplate.tsx
frontend/src/component/common/ReactJSONEditor/ReactJSONEditor.tsx
frontend/src/component/common/SidePanelList/SidePanelList.tsx
frontend/src/component/common/SidePanelList/SidePanelListHeader.tsx
frontend/src/component/common/SidePanelList/SidePanelListItem.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksEvents/IncomingWebhooksEventsModal.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksModal.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksActionsCell.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksTable/IncomingWebhooksTable.tsx
frontend/src/hooks/api/getters/useIncomingWebhookEvents/useIncomingWebhookEvents.ts
frontend/src/interfaces/incomingWebhook.ts

https://linear.app/unleash/issue/2-1937/incoming-webhook-events-ui
This PR implements the UI for incoming webhook events.
We're also introducing a new `SidePanelList` component that we'll be able to reuse when we tackle action set events. This PR also promotes `ReactJSONEditor` to a common component and adapts it slightly for this use case.
We're refreshing the events view every 5s, so if you're monitoring events for a specific incoming webhook you can see the latest ones coming in.
We load 20 (configurable through the hook) events by default. Everytime you reach the end of the list you can load 20 more events until you reach the end of the event list.

chore: incoming webhook events UI

---

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx

Improves the arrow design in the "Network overview" after aligning with @nicolaesocaciu

fix: better arrow design in network overview

---

frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/NewFeatureStrategyEdit.tsx
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/change-request-conflict-data.test.ts
frontend/src/component/feature/FeatureStrategy/NewFeatureStrategyEdit/change-request-conflict-data.ts

Fixes a bug where the conflict tracking was only in the old feature strategy edit screen. 
- Ports the conflict tracking to the NewFeatureStrategyEdit screen
Closes # [1-2093](https://linear.app/unleash/issue/1-2093/cr-conflict-detection-in-new-strategy-edit-screen)

fix: track conflicts in new strategy screen

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts

Since we're polling for updates to max revision id every second, and listening for update events for revision id in the proxy repository then running a refresh interval of 20secs in the proxy repo refresh seems excessive.
This PR changes the frequency of the refresh to once per 45mins.

chore: set proxy-repo interval to 45mins instead of 20secs

---

frontend/src/component/executiveDashboard/FlagsProjectChart/FlagsProjectChart.tsx
frontend/src/component/executiveDashboard/LineChart/LineChartComponent.tsx
frontend/src/component/executiveDashboard/ProjectHealthChart/ProjectHealthChart.tsx
frontend/src/component/executiveDashboard/TimeToProductionChart/TimeToProductionChart.tsx
frontend/src/component/executiveDashboard/useProjectChartData.ts

Simplify insights data fetching - let charts pick data instead of preparing labels in hook.
This also **allows access other data-point related properties for use in a tooltip**

feat: simplified insights data fetching

---

frontend/src/component/common/SidePanelList/SidePanelList.tsx
frontend/src/component/common/SidePanelList/SidePanelListHeader.tsx
frontend/src/component/common/SidePanelList/SidePanelListItem.tsx
frontend/src/component/incomingWebhooks/IncomingWebhooksModal/IncomingWebhooksModal.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsEventsModal/ProjectActionsEventsDetails.tsx/ProjectActionsEventsDetails.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsEventsModal/ProjectActionsEventsDetails.tsx/ProjectActionsEventsDetailsAction.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsEventsModal/ProjectActionsEventsDetails.tsx/ProjectActionsEventsDetailsSource/ProjectActionsEventsDetailsSource.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsEventsModal/ProjectActionsEventsDetails.tsx/ProjectActionsEventsDetailsSource/ProjectActionsEventsDetailsSourceIncomingWebhook.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsEventsModal/ProjectActionsEventsModal.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsEventsModal/ProjectActionsEventsStateCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsModal.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTable.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTableActionsCell.tsx
frontend/src/hooks/api/getters/useActionEvents/useActionEvents.ts
frontend/src/interfaces/action.ts
frontend/src/interfaces/incomingWebhook.ts

https://linear.app/unleash/issue/2-1936/action-events-ui
Implements the UI for action events.

chore: action events UI

---

src/lib/middleware/api-token-middleware.ts
src/lib/services/api-token-service.test.ts
src/lib/services/api-token-service.ts

This PR tries to limit the scope the impact of this change to just requests from edge. This has to be configured as a constraint in the feature flag that controls the rollout of this feature.
This is an option to https://github.com/Unleash/unleash/pull/6356 which is more flexible and can be used for other purposes.

idea 1: api token consistency scope using flags

---

src/lib/features/project/project-service.ts
src/test/e2e/services/project-service.e2e.test.ts

In order to stop privilege escalation via `/api/admin/projects/:project/users/:userId/roles` and `/api/admin/projects/:project/groups/:groupId/roles` this PR adds the same check we added to setAccess methods to the methods updating access for these two methods.
Also adds tests that verify that we throw an exception if you try to assign roles you do not have.  
Thank you @nunogois for spotting this during testing.

fix: setRolesForUser and setRolesForGroup role check

---

src/migrations/20240222123532-project-metrics-summary-trends.js

Cleaning up a migration by removing invalid insert. For some customers it's been already applied. For 2 clientIds it was failing. After this change most customers will have inserted data and the failing clientIds will get this migration applied.
We need to pay extra attention if we want to bring the insert back in future as it already got applied for some customers.
In the next PR we can drop the FK constraint to projects since features don't have FK constraint to projects and we read the project information from features.
Another option is to read project information from the projects table not features table (my preference).

fix: project client metrics trends remove invalid insert

---

frontend/src/component/common/ProjectSelect/ProjectSelect.tsx
frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/hooks/useFilteredTrends.ts
frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundConnectionFieldset/PlaygroundConnectionFieldset.tsx

Project select fix for Executive Dashboard and Playground
Extract the select to it's own component and move to `common`
Re-use for both Dashboard and Playground
Adds the id in parenthesis when there are duplicate names

fix: Project select bug with duplicate values

---

src/migrations/20240304084102-rename-observable-events-to-signals.js

https://linear.app/unleash/issue/2-1997/rename-feature-in-the-db
Renames the **incoming webhooks** feature to **signals** in the DB.
Also adds a `description` column to `action_sets`, so we can match the new designs.

chore: rename incoming webhooks to signals (DB)

---

frontend/src/component/application/ApplicationOverview.tsx
frontend/src/hooks/useSubmittedFeedback.ts

feat: application overview feedback

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
src/lib/db/segment-store.ts

For `getAll` method, kept only sql queries and moved mappers into separate functions.
No change in logic, just refactoring.

refactor: segment-store getAll refactor, move mappers out of main method.

---

src/lib/features/playground/playground-service.ts
src/lib/features/segment/fake-segment-read-model.ts
src/lib/features/segment/segment-read-model-type.ts
src/lib/features/segment/segment-read-model.ts
src/lib/segments/segment-service-interface.ts
src/lib/services/index.ts
src/lib/services/segment-service.ts
src/test/e2e/api/admin/state.e2e.test.ts
src/test/e2e/services/playground-service.test.ts

Playground service uses segment read model since we don't need write model.
In the next refactoring I will do the same with the getActiveForClient and remove getActive and getActiveForClient from the store.

refactor: playground uses segment read model

---

frontend/src/component/integrations/IntegrationList/AvailableIntegrations/AvailableIntegrations.tsx
frontend/src/component/integrations/IntegrationList/ConfiguredIntegrations/ConfiguredIntegrations.tsx
frontend/src/component/integrations/IntegrationList/IntegrationIcon/IntegrationIcon.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTriggerCell.tsx
frontend/src/component/signals/SignalEndpointsSignals/SignalEndpointsSignalsModal.tsx

https://linear.app/unleash/issue/2-2002/add-new-signals-icon-instead-of-using-the-webhooks-icon
Adds a new icon for signals, instead of using the same icon as webhooks.
Includes some slight refactoring.

chore: add new signals icon instead of webhook icon

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsActionsCell/ProjectActionsActionsCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsActionsCell/ProjectActionsLastEvent.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsActorCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsEventsModal/ProjectActionsEventsDetails/ProjectActionsEventsDetails.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsEventsModal/ProjectActionsEventsDetails/ProjectActionsEventsDetailsAction.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsEventsModal/ProjectActionsEventsDetails/ProjectActionsEventsDetailsSource/ProjectActionsEventsDetailsSourceSignalEndpoint.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsFiltersCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/useProjectActionsForm.ts
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsModal.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsSourceCell.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsTable.tsx
frontend/src/interfaces/action.ts

https://linear.app/unleash/issue/2-1995/ui-feature-rename-adapt-the-actions-ui
https://linear.app/unleash/issue/2-1988/nice-to-have-last-action-status-on-the-action-sets-table
Brings the project actions table UI up to par with the new designs, implementing some features that were discussed with UX.

chore: new actions table UI

---

package.json

Bumps OSS main package.json version to 5.10.0+main as that's what is shown to Pro

chore: bump OSS main version to 5.10

---

src/migrations/20240305131822-add-scim-id-column-to-user.js

SCIM synchronizations requires a stable id no matter how many changes are made to username and email (our other unique fields). In addition, exposing internal incremented database ids to an external service (our current id field) feels insecure. Our plan is to create either a uuidv7 or ulid when scim operations are performed against the user, so the external scim provisioner has a stable globally unique id to use to refer to the users they're modifying.

task: added scim id to user

---

src/migrations/20240304160659-add-environment-type-trends.js
src/migrations/20240305121426-add-created-at-environment-type-trends.js
src/migrations/20240305121702-add-metrics-summary-columns-to-flag-trends.js

Adds the metrics summary trend columns to flag_trends table.
These will be populated with the rest of the weekly aggregations
Closes [1-2139](https://linear.app/unleash/issue/1-2139/add-the-summary-columns-to-flag-trends-table)

Feat: add metrics summary columns to flag trends

---

src/lib/features/feature-toggle/feature-toggle-store.ts
src/migrations/20240305094305-features-remove-archived.js
src/test/e2e/services/project-service.e2e.test.ts

This column has not been used for 1.5 years and was replace by **archived_at** column and people still get confused of why this is not working as name suggests. Removing this column to remove technical debt.

chore: remove archived column from features table

---

src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts

This is a small fix to avoid that cloning a feature toggle also clones the "createdAt" field, which does not make sense. 
fixes: #6426

fix: clone feature toggle should not copy createdAt

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/components/DashboardHeader/DashboardHeader.tsx
frontend/src/component/executiveDashboard/componentsStat/FlagStats/FlagStats.tsx
frontend/src/component/executiveDashboard/componentsStat/UserStats/UserStats.tsx

- improved page header
- added help text to health and metrics
- updated style for flag stats widget
- fixed users widget shadow

Insights UI improvements

---

frontend/src/component/user/UserProfile/UserProfileContent/UserProfileContent.tsx

Aligns the privacy policy to the center in the profile dropdown, just like we do for the profile settings.

fix: align privacy policy link to the center

---

src/lib/error/exceeds-limit-error.ts
src/lib/error/exeeds-limit-error.ts
src/lib/error/unleash-error.ts

We don't have a meaningful error for limits established by the application. This could be a good starting point.
The error code is 400 cause I couldn't find anything better. 
The name of the error was picked from UnleashApiErrorTypes: https://github.com/Unleash/unleash/blob/2d8e9f87ff96fcb2e2f84a8b4b36bf5c0e28a885/src/lib/error/unleash-error.ts#L4-L34

chore: add a generic error for limit's exeeded

---

frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestTable.tsx

There was a typo in the original message, it said "Unleash Admin already have" (either "admins already have," or "admin already has.")
Fixed it and improved the wording a little bit.

Typo fix in ChangeRequestTable.tsx

---

frontend/src/component/project/Project/ProjectSettings/ProjectApiAccess/CreateProjectApiTokenForm.tsx

Noticed a small typo in the path shown in the project API access side panel.

fix: project tokens path typo

---

src/lib/db/crud/crud-store.ts
src/lib/db/crud/default-mappings.ts
src/lib/db/crud/row-type.ts

This ports the CRUD store into OSS which is an abstraction to reduce the amount of boilerplate code we have to write in stores.
By extending CRUDStore, the store becomes simply the type definition:
```typescript
type ActionModel = { 
actionSetId: number; 
action: string; 
executionParams: Record<string, unknown>; 
createdByUserId: number; 
sortOrder: number; 
}; 
export class ActionStore extends CRUDStore< 
ActionModel & { id: number; createdAt: Date }, 
ActionModel 
> { 
}
```
And eventually specific mappings between those types can be provided (if the mapping is more complex than camelCase -> snake_case):
```typescript
toRow: ({ project, name, actor, match, createdByUserId }) => ({ 
created_by_user_id: createdByUserId, 
project, 
name, 
actor_id: actor, 
source: match.source, …
```

feat: adapted CRUD store from enterprise into OSS

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/proxy/fake-client-feature-toggle-read-model.ts
src/lib/proxy/frontend-api-repository.ts
src/lib/proxy/global-frontend-api-cache.test.ts
src/lib/proxy/global-frontend-api-cache.ts
src/lib/routes/proxy-api/index.ts
src/lib/services/index.ts
src/lib/services/proxy-service.test.ts
src/lib/services/proxy-service.ts
src/lib/types/experimental.ts
src/server-dev.ts

Running old frontend API and new frontend API side by side and comparing results.
Details:
* comparison only on when flag enabled
* always returning old results and warning if new results are different
* global cache is updated only when the flag is on
* copy pasted most of the old code with minor tweak so it's easy to delete old code after the migration
* sticking to the existing naming (separate PR will remove proxy and replace it with frontend API naming)
* next PR will create a composition root for the proxy service

Compare old results with new frontend api

---

src/lib/features/traffic-data-usage/traffic-data-usage-store.test.ts

trafficDataUsageStore.deleteAll() wasn't being awaited in tests, leading to flaky tests. This PR ensures it's being awaited

fix: await trafficDataUsageStore.deleteAll where its being used

---

src/lib/features/playground/offline-unleash-client.ts
src/lib/proxy/client-feature-toggle-read-model-type.ts
src/lib/proxy/client-feature-toggle-read-model.ts
src/lib/proxy/fake-client-feature-toggle-read-model.ts
src/lib/proxy/frontend-api-repository.ts
src/lib/proxy/global-frontend-api-cache.test.ts
src/lib/proxy/global-frontend-api-cache.ts
src/lib/services/proxy-service.test.ts

Now frontend api complexity for evaluation is down from O(n²) to O(n). Because previous getToggle was filtering from the features pool, now we have hashmap, so we can find by key.

feat: make frontend api complexity O(n) instead of O(n2)

---

frontend/src/component/menu/Header/Header.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts
frontend/src/component/project/Project/ProjectSettings/ProjectApiAccess/CreateProjectApiTokenForm.tsx

What it says on the tin
Also adds the beta badge
Closes # [1-2152](https://linear.app/unleash/issue/1-2152/adjust-insights-placement-in-navigation)

fix: insights navigation

---

frontend/src/component/menu/Header/Header.tsx
src/lib/proxy/client-feature-toggle-read-model.ts
src/lib/proxy/proxy-service.ts

1. Clean up not used fields
2. Fix a bug where segment was not attached

feat: frontend api clean up not needed columns

---

src/lib/services/index.ts

fix: revert composition root

---

src/lib/features/project/project-service.ts
src/lib/middleware/rbac-middleware.test.ts
src/lib/middleware/rbac-middleware.ts
src/lib/services/access-service.ts

To check that users do indeed have permissions to update the roles from project-service, we've been depending on req.user.id. 
We had one error on Friday March 8th, where we managed to send undefined/null to a method that requires a number. This PR assumes that if we have an API token, and we have admin permissions and userId is not set we're a legacy admin token. As such we do not have a real user id, so this sets the userId on the request to SYSTEM_USER_ID (-1337), to credit someone with the operation.

fix: admin token requests does not automatically have id

---

src/lib/features/project/project-service.ts
src/lib/middleware/rbac-middleware.test.ts
src/lib/middleware/rbac-middleware.ts
src/lib/services/access-service.ts

To check that users do indeed have permissions to update the roles from project-service, we've been depending on req.user.id. We had one error on Friday March 8th, where we managed to send undefined/null to a method that requires a number. This PR assumes that if we have an API token, and we have admin permissions and userId is not set we're a legacy admin token.
It uses the util method for extractUserId(req: IAuthRequest | IApiRequest), so if we've passed through the apiTokenMiddleware first, we'll have userId -42, if we haven't, we'll get -1337.

fix: admin token requests does not automatically have id (#6501)

---

.github/workflows/build_frontend_prs.yml
frontend/check-imports.rc
frontend/package.json
frontend/src/component/admin/banners/BannerModal/BannerForm.tsx

This PR adds a check that should fail the build if we use disallowed imports from `@mui/icons-material`

chore: add a script that validates that we don't use prohibited mui material-icons import

---

src/migrations/20240305131822-add-scim-id-column-to-user.js
src/migrations/20240306145609-make-scim-id-idx-unique.js

This PR drops the previous PRs scim_id idx and replaces it with an actual UNIQUE index

fix: scim id was not unique

---

frontend/src/component/admin/users/UsersAdmin.tsx
frontend/src/component/admin/users/UsersList/UsersList.tsx
frontend/src/component/common/PremiumFeature/PremiumFeature.tsx

Ivar pointed out to me that this was intended as an enterprise only feature. So this PR makes it an enterprise only feature. Conditionally render the link in the normal user table, and use premium feature component if you happen to hit the route and not be running on the enterprise plan.

task: Make Inactive users an enterprise feature (#6510)

---

package.json
src/lib/features/feature-toggle/configuration-revision-service.ts
src/lib/middleware/response-time-metrics.test.ts
src/test/e2e/helpers/test-helper.ts

Some tests are reporting this error:
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 UPDATE_REVISION listeners added to [ConfigurationRevisionService]. Use emitter.setMaxListeners() to increase limit`
I thought it's because of this change https://github.com/Unleash/unleash/pull/6400#discussion_r1511494201 but it was not.
I've managed to get a trace of the issue following this https://stackoverflow.com/q/62897235/239613 and now we can identify `ConfigurationRevisionService` as one explanation. The reason is that it's a singleton that should be cleaned up after tests.
E.g.: https://github.com/Unleash/unleash/actions/runs/8248332132/job/22558419656?pr=6517#step:8:15

chore: re-add max listeners

---

src/lib/features/frontend-api/create-context.ts
src/lib/features/frontend-api/frontend-api-controller.ts

We are sharing contexts because we want both clients to use same session ID.

feat: share context between both frontend apis

---

src/lib/features/frontend-api/frontend-api-controller.ts
src/lib/features/frontend-api/frontend-api-service.ts

Moving to controller level to measure only for flag. Other option would have been to check flag also at service.

fix: measure frontend times only when flag enabled

---

frontend/src/component/executiveDashboard/componentsStat/FlagStats/FlagStats.tsx

Changes the insights icon to award_star.  
Closes # [1-2180](https://linear.app/unleash/issue/1-2180/change-icon-to-award-star)

fix: change insights icon to award star

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/components/DashboardHeader/DashboardHeader.tsx
frontend/src/component/executiveDashboard/components/LineChart/createChartOptions.ts
frontend/src/component/executiveDashboard/components/Widget/Widget.tsx
frontend/src/component/executiveDashboard/componentsStat/HealthStats/HealthStats.tsx
frontend/src/themes/theme.ts

What it says on the tin
Closes # [1-2182](https://linear.app/unleash/issue/1-2182/sticky-header-on-scroll)
https://github.com/Unleash/unleash/assets/104830839/f5249fd6-a4cc-4e52-9b01-89ef3cbeb47c

Feat: sticky insights header and widget tooltip icon

---

src/lib/db/client-applications-store.ts

There was no need to join the entire metrics table, as it is a huge table. We only needed all combinations of app_name, environment, and feature_name. The new query retrieves all this data, which will then be joined into the main query.

refactor: optimize applications overview

---

website/docs/reference/strategy-constraints.md
website/docs/reference/unleash-context.md

This change addresses the question in #6542 about using non-string
operators on string values by clarifying that Unleash SDK converts the
string values before performing the comparison.

docs: add notes about how Unleash deals with string context values and conversion

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsActionItem.tsx
src/lib/util/constants/actions.ts

https://linear.app/unleash/issue/2-2046/implement-dynamic-action-parameters
Follow up to https://github.com/Unleash/unleash/pull/6554
Cleans up the `required` property in action definitions after adapting to using the `parameters` property instead.

chore: drop action definition required

---

frontend/src/component/menu/Header/Header.tsx

Reuses the beta badge from insights

Fix: insights beta badge

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/components/LineChart/createChartOptions.ts
frontend/src/component/executiveDashboard/componentsChart/FlagsProjectChart/FlagsProjectChart.tsx
frontend/src/component/executiveDashboard/componentsChart/MetricsSummaryChart/MetricsSummaryChart.tsx
frontend/src/component/executiveDashboard/componentsChart/ProjectHealthChart/ProjectHealthChart.tsx
frontend/src/component/executiveDashboard/componentsChart/TimeToProductionChart/TimeToProductionChart.tsx
frontend/src/component/executiveDashboard/componentsChart/TimeToProductionChart/TimeToProductionTooltip/TimeToProductionTooltip.tsx
frontend/src/component/executiveDashboard/componentsChart/UsersPerProjectChart/UsersPerProjectChart.tsx
frontend/src/component/executiveDashboard/hooks/useAvgTimeToProduction.test.ts
frontend/src/component/executiveDashboard/hooks/useAvgTimeToProduction.ts
frontend/src/component/executiveDashboard/hooks/useGroupedProjectTrends.test.ts
frontend/src/component/executiveDashboard/hooks/useGroupedProjectTrends.ts
frontend/src/component/executiveDashboard/hooks/useMetricsSummary.ts
frontend/src/component/executiveDashboard/hooks/useProjectChartData.ts

Adds live data to TimeToProductionChart and AverageTimeToProduction gauge.
Create a custom tooltip
Changes the interaction mode for tooltips as per @nicolaesocaciu pairing session
Improvement:
Extract grouping by project to its own hook (3 charts that needed grouped data where handling it independently.
Closes # [1-2143](https://linear.app/unleash/issue/1-2143/time-to-production-total-aggregation)

feat: average time to production chart

---

CODEOWNERS

This PR updates the codeowners file, setting @alvinometric and @nnennandukwe as the code owners for docs, removing @thomasheartman .

chore: make Alvin and Nnenna CODEOWNERs for docs

---

frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsActionSelect.tsx

This should fix the action select bug where it shows as empty when the form loads.

fix: action select value

---

src/lib/server-impl.ts
src/lib/types/option.ts

An entrypoint for enterprise to register a hook which will be called before the database and scheduler services are torn down. That way enterprise can also perform graceful shutdown.

feat: Added shutdown hook option

---

frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx

https://linear.app/unleash/issue/2-2034/project-settings-url-bug
This prevents a bug where the wrong tab would show as selected, only present in an edge case where the project has the name of a settings tab.

fix: project settings selected tab bug

---

frontend/src/component/executiveDashboard/ExecutiveDashboard.tsx
frontend/src/component/executiveDashboard/componentsChart/MetricsSummaryChart/MetricsChartTooltip/MetricsChartTooltip.tsx
frontend/src/component/executiveDashboard/componentsChart/UpdatesPerEnvironmentTypeChart/UpdatesPerEnvironmentTypeChartTooltip/UpdatesPerEnvironmentTypeChartTooltip.tsx

This PR fixes these errors (that were showing up in the dev console) in the insights pages:
- nesting a div within a p in the count header (flags, environments, apps); instead flip the relationship and nest the p within the div
- missing keys in mapped components
- passing a boolean "scrolled" value to the underlying component (a div) is invalid: instead, make it so that that prop is not passed
The only one of these that could have a visual impact is the first one (p>div -> div>p), but it appears to be the same to me.
Here's before the change:
And here's after:

fix: invalid HTML and react errors in insights pages

---

frontend/src/component/banners/Banner/Banner.tsx
frontend/src/component/banners/OutdatedSdksBanner/OutdatedSdksBanner.tsx
frontend/src/hooks/usePlausibleTracker.ts
frontend/src/interfaces/banner.ts
frontend/src/themes/themeTypes.ts

We added banner to get attention of customer, but we are not tracking its usage.
Added a way to track the **goto action** button.

feat: add configurable event for banner goto action

---

package.json
src/test/arbitraries.test.ts
yarn.lock

The changes to arbitraries here is to make typescript agree with our schema types. Seems like somewhere between 4.8.4 and 5.4.2, typescript got stricter.

chore: Upgrade to typescript 5.4.2

---

src/migrator.ts

This PR sets the log level of db-migrate to error, because it interferes with the indexing of our logs in Loki when the logs are not in JSON format.

fix: set log level to error for db migrate

---

src/lib/features/metrics/instance/register.ts

There seems to be a typo in the authorization header. We're keeping the old typo as preferred just in case, but if not present we'll default to the authorization header (not authorisation).
Not sure about the impact of this bug, as all registrations might be using default project.

fix: authorization header typo

---

frontend/src/component/signals/SignalEndpointsModal/SignalEndpointsForm/SignalEndpointsTokens/SignalEndpointsTokens.tsx
frontend/src/component/signals/SignalEndpointsModal/SignalEndpointsForm/SignalEndpointsTokens/SignalEndpointsTokensDialog.tsx
frontend/src/component/signals/SignalEndpointsModal/SignalEndpointsModal.tsx
frontend/src/component/signals/SignalEndpointsTable/SignalEndpointsTable.tsx

Adds a "call signal endpoint" example to the token dialog.

chore: call signal endpoint example

---

src/lib/features/project/project-controller.ts
src/lib/features/project/projects.e2e.test.ts
src/lib/openapi/spec/index.ts
src/lib/openapi/spec/project-insights-schema.ts

Hardcoded data powering this screen:
This PR introduces a new resource (/insights) and corresponding openapi schemas.

feat: project insights resource with hardcoded data

---

frontend/src/component/executiveDashboard/componentsChart/MetricsSummaryChart/MetricsChartTooltip/MetricsChartTooltip-InfoSummary.test.tsx
frontend/src/component/executiveDashboard/componentsChart/MetricsSummaryChart/MetricsChartTooltip/MetricsChartTooltip.tsx

This change makes the tooltip still render values and headers that are
`N/A` (instead of not rendering them at all).
This makes the tooltip more consistent and predictable. At least to
me, it was confusing that some of the values were just hidden sometimes.
I've also added a test to make sure that the tooltip renders the N/A values.
This is what it looks like now:

fix: render values that are N/A

---

frontend/src/component/executiveDashboard/hooks/useAvgTimeToProduction.test.ts
frontend/src/component/executiveDashboard/hooks/useAvgTimeToProduction.ts

Makes the time to production stats show the current value (latest date).  This aligns it with other stats on the page.
Closes # [1-2203](https://linear.app/unleash/issue/1-2203/make-the-time-to-production-stats-show-the-latest-current-data)

fix: ttp stat show latest date

---

frontend/src/component/menu/Header/Header.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Creates a new flag to control the executive dashboard ui
Closes # [1-2208](https://linear.app/unleash/issue/1-2208/create-separate-ui-flag-decoupled-from-the-backend-flag)

chore: create new flag to hide insights ui

---

frontend/src/component/menu/Header/Header.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Creates a new flag to control the executive dashboard ui
Closes #
[1-2208](https://linear.app/unleash/issue/1-2208/create-separate-ui-flag-decoupled-from-the-backend-flag)
---------
(cherry picked from commit 84707e2bf3aa2241a60c92aa4fd40f5b6b6e34c2)
Closes #

chore: create new flag to hide insights ui (#6638)

---

frontend/src/component/executiveDashboard/chart-info.ts
frontend/src/component/executiveDashboard/componentsChart/TimeToProductionChart/TimeToProductionChart.tsx
frontend/src/component/executiveDashboard/componentsChart/TimeToProductionChart/median-time-to-production.test.ts
frontend/src/component/executiveDashboard/componentsChart/TimeToProductionChart/median-time-to-production.ts

Separates out the calculation of the median to its own file and tested
Closes # [1-2212](https://linear.app/unleash/issue/1-2212/timetoproduction-for-all-projects-should-show-the-change-in-the-median)

feat: ttp for all projects should show median value per day

---

frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/EditDefaultStrategy.tsx

This PR fixes a bug where editing the default strategy would not refresh the resource it was depending on to display the data. This also surfaces another issue, which is that project settings is using data from the getProjectOverview hook to display the default strategies in each environment. This should be it's own resource, but that is beyond the scope of this PR.

fix: default strategy ui update fix

---

frontend/src/component/project/Project/ProjectInsights/ProjectHealth/ProjectHealthChart.test.tsx
frontend/src/component/project/Project/ProjectInsights/ProjectHealth/ProjectHealthChart.tsx

For very small values we were getting negative stroke dasharray (due to a required gap). This fix prevents negative values in stroke dasharray.

fix: render small values in project health

---

frontend/src/component/project/Project/ProjectInsights/ProjectInsights.tsx
frontend/src/component/project/Project/ProjectInsights/ProjectInsightsStats/HelpPopper.tsx
frontend/src/component/project/Project/ProjectInsights/ProjectInsightsStats/ProjectInsightsStats.tsx
frontend/src/component/project/Project/ProjectInsights/ProjectInsightsStats/StatusBox.tsx
frontend/src/component/project/Project/ProjectInsights/ProjectMembers/ProjectMembers.tsx

Now project members and stats are sharing the same status component.

refactor: fix stats layout and unify components

---

frontend/package.json
frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/change-request-conflict-data.test.ts
frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/change-request-conflict-data.ts
frontend/src/utils/strategyNames.tsx
frontend/yarn.lock

Follow up to https://github.com/Unleash/unleash/pull/6605
This upgrades TypeScript in frontend to `5.4.2`, matching the version we have on the server.
Only 2 things broke with this upgrade, so the changes are related to fixing the types in those places.
This fixes https://github.com/Unleash/unleash/pull/6659

chore: upgrade typescript in frontend to 5.4.2

---

frontend/src/component/common/ProjectSelect/ProjectSelect.tsx

Make the tooltip for project selection in the playground work properly again. Right now, it doesn't work due to an error in react refs.
Because we wrap this in a tooltip in the Playground, we need to forward the ref to the underlying component.
This follows the steps outlined in https://mui.com/material-ui/guides/composition/#caveat-with-refs

fix: add forwardRef to ProjectSelect component

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/tests/feature-toggle-strategies-store.e2e.test.ts

Via the API you can currently create gradualRollout strategies without any parameters set, when visiting the UI afterwards, you can edit this, because the UI reads the parameter list from the database and sees that some parameters are required, and refuses to accept the data. This PR adds defaults for gradualRollout strategies created from the API, making sure gradual rollout strategies always have `rollout`, `groupId` and `stickiness` set.
My one worry here is if we should take the time to check if default stickiness is disabled. I think it makes sense to default to default here; but I'm open to suggestions.

fix: use defaults when creating gradualRollout strategies

---

src/lib/types/openapi.d.ts
src/migrations/20240325081847-add-scim-id-for-groups.js
website/package.json

Adds a scim id to groups. Seemed like we could get away with the name here but unfortunately our names are not unique

chore: add scim id migration for groups

---

src/lib/openapi/spec/sdk-context-schema.test.ts
src/lib/openapi/spec/sdk-context-schema.ts

This change fixes the OpenAPI schema to disallow non-string properties
on the top level of the context (except, of course, the `properties` object).
This means that we'll no longer be seeing issues with rendering
invalid contexts, because we don't accept them in the first place.

fix: prevent non-string properties from being passed as context values

---

src/lib/metrics.ts

This change adds a new prometheus counter to all us to capture when we automatically forward traffic from old /proxy paths to the /api/frontend path.

fix: Add metrics for old proxy forward

---

package.json
src/migrations/20240326122126-add-index-on-group-name.js

As the title says, adds an index on the group name. Scim (in particular Azure) uses group names to find correct group to sync.

feat: add index on group name

---

frontend/src/component/feature/FeatureToggleList/BulkEnableDialog.tsx

This was meant to repull the features, but we are using search, so it was doing nothing.
I tested and features are still updated after removal.

refactor: remove quering old features endpoint from BulkEnableDialog 

---

frontend/src/component/common/Table/PaginatedTable/PaginatedTable.tsx
frontend/src/component/common/Table/cells/FavoriteIconCell/FavoriteIconCell.tsx
frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/OldProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/RowSelectCell/RowSelectCell.tsx
frontend/src/component/project/Project/ProjectOverview.tsx

This PR is only 80 LOC. 500 LOC is copy paste of the old table component that will be removed soon. I renamed the previous version to keep the history for the evolving component.
Old table:
New table:
Improved flag type tooltip
Tooltip for long tag names
Adjusted row selector and favourite spacing

feat: Table with feature overview cell

---

frontend/src/component/feature/Dependencies/AddDependencyDialogue.test.tsx
frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/DependencyRow.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.test.tsx

Before: remove dependency option always selected by default
After: if there's existing parent dependency it gets auto-selected by default

feat: keep parent selection in edit dependency dialogue

---

frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/LegalValueLabel/LegalValueLabel.styles.ts
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/LegalValueLabel/LegalValueLabel.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/RestrictiveLegalValues/RestrictiveLegalValues.tsx

Improves how we show context field legal values in the new strategy configuration.
Refactored makeStyles to styled components 
Closes # [1-2235](https://linear.app/unleash/issue/1-2235/context-field-ui-in-strategy-configuration)
Before: 
After:

Chore: constraint context field legal values improvement

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/DependencyChange.tsx
frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/component/feature/Dependencies/AddDependencyDialogue.test.tsx
frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/DependencyRow.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.tsx
frontend/src/interfaces/featureToggle.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Feature dependency on a disabled feature (e.g. killswitch)
https://github.com/Unleash/unleash/assets/1394682/0d39285f-af4a-4ac7-a327-9d1a262f4f2a
Details:
* new flag that allows to select feature status: enabled/disabled
* new dropdown for status
* new display value in the feature overview (shows only when parent is disabled)
* works with regular add dependency and with add dependency in change request (separate PR in the enterprise)
* tests verifying new capability

feat: disabled feature dependency

---

src/migrations/20240329064629-revert-feature-archived.js

When downgrading to 5.10 we had one query impacted because of the missing legacy archived column (used in getFeatureTypeCounts). Bringing it back so that we keep our rule of being backwards compat for 2 versions ([from our db changes ADR](https://github.com/Unleash/unleash/blob/main/website/docs/contributing/ADRs/back-end/breaking-db-changes.md)).
It reverts this change: https://github.com/Unleash/unleash/pull/6431

fix: revert archived column for backwards migration compatibility

---

frontend/src/component/common/ConstraintAccordion/ConstraintValueSearch/ConstraintValueSearch.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/ConstraintFormHeader/ConstraintFormHeader.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/LegalValueLabel/LegalValueLabel.styles.ts
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/LegalValueLabel/LegalValueLabel.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/LegalValueLabel/filter-legal-values.test.ts
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/RestrictiveLegalValues/RestrictiveLegalValues.test.tsx
frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/RestrictiveLegalValues/RestrictiveLegalValues.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Adds highlighting to search values 
Search also looks in `description`
behind a flag -  it could possibly degrade performance when too many items.  Tested with 200 and it's ok but anything above might degrade:
Adds a Select/Unselect all button
Shows the selected values above the search 
Closes # [1-2232](https://linear.app/unleash/issue/1-2232/context-field-ui-filter-and-search)
https://github.com/Unleash/unleash/assets/104830839/ba2fe56f-c5db-4ce7-bc3c-1e7988682984

Feat: context field search and filter improvements

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/app.ts
src/lib/middleware/bearer-token-middleware.test.ts
src/lib/middleware/bearer-token-middleware.ts
src/lib/openapi/index.ts
src/lib/types/experimental.ts

Adds a bearer token middleware that adds support for tokens prefixed with "Bearer" scheme. Prefixing with "Bearer" is optional and the old way of authenticating still works, so we now support both ways.
Also, added as part of our OpenAPI spec which now displays authorization as follows:
Related to #4630. Doesn't fully close the issue as we're still using some invalid characters for the RFC, in particular `*` and `[]`
For safety reasons this is behind a feature flag

chore: bearer token middleware

---

src/lib/features/feature-toggle/feature-toggle-service.ts

This was identified during some tests where we noticed jest did not complete properly (notice how after linking unleash-server to this commit it didn't have that issue):

chore: when some promise fails others might hang and leave open conns

---

frontend/src/component/banners/EdgeUpgradeBanner/EdgeUpgradeBanner.tsx
frontend/src/component/banners/OutdatedSdksBanner/OutdatedSdksBanner.tsx
frontend/src/component/project/Project/Project.tsx

fix: tabs alignment

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx
frontend/src/hooks/useSubmittedFeedback.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

We are removing strategy form feedback in favor of new project overview feedback form.

chore: remove strategy form feedback

---

src/lib/middleware/bearer-token-middleware.test.ts
src/lib/middleware/bearer-token-middleware.ts

This should make it so that the `signal-endpoint` route match is slightly less strict.

chore: fix bearer token middleware signal endpoint logic

---

src/lib/services/api-token-service.test.ts
src/lib/services/api-token-service.ts
src/test/e2e/stores/api-token-store.e2e.test.ts
src/test/fixtures/fake-api-token-store.ts

This PR establishes a simple yet effective mechanism to avoid DDoS against our DB while also protecting against memory leaks.
This will enable us to release the flag `queryMissingTokens` to make our token validation consistent across different nodes

chore: cache query misses to protect against DDoS

---

CONTRIBUTING.md

There was some confusion on how to run the e2e tests in #6447, so I'm
adding a small section to CONTRIBUTING.md to make it clearer.

docs: explicitly call out how to run e2e tests in CONTRIBUTING.md

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/FeatureStrategyConstraints.tsx

API returns both value and values fields. Empty values array causes ui to think constraint doesnt have a value
This PR checks if value field exists and is empty before returning check on values and length
Included a check on the value of the field in addition to checking if the field exists, I'll check the Open API spec but can we guarantee it doesn't exist without also having a value?
Should we check if the field is undefined? Feels like if it exists it's returned either with a value or as empty.

fix: strategy targeting numeric also check value field

---

src/lib/features/playground/clean-context.test.ts
src/lib/features/playground/clean-context.ts
src/lib/features/playground/playground-api.e2e.test.ts
src/lib/features/playground/playground-service.ts
src/test/e2e/api/admin/playground-api.e2e.test.ts

Don't include invalid context properties in the contexts that we evaluate. 
This PR removes any non-`properties` fields that have a non-string value. 
This prevents the front end from crashing when trying to render an object.
Expect follow-up PRs to include more warnings/diagnostics we can show to the end user to inform them of what fields have been removed and why.

fix: handle objects in top-level context in playground

---

src/lib/features/feature-lifecycle/createFeatureLifecycle.ts
src/lib/features/feature-lifecycle/fake-feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store-type.ts
src/lib/types/events.ts

Initial design for the feature lifecycle service.
Design considerations:
* defer DB schema as much as possible and work off the fake store implementation (DB changes are less reversible)
* focus on reacting to event store events to build the feature lifecycle derivative model. We may need to create 2 new events for "feature first non prod traffic received" and "feature first prod traffic received".

feat: initial design for feature lifecycle service

---

frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/feature-lifecycle/createFeatureLifecycle.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/index.ts
src/lib/services/index.ts
src/lib/types/experimental.ts
src/lib/types/services.ts
src/server-dev.ts

* introducing featureLifecycle flag that can disable event listening at runtime
* making some of the methods private in the lifecycle service
* setting up fake lifecycle service in the initial service bootstrap so that we can test with the in-memory based persistence
When get get DB migrations and SQL repository we'll switch to the real store. 
In the next PR I'll expose the in-memory recorded lifecycle stages over API.

feat: feature lifecycle usage behind a flag

---

src/lib/features/playground/clean-context.test.ts
src/lib/features/playground/clean-context.ts
src/lib/features/playground/playground-api.e2e.test.ts
src/lib/features/playground/playground-service.ts
src/lib/features/playground/playground-view-model.ts
src/lib/features/playground/playground.ts
src/lib/openapi/spec/advanced-playground-response-schema.ts

This PR expands upon #6773 by returning the list of removed properties in the API response. To achieve this, I added a new top-level `warnings` key to the API response and added an `invalidContextProperties` property under it. This is a list with the keys that were removed.
**Should we return the type of each removed key's value?** We could expand upon this by also returning the type that was considered invalid for the property, e.g. `invalidProp: 'object'`. This would give us more information that we could display to the user. However, I'm not sure it's useful? We already return the input as-is, so you can always cross-check. And the only type we allow for non-`properties` top-level properties is `string`. Does it give any useful info? I think if we want to display this in the UI, we …

feat: playground api returns removed context values under a new `warnings` property

---

src/lib/features/feature-lifecycle/createFeatureLifecycle.ts
src/lib/features/feature-lifecycle/fake-feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts
src/lib/services/index.ts
src/migrations/20240405120422-add-feature-lifecycles.js

* db migration for lifecycle stages
* sql store based on the new migration and tested through the e2e test (if there's error in any query the tests catches it)
* making feature lifecycle service an event emitter itself so that we can wait to stage change events in tests instead of `await ms(randomTime)`

feat: Feature lifecycle sql store

---

package.json

v5.11 was released. This is updating current version indicated on main branch of open-source

chore: bump indicated main version in package.json

---

CONTRIBUTING.md

Just aligning with our required node version from package.json https://github.com/Unleash/unleash/blob/e9f9cd1147d636fbb47956f07b18baa46bdabf93/package.json#L22-L24
and https://docs.getunleash.io/using-unleash/deploy/database-setup

docs: update min versions for node and postsgres

---

frontend/src/component/insights/hooks/useFilteredFlagsSummary.ts

Fix: time to production showing  NaN when no data

---

frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/LegalValueLabel/LegalValueLabel.styles.ts

Fixes a bug where the background of Legal values was white for dark mode

fix: dark mode background

---

frontend/src/component/insights/Insights.tsx

Before: 
After:
Closes # [1-2267](https://linear.app/unleash/issue/1-2267/fix-zindex-of-notenoughdata-component)

fix: NotEnoughData hiding the header

---

frontend/src/component/insights/InsightsCharts.tsx

Fixes the flag stats flagsPerUser calculation and display value. 
Previously the calculation depended on project data which might not be there with the permission changes
Closes # [1-2255](https://linear.app/unleash/issue/1-2255/unable-to-render-total-number-of-flags-when-there-are-no-project-data)

fix: total flags and flags per user when all projects

---

frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/LegalValueLabel/LegalValueLabel.styles.ts

Pulls in dark mode fix for strategy constraint legal values background from PR #6803 to be released in 5.11.1

fix: dark mode background (#6803)

---

frontend/src/component/insights/Insights.tsx
frontend/src/component/insights/componentsChart/TimeToProductionChart/TimeToProductionTooltip/TimeToProductionTooltip.tsx
frontend/src/component/insights/componentsChart/UpdatesPerEnvironmentTypeChart/UpdatesPerEnvironmentTypeChart.tsx
frontend/src/component/insights/componentsChart/UpdatesPerEnvironmentTypeChart/group-by-date.test.ts

Fills datasets that do not have all the datapoints with 0 so that every line in the graph starts at the beginning and ends at the end of graph.
Closes # [1-2256](https://linear.app/unleash/issue/1-2256/fill-the-data-with-0s-so-that-all-x-axis-labels-have-values)

fix: fill the datasets with 0s when not enough data points

---

frontend/src/component/insights/components/LineChart/LineChartComponent.tsx

Chart options should change when it stops displaying a placeholder/cover. Without this we had axis missing on some renders.

fix(insights): axis rendering after placeholder

---

src/migrations/20240408104624-fix-environment-type-trends.js

Creates a migration to fix the environment_type_trends table data.
The migration works in 4 steps:
- Clear environment_type_trends table
- Create a temporary staging table for 1st aggregation (day + environmentType)
- Aggregate the data from stat_environment_updates to the staging table
- Aggregate the data from staging to environment_type_trends 
Closes # [1-2266](https://linear.app/unleash/issue/1-2266/fix-the-environment-type-trends-table-data)

fix: environment_type_trends table data

---

frontend/src/component/insights/components/LineChart/LineChartComponent.tsx
frontend/src/component/insights/components/LineChart/createChartOptions.ts
frontend/src/component/insights/componentsChart/FlagsProjectChart/FlagsProjectChart.tsx
frontend/src/component/insights/componentsChart/MetricsSummaryChart/MetricsSummaryChart.tsx
frontend/src/component/insights/componentsChart/ProjectHealthChart/ProjectHealthChart.tsx
frontend/src/component/insights/componentsChart/TimeToProductionChart/TimeToProductionChart.tsx
frontend/src/component/insights/componentsChart/UsersPerProjectChart/UsersPerProjectChart.tsx

Internal ticket: https://linear.app/unleash/issue/1-2271/cleanup-of-local-tooltip-from-insights-charts

refactor(insights): remove unused chart property

---

frontend/src/component/insights/componentsChart/ProjectHealthChart/ProjectHealthChart.tsx

What it says on the tin
Closes # [1-2274](https://linear.app/unleash/issue/1-2274/health-tooltip-when-all-projects-should-show-percent-values)

fix: Health tooltip when all projects should show %

---

frontend/src/component/admin/auth/AuthSettings.tsx
frontend/src/component/admin/auth/ScimSettings/ScimSettings.tsx
frontend/src/component/admin/auth/ScimSettings/ScimTokenDialog.tsx
frontend/src/component/admin/auth/ScimSettings/ScimTokenGenerationDialog.tsx
frontend/src/hooks/api/actions/useScimSettingsApi/useScimSettingsApi.ts
frontend/src/hooks/api/getters/useScimSettings/useScimSettings.ts
frontend/src/interfaces/uiConfig.ts

https://linear.app/unleash/issue/2-1981/ui-allow-users-to-set-up-scim
Adds UI for Provisioning (SCIM) settings.

chore: SCIM settings UI

---

src/lib/metrics.test.ts
src/lib/metrics.ts

This PR adds a counter in Prometheus for counting the number of "environment disabled" events we get per project. The purpose of this is to establish a baseline for one of the "project management UI" project's key results.
This PR uses a counter. Using a gauge would give you the total number of envs disabled, not the number of disable events. The difference is subtle, but important.
For projects that were created before the new feature, the gauge might be appropriate. Because each disabled env would require at least one disabled event, we can get a floor of how many events were triggered for each project.
However, for projects created after we introduce the planned change, we're not interested in the total envs anymore, because you can disable a hundred envs on creation with a single …

chore: Establish a baseline for the number of envs disabled per project

---

src/lib/middleware/response-time-metrics.test.ts
src/lib/middleware/response-time-metrics.ts

The feature `responseTimeMetricsFix` has been enabled for a while. Since it's released in 5.11 this prepares the removal for the next major version.

chore: remove response time metrics fix

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx

Instead of using two placeholders both called "production", we rename
one of them to "development"

chore: fix duplicate use of placeholder name

---

frontend/src/component/insights/componentsStat/TimeToProduction/TimeToProduction.tsx

Currently the TimeToProduction stat shows `Fast` for ttp = 0 which is wrong.  Absolute 0 will only happen when there are no data.
Closes [1-2281](https://linear.app/unleash/issue/1-2281/timetoproduction-stat-should-not-say-fast-when-value-is-0)
Before: 
After:

feat: ttp stat should show No data when exactly 0

---

src/lib/features/scheduler/job-service.test.ts
src/lib/features/scheduler/job-service.ts

This allows failed functions to record that they've failed when wrapped with a job.

chore: job-service handle exceptions

---

package.json

This change adds "feature flag" and "flag" to the keywords in the package.json file. We've started moving towards using that over feature toggle, so it makes sense to add it to the keywords.

chore: add new keywords to package json

---

frontend/src/component/feature/CreateFeature/CreateFeature.tsx
frontend/src/component/project/Project/CreateProject/CreateProject.tsx

This adds replace: true to navigate on the create feature toggle screen and create project screen. This will make it so you don't go back to the form after you have created the resource, replacing the entry in the history with the new url. We can do this in more places, but some of them require a bit more thought. For example when creating a user, you navigate from the admin screen to the user page, and then back to the same screen. Adding `{ replace: true }` in this context makes it so that when you press back you end up on the same screen, because it's recorded twice in history. 
Another discussion point: 
* Would you expect the edit screens to also replace the history?

fix: replace true on important create screens

---

frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

cherry-picks adding the UI-flag for traffic visibility to 5.11
We're splitting the original `collectTrafficDataUsage` in two, one for data collection and the new one introduced here is to allow the UI.
Showing the UI makes no sense if we haven't been collecting data, but starting to collect data makes sense without showing the UI (docs, training/information etc needed when showing the UI for enterprise users), so the feature flag in Unleash is set to depend on data collecting flag being enabled.

chore(ui): add a separate feature flag for traffic visibility UI (#6832)

---

website/docs/reference/change-requests.md

Scheduled config changes aren't in dev anymore; they went GA in 5.10. This PR updates the docs to reflect that.

docs: indicate that scheduled config changes are GA

---

frontend/src/component/admin/users/UsersList/ChangePassword/ChangePassword.tsx
frontend/src/hooks/api/actions/useAdminUsersApi/useAdminUsersApi.ts
src/lib/db/user-store.ts
src/lib/openapi/spec/user-schema.ts
src/lib/routes/admin-api/user-admin.ts
src/lib/types/user.ts
src/test/e2e/api/admin/user-admin.scim.e2e.test.ts

https://linear.app/unleash/issue/2-2093/api-should-not-allow-manual-management-of-scim-managed-users-in
Introduces a SCIM guard for SCIM users. SCIM users should be managed exclusively by the SCIM client, not Unleash.
We decided to be restrictive for now, completely covering all of the write methods, but may fine-tune some of this at a later stage.
Will eventually be followed up by a UI-centric PR.

chore: SCIM guard for users

---

frontend/src/hooks/usePersistentTableState.ts

This change specifies the update type as `replace` for the
`useQueryParams` hook used to set table state.
Primarily, this prevents the column selection from being added to the browser
history and more importantly prevents you from changing your config by
navigating through browser history.
However, this also affects other table state, such as changing sorting order etc. These will also no longer be added to the browser history.
---
Bug description:
In the project flag table, you can select which env columns to show. However, adding and removing these envs get added as steps in your browser history. This means that if you add 3 envs, you:
1. have to go back three times to get back to the previous page
2. In doing so, you also inadvertently revert the choices you mean, which can be …

fix: don't add project flag table state config to browser history

---

frontend/src/interfaces/group.ts
src/lib/db/group-store.ts
src/lib/openapi/spec/group-schema.ts
src/lib/services/group-service.ts
src/lib/types/group.ts

https://linear.app/unleash/issue/2-2111/api-should-not-allow-manual-management-of-scim-managed-groups-in
Introduces a SCIM guard for SCIM groups. SCIM groups should be managed exclusively by the SCIM client, not Unleash.
We decided to be restrictive for now, completely covering all of the write methods, but may fine-tune some of this at a later stage.
Will eventually be followed up by a UI-centric PR.

chore: SCIM guard for groups

---

frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts

Moves the Insights nav menu item down to match desktop ordering
Closes # [1-2290](https://linear.app/unleash/issue/1-2290/mobile-menu-insights-pops-up-as-the-first-item)

fix: Insights placement in drawer nav

---

frontend/src/component/menu/Header/Header.tsx

What is says on the tin
Closes [1-2288](https://linear.app/unleash/issue/1-2288/misalignment-insights-beta-menu-item)

fix: insights menu point alignment

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx

feat: change time based feedback to button

---

frontend/src/component/project/ProjectList/ProjectList.tsx
frontend/src/component/project/ProjectList/should-display-in-my-projects.test.ts
frontend/src/component/project/ProjectList/should-display-in-my-projects.ts

This change adds filtering functionality to the project list filter buttons.
In this case, "my projects" is defined as any project that is marked as a favorite OR (inclusive or) that you are a part of, as defined by your user profile.

feat: allow you to filter for "my projects"

---

frontend/src/component/admin/users/UsersList/UsersActionsCell/UsersActionsCell.tsx
frontend/src/component/admin/users/UsersList/UsersList.tsx
frontend/src/interfaces/user.ts

https://linear.app/unleash/issue/2-2092/ui-should-not-allow-manual-management-of-scim-managed-users-in-unleash
Adds a UI SCIM guard when trying to manage users.
The condition for the guard is:
- Enterprise
- SCIM flag enabled
- SCIM setting enabled
- SCIM user

chore: UI SCIM guard for users

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/db/client-applications-store.ts
src/lib/db/index.ts
src/lib/features/metrics/instance/models.ts
src/lib/features/metrics/instance/register.ts
src/lib/features/metrics/shared/schema.ts
src/lib/types/experimental.ts
src/server-dev.ts
src/test/e2e/api/admin/metrics.e2e.test.ts

Previously, we were extracting the project from the token, but now we will retrieve it from the session, which contains the full list of projects.
This change also resolves an issue we encountered when the token was a multi-project token, formatted as []:dev:token. Previously, it was unable to display the exact list of projects. Now, it will show the exact project names.

feat: start extracting project from session object

---

src/lib/features/segment/admin-segment.e2e.test.ts
src/lib/features/segment/segment-controller.ts
src/lib/middleware/id-number-middleware.test.ts
src/lib/middleware/id-number-middleware.ts
src/lib/routes/admin-api/user-admin.ts
src/lib/routes/admin-api/user/pat.ts

Previously, we were not validating that the ID was a number, which sometimes resulted in returning our database queries (source code) to the frontend. Now, we have validation middleware.

feat: validate that id is number or we throw our our source code

---

frontend/src/component/admin/groups/EditGroup/EditGroup.tsx
frontend/src/component/admin/groups/Group/Group.tsx
frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCard.tsx
frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCardActions/GroupCardActions.tsx
frontend/src/component/admin/groups/group-constants.ts
frontend/src/component/admin/users/UsersList/UsersActionsCell/UsersActionsCell.tsx
frontend/src/component/admin/users/UsersList/UsersList.tsx

https://linear.app/unleash/issue/2-2113/ui-should-not-allow-manual-management-of-scim-managed-groups-in
Adds a UI SCIM guard when trying to manage groups.
The condition for the guard is:
- Enterprise
- SCIM flag enabled
- SCIM setting enabled
- SCIM group
Similar to https://github.com/Unleash/unleash/pull/6859

chore: UI SCIM guard for groups

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/db/client-applications-store.ts
src/lib/types/experimental.ts
src/server-dev.ts
src/test/e2e/api/admin/applications.e2e.test.ts

We encountered an issue with a customer because this query was returning 3 million rows. The problem arose from each instance reporting approximately 100 features, with a total of 30,000 instances. The query was joining these, thus multiplying the data. This approach was fine for a reasonable number of instances, but in this extreme case, it did not perform well.
This PR modifies the logic; instead of performing outright joins, we are now grouping features by environment into an array, resulting in just one row returned per instance.
I tested locally with the same dataset. Previously, loading this large instance took about 21 seconds; now it has reduced to 2 seconds. Although this is still significant, the dataset is extensive.

feat: optimize applications overview query

---

src/lib/app.ts
src/lib/middleware/audit-middleware.test.ts
src/lib/middleware/audit-middleware.ts
src/lib/middleware/index.ts
src/lib/routes/unleash-types.ts
src/lib/server-impl.ts
src/lib/types/user.ts
src/lib/util/extract-user.ts

Adds a middleware which adds our needed audit info as a separate object to the request.

feat: added IAuditUser to request with middleware

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
frontend/src/themes/dark-theme.ts
frontend/src/themes/theme.ts
frontend/src/themes/themeTypes.ts

feat: restyle the project meta box

---

src/lib/features/project/project-service.test.ts
src/lib/features/project/project-service.ts
src/test/fixtures/fake-role-store.ts

This PR adds an optional function parameter to the `createProject` function that is intended to enable change requests for the newly created project.
The assumption is that all the logic within will be decided in the enterprise impl. The only thing we want to verify here is that it is called after the project has been created.

chore: add enterprise extension point to enable change requests on project creation

---

src/lib/types/events.ts

This type was added to try to consolidate events now we're moving in a different direction and this type is not used.

chore: Remove unused type

---

frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsagePlanSummary.tsx

Adds a summary card that sums up data usage for selected month, and for Pro shows monthly quota and badge color according to monthly quota
Light mode (enterprise)
Dark mode (enterprise)
Dark mode Pro
Dark mode Pro above quota

feat: add selected month summary card for data usage

---

website/src/components/Figure/Figure.tsx
website/src/components/Figure/styles.module.css

It turns out the styles that we had in `style.modules.css` were overridden by browser defaults.
Now taking into account all the styles that were in the CSS files (notice margin and border)

Correctly applied styles to `Figure` component in docs

---

src/lib/create-config.ts
website/docs/using-unleash/deploy/configuring-unleash.md

This makes it configurable either through a single JSON file with all three certificates as separate keys or via separate files per ca/cert/key key.
fixes #6718

feat: Make Database SSL Configurable through files

---

src/lib/db/api-token-store.ts
src/lib/features/scheduler/schedule-services.ts
src/lib/middleware/api-token-middleware.ts
src/lib/services/api-token-service.test.ts
src/lib/services/api-token-service.ts
src/lib/services/edge-service.ts
src/lib/types/experimental.ts

This PR removes the feature flag `queryMissingTokens` that was fully rolled out.
It introduces a new way of checking edgeValidTokens controlled by the flag `checkEdgeValidTokensFromCache` that relies in the cached data but hits the DB if needed. 
The assumption is that most of the times edge will find tokens in the cache, except for a few cases in which a new token is queried. From all tokens we expect at most one to hit the DB and in this case querying a single token should be better than querying all the tokens.

feat: make edge use token's cache

---

src/lib/db/crud/crud-store.ts

Add time metrics to relevant queries:
- get
- getAll
- bulkInsert
- count
- exists
- get
Ignored because might not be that relevant:
- insert
- delete
- deleteAll
- update

feat: crud time queries

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

This PR adds the `projectListNewCards` flag to the constant defined in `experimental.ts`. This should allow the API to pass that value to the front end.

chore: add the `projectListNewCards` flag

---

src/lib/features/project/project-service.ts
src/lib/types/model.ts

This commit adds an `environments` property to the project created
payload. The list contains only the projects that the project has
enabled.
The point of adding it is that it gives you a better overview over
what you have created.

feat: add environments to project created payload

---

website/docs/using-unleash/deploy/configuring-unleash.md

This PR adds docs for the new `demoAllowAdminLogin` option, including how to use it and what it does.

docs: document the new `demoAllowAdminLogin` option

---

src/lib/middleware/api-token-middleware.ts
src/lib/services/api-token-service.ts

This change is meant to test something in sandbox. It will be reverted after the investigation.

chore: add a bunch of logs to validate api token validation behavior

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleStageIcon.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx

Adding lifecycle stage badge and passing it's value to the tooltip. In the tooltip the name, icon and stage selector are adjusted accordingly.

feat: pass lifecycle stage to tooltip

---

src/lib/middleware/api-token-middleware.ts
src/lib/services/api-token-service.test.ts
src/lib/services/api-token-service.ts

What's going on is the following:
1. When a token is not found in the token's cache we try to find it in the db
2. To prevent a denial of service attack using invalid tokens, we cache the invalid tokens so we don't hit the db.
3. The issue is that we stored this token in the cache regardless we found it or not. And if the token was valid the first time we'd add a timestamp to avoid querying this token again the next time. 
4. The next iteration the token should be in the cache: https://github.com/Unleash/unleash/blob/54383a6578c221bdacdd1b9f14a108a1eb256e7c/src/lib/services/api-token-service.ts#L162 but for some reason it is not and therefore we have to make a query. But this is where the query prevention mechanism kicks in because it finds the token in the cache and kicks us out. This PR …

chore: remove logs for secret and change invalid token query logic

---

src/lib/middleware/api-token-middleware.ts

This log is also not needed because we have the API status code 401 that shows the same data

chore: remove log

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleStageIcon.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/LifecycleStage.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/isSafeToArchive.test.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/isSafeToArchive.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx

Completed but active traffic in prod for the last 2 days:
Completed and safe to archive since no traffic in the last 2 days:
Details:
* currently a decision if it's safe to archive is done frontend side but we may consider moving it server side

feat: Completed stage UI

---

src/lib/features/feature-lifecycle/fake-feature-lifecycle-read-model.ts
src/lib/features/feature-lifecycle/feature-lifecycle-read-model-type.ts
src/lib/features/feature-lifecycle/feature-lifecycle-read-model.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store-type.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts
src/lib/features/feature-lifecycle/get-current-stage.test.ts
src/lib/features/feature-lifecycle/get-current-stage.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/openapi/spec/feature-schema.ts
src/lib/services/feature-service-potentially-stale.test.ts
src/lib/services/index.ts
src/lib/types/model.ts

Exposing current lifecycle stage in the feature API.
* exposing read model for reading a current stage and injecting it to the feature toggle service
* stages are ordered by fixed rules and even when they were created at mixed order we respect the fixed stage order
* lifecycle is added to feature in a similar fashion to dependencies
* lifecycle can be undefined when no stages were recorded

feat: return lifecycle state in feature overview

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/populateCurrentStage.test.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/populateCurrentStage.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
frontend/src/interfaces/featureToggle.ts

* reading lifecycle data from the feature API
* if no lifecycle data so not show lifecycle UI
* each stage gets corresponding environment metrics info from dev or prod (data combined from lifecycle and env metrics)

feat: connect feature lifecycle to real API

---

src/lib/features/project/project-controller.ts
src/lib/features/project/project-owners-read-model.test.ts
src/lib/features/project/project-owners-read-model.ts

Implementation of the logic for fetching project owners.
Based on pattern documented in https://docs.getunleash.io/contributing/ADRs/back-end/write-model-vs-read-models
- Create and test function combining projects list result with project owners read model results.
- Create Schema update
- Add project owners to the response when the feature flag is enabled
Internal ticket https://linear.app/unleash/issue/1-2318/get-project-owner-users-and-groups-from-db

Project owners read model - db read

---

src/lib/middleware/response-time-metrics.ts

Due to how we handle redirects of embedded proxy, we ended up counting the same request twice. This PR adds a boolean to res.locals which we then check if set to avoid double counting.

fix: added a check to avoid double counting

---

frontend/src/component/feature/Dependencies/AddDependencyDialogue.test.tsx
frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.test.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

Removing variant dependencies flag

chore: remove variant dependencies flag

---

src/lib/features/project/project-owners-read-model.test.ts
src/lib/features/project/project-owners-read-model.ts

Follow-up for https://github.com/Unleash/unleash/pull/6916
- Combining list of projects with owners
- Additional tests and checks 
Internal ticket: https://linear.app/unleash/issue/1-2320/project-owners-mapping

feat: map project owners to projects list

---

src/migrations/20240425132155-flag-trends-bigint.js

Recently we see some pods failing with inserting yes, no values that were over int. Increasing type to bigint.

fix: flag trends should support bigint for yes and no evaluations

---

frontend/src/component/admin/auth/AuthSettings.tsx
frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx
frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx
frontend/src/component/admin/auth/ScimSettings/ScimSettings.tsx
frontend/src/hooks/api/getters/useScimSettings/useScimSettings.ts
frontend/src/hooks/useScim.ts

- Adds support for the configuration option for SCIM taking over control of users and groups
- Moves SCIM settings into SSO config pages (OIDC and SAML). SCIM registers a callback to be invoked when saving in a parent SSO config page

feat: scim assume control UI - move scim into sso configs

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/middleware/bearer-token-middleware.test.ts
src/lib/middleware/bearer-token-middleware.ts
src/lib/types/experimental.ts

Removes the bearer token middleware flag for GA

feat: remove bearer token middleware flag

---

src/lib/app.ts

Conflicts with scim which assumes Bearer <token>, and is located under /scim, with no /api prefix

fix: don't apply bearer token middleware to root

---

src/lib/features/project/project-service.test.ts
src/lib/features/project/project-service.ts
src/lib/services/project-schema.ts
src/lib/types/model.ts

This PR improves the handling of change request enables on project creation in two ways:
1. We now verify that the envs you try to enable CRs for exist before passing them on to the enterprise functionality.
2. We include data about environments and change request environments in the project created events.

feat: include CR envs enabled on creation in event and update validation

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx

Can archive feature from the completed lifecycle stage.
Details:
* added modal for archive at the meta data component level. This component owns featureId and projectId that are needed for the archive.
* modal handles regular and change request flow
* passing archive action to the lifecycle tooltip so that we don't need to pass modal itself very deep down
* test verifying that archive action is invoked from the completed lifecycle stage

feat: archive feature from lifecycle

---

src/lib/features/feature-lifecycle/fake-feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store-type.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts

Revived feature goes back to the initial stage. This is a new initial stage with a date matching the revive time.

feat: revived feature goes to initial lifecycle stage

---

src/lib/features/feature-lifecycle/createFeatureLifecycle.ts
src/lib/features/feature-lifecycle/fake-feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle-controller.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store-type.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts
src/lib/types/events.ts

Creating a way to complete and uncomplete feature.

feat: feature lifecycle complete and uncomplete

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
frontend/src/hooks/api/actions/useFeatureLifecycleApi/useFeatureLifecycleApi.ts

Connects feature complete to backend

feat: feature completed connected to backend

---

src/lib/db/index.ts
src/lib/features/project/createProjectService.ts
src/lib/features/project/fake-project-owners-read-model.ts
src/lib/features/project/project-controller.ts
src/lib/features/project/project-owners-read-model.test.ts
src/lib/features/project/project-owners-read-model.ts
src/lib/features/project/project-owners-read-model.type.ts
src/lib/features/project/project-service.ts
src/lib/openapi/spec/project-schema.ts
src/lib/types/stores.ts
src/test/fixtures/store.ts

Schema and integrating into service and controller for project owners

feat: project owners in project service

---

src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts

Pre-live is not just development but also anything else that is not production.

feat: pre-live is non production not just dev

---

src/lib/features/feature-lifecycle/createFeatureLifecycle.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts
src/test/fixtures/fake-feature-environment-store.ts

To enter the live stage we need to check if feature env is enabled

feat: Check production enabled live stage

---

frontend/package.json
frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsagePlanSummary.tsx
frontend/yarn.lock

Added a small annotation to the chart on how much data is included in the pro plan on average per day to make it easier to spot when a customer average above the included threshold.

fix: Data usage metrics chart included per day annotion

---

frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx
frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx

disable SCIM for OIDC, nothing to test it on
Also checks scim enabled before saving

fix: disable SCIM for OIDC, nothing to test it on

---

src/lib/features/project/project-service.test.ts
src/lib/features/project/project-service.ts

This PR removes the workaround introduced in https://github.com/Unleash/unleash/pull/6931. After https://github.com/ivarconr/unleash-enterprise/pull/1268 has been merged, this should be safe to apply.
Notably, this PR: 
- tightens up the type for the enable change request function, so we can use that to inform the code
- skips trying to do anything with an empty array
The last point is less important than it might seem because both the env validation and the current implementation of the callback is essentially a no-op when there are no envs. However, that's hard to enforce. If we just exit out early, then at least we know nothing happens.
Optionally, we could do something like this instead, but I'm not sure it's better or worse. Happy to take input.
```ts
const crEnvs = …
```

chore: remove workaround

---

frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

Add a flag to enable/disable the new UI for project creation.
This flag is separate from the impl on the back end so that we can enable one without the other (but uses flag dependencies in Unleash, so that we can never enable the new UI without the new back end).
I have not set the flag to `true` in server startup because the form doesn't work yet, so it's a manual step for now.

chore: add flag for the new project creation form layout

---

src/lib/features/feature-lifecycle/feature-lifecycle-store.ts

Previously when we had thousands of metrics coming in, we were trying to write them all to database and running into on conflict

feat: do not insert into database stages that already exist

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

Removes the `inMemoryScheduledChangeRequests` flag and adds `killScheduledChangeRequestCache`

chore: scheduled change request cache kill switch

---

frontend/src/component/common/Badge/Badge.tsx

Simplified after previous modifications

refactor: badge icon spacing

---

website/docs/how-to/how-to-create-and-display-banners.md
website/docs/reference/actions.md
website/docs/reference/banners.md
website/docs/reference/signals.md

Updates feature availability. 
Banners is a feature that is already GA'd since Unleash 5.7, so beta availability seems irrelevant now.
We removed the mention of planning to GA Signals & Actions in 5.12, since that's not happening and we would prefer not to include these mentions in the future.

docs: update feature availability

---

frontend/src/component/common/FilterDateItem/FilterDateItem.test.tsx

This test is breaking right now because it tests a date picker,  week 21 is approaching, and `findByText` only expects a single element. Checking that we have *at least* one element fixes that breakage and I don't think it should cause any issues.
Of course, that means that right now, this test would also pass even if the expected button wasn't there, but it would stop passing in about four weeks time.

chore: fix failing test; don't rely on a single item only

---

src/lib/features/feature-search/feature-search-store.ts

Final rank has always been ordering correctly by default. But after 5.12 I see some issues that sometimes it is not ordered. Just to be extra sure, I am for ordering it.

feat: search order by final

---

frontend/src/component/common/Badge/Badge.test.tsx
frontend/src/component/common/Badge/Badge.tsx

When passing 0 in as child, the 0 was not rendred. Fixed the badge component and added tests.

fix: badge should render children 0 value

---

frontend/src/component/project/Project/CreateProject/ChangeRequestTable.tsx
frontend/src/component/project/Project/CreateProject/CreateProject.tsx
frontend/src/component/project/Project/CreateProject/NewProjectForm.tsx
frontend/src/component/project/Project/CreateProject/SelectionButton.styles.tsx
frontend/src/component/project/Project/CreateProject/SelectionButton.tsx
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestTable.tsx
frontend/src/component/project/Project/hooks/useProjectForm.ts

This PR adds the ability to configure CRs when creating a project.
The design is unfinished, and the code certainly needs cleanup, but I'd like to get this into sandbox so we can look at it.
Things that still need to be done:
1. What do we do about this button when the user has no environments selected? As a rough draft, I've disabled it. However, we should make it possible to navigate to and give you an explanation why it was disabled, e.g. "You have no project environments selected. Please select at least one project environment.".
2. The form design is not done: the width should be constant and not jumpy the way it is now. Also, the search field is too wide.
3. I've made the desicion that if you deselect a project env, we also remove that env from your CR config it it's in there.
4. …

feat: configure CRs when creating projects

---

src/migrations/20240507075431-client-metrics-env-daily-bigint.js

Daily metrics for feature yes/no are approaching integer limits so changing it to bigint. 
This table is queries in two places:
* for the metrics display where the reducer is already casting string (knex type for pg bigint) to number 
```
yes: Number(yes),
no: Number(no),
```
* for the insights aggregation where total_yes and total_no are already bigint so no issue here
```
.sum({ total_yes: 'cmed.yes' })
.sum({ total_no: 'cmed.no' })
```

feat: increase possible number range for yes/no metrics

---

frontend/src/component/project/Project/hooks/useProjectForm.test.ts
frontend/src/component/project/Project/hooks/useProjectForm.ts

This PR adds some tests around how project envs and change request envs interact in the new project form. It tests that:
1. If you remove an env from the project setup, that env is also removed from the change request list.
2. If you try to enable CRs for an env that isn't enabled, nothing happens.

test: test how the project form deals with project envs and cr env interaction

---

src/lib/features/feature-lifecycle/fake-feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store-type.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/features/instance-stats/instance-stats-service.ts
src/lib/metrics.test.ts
src/lib/metrics.ts
src/lib/routes/admin-api/instance-admin.ts
src/lib/types/experimental.ts
src/lib/types/model.ts

Now we are also sending project id to prometheus, also querying from database. This sets us up for grafana dashboard.
Also put the metrics behind flag, just incase it causes cpu/memory issues.

feat: add project id to prometheus and feature flag

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyNonDraggableItem.tsx
frontend/src/hooks/usePagination.ts
frontend/src/hooks/usePlausibleTracker.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

This fixes the case when a customer have thousands of strategies causing the react UI to crash. We still consider it incorrect to use that amount of strategies and this is more a workaround to help the customer out of a crashing state.
We put it behind a flag called `manyStrategiesPagination` and plan to only enable it for the customer in trouble.

poc: many strategies pagination

---

package.json
src/lib/create-config.ts

We'd like to get this out so you can get away with only defining a CA certificate, the current iteration requires CA, CERT and KEY in order to work. This PR splits it up and allows you to configure one.

feat: Allow to use CA certificate file path for DB (#6985)

---

src/lib/db/index.ts
src/lib/features/feature-search/createFeatureSearchService.ts
src/lib/features/feature-search/feature-search-store.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/openapi/spec/feature-search-response-schema.ts
src/lib/types/model.ts
src/lib/types/stores.ts
src/test/fixtures/store.ts

Each feature in project overview search will have a lifecycle with current stage and entered date similarly to single feature query.
I'm adding this new capability behind a flag so that we can safely roll it out.

feat: expose lifecycle stage in project overview search

---

frontend/src/component/common/GeneralSelect/GeneralSelect.tsx
frontend/src/component/project/Project/CreateProject/ChangeRequestTable.tsx
frontend/src/component/project/Project/CreateProject/SelectionButton.styles.tsx
frontend/src/component/project/Project/CreateProject/SelectionButton.tsx

This PR visually hides the labels in the new create project form. They're still rendered for screen readers, however.
It means it looks like this now:

Chore: visually hide labels in the create project form

---

frontend/src/component/project/Project/CreateProject/CreateProjectDialog/CreateProjectDialog.tsx

It seems the code that was copied was copied from before we changed
the validation logic, so it wouldn't submit. This fixes that to remove
any ID validation in the new form.

fix: make the project submission work from the project creation modal

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/populateCurrentStage.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
frontend/src/interfaces/featureToggle.ts
src/lib/features/feature-lifecycle/fake-feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle-read-model.ts
src/lib/features/feature-lifecycle/feature-lifecycle-store.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts
src/lib/features/feature-lifecycle/get-current-stage.test.ts
src/lib/features/feature-search/feature-search-store.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/openapi/spec/feature-lifecycle-schema.ts
src/lib/openapi/spec/feature-search-response-schema.ts
src/lib/types/model.ts

* Adding status information to stages
* Modifying single feature read model and search query
* Modelled field as optional but when the field is present it's not null 
* Making lifecycle UI display when lifecycle is present (previously we had as short window where lifecycle had no value after new feature creation)

feat: kept and discarded read model

---

src/lib/db/setting-store.ts
src/lib/metrics.ts
src/lib/services/version-service.ts
src/lib/types/stores/settings-store.ts
src/test/fixtures/fake-setting-store.ts

Adds a postgres_version gauge to allow us to see postgres_version in prometheus and to post it upstream when version checking. Depends on https://github.com/bricks-software/version-function/pull/20 to be merged first to ensure our version-function doesn't crash when given the postgres-version data.

feat: expose postgres version

---

frontend/src/component/feature/FeatureStrategy/featureStrategy.utils.ts
frontend/src/utils/deepOmit.test.ts
frontend/src/utils/deepOmit.ts

When computing stale data e.g. on strategy edit we need to omit yes/no counts same way we do it for lastSeenAt.
Expanded deepOmit function to support multiple keys.

fix: omit yes no from stale data comparison

---

website/docs/feature-flag-tutorials/serverless/implementing-feature-flags-in-aws-lambda.md

Closes #
Updates according to our revision doc for our horizontal content pieces.

doc: Optimizing AWS Lambda Documentation

---

src/lib/app.ts

Current state, when returning the HTML entry point from the server, there are no headers attached. We encountered an issue with a deployment and this had an impact for us.
A brief description:
1. We deployed the most recent version. Noticed an unrelated issue.
2. Users tried to use the most recent version and due to their client cache, requested assets that did not exist in the newest version.
3. Our cache layer cached the assets that were not there with the HTML response. It had to infer the type based on the filename because there was no attached `Content-Type` header. This cache was very sticky.
4. After rolling back we saw the HTML response (from the cache) instead of the appropriate response from the upstream Unleash application.
This PR does a few things.
1. When responding with the …

fix: Add appropriate response headers to SPA entry point HTML response

---

frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts
website/docs/reference/feature-toggle-variants.md

Variants tab will be hidden for new features and feature that don't use environment variants. 
We'd like to encourage the usage of the strategy variants. Env variants are still kept for the features that already use them for backwards compatibility.
Variants in this tab will be gone for new features and existing features without env variants
We also have a sunset flag called "enableLegacyVariants" that can be used to enable environment variants even for the new features.
This PR also updates docs with a deprecation notice.
Next PR will be created to block environment variants in the backend API.
Original PR https://github.com/Unleash/unleash/pull/7054 was working at the instance level but we found that feature level deprecation is more versatile and simpler.

feat: deprecate feature toggle variants at environment level

---

.github/workflows/publish-new-version.yaml
.github/workflows/update_version_for_version_checker.yml
package.json

Automate some of our release steps in the same workflow. This gives us the ability to opt-out some of the jobs which allows us to release patches to older versions without setting that patch as the latest version (currently not covering docker publish but if this test works successfully we might include it as well). 
This comes from tests in our enterprise repository.

chore: automate release actions

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/EditDefaultStrategy.test.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/EditDefaultStrategy.tsx

First click on add strategy didn't respect the default strategy. Subsequent ones did. The reason for that is useEffect didn't observe the default strategy being updated from no strategy to actual strategy from the API. 
Also, updated useProject to useProjectOverview which is part of the useProject deprecation. They are almost the same. The only difference is project overview doesn't read all project features which we don't need here to read env default strategy. 
Since we're observing all changes to the default strategy it means that if I'm editing a strategy and the default project environment strategy changes my edits are erased and I have to start from scratch. I'm assuming that default strategy changes are so rare it shouldn't be a problem and more complex logic is not justified.

fix: new strategy using default strategy

---

frontend/src/component/App.tsx
frontend/src/component/banners/OutdatedSdksBanner/OutdatedSdksBanner.test.tsx
frontend/src/component/banners/OutdatedSdksBanner/OutdatedSdksBanner.tsx
frontend/src/component/project/Project/ProjectOverview.tsx
frontend/src/hooks/api/getters/useOutdatedSdks/useOutdatedSdks.ts

At first, I was creating a new component, Project Banner, which was 90% of the old banner and 10% new code, but it did not feel right. The current banner is actually smart enough to be used in any container. So now, I have moved the outdated SDK banner to the project level.
I like the simplicity of the change.

feat: project level outdated sdks, project level banner

---

frontend/src/component/insights/componentsChart/MetricsSummaryChart/MetricsChartTooltip/MetricsChartTooltip.tsx

To get correct formatting to number, in our codebase we call toLocaleString(). Added it also to this component.
From
To

fix: make numbers in chart to locale string

---

frontend/src/component/changeRequest/ProjectChangeRequests/ProjectChangeRequests.tsx
frontend/src/component/project/Project/ProjectFeaturesArchive/ProjectFeaturesArchive.tsx
frontend/src/component/project/Project/ProjectHealth/ProjectHealth.tsx
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestConfiguration.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectSegments/ProjectSegments.tsx
frontend/src/component/project/ProjectAccess/ProjectAccess.tsx
frontend/src/component/project/ProjectEnvironment/ProjectEnvironment.tsx
frontend/src/hooks/api/getters/useProject/useProject.ts

`useProjectNameOrId` calls `useProject` under the hood. We use the `useProjectNameOrId` to get page titles so we don't need to fetch all features. Also we gonna remove `useProject` soon so it's a step in this direction.

fix: deprecate useProjectNameOrId

---

src/lib/features/access/createAccessService.ts
src/lib/services/access-service.test.ts
src/lib/services/access-service.ts

This is preparation, so we do not need to define an `isAdmin` method in the change request context.

feat: add global isAdmin method for access service

---

frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx

Fixes a bug that would display the overage warning on network/traffic-usage when included traffic was 0. (it assumed all traffic was overage)

fix: also check includedTraffic before calculating overage and showing warning

---

src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts

Adding feature name check when reaching a certain lifecycle stage to check if we're looking at the right thing.

test: fix flaky lifecycle test

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/useShowDependentFeatures.ts

Check if project is provided because we don't want hooks making 404 requests during initial data load for the project.

fix: no requests before project loaded

---

frontend/src/component/project/Project/CreateProject/CreateProjectDialog/CreateProjectDialog.tsx
frontend/src/component/project/Project/hooks/useProjectForm.test.ts
frontend/src/component/project/Project/hooks/useProjectForm.ts

I realized that, in an oversight, the form now shows and sends project CR config, even if the new form isn't active. The API just ignores it if it doesn't understand it, so it's not very harmful, but it's better if we don't send it at all. This PR does that.
It does not actually test that change request info isn't included (but it does test ID inclusion). This is because:
- change request info is only included if we're enterprise. The rendered version of the hook isn't by default.
- Setting up module mocking and making it work seems like a lot of work for a small gain, considering we're probably going to be removing the old form anyway.
- I've tested it locally.
Also adds some testing for the hook related to name validation and payload creation

fix: don't send change request info unless using the new form

---

frontend/src/component/common/FormTemplate/FormTemplate.tsx
frontend/src/component/project/Project/CreateProject/CreateProjectDialog/CreateProjectDialog.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/DeleteProjectForm.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/UpdateEnterpriseSettings.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/UpdateProject.tsx

I've marked the project creation dialog as "compact", so that it's only as tall as it needs to be.
However, by default, compact forms don't scroll because they have overflow set to hidden. This is a problem on very short windows. To get around this, I've set overflow to unset on compact forms.
I've also removed `min-height: 0` which has some weird side effects on the centered dialog. Instead, I'm setting `min-height` to `unset` if it's compact.
This task also uncovered some inconsistencies and some borders that only show up sometimes, so I've removed them too.

fix: make dialog the right height and make it scroll if it's smaller

---

frontend/src/component/project/Project/CreateProject/SelectionButton.styles.tsx

This ensures that the dropdown items without checkbox are the same height as the dropdown items with checkbox.

fix: set min-height on dropdown item list

---

frontend/src/assets/icons/projectIconSmall.svg
frontend/src/component/common/FormTemplate/FormTemplate.tsx
frontend/src/component/project/NewProjectCard/NewProjectCard.styles.ts
frontend/src/component/project/Project/CreateProject/CreateProjectDialog/CreateProjectDialog.tsx
frontend/src/component/project/Project/CreateProject/NewProjectForm.tsx

Adds icons to sidebar documentation and removes the link when you can't interact with it.
I'm a little concerned that this won't be very accessible at the moment, because we don't announce that anything has changed (i.e. there's no way to find out that the text has changed if you can't see it), and the text isn't labeled as describing anything. (this is being addressed in #7110 )
There's a few caveats to this:
1. we don't set a min height at the moment. I've avoided this because we use the sidebar a number of other places and I wanted to touch as little as possible. This means we can still get height adjustments
2. The new project icon doesn't have the same proportions as the mui icons. This adds some additional jank. We should probably look at this, though.

feat: show docs with icons in sidebar

---

frontend/src/component/project/Project/CreateProject/SelectionButton.tsx

We have this very specific edge case in the new project form
dropdowns. It only occurs for the single-select lists and only if you
select an item via search.
When the search input is non-empty, you can use enter to select the
first item in the list.
For some reason, this also triggers a click on the underlying button
that opens the dropdown (I'm guessing this is to do with an underlying
focus).
To work around it, we create a variable that prevents you from opening
the dropdown if it is true. We set it to 'true' when you close it (for
single-selects), but also set single-millisecond timeout that sets it
to false thereafter.
This is much to short for the user to notice anything, but it prevents
the browser from noticing the click.

fix: prevent single-select lists from reopening when you select an item from the search bar

---

frontend/cypress/integration/feature/feature.spec.ts
src/migrations/20240523113322-roles-toggle-to-flag-rename.js
src/test/e2e/favor-permission-name-over-id.e2e.test.ts

Running migration to update roles descriptions.

chore: rename roles toggles to flag

---

frontend/src/component/layout/MainLayout/MainLayout.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx

* Reading plan specific navigation (different for OSS, pro and enterprise). Re-using existing method wrapped in a hook encapsulating the details
* Showing enterprise badge (ported existing functionality)
* added some missing icons (cors, billing)
* extracted icons lookup that will probably land in routes config eventually
* hiding new menu on small screens for now to avoid breaking responsive layout. Later I will wrap it in a drawer for mobile.

feat: plan specific navigation

---

website/docs/feature-flag-tutorials/dotnet/dotnet-examples.md
website/docs/feature-flag-tutorials/dotnet/implementing-feature-flags-dotnet.md
website/sidebars.js

Another one for you @daveleek 🙏

.NET examples

---

frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx

New layout requires CR banner stretch with the wider top nav
Previous layout had CR banners in the middle

feat: adjust change request banner for new layout

---

src/lib/error/bad-data-error.ts
src/lib/error/incompatible-project-error.ts
src/lib/error/password-undefined.ts
src/lib/error/project-without-owner-error.ts
src/lib/error/unleash-error.test.ts
src/lib/error/unleash-error.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/features/project-environments/environments.e2e.test.ts
src/lib/features/tag-type/tag-types.e2e.test.ts
src/lib/routes/admin-api/strategy.test.ts
src/test/e2e/api/admin/api-token.e2e.test.ts
src/test/e2e/api/admin/project/variants.e2e.test.ts
src/test/e2e/api/admin/tags.e2e.test.ts
src/test/e2e/api/admin/user-admin.e2e.test.ts
src/test/e2e/api/auth/reset-password-controller.e2e.test.ts

In preparation for v6, this PR removes usage and references to `error.description` instead favoring `error.message` (as mentioned #4380)
I found no references in the front end, so this might be (I believe it to be) all the required changes.

chore!: [v6] remove error.description in error messages

---

src/lib/db/group-store.ts
src/lib/features/metrics/instance/instance-service.ts
src/lib/services/access-service.test.ts
src/lib/services/addon-service.test.ts
src/lib/services/feature-service-potentially-stale.test.ts
src/lib/services/group-service.ts
src/test/e2e/api/admin/event.e2e.test.ts
src/test/e2e/services/group-service.e2e.test.ts
src/test/e2e/stores/event-store.e2e.test.ts
src/test/fixtures/fake-event-store.ts

This aligns us with the requirement of having ip in all events. After tackling the enterprise part we will be able to make the ip field mandatory here: https://github.com/Unleash/unleash/blob/2c66a4ace44e3553195f45a8eafa0d19ca26113c/src/lib/types/events.ts#L362

feat: add remote ip to all events (2)

---

frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx
frontend/src/component/menu/Header/Header.tsx
frontend/src/component/user/UserProfile/UserProfile.tsx
frontend/src/component/user/UserProfile/UserProfileContent/UserProfileContent.tsx

Moving user profile info (name and email) from behind the avatar to the top bar. This change is not flagged since it looks good for current and new code. The new profile is modelled as a button so that keyboard navigation works fine.
Current desktop view (username and profile removed from the dropdown and added to top bar):
New desktop view (divider between icons and new profile):
Current and new mobile view (identical): <img width="591" alt="Screenshot 2024-05-24 at 15 39 13" src="https://github.com/Unleash/unleash/assets/1394682/3f48ca38-f85b-4b12-b81b-de9de782a2c1">
Also works with very long names and emails:

feat: user profile preview

---

frontend/src/component/common/FormTemplate/FormTemplate.tsx
frontend/src/component/project/Project/CreateProject/CreateProjectDialog/CreateProjectDialog.tsx
frontend/src/component/project/Project/CreateProject/NewProjectForm.tsx
frontend/src/component/project/Project/CreateProject/SelectionButton.tsx

This PR addresses several related fixes to the new project creation dialog to prevent unnecessary growing and shifting:
- use a fixed width for the guidance sidebar
- use a fixed height for the guidance code snippet
- use a fixed height for the mobile guidance
- use a fixed width for the mode selector button
- cap description height
This is a little tricky because we don't want the changes for the dialog to affect other forms. As such, I've added some new options you can use when you create the guidance components / sidebar.

chore: new create project dialog UI fixes

---

frontend/src/component/project/Project/CreateProject/NewProjectForm.tsx

This change makes the CR button wider when you have environments
selected, reducing the difference between "no environments" and "envs
configured" states, thereby reducing the difference in the layout.

fix: make CR button wider always

---

frontend/src/component/project/Project/CreateProject/NewProjectForm.tsx

This commit sets the width of the environment selector button to a
fixed width (wide enough to display "all environments").

chore: fix create project form environment selector button width

---

frontend/src/component/project/Project/CreateProject/NewProjectForm.tsx

This change makes it so that the button for change request
environments reads correctly when:
1. You have no envs configured: "Configure change requests"
2. One env configured: "1 environment configured"
3. More than one env configured: "`n` environments configured"

fix: change request environment selector button label

---

.github/workflows/build_frontend_prs.yml
frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingPlan.tsx

Summing on Billing page got a little wonky after changing how the summing worked when the estimation flag is off. This attempts to return it to previous way of showing numbers when flag is off
If you go directly to the billing page it will not add user calculations to the total. If you however interact with the UI, like change tabs back and forth, it will suddenly show the correct sum:

fix: attempt a react friendly fix of summing

---

frontend/src/component/project/Project/CreateProject/SelectionButton.tsx

This change makes the button label for the CR selector in the new
project creation form have a fixed width. It adds a missing wrapper
element.

fix: use a fixed-width button label for CR selector in new project creation form

---

src/lib/routes/admin-api/config.test.ts
src/lib/routes/admin-api/config.ts

Upgrading banner to 19.1.3, because we fixed critical issue there.

chore: upgrade edge banner version

---

frontend/src/component/project/Project/hooks/useProjectForm.test.ts
frontend/src/component/project/Project/hooks/useProjectForm.ts

This PR allows you to configure change requests for all environments when no environments are enabled explicitly. This is the default state of the form and makes it so that you can configure CRs even if you want all envs enabled.
Additionally, it preserves the case where you configure CRs for an environment and then disable all envs.
This is logic only. It's not available in the UI yet.

chore: allow CR selection when no envs are enabled

---

frontend/src/component/layout/MainLayout/NavigationSidebar/IconRenderer.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/ListItems.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationList.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.test.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx
frontend/src/component/layout/MainLayout/NavigationSidebar/useInitialPathname.test.ts
frontend/src/component/layout/MainLayout/NavigationSidebar/useInitialPathname.ts

Adding a marker for the currently selected item. Works for full and mini sidebar.
The tricky part is to set the initial value. I created a hook `useInitialPathname` that takes the URL and extracts the top level navigation part of the URL. E.g. /project/my-project should normalize to /project for the sidebar active item selection.

feat: currently selected nav item

---

frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/ConfigButton.styles.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/CreateProjectDialog.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/NewProjectForm.styles.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/NewProjectForm.tsx

This PR contains a few fixes for button designs on small screens for the new project form.
It makes all buttons (config and actions) full-width and addresses some sizing stuff.
It also caps the width of the stickiness button on non-small screens to avoid shifting.

chore: fix button design on narrow screens for new project form

---

frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/CreateProjectDialog.tsx

This PR hides horizontal overflow in the dialog.
The pop-up docs that we have on small windows was causing a tiny bit of overflow, giving us an annoying (and pretty useless) horizontal scrollbar. We can hide that scrollbar by hiding horizontal overflow.

fix: get rid of horizontal scrollbar on narrow screens in CreateProjectDialog

---

src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/legacy/feature-toggle-legacy-controller.ts

Removes unused and deprecated methods in feature toggle legacy controller (methods not having an endpoint)
Removes unused and deprecated methods in feature toggle service (methods not in use in Unleash)

chore: remove unused and deprecated methods in feature toggle legacy controller and in feature toggle service

---

frontend/src/component/menu/Footer/Footer.tsx
frontend/src/component/menu/Footer/__snapshots__/Footer.test.tsx.snap

Footer component overflows the main content making some elements e.g. hide/expand not clickable. Instead of zIndex escalation I prefer to prevent the overflow. 
Root cause:
Footer uses mui grid. The grid has a negative margin. The negative margin comes from the spacing property on the grid. It has this behavior: https://github.com/mui/material-ui/issues/10223. We could also remove the spacing and set it to 0 but the spacing is needed for keeping footer elements apart vertically and we can live with the horizontal impact of the negative margin once we hide it behind overflow hidden.

fix: footer overflow

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ChangeOverwriteWarning/strategy-change-diff-calculation.test.ts
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ChangeOverwriteWarning/strategy-change-diff-calculation.ts

This change fixes a bug where we would show the list of segments as
changed (causing a conflict) if their order wasn't the same in the
change as in the original.
By sorting the segments before comparing them, we can avoid this issue.
To avoid modifying the objects that are passed in (in case that has knock-on effects anywhere), we copy the objects. And because `toSorted` "only" has about 89% coverage now, I chose to use `sort` and spread the arrays instead.

fix: sort segments before comparing in cr diff calculations

---

frontend/src/component/insights/hooks/useFilteredFlagsSummary.test.ts
frontend/src/component/insights/hooks/useFilteredFlagsSummary.ts
src/test/e2e/api/admin/playground.e2e.test.ts

We have an issue that if you open up Insights, the Time to Production chart was showing nothing because it was taking the median across all projects. You might have many new or empty projects where the median was 0 (no data).
For example, the median from [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.7, 50.3, 140] was 0.
Now, we will remove the 0 values to have a more reasonable median.

fix: when finding median time to production, ignore 0s

---

website/docs/contributing/ADRs/front-end/preferred-styling-method.md

This change adds a section on when to use `sx` vs `styled`. I'm adding
it because it was unclear to me when we should use one over the other.
Hopefully this clears it up and makes it easier for others going forward.

docs: add more clarification on when to use sx vs styled

---

frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/ChangeRequestTableConfigButton.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/ConfigButton.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/MultiSelectConfigButton.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/SingleSelectConfigButton.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/NewProjectForm.tsx

This PR adds tooltips to the new project creation form buttons to make it clearer what they do. The tooltips tell you what the buttons do and contains the same description that we use for docs.
The tooltips will cover other buttons on narrow windows, but I think that's an acceptable tradeoff

feat: add tooltips to new project creation form config buttons

---

frontend/src/component/project/NewProjectCard/ProjectCardFooter/ProjectCardFooter.tsx
frontend/src/component/project/NewProjectCard/ProjectOwners/ProjectOwners.tsx

This change updates the new project card footer to better handle long
names. Previously, if a name was too long to fit on a single line,
it'd wrap. It didn't cause any layout shift, but it made the card look
off.
So instead of wrapping, we now truncate the name and add an ellipsis.
To achieve this, I changed the layout to grid instead of flexbox and
removed a nested flex container.
Before: 
After:
Other cards remain the same, as shown here (new code on left, old code on right):

fix: handle long owner names for projects

---

frontend/src/component/project/NewProjectCard/ProjectCardFooter/ProjectCardFooter.tsx
frontend/src/component/project/NewProjectCard/ProjectOwners/ProjectOwners.tsx

This is a redo of  #7215. I missed the case where you have multiple owners, causing it to lay out weird in that case.
This version handles that by returning an empty div for the owners instead to fill up that space.
There **are** edge cases where the owners wrap:
But that is also the case with the current implementation:
And only happens at very specific breakpoints.

fix: handle long names in new project card footers

---

src/lib/services/group-service.ts
src/test/e2e/services/group-service.e2e.test.ts

After an internal conversation, we concluded that syncExternalGroups is an action that Unleash performs as a system, not something triggered by the user. We keep the method and just write the event log that the action was performed by the system user.

chore: sync user groups is a system action

---

frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCardAvatars/NewGroupCardAvatars.tsx
frontend/src/component/project/NewProjectCard/ProjectOwners/ProjectOwners.tsx

This change prevents the project owner avatars in the new project card
footer from overflowing by making the number of avatars to show
configurable.
It defaults to 9, the old hard-coded number of avatars shown, but can
be configured.
The reason it overflows here is probably that the extra button in the
project card footer (the favorite) makes the footer smaller than what
we have for the group card footer.
Before: 
After:

fix: handle overflowing avatars in the new project card

---

.github/workflows/dependency-review.yml

To help with compliance with customer's OSS requirements, this now bans usage of GPL and LGPL, as well as scans PRs for dependency vulnerabilities and new licenses being added.

chore: added dependency review

---

src/lib/openapi/spec/client-application-schema.ts
src/lib/openapi/spec/client-features-query-schema.ts
src/lib/openapi/spec/create-api-token-schema.ts
src/lib/openapi/spec/feature-schema.ts
src/lib/openapi/spec/feature-search-response-schema.ts
src/lib/openapi/spec/user-schema.ts

Makes some deprecation messages in open API clearer around which version they were deprecated in so that they can be removed in v7

chore: mark deprecations with version

---

frontend/src/component/project/NewProjectCard/NewProjectCard.styles.ts

This change updates the styling of the project card bodies so that
alignment of the project data (number of flags, members, health) stays
at the bottom of the project card body, even if some cards have longer
bodies than others. It also updates the icon placement so that it is consistent even when the title is multi-line.
Before this change, the bottom row would be misaligned if some (but
not all) project cards on a row had names long enough to span multiple lines. The project icon would also be misaligned
Before:
Misaligned project icon: 
After:
Icon alignment:

fix: correctly align project card info when some cards have multi-line names

---

frontend/src/component/project/ProjectList/ProjectList.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

This PR removes all the feature flags related to the project list split and updates the snapshot.
Now the project list will always contain "my projects" and "other projects"

chore: remove project list split feature flags

---

Dockerfile

As the title says, bumps from 20.13.1 to 20.14.0 to ensure v6 gets the latest and greatest next week

chore: bump node 20 version in docker image

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/events.ts

IP should be mandatory for storing events. Automated events should use 127.0.0.1

chore: make ip mandatory

---

src/lib/features/metrics/instance/instance-service.ts

This leaks potential pii information in the event log. Instead of that we're using the system user

fix: Created by on application-created adds the ip as created by

---

src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/features/export-import-toggles/import-data.json
src/lib/features/export-import-toggles/import-file-reader.ts
src/lib/util/read-file.ts

- Makes readFile a generic utility
- Uses fs/promises in readFile
- Adds a e2e file import test

chore: change to fs/promises and add an import from file e2e test

---

package.json
yarn.lock

https://github.com/isaacs/node-tar/compare/v6.1.11...v6.2.1
This solves an issue:
> ### Denial of service while parsing a tar file due to lack of folders count validation
> 
> During some analysis today on npm's node-tar package I came across the folder creation process, Basicly if you provide node-tar with a path like this ./a/b/c/foo.txt it would create every folder and sub-folder here a, b and c until it reaches the last folder to create foo.txt, In-this case I noticed that there's no validation at all on the amount of folders being created, that said we're actually able to CPU and memory consume the system running node-tar and even crash the nodejs client within few seconds of running it using a path with too many sub-folders inside

fix: resolve tar to 6.2.1

---

.github/workflows/docker_publish.yaml
.github/workflows/release.yaml
.github/workflows/release_changelog.yml
package.json

Use the tag created by the build action when running npm version, otherwise the checkout actions gets the HEAD of the commit that triggered the original workflow resulting in the usage of the previous version.
Potentially in the future, instead of triggering the build manually we could consider using the tag as a trigger for the build process and then all the dependent workflows should work fine. It's good we have this manual for validation, and we workaround some of the limitations before we invest more into more automation

chore: improve release process

---

frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.test.tsx
frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.test.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx

Making tags in project overview clickable to add tag filters with one click:
Details:
* tags are modelled as buttons so that keyboard navigation works
* tags within "more tags" section are also clickable
* clicking same tag is idempotent
* clicking for the first time adds include tag operator
* clicking for the second time keeps the existing operator
* styling button similarly to the previous div

feat: clickable tags in project overview

---

frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/TagsInput.tsx

When opening a dialog where there's previously selected tags, also
render the previously selected tags.
This is consistent with how we do it for bulk tags.
So instead of showing this when you open the tag manager on a flag with existing tags:
We show this:

fix: display previously selected tags in dialog

---

frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/TagsInput.tsx

1. Only suggest to create a tag value if the input is more than two
characters after trimming.
2. Ignore trailing and leading whitespace when considering which autocomplete options to show

fix: trying to create a tag that's too short gives errors

---

frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/ChangeRequestTableConfigButton.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/ConfigButton.styles.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/ConfigButton.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/MultiSelectConfigButton.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/SingleSelectConfigButton.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/NewProjectForm.styles.tsx
frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/NewProjectForm.tsx

This change adds information about the project modes to the new
project creation form, using the tooltip for project creation modes.
In doing so, it updates the config button tooltip to accept extra
elements and adds styling for them.
What it looks like: 
This solution does present one problem: the popover doesn't get focus, so it's impossible for you to scroll with only a keyboard. However, this is something that's present in Unleash already, and not something that I think would be easily solvable, so I don't think this is when we should solve it.

feat: adds information about project modes to the project creation form

---

frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCardAvatars/GroupPopover/GroupPopover.tsx

This PR fixes a bug where if you navigated to the projects page via the menu, scrolled down, and hovered over a project's avatars, you'd be scrolled to the top of the page when you moused off the avatar.
Turns out this issue was also in the group cards. It seems to be that the popover attempts to restore focus back to where you where, which, if you navigated via the menu, is at the top of the page. Because these popovers don't have any focusable content, we can disable that functionality.
Additionally, I've disabled the scroll lock when the popover is open. The scroll lock made it impossible to scroll when one of the popovers is open, which is confusing as a user.

fix: involuntarily scrolled to the top when mousing off group/project avatars

---

src/lib/features/feature-search/feature-search-store.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/openapi/spec/feature-search-response-schema.ts
src/lib/openapi/spec/user-schema.ts
src/lib/types/model.ts

Adding created by section with id, name and avatar img for the search results. Search table will have a user avatar (next PR)

feat: add created by in search results

---

frontend/src/component/common/VerticalTabs/VerticalTabs.tsx

Stop project settings tables from overflowing. Some tables (e.g. API tokens) in the project settings had px based min width that is overflowing after we added a sidebar. I'm adjusting the breakpoint for mobile view a bit earlier. We could also consider not using px based min width and use % based width instead.
Before (on 1500px, type, created and other columns push the content out of the parent container):
After (on 1500px):

fix: project settings table overflow

---

website/docs/using-unleash/deploy/upgrading-unleash.md

This include some notes about the migration guide based on https://github.com/Unleash/unleash/issues/4380
Initially, we don't expect any breaking change provided users are not using deprecated functionality.
Preview notes: https://unleash-docs-git-v6-upgrade-notes-unleash-team.vercel.app/using-unleash/deploy/upgrading-unleash#upgrading-to-v6-from-v5

docs: v6 upgrading notes

---

frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx
frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx

What the title says. There are input values that are whitespace sensitive, so this will trim clientId and entity field, preventing the form from sending leading or trailing whitespace. Will make a PR on enterprise as well to trim on the backend as well.

fix: trim sso URL fields

---

frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx
frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx

What the title says. There are input values that are whitespace sensitive, so this will trim clientId and entity field, preventing the form from sending leading or trailing whitespace. Will make a PR on enterprise as well to trim on the backend as well.

fix: trim sso URL fields (#7301)

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.test.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/hooks/useDefaultColumnVisibility.ts
frontend/src/interfaces/uiConfig.ts
frontend/src/openapi/models/featureSearchResponseSchema.ts
frontend/src/openapi/models/featureSearchResponseSchemaCreatedBy.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/feature-search/feature-search-store.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/openapi/spec/feature-search-response-schema.ts
src/lib/types/experimental.ts
src/server-dev.ts

Displaying columns with created by user:
Currently we show avatar and user name + id on hover.
Next PR:
* extract and reuse on hover component from the project overview
* add filter by user id backend (new filter in search and list of all users who created features in this project) and UI component
Should we put it behind a dedicated flag? It's a new table column that's visible by default on large screens.

feat: display created by user in search

---

src/test/e2e/api/admin/tags.e2e.test.ts

This change adds a test to the tags API to ensure that even if you
can't create tags that are pure whitespace anymore, you'll still
receive pre-existing tags from the API that fit this description.
The test is here to ensure that we don't break this in future versions
of Unleash.

chore: test that the tags API still returns tags that you can't create anymore

---

src/lib/features/feature-lifecycle/feature-lifecycle-service.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts
src/lib/features/metrics/client-metrics/metrics-service-v2.ts
src/lib/types/events.ts

CLIENT_METRICS is emitted too often to update lifecycle as a result. Piggybacking on the bulk insert of metrics into a DB with a new event CLIENT_METRICS_ADDED

fix: lifecycle metrics on metrics insert

---

frontend/src/component/common/UserAvatar/UserAvatar.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx

This change makes the width of the user avatar configurable via a new
"avatarWidth" property.
It also sets the width to be `theme.spacing(3)` (currently 24px) for the feature flag table.
It looks like this now:
It used to look like this:

chore: make the User Avatar size configurable

---

frontend/.gitignore
website/.gitignore

This PR is a follow up to #7333. It appears that the `.gitignore` file in the root of the repository is not ignoring the yarn files in the `/frontend` and `/website` directories.
This PR adds those.
Because the patterns contain slashes, they're interpreted as being relative to the root directory, as mentioned the description of the [gitignore format](https://git-scm.com/docs/gitignore#_description) in the official git docs:
> If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.

chore: add gitignores to frontend and website subdirectories

---

website/docs/reference/scim.md
website/sidebars.js

Moves the docs at refence/provisioning to reference/scim because there's already a reference to /scim in our source code.

docs: move provisioning reference to scim reference

---

frontend/src/component/common/UserAvatar/UserAvatar.tsx
frontend/src/component/common/UserAvatar/UserAvatarWithPopover.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx

This PR adds a popover to the user avatars in the flag list.
The popover is similar to the one used for projects and groups, but it differs in a few ways:
- There's less padding. There's quite a lot of padding in the other popovers, and it felt like too much for this table.
- It only shows one bit of text (the user's name/username/email). The other popovers show email and name/username, but we don't have all that information, so this is a stripped down version.
Flag list popover:
Group popover:
or if no email

feat: add popover to users in flags list

---

frontend/src/component/project/Project/ProjectInsights/ProjectInsightsStats/ProjectInsightsStats.tsx

Removed stale stats widget that had incorrect data

fix: remove stale stats widget

---

frontend/src/component/common/PermissionSwitch/PermissionSwitch.tsx

This PR changes the environment permission switch to use the HTML tooltip instead of the default MUI tooltip. This aligns with how we've been doing tooltips recently.
The main driver behind this change was that the project flag table used two different tooltips. This makes it so that they all look the same, but it also impacts other places that use the same switch.
In feature flag table:
On flag page:
In project env table:

chore: use HTML (custom) tooltip for permission switches

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/AvatarCell.test.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/AvatarCell.tsx

This PR disables the filtering capability in the front end for unknown users.
Modifying the back end to support filtering for unknown users is not something we want to do yet. It's possible, but it requires adding a lot of special cases to the handling code (refer to [PR #7359](https://github.com/Unleash/unleash/pull/7359)), which we'd like to avoid if possible. To avoid annoying cases where the filtering doesn't work as expected and breaks user expectations, we're disabling the filtering capability for unknown users in the front end.
We can consider whether to enable back-end results for unknown users in the future if we get user feedback that it's important.
This PR works by changing the avatar cell component. When the user has id 0 (and is therefore unknown), we:
- set aria-disabled to …

chore: disable filtering for unknown users

---

frontend/src/component/commandBar/CommandBar.tsx
frontend/src/component/commandBar/RecentlyVisited/CommandResultGroup.tsx
frontend/src/component/feature/FeatureToggleList/useGlobalFeatureSearch.ts

Now searching works in command bar
1. Currently piggybacking on the search hook, but I think it is not fast enough, and also it is using the query params as the global search. This causes some weird behaviour in UI. This probably means we will create separate endpoint for this.

feat: search features from command bar

---

src/lib/features/feature-search/feature-search-store.ts
src/lib/features/feature-search/feature.search.e2e.test.ts

Instead of running exists on every row, we are joining the exists, which runs the query only once.
This decreased load time on my huge dataset from 2000ms to 200ms.
Also added tests that values still come through as expected.

feat: optimize search store by removing inline EXISTS

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.test.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx

We were missing projectId on 3 lifecycle buttons: mark completed, revert and archive. 
Also fixed styling for locked buttons. Previously they were growing and moving text in another line. Now we move the second button to the next line.

fix: lifecycle button permissions

---

frontend/src/component/commandBar/CommandBar.tsx

Previously since query params were changing by global search, and menubar was also altering them, they were conflicting. Menubar does not need query params as state. So using search hook directly.

feat: menubar is not dependant on query params anymroe

---

src/lib/features/client-feature-toggles/tests/client-feature-toggles.e2e.test.ts
src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/tests/feature-toggle-strategies-store.e2e.test.ts

This moves the defaults parameters check for adding strategies to target the correct name for gradual rollout strategies. Previously we checked for `gradualRollout` but actually on the backend/SDKs the strategy name is `flexibleRollout`.
Tests have been updated but tested by checking against the API call the UI suggests and cURLs.

fix: make default for gradual rollout work on the correct strategy name

---

src/lib/features/feature-toggle/fake-feature-strategies-read-model.ts
src/lib/features/feature-toggle/feature-strategies-read-model.ts
src/lib/features/feature-toggle/tests/feature-toggle-strategies-store.e2e.test.ts
src/lib/features/feature-toggle/types/feature-strategies-read-model-type.ts
src/lib/metrics.ts

This PR adds metrics tracking for:
- "maxConstraintValues": the highest number of constraint values that are in use
- "maxConstraintsPerStrategy": the highest number of constraints used on a strategy
It updates the existing feature strategy read model that returns max metrics for other strategy-related things.
It also moves one test into a more fitting describe block.

chore: add metrics/gauges for "max constraint values" and "max constraints"

---

frontend/src/component/project/ProjectList/ProjectList.tsx

This change takes the rendering of the new project form component and
puts in a child component of the project list, thereby
significantly speeding up the time it takes to render the form if you
have lots of projects (about to 10x for 50 projects on my machine).
The reason it was so slow before was that the open state of the form
component was stored in the project list component. This meant that
whenever you wanted to open or close the form, you'd have to rerender
the entire project list.
This change abstracts that process into the new ProjectCreationButton
component. This component takes care of checking the feature flag for
whether to render the dialog or to send the user to the old form, and
takes care of state management for the dialog.
Because this is a child component of the …

fix: make rendering of new project form independent of rendering the project list

---

frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx
src/lib/features/project/project-service.e2e.test.ts
src/lib/features/project/project-service.ts

Fix project role assignment for users with `ADMIN` permission, even if they don't have the Admin root role. This happens when e.g. users inherit the `ADMIN` permission from a group root role, but are not Admins themselves.

fix: check for permission in group access assignment

---

package.json
yarn.lock

Bumps `unleash-client` to the latest 5.5.5.

chore: bump unleash-client to 5.5.5

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/project/project-owners-read-model.test.ts
src/lib/features/project/project-owners-read-model.ts
src/lib/features/project/project-owners-read-model.type.ts
src/lib/features/project/project-service.ts
src/lib/types/experimental.ts

This PR:
- adds a flag to anonymize user emails in the new project cards
- performs the anonymization using the existing `anonymise` function that we have.
It does not anonymize the system user, nor does it anonymize groups. It does, however, leave the gravatar url unchanged, as that is already hashed (but we may want to hide that too). 
This PR also does not affect the user's name or username. Considering the target is the demo instance where the vast majority of users don't have this (and if they do, they've chosen to set it themselves), this seems an appropriate mitigation.
With the flag turned off:
With the flag on:

fix: turn off showing usernames and emails in the project cards when the flag is turned on

---

frontend/src/component/feature/EditFeature/EditFeature.tsx

This message appears to have been missed when we did the previous
migration from "toggle" to "flag".

chore: change "toggle updated" to "flag updated" in toast message

---

src/lib/db/index.ts
src/lib/features/feature-lifecycle/feature-lifecycle-read-model.test.ts
src/lib/features/feature-lifecycle/feature-lifecycle-read-model.ts
src/lib/features/feature-lifecycle/feature-lifecycle.e2e.test.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/metrics.ts
src/lib/services/index.ts
src/lib/types/stores.ts
src/test/fixtures/store.ts

Expose prometheus metric for counting how many features are in each of the stages grouped by project.
Details:
* this metric is a gauge
* query behind this metric is feature flagged just in case we find perf problems
* reading data in the metrics.ts from the injected read model. This code is not added to instance stats since they don't need it
Next PRs:
* move lifecycle median duration metrics from instance stats to metrics.ts so that generating instance stats doesn't run unnecessary lifecycle queries
* change duration metric type to gauge since we don't do sampling in median duration metrics

feat: stage count by project metric

---

website/docs/using-unleash/deploy/upgrading-unleash.md

Add missing notice about license keys when upgrading to v6

fix: add license key notice to upgrade instructions

---

frontend/src/component/commandBar/CommandBar.tsx

Previously it was doing request to search behind to scenes, when noone was using the nav bar. This fixes it.

feat: now command bar will not search behind the scene

---

src/lib/metrics.ts

Given our approach of calculating the median value in the application code and then reporting this calculated value to Prometheus every 2 hours, the most appropriate Prometheus metric type to use would be a Gauge. This type of metric is best suited for capturing values that can go up or down, like a median calculation, which may change each time it is computed depending on the underlying data.
We'll need to update Grafana queries accordingly.

fix: change lifecycle stage duration metric type

---

src/lib/features/feature-search/feature-search-store.ts

Now we are not returning * columns, but all tables that we join later, will need to select columns one by one.

fix: make search selects explicit

---

frontend/src/component/commandBar/CommandBar.tsx
frontend/src/component/commandBar/PageSuggestions.tsx
frontend/src/component/commandBar/RecentlyVisited/RecentlyVisited.tsx

Tweaks the styles of the UI of the command bar to match sketches.
A lot of these styles should be refactored into command bar components and applied to search results as well

feat: tweak command bar UI styles to match sketches

---

src/lib/types/model.ts

Removes some unused interfaces that I missed when removing state service

chore: remove unused interfaces from old state import

---

frontend/src/component/commandBar/CommandBar.tsx
frontend/src/component/commandBar/CommandFeatures.tsx

Now the search hook is inside another component, so we do not get searches without search query.
Also we had 2 state variable handing the search query. Removed one of them.

feat: search only features when there is search string

---

src/lib/db/index.ts
src/lib/features/feature-lifecycle/feature-lifecycle-read-model.test.ts
src/lib/features/metrics/sizes/fake-largest-resources-read-model.ts
src/lib/features/metrics/sizes/largest-resources-read-model-type.ts
src/lib/features/metrics/sizes/largest-resources-read-model.test.ts
src/lib/features/metrics/sizes/largest-resources-read-model.ts
src/lib/metrics.ts
src/lib/types/stores.ts
src/test/fixtures/store.ts

Proactive **project env and feature env weight metrics** allowing us to asses which feature environments and which project environments are the largest in the Unleash instance. 
* Unleash should always protect SDKs from fetching unnecessary data causing memory problems or CPU problems due to excessive config data
* We want to get feedback on the excessive configuration at the feature environment level and at the project level way before the first client feature request is being made (being proactive)
We can use feature_strategies table to calculate size heuristic for large feature environments and project environments.
Both are affected by two dimensions of the feature_strategies table. The vertical axis is the numbers of strategies and the horizontal axis is the sum of sizes of …

feat: largest projects and features metric

---

src/lib/features/project/project-service.e2e.test.ts
src/lib/features/project/project-service.test.ts
src/lib/features/project/project-service.ts

This change changes how we generate project IDs. Instead of adding a
12-character hash, we now use an incrementing number when necessary.
We first slugify the project name (as we already do). If no project
with that ID exists, that's what you get. If that ID already exists,
then we add a number to the end of the slugified name, starting at 1.
So if you create a project called "My Project" three times over,
first one will have the ID "my-project", the second one will have the
ID "my-project-1", and the third one will have the ID "my-project-2".
In a list:
- my-project
- my-project-1
- my-project-2
This does not impact any existing projects.
The only potential drawback I can see this having, is that it makes
race conditions more likely. If two people create a project with the
same name at …

chore: change generated project id format to use incrementing numbers instead of hashes

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyEnabled/FeatureStrategyEnabled.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx

Only one banner info about the outcome of strategy edit should appear when change requests are enabled.
[issue/1-2292](https://linear.app/unleash/issue/1-2292/bug-do-not-show-feature-toggle-is-currently-enabled-banner-when-change)

fix: banner duplication on strategy edit with change requests

---

frontend/src/component/common/util.test.ts
frontend/src/component/common/util.ts
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx
frontend/src/component/feature/StrategyTypes/NewStrategyVariants.tsx
frontend/src/component/feature/StrategyTypes/SplitPreviewSlider/SplitPreviewSlider.tsx

If you have for example 3 variants, and 2 have weight type `fixed` with sum over 100%, this was resulting in a third weight calculation going into negative. It's something that later validation will catch, but we would like to provide earlier feedback.
Added validation if sum goes over 100%. Remaining split is never negative.

fix: prevent strategy variant weight from going into negative numbers on Frontend

---

frontend/src/component/commandBar/CommandBar.tsx
frontend/src/component/commandBar/CommandFeatures.tsx
frontend/src/component/commandBar/PageSuggestions.tsx
frontend/src/component/commandBar/RecentlyVisited/CommandResultGroup.tsx
frontend/src/component/commandBar/RecentlyVisited/RecentlyVisited.tsx
frontend/src/hooks/usePlausibleTracker.ts

Start tracking plausible events
1. Log the search keywords that returned 0 results
2. Track all clicks, based on source(search/recents/pages), type etc.

feat: command bar track events

---

src/lib/features/project/project-service.e2e.test.ts
src/lib/features/project/project-service.ts

This fixes the issue where project names that are 100 characters long
or longer would cause the project creation to fail. This is because
the resulting ID would be longer than the 100 character limit imposed
by the back end.
We solve this by capping the project ID to 90 characters, which leaves
us with 10 characters for the suffix, meaning you can have 1 billion
projects (999,999,999 + 1) that start with the same 90
characters (after slugification) before anything breaks.
It's a little shorter than what it strictly has to be (we could
probably get around with 95 characters), but at this point, you're
reaching into edge case territory anyway, and I'd rather have a little
too much wiggle room here.

fix: cap project ids to 90 characters (without suffix)

---

frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.test.tsx
frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts
frontend/src/hooks/useClearSWRCache.test.ts
frontend/src/hooks/useClearSWRCache.ts

Previously, clearing the SWR cache cleared all entries. Now you can configure the cache size.
1. This makes the search more fluid. Previously, if you went back and forth on pages, you were always sent to the loading state. 
2. This also solves the issue where the command bar search cleared the cache for all other searches. 
3. Additionally, it addresses the problem where the global search cleared the cache for project search.

feat: introduce large cache for swr

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts
src/lib/openapi/spec/resource-limits-schema.ts

This PR adds limits for environments to the resource limit schema. The actual limiting will have to be done in Enterprise, however, so this is just laying the groundwork.

feat: add environments to resource limit schema

---

frontend/src/component/commandBar/CommandPageSuggestions.tsx
frontend/src/component/commandBar/CommandPages.tsx
frontend/src/component/commandBar/CommandRecent.tsx

Now quick suggestions padding is not bigger than for pages.

fix: improve menu styling

---

package.json
yarn.lock

Since I couldn't find a single place that imported/used multer (which is a multi-part upload handler for express) I went ahead and removed it from our dependency tree

chore: remove multer, since it isn't being used

---

frontend/src/component/admin/apiToken/ProjectsList/ProjectsList.test.tsx
frontend/src/component/admin/apiToken/ProjectsList/ProjectsList.tsx
frontend/src/component/common/HtmlTooltip/HtmlTooltip.tsx

Instead of listing all projects, that currently stretch the row height, I added a tooltip. This is similar to segments. It will enable virtualization of the table

fix: prevent project cell overflow on api keys table

---

frontend/src/component/commandBar/RecentlyVisited/CommandResultGroup.tsx

Now command menu hover has same styling as sidebar

fix: command menu hover

---

frontend/src/component/commandBar/CommandBar.tsx

Fixes so search bar in command bar retains it's styling when focus is shifted to search results

chore: fix searchbar styling when focus is on results

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts
src/lib/openapi/spec/resource-limits-schema.ts
src/lib/services/api-token-service.limit.test.ts
src/lib/services/api-token-service.ts
src/lib/types/option.ts

This PR adds the back end for API token resource limits. 
It adds the limit to the schema and checks the limit in the service.
The PAT service uses a different service and different store entirely, so I have not included testing any edge cases where PATs are included. However, that could be seen as "knowing too much". We could add tests that check both of the stores in tandem, but I think it's overkill for now.

feat: add resource limits for API tokens

---

website/docs/how-to/how-to-environment-import-export.mdx

Adds a documentation entry to import/export about file based import.
This feature only supports the OSS import feature set.

docs: add an entry for file based OSS featureset import

---

frontend/src/component/commandBar/RecentlyVisited/CommandResultGroup.tsx

Adds quick suggestions icons for playground and insights

chore: fix command bar missing icons in quick suggestions

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts
src/lib/features/segment/segment-service.limit.test.ts
src/lib/features/segment/segment-service.ts
src/lib/openapi/spec/resource-limits-schema.ts
src/test/fixtures/fake-segment-store.ts

Limit how many segments we can create in our backend (by default it's 300). 
Details:
* I had to add method to our fake store to get the unit test for limits running
* if we set limit to 0 then we can effectively disable segment creation

feat: segments limit

---

frontend/src/component/common/Search/Search.tsx
frontend/src/hooks/usePlausibleTracker.ts

Now we will start tracking how users interact with search box. Whether they open it manually or use CTRL K

feat: track interaction with search

---

frontend/src/component/segments/CreateSegmentButton/CreateSegmentButton.tsx
frontend/src/component/segments/SegmentTable/SegmentTable.test.tsx
frontend/src/component/segments/SegmentTable/SegmentTable.tsx
frontend/src/hooks/api/getters/useUiConfig/defaultValue.tsx
frontend/src/openapi/models/resourceLimitsSchema.ts

Disable 'New segment' button when limit of 300 reached. Screenshot has manually adjusted limit of 6
Additionally, I decided to make the create segment button disabled when segments are being loaded or config is being loaded.
Modified existing test to avoid adding too many UI tests since they are quite slow.

feat: segments limit ui

---

frontend/src/component/common/ApiTokenTable/CreateApiTokenButton/CreateApiTokenButton.test.tsx
frontend/src/component/common/ApiTokenTable/CreateApiTokenButton/CreateApiTokenButton.tsx
frontend/src/hooks/api/getters/useUiConfig/defaultValue.tsx
frontend/src/openapi/models/resourceLimitsSchema.ts

This PR activates the limit for API token creation in both the global API token window and in the project-level API token tab.
Because the same button is used in two places, I encapsulated the fetching of flags and resource limits within the button. I can be convinced to pass the current API token count and the limit as arguments, but I think this is the right solution for this case.

feat: UI limit for API tokens

---

frontend/src/component/commandBar/CommandBar.tsx

Now when pressing ESC, command bar will lose focus.

fix: remove focus on ESC

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/features/metrics/client-metrics/metrics-service-v2.ts
src/lib/features/metrics/instance/instance-service.ts
src/lib/metrics.test.ts
src/lib/metrics.ts
src/lib/openapi/spec/client-application-schema.ts
src/lib/openapi/spec/client-metrics-schema.ts
src/lib/types/experimental.ts
src/lib/types/model.ts
src/server-dev.ts

This adds an extended metrics format to the metrics ingested by Unleash and sent by running SDKs in the wild. Notably, we don't store this information anywhere new in this PR, this is just streamed out to Victoria metrics - the point of this project is insight, not analysis.
Two things to look out for in this PR:
- I've chosen to take extend the registration event and also send that when we receive metrics. This means that the new data is received on startup and on heartbeat. This takes us in the direction of collapsing these two calls into one at a later point
- I've wrapped the existing metrics events in some "type safety", it ain't much because we have 0 type safety on the event emitter so this also has some if checks that look funny in TS that actually check if the data shape is …

Extended SDK Metrics

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/features/feature-toggle/fakes/fake-feature-toggle-store.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggle-service.limit.test.ts
src/lib/openapi/spec/resource-limits-schema.ts
src/lib/types/option.ts

This PR adds a feature flag limit to Unleash. It's set up to be overridden in Enterprise, where we turn the limit up. 
I've also fixed a couple bugs in the fake feature flag store.

Chore: add limits to feature flags

---

frontend/src/component/commandBar/CommandPageSuggestions.tsx

Removes strategy types as command bar page suggestion

chore: command bar remove strategy types as page suggestion

---

frontend/src/component/commandBar/CommandQuickSuggestions.tsx
frontend/src/component/commandBar/RecentlyVisited/CommandResultGroup.tsx

Pass in explicitly named keyName property to components instead of key, use as key on returned components

chore: fix command bar key prop usage

---

frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx

Currently, if the location changes, it does not update the active item. I added useEffect to update the active item.
This is required when the user navigates via the command menu.

fix: sidebar update active when navigated via command menu.

---

frontend/src/component/commandBar/CommandBar.tsx

Adds arrow up / down navigation to command bar using the DOM
When we move up/down check to see if any of the items in the list has focus, and sets the index to focus to be the one before or after the current focus. this lets us use both tabs (react built in) and arrows to navigate the list

feat: command bar up down navigation

---

frontend/src/component/project/Project/DeleteProject/DeleteProjectDialogue.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/DeleteProject.tsx

Improving the project deletion experience by adding information about API keys and refining the messaging, making it easier to comprehend.
- Pre-Deletion Requirements: Reminder to archive all feature flags before deleting a project now only shows up when it is relevant.
- Lists all entities that will be permanently deleted is now done with bullet points. It is easier to comprehend as we reached 3 items.
Now reiterates that deleting a project will also remove all actions configured for the project, in addition to the project itself, its feature flags, and API keys.
Should reminder to archive flags be reverted closer to disabled delete button, instead of placing it on the top.
https://github.com/Unleash/unleash/pull/7503

feat: update description on project deletion

---

frontend/src/component/commandBar/CommandBar.tsx

Adds a drop shadow to command bar that is visible also in dark mode

chore: use a command bar shadow thats visible in darkmode as well

---

src/lib/features/feature-toggle/feature-strategies-read-model.ts
src/lib/features/feature-toggle/tests/feature-toggle-strategies-store.e2e.test.ts

When reporting max values in prometheus metrics we want to exclude strategies that belong to archived features. It means we need to join with the features table in the queries.

feat: exclude archived features in max reporting

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/middleware/secure-headers.ts
src/lib/types/experimental.ts

Our CSP reports that unsafe-inline is not recommended for styleSrc. This PR adds a flag for making it possible to remove this element of our CSP headers. It should allow us to see what (if anything) breaks hard.

task: added flag to remove unsafe inline style src header

---

frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.test.tsx
frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts

This PR fixes a bug where we wouldn't update the `useFeatureSearch` hook's cached `total` value if the new total was `0`. The reason this failed is that we would only update it if `data?.total`. Because `0` is a falsy value, the check would fail.

fix: update cache, even when the total is 0

---

frontend/src/component/insights/componentsStat/UserSeats/UserSeats.test.tsx
frontend/src/component/insights/componentsStat/UserSeats/UserSeats.tsx

Creating self-contained component for user seats.
Decisions:
* this component is hosted on the insights page but since it's not affected by the date range selection I decided to not add this data to the insights endpoint
* instead this components fetches the data it needs from the existing APIs
* I still need to figure out if this is the right way to fetch the user count and the seats count
* I'm calling it user seats not user licenses since I want consistent terms across all pages

feat: user seats component

---

frontend/src/component/App.tsx
frontend/src/component/common/Loader/Loader.tsx

This change fixes an issue with the loader where it would explode its
parent component to 100vh even when that was not called for.
To do so, I've added the a new `type` prop to the component, to
distinguish between `fullscreen` and `inline` usage. The `fullscreen`
type sets the height to 100vh, while the `inline` type sets it to
100%.
Now, this doesn't directly make the loader fullscreen (it just makes
sure it's at least as tall as the screen), so maybe the prop name is
misleading. I'd be happy to change it (or to even extract this into
two separate components) if that's preferable. Other potential prop
names could be `height`, which is very direct, or `usage`, which I
think better describes what we do. Like with `type`, I'd like to
communicate the intended behavior more that the actual …

fix: make loader not exlpode to 100vh in unnecessary locations

---

frontend/src/component/common/FormTemplate/FormTemplate.styles.ts
frontend/src/component/common/FormTemplate/FormTemplate.tsx
frontend/src/component/common/GeneralSelect/GeneralSelect.tsx
frontend/src/component/feature/FeatureView/FeatureSettings/FeatureSettingsProject/FeatureProjectSelect/FeatureProjectSelect.tsx

This PR fixes a couple instances where long resource names would break form and input layouts.
I've added comments to the various files to explain what they're doing and why.
I've now set the width of project selector to be as narrow as it can with wrapped text. In the main interfaces, it's much better, but on the page where you can move a flag, it is quite narrow. However, I still think it's better (no chance of it being wider than the whole screen). We might want to find another way, but regardless, it'll only show up with real edge cases.
**Files**:
- `frontend/src/component/common/FormTemplate/FormTemplate.styles.ts`
- `frontend/src/component/common/FormTemplate/FormTemplate.tsx`
Before:
After:
**Files**:
- `frontend/src/component/common/GeneralSelect/GeneralSelect.tsx`
Before:
After: …

fix: prevent long names from breaking form layouts

---

frontend/src/hooks/api/actions/useAuthSettingsApi/useAuthSettingsApi.ts

This change improves the toast error message for auth settings by
preferring the message from the error's details list if it exists. If
it doesn't it'll still fall back to the original error message.
Before:
After:

fix: toast error doesn't tell you what the error is

---

src/migrations/20240716135038-integration-events.js
website/sidebars.js

https://linear.app/unleash/issue/2-2435/create-migration-for-a-new-integration-events-table
Adds a DB migration that creates the `integration_events` table:
- `id`: Auto-incrementing primary key;
- `integration_id`: The id of the respective integration (i.e. integration configuration);
- `created_at`: Date of insertion;
- `state`: Integration event state, as text. Can be anything we'd like, but I'm thinking this will be something like:
- Success ✅
- Failed ❌
- SuccessWithErrors ⚠️
- `state_details`: Expands on the previous column with more details, as text. Examples:
- OK. Status code: 200
- Status code: 429 - Rate limit reached
- No access token provided
- `event`: The whole event object, stored as a JSON blob;
- `details`: JSON blob with details about the integration execution. Will …

chore: db migration for integration events

---

frontend/src/component/insights/Insights.tsx
frontend/src/component/insights/InsightsFilters.tsx
frontend/src/component/insights/components/InsightsHeader/InsightsHeader.tsx
frontend/src/hooks/api/getters/useInsights/useInsights.ts

Adding date and project filters to the insights view.
Initial state
All filters added
* split the insights page into two variants (legacy and new) so that we can evolve them independently. Previously only charts were split but we also need to split on the header
* re-using existing filters component. It saves a lot of effort and gives us project filtering for free. I tried other approaches and this one is by far the cheapest to implement and brings consistency across the pages
Next PR:
* I will add tests for the insights filtering since I couldn't find any

feat: insights filters

---

frontend/src/component/common/BreadcrumbNav/BreadcrumbNav.tsx
frontend/src/component/insights/Insights.tsx
frontend/src/component/insights/InsightsCharts.tsx

Insights header should show below banners.
- We should revisit "breadcrubms", because current implementation is inconsistent - try project tabs navigation. Added task: https://linear.app/unleash/issue/1-2568/fix-inconsistent-breadcrumbs

fix: insights sticky header

---

src/lib/error/bad-data-error.ts
src/lib/error/unleash-error.test.ts
src/lib/services/openapi-service.ts

This PR updates the OpenAPI error converter to also work for errors with query parameters. 
We previously only sent the body of the request along with the error, which meant that query parameter errors would show up incorrectly.
For instance given a query param with the date format and the invalid value `01-2020-01`, you'd previously get the message:
> The `from` value must match format "date". You sent undefined
With this change, you'll get this instead:
> The `from` value must match format "date". You sent "01-2020-01". 
The important changes here are two things:
- passing both request body and query params
- the 3 lines in `fromOpenApiValidationError` that check where we should get the value you sent from.
The rest of it is primarily updating tests to send the right arguments and some …

fix: Update OpenAPI error converter to handle query param errors too

---

frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx
frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx
frontend/src/interfaces/uiConfig.ts

Same as the OIDC changes we merged yesterday, this makes the frontend ready for disabling SAML configuration page, if the SAML_ environment variables are set.

feat: Make SAML dialog aware that it might be configured via env

---

frontend/src/component/insights/InsightsCharts.tsx
frontend/src/component/insights/components/LineChart/LineChartComponent.tsx
frontend/src/component/insights/componentsChart/ProjectHealthChart/HealthChartTooltip/HealthChartTooltip.tsx
frontend/src/component/insights/componentsChart/ProjectHealthChart/ProjectHealthChart.tsx
frontend/src/component/insights/componentsStat/HealthStats/HealthStats.tsx

This PR updates the tooltips for the health chart to also include information on how healthy  flags there are. The user could make this calculation themselves before, but it'd require them to subtract the sum of stale and potentially stale flags from the total. This makes it so that they don't have to do the calculation.
I've also included a bar for the healthy flags in the overview, so that it's easier to see how large a portion it is compared to the others.
Also: clean up some uses of the now-deprecated VFC.

feat: show info on healthy flags in health tooltip

---

src/lib/error/exceeds-limit-error.test.ts
src/lib/error/exceeds-limit-error.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggle-service.limit.test.ts
src/lib/features/project/project-service.limit.test.ts
src/lib/features/project/project-service.ts
src/lib/features/segment/segment-service.limit.test.ts
src/lib/features/segment/segment-service.ts
src/lib/metric-events.ts
src/lib/metrics.test.ts
src/lib/metrics.ts
src/lib/services/api-token-service.ts

This PR adds prometheus metrics for when users attempt to exceed the limits for a given resource. 
The implementation sets up a second function exported from the ExceedsLimitError file that records metrics and then throws the error. This could also be a static method on the class, but I'm not sure that'd be better.

chore: send prometheus metrics when someone tries to exceed resource limits

---

src/lib/error/bad-data-error.ts
src/lib/error/unleash-error.test.ts
src/lib/features/feature-toggle/feature-toggle-controller.ts
src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts
src/lib/openapi/validate.test.ts
src/lib/openapi/validate.ts

https://linear.app/unleash/issue/2-2453/validate-patched-data-against-schema
This adds schema validation to patched data, fixing potential issues of patching data to an invalid state.
This can be easily reproduced by patching a strategy constraints to be an object (invalid), instead of an array (valid):
```sh
curl -X 'PATCH' \
'http://localhost:4242/api/admin/projects/default/features/test/environments/development/strategies/8cb3fec6-c40a-45f7-8be0-138c5aaa5263' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '[
{
"path": "/constraints",
"op": "replace",
"from": "/constraints",
"value": {}
}
]'
```
Unleash will accept this because there's no validation that the patched data actually looks like a proper strategy, and we'll start seeing Unleash errors due to the …

fix: validate patched data with schema

---

frontend/src/component/InitialRedirect.tsx

This PR fixes a minor visual glitch where the initial Unleash load might display a jumping loading icon. The reason was that the initial redirect's loader wasn't marked as a fullscreen loader.

fix: use a fullscreen loader for the initial redirect load

---

src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggle-service.limit.test.ts

This PR updates the limit validation for constraint numbers on a single strategy. In cases where you're already above the limit, it allows you to still update the strategy as long as you don't add any **new** constraints (that is: the number of constraints doesn't increase).
A discussion point: I've only tested this with unit tests of the method directly. I haven't tested that the right parameters are passed in from calling functions. The main reason being that that would involve updating the fake strategy and feature stores to sync their flag lists (or just checking that the thrown error isn't a limit exceeded error), because right now the fake strategy store throws an error when it doesn't find the flag I want to update.

feat: allow you to gradually scale back constraint usage

---

src/lib/addons/addon.test.ts
src/lib/addons/addon.ts
src/lib/addons/datadog.test.ts
src/lib/addons/datadog.ts
src/lib/addons/index.ts
src/lib/addons/new-relic.test.ts
src/lib/addons/new-relic.ts
src/lib/addons/slack-app.test.ts
src/lib/addons/slack-app.ts
src/lib/addons/slack.test.ts
src/lib/addons/slack.ts
src/lib/addons/teams.test.ts
src/lib/addons/teams.ts
src/lib/addons/webhook.test.ts
src/lib/addons/webhook.ts
src/lib/features/integration-events/integration-events-store.ts
src/lib/services/addon-service-test-simple-addon.ts
src/lib/services/addon-service.test.ts
src/lib/services/addon-service.ts
src/lib/services/index.ts
src/lib/types/model.ts
src/test/e2e/services/addon-service.e2e.test.ts

https://linear.app/unleash/issue/2-2450/register-integration-events-webhook
Registers integration events in the **Webhook** integration.
Even though this touches a lot of files, most of it is preparation for the next steps. The only actual implementation of registering integration events is in the **Webhook** integration. The rest will follow on separate PRs.
Here's an example of how this looks like in the database table:
```json
{
"id": 7,
"integration_id": 2,
"created_at": "2024-07-18T18:11:11.376348+01:00",
"state": "failed",
"state_details": "Webhook request failed with status code: ECONNREFUSED",
"event": {
"id": 130,
"data": null,
"tags": [],
"type": "feature-environment-enabled",
"preData": null,
"project": "default",
"createdAt": "2024-07-18T17:11:10.821Z",
"createdBy": "admin", …
```

chore: register integration events in webhooks

---

src/lib/openapi/spec/ui-config-schema.ts

As the title says. Adds two new nullable variables to uiConfig. Used in frontend to decide if SSO config is editable through the GUI

chore: extend uiConfig schema with new SSO variables

---

src/lib/openapi/util/openapi-tags.ts

This typo has been around since the tag was introduced. About time we fixed it.

fix: change "features flags" -> "feature flags"

---

frontend/src/component/common/Limit/Limit.tsx

The limit card says to contact cs@getunleash if you're at the limits,
but we probably don't want to show that to OSS customers (it's not
terrible, just not very helpful), so let's hide it for OSS.
Instead, we'll ask them to try the community slack.
Screenie:

chore: don't ask OSS users to reach out to CS

---

.husky/update-openapi-spec-list.js
package.json
src/lib/features/integration-events/integration-events-store.ts
src/lib/features/integration-events/integration-events.e2e.test.ts
src/lib/openapi/spec/base-pagination-parameters.ts
src/lib/openapi/spec/index.ts
src/lib/openapi/spec/integration-event-schema.ts
src/lib/openapi/spec/integration-events-schema.ts
src/lib/routes/admin-api/addon.ts

https://linear.app/unleash/issue/2-2439/create-new-integration-events-endpoint
https://linear.app/unleash/issue/2-2436/create-new-integration-event-openapi-schemas
This adds a new `/events` endpoint to the Addons API, allowing us to fetch integration events for a specific integration configuration id.
Also includes:
- `IntegrationEventsSchema`: New schema to represent the response object of the list of integration events;
- `yarn schema:update`: New `package.json` script to update the OpenAPI spec file;
- `BasePaginationParameters`: This is copied from Enterprise. After merging this we should be able to refactor Enterprise to use this one instead of the one it has, so we don't repeat ourselves;
We're also now correctly representing the BIGSERIAL as BigInt (string + pattern) in our OpenAPI …

chore: integration events API

---

frontend/src/component/common/Search/Search.tsx
frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
frontend/src/hooks/useKeyboardShortcut.ts

Currently, the command bar and search hotkeys are conflicting. I am now separating them and assigning search an extra modifier key: Shift.

feat: separate command bar and search hotkeys

---

website/docs/using-unleash/deploy/configuring-unleash.md

Turns out we're hosting 20-30 customer instances on db.t4g.small, so our recommended specs just seemed like complete overkill.

docs: Removed the recommended chapter of PostgreSQL config

---

frontend/src/component/integrations/IntegrationForm/IntegrationParameters/IntegrationParameter/IntegrationParameterTextField.tsx
package.json
src/lib/addons/__snapshots__/webhook.test.ts.snap
src/lib/addons/webhook-definition.ts
src/lib/addons/webhook.test.ts
src/lib/addons/webhook.ts
yarn.lock

Add ability to format format event as Markdown in generic webhooks, similar to Datadog integration.
Closes https://github.com/Unleash/unleash/issues/7646

Feat: webhook markdown

---

frontend/src/component/common/DialogFormTemplate/DialogFormTemplate.styles.tsx
frontend/src/component/feature/CreateFeature/CreateFeature.tsx

This change makes it so that all form input labels start with a
capital letter, regardless of the data we use to generate them.
Also fixes a leftover toggle -> flag renaming.

fix: Capitalize input labels

---

website/remote-content/sdks.js

This will download the README of the new SDK from the remote location based on this:
https://github.com/Unleash/unleash/blob/1e3c6901850e1719f870dae08350ef806564e038/website/docusaurus.config.js#L883-L892
And we can here see the preview: https://unleash-docs-git-update-internal-docs-to-ne-9ba815-unleash-team.vercel.app/reference/sdks/android-proxy

docs: add new android sdk readme

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/CreateFeatureDialog.tsx

This change wraps the project selection option in the
CreateFeatureDialog in a conditional that hides it when Unleash is
OSS.
OSS doesn't have access to the project creation API, so there's no
point in showing this.

fix: Hide project selection option in CreateFeatureDialog when OSS

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/CreateFeatureDialog.tsx

This change makes it so that we show the name of the project that is
selected on the selection button instead of the ID. There is a chance
that the name is not unique, but I'm willing to take that risk (plus
it's how we do it today).
I've used a useMemo for this, because we have to scan through a list
to find the right project. Sure, it's always a small list (less than
500 items, I should think), but still nice to avoid doing it every
render. Happy to remove it if you think it obfuscates something.
We *could* also use a `useState` hook and initialize it with the right value, update when it changes, but I actually think this is a better option (requires less code and less "remember to update this when that changes").

fix: show the selected project's name on the button, not its ID

---

frontend/src/component/common/DialogFormTemplate/ConfigButtons/DropdownList.tsx
frontend/src/component/common/DialogFormTemplate/ConfigButtons/MultiSelectConfigButton.tsx
frontend/src/component/common/DialogFormTemplate/ConfigButtons/SingleSelectConfigButton.tsx
frontend/src/component/feature/hooks/useFeatureForm.ts
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/CreateFeatureDialog.tsx

This PR makes the config dropdown list generic over its values, so that you can pass stuff that isn't strings.
It also updates the existing impression data button to use booleans instead.

fix: make config dropdown list generic over values

---

frontend/src/component/common/DialogFormTemplate/ConfigButtons/ConfigButton.styles.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/CreateFeatureDialog.tsx

This change prevents long project names from blowing the form out of proportion.
To do so, it:
1. sets `whitespace: no-wrap` on the button labels. Judging by the other
styles, this was the intention all along, but it didn't really come up
until now.
2. It also sets the label width for projects to 30ch,so that you'll get
to see quite a bit of the project name before it gets cut off.
It would be possible to set a dynamic width for this button based on the longest project name, but I'm not sure it adds much value, so I'm leaning towards keeping it simple.
Here's what the dynamic width would look like:
``` tsx
const projectButtonLabelWidth = useMemo(() => {
const longestProjectName = projects.reduce(
(prev: number, type: { name: string }) =>
prev >= type.name.length ? prev : type.name.length, …
```

fix: prevent long project names from blowing out the form

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/CreateFeatureDialog.tsx

This change sets the max project name label width to 20ch instead of 30ch.
At 30ch, the button is wide enough that it causes the buttons always
to overflow. At 20, it's about as wide as the impression data button,
and it renders on one line.
Before:
After:

fix: shorten max project name width in feature toggles creation form

---

frontend/src/component/common/DialogFormTemplate/ConfigButtons/ToggleConfigButton.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/CreateFeatureDialog.tsx

Instead of using a dropdown list for impression data, this PR introduces a new config button that is a switch type button. It will be filled (contained) when impression data is on and will be outlined when impression data is off.
Off:
On:

feat: Use a toggling button for impression data on/off

---

frontend/src/component/project/Project/Project.styles.ts

This change fixes an issue where the title of the project would be
pushed all the way to the right when the project was set to "private".
The cause was that the container with the project mode and the title
was a flex box with `justifyContent` set to `space-between`.
Removing that line fixes the issue, and the contents align to the
start of the box. There are no other elements in that container, so it
does not affect anything else.
Before:
After:

fix: Avoid weird spacing between title and collab mode icon

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx

This change fixes a bug where editors were suddenly unable to create
flags. The issue is that the new project creation dialog used a
permission button, but didn't supply the project ID.

fix: allow editors to create flags again

---

frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/CreateFeatureDialog.tsx

This change is a follow-up to
https://github.com/Unleash/unleash/pull/7685 and fixes another
instance of the same issue.
It wasn't caught previously, because the permissions are passed as
props here, and not used directly.

fix: allow editors to submit flag form

---

frontend/src/component/insights/hooks/useProjectChartData.ts

Adds human readable project names in all the charts so that we match the selectors from the project filter
Details:
* decided to query the projects hook and create a map for quick lookup of names by project id
* fallback to project id if the name cannot be found

feat: human readable project names in insight charts

---

frontend/src/component/insights/componentsStat/HealthStats/HealthStats.tsx

Prevent showing "undefined%" in new Health statistics.

fix: health stats number

---

frontend/src/component/feature/FeatureView/Collaborators.tsx

This change removes the use of grid area from the collaborators
component, replacing it with a nested flexbox setup.

fix: use nested flexboxes instead of grid area

---

frontend/src/component/project/Project/Project.styles.ts

This PR fixes a minor visual issue where the "favorite project" button's hover outline would get cut off due to its container having `overflow: hidden`.
The overflow value was introduced in [#7575](https://github.com/Unleash/unleash/pull/7575) as way to handle long project names. We didn't discover the hover issue back then  because it's not apparent unless you hover the fav star.
I found the solution in the CSS-tricks post [Preventing a Grid Blowout](https://css-tricks.com/preventing-a-grid-blowout/). To quote the article, the reason this works is that:
> the minimum width of a grid column is auto. (The same is true for flex items, by the way.)
>
> And since auto is entirely based on content, we can say it is “indefinitely” sized, its dimensions flex. If we were to put an explicit width …

fix: don't cut off hover-color of favorite button

---

frontend/src/component/feature/FeatureView/Collaborators.tsx

This change fixes an issue where the flex layouts for collaborator
info used the wrong axes for layout (row instead of column and vice
versa), causing the component to look wonky.
Before:
After:

fix: flex layout used the wrong axes for layout.

---

frontend/src/component/common/Table/SortableTableHeader/SortableTableHeader.tsx
frontend/src/component/common/Table/VirtualizedTable/VirtualizedTable.tsx

Refactoring to get rid of `A props object containing a "key" prop is being spread into JSX` warning. See diff with "hide whitespace" on https://github.com/Unleash/unleash/pull/7694/files?diff=split&w=1
Internal ticket [1-2548](https://linear.app/unleash/issue/1-2548/api-tokens-table-react-warnings-about-keys)

fix: avoid react key warnings in tables

---

frontend/src/component/events/EventLog/EventLog.tsx
frontend/src/component/feature/FeatureView/FeatureLog/FeatureLog.tsx
frontend/src/component/project/Project/ProjectLog/ProjectLog.tsx

Updates the way the event log works. Previously, we'd use the
`displayInline` parameter to disable padding and border. However,
recent pages (including project overview etc) have moved away from
this look.
By bringing the event log into line with how those other pages look,
it'll be easier to make designs for the new filtering capability align
with other Unleash filters.
The eventlog is used in three places. In two of them, it used to not have a separating border. However, when we look at other screens that have seen recent work (such as feature flags), we see that they *do* have a separator, so bringing the event log in line seems like a reasonable change.
Project flags list (notice the separator):
Here's what they look like before and after the change:
Before: 
After (no change): …

refactor: Make event log look and act like other pages

---

src/lib/middleware/origin-middleware.test.ts
src/lib/middleware/origin-middleware.ts

https://linear.app/unleash/issue/2-2492/change-origin-middleware-log-level-to-info
Changes origin middleware log level to `info` instead of `debug`.

chore: change log level to info in origin middleware

---

src/lib/metric-events.ts
src/lib/metrics.ts
src/lib/middleware/origin-middleware.test.ts
src/lib/middleware/origin-middleware.ts

https://linear.app/unleash/issue/2-2501/adapt-origin-middleware-to-stop-logging-ui-requests-and-start
This adapts the new origin middleware to stop logging UI requests (too noisy) and adds new Prometheus metrics.
This should allow us to better analyze this data. If we see a lot of API requests, we can dive into the logs for that instance and check the logged data, like the user agent.
This PR adds some helper methods to make listening and emitting metric events more strict in terms of types. I think it's a positive change aligned with our scouting principle, but if you think it's complex and does not belong here I'm happy with dropping it.

chore: request origin prom metrics

---

frontend/src/component/events/EventLog/EventLog.tsx
frontend/src/component/events/EventLog/EventLogFilters.tsx
frontend/src/component/filter/Filters/Filters.tsx

Adds placeholder filter buttons (that don't work at all) yet to the three event logs.
Flag logs get to choose to and from dates, created by, and event type.
Project logs get all that flag logs get + a filter for flag.
The global log gets all project log filters + a project filter.
There's still work to be done to add data to createdBy, eventType, to hook it up to the API, and to finalize the layout, but I wanted to get a rough outline in to iterate on later. The eventType icon will also need to be decided on.

feat: add filter dropdowns to event log pages

---

src/lib/metrics.ts

This PR adds Grafana gauges for all the existing resource limits. The primary purpose is to be able to use this in alerting. Secondarily, we can also use it to get better insights into how many customers have increased their limits, as well as how many people are approaching their limit, regdardless of whether it's been increased or not.
The first approach I took (in https://github.com/Unleash/unleash/pull/7718/commits/87528b4c6785899d7afec34721cb9f0df9bf0bfc), was to add a new gauge for each resource limit. However, there's a lot of boilerplate for it. 
I thought doing it like this (the current implementation) would make it easier. We should still be able to use the labelName to collate this in Grafana, as far as I understand? As a bonus, we'd automatically get new resource limits when …

feat: create gauges for all resource limits

---

website/package.json
website/remote-content/edge-proxy.js
website/remote-content/sdks.test.js
website/remote-content/shared.js
website/sidebars.js

When all edge documentation was in a single page, we had all of it here: https://docs.getunleash.io/reference/unleash-edge but after splitting up https://github.com/Unleash/unleash-edge/pull/475 some of that documentation is not present in our docs and we should probably have them as sub-pages
This change allows us to include subpages for external documentation. Note that the key of the subpage needs to match the remote path
Checkout the preview: https://unleash-docs-git-add-edge-subpages-unleash-team.vercel.app/

docs: add subpages of edge documentation

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/CopyStrategyIconMenu/CopyStrategyIconMenu.tsx

You can copy strategy not only to other environments but also to the current one
Use case: you configure variants once and want to have a few strategies with the same variants without having to type them manually
Details:
* it's a UI change only, we're adding current environment to the list of envs you can copy to
* current env is the last one on the list and has a text: "Copy to current"
* I checked and it also supports change requests out of the box
* tooltip changes from "copy to another environment" to "copy to environment"

feat: copy strategy to current environment

---

frontend/src/component/events/EventLog/EventLogFilters.tsx

Add event types to the event log filter button.
The event types are taken from the OpenAPI definition.

feat: add event types to filter button

---

frontend/src/component/events/EventLog/EventLog.tsx
frontend/src/component/events/EventLog/EventLogFilters.tsx
frontend/src/component/filter/Filters/Filters.tsx

Fixes an issue where the filter buttons were both too far down and too
far to the right.
The issue was that the wrapper body imposed a pretty substantial bit
of padding. However, the filter buttons already came with their own
bit of padding. The result of this was alignment issues.
To fix it I have:
- opened the `Filters` component up to be styled with styled components
And conditionally (when isEnterprise and the flag is on):
- set the page body to have no padding.
- added a wrapper with padding around the event search results for 
This feels a little messy to me, but I also think that because it's still in heavy development, it might change later. I'd be happy to have suggestions forbetter implementations.
What makes this extra tricky is that the top padding differs depending on whether …

fix: align event log filter buttons

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyType/FeatureStrategyType.tsx
frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.test.tsx
frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.tsx

Old versions of Unleash allow for creating "Gradual Rollout" strategies without `groupId` or `stickiness`. UI will now populate those fields, not getting stuck when editing strategies without said fields.
Internal ticket: [1-2198](https://linear.app/unleash/issue/1-2198/strategy-configuration-auto-add-stickiness-and-groupid-if-missing)

fix: strategy parameters UI

---

frontend/src/component/demo/demo-setup.ts

This PR makes some small changes to how we handle strategy deletion in the demo environment, which has become extra important with the recent soft limits.
The changes are:
- lower the strategy limit from 30 to 25. The standard limit is 30, so we want to make sure we're below that.
- when checking whether we should delete a strategy, check whether we're **at or above** the limit. It used to only check if we were above, but if soft limits would prevent you from adding more, then you'd never be able to go above the limit.
- Also delete strategies for step3.

chore[demo]: update handling of strategy deletion for demo walkthrough

---

frontend/src/component/common/AvatarGroup/AvatarGroup.tsx
frontend/src/component/project/NewProjectCard/ProjectOwners/ProjectOwners.tsx

Fixes a bug introduced with the new tooltips where the system user was shown as "User ID n" instead of "System". The "n" in this case is actually the user's index number in the list of project owners (including duplicates).
There's a few things happening: 
1. Change the object for system owners: use `name` instead of `description`. At the same time, remove the `description` property completely because it's not used at the moment. 
2. Remove the assignnment of `id: objectId(user)` to the user sent to the User Avatar component. This was a leftover from when we split out the AvatarGroup component, and is not something we use anymore.
Before:
After:

fix: show "System" for system users, instead of "User ID n" where n is the project's number in the order.

---

src/lib/features/events/event-search-controller.ts
src/lib/features/events/event-service.ts
src/lib/features/events/event-store.ts
src/lib/features/feature-search/feature-search-controller.ts
src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/openapi/spec/event-search-query-parameters.ts
src/lib/routes/admin-api/event.ts
src/lib/routes/admin-api/index.ts
src/lib/routes/admin-api/search/index.ts
src/lib/types/stores/event-store.ts
src/test/e2e/api/admin/event-search.e2e.test.ts

Changed the url of event search to search/events to align with search/features. With that created a search controller to keep all searches under there.
Added first test.

feat: event search on new endpoint, first test

---

frontend/src/component/common/AvatarGroup/AvatarGroup.tsx
frontend/src/component/feature/FeatureView/Collaborators.tsx

Fixes an issue where the collaborator component would be smooshed together when you have too many collaborators and too many flag tab items.
The primary things I have done are:
1. Limit the amount of collaborators we show to 6 instead of 8. I believe the number 8 was arbitrary, so let's go with 6 for now.
2. Instead of using a fixed gap, use a separator element that grows up to a certain limit. I've added a `Separator` component, which is an empty div with flex-grow. It feels like you should be able to do that with gap too, but I can't think of how right now.
3. Don't allow collaborator component text (or avatars) to wrap. We don't have a lot of space in this header, so let's keep it tight.
Additionally, I've added the `className` prop to the AvatarGroup component so that it can be styled …

fix: Avoid collaborators being smooshed together

---

src/lib/features/playground/advanced-playground.test.ts
src/lib/features/playground/feature-evaluator/client.ts

This bug manifests when you evaluate parent/child relationship where parent is disabled but has some strategies.
I added extra check in the parent deps checking code. It's different from the node SDK but should pass the tests and keep it backwards compatible with the execution plans requirement of the playground.
This solution diverges from the node SDK because of the playground behavior described as a test "considers disabled features with a default strategy to be enabled". I had to add an extra check in parent deps checking function to overcome for the differences in the behavior.

fix: playground parent disabled with strategy

---

frontend/src/component/playground/Playground/AdvancedPlayground.tsx

* removing old event `playground_token_input_used` - it was never registered in plausible
* re-using more generic event `playground` with type of `try-configuration` and `mode`
* we have 3 modes: default, api token and change request

feat: playground try configuration mode

---

src/lib/features/feature-search/feature.search.e2e.test.ts
src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts
src/lib/features/project/projects.e2e.test.ts
src/lib/openapi/spec/create-feature-schema.ts
src/lib/openapi/spec/update-feature-schema.ts
src/test/e2e/api/admin/tags.e2e.test.ts
src/test/e2e/api/client/feature.e2e.test.ts

Previously people were able to send random data to feature type. Now it is validated.
Fixes https://github.com/Unleash/unleash/issues/7751

fix: feature type is now validated

---

frontend/src/component/admin/apiToken/ApiTokenIcon/ApiTokenIcon.tsx

Adding a link "Read more in [release notes](https://github.com/Unleash/unleash/releases/tag/v6.1.0)" to orphaned tokens.
This needs to be added on v6.1, with the following changelog entry:
> **SDK tokens for deleted projects**
> 
> In previous versions of Unleash, when a project was deleted, the associated SDK tokens were not removed. This issue has been addressed in the current version of Unleash.
> 
> Unfortunately, if you deleted a project in the past without manually removing the associated tokens, these "orphaned" tokens were automatically converted to “wildcard” tokens, granting access to all feature flags across all projects.
> 
> Our assessment indicates this poses a minor security concern due to the following reasons:
> 
> This issue only affects tokens whose entire project scope …

feat: link to release notes from orphaned tokens

---

src/lib/features/events/event-service.ts
src/test/e2e/api/admin/event-search.e2e.test.ts

Changes the handling of the `to` query parameter in
the API to be inclusive.

feat: make `to` date inclusive

---

frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/CreateProjectDialog.tsx

Fixes a bug in the navigation when you create a project. It used to be
that we'd replace the current entry in the browser history when we
took you to a separate form for it. However, now that we instead
use a dialog, we don't want to replace the history.
Before: if you created a project and navigated back, you'd be taken to
the page you were at BEFORE you went to the projects page, whether
that was in Unleash or otherwise.
Now you'll be taken back to the projects page.

fix: don't delete projects screen from history

---

src/migrations/20240806140453-add-archived-at-to-projects.js

Adding DB migration adding archived_at column to projects. It's modelled after the same column in the features table.
We need to check if none of the queries break (e.g. in joins with features where archived_at was not namespaced with a table name)

feat: archived at column in projects

---

.github/workflows/publish-new-version.yaml

Tests were failing on this workflow due to postgres taking longer to boot up, now it will wait for postgres to boot up before continuing.

feat: wait for postgres to boot before running tests

---

src/lib/features/project/project-service.e2e.test.ts
src/lib/features/project/project-service.ts
src/lib/features/project/project-store-type.ts
src/lib/features/project/project-store.ts
src/lib/types/events.ts
src/test/fixtures/fake-project-store.ts

Service can archive projects now.
Details:
* similar to delete but it only updates one column
* no code has been changed in reading projects yet (e.g. excluding archived projects). It will be a set of other PRs to do that
* added new event for project archived
* testing that new event for project archived was generated since we don't expose archived at information anywhere yet
Next PR:
* enterprise repo will expose this service over API

feat: archive project service

---

frontend/src/component/filter/FilterItem/FilterItem.tsx

Fixes a bug where the `handleSelection` function would select the
wrong item under certain conditions.
Because we always sent the unfiltered list of options to the function,
but took the index of the filtered items, the index would be off when
you have filtered the list and items before the selected items were hidden.
This addresses that and also ports in some improvements I made when
setting up the config buttons for the new dialogs:
1. You can now use the space bar to select items that you have
focused (this is consistent with regular form interactions for
checkboxes)
2. When you have added text to the search field, pressing Enter will
select the top-most item (this is consistent with how these fields
work in linear, for instance) as long as your focus is still in the
search field. If …

fix: select an item only from the filtered list of options

---

frontend/src/component/events/EventLog/EventLog.tsx
frontend/src/component/events/EventLog/useEventLogSearch.test.ts
frontend/src/component/events/EventLog/useEventLogSearch.ts
frontend/src/hooks/api/getters/useEventSearch/useEventSearch.ts

Adds sticky pagination to the event log:
This PR uses the sticky pagination bar that we use on other tables to navigate the event search results.
The trickiest issue here is how we calculate the next and previous page offsets. This is tricky because we don't expose the page number to the API, but the raw offset itself. This abstraction makes it possible to set an offset that isn't a multiple of the page size.
Say the page size is 25. If you manually set an offset of 30 (through changing the URL), what do you expect should happen when you:
- load the page? Should you see results 31 to 55? 26 to 50?
- go to the next page? Should your next offset be 55 or 50?
- previous page: should your previous page offset be 5? 25? 0?
The current implementation has taken what I thought would be the …

feat: add paging to event log

---

frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.tsx

`groupId` parameter because of the change in validation wasn't parsed correctly.
Intent was to fill it when it is empty, when the form is loaded.
By mistake the same logic applies when you manually remove all characters from the text field.

fix: allow for empty groupId in form

---

frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.tsx

`groupId` parameter because of the change in validation wasn't parsed correctly. Intent was to fill it when it is empty, when the form is loaded. By mistake the same logic applies when you manually remove all characters from the text field.
Closes #

fix: allow for empty groupId in form (#7798)

---

src/lib/addons/slack-app.ts

Slack is trying to add not useful link previews 
_"just, don't"_

fix: don't show link stubs in slack notifications

---

src/lib/features/events/event-service.ts
src/lib/features/events/event-store.ts
src/lib/openapi/spec/event-creators-schema.ts
src/lib/openapi/spec/index.ts
src/lib/routes/admin-api/event.ts
src/lib/routes/admin-api/index.ts
src/lib/routes/admin-api/search/index.ts
src/lib/types/stores/event-store.ts
src/test/e2e/api/admin/event.e2e.test.ts
src/test/fixtures/fake-event-store.ts

Adds an endpoint to return all event creators.
An interesting point is that it does not return the user object, but just created_by as a string. This is because we do not store user IDs for events, as they are not strictly bound to a user object, but rather a historical user with the name X.

feat: event creators

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/AddCommentField.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/ChangeRequestComment.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/StyledAvatar.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.styles.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewers/ChangeRequestReviewer.tsx

Turns out there was (at least) one other avatar instance we missed in
[ previous update ](https://github.com/Unleash/unleash/pull/7681):
change request avatars.
They don't use the existing UserAvatar component, so didn't show up in
the dependency graph. This change makes it so that those avatars also
use the user avatar component (and send all the info that we need).
Before: 
After:
To show that the overall layout is the same, here's before:
and after:

fix: Update avatar usage in change requests

---

src/lib/features/events/event-store.ts
src/test/e2e/api/admin/event.e2e.test.ts

Previously distinct was not working properly, because we were joining users table. 
You needed to do distinctOn. Now fixed.

fix: event creators, distinct on two users with same id

---

src/lib/services/user-service.ts
src/lib/types/user.test.ts
src/lib/types/user.ts

Encountered this case after encrypting an already long email address. This should mitigate the issue in demo instance. I don't think it's a big issue to ignore the length when validating an email address cause this is already limited at the DB layer by the column length

fix: after encryption some emails end up being too long

---

frontend/src/component/feature/CreateFeature/CreateFeature.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/CreateFeatureDialog.tsx

There's a bug where the UI will fetch all features every time you load a project screen (including every time you filter the project results).
The reason is that the create flag dialog was rendered (just not open) every time. To solve it, we instead wrap it in an extra component that prevents all the fetching and setup from running when the dialog isn't open.
Additionally, we'll lower the page size for the global fetch limit to 1, so that we send less data.
(There's a bug in place that prevents the page size from working at the moment, but I'll address that in a follow-up)

fix: don't always fetch all flags on project flag screen

---

src/migrations/20240812120954-add-archived-at-to-projects.js

After adding an index, the time for the new event search on 100k events decreased from 5000ms to 4ms. This improvement is due to the query using an index scan instead of a sequence scan.

feat: add index on events created at

---

frontend/src/component/insights/componentsChart/TimeToProductionChart/TimeToProductionChart.tsx
src/lib/features/feature-toggle/time-to-production/time-to-production.test.ts
src/lib/features/feature-toggle/time-to-production/time-to-production.ts

- filter out time to production data points of `0 days to production`
- allow for gathering data for quickly enabled feature flags

Fix: time to production

---

src/lib/features/feature-toggle/feature-toggle-service.ts
src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts

Prevent people from reviving features in archived project
Details:
* added a validation method that checks if there's an active project
* covering single feature and batch revive
* currently we don't distinguish between deleted and archived and we always say that active project was not found. We may consider splitting this into not found and invalid operation in future

feat: prevent revive flag/flags in archived project

---

frontend/src/component/common/DialogFormTemplate/DialogFormTemplate.styles.tsx
frontend/src/component/common/DialogFormTemplate/DialogFormTemplate.tsx
frontend/src/component/common/DialogFormTemplate/NamingPatternInfo.tsx
frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/CreateFeatureDialog.tsx

Updates the dialog form template to include a `namingPattern` prop that can be used to display the naming pattern of whatever the form is used for.
Also updates the create feature dialog to display the naming pattern in the current project.
The naming pattern component re-uses the pattern that we have in place for feature naming patterns, but puts it in an expandable dialog instead. 
Screenies:
Naming pattern closed:
Naming pattern open:

fix: display feature naming patterns in dialog

---

src/lib/features/events/event-service.ts
src/test/e2e/api/admin/event-search.e2e.test.ts

Changes the event search handling, so that searching by user uses the user's ID, not the "createdBy" name in the event. This aligns better with what the OpenAPI schema describes it.

fix: search events by user ID, not by user name

---

src/lib/addons/slack-app.ts

https://github.com/Unleash/unleash/pull/7810

fix: don't show link stubs in slack notifications (#7810)

---

frontend/src/component/insights/componentsChart/TimeToProductionChart/TimeToProductionChart.tsx
src/lib/features/feature-toggle/time-to-production/time-to-production.test.ts
src/lib/features/feature-toggle/time-to-production/time-to-production.ts

- filter out time to production data points of `0 days to production`
- allow for gathering data for quickly enabled feature flags

Fix: time to production (#7835)

---

src/lib/features/feature-lifecycle/feature-lifecycle-service.ts
src/lib/types/events.ts

For easy gitar integration, we need to have boolean in the event payload.
We might rethink it when we add variants, but currently enabled with variants is not used.

feat: update feature completed payload to have boolean instead of string

---

frontend/src/component/common/BreadcrumbNav/BreadcrumbNav.tsx
frontend/src/component/common/ProjectIcon/ProjectIcon.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts
frontend/src/component/project/NewProjectCard/NewProjectCard.styles.ts
frontend/src/component/project/NewProjectCard/NewProjectCard.tsx
frontend/src/component/project/NewProjectCard/ProjectArchiveCard.tsx
frontend/src/component/project/NewProjectCard/ProjectCardFooter/ProjectCardFooter.tsx
frontend/src/component/project/NewProjectCard/ProjectModeBadge/ProjectModeBadge.tsx
frontend/src/component/project/ProjectList/ArchiveProjectList.tsx
frontend/src/component/project/ProjectList/ProjectGroup.tsx
frontend/src/component/project/ProjectList/ProjectList.tsx
frontend/src/hooks/api/getters/useProjectsArchive/useProjectsArchive.ts
frontend/src/themes/dark-theme.ts
frontend/src/themes/theme.ts
frontend/src/themes/themeTypes.ts

Closes [issue/1-2666](https://linear.app/unleash/issue/1-2666/archived-projects-view)
- should archive card include collaboration "mode" (badge for 'private' projects)?
- TODO: check if  archive respects "hidden" projects

Projects archive UI

---

frontend/src/component/events/EventLog/EventLog.tsx

Updates the new event log to show a skeleton loading screen while the search results are being fetched.
The placeholder size is based on the standard event size.

chore: create skeleton loading for new event screen

---

frontend/src/component/events/EventLog/EventActions.tsx
frontend/src/hooks/usePlausibleTracker.ts

Plausible for events exports. And small cleanup.

feat: plausible for events export

---

frontend/src/component/admin/groups/CreateGroup/CreateGroup.tsx
frontend/src/component/admin/groups/EditGroup/EditGroup.tsx
frontend/src/component/admin/groups/Group/Group.tsx
frontend/src/component/admin/groups/GroupForm/GroupForm.tsx
frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCardActions/GroupCardActions.tsx
frontend/src/component/admin/groups/group-constants.ts
src/lib/services/group-service.ts
src/test/e2e/services/group-service.e2e.test.ts

This relaxes validation on modifying SCIM groups.
From a UI perspective, users are now allowed to access the edit screen for SCIM groups (previously you couldn't click the relevant UI elements and if you navigated manually you'd just get the save button disabled). Now instead updating the name is disabled and modifying the SSO mappings is hidden. The usual places that previously blocked you from changing users are still disabled.
On the backend, validation has been relaxed to allow some editing of groups, so long as you're not changing the name or modifying the users (effectively the only two properties SCIM cares about).

feat: allow editing root role/description on SCIM group

---

frontend/src/component/common/AvatarGroup/AvatarGroup.tsx

Caps the number of collaborators to display to a constant (currently
set to 99).
Above that, it'll always show "+99".
However, we also add a tooltip that shows you a prettified version of
the extra collaborators (using the `millify` package that we already use for metrics)
Screenies:
< 1000 collaborators:
1000 - 1M collaborators:
1M+ collaborators:
Update, it now shows the total number of collaborators instead of the overflow:

fix: cap number of collaborators displayed

---

src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts

When reading feature env strategies and there's no segments it returns empty list of segments now. Previously it was undefined leading to overly verbose change request diffs.

fix: always provide empty segments list in feature env strategies

---

website/docs/contributing/ADRs/back-end/write-model-vs-read-models.md

The link to the image was incorrectly formatted, leading to the image being displayed as a link. This fixes it so that the image is displayed inline.

fix: display 3 types of models image

---

src/lib/features/segment/admin-segment.e2e.test.ts
src/lib/features/segment/segment-store.test.ts
src/lib/features/segment/segment-store.ts

Exclude archived feature flags from the segment usage count calculations
Making sure this list count
matches this strategy values

fix: exclude archived features in segments count

---

src/lib/features/events/event-search-controller.ts
src/lib/features/events/event-service.test.ts
src/lib/features/events/event-service.ts

Adds private projects support for event search. Unit test should cover the usecases.

feat: support private projects for event search

---

frontend/src/component/project/NewProjectCard/ProjectArchiveCard.tsx
frontend/src/component/project/Project/ArchiveProject/ProjectArchived.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/interfaces/project.ts

When you get to the url of an archived project you will be given similar message to archived flag. It has a link to all archived projects list. I deliberately keep UI simple since very few people should end up here.
Aslo fixed time ago component to avoid ticking for the first 60 seconds

feat: Show project archived message

---

frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

These are both related to the work on the project list improvements project.
The `projectListImprovements` flag will be used to enable disable the
new project list improvements.
The `useProjectReadModel` flag will be used to enable/disable the use
of the new project read model and is mostly a safety feature.

chore: add flags `projectListImprovements` and `useProjectReadModel`

---

src/lib/db/index.ts
src/lib/features/project/createProjectReadModel.ts
src/lib/features/project/createProjectService.ts
src/lib/features/project/fake-project-owners-read-model.ts
src/lib/features/project/fake-project-read-model.ts
src/lib/features/project/project-owners-read-model.test.ts
src/lib/features/project/project-owners-read-model.ts
src/lib/features/project/project-owners-read-model.type.ts
src/lib/features/project/project-read-model-type.ts
src/lib/features/project/project-read-model.ts
src/lib/features/project/project-service.e2e.test.ts
src/lib/features/project/project-service.ts
src/lib/openapi/spec/project-schema.ts
src/lib/types/model.ts
src/lib/types/stores.ts
src/test/fixtures/store.ts

Hooks up the new project read model and updates the existing project service to use it instead when the flag is on.
In doing:
- creates a composition root for the read model
- includes it in IUnleashStores
- updates some existing methods to accept either the old or the new model
- updates the OpenAPI schema to deprecate the old properties

refactor: switch `projectStore.getProjects` with `projectReadModel.getProjectsForAdminUi` in project service

---

src/lib/features/project/project-read-model.ts

This PR touches up a few small things in the project read model.
Fixes:
Use the right method name in the query/method timer for `getProjectsForAdminUi`. I'd forgotten to change the timer name from the original method name.
Spells the method name correctly for the `getMembersCount` timer (it used to be `getMemberCount`, but the method is callled `getMembersCount` with a plural s).
Changes:
Call the `getMembersCount` timer from within the `getMembersCount` method itself. Instead of setting that timer up from two different places, we can call it in the method we're timing. This wasn't a problem previously, because the method was only called from a single place. Assuming we always wanna time that query, it makes more sense to put the timing in the actual method.

chore: minor cleanup in new project read model

---

src/lib/features/project/fake-project-read-model.ts

Implements empty responses for the fake project read model. Instead of throwing a not implemented error, we'll return empty results.
This makes some of the tests in enterprise pass.

chore: impl empty results for fake project read model

---

frontend/src/component/project/NewProjectCard/NewProjectCard.styles.ts
frontend/src/component/project/NewProjectCard/ProjectArchiveCard.tsx

A link to archived project archived flags is always there without a number of archived flags (we decided not to expose it for now). 
I decided to choose a link similar to view archive link in the flag search
I also played with the card title link but it  felt like it leads you to full project information that we don't want to show for the archived projects.

feat: static link to archived flags in archived project

---

frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCard.tsx

This PR updates the styling of the group cards to better handle edge cases where you have a lot of assigned projects, long project names, lots of members, etc.
In particular, it does the following things:
- aligns the avatars along the bottom of the card, so that even if there's a lot of projects, the avatars stay close to the bottom edge
- adds word breaks for the project names, so that long names can break when they need to
- adds some spacing between the two columns in the bottom row, so that even when you they get close, they never quite touch.
Note: there is one more thing I'd like to address in a follow up: as shown in the top row of the after image, there's some extra wrapping of the first "This group has no users", even though it has the room to grow. I'll keep looking into this …

fix: avoid awkward overlaps of group cards with lots of members, long project names, and small cards

---

src/lib/features/metrics/client-metrics/metrics-service-v2.test.ts
src/lib/features/metrics/last-seen/createLastSeenService.ts
src/lib/features/metrics/last-seen/last-seen-service.ts
src/lib/features/metrics/last-seen/last-seen-store.ts
src/lib/features/metrics/last-seen/tests/last-seen-service.e2e.test.ts
src/lib/features/metrics/last-seen/tests/last-seen-service.test.ts

When storing last seen metrics we no longer validate at insert time that the feature exists. Instead, there's a job cleaning up on a regular interval. 
Metrics for features with more than 255 characters, makes the whole batch to fail, resulting in metrics being lost.
This PR helps mitigate the issue while also logs long name feature names

fix: last seen metrics exceeding table limits

---

src/lib/features/project/project-owners-read-model.test.ts
src/lib/features/project/project-read-model-type.ts
src/lib/features/project/project-read-model.test.ts
src/lib/features/project/project-read-model.ts
src/lib/types/events.ts

This PR fixes an issue where the number of flags belonging to a project was wrong in the new getProjectsForAdminUi.
The cause was that we now join with the events table to get the most "lastUpdatedAt" data. This meant that we got multiple rows for each flag, so we counted the same flag multiple times. The fix was to use a "distinct".
Additionally, I used this as an excuse to write some more tests that I'd been thinking about. And in doing so also uncovered another bug that would only ever surface in verrry rare conditions: if a flag had been created in project A, but moved to project B AND the feature-project-change event hadn't fired correctly, project B's last updated could show data from that feature in project A.
I've also taken the liberty of doing a little bit of cleanup.

fix: don't count flags multiple times (bonus: don't count non-project events)

---

frontend/src/component/common/Limit/Limit.tsx

The previously used email address doesn't actually exist 😳 It was taken from the sketches and we just never verified it.

fix: update the customer success email for limits

---

src/lib/routes/admin-api/addon.ts

Changes the OpenAPI tag used for integration events to be 'Addons' like the rest of the addon APIs

chore: change integration events api tag to addons

---

frontend/src/component/application/ApplicationChart.tsx
frontend/src/component/archive/ArchiveTable/FeatureArchivedCell/FeatureArchivedCell.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/ChangeRequestComment.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx
frontend/src/component/common/Notifications/Notification.tsx
frontend/src/component/common/Table/cells/FeatureSeenCell/FeatureSeenCell.tsx
frontend/src/component/common/Table/cells/FeatureSeenCell/LastSeenTooltip.tsx
frontend/src/component/common/Table/cells/TimeAgoCell/TimeAgoCell.tsx
frontend/src/component/feature/FeatureView/FeatureEnvironmentSeen/FeatureEnvironmentSeen.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
frontend/src/component/project/NewProjectCard/ProjectArchiveCard.tsx

There is a bug I'm fixing, when sometimes time values for "last seen" appear to be in the future, like "in X seconds".
Turns out `react-timeago` dependency has an issue, where it doesn't refresh current time when new value is passed (https://github.com/nmn/react-timeago/issues/181).
Temporary solution to this, is to force re-rendering by providing a component `key`.
For a long term solution, I'd like to drop this dependency, and replace it with [date-fns/formatDistanceToNow](https://date-fns.org/v3.6.0/docs/formatDistanceToNow).

fix: react-timeago issue

---

frontend/src/component/integrations/IntegrationForm/IntegrationForm.tsx

Fixes so that delete button doesn't show up when creating integrations, only when editing them

fix: only show addon delete button when editing addons

---

website/docs/topics/feature-flags/feature-flag-best-practices.md

An extension of [#7801](https://github.com/Unleash/unleash/pull/7801). 
**[Docs preview](https://unleash-docs-git-melinda-11-principles-unleash-team.vercel.app/topics/feature-flags/feature-flag-best-practices)**
Key changes:
- Improved readability—removed a lot of passive voice, made sections a bit less repetitive and reorganized a few sentences/headings for better structure.
- Removed nested lists. I generally avoid using numbered lists, unless it's instructions or something that really calls for an order. I think it's fine to keep the high-level 11-step list (because 11 principles sounds catchy) but I would avoid nested lists like 1.1.a in this case.
- Added some more links to tie back to some of the Unleash concepts in a subtle way. For example, linking the 4-eyes principle to the …

Update 11 principles page

---

src/lib/create-config.ts
src/lib/types/option.ts

This allows us to use different limits for enterprise self-hosted and hosted

chore: allow you to use the options object to override *all* the new resource limits

---

frontend/src/component/project/Project/ArchiveProject/ProjectArchived.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject/ArchiveProjectForm.tsx
frontend/src/component/project/ProjectList/ReviveProjectDialog/ReviveProjectDialog.tsx
src/lib/features/project/project-service.limit.test.ts
src/lib/features/project/project-service.ts

Addressing the following breakathon findings:
* archive project 404 page wording
* prevent revive project when limit exceeded
* API command for archive (method and URL changed)
* navigate to revived project after revive
Archive card text overflow is a separate PR as it also applies to the main project list.

fix: misc fixes for project archive

---

src/lib/features/access/access-read-model-type.ts
src/lib/features/access/access-read-model.ts
src/lib/features/access/createAccessReadModel.ts
src/lib/features/access/createAccessService.ts
src/lib/features/events/createEventsService.ts
src/lib/features/events/event-created-by-migration.test.ts
src/lib/features/events/event-service.ts
src/lib/features/feature-search/search-utils.ts
src/lib/features/feature-toggle/types/feature-toggle-strategies-store-type.ts
src/lib/features/segment/segment-service.ts
src/lib/services/access-service.test.ts
src/lib/services/access-service.ts
src/lib/services/feature-service-potentially-stale.test.ts
src/lib/types/events.ts
src/test/e2e/api/admin/event-search.e2e.test.ts

Now events that do not have project ( for example user creation, segment creation etc), will not be displayed to non root admins.

feat: filter projectless events for normal users

---

src/lib/routes/admin-api/user-admin.ts

Path types in our openapi are inferred as string (which is a sensible default). But we can be more specific and provide the right type for each parameter. This is one example of how we can do that
@thomasheartman WDYT?

chore: type our path parameters
