package.json

Bump some package deps that nodesecurity recomends

---

app.js
lib/extractUser.js
lib/featureApi.js
lib/strategyApi.js
package.json
public/js/app.jsx
public/js/components/Menu.jsx
public/js/components/User.jsx
public/js/stores/UserStore.js
test/featureApiSpec.js

This is a simple solution where we have a input field which updates a "username" cookie with the given username from the user. The server reads this cookie and makes sure all change requests uses the value from the cookie. 
THIS IS NOT AUTHENTICATION! it is not safe and is only implemented as a first edition. It does however solve the issue where we are not able to see who changed what.
How it looks like in the UI:

Username in a cookie

---

lib/eventDiffer.js
lib/eventType.js
lib/featureApi.js
lib/featureArchiveApi.js
lib/featureDb.js
migrations/20150210152531-006-rename-eventtype.js
migrations/sql/006-rename-eventtype.down.sql
migrations/sql/006-rename-eventtype.up.sql

@jarib raised some concerns with the database so we need to figure that out.
The problem will be that some databases will be using the old naming so we need to have a migration.

#80 Rename event types

---

artifact.json
package.json

According to editorconfig the indent_size of json files should be 2 spaces.
I updated our json files to reflect this.
Ok?

Update files with correct indent_size

---

.gitignore
Dockerfile
Vagrantfile
helpers/install.sh

to enable deployment of unleash in new infrastructure

added docker container and vagrant

---

.gitignore
public/css/unleash.css

commit messages should be pretty obvious

Clearer colors

---

index.js
package.json
server.js

We do this in order to make it possible to release the unleash-server. 
The main goal is to drag out finn-specific code, and use the server as a npm  require.

make it possible to require server

---

packages/unleash-api/package.json
packages/unleash-api/server.js
packages/unleash-frontend/package.json
packages/unleash-server/package.json

- fix correct verison number (1.0.0-alpha.2)
- added missing server.js inside unleash-api

Minor cleanup after lerna migration.

---

README.md
package.json
packages/unleash-api/lib/error/validateRequest.js
packages/unleash-api/lib/routes/feature.js
packages/unleash-api/lib/routes/strategy.js
packages/unleash-api/test/eventDifferTest.js
packages/unleash-api/test/specHelper.js
packages/unleash-frontend/public/js/__tests__/components/feature/FeatureForm-test.js
packages/unleash-frontend/public/js/components/feature/FeatureForm.jsx
packages/unleash-frontend/public/js/components/log/LogEntryList.jsx
packages/unleash-frontend/public/js/components/strategy/Strategy.jsx
packages/unleash-frontend/public/js/components/strategy/StrategyForm.jsx
packages/unleash-frontend/public/js/stores/EventStore.js
packages/unleash-frontend/public/js/stores/UserStore.js
packages/unleash-frontend/webpack.config.js

Tests are failing for me locally, pushing to see if it somehow works on Travis
Badges diff:
Old:
New:

Fix linting errors

---

app.js
lib/db/db-pool.js
lib/db/index.js
migrator.js
package.json
test/e2e/util/database-config.js
test/e2e/util/test-helper.js

options to specify different db-schema

---

lib/app.js
lib/app.test.js
package.json

https://github.com/Unleash/unleash/issues/192

add app hooks

---

lib/client-metrics/client-metrics.test.js
lib/client-metrics/ttl-list.js

cc @ivarconr 
fixes https://github.com/Unleash/unleash-frontend/issues/24

Add ttl tests

---

CHANGELOG.md

Something more to add @sveisvei @vsandvold ?

Added changelog #196

---

lib/routes/feature.js
test/e2e/feature-api.test.js

cc @ivarconr 
Adding this as it makes sense given we dont need to post the whole feature for each toggle.

add toggle endpoint

---

migrations/20170306233934-timestamp-with-tz.js

Database should holde timezone information.

---

lib/routes/feature.js

validate configures strategy shape

---

.eslintrc
lib/server-impl.js
lib/server-impl.test.js

Spawned from https://github.com/Unleash/unleash/issues/222

pass along hooks, add test to server impl

---

lib/routes/client-api/feature.js
lib/routes/client-api/feature.test.js

should expose one feature

---

CHANGELOG.md
lib/client-metrics/client-metrics.test.js
lib/client-metrics/index.js
lib/routes/client-api/metrics-schema.js
lib/routes/client-api/metrics.test.js
test/examples/client-register.json

Add metrics validation to avoid NaN #253

---

lib/db/client-instance-store.js
lib/db/client-metrics-db.js

We use intervals in three places and we could probably organise them
better in the future. As long as they all do unref they do not form
any issues for us and I will just let them be as is for now.
This closes #186

Clean up intervals.

---

lib/routes/index.js
package.json

Include module version number in /api reponse

---

lib/app.js
lib/routes/admin-api/feature.js
lib/routes/admin-api/feature.test.js

Simplify name validator

---

lib/app.js
lib/middleware/request-logger.js
lib/middleware/response-time.js
lib/middleware/session-middleware.js
lib/middleware/session.js
lib/middleware/validator.js
lib/options.js
lib/routes/admin-api/feature.js
lib/routes/admin-api/index.js
package.json
yarn.lock

Unleash needs to have a session awareness to handle signed in users across multiple instances (to avoid redirects to OAuth provider). 
I also separated out setup of a few middlewares to make `app.js` more readable. 
Closes #275

Cookie session

---

docs/getting-started.md
docs/migration-guide.md

Add details on how to upgrade unleash to version 3.
closes #276

Add migration details for v3. 

---

docs/securing-unleash.md
examples/basic-auth-hook.js

This was the one (fairly pleasant) surprise that I ran into integrating a custom OAuth2 provider in with Unleash. Hopefully this helps make the signout/sign in process more clear for everyone else!

Add example and documentation around triggering login modal #234

---

lib/app.js
package.json
yarn.lock

See https://expressjs.com/en/4x/api.html#express.json

use body-parser bundled with express

---

bin/unleash.js
lib/options.js
lib/server-impl.js

feat(bind): Added option to bind to http address.

---

CHANGELOG.md
lib/server-impl.js

fix(migration): Unleash should not start if migration fails.

---

lib/routes/admin-api/archive.js
lib/routes/admin-api/archive.test.js
test/fixtures/fake-event-store.js

Include user information on revive

---

README.md

Added Ruby to the list of available SDKs.

Update README with available SDKs.

---

README.md

Hello!
I work for a startup in NYC that's planning on using Unleash as our feature toggle framework.  I actually heard about the product from a friend (@ another startup!).
During a few conversations, a few folks raised a desire for an Python client that uses murmerhash3, metrics polling, et cetera.  I decided that it'd be a fun personal project to take on while suffering from caffeine induced insomnia. :)
My take on a Python client is on [Github](https://github.com/ivanklee86/unleash-client-python) and [Pypi](https://pypi.org/project/UnleashClient/).  It implements the Client Specifications v1 (from the main repo) as well as the tests in the client-specifications repo.
I'm sure there's still a bunch of rough spots/areas of improvements.  (We're hoping to start using it in a prod-ish …

Adding another Python client

---

docs/guides/google-auth-hook.md
website/sidebars.json

I added Google auth hook guide :)

chore(docs): Add google auth hook guide

---

lib/metrics.js
lib/metrics.test.js
lib/server-impl.js

This PR implements feature request #308

Add prometheus compatible feature metrics endpoint

---

lib/app.js
lib/middleware/simple-authentication.js

fix: SimpleAuthentication should work with custom basePaths

---

docs/getting-started.md
lib/options.js
lib/routes/admin-api/config.js
lib/routes/admin-api/config.test.js
lib/routes/admin-api/index.js
package.json
yarn.lock

See https://github.com/Unleash/unleash-frontend/pull/170

feat: Add customizable ui config

---

docs/api/admin/state-api.md
docs/import-export.md
website/sidebars.json

* Include import/export in sidebar.json
* Added state-api.md

Update import/export documentation

---

lib/routes/admin-api/state.js

fix: import should use mime.lookup() for filename

---

docs/getting-started.md
lib/options.js
lib/server-impl.js

Read this for more details:
https://nodejs.org/api/net.html#net_identifying_paths_for_ipc_connections

Fix: Add support for IPC connections.

---

bin/unleash.js
docs/getting-started.md
docs/guides/google-auth-hook.md
lib/options.js
lib/options.test.js
lib/server-impl.js

Not sure why this is not part of the main code base and instead suggested in docs and used separately in https://github.com/Unleash/unleash-docker

fix: Add DATABASE_URL_FILE for loading a db url from a file

---

README.md
docs/client-sdk.md

I pushed a new elixir package (https://hex.pm/packages/unleash) so you can use unleash from an Elixir project!

Add Elixir Unleash Library to README

---

website/core/Footer.js

Slack invite token was invalid, updated to a valid one

chore: Updated slack invite token

---

docs/api/admin/feature-toggles-api.md

chore: toggle/on|off documentation added

---

lib/options.js
lib/server-impl.js

Added a new parameter to disable db migration.

fix: Add option to disable database migrations #526

---

examples/google-auth-hook.js

Fix typo in gogole-auth-hook example

---

lib/routes/admin-api/user.js
lib/routes/index.js
lib/routes/logout.js
lib/routes/logout.test.js

fix: Logout should not be xhr call

---

website/pages/en/index.js

Update index.js (small typo)

---

docs/getting-started.md

Fix Typo in Getting Started

---

lib/routes/admin-api/feature-schema.js
lib/routes/admin-api/feature-schema.test.js

feat: add weightType as legal property on variant schema

---

lib/db/client-applications-store.js
lib/db/client-instance-store.js
lib/routes/admin-api/metrics.js
lib/routes/admin-api/metrics.test.js
test/e2e/api/admin/metrics.e2e.test.js
test/e2e/api/client/metrics.e2e.test.js
test/e2e/helpers/database.json
test/fixtures/fake-client-applications-store.js
test/fixtures/fake-client-instance-store.js

feat: Remove applications

---

docs/api/admin/events-api.md
docs/api/admin/feature-toggles-api.md
docs/api/admin/feature-types-api.md
docs/api/admin/metrics-api.md
docs/api/admin/state-api.md
docs/api/admin/strategies-api.md
lib/middleware/simple-authentication.js
package.json
yarn.lock

fix: add support for basic auth with simple-auth

---

docs/api/oas/index.html
docs/api/oas/openapi.yaml

fix: OpenApi - Added Client API calls

---

lib/db/client-instance-store.js
lib/db/client-metrics-db.js
lib/db/client-metrics-store.js
lib/db/client-metrics-store.test.js
lib/metrics.js
lib/metrics.test.js
lib/server-impl.js
lib/server-impl.test.js

Closes https://github.com/Unleash/unleash/issues/570

feat: add stop() method to gracefully terminate unleash

---

docs/api/oas/openapi.yaml

- Added 'Responses' section to streamline the Paths section.
- Added cURL example requests to all operations

chore: Update Open API specification

---

docs/getting-started.md

Updates docs with multiple docker options to easily get started with unleash.

docs: update getting started guide with docker options

---

lib/db/event-store.js
lib/routes/admin-api/archive.test.js
lib/routes/admin-api/feature.test.js
lib/services/feature-toggle-service.js
migrations/20210127094440-add-tags-column-to-events.js
test/fixtures/fake-feature-toggle-store.js

Added tags to events table and emitted events

---

lib/services/strategy-schema.js
test/e2e/api/admin/strategy.e2e.test.js

fix: Strategy schema should allow deprecated field

---

lib/middleware/simple-authentication.js

`lib/middleware/simple-authentication.js`

fix: typo in message in simple-authentication.js

---

CHANGELOG.md
docs/configuring-unleash.md
lib/db/db-pool.js
lib/event-type.js
lib/metrics.js
lib/metrics.test.js
lib/options.js
lib/options.test.js
test/e2e/helpers/database-init.js

Added explicit pool settings in options.db object

---

src/lib/addons/slack-definition.js
src/lib/addons/slack.js
src/lib/addons/webhook-definition.js
src/lib/event-differ.js
src/lib/event-type.js
src/lib/routes/admin-api/feature.js
src/lib/routes/admin-api/feature.test.js
src/lib/services/feature-toggle-service.js
src/test/e2e/api/admin/feature.e2e.test.js

How it loos like with the Slack Addon:
And if you remove "stale":
fixes: #726

feat: Introduce specific "feature stale" events

---

CHANGELOG.md
docs/getting-started.md
src/lib/options.js
src/lib/routes/admin-api/config.js
src/lib/services/index.js
src/lib/services/version-service.js
src/lib/services/versions-service.test.js
src/migrations/20210218090213-generate-server-identifier.js
src/test/fixtures/fake-setting-store.js

- Checks versions against https://version.unleash.run
- Generates a unique instance id (uuid)

Add a version service

---

src/lib/addons/addon.js

added try/catch logic around fetchRetry function so that we do not
crash if addon fetch call throws

fix: not crash if addon http post throws

---

src/lib/db/event-store.js
src/test/e2e/stores/event-store.e2e.test.js

fix: makes eventstore emit id and createdAt

---

src/test/e2e/api/admin/addon.e2e.test.js
src/test/e2e/api/admin/context.e2e.test.js
src/test/e2e/api/admin/event.e2e.test.js
src/test/e2e/api/admin/feature-archive.e2e.test.js
src/test/e2e/api/admin/feature.auth.e2e.test.js
src/test/e2e/api/admin/feature.custom-auth.e2e.test.js
src/test/e2e/api/admin/feature.e2e.test.js
src/test/e2e/api/admin/metrics.e2e.test.js
src/test/e2e/api/admin/state.e2e.test.js
src/test/e2e/api/admin/strategy.e2e.test.js
src/test/e2e/api/admin/tag-types.e2e.test.js
src/test/e2e/api/admin/tags.e2e.test.js
src/test/e2e/api/client/feature.e2e.test.js
src/test/e2e/api/client/metrics.e2e.test.js
src/test/e2e/api/client/register.e2e.test.js
src/test/e2e/health.e2e.test.js
src/test/e2e/helpers/database-init.js
src/test/e2e/services/access-service.e2e.test.js
src/test/e2e/services/client-metrics-service.e2e.test.js
src/test/e2e/services/project-service.e2e.test.js
src/test/e2e/stores/event-store.e2e.test.js
src/test/e2e/stores/project-store.e2e.test.js
src/test/e2e/stores/setting-store.e2e.test.js
src/test/e2e/stores/user-store.e2e.test.js

make sure we destroy all the stores which should also cancel
any background work they have for the database.

fix: Make e2e test more stable

---

src/lib/services/access-service.ts
src/lib/services/user-service.ts
src/migrations/20210415173116-rbac-rename-roles.js
src/test/e2e/api/admin/api-token.e2e.test.ts
src/test/e2e/api/admin/user-admin.e2e.test.ts
src/test/e2e/services/access-service.e2e.test.js
src/test/e2e/services/project-service.e2e.test.js

Root-roles:
- Admin
- Editor
- Viewer
Project roles:
- Owner
- Member

fix: rename rbac roles.

---

src/lib/create-config.ts
src/lib/logger.test.js
src/lib/logger.ts
src/lib/middleware/request-logger.js
src/lib/services/access-service.ts
src/lib/types/option.ts
src/server-dev.ts

feat: add option for LOG_LEVEL

---

src/migrations/20210428062103-user-permission-to-rbac.js

needed to migrate enterprise users to rbac.

fix: migration to create root roles for users with permissions

---

src/lib/middleware/rbac-middleware.test.ts
src/lib/middleware/rbac-middleware.ts

- When updating a toggle
- If the project is updated, the user performing the operation
will need UPDATE_FEATURE permission for both old and new project
fixes: #837

fix: rbac now checks permission for both projects

---

src/migrations/20210520171325-update-role-descriptions.js

Does this need a down migration? If so, what should we set description to?

fix: add migration

---

docs/client_sdk.md
docs/toggle_variants.md

Doc links fixed

---

README.md

Add [Utviklerpodden](https://pod.space/utviklerpodden/feature-flags-og-unleash-med-fredrik-oseberg) podcast episode to 'In the media'-list.

Update README.md - 'In the media'-list

---

src/lib/app.ts
src/lib/server-impl.test.js
src/lib/server-impl.ts
src/lib/types/core.ts
src/lib/util/graceful-shutdown.ts
websitev2/docs/deploy/configuring-unleash.md

fix: Do gracefull shutdown of Unleash on 'SIGINT' & 'SIGTERM'

---

package.json
src/lib/create-config.ts
src/lib/db/db-pool.ts
src/lib/server-impl.ts
src/lib/types/option.ts
src/lib/util/graceful-shutdown.ts
src/server-dev.ts
websitev2/docs/deploy/configuring-unleash.md
yarn.lock

This PR adds an additional unleash option to enable/disable graceful shutdown. Follow up on #706 
New options:
- `GRACEFUL_SHUTDOWN_ENABLE`
- `GRACEFUL_SHUTDOWN_TIMEOUT`

fix: add option for graceful shutdown

---

websitev2/docs/sdks/java.md

Someone obviously needed a coffee there.

Fix contextProvider not being in code block

---

websitev2/docs/sdks/unleash-proxy.md

correct then link for the JavaScript Proxy SDK

fix link to proxy-javascript

---

websitev2/docs/deploy/getting-started.md

fix: remove trailing backslash

---

websitev2/docs/sdks/unleash-proxy.md

Removed duplicated text from the doc

Fix Unleash Proxy docker pull instructions

---

README.md

Fix common grammar errors in README.md

Fix Error in README.md

---

websitev2/docs/deploy/configuring-unleash.md

Fix typo in sample

---

websitev2/docs/advanced/custom-activation-strategy.md

The previous implementation did exactly the opposite of what it was supposed to.

📝 Fix the custom activation strategy example

---

README.md
websitev2/docs/sdks/community.md
websitev2/docs/sdks/index.md
websitev2/docs/sdks/php.md
websitev2/sidebars.js

@ivarconr I basically copied the Java documentation and modified it for php, let me know if everything is ok.

Add official php documentation

---

src/lib/create-config.ts

Set default SMTP port to 587 instead of 567

---

websitev2/docs/deploy/getting-started.md
websitev2/docs/sdks/unleash-proxy.md

remove the conflict between docker steps and docker-compose

---

src/lib/db/environment-store.ts
src/lib/db/feature-strategy-store.ts
src/lib/services/state-service.test.ts
src/lib/types/model.ts
src/lib/types/stores/environment-store.ts
src/migrations/20210928065411-remove-displayname-from-environments.js
src/test/e2e/api/admin/environment.test.ts
src/test/e2e/api/admin/project/environments.e2e.test.ts
src/test/e2e/api/admin/project/feature.strategy.e2e.test.ts
src/test/e2e/api/admin/state.e2e.test.ts
src/test/e2e/api/client/feature.e2e.test.ts
src/test/e2e/api/client/feature.token.access.e2e.test.ts
src/test/e2e/api/client/metrics.e2e.access.e2e.test.ts
src/test/e2e/helpers/database.json
src/test/e2e/services/environment-service.test.ts
src/test/e2e/stores/project-store.e2e.test.ts
src/test/fixtures/fake-environment-store.ts

This will require a change in enterprise as well.

task: remove displayName from environments

---

src/lib/db/environment-store.ts
src/lib/services/project-service.ts
src/lib/types/model.ts
src/migrations/20210928080601-add-development-and-production-environments.js
src/migrations/20210928082228-connect-default-environment-to-all-existing-projects.js
src/test/e2e/helpers/database.json
src/test/e2e/services/project-service.e2e.test.ts

- Adds development and production environments.
- Connects default environment to all projects
- When creating a project connects the project to all enabled
environments

task: add built-in environments

---

website/docs/sdks/unleash-proxy.md

This PR attempts to explain what the proxy returns in more detail,
explaining how payloads work and what the `enabled` properties mean
and how they relate to the rest of the content.
As always: any feedback is very welcome: corrections, structural suggestions, and nits are all good!

docs: describe the shape of the data returned by the Unleash proxy

---

src/migrations/20200805091409-add-feature-toggle-type.js
src/migrations/20220119182603-update-toggle-types-description.js

feat: update feature types description

---

website/docs/api/admin/feature-toggles-archive-api.md

doc: Fix delete call for deleting feature toggles

---

website/docs/topics/a-b-testing.md

Mention impression data in the A/B discussion topic.

docs: Reference impression data from A/B testing doc

---

package.json
src/lib/db/index.ts
src/lib/db/project-store.ts
src/lib/services/project-service.ts
src/lib/types/stores/project-store.ts
src/test/e2e/api/admin/project/features.e2e.test.ts
src/test/e2e/api/client/feature.e2e.test.ts
src/test/fixtures/fake-project-store.ts
yarn.lock

Previously we've been doing N+1 queries for projects.
So until we've decided what to keep of the numbers. This should at least scale better than our current solution

fix: reduce project overview query count to 2.

---

src/lib/middleware/no-authentication.ts
src/lib/routes/admin-api/config.ts
src/lib/routes/admin-api/user.ts
src/lib/types/no-auth-user.ts

Co-authored-by: Fredrik Oseberg <fredrik.no@gmail.com>

fix: configure user endpoint when AuthType is NONE

---

src/lib/error/project-without-owner-error.ts
src/lib/routes/util.ts
src/lib/services/project-service.ts
src/test/e2e/services/project-service.e2e.test.ts

Co-authored-by: Christopher Kolstad <chriswk@getunleash.ai>

fix: changeRole to assign roles without existing members

---

website/docs/sdks/index.md

This PR addresses the questions raised in #1405 and adds information about how SDKs work in offline modes.
Closes #1405.

docs: describe how sdks work in offline modes

---

website/docs/advanced/strategy-constraints.md

With a little bit of boolean logic and thinking, we support SEMVER_GTE and SEMVER_LTE, if only implicitly.

docs: document how to get SEMVER_GTE/LTE functionality

---

website/docs/deploy/configuring-unleash.md

Improve database connection configuration documentation (#1445)

docs: add more content around database connections

---

src/lib/db/segment-store.ts
src/lib/services/segment-service.ts
src/lib/types/stores/segment-store.ts
src/migrations/20220405103233-add-segments-name-index.js
src/test/fixtures/fake-segment-store.ts

fix: reject duplicate segment names

---

website/docs/sdks/proxy-react.md
website/docs/sdks/proxy-svelte.md
website/docs/sdks/proxy-vue.md
website/sidebars.js

Adds docs for experimental vue and svelte proxy clients.

docs: add docs for vue and svelte clients

---

src/lib/util/rewriteHTML.test.ts
src/lib/util/rewriteHTML.ts
yarn.lock

Rewrites favicon url to be CDN if CDN prefix is set.

fix: set favicon icon to CDN if prefix is set

---

website/docs/advanced/feature-toggle-types.md

Add link to kill switch best practices blog post.

---

src/lib/routes/admin-api/archive.ts
src/lib/services/feature-toggle-service.ts
src/test/e2e/api/admin/archive.test.ts

feat: show archived toggles on a project level

---

src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Updates the open API snapshot respective to the new route added in https://github.com/Unleash/unleash/pull/1555

fix: update open api snapshot

---

src/lib/util/rewriteHTML.test.ts

https://trello.com/c/EbjaGycH
Connected to: https://github.com/Unleash/unleash-frontend/pull/940
Changing from react-scripts to [Vite](https://vitejs.dev/) may provide some DX-related improvements.

refactor: use vite html in test

---

src/lib/openapi/spec/variant-schema.ts

Update spec to set overrides to optional.

fix: update spec

---

src/migrations/20220511111823-patch-broken-feature-strategies.js

Apply migration to repair feature strategies with incorrect project ids

fix: Repair feature strategies with broken project ids

---

CONTRIBUTING.md
README.md

This PR adds detailed instruction on how to run this project directly from source code. The steps are added to the `CONTRIBUTING.md` file and linked from the readme.

docs: add "how to run" to CONTRIBUTING.md

---

src/lib/openapi/spec/clone-feature-schema.ts
src/lib/routes/admin-api/project/features.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

See https://github.com/Unleash/unleash/runs/6503894491?check_suite_focus=true#step:7:421

fix: the replaceGroupId field should be optional

---

src/lib/openapi/spec/feature-variants-response.ts
src/lib/openapi/spec/feature-variants-schema.ts
src/lib/openapi/spec/update-feature-variants-request.ts
src/lib/openapi/spec/variant-schema.ts
src/lib/routes/admin-api/project/variants.ts
src/test/e2e/api/admin/project/variants.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

This adds openapi middleware for the feature variants controller. :)

feat: add OpenApi spec to feature variants

---

src/lib/db/project-store.ts
src/lib/openapi/index.ts
src/lib/openapi/spec/environment-schema.ts
src/lib/openapi/spec/feature-schema.test.ts
src/lib/openapi/spec/feature-schema.ts
src/lib/openapi/spec/health-overview-schema.ts
src/lib/openapi/spec/health-report-schema.ts
src/lib/openapi/spec/project-environment-schema.ts
src/lib/openapi/spec/project-schema.ts
src/lib/openapi/spec/projects-schema.ts
src/lib/routes/admin-api/archive.ts
src/lib/routes/admin-api/project/environments.ts
src/lib/routes/admin-api/project/health-report.ts
src/lib/routes/admin-api/project/index.ts
src/lib/schema/project-schema.ts
src/lib/services/openapi-service.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

https://trello.com/c/DbqjKODY/1250-openapi-convert-some-controllers

refactor: add OpenAPI schemas to more controllers

---

website/docs/deploy/google-auth-hook.md

doc: proper api protection in google auth example.

---

.do/deploy.template.yaml

Correct branch name, so that user can deploy it directly to DigitalOcean.
Closes # .

fix: correct branch name

---

src/lib/openapi/index.ts
src/lib/openapi/spec/__snapshots__/api-token-schema.test.ts.snap
src/lib/openapi/spec/api-token-schema.test.ts
src/lib/openapi/spec/api-token-schema.ts
src/lib/openapi/spec/api-tokens-schema.ts
src/lib/openapi/spec/create-api-token-schema.ts
src/lib/openapi/spec/expires-at-schema.ts
src/lib/openapi/spec/update-api-token-schema.ts
src/lib/routes/admin-api/api-token.ts
src/lib/routes/admin-api/environments.ts
src/lib/routes/admin-api/index.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

refactor: add OpenAPI schema to api-token controller

---

src/lib/openapi/index.ts
src/lib/openapi/spec/health-check-schema.ts
src/lib/routes/health-check.ts
src/lib/routes/index.ts
src/lib/services/openapi-service.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

refactor: add OpenAPI schema to health-check controller

---

src/lib/openapi/index.ts
src/lib/openapi/spec/login-schema.ts
src/lib/routes/auth/reset-password-controller.ts
src/lib/routes/auth/simple-password-provider.test.ts
src/lib/routes/auth/simple-password-provider.ts
src/lib/routes/index.ts
src/lib/services/openapi-service.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

https://trello.com/c/x8kbp2dJ
Waiting for https://github.com/Unleash/unleash/pull/1692 to be merged first.

refactor: add OpenAPI schema to simple-password-provider controller

---

website/docs/deploy/configuring-unleash.md

Add documentation for configurable session options, including `clearSiteDataOnLogout` coming in v4.13.

fix: add docs for session options

---

src/lib/db/feature-tag-store.ts
src/test/e2e/api/admin/feature.e2e.test.ts
src/test/e2e/stores/feature-tag-store.e2e.test.ts

Adjusted message according to https://trello.com/c/D2laPQFd/1320-small-fixes-in-the-ui-part-2

fix: tag validation message

---

src/lib/db/feature-toggle-store.ts
src/lib/schema/feature-schema.ts
src/lib/types/model.ts
src/test/e2e/api/admin/project/features.e2e.test.ts

https://trello.com/c/G187Oycd
Would be great if someone more experienced with feature toggle variants could check whether this is a good idea or if there's a better way.

fix: copy feature variants

---

website/docs/user_guide/unleash_overview.md

I just learn about Unleash via GitLab as it integrates with their platform (as a backend API). I felt it worth mentioning that in the Unleash docs.

Add GitLab to Unleash server options

---

src/lib/db/access-store.ts
src/lib/db/role-store.ts
src/lib/services/access-service.ts
src/lib/services/group-service.ts
src/lib/services/index.ts
src/lib/services/project-service.ts
src/lib/types/events.ts
src/lib/types/stores/access-store.ts
src/migrations/20220704115624-add-user-groups.js
src/test/e2e/services/access-service.e2e.test.ts
src/test/e2e/services/api-token-service.e2e.test.ts
src/test/e2e/services/project-health-service.e2e.test.ts
src/test/e2e/services/project-service.e2e.test.ts
src/test/fixtures/fake-access-store.ts
src/test/fixtures/fake-role-store.ts

Adds logic for modifying and creating group -> role -> user links so that permissions can be consumed for groups

feat: implement crud for group permissions

---

src/lib/db/access-store.ts
src/lib/db/group-store.ts
src/lib/services/access-service.ts
src/lib/services/group-service.ts
src/lib/services/project-service.ts
src/lib/types/group.ts
src/lib/types/model.ts
src/lib/types/stores/access-store.ts
src/lib/types/user.ts
src/test/e2e/services/project-service.e2e.test.ts
src/test/fixtures/access-service-mock.ts
src/test/fixtures/fake-access-store.ts

1. Added "Added date" column to project access table, this includes user and group

Add added column to project access table

---

src/lib/db/feature-strategy-store.ts

Tested the SQL query and it also adds empty rows with fullOuterJoin. Changed those to left joins.

Fix full outer joins to left joins

---

src/lib/openapi/index.ts
src/lib/openapi/spec/group-schema.ts
src/lib/openapi/spec/users-groups-base-schema.test.ts
src/lib/openapi/spec/users-groups-base-schema.ts
src/lib/routes/admin-api/user-admin.ts
src/lib/types/group.ts
src/lib/types/stores/group-store.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

1. Fixed search users endpoint permissions
2. Added new endpoint that returns all users/groups with minimal fields.

Grouping access endpoing

---

package.json
yarn.lock

Release 4.14.0.beta.4

---

src/lib/db/user-store.ts
src/lib/types/group.ts

Simple update, that also sends the `last_seen` column to frontend.

Add possibility to see the last logged in person in group under projects

---

src/lib/services/openapi-service.ts

We're changing the open api log when there are errors to debug

feat: change log level for OpenAPI to debug

---

src/lib/openapi/util/standard-responses.ts

Changes parameter name in one function to increase clarity

fix: parameter naming

---

src/lib/db/event-store.test.ts
src/lib/db/event-store.ts
src/lib/openapi/index.ts
src/lib/openapi/spec/feature-events-schema.ts
src/lib/openapi/spec/search-events-schema.ts
src/lib/routes/admin-api/event.ts
src/lib/services/event-service.ts
src/lib/types/stores/event-store.ts
src/test/e2e/api/admin/event.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
src/test/e2e/services/setting-service.test.ts
src/test/e2e/stores/event-store.e2e.test.ts
src/test/fixtures/fake-event-store.ts

Related to https://linear.app/unleash/issue/1-120/add-searchfilter-for-event-log
Updates https://github.com/Unleash/unleash/issues/1876

feat: add event search endpoint

---

src/lib/db/feature-strategy-store.ts
src/lib/db/feature-toggle-client-store.ts

After looking into full outer joins more, we still had some empty rows coming in because of this.
I think there is no benefit of doing full outer joins, replaced everything with left join.

Remove full outer joins

---

src/migrations/20220816121136-add-metadata-to-api-keys.js

Add metadata to api keys - for aliases and frontend key CORS

Migration for API key metadata

---

src/lib/openapi/spec/ui-config-schema.ts
src/lib/routes/admin-api/config.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Feature flag to show/hide new token type in frontend
Relates to roadmap item: #1875

feat: add feature flag for embedded proxy

---

package.json
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/app.ts
src/lib/create-config.ts
src/lib/middleware/cors-origin-middleware.test.ts
src/lib/middleware/cors-origin-middleware.ts
src/lib/routes/admin-api/index.ts
src/lib/routes/proxy-api/index.ts
src/lib/types/option.ts
src/lib/util/parseEnvVar.test.ts
src/lib/util/parseEnvVar.ts
src/test/e2e/api/proxy/proxy.e2e.test.ts
yarn.lock

https://linear.app/unleash/issue/1-154/embedded-proxy-add-apifrontend-endpoints
https://github.com/Unleash/unleash/issues/1875

feat: add CORS support to the proxy endpoints

---

src/lib/util/collapseHourlyMetrics.ts

Optimize grouping for https://github.com/Unleash/unleash/pull/1928

refactor: improve performance of groupHourlyMetrics

---

src/lib/proxy/proxy-repository.ts
src/test/e2e/api/proxy/proxy.e2e.test.ts

Also updates a test to catch regressions.

fix: use correct project field for proxy features

---

package.json
yarn.lock

Closes https://github.com/Unleash/unleash/security/dependabot/18

fix: Prototype Pollution in async

---

website/docs/user_guide/unleash_overview.md

Edit (_we're talk nano-seconds_) to (_we're talking nano-seconds_)

docs: fix typo for overview guide

---

src/lib/services/segment-service.ts
src/test/e2e/api/client/segment.e2e.test.ts
src/test/e2e/api/proxy/proxy.e2e.test.ts

Adds an end-to-end test for using segments with the embedded proxy.
https://github.com/Unleash/unleash/issues/1875

refactor: test segments in the embedded proxy

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/app.ts
src/lib/create-config.test.ts
src/lib/create-config.ts
src/lib/middleware/cors-origin-middleware.test.ts
src/lib/middleware/cors-origin-middleware.ts
src/lib/openapi/index.ts
src/lib/openapi/spec/set-ui-config-schema.ts
src/lib/openapi/spec/ui-config-schema.ts
src/lib/routes/admin-api/config.ts
src/lib/routes/admin-api/user-admin.ts
src/lib/routes/proxy-api/index.ts
src/lib/services/setting-service.ts
src/lib/services/user-service.ts
src/lib/types/settings/frontend-settings.ts
src/lib/types/settings/simple-auth-settings.ts
src/lib/util/parseEnvVar.test.ts
src/lib/util/parseEnvVar.ts
src/lib/util/validateOrigin.test.ts
src/lib/util/validateOrigin.ts
src/test/e2e/api/admin/config.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
src/test/e2e/services/user-service.e2e.test.ts

https://linear.app/unleash/issue/1-171/embedded-proxy-instance-cors-settings-api
https://github.com/Unleash/unleash/issues/1875

feat: add CORS instance settings

---

frontend/package.json
frontend/vite.config.ts
frontend/yarn.lock

https://linear.app/unleash/issue/2-192/upgrade-vite-to-v3-in-frontend-after-the-merge
Related to: https://github.com/Unleash/unleash-frontend/pull/1237

chore: upgrade vite to v3

---

.github/workflows/release_changelog.yml

Fix GitHub release notes

---

Dockerfile

Fix docker failing

---

frontend/src/component/admin/groups/GroupForm/GroupFormUsersSelect/GroupFormUsersSelect.tsx
frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx
frontend/src/utils/search.ts

https://linear.app/unleash/issue/2-195/groups-improve-search

feat: improve group users select search

---

frontend/package.json
frontend/src/component/common/InstanceStatus/__snapshots__/InstanceStatusBar.test.tsx.snap
frontend/src/component/feedback/FeedbackCES/__snapshots__/FeedbackCESForm.test.tsx.snap
frontend/src/component/menu/Footer/ApiDetails/__snapshots__/ApiDetails.test.tsx.snap
frontend/src/component/menu/Footer/__snapshots__/Footer.test.tsx.snap
frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
frontend/yarn.lock

Fixes https://github.com/Unleash/unleash/pull/1973.

chore: update emotion 

---

src/lib/metrics.ts

Make the percentile metrics more adaptive to changes.
https://github.com/siimon/prom-client#summary

fix: Sliding window functionality for summaries

---

frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx

This sets an accessor field on status, which allows react-table to sort by the field

feat: set accessor on status field for health

---

frontend/src/component/addons/AddonList/AvailableAddons/AvailableAddons.tsx
frontend/src/component/addons/AddonList/ConfiguredAddons/ConfiguredAddons.tsx

By request from Nicolae, this PR adds a counter to the AddonsList.

feat: Add count to list of addons

---

frontend/src/component/environments/EnvironmentTable/EnvironmentTable.tsx

By request from Nicolae, this PR adds a counter to the EnvironmentsList.

feat add count to Environments

---

frontend/src/component/strategies/StrategiesList/StrategiesList.tsx

By request from Nicolae, this PR adds a counter to the Strategy types list.

feat: add count for strategy types list

---

frontend/src/component/project/ProjectList/ProjectList.tsx

By request from Nicolae, this PR adds a counter to the ProjectList, it will also list (x of y projects) when filtering.
https://linear.app/unleash/issue/1-197/add-the-title-counter-to-more-pages

feat: add project count to projectlist

---

frontend/src/component/context/ContextList/ContextList.tsx

By request from Nicolae, this PR adds a counter to the ContextFieldList, it will also list (x of y) when filtering.

feat: add count to context field list

---

frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx

https://linear.app/unleash/issue/1-216/health-count

feat: add features counter to health report table

---

frontend/src/component/tags/TagTypeList/TagTypeList.tsx
frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap

By request from Nicolae, this PR adds a counter to the TagTypes list.

feat: add count to tag types list

---

frontend/src/component/segments/SegmentTable/SegmentTable.tsx

By request from Nicolae, this PR adds a counter to the SegmentsList.

feat: add count to segment table

---

src/lib/openapi/index.ts
src/lib/openapi/spec/edge-token-schema.ts
src/lib/openapi/spec/validate-edge-tokens-schema.ts
src/lib/openapi/util/openapi-tags.ts
src/lib/routes/edge-api/index.ts
src/lib/routes/index.ts
src/lib/routes/unleash-types.ts
src/lib/services/edge-service.ts
src/lib/services/index.ts
src/lib/types/services.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Create endpoint that validates tokens for edge

Create endpoint that validates tokens for edge

---

package.json
scripts/jest-setup.js

Fix tests not passing when timezone not UTC

Fix tests not passing when timezone not UTC

---

frontend/src/component/admin/projectRoles/ProjectRoles/ProjectRoleList/ProjectRoleList.tsx

Adds count to project role list

feat: add count to project role list

---

frontend/src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditHeader/ConstraintAccordionEditHeader.tsx

Bug fix - Hide case sensitive button when changing operators
Closes # .

Bug fix - Hide case sensitive button when changing operators

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyEmpty/FeatureStrategyEmpty.tsx

Added groupId to Gradual rollout template
Closes # .

add groupId to gradual rollout template

---

frontend/src/component/admin/menu/AdminMenu.tsx
frontend/src/component/common/TabNav/TabNav/TabNav.styles.ts
frontend/src/component/common/TabNav/TabNav/TabNav.tsx
frontend/src/themes/theme.ts

Improve tabs UI on smaller devices
Closes # .

Improve tabs UI on smaller devices

---

.github/workflows/check_links.yaml

Schedule link checker to run at 12:30 UTC on Mon, Tue, Wed, Thu and Fri

Schedule link checker action

---

package.json

This makes `yarn test:unit` work

fix: make unit test target work

---

.github/workflows/build_prs_jest_report.yaml

This PR precedes https://github.com/Unleash/unleash/pull/2087 so we can first reproduce the issue and then verify the solution proposed by that PR.

Revert usage of pull_request_target

---

src/lib/db/pat-store.ts
src/lib/types/models/pat.ts
src/migrations/20220912165344-pat-tokens.js
src/test/e2e/api/user/pat.e2e.test.ts

Add description to PAT

---

src/lib/__snapshots__/create-config.test.ts.snap

Fix snapshot so tests will work

Fix snapshot so tests will work 

---

website/docs/advanced/custom-activation-strategy.md

Updated name and parameters description

---

website/docs/advanced/strategy-constraints.md

fix: typo in strategy-constraints.md

---

frontend/package.json
frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts
frontend/src/component/splash/SplashPageRedirect/SplashPageRedirect.tsx
frontend/yarn.lock

This commits lift the flags and makes Strategy Constraints available to all users of Unleash.
Read more in the docs:
https://docs.getunleash.io/advanced/strategy_constraints
Enjoy!
@ivarconr
Author and maintainer

feat: Open-Source Strategy Constraints

---

src/lib/db/access-store.ts
src/lib/db/project-store.ts
src/lib/openapi/spec/profile-schema.test.ts
src/lib/openapi/spec/profile-schema.ts
src/lib/routes/admin-api/user/user.ts
src/lib/services/access-service.ts
src/lib/types/stores/access-store.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
src/test/fixtures/fake-access-store.ts

Fix project structure when sending to profile.
Add extra fields for role.

Add some extra fields for profile

---

src/migrations/20220908093515-add-public-signup-tokens.js

Adds IF EXISTS to drop table 
Removes unused table
Closes # .

Update public signup migration files

---

frontend/src/component/common/index.jsx
frontend/src/hooks/api/actions/useApplicationsApi/useApplicationsApi.ts

This ensures that we url encode application names for our links.

fix: url encode application name in links

---

frontend/package.json

Fix yarn lint to fmt:check

---

src/lib/db/user-store.ts
src/test/e2e/api/admin/user/pat.e2e.test.ts

https://linear.app/unleash/issue/2-318/pats-dont-expire

fix: PAT not taking into account expires_at

---

src/lib/app.ts
src/lib/middleware/api-token-middleware.ts

* Accounts for basepath when setting up options
* Related to: [#1875](https://github.com/Unleash/unleash/issues/1875)
Closes # .

fix: CORS options path

---

frontend/src/component/admin/groups/CreateGroup/CreateGroup.tsx
frontend/src/component/admin/groups/EditGroup/EditGroup.tsx
frontend/src/component/admin/groups/Group/EditGroupUsers/EditGroupUsers.tsx
frontend/src/component/admin/groups/GroupForm/GroupForm.tsx
frontend/src/component/admin/groups/hooks/useGroupForm.ts
frontend/src/component/common/ItemList/ItemList.tsx
frontend/src/hooks/api/actions/useGroupApi/useGroupApi.ts
frontend/src/interfaces/group.ts
src/lib/db/group-store.ts
src/lib/openapi/spec/group-schema.ts
src/lib/types/group.ts
src/lib/types/stores/group-store.ts
src/migrations/20221011155007-add-user-groups-mappings.js
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

https://linear.app/unleash/issue/2-109/frontend-patch-ui-to-take-in-property-from-sso-response-to-add-users

feat: add SSO mappings to groups

---

frontend/src/component/user/Profile/PersonalAPITokensTab/CreatePersonalAPIToken/CreatePersonalAPIToken.tsx
src/lib/db/pat-store.ts
src/lib/services/pat-service.ts
src/lib/types/stores/pat-store.ts
src/test/e2e/api/admin/user/pat.e2e.test.ts
src/test/fixtures/fake-pat-store.ts

https://linear.app/unleash/issue/2-327/pats-dont-have-a-unique-description

fix: PATs should have an unique description (per user)

---

frontend/src/component/common/DateTimePicker/DateTimePicker.tsx
frontend/src/component/user/Profile/PersonalAPITokensTab/CreatePersonalAPIToken/CreatePersonalAPIToken.tsx
frontend/src/component/user/Profile/PersonalAPITokensTab/PersonalAPITokensTab.tsx

https://linear.app/unleash/issue/2-330/feedback-from-visma-pats-with-no-expirycustom-expiry
Front-end only, assumes "never" as a **very long** time from now.

PAT: add "never", "custom" options to expiry date

---

frontend/src/component/addons/AddonForm/AddonForm.tsx

fix: should only require CREATE_ADDON when creating addon

---

frontend/src/component/admin/groups/Group/Group.tsx
frontend/src/component/admin/groups/GroupForm/GroupForm.tsx
frontend/src/hooks/api/getters/useGroup/useGroup.ts
src/lib/db/group-store.ts
src/lib/openapi/spec/group-user-model-schema.ts
src/lib/services/group-service.ts
src/lib/types/group.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

When group syncing is disabled, now gray infromation box is displayed.
Also now in group members list, the person who added the person to group, is displayed.

UX additions to groups SSO syncing

---

frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCard.tsx
frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCardActions/GroupCardActions.tsx
frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx

https://linear.app/unleash/issue/2-331/ui-groups-cards-adjustments

Group misc UI fixes

---

src/lib/db/suggest-change-store.ts
src/lib/types/model.ts
src/lib/types/stores/suggest-change-store.ts
src/test/fixtures/fake-suggest-change-store.ts

1. Now drafts endpoint will return list of drafts
2. New schema for suggest changes
3. Smaller tweaks

Suggest changes refactoring and schema fixes

---

src/lib/db/suggest-change-store.ts
src/lib/types/model.ts
src/lib/types/stores/suggest-change-store.ts
src/migrations/20221810114644-add-suggest-changes-table.js
src/test/fixtures/fake-suggest-change-store.ts

Suggest changes updates

---

website/docs/api/client/feature-toggles-api.md

Change notice about who has access to constraints.
We recently open-sourced constraints.

docs: change notice about constraints availability.

---

frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts
frontend/src/component/project/Project/Project.tsx
frontend/src/component/suggestChanges/DraftBanner/DraftBanner.tsx
frontend/src/component/suggestChanges/SuggestedChangesSidebar/SuggestedChangesSidebar.tsx
frontend/src/component/suggestChanges/SuggestedChangeset/SuggestedChangeset.tsx
frontend/src/hooks/api/getters/useSuggestChange/useSuggestedChange.ts
frontend/src/hooks/api/getters/useSuggestedChangesDraft/useSuggestedChangesDraft.ts

Put draft changes into sidebar.
Relates to [roadmap ](https://github.com/orgs/Unleash/projects/10) item: #2251

feat: get suggested changeset draft

---

src/lib/db/access-store.ts
src/lib/db/feature-environment-store.ts
src/lib/db/project-store.ts
src/lib/types/model.ts
src/lib/types/stores/access-store.ts
src/lib/types/stores/feature-environment-store.ts
src/lib/types/stores/project-store.ts
src/test/fixtures/fake-access-store.ts
src/test/fixtures/fake-feature-environment-store.ts
src/test/fixtures/fake-project-store.ts

Adds support for cloning environments into Unleash. This does nothing on its own, and requires the related PR on enterprise to implement, related tests are also in that PR

add support for cloning environments

---

src/lib/server-impl.ts

* Takes the knex import and reexports it so we can keep the same types in the enterprise project
Closes # .

fix: re export knex

---

frontend/src/component/common/PageContent/PageContent.styles.ts
frontend/src/component/common/PageContent/PageContent.tsx
frontend/src/component/suggest-changes/ProjectSuggestions/SuggestionsTabs/ChangesetStatusCell/ChangesetStatusCell.tsx
frontend/src/component/suggest-changes/ProjectSuggestions/SuggestionsTabs/SuggestionsTabs.styles.ts
frontend/src/component/suggest-changes/ProjectSuggestions/SuggestionsTabs/SuggestionsTabs.tsx
frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
frontend/src/hooks/api/actions/useSuggestChangeApi/useSuggestChangeApi.ts

fix: suggestions table tabs state

---

frontend/src/component/common/PageContent/PageContent.styles.ts
frontend/src/component/common/PageContent/PageContent.tsx
frontend/src/component/suggest-changes/ProjectSuggestions/SuggestionsTabs/ChangesetStatusCell/ChangesetStatusCell.tsx
frontend/src/component/suggest-changes/ProjectSuggestions/SuggestionsTabs/ChangesetTitleCell/ChangesetTitleCell.tsx
frontend/src/component/suggest-changes/ProjectSuggestions/SuggestionsTabs/SuggestionsTabs.styles.ts
frontend/src/component/suggest-changes/ProjectSuggestions/SuggestionsTabs/SuggestionsTabs.tsx
frontend/src/component/suggestChanges/DraftBanner/DraftBanner.tsx
frontend/src/component/suggestChanges/SuggestedChangeOverview/SuggestedChangeHeader/SuggestedChangeHeader.tsx
frontend/src/component/suggestChanges/SuggestedChangeOverview/SuggestedChangeOverview.tsx
frontend/src/component/suggestChanges/SuggestedChangesSidebar/SuggestedChangesSidebar.tsx
frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
frontend/src/hooks/api/actions/useSuggestChangeApi/useSuggestChangeApi.ts
frontend/src/hooks/api/getters/useSuggestChange/useSuggestedChange.ts
frontend/src/hooks/useSuggestToggle.ts
src/lib/db/suggest-change-store.ts

* Adds API integration for the suggest changes endpoints
Closes # .

feat: integrate with API for suggest changes

---

src/lib/services/public-signup-token-service.ts
src/test/e2e/api/admin/public-signup-token.e2e.test.ts

Currently there was missing backend validation of expiry for public signup tokens. This PR adds a hard cap to the expiry.

Hard cap expiry date of public signup token

---

frontend/src/component/user/Profile/PersonalAPITokensTab/PersonalAPITokensTab.tsx
frontend/src/constants/values.ts
frontend/tsconfig.json
src/lib/db/pat-store.ts
src/lib/services/pat-service.ts
src/lib/types/stores/pat-store.ts
src/lib/util/constants.ts
src/test/e2e/api/admin/user/pat.e2e.test.ts
src/test/fixtures/fake-pat-store.ts

https://linear.app/unleash/issue/2-367/rate-limiting-absent-on-creatingadding-token

fix: limit total of PATs a user can have

---

frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx

Co-authored-by: Tymoteusz Czech <2625371+Tymek@users.noreply.github.com>
Before:
When switching toggles in the project overview unrelated toggled were flipped. It was due to server returning data in different order and frontend not having stable identity for table rows. 
After:
Now the row identity is inherited from the feature name. react-table wants getRowId to be memoized.
Unfortunately the table data is not fully types so sticking to any param for now.

Add stable row id.

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.styles.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/changeRequest.types.ts
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestStatusCell/ChangeRequestStatusCell.tsx
frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/component/changeRequest/changeRequest.utils.tsx

This PR adds styling and conditional badges to the header component of the change request overview. Notable changes include: 
* Extracting Badge to util function that can be called with the changeset state

feat: change request header

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyRemove/FeatureStrategyRemove.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvSwitches/FeatureOverviewEnvSwitch/FeatureOverviewEnvSwitch.tsx
frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/hooks/useChangeRequestsEnabled.ts

feat: env check in change requests

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts
src/lib/util/extract-user.ts
src/migrations/20221104123349-change-request-approval.js

1. Added database table for change request approvals
2. Removed separate endpoint for applying. **Now all state changes will go through same endpoint.**

Change request approvals table

---

src/lib/addons/webhook-definition.ts
src/lib/addons/webhook.test.ts
src/lib/addons/webhook.ts

Added unit test and made code prettier in 
webhook.ts
webhook.test.ts

Authorization header webhook

---

package.json
src/lib/middleware/content_type_checker.test.ts
src/lib/routes/client-api/metrics.ts
src/lib/routes/client-api/register.ts
src/lib/routes/public-invite.ts
yarn.lock

This pr upgrade @types/node to v16.18.3.
This also detected some inconsitent retrun types that I decided to fix.

fix: upgrade @types/node to v16.18.3

---

frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestConfiguration.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx

- Refactor project menu - merge "Access" and "Environments" with newly added "Change request configuration" into "Project settings" tab.
- Add Change request config page with table
- Add Change request dialog
Closes https://linear.app/unleash/issue/1-344/frontend-project-options
Relates to [roadmap](https://github.com/orgs/Unleash/projects/10) item: #2251

feat: project change request page frontend

---

src/lib/types/user.ts
src/lib/util/generateImageUrl.ts

We need gravatar making fn in the enterprise

Extract gravatar URL fn

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx
frontend/src/component/common/PermissionButton/PermissionButton.tsx

* This PR adds permission buttons to the change request overview which allows us to give visual clues to the user whether or not they are allowed to approve and apply a change request.
Closes #

feat: add permission buttons for change requests

---

frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestConfiguration.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts
frontend/src/hooks/api/getters/useChangeRequestConfig/useChangeRequestConfig.ts
yarn.lock

Integrates frontend with the change request settings backedn
Closes #

integrate change request settings be

---

frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
frontend/src/component/changeRequest/DraftBanner/DraftBanner.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts

* Adds polish to the sidebar
Closes #

fix: add discard actions

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyEmpty/AddFromTemplateCard/AddFromTemplateCard.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyEmpty/FeatureStrategyEmpty.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyRemove/FeatureStrategyRemove.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvSwitches/FeatureOverviewEnvSwitch/FeatureOverviewEnvSwitch.tsx
frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/hooks/useChangeRequestsEnabled.ts

* Use the change request settings to turn it on / off for an environment in a project
Closes #

feat: update hook to use change request settings

---

frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/Project/ProjectInfo/ProjectInfo.styles.ts
frontend/src/component/project/Project/ProjectInfo/ProjectInfo.tsx

Removes uneccesary info box about the project and projectId, this has been moved to the project header.
Closes #

fix: remove uneccesary code

---

src/migrations/20221114150559-change-request-comments.js

DB migration for changeset comments

Changeset comments schema

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/CopyStrategyIconMenu/CopyStrategyIconMenu.tsx

* Fixes a bug where change request configured was instead governed by the feature flag
Closes #

fix: copy strategy change request

---

frontend/src/component/environments/EnvironmentTable/EnvironmentActionCell/EnvironmentDeleteDialog/EnvironmentDeleteDialog.tsx
frontend/src/component/environments/EnvironmentTable/EnvironmentActionCell/EnvironmentDeprecateToggleDialog/EnvironmentDeprecateToggleDialog.tsx

Updates the text in some places related with the new environments updates. Hopefully this makes things even clearer 🙂

fix: update text in environments

---

src/lib/services/feature-toggle-service.ts

Remove change request api protection

Remove change request api protection

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/CopyStrategyIconMenu/CopyStrategyIconMenu.tsx

This PR fixes a bug where when you copy a strategy, instead of the strategy being copied to the target environment, it was copied to the source environment
Closes #

Copy strategy bug fix

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/db/feature-environment-store.ts
src/lib/db/project-store.ts
src/lib/services/feature-toggle-service.ts
src/lib/types/stores/feature-environment-store.ts

Add variants per env gaston

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/AddComment.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/AddCommentField.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/ChangeRequestComment.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/StyledAvatar.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/DraftBanner/DraftBanner.tsx
frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts

What it adds?
* list of comments
* adding a comment (can only add comment when the field is not empty)
* banner zIndex fix

first draft of the comments ui

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx

Current commenting user should have their own avatar, not change request author avatar

add comment with current user avatar

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyEnabled/FeatureStrategyEnabled.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx

Green box message changes for change requests
* composition over configuration - I'm composing by passing children props instead of branching inside the child component

conditional message for change request strategy form

---

frontend/src/component/admin/users/UsersList/UsersList.tsx

fix: Users list RWD

---

src/lib/services/feature-toggle-service.ts

With change requests functionality we need to separate feature toggle service methods exposed over API (protected) and service method calls that change requests service can invoke directly (unprotecte)

separate protected and unprotected routes

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/AddCommentField.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/ChangeRequestComment.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestComments/StyledAvatar.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestFeatureToggleChange/ChangeRequestFeatureToggleChange.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.styles.tsx

replacing gap with margins for older safari.

older safari does not support gap

---

website/docs/reference/api-tokens-and-client-keys.mdx

Updated **personal access tokens** section to reflect that users technically can set the expiration date to **never**.
Closes #

Updated personal access tokens for accuracy

---

src/lib/server-impl.ts

This PR adds (back) the permissions and eventType module exports
Closes #

add back removed permissions and eventType from module exports

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanel.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitch/FeatureOverviewSidePanelEnvironmentSwitch.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitches.tsx

https://linear.app/unleash/issue/2-423/update-feature-toggle-overview-sidepanel

feat: improved feature overview sidepanel env toggles

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanel.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitches.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelTags/FeatureOverviewSidePanelTags.tsx

https://linear.app/unleash/issue/2-423/update-feature-toggle-overview-sidepanel

feat: add tags to the new feature overview sidepanel

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanel.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.tsx

https://linear.app/unleash/issue/2-423/update-feature-toggle-overview-sidepanel

feat: add details section to overview sidepanel

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyItem.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/useStrategyChangeFromRequest.tsx

* Adds a badge to strategies if the change can be found and the change is relevant: 
* I was considering making this more ergonomic using the slots vs props pattern, but since this component is used in multiple places I left it as is for now. 
Closes #

feat: add badges to modified strategies

---

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/VariantDeleteDialog/VariantDeleteDialog.tsx

Small fix after talking with @NicolaeUnleash

fix: secondary button should say "cancel" instead of "close"

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx
frontend/src/hooks/api/getters/useChangeRequestOpen/useChangeRequestOpen.ts

Banner was not disappearing after apply and not changing status after approve.

fix cr banner

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelDetails/FeatureOverviewSidePanelDetails.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitch/FeatureOverviewSidePanelEnvironmentSwitch.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitches.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelTags/FeatureOverviewSidePanelTags.tsx

https://linear.app/unleash/issue/2-423/update-feature-toggle-overview-sidepanel

misc fixes related to loading, font-size, alignment

---

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsCard.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCopyFrom/EnvironmentVariantsCopyFrom.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/FeatureEnvironmentVariants.tsx

https://linear.app/unleash/issue/2-446/ui-simplify-design-with-some-improvements

fix: improve UI in env variants, simplify code

---

frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestFeatureToggleChange/StrategyChange.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestFeatureToggleChange/ToggleStatusChange.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx

Hide button to discard change when applied or cancelled or only 1 change is available

hide discard button

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
frontend/src/component/changeRequest/DraftBanner/DraftBanner.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyRemove/FeatureStrategyRemove.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/useStrategyChangeFromRequest.tsx
frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/StrategyList/StrategyItem/FeatureStrategyItem.tsx
frontend/src/hooks/api/getters/usePendingChangeRequests/usePendingChangeRequests.ts
frontend/src/hooks/useChangeRequestAddStrategy.ts
frontend/src/hooks/useChangeRequestToggle.ts

* Changes the naming of useOpenRequests to usePendingChangeRequests

fix: change domain vocabulary

---

frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

https://linear.app/unleash/issue/2-450/add-feature-flag

add tokens last seen feature flag

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx

ChangeRequest Author and Admin can Cancel ChangeRequest as long as it's not Applied or Cancelled.
Other users won't see a button.
Important:
* Cancel happens when the ChangeRequest is outside of a Draft state
* In Draft state we Discard ChangeRequest

cancel changes

---

frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx

react exhaustive check fix

---

frontend/src/hooks/api/getters/useChangeRequestConfig/useChangeRequestConfig.ts
frontend/src/hooks/api/getters/usePendingChangeRequests/usePendingChangeRequests.ts

Fetchers that depend on OSS/enterprise version should not be stuck on initial selection

Change fetcher in OSS chang

---

frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
frontend/src/component/changeRequest/DraftBanner/DraftBanner.tsx
frontend/src/component/changeRequest/changesCount.ts

Change count should reflect number of changes not number of feature toggles

changes count

---

frontend/src/component/events/EventCard/EventCard.tsx

With new events with longer names we need to align left column in the grid

log widths should be equal size

---

frontend/src/component/project/Project/ProjectOverview.tsx

Use project id for last viewed project

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanel.tsx

https://linear.app/unleash/issue/2-457/fix-feature-overview-sidepanel-environment-counter-to-only-include

fix: feature overview env count should only count enabled

---

src/migrations/20221125185244-change-request-unique-approvals.js

Make change request approvals unique

make approvals unique

---

frontend/cypress/integration/feature/feature.spec.ts

Fix test assumption

---

src/migrations/20221128165141-change-request-min-approvals.js

Min approvals should be stored when creating Change Request

store min approvals as part of change request creation

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx
frontend/src/component/changeRequest/changeRequest.types.ts

Min approvals should be fetched from change request, not from config

min approvals from cr not config

---

frontend/src/component/changeRequest/ChangeRequestConfirmDialog/ChangeRequestMessages/UpdateEnabledMessage.tsx
frontend/src/hooks/useChangeRequestToggle.ts

* This PR fixes an issue with flickering states in the change request dialogue

fix: flickering dialogue

---

frontend/src/component/events/EventDiff/EventDiff.tsx

add missing key

---

frontend/src/component/user/Profile/PersonalAPITokensTab/PersonalAPITokensTab.tsx

https://linear.app/unleash/issue/2-452/add-table-column-to-pats-table-ui

feat: add last seen column to PAT table

---

frontend/src/component/admin/apiToken/ApiTokenTable/ApiTokenTable.tsx
src/lib/db/api-token-store.ts

https://linear.app/unleash/issue/2-449/add-table-column-to-api-tokens-table-ui

feat: add last seen column to token table

---

src/lib/db/user-store.ts
src/lib/middleware/pat-middleware.ts
src/lib/services/user-service.ts
src/lib/types/stores/user-store.ts
src/test/fixtures/fake-user-store.ts

https://linear.app/unleash/issue/2-451/update-last-seen-column-for-pats

feat: update seen_at pat column

---

src/lib/services/feature-toggle-service.ts

Fix super small text issue

---

src/lib/db/feature-strategy-store.ts
src/test/e2e/api/admin/favorites.e2e.test.ts

This is follow up PR to https://github.com/Unleash/unleash/pull/2550, which addresses the issues that came up from reviews.

Some tweaks to favorites

---

frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx
frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts

Consistent usage of domain language

uniquitous language cleanup

---

website/docs/contributing/ADRs/front-end/preferred-form-architecture.md

A very quick typo fix. It's whether, not wheter. :)

fix typo in preferred-form-architecture

---

frontend/src/component/admin/apiToken/ConfirmToken/ConfirmToken.tsx
frontend/src/component/admin/instance-admin/InstanceStats/InstanceStats.tsx
frontend/src/component/admin/projectRoles/EditProjectRole/EditProjectRole.tsx
frontend/src/component/admin/projectRoles/ProjectRoleForm/ProjectRoleForm.tsx
frontend/src/component/admin/users/InviteLinkBar/InviteLinkBar.tsx
frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequestConfirmDialog/ChangeRequestMessages/CopyStrategiesMessage.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestFeatureToggleChange/ChangeRequestFeatureToggleChange.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewers/ChangeRequestReviewer.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ReviewButton/ReviewButton.tsx
frontend/src/component/changeRequest/DraftBanner/DraftBanner.tsx
frontend/src/component/common/PrettifyLargeNumber/PrettifyLargeNumber.test.tsx
frontend/src/component/common/SidebarModal/SidebarModal.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/CopyStrategyIconMenu/CopyStrategyIconMenu.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/useStrategyChangeFromRequest.tsx
frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/layout/Error/Error.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx
frontend/src/component/user/common/ResetPasswordForm/ResetPasswordForm.tsx
frontend/src/hooks/useCollaborateData.tsx
frontend/src/utils/formatDate.ts

linter fixes

---

src/lib/db/favorite-projects-store.ts
src/lib/db/feature-strategy-store.ts
src/lib/db/feature-toggle-client-store.ts
src/lib/db/index.ts
src/lib/db/project-store.ts
src/lib/openapi/spec/health-overview-schema.ts
src/lib/openapi/spec/project-schema.ts
src/lib/routes/admin-api/favorites.ts
src/lib/routes/admin-api/project/health-report.ts
src/lib/routes/admin-api/project/index.ts
src/lib/services/favorites-service.ts
src/lib/services/index.ts
src/lib/services/project-health-service.ts
src/lib/services/project-service.ts
src/lib/types/model.ts
src/lib/types/stores.ts
src/lib/types/stores/favorite-projects.ts
src/lib/types/stores/project-store.ts
src/test/e2e/api/admin/favorites.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
src/test/e2e/services/project-health-service.e2e.test.ts
src/test/fixtures/fake-favorite-projects-store.ts
src/test/fixtures/store.ts

Adds ability to favorite projects.
1. Can favorite project
2. Can unfavorite project
3. Favorite field is returned on `/api/admin/projects/default`
4. Favorite field is returned on` /api/admin/projects`

Favorite project

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.styles.ts
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewStatus/ChangeRequestReviewStatus.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx

Lighter warning on change request overview
Explanation text

change request overview warning colors

---

src/lib/routes/admin-api/favorites.ts
src/lib/services/favorites-service.ts
src/lib/services/project-health-service.ts
src/lib/types/events.ts

This PR adds 4 new events
1. FAVORITE_FEATURE_ADDED
2.  FAVORITE_FEATURE_REMOVED
3. FAVORITE_PROJECT_ADDED
4. FAVORITE_PROJECT_REMOVED

Add favorite events

---

src/lib/routes/admin-api/index.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Remove signup conditional flag

---

frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequest/CodeSnippetPopover/CodeSnippetPopover.tsx
frontend/src/component/events/EventCard/EventCard.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyExecution/StrategyExecution.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSegment/FeatureOverviewSegment.tsx

Visual representation of the new state:
Code representation of the diff:
* reusing StrategyExecution component for visualizations. Fixed how we handle segments so that it can work for current settings and for change requests. 
* refactored ChangeRequest component because there was too much indentation in code
* extracted CodeSnippetPopover to a separate component

visual changes representation

---

frontend/src/component/common/FavoriteIconButton/FavoriteIconButton.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/feature/FeatureView/FeatureView.styles.ts
frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/ProjectCard/ProjectCard.styles.ts
frontend/src/component/project/ProjectCard/ProjectCard.tsx
frontend/src/component/project/ProjectList/ProjectList.tsx
frontend/src/hooks/api/actions/useFavoriteFeaturesApi/useFavoriteFeaturesApi.ts
frontend/src/hooks/api/actions/useFavoriteProjectsApi/useFavoriteProjectsApi.ts
frontend/src/hooks/api/getters/useFeature/emptyFeature.ts
frontend/src/hooks/api/getters/useProject/useProject.ts
frontend/src/interfaces/featureToggle.ts
frontend/src/interfaces/project.ts
src/lib/routes/admin-api/index.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Add an ability to star a toggle from it's overiew.

feat: favorite feature and project

---

frontend/src/component/common/Loader/Loader.styles.ts
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestConfiguration.tsx

fix flickering toggle

---

src/lib/services/feature-toggle-service.ts

Let the unprotected route to create strategy so that Change Request Applier doesn't need a permission for strategy creation

CR applier should be able to create strategy

---

.github/workflows/publish-new-version.yaml

github action to publish new npm version

---

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantModal/EnvironmentVariantModal.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsCard.tsx
src/lib/addons/webhook-definition.ts
website/docusaurus.config.js

This PR fixes some broken links we had in the application. It also adds redirects for those links so that they should work in the future.
Because it's important to have links that work 💁

Docs(fix): add more (missing) redirects, fix links

---

frontend/src/hooks/api/getters/useUiConfig/useUiConfig.ts

Hopefully a cleaner and DRY way of checking for the current Unleash plan level, which may help in cases like https://github.com/Unleash/unleash/pull/2585#discussion_r1038138963

feat: add plan checks to uiconfig

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestTitleCell/ChangeRequestTitleCell.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.styles.ts
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx
frontend/src/component/common/PageContent/PageContent.styles.ts
frontend/src/component/environments/EnvironmentTable/EnvironmentNameCell/EnvironmentNameCell.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/ProjectEnvironment/ProjectEnvironment.tsx
frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap

Change request overview optimized for mobile
Change requests list with scrollable table and tabs:

adjusting mobile styles

---

frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx

Using default sort type. sortType text does not exist.

fix sort type

---

frontend/src/hooks/api/getters/useConditionalSWR/useConditionalSWR.ts
frontend/src/hooks/api/getters/useEnterpriseSWR/useEnterpriseSWR.ts

Moves `useConditionalSWR` into its own file.

Refactor move ConditionalSWR into its own file

---

frontend/src/component/admin/menu/AdminMenu.tsx
frontend/src/component/admin/menu/CenteredNavLink.tsx
frontend/src/component/project/Project/Project.styles.ts
frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/Project/ProjectOverview.tsx

Consistent margin top:
Equal spacing between tabs:
Extracted low level component in admin tab.

UI adjustments change requests

---

frontend/vercel.json

* Change the vercel paths to proxy against unleash instead of unleash4.
Closes #

fix: update vercel proxy paths

---

frontend/index.html
frontend/src/component/providers/PlausibleProvider/PlausibleProvider.tsx
src/lib/util/load-index-html.ts
src/lib/util/rewriteHTML.ts

This PR puts the ui flags in the index.html in a meta tag. This makes them accessible without logging in and allows us to track user signups with invite links
Closes #

ui flags replaced in index.html

---

frontend/cypress/integration/feature/feature.spec.ts
frontend/cypress/integration/groups/groups.spec.ts
frontend/cypress/integration/projects/access.spec.ts
frontend/cypress/integration/segments/segments.spec.ts
frontend/package.json

* Removes exports statements in e2e tests
* Updates package.json to optionally use heroku url for e2e tests when running locally

fix: update package json and remove empty exports

---

frontend/src/hooks/api/getters/useProjectChangeRequests/useProjectChangeRequests.ts

One hook hasn't been migrated to the new enterprise check

adding missing enterprise check

---

frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ProjectChangeRequests.tsx
frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestConfiguration.tsx
frontend/src/component/project/ProjectAccess/ProjectAccess.tsx
frontend/src/component/project/ProjectList/ProjectList.tsx

https://linear.app/unleash/issue/2-491/improve-premiumfeature-component-and-how-its-implemented
Refactors `PremiumFeature` to be a bit more straightforward and match new designs, both in standalone and tooltip modes.
This also fixes the fact that the change requests tab did not display the premium feature info, along with other smaller fixes.

Refactor premium feature

---

frontend/src/hooks/api/getters/useConditionalSWR/useConditionalSWR.ts

More idiomatic conditional SWR (https://swr.vercel.app/docs/conditional-fetching#conditional)

Conditional swr

---

website/docs/reference/front-end-api.md

remove experimental notice

---

.github/workflows/publish-new-version.yaml

When we run npm version locally it will run all tests.
When we run npm version in Github Action preversion with tests will be skipped since we already tested the PR and merged code on main.

do not test again when creting version from github actions

---

frontend/src/hooks/api/getters/useFeature/useFeature.ts

Fixes an issue where the feature toggle endpoint gets request too many times repeatedly.

fix: too many reqs to feature toggle endpoint

---

frontend/src/component/admin/apiToken/ApiTokenTable/ApiTokenTable.tsx
frontend/src/component/user/Profile/PersonalAPITokensTab/PersonalAPITokensTab.tsx
frontend/src/component/user/Profile/Profile.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/services/api-token-service.ts
src/lib/services/user-service.ts
src/lib/types/experimental.ts

https://linear.app/unleash/issue/2-470/clean-up-flag

remove feature flag: tokens last seen

---

README.md
docker-compose.yml
scripts/wait-for
src/lib/create-config.ts

Use latest official image for Unleash for simplicity. 
Also takes away the proxy as it is not needed anymore.

fix: move docker-compose to this repo

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.styles.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewers/ChangeRequestReviewers.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/ReviewChangesHeader/ReviewChangesHeader.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestTitleCell/ChangeRequestTitleCell.tsx
frontend/src/component/common/SidebarModal/SidebarModal.tsx

UI tweaks for Change Request release continues

change request ui tweaks

---

frontend/src/component/changeRequest/ProjectChangeRequests/ProjectChangeRequests.tsx
frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestConfiguration.tsx
frontend/src/component/project/ProjectAccess/ProjectAccess.tsx
frontend/src/component/project/ProjectList/ProjectList.tsx

Add unique trackable URLs for Pro/Enterprise feature lead generation

Add unique trackable URLs for Pro/Enterprise feature lead generation

---

frontend/src/component/admin/groups/GroupForm/GroupForm.tsx

https://linear.app/unleash/issue/2-495/group-form-small-ui-fix

fix: adds bottom margin to SSO sync info box

---

frontend/src/component/admin/groups/Group/Group.tsx
frontend/src/component/common/FavoriteIconButton/FavoriteIconButton.tsx
frontend/src/component/common/MainHeader/MainHeader.tsx
frontend/src/component/common/Table/VirtualizedTable/VirtualizedTable.styles.ts
frontend/src/component/common/Table/cells/FavoriteIconCell/FavoriteIconCell.tsx
frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/project/Project/Project.styles.ts
frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/ProjectCard/ProjectCard.tsx

https://linear.app/unleash/issue/2-504/misc-frontend-related-fixes-mostly-related-with-favorites

fix: misc UI/UX fixes, mostly related with favorites

---

frontend/src/component/admin/groups/Group/Group.tsx
frontend/src/component/common/FavoriteIconButton/FavoriteIconButton.tsx
frontend/src/component/common/MainHeader/MainHeader.tsx
frontend/src/component/common/Table/VirtualizedTable/VirtualizedTable.styles.ts
frontend/src/component/common/Table/cells/FavoriteIconCell/FavoriteIconCell.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/feature/FeatureView/FeatureView.tsx
frontend/src/component/project/Project/Project.styles.ts
frontend/src/component/project/Project/Project.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/ProjectCard/ProjectCard.tsx
frontend/src/hooks/useGlobalLocalStorage.ts

https://linear.app/unleash/issue/2-508/make-pinned-favorites-a-global-preference
Also introduces a `useGlobalLocalStorage` hook where system-wide preferences that are stored in LocalStorage can be maintained.

feat: make favorites a global preference

---

frontend/src/component/common/PermissionButton/PermissionButton.tsx
frontend/src/component/common/PermissionIconButton/PermissionIconButton.tsx
frontend/src/component/common/PermissionSwitch/PermissionSwitch.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/FeatureStrategyConstraints.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx
frontend/src/hooks/useHasAccess.ts

Fixing constraints add/edit/delete not visible for change requests users.
Also refactored new access hooks to reflect hasAccess parameter order so that migration is just a matter of method replacement.

added contraints checking in change request permissions

---

website/docs/how-to/how-to-set-up-group-sso-sync.md
website/docs/reference/deploy/import-export.md

This PR contains two small doc updates/fixes:
1. Update the availability notice on SSO syncing to indicate that it has been released.
2. Add a note to the Import API description that importing environments will make Unleash delete API keys belonging to those environments.
1. To keep the docs up to date.
2. Because this behavior surprised (and rightly so, I'd say) a user, who then suddenly had all their SDKs unable to connect.

docs: small fixes

---

frontend/src/component/changeRequest/ChangeRequest/Changes/FeatureToggleChanges.tsx
frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx
frontend/src/hooks/api/getters/useChangeRequest/useChangeRequest.ts

* Conflict margin tweak
* Refresh change request overview
* time ago fix

refresh change request, add conflict margin, set time ago

---

frontend/src/component/admin/traffic/TrafficMetricsChart.tsx
src/lib/services/client-metrics/instance-service.ts
src/server-dev.ts

Disables networkView for dev for now. Attempts to fail more gracefully both on the service and front-end.

fix: disable networkView for dev, fail more gracefully

---

frontend/src/component/admin/projectRoles/hooks/useProjectRoleForm.ts
frontend/src/component/project/Project/Project.tsx
frontend/src/hooks/useChangeRequestsEnabled.ts

remove change request flag

---

frontend/src/component/admin/projectRoles/ProjectRoles/ProjectRoleList/ProjectRoleList.tsx
frontend/src/component/admin/users/UsersList/UsersList.tsx
frontend/src/component/archive/ArchiveTable/ArchiveTable.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsTable/FeatureMetricsTable.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsTable/EnvironmentVariantsTable.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureVariantsList/FeatureVariantsList.tsx
frontend/src/component/playground/Playground/PlaygroundResultsTable/PlaygroundResultsTable.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportTable.tsx
frontend/src/component/segments/SegmentTable/SegmentTable.tsx
frontend/src/component/user/Profile/PersonalAPITokensTab/PersonalAPITokensTab.tsx
frontend/src/hooks/useConditionallyHiddenColumns.ts

https://linear.app/unleash/issue/2-515/adapt-tables-to-use-the-new-useconditionallyhiddencolumns-hook
Uses the new `useConditionallyHiddenColumns` hook, like mentioned here: https://github.com/Unleash/unleash/pull/2691
Also includes small fixes for things I caught along the way. See comments below.

Use new useConditionallyHiddenColumns hook

---

README.md

Related to breaking change Github did on their badges https://github.com/badges/shields/issues/8671
Closes #

Make build badge work correctly

---

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx
frontend/src/component/admin/network/NetworkTraffic/NetworkTraffic.tsx
frontend/src/component/common/Mermaid/Mermaid.tsx
frontend/src/utils/unknownify.ts
src/lib/services/client-metrics/instance-service.ts

Some suggestions for https://github.com/Unleash/unleash/pull/2706
Unrelated, but also fixes some random issues with the Mermaid component.

Simplify prometheus queries suggestions

---

frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx

https://unleash-internal.slack.com/archives/C046LV6HH6W/p1671533789519689

fix: set a more generous maxWidth in access timeago cells

---

frontend/src/component/admin/maintenance/MaintenanceToggle.tsx
frontend/src/hooks/usePlausibleTracker.ts

Adds tracking with plausible to maintenance feature

Adds tracking to maintenance feature

---

frontend/package.json
frontend/src/component/common/MessageBanner/MessageBanner.tsx
frontend/src/component/common/MessageBanner/MessageBannerDialog/MessageBannerDialog.tsx
frontend/yarn.lock

Adds the option of showing a dialog and adds markdown support to it, could be useful to show changelogs inside Unleash in the future.

feat: adds an optional dialog and markdown support

---

frontend/src/component/admin/menu/AdminMenu.tsx

Tabs from admin section were missing paddings left-right.
This PR adds these paddings.

Fix padding for tabs in admin section

---

website/docs/contributing/ADRs/ADRs.md
website/docs/contributing/ADRs/front-end/sdk-generator.md
website/docs/contributing/frontend/overview.md

Documenting the decision.
Closes [1-537/openapi-generator-adr](https://linear.app/unleash/issue/1-537/openapi-generator-adr)

docs: Orval ADR

---

frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountDeleteDialog/ServiceAccountDeleteDialog.tsx
frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountModal/ServiceAccountTokens/ServiceAccountTokens.tsx

https://linear.app/unleash/issue/2-544/delete-service-account-show-latest-activity-for-that-service-account

feat: show token info when deleting SA

---

frontend/src/component/admin/maintenance/MaintenanceToggle.tsx
frontend/src/component/admin/maintenance/index.tsx

Maintenance UI fixes

---

frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx

Handle dots in env names inside react table.
Closes #2847

fix: table accessor should handle dots

---

frontend/src/component/feature/FeatureToggleList/ExportDialog.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/interfaces/uiConfig.ts

MVP for export features UI. Includes a new button in the feature toggle list you can use to trigger a dialog that exports the current filtered selection and allows you to choose which environment to fetch from.
Closes #

Feat/export UI

---

frontend/src/component/admin/apiToken/ApiTokenTable/ApiTokenTable.tsx
frontend/src/component/project/ProjectEnvironment/ProjectEnvironment.tsx
frontend/src/hooks/api/getters/useUiConfig/defaultValue.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts
src/lib/types/experimental.ts

Remove environments flag, because it is not needed anymore. Everyone can use environments.

Remove E flag

---

frontend/src/hooks/api/getters/useAuth/useAuthPermissions.ts
frontend/src/interfaces/uiConfig.ts

Maintenance mode fix

---

src/lib/routes/admin-api/export-import.ts
src/lib/services/export-import-service.ts
src/lib/services/index.ts
src/test/e2e/api/admin/export-import.e2e.test.ts

First skeleton of batch import:
* injecting feature toggle service because I want to reuse logic and not just the store

feat: first skeleton of the batch import

---

frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountDeleteDialog/ServiceAccountDeleteDialog.tsx
frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountTokensCell/ServiceAccountTokensCell.tsx
frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountsTable.tsx

https://linear.app/unleash/issue/2-559/check-if-uiux-and-overall-design-looks-correct
We're happy with the overall design and behaviour for a first iteration, only identified these small changes for now.

fix: SA UI/UX improvements and fixes

---

frontend/src/hooks/api/getters/useChangeRequestConfig/useChangeRequestConfig.ts

Conditionally fetch change request config to fix 404

---

src/test/e2e/api/admin/playground.e2e.test.ts

property based tests will run only once because otherwise e2e is flaky

test: fix test runs to 1

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvSwitches/FeatureOverviewEnvSwitch/FeatureOverviewEnvSwitch.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvSwitches/FeatureOverviewEnvSwitches.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitch/FeatureOverviewSidePanelEnvironmentHider.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitch/FeatureOverviewSidePanelEnvironmentSwitch.tsx

Some small UI/UX fixes related to user-scoped hidden environments in the feature overview after aligning with @NicolaeUnleash

fix: improve hidden envs UI/UX

---

src/lib/services/export-import-service.ts
src/test/e2e/api/admin/export-import.e2e.test.ts

Ability to import feature strategies to existing project/environment. In later versions we may consider creating project/environment on the fly when they don't exists. This is early draft.
```
{
data: {
features: [exportedFeature],
featureStrategies: [exportedStrategy],
},
project: project,
environment: environment,
}
```

feat: import feature strategies

---

frontend/src/component/common/BreadcrumbNav/BreadcrumbNav.tsx
frontend/src/component/layout/MainLayout/MainLayout.tsx

https://linear.app/unleash/issue/2-575/improve-the-breadcrumb-spacing

fix: improve breadcrumb spacing

---

frontend/src/component/layout/MainLayout/MainLayout.tsx

replace flex with overflow to prevent margin collapsing

fix: flex was breaking change request banner

---

frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountModal/ServiceAccountTokens/ServiceAccountCreateTokenDialog/ServiceAccountCreateTokenDialog.tsx
frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountModal/ServiceAccountTokens/ServiceAccountTokens.tsx

Fixes a small bug on service account token creation where the tokens the new one was being validated against were not the most up-to-date ones.

fix: SA unique token bug

---

src/lib/db/feature-environment-store.ts
src/lib/openapi/spec/export-query-schema.ts
src/lib/openapi/spec/export-result-schema.ts
src/lib/routes/admin-api/export-import.ts
src/lib/services/export-import-service.ts
src/lib/types/events.ts
src/lib/types/stores/feature-environment-store.ts
src/test/e2e/api/admin/export-import.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
src/test/fixtures/fake-feature-environment-store.ts

1. Support file download
2. Add event for export
3. Segment support
4. Custom context fields support 
5. Tags support

Export features

---

src/lib/openapi/spec/export-result-schema.ts
src/lib/services/export-import-service.ts
src/test/e2e/api/admin/export-import.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Segment export

---

src/lib/db/project-store.ts
src/test/e2e/services/project-service.e2e.test.ts

fix: project feature_count should not include archived

---

src/lib/openapi/spec/feature-environment-schema.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

sortOrder property was missing in some schemas as seen in the logs:
```
[2023-01-19T18:00:52.506] [DEBUG] openapi-service.ts - Invalid response: {
schema: '#/components/schemas/healthOverviewSchema',
errors: [
{
instancePath: '/features/0/environments/0',
schemaPath: '#/additionalProperties',
keyword: 'additionalProperties',
params: [Object],
message: 'must NOT have additional properties'
}
]
}
```
and
```
[2023-01-19T18:01:04.245] [DEBUG] openapi-service.ts - Invalid response: {
schema: '#/components/schemas/featuresSchema',
errors: [
{
instancePath: '/features/0/environments/0',
schemaPath: '#/additionalProperties',
keyword: 'additionalProperties',
params: [Object],
message: 'must NOT have additional properties'
}
]
}
```
Tested using:
```shell
curl -H "Authorization: ${TOKEN}" …
```

fix: Add missing sortOrder property

---

frontend/package.json
frontend/src/component/common/ConstraintAccordion/ConstraintAccordionList/ConstraintAccordionList.tsx
frontend/src/component/project/Project/Import/FileDropZone.tsx
frontend/src/component/project/Project/Import/ImportModal.tsx
frontend/src/component/project/Project/Import/ImportTogglesDropZone.tsx
frontend/yarn.lock

Adding dropzone component for storing dropped files in memory.
Dragging a file to dropzone sets the text area with auto-formatted JSON.
Please ignore styling for now as it's just a placeholder.
Design decision:
* separate styling from dropzone logic so that dropzone can be used outside of the import feature
* choosing react-dropzone as it's small 7.5kB w gzip and very popular (2.5M weekly downloads)

feat: file dropzone

---

frontend/src/component/project/Project/Import/FileDropZone.tsx
frontend/src/component/project/Project/Import/ImportExplanation.tsx
frontend/src/component/project/Project/Import/ImportModal.tsx
frontend/src/component/project/Project/Import/PulsingAvatar.tsx
frontend/src/component/project/Project/Import/StyledFileDropZone.tsx

Making import/upload joyful with the avatar animation.
https://user-images.githubusercontent.com/1394682/213745654-9cb5d464-dee0-4f95-8389-ca838e67b6ec.mov
Also added import rules description:

feat: pulsing avatar for import

---

frontend/src/component/project/Project/Import/ImportModal.tsx
frontend/src/component/project/Project/Import/ImportTimeline.tsx

timeline component

---

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/FeatureEnvironmentVariants.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/PushVariantsButton/PushVariantsButton.tsx
frontend/src/hooks/api/actions/useFeatureApi/useFeatureApi.ts

This adds the push to all button to the UI
Relates to [roadmap](https://github.com/orgs/Unleash/projects/10) item: #2254

feat: add push to all button to UI

---

frontend/vite.config.ts
src/server-dev.ts

https://vitejs.dev/config/build-options.html#build-modulepreload

fix: preload error

---

frontend/src/component/project/Project/Import/ImportModal.tsx
frontend/src/component/project/Project/Import/ImportStage.ts
frontend/src/component/project/Project/Import/ImportTimeline.tsx
frontend/src/component/project/Project/Import/configure/ConfigurationStage.tsx
frontend/src/component/project/Project/Import/configure/ImportOptions.tsx
frontend/src/component/project/Project/Import/validate/ValidationStage.tsx

* keep the state (env, payload) between the configuration stages (moving state up to the parent modal from each individual stage)
* show import button when no errors

feat: back transition from validate to configure

---

frontend/src/component/project/Project/Import/ImportModal.tsx
frontend/src/component/project/Project/Import/ImportStage.ts
frontend/src/component/project/Project/Import/ImportTimeline.tsx
frontend/src/component/project/Project/Import/PulsingAvatar.tsx
frontend/src/component/project/Project/Import/StageName.ts
frontend/src/component/project/Project/Import/configure/ConfigurationStage.tsx
frontend/src/component/project/Project/Import/configure/ImportOptions.tsx
frontend/src/component/project/Project/Import/import/ImportStage.tsx
frontend/src/component/project/Project/Import/validate/ValidationStage.tsx
frontend/src/hooks/api/actions/useImportApi/useImportApi.ts
frontend/src/hooks/api/actions/useValidateImportApi/useValidateImportApi.ts
src/lib/services/export-import-service.ts

Last import stage UI handling success, error and loading states

feat: import stage

---

frontend/src/component/project/Project/ProjectInfo/HealthWidget.tsx
frontend/src/component/project/Project/ProjectInfo/ProjectInfo.styles.ts
frontend/src/component/project/Project/ProjectInfo/ProjectInfo.tsx
frontend/src/component/project/Project/ProjectInfo/ToggleTypesWidget.tsx
frontend/src/component/project/Project/ProjectOverview.tsx

Implements ToggleTypeWidget
Refactored HealthWidget to it's own component
Closes #

ToggleTypesWidget

---

frontend/src/component/project/Project/ProjectOverview.tsx

Closes [issue/1-600](https://linear.app/unleash/issue/1-600/project-overview-table-when-you-have-to-many-columns-visible-it)

fix: project table overflow

---

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/PushVariantsButton/PushVariantsButton.tsx

https://linear.app/unleash/issue/2-652/slight-improvements-and-fixes-on-the-push-to-environment-feature
Includes:
- Hover effect on the items should cover the full width of the menu;
- Clicking anywhere on the item should toggle the check;
- Small refactoring

fix: small fixes on variants push to env UI

---

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantModal/EnvironmentVariantModal.tsx

This checks the feature toggle to see if change request is enabled for variants
Tested  locally

fix: check is flag enabled!

---

frontend/src/component/project/Project/Import/import/ImportStage.tsx

Show info banner that import is in change request mode

change request import banner

---

frontend/src/component/project/Project/Import/configure/ImportOptions.tsx
frontend/src/component/project/Project/ProjectHealth/ReportTable/ReportCard/ReportCard.tsx
src/lib/services/export-import-service.ts

* filter out unused fields that are failing on import
* make sure to populate environments dropdown when envs change

filter out unused fields as they fail import validation

---

frontend/src/component/project/Project/Import/validate/ValidationStage.tsx
src/lib/app.ts
src/lib/middleware/unless-middleware.ts
src/lib/services/export-import-service.ts

* import should accept bigger payload

upload limit and import ui tweaks

---

frontend/src/utils/formatPath.test.ts
frontend/src/utils/formatPath.ts

Revert "formatApiPath / formatAssetPath - Implement smart functionality to detect double subpath"

---

frontend/src/hooks/api/getters/useFeatures/useFeatures.ts
frontend/src/hooks/api/getters/useFeaturesArchive/useFeaturesArchive.ts

Archive page is not loading archived feature toggles.
When fetching from the server is not including the baseUrl

fix: missing formatApiPath

---

src/lib/db/feature-strategy-store.ts
src/lib/db/feature-tag-store.ts
src/lib/services/export-import-service.ts
src/lib/types/stores/feature-tag-store.ts
src/test/fixtures/fake-feature-tag-store.ts

Import was failing on import of tags for features that don't exist in the new unleash. We filter out tags from other features that we don't export.
Also feature strategy query seems to be incorrect so I fixed it

exclude tags for other features

---

src/lib/db/feature-environment-store.ts
src/lib/openapi/spec/export-result-schema.test.ts
src/lib/openapi/spec/feature-environment-schema.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Export variants env

---

frontend/src/component/project/Project/ProjectInfo/HealthWidget.tsx
frontend/src/component/project/Project/ProjectInfo/ProjectInfo.styles.ts
frontend/src/component/project/Project/ProjectInfo/ProjectInfo.tsx
frontend/src/component/project/Project/ProjectInfo/ToggleTypesWidget.tsx

Am I loading "potentially stale" features right?
Testing Linear integration:
Close 1-605
Close ID-1-605
Close ID1-605

feat: new project health widget

---

src/migrations/20230125065315-project-stats-table.js

fix: down migration

---

src/lib/server-impl.ts
src/lib/services/index.ts
src/lib/services/scheduler-service.test.ts
src/lib/services/scheduler-service.ts
src/lib/types/services.ts

refactor: separate scheduling from DI

---

src/lib/domain/calculate-project-health/calculate-project-health.ts
src/lib/services/project-health-service.ts

Refactor project health calculation as domain code

refactor: project health domain

---

src/lib/services/index.ts
src/lib/services/project-health-service.ts

Move scheduler out of the service

Schedule health report

---

src/lib/openapi/spec/export-result-schema.test.ts
src/lib/openapi/spec/export-result-schema.ts
src/lib/services/export-import-service.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Adds a simple functionality to export also tag types.

Export tag types

---

src/lib/domain/project-health/project-health.test.ts
src/lib/domain/project-health/project-health.ts
src/lib/services/project-health-service.ts

Tests for https://github.com/Unleash/unleash/pull/3024

Project health tests

---

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx

Use `useMemo` as in NetworkTraffic: https://github.com/Unleash/unleash/blob/6ad27c2e9c1c57cdbc376fedaca957b906dc67e4/frontend/src/component/admin/network/NetworkTraffic/NetworkTraffic.tsx#L173-L176
Hopefully this should help getting rid of the flakiness of the UI

fix: try to make the network overview stable

---

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx
frontend/src/component/project/Project/ProjectOverview.tsx

It seems to have slipped but let me know if it's needed. The thing is it logs in every screen.

Remove console log

---

website/docs/contributing/backend/overview.md

One-liner to fix typo within contribution guide

Update overview.md, fix typo

---

frontend/src/component/project/Project/Project.styles.ts
src/lib/db/feature-environment-store.ts
src/lib/db/feature-strategy-store.ts
src/lib/db/feature-tag-store.ts
src/lib/db/feature-toggle-store.ts

* order by queries for export
* fixed UI bug with nested h elements and hidden text in project name

export queries use order by feature name

---

frontend/src/component/admin/maintenance/MaintenanceToggle.tsx
src/server-dev.ts

Currently, there was no toast, when maintenance mode was changed. Now user gets nice toast to have better feedback.

Add maintenance toast

---

frontend/src/component/InitialRedirect.tsx
frontend/src/component/admin/apiToken/ApiTokenTable/ApiTokenTable.tsx
frontend/src/component/admin/apiToken/ConfirmToken/ConfirmToken.tsx
frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx
frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx
frontend/src/component/admin/cors/CorsForm.tsx
frontend/src/component/admin/cors/index.tsx
frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCard.tsx

Github was reporting those warnings on all PRs so cleaning it.

clear warnings

---

src/lib/services/openapi-service.ts

as you can see below message with `params: [Object],`, i'd like to view this Object inside params to easy for debugging
```
[2023-01-20T03:56:35.912] [DEBUG] openapi-service.ts - Invalid response: {
schema: '#/components/schemas/clientFeaturesSchema',
errors: [
{
instancePath: '/features/0',
schemaPath: '#/additionalProperties',
keyword: 'additionalProperties',
params: [Object],
message: 'must NOT have additional properties'
}
]
}
```

JSON stringify errors to view more info of params 

---

frontend/package.json
frontend/src/component/admin/projectRoles/hooks/useProjectRoleForm.ts
frontend/src/component/admin/serviceAccounts/ServiceAccountsTable/ServiceAccountModal/ServiceAccountTokens/ServiceAccountTokens.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
frontend/src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/ConstraintAccordionViewHeaderInfo.tsx
frontend/src/component/common/ConstraintAccordion/ConstraintAccordionView/ConstraintAccordionViewHeader/ConstraintAccordionViewHeaderMultipleValues.tsx
frontend/src/component/common/ConstraintAccordion/ConstraintOperatorSelect.tsx
frontend/src/component/common/DividerText/DividerText.tsx
frontend/src/component/common/EnvironmentStrategiesDialog/EnvironmentStrategyDialog.tsx
frontend/src/component/common/MessageBanner/MessageBanner.tsx
frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
frontend/src/component/common/Table/cells/LinkCell/LinkCell.tsx
frontend/src/component/environments/EnvironmentTable/EnvironmentActionCell/EnvironmentActionCellPopover/EnvironmentActionCellPopover.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyEmpty/FeatureStrategyEmpty.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/CopyStrategyIconMenu/CopyStrategyIconMenu.tsx
frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitches.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/VariantsTooltipWarning.tsx
frontend/src/component/project/Project/Import/configure/StyledFileDropZone.tsx
frontend/src/component/project/Project/ProjectStats/ProjectStats.tsx
frontend/src/component/project/ProjectCard/ProjectCard.tsx
frontend/src/component/project/ProjectEnvironment/ProjectEnvironment.tsx
frontend/src/component/segments/SegmentForm.tsx
frontend/src/component/user/NewUser/NewUser.tsx
frontend/src/component/user/PasswordAuth.tsx
frontend/src/component/user/common/SecondaryLoginActions.tsx
frontend/src/hooks/api/getters/useEnterpriseSWR/useEnterpriseSWR.ts
frontend/src/hooks/api/getters/useProjectChangeRequests/useProjectChangeRequests.ts
frontend/src/hooks/api/getters/useSegments/useSegments.ts

Fixing all warnings. The point is with 50+ warnings those are ignored.
Important:
* removed exhaustive react deps check as we ignore them anyway
* one logical condition fix
* using ===
* removed unused vars

fix: remove all warnings

---

frontend/src/component/admin/apiToken/ApiTokenTable/ApiTokenTable.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectApiAccess.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

Closes # [1-612](https://linear.app/unleash/issue/1-612/first-iteration-of-project-token-management)

show api access screen in projet settings

---

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx
frontend/src/component/admin/network/NetworkTraffic/NetworkTraffic.tsx

The x-axis is showing 10:31 which is not the right date. If you look at the tooltips the date is correct but not the x-axis
How it looks:
How it will look like:

fix: x axis not displaying the right date

---

frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx

This replicates the logic of unknowify library to filter out undefined

fix: unknown in network view

---

.github/workflows/continuous-publish-new-version.yaml
.github/workflows/release.yaml

Moving repo sync signal after npm publish

refactor: move repo sync signal after npm publish

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/openapi/spec/feature-schema.ts
src/lib/openapi/spec/group-schema.ts
src/lib/routes/admin-api/project/features.ts
src/lib/services/openapi-service.ts
src/lib/types/experimental.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Add option to run unleash in strict schema

Add option to run unleash in strict schema validation

---

src/lib/openapi/spec/environment-schema.ts
src/lib/openapi/spec/feature-environment-schema.ts
src/lib/openapi/spec/feature-schema.ts
src/lib/openapi/spec/project-overview-schema.ts
src/lib/openapi/spec/project-schema.test.ts
src/lib/openapi/spec/project-schema.ts
src/lib/openapi/spec/project-stats-schema.ts
src/lib/openapi/spec/projects-schema.ts
src/lib/routes/admin-api/project/index.ts
src/lib/types/model.ts
src/test/e2e/api/admin/project/environments.e2e.test.ts
src/test/e2e/api/admin/project/features.e2e.test.ts
src/test/e2e/api/admin/project/projects.e2e.test.ts
src/test/e2e/api/admin/strategy.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Gradual schema improvements:
* adding strictSchemaValidation flag to some tests in order to fix schema validation errors in responses
* project overview was using health schema which is probably incorrect
* adding examples and descriptions to selected schemas

Gradual schema improvements

---

frontend/src/component/project/Project/Import/validate/ValidationStage.tsx
frontend/src/component/project/Project/Project.tsx
frontend/src/hooks/api/actions/useValidateImportApi/useValidateImportApi.ts

feat: validate import permissions

---

src/lib/db/feature-toggle-store.ts
src/test/e2e/api/admin/export-import.e2e.test.ts

When no features are selected for export return no features. This will fix the issue with archived features were returned.

fix: export empty list

---

frontend/src/component/project/Project/Import/ImportModal.tsx
frontend/src/component/project/Project/Import/import/ImportStage.tsx

After import we should refresh a list of toggles and change request banner. This should also work when someone closes the import dialog before the import is finished.

Refresh after import

---

frontend/src/component/App.tsx
frontend/src/component/InitialRedirect.tsx

This PR will force a refetch of the uiConfig after the user has logged into the system.

fix: fetch uiConfig when the user logs in

---

frontend/src/component/project/Project/Import/validate/ValidationStage.tsx
src/lib/openapi/spec/export-result-schema.ts
src/lib/services/export-import-service.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

* we don't need to export whole segments, only id and name are needed for importing. It can save a lot of kB since segments can have very long lists of contraints
* also fixing error message because the previous one was too specific for cover all suberrors

Export segments limited info

---

src/lib/services/export-import-service.ts
src/lib/services/scheduler-service.test.ts
src/test/e2e/api/admin/export-import.e2e.test.ts

Context fields can appear in 4 different places: strategy constraints, strategy stickiness, variant stickiness, variant overrides
All 4 cases are covered by test

feat: extract custom context fields from all possible locations

---

frontend/src/component/feature/FeatureToggleList/ExportDialog.tsx
frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx

In addition to global toggles export we now support project level export

feat: export project level feature toggles

---

src/lib/server-impl.ts

Scheduler should stop on unleash stopping

feat: stop scheduler on app stop

---

frontend/src/component/feature/FeatureView/FeatureOverview/AddTagDialog/AddTagDialog.tsx
frontend/src/hooks/usePlausibleTracker.ts

Closes # [1-669](https://linear.app/unleash/issue/1-669/plausible-tracking-if-needed-in-preparation-for-beta)

suggest tags plausible tracking

---

.github/workflows/gradual-strict-null-checks.yml
src/lib/types/experimental.ts
src/lib/util/parseEnvVar.ts

Post a comment in the Pull Request rather than echo in the console in case of an error. Also, [reduced the null check errors by 26](https://github.com/Unleash/unleash/actions/runs/4196924954/jobs/7278564622#step:5:40)

chore: comment outcome of null check action

---

frontend/package.json

Starting with [Demo](https://app.unleash-hosted.com/demo/) backend should work with `cd frontend && yarn && yarn start:demo`

Update demo start script

---

frontend/src/component/project/Project/ProjectStats/Feedback.tsx
frontend/src/component/project/Project/ProjectStats/HelpPopper.tsx
frontend/src/component/project/Project/ProjectStats/ProjectStats.tsx
frontend/src/component/project/Project/ProjectStats/StatusBox.tsx
frontend/src/hooks/usePersistentGlobalState.ts
frontend/src/hooks/usePlausibleTracker.ts

https://linear.app/unleash/issue/1-694/widgets-explanation-plausible-buttons

Project stats feedback

---

frontend/src/hooks/api/actions/useProjectApiTokensApi/useProjectApiTokensApi.ts

fix incorrect path

---

src/lib/services/index.ts

Note about "a seam" in the code

docs: seam explanation

---

frontend/src/component/admin/apiToken/ApiTokenTable/ApiTokenTable.tsx
frontend/src/component/admin/apiToken/ProjectsList/ProjectsList.tsx

Temporary fix for a bug crashing the UI in ApiTokenTable (API Access page
Closes #

fix token type description

---

src/lib/export-import-toggles/export-import-service.ts
src/lib/export-import-toggles/import-permissions-service.ts
src/lib/export-import-toggles/import-validation-messages.ts

Move permissions service from another repo

refactor: migrate permissions service from another repo

---

src/lib/features/export-import-toggles/import-toggles-store.ts

fix: db type

---

src/migrations/20230224093446-drop-createdBy-from-notifications-table.js

remove createdBy column from notifications table

---

src/migrations/20230222154915-create-notiications-table.js

fix: add on delete cascade to notifications and userNotifications tables

---

.github/update_own_version.sh
.github/workflows/continuous-publish-new-version.yaml

fix: gh action shell

---

frontend/src/component/common/Table/cells/TimeAgoCell/TimeAgoCell.tsx
frontend/src/component/signOnLog/SignOnLogTable/SignOnLogTable.tsx

Slight refactor to `TimeAgoCell` that allows passing in a date format function.
Suggested by @gastonfournier in https://github.com/Unleash/unleash/pull/3193#pullrequestreview-1315064957

feat: dateFormat in TimeAgoCell

---

src/lib/openapi/spec/bulk-registration-schema.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

This adds support for connectVia the way we intend to use it and start now supports also a string

Improve bulk metrics

---

package.json
yarn.lock

Let's see if the GH action error is gone after we revert this dependency

fix: revert lib version

---

frontend/src/component/admin/users/CreateUser/CreateUser.tsx
frontend/src/component/admin/users/CreateUser/ProUserLimitWarning/ProUserLimitWarning.tsx
frontend/src/component/admin/users/CreateUser/SeatCostWarning/SeatCostWarning.tsx
frontend/src/component/admin/users/UsersList/UserLimitWarning/UserLimitWarning.tsx
frontend/src/component/admin/users/UsersList/UsersList.tsx
frontend/src/hooks/useUsersPlan.ts

UI on user creation warning about costs in Pro plan.

feat: paid users limit in UI

---

frontend/src/component/strategies/StrategiesList/StrategySwitch/StrategySwitch.tsx

Fixing this issue:
https://linear.app/unleash/issue/1-699/ui-bug-duplicate-strategy-tooltip

fix: strategy access tooltip

---

src/lib/features/export-import-toggles/createExportImportService.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/services/index.ts

Pass event store around for event emitter semantics. This will fix import not triggering notifications

fix: pass shared event store

---

frontend/src/component/common/Notifications/Notification.tsx
frontend/src/component/common/Notifications/Notifications.tsx
frontend/src/hooks/api/getters/useNotifications/useNotifications.ts

Adds the user created by avatar and name to the notification.

feat: add user created by

---

frontend/src/component/segments/SegmentDocs.tsx
frontend/src/component/segments/SegmentFormStepTwo.tsx
website/docs/reference/deploy/configuring-unleash.md
website/docs/reference/segments.mdx

- Updates the segment information on top to be clearer - No longer an experimental feature, but we do have some limits in place;
- Also updates the documentation to better reflect this;
Co-authored-by: @thomasheartman

feat: better segment info

---

frontend/src/component/admin/users/UsersList/UserTypeCell/UserTypeCell.tsx
frontend/src/component/admin/users/UsersList/UsersList.tsx

Adjustments for stripe auto charge

feat: users ui adjustments

---

src/lib/routes/index.ts
src/test/e2e/api/auth/simple-password-provider.e2e.test.ts

https://linear.app/unleash/issue/2-732/rate-limit-auth-endpoints-in-enterprise
Updates the rate-limit to reflect the [recent rate-limiting in Enterprise](https://github.com/ivarconr/unleash-enterprise/pull/381).

feat: update rate-limit

---

frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingPlan.tsx
frontend/src/component/admin/billing/BillingHistory/BillingHistory.tsx

Adds created date to invoices and some UI tweaks

feat: invoices created date

---

src/lib/openapi/index.ts
src/lib/openapi/spec/update-tags-schema.ts
src/lib/routes/admin-api/feature.ts
src/test/e2e/api/admin/feature.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

- Create UpdateTagsSchema
- Create PUT endpoint
Relates to# https://linear.app/unleash/issue/1-767/refactor-existing-tag-component-to-also-allow-removing-tags

feat: creates a PUT endpoint for updating tags

---

frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx

Fix hard refresh on project page affecting exported envs

fix: load export dialog after envs loaded

---

src/lib/openapi/spec/client-feature-schema.ts
src/lib/routes/client-api/feature.ts
src/lib/services/feature-toggle-service.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Service returning client feature data filters in only relevant fields. Anything that is not part of the openapi schema will be removed.

feat: filter out all data fields other than explicit openapi fields

---

frontend/src/component/segments/CreateSegment/CreateSegment.tsx
frontend/src/component/segments/EditSegment/EditSegment.tsx
frontend/src/component/segments/SegmentForm.tsx
frontend/src/component/segments/SegmentFormStepOne.tsx
frontend/src/component/segments/hooks/useSegmentForm.ts
frontend/src/interfaces/segment.ts
src/lib/db/segment-store.ts

https://linear.app/unleash/issue/2-741/add-project-dropdown-into-creation-of-segments
Allows users to bind a segment to a project when creating or editing a segment.

feat: allow adding project to segment

---

src/lib/middleware/pat-middleware.test.ts
src/lib/server-impl.test.ts

Remove warning from test that was touching scheduler, so that we're one step closer to zero warnings in CI build.
Warnings came from scheduler calling nonexistent methods from the test mock.
Also: missing mock methods for PAT last seen cc: @nunogois

fix: remove remaining warnings in tests

---

src/migrator.ts
src/test/e2e/api/admin/user/pat.e2e.test.ts

* db migrate was reading --verbose setting that WebStorm/Intellij set by default so it was impossible to silence DB migrations in dev
* also fixing last e2e test logging unnecessary stuff to stderr

feat: disable verbosity from db-migrate

---

src/lib/openapi/index.ts
src/lib/openapi/spec/index.ts
src/lib/openapi/spec/stickiness-schema.ts
src/lib/routes/admin-api/project/index.ts
src/test/e2e/api/admin/project/projects.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Introduces 2 new endpoints (behind flag `projectScopedStickiness` to set and get the setting
Closes #

feat: default stickiness per project in settings

---

src/migrations/20230314131041-project-settings.js

feat: project settings migration

---

.github/workflows/build.yaml

Building main when building the main branch. I thought it was not needed but apparently it is

fix: add build frontend

---

frontend/src/component/project/Project/ProjectSettings/ProjectApiAccess/ProjectApiAccess.tsx

This PR fixes an issue where permissions would not allow you to create an API token in the new project API management view. In addition, it fixes an issue where if you missed the permission to read API tokens, you would be blocked from creating one as well. 
Closes #

fix: project permissions

---

src/lib/routes/admin-api/project/project-archive.ts
src/lib/routes/admin-api/project/project-features.ts
src/test/e2e/api/admin/feature-archive.e2e.test.ts
src/test/e2e/api/admin/project/features.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Now all 3 operations are in the same controller. They also support project level permissions.
1. Archive features
2. Revive features
3. Delete features

feat: refactor archive

---

frontend/src/component/project/Project/CreateProject/CreateProject.tsx
frontend/src/component/project/Project/EditProject/EditProject.tsx
frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
frontend/src/component/project/Project/hooks/useProjectForm.ts
frontend/src/hooks/api/getters/useProject/useProject.ts
frontend/src/interfaces/project.ts
frontend/src/interfaces/uiConfig.ts
src/lib/db/project-store.ts
src/lib/features/export-import-toggles/export-import-permissions.e2e.test.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/openapi/spec/health-overview-schema.ts
src/lib/openapi/spec/project-overview-schema.ts
src/lib/openapi/spec/project-schema.ts
src/lib/services/project-schema.ts
src/lib/services/project-service.ts
src/lib/services/state-service.test.ts
src/lib/types/model.ts
src/lib/types/stores/project-store.ts
src/test/e2e/api/admin/archive.test.ts
src/test/e2e/api/admin/instance-admin.e2e.test.ts
src/test/e2e/api/admin/project/features.e2e.test.ts
src/test/e2e/api/admin/project/projects.e2e.test.ts
src/test/e2e/api/admin/state.e2e.test.ts
src/test/e2e/api/client/feature.e2e.test.ts
src/test/e2e/api/client/feature.token.access.e2e.test.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
src/test/e2e/api/proxy/proxy.e2e.test.ts
src/test/e2e/services/api-token-service.e2e.test.ts
src/test/e2e/services/project-service.e2e.test.ts
src/test/e2e/stores/project-store.e2e.test.ts

* Adding UI and backend service for project mode (open or protected)
* fixing type errors
* project mode is made mandatory for the backend internals since create and update project have joi schema that can provide a default value at the edges
* similarly our read query always default to open for projects that never had this option set explicitly
Followup work:
* extend cypress tests for this feature
* hide buttons for change requests client side when project mode is protected and user is not a member

feat: project mode

---

frontend/src/component/menu/Header/Header.tsx

If we don't hide notifications they'll generate 404

feat: hide notifications from oss version

---

frontend/src/component/menu/Header/Header.tsx

fix: hidden notifications

---

frontend/src/component/project/Project/EditProject/EditProject.tsx

We're hitting /settings endpoint that returns 404. Adding a flag to safely continue work on this feature without breaking sandbox.

fix: project stickiness behind flag

---

frontend/src/component/project/Project/ProjectForm/CollaborationModeTooltip.tsx
frontend/src/component/project/Project/ProjectForm/ProjectForm.styles.ts
frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx

feat: project mode tooltip

---

frontend/src/component/archive/ArchiveTable/ArchiveBatchActions.tsx
frontend/src/component/feature/FeatureToggleList/ExportDialog.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ArchiveButton.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ManageTags.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/MoreActions.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ProjectFeaturesBatchActions.tsx
frontend/src/hooks/usePlausibleTracker.ts

Add plausible to all batch operations
1. Archiving
2. Tagging
3. Staling
4. Unstaling
5. Reviving
6. Deleting

feat: batch operatsion plausible events

---

frontend/src/component/archive/ArchiveTable/ArchiveBatchActions.tsx
frontend/src/component/archive/ArchiveTable/ArchiveTable.tsx
frontend/src/component/common/BatchSelectionActionsBar/BatchSelectionActionsBar.tsx
frontend/src/component/common/InstanceStatus/InstanceStatus.tsx
frontend/src/component/layout/MainLayout/MainLayout.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
frontend/src/themes/app.css

Sticky batch actions bar

---

src/lib/openapi/spec/health-overview-schema.ts
src/lib/openapi/spec/project-overview-schema.ts
src/lib/openapi/spec/project-schema.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Project mode openapi specs change: Removing confusing nullable field. Making wording consistent
Depends on: https://github.com/Unleash/unleash/pull/3360

feat: collaboration mode API cleanup

---

frontend/src/component/feature/FeatureView/FeatureSettings/FeatureSettingsProject/FeatureSettingsProjectConfirm/FeatureSettingsProjectConfirm.tsx
src/lib/services/feature-toggle-service.ts
src/test/e2e/services/feature-toggle-service-v2.e2e.test.ts

Backend check to verify we cannot switch toggle project to a project that has change requests enabled in any environment. We can add extra UI enhancement on top of it in a separate PR.

feat: stop change project on change request enabled

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx

Apply change request button should be disabled when the changes are being applied. Otherwise we allow for double apply submission.

feat: disable apply button on loading

---

frontend/src/hooks/api/actions/useProjectApi/useProjectApi.ts
src/lib/db/project-store.ts
src/lib/openapi/spec/health-overview-schema.ts
src/lib/openapi/spec/project-overview-schema.ts
src/lib/openapi/spec/project-schema.ts
src/lib/services/project-service.ts
src/lib/types/model.ts
src/lib/types/models/api-token.ts
src/lib/types/stores/project-store.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
src/test/fixtures/fake-project-store.ts

Changes the schema and api to accept any string for defaultStickiness
Closes #

Fix: make stickiness accept any string

---

frontend/src/component/menu/routes.ts

Follow up to https://github.com/Unleash/unleash/pull/3409:
`Login history` and `Project roles` are also Enterprise features.

fix: update route modes

---

frontend/src/component/admin/apiToken/ApiTokenForm/EnvironmentSelector/EnvironmentSelector.tsx
frontend/src/component/admin/apiToken/CreateApiToken/CreateApiToken.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectApiAccess/CreateProjectApiTokenForm.tsx
src/lib/types/models/api-token.ts
src/test/e2e/api/admin/api-token.e2e.test.ts

This PR removes the check for deprecated environments when validating api token environment.
Unifies global and project level tokens allow selection of deprecated environments when creating an api token
Adds 'deprecated' to the EnvironmentSelector when appropriate
Closes #

fix: make api tokens ui consistent and remove check for deprecated envs.

---

.github/workflows/reset_heroku.yml

feat: reset heroku GH action

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

Reverts https://github.com/Unleash/unleash/pull/3417 - If we're not going forward with this project at this stage, we should clean up after ourselves and remove the unused flag that we added.

refactor: revert adding apiPagination feature flag

---

.github/workflows/e2e.frontend.yaml
frontend/cypress.d.ts
frontend/cypress/README.md
frontend/cypress/global.d.ts
frontend/cypress/integration/feature/feature.spec.ts
frontend/cypress/integration/groups/groups.spec.ts
frontend/cypress/integration/import/import.spec.ts
frontend/cypress/integration/projects/access.spec.ts
frontend/cypress/integration/projects/notifications.spec.ts
frontend/cypress/integration/projects/overview.spec.ts
frontend/cypress/integration/projects/settings.spec.ts
frontend/cypress/integration/segments/segments.spec.ts
frontend/cypress/support/API.ts
frontend/cypress/support/UI.ts
frontend/cypress/support/commands.ts
frontend/cypress/support/index.ts
frontend/cypress/tsconfig.json
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/EnvironmentVariantsModal.tsx
frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.tsx
frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
frontend/src/component/project/Project/hooks/useProjectForm.ts
frontend/src/hooks/useDefaultProjectSettings.ts
frontend/tsconfig.json

Adds proper typescript support.
Created reusable commands
Added README for cypress test
Refactored tests
Fixed bugs as I found them.
Closes #

chore: refactor Cypress tests

---

frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
frontend/src/interfaces/uiConfig.ts

feat: remove project mode flag

---

src/lib/services/scheduler-service.test.ts

Some of the tests in scheduler were flaky due to small tick values for setInterval. This change should make the tests more stable while still testing the integration with the system scheduler.

test: increase timer values in scheduler integration test

---

src/lib/openapi/spec/environment-project-schema.ts
src/lib/openapi/spec/environment-schema.ts
src/lib/openapi/spec/environments-project-schema.ts
src/lib/routes/admin-api/environments.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

This fleshes out the documentation for actions tagged with Environments. 
A rather small PR since previous efforts had covered most of the operations already.

docs: Flesh out openapi for tag: Environments

---

frontend/cypress/integration/projects/settings.spec.ts
frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/EnvironmentVariantsModal.tsx
frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.tsx
frontend/src/component/feature/StrategyTypes/FlexibleStrategy/StickinessSelect/StickinessSelect.tsx
frontend/src/hooks/api/getters/useProject/useProject.ts
frontend/src/hooks/useDefaultProjectSettings.ts
frontend/src/interfaces/project.ts
src/lib/db/project-store.ts
src/lib/services/project-service.ts
src/lib/types/model.ts
src/test/e2e/api/admin/project/features.e2e.test.ts
src/test/e2e/api/proxy/proxy.e2e.test.ts
src/test/e2e/services/api-token-service.e2e.test.ts
src/test/e2e/services/project-service.e2e.test.ts
src/test/fixtures/fake-project-store.ts

- Fixes project model/store
- Fixes UI sync issues when switching stickiness 
Closes #

fix: stickiness

---

frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureDeleteConfirm/ArchivedFeatureDeleteConfirm.tsx
frontend/src/hooks/api/actions/useProjectApi/useProjectApi.ts

Allow deleting with BULK_UPDATE flag turned off

fix: bulk update delete flag

---

website/docs/reference/sdks/index.md

Update to Python compatibility table. 
* Impression events supported in v5.6.0.  ([Docs](https://docs.getunleash.io/unleash-client-python/eventcallbacks.html))
* Bootstrapping from files and custom boostrapping has been supported since v5.2.0. ([Docs](https://docs.getunleash.io/unleash-client-python/filecache.html) & [Docs](https://docs.getunleash.io/unleash-client-python/customcache.html))
Closes #

Update Python SDK compatibility.

---

frontend/src/component/feedback/FeedbackNPS/FeedbackNPS.tsx
frontend/src/themes/themeStyles.ts

https://linear.app/unleash/issue/1-821/after-creating-a-new-toggle-we-get-this-error-in-dev

fix: media query issue in feedback modal

---

src/lib/openapi/index.ts
src/lib/openapi/spec/toggle-maintenance-schema.ts
src/lib/routes/admin-api/maintenance.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Cleaning maintenance mode schema: 
* added separate error messages for read and write models
* added example values
* added summary and descriptions 
* split read and write schemas because one should be strict, the other lenient

Maintenance openapi

---

src/lib/routes/admin-api/email.ts

This was an oversight of https://github.com/Unleash/unleash/pull/3402

fix: security vulnerability

---

src/lib/app.ts
src/lib/middleware/catch-all-error-handler.ts
src/lib/middleware/debug-error-handler.ts
src/lib/routes/util.ts

All errors that didn't get to express routes and their own error handling (e.g. client closing connection before request is dispatched) will be handled by this catch all handler at the very end of all middleware handlers. It will log everything using normal logger at the warn level. Previously it was logged to stderr by a default express error handling mechanism.
Added BadRequestError to our list of recognized errors. BadRequestError is the error we get from raw body parser when client closes connection in the middle of POST body sending.

Catch all error handler

---

src/migrations/20230412062635-add-change-request-title.js

Adding support for custom change request title

feat: change request title migration

---

src/lib/openapi/spec/constraint-schema.ts
src/lib/openapi/spec/segment-schema.ts
src/lib/openapi/spec/upsert-segment-schema.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Add additional documentation for segments

docs: open api examples for segment schemas

---

website/docs/reference/api-tokens-and-client-keys.mdx

[Previous PR (has the comments)](https://github.com/Unleash/unleash/pull/3405)
Closes #

fix: project api token docs

---

frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequestTitle.test.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequestTitle.tsx
frontend/src/component/changeRequest/changeRequest.types.ts
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts
frontend/src/utils/testServer.ts

feat: CR title from review page

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestHeader/ChangeRequestHeader.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/ChangeRequestTitle.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequestTitle.test.tsx

feat: cr overview title

---

src/lib/middleware/catch-all-error-handler.ts

Express.js error handler needs 4 params

fix: 4 param error handler

---

src/lib/openapi/meta-schema-rules.test.ts

This rule defines that all properties should have a description
We also considered enforcing an example but we noticed that in some cases that's not needed.

chore: rule for description on properties

---

frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/AvatarCell.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestStatusCell.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestTitleCell.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/FeaturesCell.tsx

feat: list affected features

---

src/lib/openapi/spec/feature-tag-schema.ts
src/lib/openapi/spec/tag-schema.ts
src/lib/openapi/spec/update-tags-schema.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Amends based on https://github.com/Unleash/unleash/pull/3519

docs: improve open api

---

.github/workflows/build_coverage.yaml
.github/workflows/update_contributors.yaml

These also need to be migrated to node 18

fix: gh actions that run on main

---

.github/workflows/release.yaml
frontend/package.json
package.json

Updates frontend engine minimum version to node 18 and also improves some messages in the release GHA task

fix: missing node engine upgrade to 18

---

src/migrations/20230412125618-add-title-to-strategy.js

Fixes `down` migration  for add_title_to_strategy
Closes #

fix: migration

---

src/lib/db/event-store.ts

Reduce compilation errors on event-store

fix: compilation issues from event-store

---

website/docs/reference/api/legacy/unleash/admin/state.md
website/docs/reference/deploy/import-export.md

Update documentation about the deprecation of state API.
Related to https://github.com/Unleash/unleash/issues/1265

docs: deprecation notice on state api

---

website/docs/reference/api/legacy/unleash/admin/state.md
website/docs/reference/deploy/import-export.md

Add correct link to new import/export

doc: update link to new import/export

---

src/migrations/20230419104126-add-disabled-field-to-feature-strategy.js
src/migrations/20230420125500-v5-strategy-changes.js

fixes migration syntax bugs
Closes #

fix: update migration bugs

---

frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestTitleCell.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx

Search change request list by title.

feat: search cr by title

---

.github/workflows/e2e.frontend.yaml
frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureDeleteConfirm/ArchivedFeatureDeleteConfirm.tsx
frontend/src/hooks/api/actions/useProjectApi/useProjectApi.ts

chore: patch 4.22.7

---

src/migrations/20230420211308-update-context-fields-add-sessionId.js

fix: migration failure when sessionId exists

---

src/migrations/20230420211308-update-context-fields-add-sessionId.js

Back-porting the migration fix
Closes #
Closes #

fix: migration failure when sessionId exists (#3624)

---

package.json

5.0.0-beta.0

---

.mergify.yml

Enable mergify to auto update PRs

chore: mergify

---

src/lib/db/feature-tag-store.ts
src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts
src/lib/openapi/spec/export-query-schema.ts
src/lib/services/feature-tag-service.ts
src/lib/types/stores/feature-tag-store.ts
src/lib/types/stores/tag-type-store.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
src/test/fixtures/fake-feature-tag-store.ts

Export environment toggle config by tags. This will be needed for promote feature toggles script.
* currently tags take precedence over feature list
* removed some typechecker error in the export-import-service

feat: export by tags

---

scripts/promote.sh
src/lib/features/export-import-toggles/import-toggles-store.ts

Added first version of the promote feature toggles script + fixed one query that was failing on empty toggles list

feat: promote toggles script

---

website/docs/how-to/how-to-synchronize-unleash-instances.md

Documenting how to synchronize Unleash instances

docs: unleash instance synchronization

---

website/docs/how-to/how-to-add-sso-google.md

Updates docs to point out that Google SSO is removed and how to temporarily bring it back

docs: update docs to reflect that google SSO is removed

---

website/docs/reference/deploy/getting-started.md
website/package.json

Update documentation to the minimum version of node. This was already updated in other parts of the documentation

docs: update to node 18

---

src/lib/features/export-import-toggles/export-import-service.ts
src/lib/features/export-import-toggles/export-import.e2e.test.ts

fix: import tags

---

frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCard.tsx
frontend/src/component/archive/ArchiveTable/ArchiveTable.tsx
frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureDeleteConfirm/ArchivedFeatureDeleteConfirm.tsx
frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ChangeActions.tsx
frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestTitleCell.tsx
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsChart/createChartData.ts
frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsChart/createChartOptions.tsx
frontend/src/interfaces/featureToggle.ts

feat: add UI to variant metrics

---

src/lib/services/feature-toggle-service.ts

fix: Add default value for shouldActivateDisabledStrategies

---

src/lib/db/api-token-store.ts
src/lib/routes/admin-api/project/api-token.ts
src/test/e2e/api/admin/project/api-token.e2e.test.ts

fix: project api token type to lowercase

---

frontend/src/component/demo/demo-topics.tsx

https://linear.app/unleash/issue/2-1008/steps-improvement-adjust-variants
Step improvements for the "variants" topic.

fix: improve steps for demo guide variants topic

---

src/lib/services/feature-toggle-service.ts
src/test/e2e/api/admin/project/features.e2e.test.ts

fix: bypass change requests when unprotected deleting

---

frontend/src/component/demo/DemoSteps/DemoStepTooltip/DemoStepTooltip.tsx
frontend/src/component/demo/demo-topics.tsx

https://linear.app/unleash/issue/2-1006/steps-improvement-enabledisable-a-feature-toggle
Step improvements for the "toggle" topic.
Includes a smarter "Next" label that can also be "Start" or "Finish" depending (nice-to-have).

fix: improve steps for demo guide toggle topic

---

src/lib/db/api-token-store.ts
src/lib/routes/admin-api/project/api-token.ts
src/test/e2e/api/admin/project/api-token.e2e.test.ts

Cherry picks the change transforming the token type to lowercase
Closes #

fix:  project tokens type bug fix

---

website/docs/contributing/ADRs/back-end/breaking-db-changes.md

Fix typo in ADR

---

src/lib/db/api-token-store.ts
src/lib/routes/admin-api/project/api-token.ts
src/test/e2e/api/admin/project/api-token.e2e.test.ts

chore: Tmp 5.0.5

---

Dockerfile

This adapts the docker creation to the latest package.json changes https://github.com/Unleash/unleash/pull/3736

fix: use new build process

---

.github/workflows/release.yaml

Another piece requiring changes, which adapts to: https://github.com/Unleash/unleash/pull/3736

fix: update GH action

---

frontend/src/component/demo/demo-topics.tsx

Fixes an issue where the userId screenshot did not load correctly.

fix: demo userId screenshot path

---

.github/workflows/gradual-strict-null-checks.yml
src/lib/segments/segment-service-interface.ts

These methods are being used externally as part of our enterprise package

chore: add additional methods we want exposed

---

frontend/src/component/feature/FeatureToggleList/BulkDisableDialog.tsx
frontend/src/component/feature/FeatureToggleList/BulkEnableDialog.tsx
frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts

* bulk enable and disable choose between regular mode and change request mode
* added toasts
Next PRs:
* add info text which mode you're in
* add tests

feat: bulk enable disable change requests

---

frontend/src/component/feature/FeatureToggleList/BulkDisableDialog.tsx
frontend/src/component/feature/FeatureToggleList/BulkEnableDialog.tsx

Bulk enable/disable hints:
* change request enabled hints
* how many features already enabled/disabled hint

Bulk enable hints

---

frontend/src/component/feature/FeatureToggleList/BulkDisableDialog.test.tsx
frontend/src/component/feature/FeatureToggleList/BulkDisableDialog.tsx
frontend/src/component/feature/FeatureToggleList/BulkEnableDialog.test.tsx
frontend/src/component/feature/FeatureToggleList/BulkEnableDialog.tsx

Testing display of bulk enable/disable dialogs with all corner cases
Next PR:
* testing clicking a button

test:  bulk enable display

---

frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/ProjectDefaultStrategyForm.tsx

fix: Move title at the top in default strategy

---

frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/FeatureToggleSwitch.tsx

Fixes laggy environment switch
Stabilising the functions with useCallback seems necessary in the table view
Changed the `checked` property to be dependent on `isChecked` which wraps the value in useOptimisticUpdate hook made the most difference 
Closes #(1-942)[https://linear.app/unleash/issue/1-942/bug-laggy-environment-toggles-in-the-ui]

fix: laggy switch

---

frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/FeatureToggleSwitch.tsx

Revert "fix: laggy switch"

---

.github/workflows/notify_enterprise.yaml

Use the right author name as tested here https://github.com/Unleash/unleash/actions/runs/5056589150/jobs/9074236865#step:6:833

fix: Use the correct actor

---

frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/EditDefaultStrategy.tsx

Fixes a bug where default strategy would not edit 
Closes # 1-953

fix: default strategy screen not loading when no default strategy

---

.github/workflows/notify_enterprise.yaml

Adopt the new workflow name: https://github.com/ivarconr/unleash-enterprise/pull/529

fix: new workflow name

---

src/lib/routes/admin-api/project/project-features.ts
src/lib/services/feature-toggle-service.ts
src/lib/services/scheduler-service.test.ts
src/test/e2e/api/client/segment.e2e.test.ts

Fixing problem that manifested in change requests application but the root cause was in the toggle controller:
* moving application logic to a service from a controller since it's easier to reuse from a service
* adding transaction boundaries around update of strategies so that strategy change and disabling of the toggle either both succeed of both fail but never leave the system in the inconsistent state

fix: move application logic to service

---

.github/workflows/release.yaml

This script was moved, updating the ref

fix: workflow was moved

---

src/lib/services/maintenance-service.test.ts
website/docs/reference/maintenance-mode.mdx

* describe maintanance mode impact on schedulers and read-only DB users
* added missing test for the maintenance service

docs: maintanance mode impact

---

website/docs/about-the-docs.md

They've been thoroughly restructured now. It's time to let this
admonition go 🕊️

docs: remove "docs under restructuring note"

---

frontend/src/component/common/ResponsiveButton/ResponsiveButton.tsx
frontend/src/component/demo/Demo.tsx
frontend/src/component/demo/DemoBanner/DemoBanner.tsx
frontend/src/component/demo/DemoDialog/DemoDialog.tsx
frontend/src/component/demo/DemoDialog/DemoDialogPlans/DemoDialogPlans.tsx
frontend/src/component/menu/Header/DrawerMenu/DrawerMenu.tsx
frontend/src/component/menu/Header/Header.tsx
frontend/src/themes/dark-theme.ts
frontend/src/themes/theme.ts

Includes:
- https://linear.app/unleash/issue/2-1050/ui-fixes
- https://linear.app/unleash/issue/2-1088/mobile-ui
- https://linear.app/unleash/issue/2-1090/tablet-table
Which include things like:
- zIndex adjustments;
- Make the plans dialog more responsive;
- Hide interactive demo guide on small screens;
- Improve demo banner responsiveness;
- Fix console error on `ResponsiveButton`;
- Adjust sidebar header to be more consistent;
Co-authored-by @nicolaesocaciu

fix: misc UI fixes mostly responsiveness related

---

src/lib/app.ts
src/test/e2e/api/auth/leading-slashes-are-stripped.e2e.test.ts

fix: remove consecutive slashes

---

.github/workflows/notify_enterprise.yaml
.github/workflows/release.yaml

Previous PR https://github.com/Unleash/unleash/pull/3871 we were supposed to change this for PRs but the change was made on `release.yaml` file. This fixes the issue

fix: author and email should be for PRs

---

frontend/src/component/user/PasswordAuth.tsx

Please note that modern web browsers may ignore this directive (to encourage the usage of password managers). In spite of this there is a chance that
not disabling autocomplete may cause problems obtaining PCI compliance.

feat: autocomplete off on login password

---

frontend/src/component/user/Profile/PasswordTab/PasswordTab.test.tsx
frontend/src/component/user/Profile/PasswordTab/PasswordTab.tsx
frontend/src/hooks/api/actions/usePasswordApi/usePasswordApi.ts
frontend/src/utils/testServer.ts
src/lib/openapi/spec/password-schema.ts
src/lib/routes/admin-api/user/user.test.ts
src/lib/routes/admin-api/user/user.ts
src/lib/services/user-service.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

When changing your own password you should specify the old password. I decided to place old password field above the new one.
Show new password error:
Show old password error:

feat: change own password confirmation

---

frontend/src/hooks/api/getters/useConstraintsValidation/useConstraintsValidation.ts

Fixes over-validating constraint
Closes #  [1-949](https://linear.app/unleash/issue/1-949/fix-overvalidating-constraint)

fix: remove unneseccary constraint validation request

---

src/lib/util/generateObjectCombinations.test.ts
src/lib/util/generateObjectCombinations.ts

Generate object combinations (cartesian product):
```
const obj = {
sessionId: '1,2',
appName: 'a,b,c',
channels: 'internet',
};
const expectedCombinations = [
{ sessionId: '1', appName: 'a', channels: 'internet' },
{ sessionId: '1', appName: 'b', channels: 'internet' },
{ sessionId: '1', appName: 'c', channels: 'internet' },
{ sessionId: '2', appName: 'a', channels: 'internet' },
{ sessionId: '2', appName: 'b', channels: 'internet' },
{ sessionId: '2', appName: 'c', channels: 'internet' },
];
```
This will be used by playground multivalues

feat: generate object combinations

---

frontend/src/component/context/ContextFieldUsage/ContextFieldUsage.test.tsx
frontend/src/component/context/ContextFieldUsage/ContextFieldUsage.tsx
frontend/src/component/context/ContextForm/ContextForm.tsx
frontend/src/hooks/api/getters/useStrategiesByContext/useStrategiesByContext.ts
src/lib/db/context-field-store.ts
src/lib/db/segment-store.ts

feat: context field usage frontend

---

website/sidebars.js

Added sidebar link to unleash synchronizations. Added to the toggles, strategies, context section since we're synchronizing those items in particular.

docs: how to synchronize unleash instances

---

src/lib/openapi/meta-schema-rules.test.ts
src/lib/openapi/spec/advanced-playground-request-schema.ts
src/lib/openapi/spec/playground-request-schema.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Our meta rules checker will only verify description is present when the field is not a ref based field which has its own description.
This change automatically fixes a few schemas.

test: meta schema rules should not check description on ref

---

frontend/src/component/changeRequest/ChangeRequestPermissions.test.tsx
frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentTable.tsx

* adding environment playground table (most columns are dynamic based on context fields)
Next PRs:
* unit test
* adding a modal around the table
* connecting to the advanced results table

feat:playground environment table

---

src/lib/db/environment-store.ts
src/lib/types/stores/environment-store.ts
src/test/fixtures/fake-environment-store.ts

Co-authored-by: Tymoteusz Czech <2625371+Tymek@users.noreply.github.com>

feat: add max order to environments

---

frontend/src/component/changeRequest/ChangeRequest/Changes/Change/EditChange.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCard/FeatureStrategyMenuCard.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx

feat: strategy tooltip grouping and default

---

frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx

Fix loading column IDs for Project Features table
Closes [#1-995/project-overview-ui-bug](https://linear.app/unleash/issue/1-995/project-overview-ui-bug)

fix: column initial state for project features

---

frontend/src/component/common/Table/VirtualizedTable/VirtualizedTable.tsx
frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundEnvironmentCell/AdvancedPlaygroundEnvironmentCell.tsx
frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentTable.tsx
frontend/src/component/playground/Playground/playground.utils.ts
frontend/src/hooks/useVirtualizedRange.ts

* virtualized table works with explicit parent ref now
* we default to window if parent ref is not provided
* using new capability in the new playground
* tested feature toggle list if it still works and also tested new playground results in a popover

Virtualized table with parent ref

---

frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingPlan.tsx
frontend/src/component/common/InstanceStatus/InstanceStatus.tsx
frontend/src/component/common/InstanceStatus/InstanceStatusBar.test.tsx
frontend/src/component/common/InstanceStatus/__snapshots__/InstanceStatusBar.test.tsx.snap
frontend/src/interfaces/instance.ts

Adds the trial expired warning for enterprise as well.

fix: add trial expired warning for enterprise

---

frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
frontend/src/hooks/useChangeRequestsEnabled.ts

Roles with skip change request should still be able to review (approve/apply/comment) on change requests.

fix: can review CR with skip change request

---

frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentTable.test.tsx

Verifying that correct data is displayed in the playground environment table

test: playground env table display

---

website/docs/reference/sdks/index.md

List of community unleash proxy clients extended with new Angular library
Relates to [discussion](https://github.com/orgs/Unleash/discussions/3621)

docs: angular unleash proxy client

---

frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.tsx

feat: change CR strategy title and name behaviour

---

frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundResultsTable.test.tsx

Adds a frontend test for AdvancedPlaygroundResultsTable
Closes #

chore: Add advanced playground table test

---

frontend/src/component/admin/roles/Roles.tsx
frontend/src/component/admin/roles/RolesTable/RolesTable.tsx

https://linear.app/unleash/issue/2-1145/improve-roles-sub-tabs
Improves UI/UX of the roles sub-tabs.
Some of the logic is a bit specific due to the feature flag, will be nice to clean this up once we remove it.
Before:
After:

feat: implement better roles sub-tabs

---

frontend/src/component/playground/Playground/LazyPlayground.tsx

fix: playground link

---

frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundResultsTable.test.tsx
frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundResultsTable.tsx
frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentDiffTable.test.tsx

* Testing environment diff table
* Including diff table link only when more than 1 environment

test: environment diff

---

website/docs/how-to/how-to-synchronize-unleash-instances.md

Feedback request in sync toggles docs

docs: encourage feedback for sync

---

frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundConnectionFieldset/PlaygroundConnectionFieldset.tsx

Fixes a bug with the multiple env select breaking playground
Closes #

Fix multiple env select

---

frontend/src/component/playground/Playground/AdvancedPlayground.test.tsx
frontend/src/component/playground/Playground/AdvancedPlayground.tsx
frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentDiffTable.test.tsx

* load initial advanced playground form data either from local storage or URL. Non empty query params in URL take precedence
* added ability to inject testable PlaygroundForm because the original form is using CodeMirror that is giving errors in tests (https://github.com/codemirror/dev/issues/608)

feat: store playground settings in local storage

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/create-config.ts
src/server-dev.ts
src/test/config/test-config.ts

Enable open api by default for everyone.
Next steps: 
* remove enableOas option from enterprise 
* remove enableOas option in OSS (after enterprise)

feat: enable oas by default

---

frontend/src/component/playground/Playground/Playground.tsx

Env array was causing infinite re-render

fix: infinite playground rendering

---

frontend/src/hooks/useVirtualizedRange.ts

I found an issue where a virtual list is nested inside another virtual list the nested one didn't render anything for below the fold/lazy elements from the parent list unless we scrolled inside the child list. This change triggers initial scroll when a component is loaded.

feat: initial scroll trigger

---

frontend/src/component/common/InstanceStatus/InstanceStatus.tsx
frontend/src/component/menu/routes.ts
frontend/src/component/project/Project/ProjectOverview.tsx
frontend/src/component/segments/SegmentFormStepOne.tsx

Misc cleanups of unused imports / variables.

refactor: misc cleanups

---

src/lib/features/playground/playground-service.ts
src/lib/features/playground/playground.ts
src/lib/features/playground/validateQueryComplexity.ts

Make playground evaluation limit configurable through variants so that we can experiment easily with different values.

feat: configurable playground limit

---

frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundCodeFieldset/PlaygroundCodeFieldset.tsx
frontend/src/component/playground/Playground/playground.utils.ts

Makes the autocomplete component in the playground context field - when selecting a custom context field that has legal values - able to select/edit multiple values.
Closes # [1-1006](https://linear.app/unleash/issue/1-1006/multi-value-context-field)

feat: advanced playground multi value context fields

---

frontend/src/component/playground/Playground/AdvancedPlayground.tsx
src/lib/features/playground/validateQueryComplexity.ts

2 tweaks:
* error banner dissapears when you re-submit the evaluation, previously it was stying there too long
* error banner informs about actual number of combinations exceeding limit, previously it was same number (the actual combinations) listed twice

feat: ui tweaks for playground

---

frontend/src/component/playground/Playground/AdvancedPlayground.tsx

fix: multi env select should always have an environment selected

---

frontend/src/component/playground/Playground/AdvancedPlaygroundResultsTable/AdvancedPlaygroundResultsTable.tsx
frontend/src/component/playground/Playground/PlaygroundEnvironmentTable/PlaygroundEnvironmentDiffTable.tsx
frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureStatusCell/FeatureStatusCell.tsx

Each environment in the diff table has info icon with the execution plan
This component is already tested and since we're not adding any if statements I am not adding new tests.

feat: execution plan diff table

---

frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundCodeFieldset/PlaygroundCodeFieldset.tsx

Sets a maxHeight property for add/replace button in playground 
Closes #

fix: set max height for add/replace button

---

frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx

fix: break toggle description niceley

---

frontend/src/component/common/RoleSelect/RoleSelect2.tsx
frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx

fix: allow roles to be selected when adding user to project

---

website/docs/reference/sdks/index.md

Included a library from the ColdBox Open Source team.
More detail here if needed.
https://forgebox.io/view/unleashsdk
I cheated on the grammar. Grammarly helps me out there.
Closes #

Update index.md, 2 grammar updates

---

frontend/src/component/project/Project/Project.tsx

If project doesn't exist, show 404 information.
Closes [issue/1-1069](https://linear.app/unleash/issue/1-1069/project-doesnt-show-404-if-it-doesnt-exist)

fix: project 404

---

frontend/src/component/playground/Playground/AdvancedPlayground.tsx
frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundCodeFieldset/PlaygroundCodeFieldset.tsx
frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundCodeFieldset/PlaygroundEditor/PlaygroundEditor.tsx
frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundConnectionFieldset/PlaygroundConnectionFieldset.tsx
frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundForm.tsx
frontend/src/component/playground/Playground/PlaygroundForm/renderOption.tsx

Final overview with the adjusted spacing and multi select fields
Detailed adjustments below
Left align results table and the form:
Allow 3 pills and then +1/n indicator
Align environments and context fields length
Placeholder for multiple values
Persistent multi selection for projects
Persistent multi selection for environments
Old playground is still usable but we optimize UI for the new playground

feat: advanced playground UI tweaks

---

frontend/src/component/common/Table/cells/LinkCell/LinkCell.tsx
frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx

feat: hovering over feature shows full feature name

---

.github/workflows/notify_enterprise.yaml

Debug information to get the best way of fetching the commit author and use that to trigger a workflow

chore: Add debug information

---

src/lib/db/feature-toggle-client-store.ts

This removes the burden of knowing what optionalIncludes is and also
prevents weird edge cases like isAdmin with optionalIncludes.

refactor: use `requestType` instead of `isAdmin`, `optionalIncludes`

---

.github/workflows/notify_enterprise.yaml
src/lib/util/is-email.ts

This should address: https://github.com/Unleash/unleash/security/code-scanning/1, https://github.com/Unleash/unleash/security/code-scanning/49 and https://github.com/Unleash/unleash/security/code-scanning/52
Refs:
- https://securitylab.github.com/research/github-actions-untrusted-input/
- https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS
- https://datatracker.ietf.org/doc/html/rfc5321#section-4.5.3.1.1

fix: some security vulnerabilities

---

frontend/src/component/admin/groups/GroupForm/GroupForm.tsx
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts

This is going GA. So does what it says on the tin

chore: remove group root role toggle

---

docker/yarn.lock

fix: update yarn.lock

---

frontend/src/component/playground/Playground/AdvancedPlayground.tsx
frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundForm.tsx

Fixes initial environment selection in playground
Details:
* the hook that sets the actual environment selection was not checking if backend returned available environments for selection

fix: initial playground env

---

frontend/src/component/playground/Playground/AdvancedPlayground.tsx

When the error is present no results are rendered (previously we rendered old results).

feat: no results on playground error

---

src/lib/openapi/util/openapi-tags.ts

Tiny  PR to update the admin UI tag description, including a disclaimer that it may change at any time.

openapi: update tag description

---

frontend/src/hooks/api/getters/useConstraintsValidation/useConstraintsValidation.test.tsx
frontend/src/hooks/api/getters/useConstraintsValidation/useConstraintsValidation.ts

Fixing regression introduced by https://github.com/Unleash/unleash/pull/3914.
We were not disabling save strategy or add to change request button on invalid constraints because we were filtering out invalid values locally in the frontend and excluding them from checking.
This PR fixes the regression and also introduces unit tests describing the new behavior.

fix: constraint validation affecting disabled button

---

src/lib/routes/admin-api/favorites.ts
src/test/e2e/api/admin/favorites.e2e.test.ts

Adds description and summary to `favorite` endpoints
Closes # [1-1098](https://linear.app/unleash/issue/1-1098/openapi-features-favorites)

chore: openapai favorite endpoints

---

website/docs/reference/sdks/index.md

A very small change flagging impression events as supported in the Java SDK

docs: add impression events as supported in the java sdk

---

src/lib/openapi/spec/constraint-schema.ts

Prior to introducing minItems constraint some toggles were created that break this constraint. When we do batch import we get an error from schema validation.
minItems values constraint was introduced to prevent invalid constraints creation in a single item mode. When we do batch import mode it difficult to clean up all the items.

fix: min items was breaking import

---

frontend/src/component/common/Input/Input.tsx
frontend/src/component/project/Project/CreateProject/CreateProject.tsx
frontend/src/component/project/Project/EditProject/EditProject.tsx
frontend/src/component/project/Project/ProjectForm/FeatureTogglesLimitTooltip.tsx
frontend/src/component/project/Project/ProjectForm/ProjectForm.tsx
frontend/src/component/project/Project/ProjectSettings/Settings/EditProject.tsx
frontend/src/component/project/Project/hooks/useProjectForm.ts

feat: project feature limit UI

---

src/lib/db/feature-toggle-client-store.ts

Feature strategies will be sorted in client features. This is required for the new variant strategies where the order of strategies matters for the variant that will be selected.
Client toggles cache is updated on event log change. We need to add re-ordering event for the re-order to trigger changes.
I'm wondering if this change could be behind a flag.

feat: sort feature strategies

---

src/lib/services/feature-toggle-service.ts
src/test/e2e/api/admin/project/variants.e2e.test.ts

Fix un-awaited promise on batch variant update - reduce function allowed TS to skip Promise type.

Fix: variants-batch

---

src/lib/addons/__snapshots__/datadog.test.ts.snap
src/lib/addons/__snapshots__/slack.test.ts.snap
src/lib/addons/__snapshots__/teams.test.ts.snap
src/lib/addons/datadog-definition.ts
src/lib/addons/datadog.test.ts
src/lib/addons/datadog.ts
src/lib/addons/slack-definition.ts
src/lib/addons/slack.test.ts
src/lib/addons/slack.ts
src/lib/addons/teams-definition.ts
src/lib/addons/teams.test.ts
src/lib/addons/teams.ts
src/lib/addons/webhook-definition.ts
src/lib/addons/webhook.test.ts
src/lib/addons/webhook.ts
src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap

Early release of https://github.com/Unleash/unleash/pull/4139 and https://github.com/Unleash/unleash/pull/4196 as 5.2 patch

chore: prepare 5.2 patch

---

src/migrations/20230712091834-strategy-variants.js

Adding variants JSONB column to strategies that will allow subsequent PRs introduce support for the strategy variants. 
It's less than 10 LOC, most of the code is the old view definition with a new line added.
More comments inline.

feat: strategy variant migrations

---

src/lib/db/feature-toggle-client-store.ts
src/lib/db/index.ts
src/lib/db/segment-store.ts
src/lib/features/feature-toggle/createFeatureToggleService.ts
src/lib/openapi/index.ts
src/lib/openapi/spec/client-features-schema.test.ts
src/lib/openapi/spec/client-features-schema.ts
src/lib/openapi/spec/client-segment-schema.ts
src/lib/openapi/spec/index.ts
src/lib/openapi/spec/segment-schema.ts
src/lib/routes/client-api/feature.test.ts
src/lib/routes/client-api/feature.ts
src/lib/segments/segment-service-interface.ts
src/lib/services/segment-service.ts
src/lib/types/model.ts
src/lib/types/stores/segment-store.ts
src/test/fixtures/fake-segment-store.ts

* Added strategy variants to client API - behind a flag
* Fixing client segments to include only id, constraints and name (optional but I left if for now to ease debugging and we were returning it anyway)

feat: client api with proper client segments and strategy variants

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyEdit/FeatureStrategyEdit.tsx
frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/EnvironmentVariantsModal.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx
frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.tsx
frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx
frontend/src/interfaces/featureToggle.ts
frontend/src/interfaces/strategy.ts

Spike for the strategy variants
The main file will be reworked from scratch and tests with unit tests. I'm adding it for demoing purposes behind a flag.

feat: strategy variant UI spike

---

frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/EnvironmentVariantsModal.tsx
frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantForm.tsx
frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx

VariantForm was coupled to feature variant API payload. This level of coupling is not necessary since we only need the information if there was some error outside of the component. This refactoring reduces coupling between the VariantForm and it's parent component. After this change VariantForm can be used for strategy variants without creating artificial API payload.

refactor: error param prop

---

src/lib/db/feature-type-store.ts
src/lib/types/stores/feature-type-store.ts
src/test/e2e/stores/feature-type-store.e2e.test.ts
src/test/fixtures/fake-feature-type-store.ts

This PR updates the feature type store to allow for lifetime updates, laying the foundation required to make it user-configurable (#4205).

feat(#4205): modify feature type store to allow lifetime updates

---

frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx

When parent is changing stickiness it should be reflected in strategy variants

fix: reactive stickiness strategy variants

---

src/lib/services/feature-toggle-service.ts

Fixes a bug around createStrategy
Fix: Create/Store strategy reorder event only when feature is on
Closes #

fix: unwrap create strategy event creation (bug)

---

src/lib/services/feature-toggle-service.ts

wrap reorder event creation to strategy variant feature
Closes #

Fix: wrap reorder event to strategy variant feature

---

frontend/src/component/featureTypes/FeatureTypeForm/FeatureTypeForm.tsx
frontend/src/component/featureTypes/FeatureTypesList.tsx
frontend/src/component/menu/Header/Header.tsx
frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
frontend/src/component/menu/routes.ts

Task: https://linear.app/unleash/issue/1-1127/add-front-end
frontend/src/component/featureTypes/FeatureTypeForm/FeatureTypeForm.tsx
**`FIXME`** will be addressed when integrating with API

feat: Feature toggle type - edit form

---

frontend/src/component/common/NotFound/NotFound.tsx
frontend/src/component/featureTypes/FeatureTypeEdit/FeatureTypeEdit.tsx
frontend/src/component/featureTypes/FeatureTypeEdit/FeatureTypeForm/FeatureTypeForm.test.tsx
frontend/src/component/featureTypes/FeatureTypeEdit/FeatureTypeForm/FeatureTypeForm.tsx
frontend/src/component/featureTypes/FeatureTypeForm/FeatureTypeForm.tsx
frontend/src/component/featureTypes/FeatureTypesList.tsx
frontend/src/hooks/api/actions/useFeatureTypeApi/useFeatureTypeApi.ts
frontend/src/hooks/usePlausibleTracker.ts
frontend/src/utils/sortTypes.test.ts
frontend/src/utils/sortTypes.ts

feat: Feature type lifetime API integration

---

src/lib/db/group-store.ts
src/lib/features/group/createGroupService.ts
src/lib/openapi/index.ts
src/lib/openapi/spec/create-group-schema.ts
src/lib/openapi/spec/group-schema.ts
src/lib/openapi/spec/index.ts
src/lib/services/group-service.ts
src/lib/services/index.ts
src/lib/types/group.ts
src/lib/types/services.ts
src/lib/types/stores/group-store.ts
src/test/e2e/services/group-service.e2e.test.ts
src/test/fixtures/fake-group-store.ts

* Group API cleanup triggered by the OpenAPI improvements
* Replacing 500 errors with 400 errors when foreign key violations happen (no role, no user)
* Separating write/create model and read model for groups
* Removing transaction boundaries from the store to the controller in group-controller to have the same pattern across the entire codebase and possibly span multiple stores

fix: group cleanup

---

src/lib/openapi/spec/role-schema.ts

We have 'root' role, not 'global' role.

fix: global role is called root role

---

frontend/src/component/common/NotFound/NotFound.tsx

Fix 404 error page UI in dark theme
https://linear.app/unleash/issue/1-1145/ui-404-error-in-dark-mode-can-fail-to-show-text

fix: 404 in dark theme

---

frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/FeatureStrategyCreate.tsx
frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.tsx
frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/EditDefaultStrategy.tsx

Default strategy should get default stickiness from the project settings not from a hardcoded const. 
Create a custom hook that returns default stickiness, fallback and a way to refresh it.
Will add a test in the next PR.

fix: default strategy stickiness

---

src/lib/features/playground/generateObjectCombinations.test.ts
src/lib/features/playground/generateObjectCombinations.ts

Do not try to split non string values

fix: do not split non string values

---

src/lib/features/playground/advanced-playground.test.ts

Test selected variant and list of variants match. E.g. disabled variant should not have variants list available.

test: matching variants

---

src/lib/openapi/meta-schema-rules.test.ts
src/lib/openapi/spec/__snapshots__/sort-order-schema.test.ts.snap
src/lib/openapi/spec/feature-strategy-segment-schema.ts
src/lib/openapi/spec/group-schema.ts
src/lib/openapi/spec/maintenance-schema.ts
src/lib/openapi/spec/playground-segment-schema.ts
src/lib/openapi/spec/playground-strategy-schema.ts
src/lib/openapi/spec/project-overview-schema.ts
src/lib/openapi/spec/project-schema.ts
src/lib/openapi/spec/projects-schema.ts
src/lib/openapi/spec/push-variants-schema.ts
src/lib/openapi/spec/reset-password-schema.ts
src/lib/openapi/spec/sdk-context-schema.ts
src/lib/openapi/spec/sort-order-schema.ts
src/lib/openapi/spec/state-schema.ts
src/lib/openapi/spec/toggle-maintenance-schema.ts
src/lib/openapi/spec/upsert-context-field-schema.ts
src/lib/openapi/spec/users-groups-base-schema.ts
src/lib/openapi/spec/users-search-schema.ts
src/lib/openapi/spec/variants-schema.ts
src/lib/routes/admin-api/maintenance.ts

This PR fixes additional schemas that hadn't been described properly

OpenAPI: more schema cleanup

---

frontend/src/component/common/StrategyVariantsUpgradeAlert/StrategyVariantsUpgradeAlert.tsx
frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx

Static strategy variants SDK upgrade alert. 
I'm thinking whether we should do SDK version detection in the backend and return this warning conditionally.

feat: strategy variants alert

---

src/lib/__snapshots__/create-config.test.ts.snap
src/lib/services/feature-toggle-service.ts
src/lib/types/experimental.ts

We were explicitly picking what fields to show in the client API behind a flag. Since this flag has been tested in prod for a long time we can remove it now.

chore: clean client api flag removed

---

website/docs/reference/archived-toggles.md

remove trailing periods

---

website/docs/reference/feature-strategy-variants.md

Advertising strategy variants available from 5.4

docs: strategy variants in 5.4

---

src/lib/addons/slack-app.ts

Logs to help us debug the addon

chore: Add debug information to slack addon

---

src/lib/addons/slack-app.ts

This add more debug logs to help us trace how channels are being filtered out

chore: add more debug logs

---

frontend/src/component/menu/Header/Header.tsx
frontend/src/component/menu/Header/NavigationMenu/NavigationMenu.tsx
frontend/src/component/menu/routes.ts
frontend/src/interfaces/route.ts
frontend/src/interfaces/uiConfig.ts
src/lib/__snapshots__/create-config.test.ts.snap
src/lib/types/experimental.ts
src/server-dev.ts

- add divider
- reorder items
- add flag for project https://linear.app/unleash/project/[high][s][none]-improved-menu-aefaca264034
Closes https://linear.app/unleash/issue/1-1101/improved-menu-enterprise

Update admin menu
