Unleash/unleash

- frontend/src/component/project/NewProjectCard/ProjectOwners/ProjectOwners.tsx
Truncate long project owner names. Had to add minWidth other than auto on the flex item that contains the avatar and the project name so that it doesn't grow outside of the parent. Previously the ellipsis had no effect.
> fix: project owner name overflow

- src/lib/features/feature-toggle/feature-toggle-service.ts
- src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts
> fix: enable disabled strategies keeps settings

- src/migrations/20240821141555-segment-no-project-cleanup.js
Fixes issue where `segment-created `events had fake project name **no-project** attached.
In total for previous 4 months, all segments created that were global segments, have this issue.
https://github.com/Unleash/unleash/pull/6872/files#diff-68dcd43b31d35a8a80c73bca1f2a9626b0234dd0b76920a6881b81fa04708268R135
> fix: fix events with no-project projects

- src/lib/openapi/spec/instance-admin-stats-schema.ts
- src/lib/routes/admin-api/instance-admin.ts
- src/test/e2e/api/admin/instance-admin.e2e.test.ts
Turns out we've been trying to return API token data in instance stats for a while, but that the serialization has failed. Serializing a JS map just yields an empty object. 
This PR fixes that serialization and also adds API tokens to the instance stats schema (it wasn't before, but we did return it). Adding it to the schema is also part of making resource usage visible as part of the soft limits project.
> fix: serialize API token data correctly in instance stats

- .github/workflows/docker_publish.yaml
- .github/workflows/publish-new-version.yaml
Backporting fixes to old versions usually pushes the docker latest tag as well. We only want to do this if the version we're releasing is the latest
> fix: when backporting we don't want to push latest docker tag (#7961)

- .github/workflows/docker_publish.yaml
This fixes this error: https://github.com/Unleash/unleash/actions/runs/10505976248/job/29104652388
> fix: when running on main we need to use latest=auto

- frontend/src/assets/icons/import.svg
- frontend/src/component/feature/FeatureToggleList/FeatureToggleListActions/FeatureToggleListActions.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx
- frontend/src/component/project/Project/Project.tsx
We found good one for export from MUI, but needed to created similar one for import.
> feat: introduce new icons for import/export

- website/docs/reference/resource-limits.mdx
Adds a note to the resource limit docs about what the minimum values are for some of the core resources if you override the limits.
These resources have a controlled minimum value. The resources that are not listed in the new table, do not. I don't know what happen if you set -42 for segmentValues, for instance. So ... I've left them out 🤷
Happy to take suggestions on how to fix it 😄
Also updates the availability note in preparation for 6.2 GA
> docs: mention what the minimum values are if you override the limits

- src/lib/services/api-token-service.test.ts
- src/lib/services/api-token-service.ts
Fixes a bug where if you had API keys using different casing for the same type, they'd come out as different types in the API token count map. To get around it, we normalize the keys to lowercase before inserting them into the map, taking into account any previous values that might have existed for that type.
Should fix issues like this:
> fix: normalize casing for API token types before insert 

- src/migrations/20240823091442-normalize-token-types.js
Adds a migration to normalize api token types already in the database, to remove any weird casing issues as currently demonstrated on sandbox
This is a companion piece to #7972
> fix: add migration to normalize api token types

- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NewInUnleash/NewInUnleash.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/ShowHide.tsx
Make the hide nav text and shortcut visible from the get go even when the content list is long. Previously you had to scroll to the bottom of the nav to see the text and shortcut.
Make sure there's enough space for the link info from the browser
Add new in unleash to the bottom
Also works with hidden mode
And with long content
> feat: make hide nav info always visible

- frontend/src/component/insights/InsightsCharts.tsx
- frontend/src/component/insights/hooks/useFilteredFlagsSummary.test.ts
- frontend/src/component/insights/hooks/useFilteredFlagsSummary.ts
- frontend/src/component/insights/hooks/useInsightsData.ts
- frontend/src/hooks/api/getters/useInsights/useInsights.ts
- frontend/src/openapi/models/instanceInsightsSchema.ts
Now the left widget will use the same that as the last data point on the right chart.
With this change, flags/users object never needs to be passed in.
**Next step is to remove the flags/users from the endpoint.**
Previous
Now
> feat: align insights charts

- src/lib/features/feature-search/feature-search-store.ts
- src/lib/features/feature-search/feature.search.e2e.test.ts
- src/lib/openapi/spec/feature-search-query-parameters.ts
Previously we expected the tag to look like `type:value`. Now we allow everything after first colon, as the value and not break query `type:this:still:is:value`.
> fix: support search for tags that has colon inside

- src/lib/metrics.ts
We are observing incorrect data in Prometheus, which is consistently non-reproducible. After a restart, the issue does not occur, but if the pods run for an extended period, they seem to enter a strange state where the counters become entangled and start sharing arbitrary values that are added to the counters.
For example, the `feature_lifecycle_stage_entered` counter gets an arbitrary value, such as 12, added when `inc()` is called. The `exceedsLimitErrorCounter` shows the same behavior, and the code implementation is identical.
We also tested some existing `increase()` counters, and they do not suffer from this issue.
All calls to `counter.labels(labels).inc(`) will be replaced by `counter.increment()` to try to mitigate the issue.
> fix: change .inc calls to .increment

- .github/workflows/publish-new-version.yaml
- package.json
This is not needed anymore as we are not publishing to npm from main.
> chore: strip +main from package version

- src/lib/db/user-store.ts
- src/lib/metric-events.ts
- src/lib/services/user-service.ts
- src/lib/types/stores/user-store.ts
- src/test/e2e/services/user-service.e2e.test.ts
- src/test/e2e/stores/user-store.e2e.test.ts
- src/test/fixtures/fake-user-store.ts
We can emit user login events with the extra information if it's the first user, second user etc. who logged into Unleash.
This will make onboarding metrics easier to implement by encapsulation login order logic inside the user subdomain.
> feat: user loging event emitting with login order

- src/lib/db/index.ts
- src/lib/db/user-store.ts
- src/lib/features/onboarding/fake-onboarding-store.ts
- src/lib/features/onboarding/onboarding-service.e2e.test.ts
- src/lib/features/onboarding/onboarding-service.ts
- src/lib/features/onboarding/onboarding-store-type.ts
- src/lib/features/onboarding/onboarding-store.test.ts
- src/lib/features/onboarding/onboarding-store.ts
- src/lib/features/project/fake-project-read-model.ts
- src/lib/features/project/project-read-model-type.ts
- src/lib/features/project/project-read-model.ts
- src/lib/features/project/project-store.ts
- src/lib/types/stores.ts
- src/lib/types/stores/user-store.ts
- src/test/fixtures/fake-user-store.ts
- src/test/fixtures/store.ts
* adding onboarding service with SQL store implementation
* added project read model method and user store method (can extract to read model in a separate PR)
* fixed project create method to allow for date control from the code
Next PR:
* create tests that combine store and read model
* plug the service into the rest of the code
* create composition root for the service
* write service tests with in-memory store for the listen method testing
Naming convention:
* when events progress through the system they change meaning. e.g. lifecycle `initial` event arrived from the lifecycle subdomain. It is translated to `flag-created` in the onboarding subdomain. One we confirm it's the first flag created we store it as `first-flag` in the DB.
> feat: onboarding store

- src/lib/features/onboarding/onboarding-read-model.test.ts
- src/lib/features/onboarding/onboarding-read-model.ts
Instead of lifecycle table, we take the metrics directly from onboarding tables.
> feat: onboarding table to prometheus

- src/lib/features/onboarding/createOnboardingService.ts
- src/lib/features/onboarding/fake-onboarding-store.ts
- src/lib/features/onboarding/onboarding-service.e2e.test.ts
- src/lib/features/onboarding/onboarding-service.ts
- src/lib/features/onboarding/onboarding-store-type.ts
- src/lib/features/onboarding/onboarding-store.ts
- src/lib/services/index.ts
- src/lib/types/services.ts
* creating composition root for the onboarding service
* calling listen method on the app startup
* added tests that verify that event handling works
> feat: onboarding service composition root

- frontend/src/component/menu/Footer/ApiDetails/ApiDetails.tsx
- frontend/src/component/menu/Footer/ApiDetails/__snapshots__/ApiDetails.test.tsx.snap
- frontend/src/component/menu/Footer/__snapshots__/Footer.test.tsx.snap
Instead of having the plan at the end, move it next to the product name and display the build number at last
> chore: reorganize product data in footer

- frontend/orval.config.js
- frontend/scripts/clean_orval_generated.sh
Simplify running frontend `gen:api`
> feat: update Orval config

- frontend/src/component/events/EventLog/EventLogFilters.test.tsx
- frontend/src/component/events/EventLog/EventLogFilters.tsx
- frontend/src/component/feature/FeatureView/FeatureSettings/FeatureSettingsProject/FeatureProjectSelect/FeatureProjectSelect.tsx
- frontend/src/component/insights/hooks/useProjectColor.ts
- frontend/src/component/project/ProjectCard/LegacyProjectCard.tsx
- frontend/src/component/project/ProjectCard/ProjectCard.tsx
- frontend/src/component/project/ProjectList/LegacyProjectList.tsx
- frontend/src/component/project/ProjectList/ProjectGroup.tsx
- frontend/src/component/project/ProjectList/group-projects.test.ts
- frontend/src/component/project/ProjectList/group-projects.ts
- frontend/src/component/project/ProjectList/hooks/useGroupedProjects.ts
- frontend/src/component/project/ProjectList/hooks/useProjectsSearchAndSort.test.ts
- frontend/src/component/project/ProjectList/hooks/useProjectsSearchAndSort.ts
- frontend/src/component/project/ProjectList/loadingData.ts
- frontend/src/component/segments/SegmentProjectAlert.tsx
- frontend/src/hooks/api/getters/useProjects/useProjects.ts
- frontend/src/interfaces/project.ts
- frontend/src/openapi/models/projectSchema.ts
Makes type consistent between frontend and schema generated from backend.
> refactor: replace IProjectCard with openapi type

- frontend/src/component/integrations/IntegrationEvents/IntegrationEventsModal.tsx
Cuts the total amount of integration event requests in half when browsing the integrations page, by only fetching the 20 latest events for each configured integration when it's actually needed (open modal).
> fix: reduce integration events requests

- src/lib/db/index.ts
- src/lib/features/onboarding/createOnboardingReadModel.ts
- src/lib/features/onboarding/fake-onboarding-read-model.ts
- src/lib/features/onboarding/onboarding-read-model-type.ts
- src/lib/features/onboarding/onboarding-read-model.test.ts
- src/lib/features/onboarding/onboarding-read-model.ts
- src/lib/features/onboarding/onboarding-service.e2e.test.ts
- src/lib/features/project/createProjectService.ts
- src/lib/features/project/project-service.ts
- src/lib/openapi/spec/project-overview-schema.test.ts
- src/lib/openapi/spec/project-overview-schema.ts
- src/lib/types/model.ts
- src/test/fixtures/store.ts
To show/hide onboarding flow, we need to get extra info about onboarding status. This PR adds it to project overview.
> feat: start returning onboarding status with project overview

- src/migrations/20240903152133-clear-onboarding-events.js
Clearing onboarding tables, because the data is invalid and we want to start tracking all of this for only new customers.
This migration must be applied after the new logic is implemented.
> chore: clear onboarding events

- frontend/src/component/onboarding/ConnectSdkDialog.tsx
- frontend/src/component/onboarding/GenerateApiKey.tsx
- frontend/src/component/onboarding/SelectSdk.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
First stage of connect SDK with SDK selection
Details:
* currently it's empty
* modelling union type for distinct stages
* fixing some typos
> feat: Select sdk onboarding pt 1

- frontend/src/component/onboarding/ConnectSdkDialog.tsx
- frontend/src/component/onboarding/GenerateApiKey.tsx
- frontend/src/component/onboarding/SelectSdk.tsx
Can select SDK and SDK type
Details:
* can navigate between first two stages including going back to stage 1 with SDK selection
* each stage selects either SDK name and type of the environment
* once you select one env it stays persistent even when you go back and forth
Next PR:
* add icons for SDKs
* add tests when the whole feature is complete
> feat: can select client and frontend sdk

- src/migrations/20240904084114-add-update-feature-dependency-editor.js
Editors should be able to add dependencies in a default project.
Details:
* adding new permission for editor
* editor is selection is dynamic by the role name instead of hardcoding 2 which is magical
* making sure the queries are idempotent and can be run multiple times
> fix: editor can add dependencies in default project

- src/lib/features/segment/segment-controller.ts
https://linear.app/unleash/issue/2-2592/updateimprove-a-segment-via-api-call
Related to https://github.com/Unleash/unleash/issues/7987
This does not make the endpoint necessarily better - It's still a PUT that acts as a PUT in some ways (expects specific required fields to be present, resets the project to `null` if it's not included in the body) and a PATCH in others (ignores most fields if they're not included in the body). We need to have a more in-depth discussion about developing long-term strategies for our API and respective OpenAPI spec.
However this at least includes the proper schema for the request body, which is slightly better than before.
> fix: add request body schema in update segment endpoint

- frontend/src/component/onboarding/SelectSdk.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOnboarding/ProjectOnboarding.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOnboarding/SdkExample.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOnboarding/WelcomeToProject.tsx
> feat: add sdk example box

- src/lib/create-config.ts
- src/lib/services/user-service.test.ts
https://github.com/Unleash/unleash/pull/7795 mistakenly changed the initial admin account environment variables to be:
- `INITIAL_ADMIN_USER_USERNAME`
- `INITIAL_ADMIN_USER_PASSWORD`
Instead of the previous:
- `UNLEASH_DEFAULT_ADMIN_USERNAME`
- `UNLEASH_DEFAULT_ADMIN_PASSWORD`
See: https://github.com/Unleash/unleash/pull/7795/files?diff=unified&w=0#diff-a38cc7ae9f963264333b6535498970a33e046dba50a6af554f438343a6edd2ddR319-R334
This PR reverts them back to the correct environment variable names and adds a test to prevent something similar from happening in the future.
> fix: use the correct env vars for initial admin account

- src/lib/services/user-service.test.ts
- website/docs/using-unleash/deploy/getting-started.md
https://github.com/Unleash/unleash/pull/7795 mistakenly included a mention that these environment variables can be used:
- `UNLEASH_DEFAULT_ADMIN_NAME`
- `UNLEASH_DEFAULT_ADMIN_EMAIL`
However that's not really the case, since we decided to remove their respective implementation before merging that PR.
> docs: remove mention of admin name and email env vars

- frontend/src/component/layout/MainLayout/NavigationSidebar/NewInUnleash/NewInUnleash.tsx
- frontend/src/component/onboarding/ConnectSdkDialog.tsx
- frontend/src/component/onboarding/SelectSdk.tsx
- frontend/src/component/onboarding/TestSdkConnection.tsx
- frontend/src/component/onboarding/sdkSnippets.ts
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
> feat: check flag status snippet

- frontend/src/component/admin/auth/ScimSettings/ScimSettings.tsx
- frontend/src/hooks/api/getters/useScimSettings/useScimSettings.ts
This property is unused and should be removed.
This fixes a logged schema error:
```
Invalid response: {
"schema": "#/components/schemas/scimSettingsSchema",
"errors": [
{
"instancePath": "",
"schemaPath": "#/required",
"keyword": "required",
"params": {
"missingProperty": "assumeControlOfExisting"
},
"message": "must have required property 'assumeControlOfExisting'"
}
]
}
```
> chore: remove unused SCIM setting - assumeControlOfExisting

- frontend/src/component/onboarding/GenerateApiKey.tsx
- frontend/src/component/onboarding/SelectSdk.tsx
- frontend/src/component/onboarding/SharedComponents.tsx
- frontend/src/component/onboarding/Stepper.tsx
- frontend/src/component/onboarding/TestSdkConnection.tsx
> feat: onboarding step badges

- frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/ProjectEnvironmentDefaultStrategy.tsx
This change copies (and then simplifies) the strategy variant display logic from
`frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyItem.tsx`
and inserts it into the `ProjectEnvironmentDefaultStrategy` component.
Before:
After:
> fix: Also display strategy variant information on default strategies

- src/lib/features/project-environments/environments.ts
This appears to have been an oversight in the original implementation
of this endpoint. This seems to be the primary point of this
permission. Additionally, the docs mention that this permission should
allow you to do just that.
Note: I've not added any tests for this, because we don't typically add tests for it. If we have an example to follow, I'd be very happy to add it, though
> fix: give project_default_strategy_write the ability to update the default strategy

- frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectDefaultStrategySettings.tsx
Previously, you needed read access specifically to see default
strategies. So even if you could write default strategies, you
couldn't access them in the UI without the read permission too.
This changes it so that you can see default strategies if you have
write permission.
> fix: allow you to see default strategies if you have write access

- frontend/src/component/feature/StrategyTypes/StrategyVariants.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/EditDefaultStrategy.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/ProjectDefaultStrategyForm.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/ProjectEnvironmentDefaultStrategy.tsx
Allow you to edit default strategies in the UI if you have the update_project or project_default_strategy_write permissions. These are the same permissions that we use in the API.
Previously, we used the update_feature_strategy permission here, but that one is intended to be used for updating strategies belonging to actual flags.
One of the trickier bits here is that we use the `StrategyVariants` component, which previously had baked in the permission required (update_feature_environment_variants). Because the permissions are different for the default strategy, I updated the component to make it configurable, but for the default to be the old permission (so that other uses aren't affected).
> fix: allow you to save default strategies with the right permissions

- frontend/src/component/common/ResponsiveButton/ResponsiveButton.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOnboarding/WelcomeToProject.tsx
- src/lib/features/onboarding/onboarding-read-model.ts
1. We will not show grid until 2 flags exist
2. Now new feature creation button will be always displayed on top with different style
3. Moved some text around
> feat: new onboarding welcome screen logic

- frontend/src/component/environments/CreateEnvironmentButton/CreateEnvironmentButton.tsx
The EEA flag is present in enterprise instances which currently is blocking enterprise customers from accessing this button. This PR inverts the logic that was changed in #7796.
> fix: invert logic

- .gitignore
- src/lib/features/project/can-grant-project-role.test.ts
- src/lib/features/project/can-grant-project-role.ts
- src/lib/features/project/project-service.e2e.test.ts
- src/lib/features/project/project-service.ts
- src/lib/routes/admin-api/user/user.ts
- src/lib/types/experimental.ts
Cherry pick the fix merged in #8084
> Fix/project role permission grant (#8084)

- src/lib/features/project/project-service.ts
We used these logs to debug an issue in sandbox regarding permissions. They are no longer needed.
> chore: remove debug logs

- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
https://linear.app/unleash/issue/2-2658/create-eventtimeline-feature-flag
Adds a new `eventTimeline` feature flag for the new event timeline feature.
I think `eventTimeline` is an appropriate name given the feature description and the way it is evolving, but I'm open to suggestions. ~~This also assumes that this feature will target OSS.~~ Confirmed that this will be a premium feature.
> chore: add eventTimeline feature flag

- package.json
- src/lib/services/openapi-service.ts
- yarn.lock
This new version [does not depend on dompurify](https://github.com/Unleash/unleash/pull/8170/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL3853-L3858) which should fix https://github.com/Unleash/unleash/security/dependabot/195
Tested the UI locally
> fix: upgrade openapi to drop dompurify and fix path-to-regexp

- src/lib/features/playground/feature-evaluator/strategy/flexible-rollout-strategy.ts
Same fix as done in some other sdks, such as the node one at
https://github.com/Unleash/unleash-client-node/pull/417o
Fixes an issue where 1% rollout would not yield any results with
random rollout for certain group ids
> fix: update playground SDK to increase the possible random numbers used for stickiness id

- src/lib/features/metrics/client-metrics/client-metrics-store-v2.ts
- src/migrations/20240919083625-client-metrics-env-variants-daily-to-bigint.js
We now have customers that exceed INT capacity, so we need to change this to BIGINT in client_metrics_env_variants_daily as well.
Even heavy users only have about 10000 rows here, so should be a quick enough operation.
> task: make count column bigint.

- src/lib/features/metrics/client-metrics/client-metrics-store-v2.ts
- src/migrations/20240919083625-client-metrics-env-variants-daily-to-bigint.js
We now have customers that exceed INT capacity, so we need to change this to BIGINT in client_metrics_env_variants_daily as well.
Even heavy users only have about 10000 rows here, so should be a quick enough operation.
> task: make count column bigint. (#8183)

- frontend/src/component/events/EventLog/EventLog.tsx
- frontend/src/component/events/EventTimeline/EventTimeline.tsx
- frontend/src/component/events/EventTimeline/EventTimelineEvent/EventTimelineEvent.tsx
- frontend/src/component/events/EventTimeline/EventTimelineEvent/EventTimelineEventTooltip/EventTimelineEventTooltip.tsx
- frontend/src/component/events/EventTimeline/EventTimelineHeader/EventTimelineHeader.tsx
- src/server-dev.ts
https://linear.app/unleash/issue/2-2657/implement-a-first-iteration-of-an-horizontal-event-timeline
This implements the very first iteration of our event timeline.
This is behind a feature flag, which when enabled shows the new timeline at the top of our event log page.
It is missing some features, like:
- Placement: It should show up as an option in the header, not in the event log;
- Tooltip: It should show proper tooltips for all the events that we're displaying;
- Grouping: It should group together events that occurred in a short span of time;
- Signals: It should show signals along with the events;
Here's how it currently looks like, with some example events, in order from left to right:
- A flag was disabled more than 30 min ago;
- A flag was then enabled;
- A segment was updated …
> chore: event timeline

- website/docs/contributing/ADRs/front-end/jsx-conditionals.md
https://github.com/Unleash/unleash/pull/8025#discussion_r1740561994
> fix: typo and improved example in latest ADR

- .github/workflows/docker_publish.yaml
So, since we updated to build-push-action@v6 we're now getting a nice summary of the build on the summary page of the action. It pointed out that we're caching 0% of our docker build. Since we probably change our own code more often than we change our dependencies, sharing the initial yarn install step between builds from cache seems to be a good idea.
> chore: enables github docker cache

- website/docs/feature-flag-tutorials/use-cases/gradual-rollout.md
> docs: remove extra diagram

- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/personalDashboard/ProjectSetupComplete.tsx
- frontend/src/component/personalDashboard/SetupComplete.tsx
This PR adds the new `ProjectSetupComplete` component (the name can be changed) that we display when a project has been set up with a flag and a connected SDK.
It uses the project overview to check the project's onboarding status.
> display setup complete message when project is onboarded

- frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx
- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/personalDashboard/createChartData.ts
- frontend/src/component/personalDashboard/createChartOptions.ts
Details:
* environment selection button from the active project environments
* time period selector re-used after making it more generic (configurable label)
* creating chartjs options and data based on the previous code we had in the feature metrics. I don't strive for re-use between the old line chart and the new bar chart since we'll most probably start using the bar charts in both places soon.
* most of the code is copy pasted from the previous implementation of the metrics line chart and network data bar chart
* making charts lazy loaded to avoid inflating the initial bundle with chartjs
Next steps:
* we may consider adding highlighter when a bar is selected (however this chart may be too dense for this)
> feat: personal flag metrics display

- src/lib/features/personal-dashboard/fake-personal-dashboard-read-model.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.ts
- src/lib/features/personal-dashboard/personal-dashboard-read-model-type.ts
- src/lib/features/personal-dashboard/personal-dashboard-read-model.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/openapi/spec/personal-dashboard-schema.ts
This PR adds some of the necessary project data to the personal dashboard API: project names and ids, and the roles that the user has in each of these projects.
I have not added project owners yet, as that would increase the complexity a bit and I'd rather focus on that in a separate PR.
I have also not added projects you are part of through a group, though I have added a placeholder test for that. I will address this in a follow-up.
> feat: add your projects (with roles) to personal dashboard api

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/common/Chart/customHighlightPlugin.ts
- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
- frontend/src/component/personalDashboard/createChartOptions.ts
Adding highlighter shadow to each data point
I had to explicitly disable annotations highlighting since ChartJS has a global registry of plugins and the annotation plugin from the data network tab was doing this registration. As a result if you open network data usage and then go to your dashboard you'd get the entire chart highlighted from the invisible annotation.
> feat: highlighting flags chart

- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-read-model.ts
This PR adds project roles you get from groups to the list of roles listed for each project.
> feat: add group project roles to project roles

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycle.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.test.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FlagExposure.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
Show last seen widget and lifecycle widget when selecting a flag
Same last seen as the project flags and single flag view
Same lifecycle as the project flags and single flag view
Details:
* create a new FlagExposure component to encapsulate exposure info
* had to improve lifecycle tooltip so that they don't reach to the URL for the project id. Instead we pass it explicitly from the parent. The reason for that is that personal dashboard is not tied to a project based URL 
* when archiving the flag from the lifecycle widget you end up on the same screen but we need to refresh the personal dashboard data. In other places we usually navigate to the project flags view after the archive but here it makes sense to stay in the dashboard
* if you archive a feature from the lifecycle tooltip with …
> feat: flag exposure in personal dashboard

- frontend/src/component/events/EventTimeline/EventTimeline.tsx
- frontend/src/component/events/EventTimeline/EventTimelineHeader/EventTimelineHeader.tsx
- frontend/src/component/events/EventTimeline/useEventTimeline.ts
- frontend/src/component/layout/MainLayout/MainLayout.tsx
- frontend/src/component/layout/MainLayout/MainLayoutEventTimeline.tsx
https://linear.app/unleash/issue/2-2700/persist-timeline-state-in-local-storage
Implements persistent state management for the event timeline using local storage. 
I believe this improves UX by persisting both the timeline toggle (visibility) state and applied filters across page refreshes.
Includes some scouting/refactoring and some workarounds to prevent the timeline from animating on page load (in most cases).
> chore: event timeline persistent state

- frontend/src/component/onboarding/snippets/rust.md
A bit different then other examples - only way to run current state of Rust SDK is to have some kind of an opinionated setup around it.
> feat(onboarding): Rust SDK snippet

- frontend/src/setupTests.ts
- frontend/src/utils/testServer.ts
Reducing noise in frontend tests
Most of the console warn logs we get in frontend tests are:
* wrap React in act warnings (since we use react testing library it shouldn't be needed)
* MSW HTTP mock not setup
The first warning will be hopefully gone with those issues fixed:
* https://github.com/testing-library/react-testing-library/issues/1338
* https://github.com/testing-library/react-testing-library/issues/1216
The second warning we can ignore since we don't need to setup every HTTP interaction to make our tests pass and returning error by default should be fine.
By reducing those warning we are left with the important warnings that we can act upon
> test: reduce noise from test warnings

- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-read-model-type.ts
- src/lib/features/personal-dashboard/personal-dashboard-read-model.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/features/project/fake-project-owners-read-model.ts
- src/lib/features/project/project-owners-read-model.ts
- src/lib/features/project/project-owners-read-model.type.ts
- src/lib/openapi/spec/personal-dashboard-schema.ts
- src/lib/services/index.ts
This PR adds project owner information to the personal dashboard's project payload.
To do so, it uses the existing project owners read model.
I've had to make a few changes to the project owners read model to accomodate this:
- make the input type to `addOwners` more lenient. We only need the project ids, so we can make that the only required property
- fall back to using email as the name if the user has no name or username (such as if you sign up with the demo auth)
Should we pass the anonymize emails flag here? I've got a vague memory that we actually anonymize them in the db now, so we don't need to here, but I can't remember exactly. (Update: emails are encrypted on creation in demo; this shouldn't be necessary: https://unleash-internal.slack.com/archives/C046LV6HH6W/p1722514435046269 …
> feat: add project owners to personal dashboard project payload

- frontend/src/component/onboarding/ConnectSdkDialog.tsx
- frontend/src/component/onboarding/ConnectionInformation.tsx
- frontend/src/component/onboarding/SdkConnected.tsx
- frontend/src/component/onboarding/SdkConnection.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
1. Now the dialog will not close when SDK got connected
2. It will start to show the suggested production code. ( this will be attached in next PR)
3. Also, it has connected indicator on the right
4. Back button is removed in this stage.
> feat: display new completed dialog

- frontend/src/component/layout/MainLayout/MainLayout.tsx
I believe the changes in https://github.com/Unleash/unleash/pull/8234, more specifically [this change](https://github.com/Unleash/unleash/pull/8234/files#diff-3a5e0763fe1effa9cd485763fecf0633ce8f0877c9d1971e6bd5c5abe7426364L64), have caused the main layout content to no longer stretch to its maximum relative width on larger screens.
This adjustment seems to resolve this issue, ensuring proper behavior on larger screens without introducing any overflow issues on smaller screens.
> fix: layout content width on large screens

- src/lib/features/project/project-read-model-type.ts
- src/lib/features/project/project-read-model.ts
- src/lib/features/project/project-service.e2e.test.ts
- src/lib/features/project/project-service.ts
- src/lib/features/project/project-store-type.ts
Adding ability to read projects by multiple ids.
Background:
In the personal dashboard we need to return a list of user projects with health/flags counts/members count (that a user is a member of or favorited). My plan is to have a separate query to read user project ids and then pass those ids to the existing query. This way we can orchestrate the desired behavior in a service without writing new complex queries. 
I considered changing query param id to query param ids (plural) in place, but since we use the single id in a few places I find it safer to add a new property and not touch the existing code.
> feat: get projects by ids

- src/lib/schema/role-schema.ts
- src/lib/services/access-service.test.ts
This trims role names before validation and subsequent validation.
This fixes a bug where you could have names that were empty or that
were duplicates of other names, but with leading or trailing
spaces. (They display the same in the UI).
This does not modify how we handle descriptions in the API. While the
UI form requires you to enter a description, the API does not. As
such, we can't make that required now without it being a breaking change.
> fix: trim role names before validation

- frontend/cypress/global.d.ts
- frontend/cypress/support/commands.ts
Some e2e Cypress tests were failing due to the Vercel live feedback toolbar covering interactive elements, preventing test actions from completing: https://github.com/Unleash/unleash/actions/runs/11048512034/job/30692949711#step:4:136
This PR addresses the issue by disabling the Vercel toolbar specifically during Cypress tests. This is done by setting the `x-vercel-skip-toolbar` header, which Vercel provides to prevent the toolbar from interfering with automated tests. You can find more information about this feature in the Vercel documentation: [Disable Toolbar for Automation](https://vercel.com/docs/workflow-collaboration/vercel-toolbar/managing-toolbar#disable-toolbar-for-automation).
Specific type declarations were needed due to https://github.com/cypress-io/cypress/issues/19564
> test: skip vercel toolbar in e2e tests

- frontend/src/component/admin/roles/RoleForm/RoleForm.tsx
- frontend/src/component/admin/roles/RoleForm/useRoleForm.test.ts
- frontend/src/component/admin/roles/RoleForm/useRoleForm.ts
This fixes a bug where you can input just whitespace for
name/description. It also means that you can no longer have both "my
role" and "my role    " as separate roles.
API fix will follow.
> fix: trim name and description before validation

- CONTRIBUTING.md
- website/docs/contributing/backend/overview.md
- website/docs/using-unleash/deploy/database-setup.md
- website/docs/using-unleash/deploy/getting-started.md
Unify on PG v13, we had one place recommending v10, release notes for v6 saying we dropped support for v10 through v12 and mentioning 13, and a place mentioning 14 or newer.
fixes: #8265
> docs: recommend PG v13 or later

- frontend/src/component/onboarding/dialog/snippets/flutter.md
- frontend/src/component/onboarding/dialog/snippets/go.md
- frontend/src/component/onboarding/dialog/snippets/java.md
- frontend/src/component/onboarding/dialog/snippets/javascript.md
- frontend/src/component/onboarding/dialog/snippets/nodejs.md
- frontend/src/component/onboarding/dialog/snippets/php.md
- frontend/src/component/onboarding/dialog/snippets/python.md
- frontend/src/component/onboarding/dialog/snippets/ruby.md
- frontend/src/component/onboarding/dialog/snippets/rust.md
- frontend/src/component/onboarding/dialog/snippets/swift.md
Joined all examples into one copyable example.
Did not do following ones, because they are using templates and probably will not work as joined.
1. React
2. Svelte
3. Vue
Also skipped, because those examples are not final yet.
1. .NET
2. Android
> feat: now code examples are joined into one

- frontend/src/component/common/AvatarGroupFromOwners/AvatarGroupFromOwners.tsx
- frontend/src/component/common/OwnerAvatarGroup/OwnerAvatarGroup.tsx
- frontend/src/component/personalDashboard/ContentGridNoProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/personalDashboard/RoleAndOwnerInfo.tsx
- frontend/src/component/project/ProjectCard/ProjectCardFooter/ProjectOwners/ProjectOwners.tsx
This adds a front end fallback screen for when you have no projects.
> feat: create page for when you have no projects

- frontend/src/component/onboarding/dialog/SdkConnected.tsx
- frontend/src/component/onboarding/dialog/SdkConnection.tsx
- frontend/src/component/onboarding/dialog/snippets/flutter.md
- frontend/src/component/onboarding/dialog/snippets/go.md
- frontend/src/component/onboarding/dialog/snippets/java.md
- frontend/src/component/onboarding/dialog/snippets/javascript.md
- frontend/src/component/onboarding/dialog/snippets/nodejs.md
- frontend/src/component/onboarding/dialog/snippets/php.md
- frontend/src/component/onboarding/dialog/snippets/python.md
- frontend/src/component/onboarding/dialog/snippets/react.md
- frontend/src/component/onboarding/dialog/snippets/ruby.md
- frontend/src/component/onboarding/dialog/snippets/rust.md
- frontend/src/component/onboarding/dialog/snippets/svelte.md
- frontend/src/component/onboarding/dialog/snippets/vue.md
Skipped .NET and Android because they are not ready. Also swift does not support env variables, so skipped for now.
Added all rest.
> feat: add production snippets and resources

- src/lib/addons/feature-event-formatter-md.ts
- src/lib/features/personal-dashboard/createPersonalDashboardService.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/openapi/spec/personal-dashboard-project-details-schema.ts
- src/lib/services/index.ts
Return last events from the project details API.
This will feed this part of the UI. createdBy goes to avatar and markdown summary into human readable description
Details:
* use event store to get latest events
* use addon formatter that can prepare human readable summary
* I decided to call it latestEvents (also considered recentEvents, lastEvents). I choose this name consistently within this PR
> feat: return latest project events

- src/lib/features/events/event-search-controller.ts
Scouting: I think this description was copy-pasted from the previous endpoint and we forgot to update it.
> chore: fix search events endpoint description

- frontend/src/component/onboarding/dialog/ConnectSdkDialog.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
Makes the button more clear. 
Now both **onboarding** started and **onboarding finished** screens will not be shown in the same time.
> fix: now only one onboarding screen will be shown at time

- frontend/src/component/events/EventTimeline/useEventTimeline.ts
- frontend/src/component/layout/MainLayout/MainLayoutEventTimeline.tsx
Fixes 2 bugs:
- The initial state of the event timeline should have `open: false`, not `true` - Closed by default, unless opened
- The event timeline should unmount when hidden - It should not emit requests when closed
> fix: event timeline should unmount when hidden and be closed by default

- src/lib/addons/datadog.ts
- src/lib/addons/slack-app.ts
- src/lib/addons/slack.ts
- src/lib/addons/teams.ts
Moves the addon/integration result metrics-counting to the finally block / outside the result successful if-else, to capture not just failed runs but successful runs as well
> fix: some integrations only counted errors not all results

- frontend/src/component/personalDashboard/ContentGridNoProjects.tsx
- frontend/src/component/personalDashboard/LatestProjectEvents.tsx
- frontend/src/openapi/models/personalDashboardProjectDetailsSchemaLatestEventsItem.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/openapi/spec/personal-dashboard-project-details-schema.ts
Details:
* expose event author image url from backend
* expose event id for react keys
* align avatar and markdown
> feat: last project events ui polishing

- src/lib/db/account-store.ts
- src/lib/features/personal-dashboard/createPersonalDashboardService.ts
- src/lib/features/personal-dashboard/fake-personal-dashboard-read-model.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/openapi/spec/personal-dashboard-schema.ts
- src/lib/types/stores/account-store.ts
- src/lib/types/user.ts
- src/test/fixtures/fake-account-store.ts
Adds Unleash admins to the personal dashboard payload.
Uses the access store (and a new method) to fetch admins and maps it to a new `MinimalUser` type. We already have a `User` class, but it contains a lot of information we don't care about here, such as `isAPI`, SCIM data etc.
In the UI, admins will be shown to users who are not part of any projects. This is the default state for new viewer users, and can also happen for editors if you archive the default project, for instance.
Tests in a follow-up PR
> feat: add Unleash admins to API payload

- frontend/src/component/personalDashboard/PersonalDashboard.tsx
Added ability to open Unleash concepts not only when you first visit but also when clicking on the info icon.
Other: 
* making welcome part more compact to avoid scrolling when visiting a personal dashboard
* renamed modal state to open/closed since it can be seen multiple times now
> feat: open unleash concepts

- src/lib/__snapshots__/create-config.test.ts.snap
- src/lib/metrics.test.ts
- src/lib/metrics.ts
Ideally `feature_lifecycle_stage_entered{stage="archived"}` would allow me to see how many flags are archived per week. 
It seems like the numbers for this is a bit off, and wanted to extend our current `feature_toggle_update` counter with action details.
> fix: extend feature_toggle_update counter with details about action

- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/openapi/models/personalDashboardProjectDetailsSchema.ts
- src/lib/features/personal-dashboard/createPersonalDashboardService.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/openapi/spec/personal-dashboard-project-details-schema.ts
Exposing project onboarding status in the personal dashboard project details API.
It allows to stop making separate API calls to personal dashboard API and project overview API.
Manually updated orval types. Separate PR will autogenerate new types.
> feat: add onboarding status to personal dashboard api

- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/features/project/fake-project-read-model.ts
- src/lib/features/project/project-read-model-type.ts
- src/lib/features/project/project-read-model.ts
Including user favorited projects in personal dashboard even when use is not a member of those projects.
Created a new `getProjectsFavoritedByUser` method instead of touching `getProjectsByUser` that is used in user profile and notifications. Personal dashboard service is combining user membership projects and user favorited projects.
> feat: include favorite projects in personal dashboard

- src/lib/services/access-service.ts
- src/lib/services/clean-permission-environment.test.ts
- src/lib/types/model.ts
Splitting #8271 into smaller pieces. This first PR will focus on making access service handle empty string inputs gracefully and converting them to null before inserting them into the database.
> fix: handle empty strings on permissions gracefully in access service

- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/features/project/fake-project-owners-read-model.ts
- src/lib/features/project/project-owners-read-model.ts
- src/lib/features/project/project-owners-read-model.type.ts
This PR is part 1 of returning project owners and your project roles for the personal dashboard single-project endpoint.
It moves the responsibility of adding owners and roles to the project to the service from the controller and adds a new method to the project owners read model to take care of it.
I'll add roles and tests in follow-up PRs.
> feat: return project owners

- src/lib/features/personal-dashboard/createPersonalDashboardService.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/services/access-service.test.ts
- src/test/fixtures/fake-access-store.ts
This PR updates the personal dashboard project endpoint to return owners and roles. It also adds the impl for getting roles (via the access store).
I'm filtering the roles for a project to only include project roles for now, but we might wanna change this later.
Tests and UI update will follow.
> feat: return project roles

- frontend/src/component/personalDashboard/Grid.tsx
- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
Move My projects section into MyProjects.tsx. Previously all the code was in the PersonalDashboard.tsx.
> refactor: extract my projects component

- frontend/src/component/onboarding/flow/SdkExample.tsx
Links from Unleash UI to [Unleash/unleash-sdk-examples](https://github.com/Unleash/unleash-sdk-examples)
https://linear.app/unleash/issue/1-2869/add-codesandbox-links-to-unleashunleash
> feat(onboarding): add links to examples

- src/lib/services/access-service.ts
This PR adds missing awaits on the call to eventStore which were revealed to be fire and forget when we added transactional support for these methods.
> fix: add missing awaits on events

- frontend/src/component/events/EventTimeline/EventTimelineEventGroup/EventTimelineEventCircle.tsx
https://linear.app/unleash/issue/2-2726/groups-should-show-the-timeline-event-type-icon-when-all-events-inside
Displays the event type icon for the group when all events within the group share the same type.
> chore: timeline event group icon when events are all same type

- frontend/src/component/commandBar/CommandBar.tsx
- frontend/src/component/commandBar/CommandSearchFeatures.tsx
Previously it sending plausible event before the query had loaded and making false positives.
> fix: fix tracking of menu bar for no search results

- src/lib/features/personal-dashboard/fake-personal-dashboard-read-model.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-read-model-type.ts
- src/lib/features/personal-dashboard/personal-dashboard-read-model.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/openapi/spec/personal-dashboard-project-details-schema.ts
For pro and enterprise customers we can provide feedback on avg health score in the past 4 weeks vs current 4 weeks. 
The calculation is inspired by the avg health score indicator in the ios health app. 
This PR adds the calculation in the service and a query in the personal dashboard read model. I couldn't find a good home for this query so added it to the existing read model for now. 
As a result of this PR we can implement the following logic:
* For pro and enterprise users how have enough health scores show this view
In the next iteration it would be nice to add some visual indicators
* For oss users and users without enough health scores (at least 8 weeks) show a default view
> feat: personal dashboard project avg health scores

- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/RoleAndOwnerInfo.tsx
This commit uses the now-included project owner and role information
to populate the owner/role section. If you have no roles, we'll tell
you that you don't instead of displaying an empty set of badges.
> feat: handle owners and project roles in the UI

- frontend/src/component/onboarding/dialog/SdkConnected.tsx
- frontend/src/component/onboarding/dialog/snippets/nodejs.md
- frontend/src/component/onboarding/flow/ProjectOnboarding.test.tsx
- frontend/src/component/onboarding/flow/ProjectOnboarding.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
1. Refetch features when creating the flag. It took a while for it to appear before.
2. Fix NodeJS snippet and make texts more clear.
> feat: improve onboarding flow

- src/lib/features/personal-dashboard/personal-dashboard-service.ts
This PR follows up on a comment made in https://github.com/Unleash/unleash/pull/8314 and groups sequential awaited calls into a single Promise.all instead.
> refactor: use promise.all instead of sequential awaited calls

- src/lib/types/group.ts
This property does not seem to be used anywhere, so we can remove it.
Can't find any references in code here or in enterprise. Let's try it and see if it breaks.
> chore: remove the projects? Property from ICreateGroupModel

- frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsHours/FeatureMetricsHours.tsx
- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
This PR adds labels to the environment and period selectors for the flag metrics chart on the personal dashboard page. Because the period selector is also used on the flag metrics page, I've also updated its use there by removing a previous text label (which was just text, not an associated `label` element).
Before:
Chart:
Flag metrics:
After:
Chart:
Flag metrics:
> a11y: add labels to env/period selectors

- frontend/src/hooks/api/getters/usePersonalDashboard/usePersonalDashboardProjectDetails.ts
This switches to using conditional SWR to fetch project details only
when you provide a project. This fixes an issue where we'd make
requests for `api/admin/personal-dashboard/undefined` (which will be a
404 in the future).
> fix: only ask for project details if we have a project ID

- src/lib/types/experimental.ts
We validated that all customers have migrated
QQ: for self-hosted are we switching from false to true? Should we have an intermediate release just flipping the value?
Answer: No, the code was removed long time ago so this configuration has no effect
> chore: remove unused flag

- frontend/src/component/events/EventTimeline/EventTimeline.tsx
- frontend/src/component/events/EventTimeline/EventTimelineHeader/EventTimelineHeader.tsx
- frontend/src/component/events/EventTimeline/EventTimelineHeader/EventTimelineHeaderTip.tsx
- frontend/src/component/events/EventTimeline/EventTimelineProvider.tsx
- frontend/src/component/layout/MainLayout/MainLayoutEventTimeline.tsx
https://linear.app/unleash/issue/2-2723/add-signals-tip
Adds a tip to the event timeline regarding the usage of signals.
The conditions for it to show up are the following:
- `!signalsSuggestionSeen` - The current user has not closed the tip yet
- `isEnterprise()` - The Unleash instance is an Enterprise instance (signals are currently Enterprise-only)
- `isAdmin` - The current user is an admin (signals are currently admin-only)
- `signalsEnabled` - The signals feature flag is currently enabled
- `!loading` - Signal endpoints have not finished loading (prevents flickering)
- `signalEndpoints.length === 0` - The Unleash instance currently has zero configured signal endpoints (signals feature is not being used)
> chore: event timeline signals tip

- frontend/src/component/personalDashboard/PersonalDashboard.test.tsx
Testing the entire PersonalDashboard component
Covered areas:
* welcome username
* explanation message
* projects list with flags, members, health and project name
* project insights
* event
* your project role
* favorited flags
* default metrics environment
* default metrics period
* no metrics info
* onboarding cases (create flag, connect sdk, no flags)
Next PRs will cover other areas like project owner (couldn't get it to work in this test) or viewer with no projects
I had to mock HTMLCanvasElement.prototype.getContext to remove errors from the chart library
> test: personal dashboard

- frontend/src/component/personalDashboard/Grid.tsx
- frontend/src/component/personalDashboard/MyProjects.tsx
This PR is a work in progress, but the current state aims to suggest a direction. The main goals of this are:
1. Make it so that the layout grid doesn't break on small screens
2. Fix an issue where the border of the box didn't fit the outline
3. (Bonus): make the layout of the info box depend on the **box's** size, not the screen size.
To achieve those goals, this PR:
1. Switches to using a native CSS grid instead of MUI's grid component. This gives us more power over the layout in various different sizes.
2. Switches from putting borders on the boxes inside the grid, instead makes the grid container the color of the border and uses gaps to create borders.
3. If your browser supports it, it will use container queries to determine whether we should display the layout as a multi-column grid …
> fix: add grid w/container query for projects

- frontend/src/component/personalDashboard/ContentGridNoProjects.tsx
- frontend/src/component/personalDashboard/Grid.tsx
- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
This PR uses the new CSS grid layout for the flag grid and the no content grid.
In doing so, it also improves how you use the grid item (giving them a `gridArea` prop) and extracts the breakpoint handling so that all sections that use breakpoints use the same breakpoints.
As with the previous PR, here's screenies of the same screen width, but with open and closed sidebar:
Open:
Closed:
> refactor: use css grid for flags and no content grid

- frontend/src/component/personalDashboard/PersonalDashboard.test.tsx
- frontend/src/component/personalDashboard/ProjectSetupComplete.tsx
- frontend/src/component/project/Project/ProjectInsights/ProjectHealth/FlagCounts.tsx
- frontend/src/component/project/Project/ProjectInsights/ProjectHealth/ProjectHealth.tsx
- frontend/src/openapi/models/personalDashboardProjectDetailsSchemaInsights.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/openapi/spec/personal-dashboard-project-details-schema.ts
OSS users will always see this insight. Pro and Enterprise users will see this insights until they get 8 weeks of health trends data.
Pro and Enterprise users will see this insight after they get 8 weeks of health trends data.
Details:
* reusing health chart and health chart legend from the project insights. I decided to include the legend so that we know what each color means
> feat: health score components in personal dashboard

- frontend/src/component/personalDashboard/Grid.tsx
This PR reduces the gaps/borders between items in the dashboard grids to 1px.
This screenie has both: 1px for the top grid (projects), 2px for the bottom one (flags):
> fix: make gaps 1px instead of 2px

- src/lib/features/onboarding/onboarding-read-model.test.ts
- src/lib/features/onboarding/onboarding-read-model.ts
Now when you are finished onboarding and you archive feature, you will not restart onboarding.
> feat: archived features will be included in onboarding

- frontend/src/component/onboarding/dialog/ConnectSdkDialog.tsx
- frontend/src/component/onboarding/dialog/GenerateApiKey.tsx
- frontend/src/component/onboarding/flow/SdkExample.tsx
- frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/CreateProjectDialog.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
- frontend/src/hooks/usePlausibleTracker.ts
Tracking events for
1. Onboarding started/project created
2. Onboarding finishes
3. API token generated
4. Sdk example clicked
Not tracking events that can happen multiple times and results are skewed
1. Moving between onboarding steps
> feat: add plausible for onboarding

- frontend/src/component/personalDashboard/RoleAndOwnerInfo.tsx
This change fixes the vertical alignment of the owners and roles
content.
Before:
After:
> fix: vertically center owners and roles content

- frontend/src/component/events/EventTimeline/EventTimelineHeader/EventTimelineHeaderTip.tsx
- frontend/src/hooks/api/getters/useSignalQuery/useSignalQuery.ts
https://linear.app/unleash/issue/2-2743/open-the-signal-query-endpoint-to-everyone-not-only-admins
The new signal query endpoint is now open for every Unleash user, not only admins. 
This PR allows non-admins to view signals in the event timeline. It also updates the signals tooltip to be shown to all users, not just admins, under the following assumptions:
- `!signalsSuggestionSeen` - Current user has not dismissed the signals tip
- `isEnterprise()` - Enterprise instance
- `signalsEnabled` - The signals feature flag is enabled
- `!signalsLoading` - Signals have finished loading (avoids flickering)
- `signals.length === 0` - We can't find any signals in the selected timespan
> chore: make signals visible on event timeline for non admins

- src/lib/features/onboarding/fake-onboarding-read-model.ts
- src/lib/features/onboarding/onboarding-read-model-type.ts
- src/lib/features/onboarding/onboarding-read-model.ts
- src/lib/features/personal-dashboard/createPersonalDashboardService.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/features/project/project-service.ts
This change adds a check for whether the project exists in the
database before trying to fetch data for it. If it doesn't exist,
you'll get a 404.
> fix: return 404 if the project doesn't exist

- frontend/src/openapi/models/personalDashboardProjectDetailsSchema.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/project/project-owners-read-model.ts
- src/lib/openapi/spec/personal-dashboard-project-details-schema.ts
This PR fixes a bug where the default project would have no listed owners. The issue was that the default project has no user owners by default, so we didn't get a result back when looking for user owners. Now we check whether we have any owners for that project, and if we don't, then we return the system user as an owner instead.
This also fixes an issue for the default project where you have no roles (because by default, you don't) by updating the schema to allow an empty list.
> fix: no owners listed in personal dashboard for default project

- frontend/src/component/layout/MainLayout/NavigationSidebar/NewInUnleash/NewInUnleash.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NewInUnleash/NewInUnleashItem.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NewInUnleash/NewInUnleashTooltip.tsx
https://linear.app/unleash/issue/2-2750/add-beta-badge-to-event-timeline-in-the-new-in-unleash-section
Adds a beta badge to the event timeline item in "New in Unleash".
> chore: add beta badge to event timeline in new in unleash

- frontend/src/component/events/EventTimeline/EventTimelineHeader/EventTimelineHeader.tsx
- frontend/src/component/menu/Header/HeaderEventTimelineButton.tsx
https://linear.app/unleash/issue/2-2753/improve-current-showhide-tooltips-to-be-more-specific-about-the
Improves the "show" and "hide" tooltips of this feature to have a slightly more specific text. This is not just any timeline, this is the **event timeline**.
- "Hide timeline" -> "Hide event timeline"
- "Show timeline" -> "Show event timeline"
> chore: better show hide event timeline tooltips

- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.test.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/hooks/api/getters/usePersonalDashboard/usePersonalDashboardProjectDetails.ts
This PR stores the dashboard state (selected project and flag) in localstorage so that you get taken back to the same project and flag when you refresh the page or navigate away and back.
It also handles scrolling the selected items into view in case they're below the fold.
> feat: store dashboard state

- frontend/src/assets/icons/import.svg
This change updates the import svg's viewbox. It was set to be 24 x
24, but the icon is only 16px wide, causing it to be shifted 4px to
the left, as shown in the following image:
By shrinking the viewbox (but keeping the width the same), the icon is
now more correctly aligned:
> fix: import svg viewbox misalignment

- frontend/package.json
- frontend/yarn.lock
The primary reason for the bump is that newer versions of jsdom
support `@container` queries. The current version chucks a big warning
into stderr that it couldn't parse the stylesheet.
> chore: update jsdom to 25.0.1

- frontend/src/component/personalDashboard/RoleAndOwnerInfo.tsx
This PR improves how we handle cases where you have lots of roles or roles with very long names.
It puts project roles into it's own little area (and turns it into a list!). We'll show three roles by default. If they all have super long names, we'll split them up onto multiple lines.
Additionally, the headers and avatar group will no longer wrap.
So in edge case territory, it'll look like this:
And what if one role has an even longer name? It'll wrap inside the badge:
> fix: handle lots of project roles better

- frontend/src/component/onboarding/dialog/snippets/dotnet.md
- frontend/src/component/onboarding/dialog/snippets/go.md
- frontend/src/component/onboarding/dialog/snippets/java.md
- frontend/src/component/onboarding/dialog/snippets/javascript.md
- frontend/src/component/onboarding/dialog/snippets/nodejs.md
- frontend/src/component/onboarding/dialog/snippets/php.md
- frontend/src/component/onboarding/dialog/snippets/python.md
- frontend/src/component/onboarding/dialog/snippets/react.md
- frontend/src/component/onboarding/dialog/snippets/ruby.md
- frontend/src/component/onboarding/dialog/snippets/rust.md
- frontend/src/component/onboarding/dialog/snippets/svelte.md
- frontend/src/component/onboarding/dialog/snippets/vue.md
- src/lib/features/onboarding/onboarding-read-model.test.ts
- src/lib/features/onboarding/onboarding-read-model.ts
1. Remove all customer intervals
2. Start capturing onboarded status also from register endpoint
> feat: start capturing onboarded status also from register endpoint

- frontend/src/component/personalDashboard/ContentGridNoProjects.tsx
- frontend/src/component/personalDashboard/Grid.tsx
- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.test.tsx
- frontend/src/component/personalDashboard/RoleAndOwnerInfo.tsx
The badge has been removed from the onboarding flow, so we don't need
to show it here. This also prepares it for the collapsible sections.
> chore: removes setup badge from personal dashboard

- frontend/src/component/onboarding/dialog/snippets/android.md
- frontend/src/component/onboarding/dialog/snippets/swift.md
Two corner cases, android and swift do not post metrics before default time. Adding small info box for them.
> feat: android/swift slow metric info

- src/lib/db/api-token-store.ts
These might be some heavy queries, adding timers to them to validate that assumption and get some insights
> chore: add timers to count queries

- frontend/src/component/personalDashboard/LatestProjectEvents.tsx
- frontend/src/openapi/models/personalDashboardProjectDetailsSchemaLatestEventsItem.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.e2e.test.ts
- src/lib/features/personal-dashboard/personal-dashboard-controller.ts
- src/lib/features/personal-dashboard/personal-dashboard-service.ts
- src/lib/openapi/spec/personal-dashboard-project-details-schema.ts
This PR adds timestamps to project events and displays them in the "latest events" box in the project details view.
It also changes the font weight of events to be only normal.
> feat: add timestamps to project events

- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.test.tsx
- frontend/src/component/personalDashboard/createChartOptions.ts
This PR adjusts what we show for no data to make it clearer that we actually have no data.
It also makes the graph slightly smaller.
> fix: make no data look like no data

- frontend/src/component/common/util.ts
- frontend/src/component/menu/routes.ts
- frontend/src/component/project/ProjectEnvironment/ProjectEnvironment.tsx
- frontend/src/interfaces/route.ts
Ensure that 'environments' page is not shown in navigation.
> fix: environments route should be hidden from menu for open-source

- frontend/src/component/personalDashboard/createChartOptions.ts
This PR adds back in ticks for the Y axis of the chart. The ticks were removed when updating the no content chart and this was an oversight.
> fix: display tick values for chart Y axis

- frontend/src/component/personalDashboard/PersonalDashboard.test.tsx
- frontend/src/component/personalDashboard/ProjectSetupComplete.tsx
Removes the graph and updates the box to show a health message based on current health if you don't have any trends:
With trends:
Without:
> chore: remove graph, update health message

- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
- frontend/src/component/personalDashboard/createChartOptions.ts
This PR fixes two issues with the chart in dark mode:
1. Grid lines are almost invisible
2. Placeholder data lines are way too bright
The fix for both is to use the theme's divider color.
> fix: chart issues in dark mode

- frontend/src/interfaces/uiConfig.ts
- src/lib/__snapshots__/create-config.test.ts.snap
- src/lib/create-config.ts
- src/lib/openapi/spec/ui-config-schema.ts
- src/lib/routes/admin-api/config.ts
- src/lib/types/option.ts
https://linear.app/unleash/issue/2-2787/add-openai-api-key-to-our-configuration
Adds the OpenAI API key to our configuration and exposes a new `unleashAIAvailable` boolean in our UI config to let our frontend know that we have configured this. This can be used together with our flag to decide whether we should enable our experiment for our users.
> chore: add OpenAI API key configuration

- src/lib/addons/webhook.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
Introduces a flag for webhook info-logging of invocations against domain. This should be on for our cloud customers but default to off so it doesn't clutter logs of OSS/Selfhosted
> chore: flag for webhook domain logging

- frontend/src/component/personalDashboard/ConnectSDK.tsx
- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/hooks/usePlausibleTracker.ts
This PR adds plausible tracking for navigating to items from the personal dashboard.
It tracks:
- Navigating to projects from the list
- Navigating to projects from the onboarding screen
- Navigating to flags from the list
- Opening the key concepts dialog
> chore: track personal dashboard navigation

- frontend/src/component/personalDashboard/ConnectSDK.tsx
- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
This PR makes it so that we show an empty chart when we're loading flag metrics, instead of showing the placeholder chart.
It uses a very simple version that may not be the same size as the standard chart (because it has no labels), but we can change that at a later date.
> fix: show empty chart when we're loading flag metrics

- frontend/src/component/events/EventTimeline/EventTimeline.tsx
- frontend/src/component/events/EventTimeline/EventTimelineEventGroup/EventTimelineEventCircle.tsx
- frontend/src/component/events/EventTimeline/EventTimelineEventGroup/EventTimelineEventTooltip/EventTimelineEventTooltip.tsx
https://linear.app/unleash/issue/2-2796/better-signals-integration
Adds support to the following signal payload meta properties:
- `unleash_title`
- `unleash_description`
- `unleash_icon`
- `unleash_variant`
Follows a logic similar to what we currently have for banners. E.g. [custom icon](https://docs.getunleash.io/reference/banners#custom-icon).
> chore: use new signal meta properties in event timeline

- frontend/src/component/personalDashboard/ConnectSDK.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
Making them absolute appears to break them. Reverting to relative links.
> fix: revert link changes

- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
- frontend/src/component/personalDashboard/Grid.tsx
- frontend/src/component/personalDashboard/LatestProjectEvents.tsx
- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
This PR fixes issues with section sizes including:
- Jank when they change suddenly
- Overflowing list of admins / events
- Short lists that should stretch to the height of their container.
> fix: section sizes

- frontend/src/component/personalDashboard/PersonalDashboard.tsx
To avoid showing the key concepts screen to users every time they log back in to Unleash (after logging out), store the state in the DB splash table.
The reason we need to do this is that we clear localstorage on logging out, so things like splash screens and certain other settings don't get stored.
> refactor: use splash api to store splash state

- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
- frontend/src/component/personalDashboard/Grid.tsx
- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/personalDashboard/createChartOptions.ts
This commit adjusts the height of the flag section in the personal
dashboard, so that the chart doesn't cause scrolling on the widest version.
Before:
After:
Also fixes some issues in regards to super big lists when it goes into flex mode and makes the chart more responsive
> fix: adjust the height of the flag section

- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/personalDashboard/RoleAndOwnerInfo.tsx
This PR improves handling of narrow screens. It:
- makes the owner/roles row wrap when it needs to
- makes the lifecycle + metric selectors wrap when necessary
- makes the text for the empty chart wrap (and makes it text, not label)
> fix: handle narrow screens better

- frontend/src/component/insights/hooks/useFilteredFlagsSummary.test.ts
- frontend/src/component/insights/hooks/useFilteredFlagsSummary.ts
Now it will match with chart if no data.
Previous
Now
> fix: now health widget will match will chart

- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
This PR fixes a spacing issues between the lifecycle metrics and the environment/period selector. They're now grouped better by proximity.
> fix: spacing between lifecycle metrics and env/period selector

- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
- frontend/src/component/personalDashboard/Grid.tsx
- frontend/src/component/personalDashboard/MyFlags.tsx
- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/personalDashboard/useDashboardState.ts
This PR is the first in the front end code refactoring. It moves My Flags out into a separate file and includes some extra error handling (such as if the name of the flag causes problems for the API).
> Refactor front end code pt 1

- frontend/src/hooks/api/actions/useAIApi/useAIApi.ts
- package.json
https://linear.app/unleash/issue/2-2791/create-a-useaiapi-react-hook
Implements a basic Unleash AI API React hook that fits our initial needs for interacting with this API through our frontend.
Also adds a new nice-to-have script to run the frontend set to the `demo` base path, which matches our Cloud defaults. This way you can run the latest local cloud with the latest local frontend in an easy way.
> chore: Unleash AI API hook

- frontend/src/component/ai/AIChat.tsx
- frontend/src/component/ai/AIChatHeader.tsx
- frontend/src/component/ai/AIChatInput.tsx
- frontend/src/component/ai/AIChatMessage.tsx
- frontend/src/component/layout/MainLayout/MainLayout.tsx
https://linear.app/unleash/issue/2-2792/create-the-aichat-component
Implements the Unleash AI chat UI.
This is essentially a polished version from the hackathon.
It will show up in the bottom right corner when the respective prerequisites are met.
> chore: Unleash AI chat UI

- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationList.tsx
- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
This change updates the title for the personal dashboard menu item to
be just "dashboard"
Before:
After:
> chore: rename personal dashboard menu item to dashboard

- src/lib/features/frontend-api/client-feature-toggle-read-model.ts
- src/lib/features/frontend-api/frontend-api-controller.ts
- src/lib/util/metrics-helper.ts
This gives us better types for our wrapTimer function.
Maybe the type `(args: any) => any` could also be improved
> chore: wrapTimer function types

- src/lib/middleware/authorization-middleware.ts
This fixes #8029. How to reproduce the issue is in the ticket.
The issue happens because when a web app is hosted in the same domain as Unleash UI and the web app uses unleash SDK to make requests to Unleash, the browser automatically includes the cookie in the request headers, because:
- The request URL matches the cookie's Path attribute (which it does in this case).
- The request is sent to the same domain (which it is, since both apps are under the same domain).
And this is by design in the HTTP cookie specification: https://datatracker.ietf.org/doc/html/rfc6265
This PR avoids overriding the API user with the session user if there's already an API user in the request. It's an alternative to https://github.com/Unleash/unleash/pull/8434
Closes #8029
> fix: same site api call with session cookie

- frontend/package.json
- frontend/src/component/admin/apiToken/CreateApiToken/CreateApiToken.test.tsx
- frontend/src/component/admin/roles/RoleForm/useRoleForm.test.ts
- frontend/src/component/common/Sticky/StickyProvider.test.tsx
- frontend/src/component/common/TimeAgo/TimeAgo.test.tsx
- frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsModal/VariantForm/VariantOverrides/useOverrides.test.ts
- frontend/src/component/onboarding/flow/ProjectOnboarding.test.tsx
- frontend/src/component/onboarding/flow/ProjectOnboarding.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.test.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/CreateProjectDialog.test.tsx
- frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/hooks/useOptimisticUpdate.test.ts
- frontend/src/component/project/Project/hooks/useProjectForm.test.ts
- frontend/yarn.lock
don't use `act` from `react-dom`. Instead, use act from `react` directly, as advised by the deprecation notice.
This PR fixes all of the deprecated import warnings, updates some testing libraries we use (and tests), and fixes one or two other warnings.
> chore: remove all deprecated imports of act

- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/project/ProjectList/ProjectList.tsx
This commits adds descriptions to the accordion headers in the
personal dashboard.
> chore: add descriptions to accordion headers

- src/lib/__snapshots__/create-config.test.ts.snap
- src/lib/create-config.ts
- src/lib/types/option.ts
- src/lib/users/inactive/createInactiveUsersService.ts
- src/lib/users/inactive/inactive-users-controller.ts
- src/lib/users/inactive/inactive-users-service.ts
Give the ability to change when users are considered inactive via an environment variable `USER_INACTIVITY_THRESHOLD_IN_DAYS` or configuration option: `userInactivityThresholdInDays`. Default remains 180 days
> feat: ability to configure when users are considered inactive

- frontend/src/component/ai/AIChatMessage.tsx
https://linear.app/unleash/issue/2-2841/fix-a-bug-where-code-does-not-break-to-new-lines-in-messages
Fixes a bug where code in an Unleash AI chat message would not break to new lines.
> fix: unleash AI chat message code not breaking to new line

- frontend/src/component/common/Badge/Badge.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
This PR fixes all `invalidDomNesting` errors we're getting in our tests. The culprit was the `Badge` icon we use, which wrapped its children in a div. When that's used as a child of a `p` tag, that'd cause this to trigger. 
What I've done is to change the wrapping element to a span instead. The Badge itself uses an `display: inline-flex`, so divs and spans should be treated the same, meaning there's no visual change for this.
> chore: fix invalid dom nesting

- frontend/src/component/ai/AIChat.tsx
- frontend/src/component/common/Resizable/Resizable.tsx
https://linear.app/unleash/issue/2-2840/make-the-unleash-ai-chat-window-resizable
This PR makes the Unleash AI chat resizable, providing users with a flexible way to adjust the chat window's size.
Implements a reusable `Resizable` wrapper component that allows configuration of:
- Minimum, maximum, and default sizes.
- Customizable resize handlers for each edge and corner of the container.
- Optional resize event callbacks.
Double-clicking any resize handler maximizes the container along that axis (or both, if it's a corner). If the container is already maximized, double-clicking again will revert it to the default size.
> chore: make the Unleash AI chat resizable

- src/lib/features/project/project-service.test.ts
- src/lib/features/project/project-service.ts
- src/lib/services/group-service.ts
- src/lib/types/group.ts
- src/lib/types/stores/access-store.ts
Sometimes when a project had an owner and a group that has Owner role together with other roles you couldn't remove the owner access for the group.
The workaround were to remove the other group roles first, then you could remove the owner role when it was the only role left for the group in the project (given that any other group or user had owner role)
The reason was that we were checking an aggregated `roleId` property on the group roles returned object, which is set by a reduce function to be the first row of group ids returned from the db query. If any other role than 'Owner' was set as roleId, that group wasn't counted by the atleastOneOwner verification and if there was only 1 other 'Owner' on the project then the operation wasn't allowed.
Fixed this by removing the property …
> fix: group and user has at least 1 project owner counter respects multirole project groups

- frontend/src/component/admin/apiToken/ApiTokenForm/ProjectSelector/SelectProjectInput/SelectProjectInput.tsx
- frontend/src/component/application/ConnectedInstances/ConnectedInstancesTable.tsx
- frontend/src/component/context/ContextList/ContextList/ContextList.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/FeatureStrategyConstraintAccordionList/FeatureStrategyConstraintAccordionList.test.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyCreate/featureStrategyFormTestSetup.ts
- frontend/src/component/feature/FeatureStrategy/FeatureStrategySegment/FeatureStrategySegmentList.tsx
- frontend/src/component/feature/FeatureView/FeatureMetrics/FeatureMetricsTable/FeatureMetricsTable.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/VariantsTooltip.tsx
- frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantsCard/EnvironmentVariantsTable/EnvironmentVariantsTable.tsx
- frontend/src/component/integrations/IntegrationForm/IntegrationForm.tsx
- frontend/src/component/integrations/IntegrationForm/IntegrationMultiSelector/IntegrationMultiSelector.tsx
- frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundConnectionFieldset/EnvironmentsField/EnvironmentsField.tsx
- frontend/src/component/playground/Playground/PlaygroundForm/renderOption.tsx
- frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/PlaygroundResultFeatureStrategyList.test.tsx
- frontend/src/component/project/Project/ProjectInsights/LeadTimeForChanges/LeadTimeForChanges.tsx
- frontend/src/component/project/ProjectList/ProjectList.test.tsx
- frontend/src/component/tags/TagTypeList/TagTypeList.tsx
- frontend/src/hooks/useRecentlyVisited.test.tsx
Fixes all warnings about the "key" prop. The majority of the fixes fall into one of the following categories:
- Extracting "key" props in tables (you're not allowed to just spread them in)
- Adding "key" props to autocomplete options and chips
- fixing test data that didn't contain ids
> chore: fix "key" prop issues in front end tests

- frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ArchiveButton.tsx
- frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ManageTags.tsx
Fix this warning:
> MUI: You are providing a disabled button child to the Tooltip component.
> A disabled element does not fire events.
> Tooltip needs to listen to the child element’s events to display the title.
> Add a simple wrapper element, such as a span.
> fix: fix two disabled tooltips

- src/lib/openapi/spec/ai-chat-message-schema.ts
- src/lib/openapi/spec/ai-chat-new-message-schema.ts
- src/lib/openapi/spec/ai-chat-schema.ts
- src/lib/openapi/spec/index.ts
- src/migrations/20241016123833-ai-chats-rename-chat-col-to-messages.js
https://linear.app/unleash/issue/2-2779/store-conversations-in-the-database
Updates schemas related to Unleash AI chat and renames the `chat` column to `messages` to ensure everything aligns nicely.
> chore: update schemas related to Unleash AI chat

- frontend/src/hooks/useTrafficData.test.ts
- frontend/src/hooks/useTrafficData.ts
> fix: traffic estimate should Math.floor price estimate to full million

- frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx
This changes the warning on adding group root roles to cover all roles rather than just Editor or Admin. This got opened to Viewers in a 2K line monster PR that was mostly refactor so I'm assuming this was an accident but it's not a dangerous accident
Okay so why change the warning rather than change the code?
Two reasons.
1) This has been like this for a year and a half. It was changed before the feature entered GA, so users are probably used to it by now. Seems rude to take things away and it's harmless to keep it
2) It's consistent with everything else to have all 3 roles displayed and removes an edge case in the code
> chore: patch text when trying to add a root role group

- frontend/src/setupTests.ts
This silences front end test warnings, errors, and logs that we don't care about. The
reason we don't care is that:
- we won't fix
- it's test-specific, doesn't appear to happen in real life
And it clogs the test logs.
> chore: silence remaining front end test warnings

- frontend/src/component/layout/MainLayout/NavigationSidebar/IconRenderer.tsx
- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
- frontend/src/component/releases/ReleaseManagement.tsx
- frontend/src/interfaces/uiConfig.ts
- src/server-dev.ts
Adds a `Release management` item to the nav menu and an empty releasemgmt page component.
Temporarily suggests the MUI `Launch` icon as the release mgmt link icon.
> feat: release plans nav menu item and icon suggestion

- frontend/src/component/layout/MainLayout/NavigationSidebar/IconRenderer.tsx
This makes the icon show up correctly in the command menu.
> fix: add the dashboard icon to the iconrenderer

- src/lib/features/instance-stats/instance-stats-service.test.ts
- src/lib/features/instance-stats/instance-stats-service.ts
- src/lib/features/scheduler/schedule-services.ts
- src/lib/metrics-gauge.test.ts
- src/lib/metrics-gauge.ts
- src/lib/metrics.test.ts
- src/lib/metrics.ts
- src/test/e2e/api/admin/instance-admin.e2e.test.ts
This is a follow up on https://github.com/Unleash/unleash/pull/8446
- migrating some metrics (check the commits)
- moving event listener registration outside metric calculation (every 2 hs we are adding new listeners)
- adding jitter to metric refresh
- manually executing some of the tasks immediately to avoid changing the test logic (with jitter now we'd have to force or wait until the first execution of the scheduled task that collect the metrics). We might decide to change this later after the migration
- try catch the execution of the task
- register metrics now "just registers" and returns functions for refreshing metrics. In the future, we'll return an object with the ability of independently updating specific metrics so we can tweak the frequency of updates
> chore: handle aggregation queries sequentially follow up

- frontend/src/component/admin/roles/RoleForm/useRoleForm.test.ts
- frontend/src/component/admin/roles/RoleForm/useRoleForm.ts
This fixes a bug where we didn't allow spaces in role descriptions.
The bug came about because we wanted to disallow empty descriptions,
but that means we need to trim them before validating, not necessarily
before setting it.
However, that does mean that you can have descriptions with leading
and trailing spaces now, but that's probably fine.
To fix this, we'd have to do the trimming of the description only at
submission time, I think.
> fix: allow you to add spaces to role descriptions

- frontend/src/component/admin/auth/AuthSettings.tsx
- frontend/src/component/admin/roles/RolesPage.tsx
- frontend/src/component/featureTypes/FeatureTypesList.tsx
- frontend/src/component/insights/components/InsightsHeader/InsightsHeader.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/strategies/StrategiesList/StrategiesList.tsx
Fixing page titles:
Details:
Pages using PageContent component with a header property automatically get their title set.
All the other pages need explicit usePageTitle invocation.
I tried to add more info to the title where it makes sense:
* username in personal dashboard
* SSO method in SSO page
> fix: missing page titles

- frontend/src/component/ai/AIChat.tsx
- frontend/src/component/ai/AIChatInput.tsx
- frontend/src/setupTests.ts
https://linear.app/unleash/issue/2-2857/make-some-scroll-related-ux-adjustments-to-the-unleash-ai-chat
Introduces scroll-related UX enhancements to the Unleash AI chat, providing a smoother and more refined user experience.
> chore: scroll-related UX adjustments in the Unleash AI chat

- frontend/src/component/ai/AIChat.tsx
- frontend/src/component/ai/AIChatDisclaimer.tsx
https://linear.app/unleash/issue/2-2853/add-a-disclaimer-to-the-unleash-ai-chat-window
Adds a small, initial disclaimer to Unleash AI chat.
> chore: add an initial disclaimer to Unleash AI

- website/docs/how-to/how-to-add-sso-azure-saml.mdx
In preparation for a mdx 3 upgrade, we need to remove the `{` character. This PR modifies the placeholder values to be consistent and code formatted, so it doesn't cause errors with mdx 3. 
**[Preview of the page](https://unleash-docs-git-melinda-fix-formatting-iss-17d353-unleash-team.vercel.app/how-to/how-to-add-sso-azure-saml)**
> Fix markdown 3 error for placeholder text

- frontend/src/component/personalDashboard/ActionBox.tsx
- frontend/src/component/personalDashboard/LatestProjectEvents.tsx
- frontend/src/component/personalDashboard/MyFlags.tsx
- frontend/src/component/personalDashboard/SharedComponents.tsx
* Align scrollbars to the right of the container box in flag list and project list sections.
* remove padding at the top of the insights and events boxes (it will also affect create flag and connect sdk but they still look good)
* prevent long event markdown from x-overflow (saw this with prod data)
> feat: personal dashboard scrollbars and spacing

- frontend/src/component/personalDashboard/MyProjects.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/personalDashboard/ProjectDetailsError.tsx
- frontend/src/component/personalDashboard/RemoteData.ts
- frontend/src/component/personalDashboard/RoleAndOwnerInfo.tsx
This PR updates the use of references on the project details page to handle the loading state for a single project.
Now, if a project is loading, it'll show skeleton loaders for the relevant boxes:
I've also updated the state type we use for this to be more accurate. However, it feels like it's getting kinda messy they way we handle it now. I wouldn't mind refactoring the output of the hook into something more like this data type to make handling more explicit. (Shamelessly stolen from Elm, but iykyk)
```ts
type RemoteData<T> = 
| { state: 'error', error: Error } 
| { state: 'loading' } 
| { state: 'success', data: T } 
```
Also, I had some issues with applying the `data-loading` attribute to components, where it seemed to work in some cases, but not in others. For instance, for …
> fix: handle loading states for project details for a single project

- frontend/src/component/personalDashboard/LatestProjectEvents.tsx
For the events markdown we want to prioritize breaking on words, but for very long strings we want to break on anything.
> fix: break words first, break all second

- src/lib/routes/util.ts
- src/lib/schema/feature-schema.test.ts
We do some validation on flag names, but there's some cases that slip through. These are some cases that we should handle better.
With `..` as a name, you can't go into the flag in Unleash and you can't activate any environments because the it is interpreted as "go up a level".
> fix: don't allow . or .. in feature url

- frontend/package.json
> fix: fontend dev command to start in sandbox pro environment

- .github/workflows/dependency-review.yml
Seems to be very permissive and close to ISC: https://opensource.org/license/0bsd
> chore: add 0BSD license

- src/lib/services/email-service.test.ts
- src/lib/services/email-service.ts
- src/lib/types/experimental.ts
- src/mailtemplates/productivity-report/productivity-report.html.mustache
- src/mailtemplates/productivity-report/productivity-report.plain.mustache
First draft of productivity report email sending. This has placeholder data that needs to be replaced with a real template. Also we need to figure out how to send batch emails.
> feat: email service for productivity report

- src/lib/db/client-applications-store.ts
Previously we were returning all instance names from database, but now we count them in database.
> feat: rework application overview db query

- src/migrations/20241024062521-add-release-plans-milestones-strategies.js
Adds release plans migration.
- Creates release_plan_definitions
- Creates milestones
- Creates milestone_strategies
- Creates indexes on FK of milestones and milestone_strategies tables
Adds a down migration that removes indexes, columns, and tables in an order that addresses inter-dependencies
> chore: add migration for release plans

- src/migrations/20241024081537-sent-emails-table.js
Background: we need to send emails for productivity report every month. We need to guarantee at most once delivery semantics.
Solution: Create sent_emails table. There's a potential vector of change that involves more email types so I optimize for this use case.
Proposed structure:
* id is similar to trends ids YYYY-MM and indicates that we have already sent a report for 2024-10
* type is the email type and it accommodates different email types
* created_at is the exact date we sent out the email (useful for tracking if we sent out emails when we intend)
* payload - so that we know what dynamic data was provided in the template (it allows re-sent capability in future and debugging)
Note: this PR will be merged once we used it in sample code that gives us feedback that the structure is …
> feat: emails sent table migration

- frontend/src/component/admin/billing/BillingHistory/BillingHistory.tsx
- frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx
- frontend/src/component/changeRequest/ProjectChangeRequests/ProjectChangeRequests.tsx
- frontend/src/component/environments/EnvironmentTable/EnvironmentTableSingle.tsx
- frontend/src/component/featureTypes/FeatureTypesList.tsx
- frontend/src/component/playground/Playground/PlaygroundResultsTable/VariantCell/VariantInformation/VariantInformation.tsx
- frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/ChangeRequestTable.tsx
- frontend/src/component/project/Project/ProjectDoraMetrics/ProjectDoraMetrics.tsx
- frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestTable.tsx
- frontend/src/component/project/ProjectEnvironment/EnvironmentHideDialog/ProjectEnvironmentTableSingle/ProjectEnvironmentTableSingle.tsx
- frontend/src/component/project/ProjectEnvironment/ProjectEnvironment.tsx
- frontend/src/component/segments/SegmentTable/SegmentTable.tsx
- frontend/src/component/strategies/StrategiesList/StrategiesList.tsx
This commit fixes invalid prop spreading warnings in all the table rows I
could find through a quick search in the code base.
The issue is that you can't spread the "key" prop into a component. It *must* be an explicit prop.
The process is the same everywhere:
1. Instead of spreading `row.getRowProps()` into the component, we extract and split it: `const {key, ...rowProps} = row.getRowProps()`.
2. Do the same thing for cellProps.
> fix: invalid spreading of keys into table rows everywhere

- src/lib/features/events/event-service.ts
- src/test/e2e/api/admin/event-search.e2e.test.ts
This change fixes a bug in the event filter's `to` query parameter.
The problem was that in an attempt to make it inclusive, we also
stripped it of the `IS:` prefix, which meant it had no effect. This
change fixes that by first splitting the value, fixing only the
date (because we want it to include the entire day), and then joining
it back together.
> fix: correctly filter for `to` dates

- frontend/package.json
- frontend/yarn.lock
Looking at https://github.com/Unleash/unleash/security/dependabot/204 it seems that the dependency comes from orval that should not be needed in production:
```shell
$ yarn why  --recursive jsonpath-plus                
└─ unleash-frontend-local@workspace:.
└─ orval@npm:6.31.0 (via npm:^6.31.0)
├─ @orval/angular@npm:6.31.0 (via npm:6.31.0)
│  └─ @orval/core@npm:6.31.0 (via npm:6.31.0)
│     └─ @ibm-cloud/openapi-ruleset@npm:1.17.0 (via npm:^1.14.2)
│        ├─ @stoplight/spectral-formats@npm:1.6.0 (via npm:^1.6.0)
│        │  └─ @stoplight/spectral-core@npm:1.18.3 (via npm:^1.8.0)
│        │     ├─ jsonpath-plus@npm:7.1.0 (via npm:7.1.0)
│        │     └─ nimma@npm:0.2.2 (via npm:0.2.2)
│        │        └─ jsonpath-plus@npm:6.0.1 (via npm:^6.0.1)
│        ├─ …
```
> security: move orval to dev dependency

- frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureDeleteConfirm/ArchivedFeatureDeleteConfirm.tsx
- frontend/src/component/archive/ArchiveTable/ArchivedFeatureActionCell/ArchivedFeatureReviveConfirm/ArchivedFeatureReviveConfirm.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOverviewFilters.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/hooks/useRowActions.tsx
> feat: archive is now part of project feature list

- src/migrations/20241030093439-release-plans-template-ref-and-missing-strategy-fields.js
Adds a migration that adds segments to milestone strategies and adds release-plan-template reference to release_plan_definitions
> chore: add migration for milestone strategy segments

- src/lib/addons/addon.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
Removes the `addonUsageMetrics` flag, final part of closing integration metrics project for GA in 6.4
> chore: remove the addonUsageMetrics flag

- frontend/src/component/menu/Footer/ApiDetails/ApiDetails.tsx
- frontend/src/component/menu/Footer/ApiDetails/apidetails.helpers.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/openapi/spec/ui-config-schema.ts
https://linear.app/unleash/issue/CTO-102/unleash-add-support-for-payg-billing
> chore: add support for PAYG billing

- docker/package.json
- docker/yarn.lock
> Revert "fix: set path-to-regexp version in docker"

- frontend/src/component/project/Project/Project.tsx
- frontend/src/component/project/Project/ProjectFlags.tsx
This PR adds the initial bit of code required to set up the change request indicator, but it's not functional yet: I've hardcoded the value 0 for now, which also hides the notifications.
This PR also hides the previous project change request overview.
I'll make a follow-up to the API when it's ready to hook it up.
> feat: initial setup of change request notification indicator

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/hooks/useTrafficLimit.test.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/hooks/useTrafficLimit.ts
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
> feat: traffic limits for enterprise-payg

- frontend/src/component/events/EventTimeline/EventTimeline.tsx
- frontend/src/component/layout/MainLayout/MainLayoutEventTimeline.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NewInUnleash/NewInUnleash.tsx
- frontend/src/component/menu/Header/HeaderEventTimelineButton.tsx
- src/lib/features/events/event-search-controller.ts
- src/lib/openapi/spec/event-schema.ts
- src/lib/types/experimental.ts
https://linear.app/unleash/issue/2-2855/change-our-experimental-title-to-camelcase-and-maybe-remove
Drops "experimental" from the new signal meta properties and makes them camelCase instead.
> chore: drop experimental from new signal meta properties

- src/migrations/20241031123526-release-plan-definition-remove-fk-constraint-on-userid.js
Removes a fk constraint release-plans-definitions->created_by_user_id on users table so we can delete users even if they have created release-plans/templates
Also adds an index on created_by_user_id
> chore: add migration for release-plans-definitions that removes fk on users(id)

- biome.json
- frontend/package.json
- frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
- frontend/src/themes/app.css
- frontend/yarn.lock
- package.json
- src/lib/db/access-store.ts
- src/lib/features/instance-stats/getProductionChanges.ts
- website/src/css/custom.css
- website/src/theme/DocItem/Footer/contributors.module.css
- yarn.lock
The two lints being turned off are new for 1.9.x and caused a massive diff inside frontend if activated, to reduce impact, turned them off for the merge. We might want to look at turning them back on once we're ready to have a semantic / a11y refactor of our frontend
> chore: upgrade to biome 1.9.4

- frontend/src/component/filter/AddFilterButton.tsx
> feat: archive movement informational tooltip

- frontend/src/component/events/EventTimeline/EventTimelineEventGroup/EventTimelineEventGroup.tsx
The default badge styling uses theme.palette.primary.main for the
color, but this color doesn't give us the contrast we need in dark
mode. The solution is to use theme.palette.background.alternative instead.
Before:
After:
> chore: use palette.background.alternative for background

- frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx
- frontend/src/component/project/ProjectAccess/ProjectAccess.tsx
- frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx
This PR re-orders the project settings menu according to the new design. It also renames pages as specified. It does *not* add the new "applications and sdks" link because we don't have that page yet.
I have not put this change behind a flag, because it's not a new feature and doesn't really change the user experience. However, I'd be happy to flag it if you think that's better.
The header for the user access tab has also been updated:
> chore: re-order project settings menu

- frontend/src/component/project/Project/Project.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectResources.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectStatusModal.tsx
This PR begins to stub out the project resources widget. I still need one more piece of data and then to work on the styling, but it's a placeholder for now. I've also moved the project status modal to its own folder so we can group the widgets etc. I'd like to get that merged quickly to avoid any future conflicts, which is why I'm making the PR ready now.
> chore: stub out project resources for status model

- frontend/src/component/events/EventTimeline/EventTimelineEventGroup/EventTimelineEventGroup.tsx
The recent fix to dark mode's background color for events also
caused an issue with the text color in light mode. This change makes
it so that the text color is correct in both instances.
Before (light):
After (light + dark):
> fix: text color in timeline event group for light mode

- src/lib/services/email-service.test.ts
- src/lib/services/email-service.ts
- src/mailtemplates/productivity-report/productivity-report.html.mustache
- src/mailtemplates/productivity-report/productivity-report.plain.mustache
Show link to user profile where she can manager email subscription
> feat: unsubscribe link to user profile

- frontend/src/component/user/Profile/ProfileTab/ProductivityEmailSubscription.tsx
- frontend/src/component/user/Profile/ProfileTab/ProfileTab.tsx
- frontend/src/hooks/api/actions/useEmailSubscriptionApi/useEmailSubscriptionApi.ts
- frontend/src/hooks/usePlausibleTracker.ts
- frontend/src/interfaces/uiConfig.ts
Productivity report subscription management UI
Details:
* MUI Switch toggle to control subscription status
* toasts after success and error
* sending subscribe/unsubscribe requests on toggle 
* initial state and state updates to-be-implemented after we add subscription information to user profile API
* plausible tracking of subscribe/unsubscribe actions (goal already added to plausible)
> feat: productivity report subscription UI

- frontend/src/component/App.tsx
Evaluate `*` with login redirect before showing 404s.
> fix: enterprise routes 404 when not logged in

- src/mailtemplates/productivity-report/productivity-report.html.mustache
> fix(productivity-report): email table alignment on mobile

- src/lib/features/project-status/projects-status.e2e.test.ts
This was an oversight. The test would always fail after 2024-11-04,
because yesterday is no longer 2024-11-03. This way, we're using the
same string in both places.
> fix: set a dynamic yesterday date instead of a fixed one.

- src/lib/features/project-status/createProjectStatusService.ts
- src/lib/features/project-status/project-status-service.ts
- src/lib/features/project-status/projects-status.e2e.test.ts
- src/lib/features/project/project-store-type.ts
- src/lib/features/project/project-store.ts
- src/lib/openapi/spec/project-status-schema.test.ts
- src/lib/openapi/spec/project-status-schema.ts
- src/test/fixtures/fake-project-store.ts
This PR adds connected environments to the project status payload.
It's done by:
- adding a new `getConnectedEnvironmentCountForProject` method to the project store (I opted for this approach instead of creating a new view model because it already has a `getEnvironmentsForProject` method)
- adding the project store to the project status service
- updating the schema
For the schema, I opted for adding a `resources` property, under which I put `connectedEnvironments`. My thinking was that if we want to add the rest of the project resources (that go in the resources widget), it'd make sense to group those together inside an object. However, I'd also be happy to place the property on the top level. If you have opinions one way or the other, let me know.
As for the count, we're currently only …
> chore: add connected environments to project status payload

- frontend/src/component/project/Project/Project.tsx
- frontend/src/component/project/Project/ProjectSettings/Settings/Settings.tsx
**Issue fix:** Resolves #8618, where environments were incorrectly appended to the route.
**Change:** Introduces `ossPath` specifically for OSS users, as OSS lacks the default `/settings` path, starting instead from `api-access`.
> fix: fix project settings path for oss

- src/lib/create-config.ts
- website/docs/using-unleash/deploy/configuring-unleash.mdx
Closes #
In some cases, people want to disable database migration. For example, some people or companies want to grant whole permissions to handle the schema by DBAs, not by application level hence I use `parseEnvVarBoolean` to handle `disableMigration` option by environment variable. I set the default value as `false` for the backward compatibility.
However, I wonder where to add test code of it because all the unit and e2e test is a kind of testing the whole configuration.
> feat: Make `disableMigration` option handled by environment variable

- src/migrations/20241105123918-add-cascade-for-user-unsubscription.js
Remove opt-outs for deleted users. This is useful in tests, where we delete users permanently.
> migration(producitivty-report): cascade user unsubscription

- frontend/src/component/project/Project/ProjectStatus/ProjectResources.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectStatusModal.tsx
This change adds a few small bits of styling to the status modal to
get us going. It:
- adds padding to the whole modal
- adds a row for the health and resources widgets
- add project health placeholder
It leaves the project activity widget alone for now.
it makes the modal look like this:
> chore: add initial styling bits to status modal

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/OldDependencyActions.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/OldDependencyRow.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/OldFeatureOverviewMetaData.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/TagRow.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/OldFeatureOverviewSidePanel.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/ManageTagsDialog.tsx
https://linear.app/unleash/issue/2-2920/update-the-flag-overview-metadata-properties-to-match-the-new-design
Updates the feature flag overview metadata panel to match the new design.
This redesign is behind a feature flag, so we opted to go with a duplicate file approach. We should remember to clean this up if we decide to remove the flag.
> chore: new feature flag overview metadata panel

- frontend/src/component/common/Highlight/Highlight.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/TagRow.tsx
Addressing some oversights that led to browser console errors.
This PR fixes console errors related to the recently introduced highlight component (#8643) and tag row component in the new flag metadata panel (#8663).
> fix: console errors from highlight component and tag key prop placement

- frontend/vite.config.mts
Configured SCSS preprocessor options to use the `modern-compiler` API, aligning with the new Sass API standards and preparing for Dart Sass 2.0.0. This change prevents deprecation warnings and ensures future compatibility by transitioning away from the legacy JS API.
https://sass-lang.com/documentation/breaking-changes/legacy-js-api/
Got rid of
> chore: update SCSS preprocessor API to modern-compiler

- frontend/src/component/project/Project/ProjectSettings/ProjectSegments/ProjectSegments.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx
This change opens up the project segments page to OSS users. They
could navigate to it explicitly before, but would be told it was a
premium feature (which it is not (since 5.5)).
After this, it'll show up in the settings sidebar as for
pro/enterprise, and you'll get the actual segments table instead of
"this is a premium feature" message.
> chore: remove project segments gate for oss users

- frontend/src/component/personalDashboard/MyProjects.tsx
Previously it never went to else clause. Because it was always onboardingStarted.
> fix: dashboard onboarding flow correct conditions

- frontend/src/component/releases/ReleaseManagement/ReleasePlanTemplateCardMenu.tsx
- frontend/src/component/releases/ReleaseManagement/TemplateDeleteDialog.tsx
- frontend/src/hooks/api/actions/useReleasePlanTemplatesApi/useReleasePlanTemplatesApi.ts
Deleting release plan templates (with confirmation dialog)
We should probably look at permission model for this, I'll make a note of that
> feat: deleting release-plan templates

- frontend/src/component/filter/AddFilterButton.tsx
Fixing archive tooltip appearing on every filter in Unleash
> fix: show archive tooltip only on project screen

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleStageIcon.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectLifecycleSummary.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectStatusModal.tsx
Add rough implementation of the lifecycle summary components.
This PR adds components for all the different lifecycle stages. We don't have any data yet, so they're all hardcoded for now, just to get the visuals right. I'm expecting the lines of code to drop and to refactor/extract some structures as development continues.
For now, this is what they look like:
Things to note:
- The lifecycle stage icon colors don't match up with the sketches, but they match up with what we currently have in the app. If we change them, we should change them together.
- This implementation does not contain the "Flag lifecycle" header or the "view graphs" link.
> 1-3059: add initial visuals for lifecycle summary

- website/docs/feature-flag-tutorials/flutter/a-b-testing.md
Remove a sentence from the Flutter tutorial that links to itself: **[Flutter Tutorial](https://unleash-docs-git-melinda-fix-flutter-link-unleash-team.vercel.app/feature-flag-tutorials/flutter/a-b-testing)**
> Remove referential link from the Flutter community tutorial

- frontend/src/component/events/EventTimeline/EventTimelineHeader/EventTimelineHeader.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyForm/FeatureStrategyForm.tsx
Fixes browser console warnings and errors related to the event timeline and strategy form.
- **Event Timeline**: Addressed a warning where the environment filter rendered with a default environment value (production) before environments were fully loaded.
- **Strategy Form**: Resolved an error caused by forwarding the enabled prop as a boolean.
> fix: console warnings and errors related to event timeline and strategy form

- .github/workflows/dependency-review.yml
- website/sidebars.ts
Due to our use of docusaurus and the openapi plugin we need to allow Artistic-2.0, Having read the license, it allows for free use of the licensed code, provided the license is included when distributing, but does not require a relicensing of products using the licensed code.
> task: explicitly allows Artistic-2.0 license

- .github/workflows/build_doc_prs.yaml
- website/docs/feature-flag-tutorials/flutter/a-b-testing.md
- website/docusaurus.config.ts
Add the lastmod value to our sitemap using docusaurus presets.
[Preview of the sitemap](https://unleash-docs-git-melinda-sitemap-unleash-team.vercel.app/sitemap.xml)
> Add lastmod to sitemap

- frontend/cypress/integration/demo/demo.spec.ts
- frontend/cypress/integration/feature/feature.spec.ts
- frontend/cypress/support/UI.ts
- frontend/src/component/common/VerticalTabs/VerticalTab/VerticalTab.tsx
- frontend/src/component/common/VerticalTabs/VerticalTabs.tsx
- frontend/src/component/demo/demo-topics.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanel.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/NewFeatureOverviewEnvironment/FeatureOverviewEnvironmentBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/NewFeatureOverviewEnvironment/FeatureOverviewEnvironmentToggle.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/NewFeatureOverviewEnvironment/NewFeatureOverviewEnvironment.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectSettings.tsx
https://linear.app/unleash/issue/2-2826/enabling-environment-via-feature-flag-environment-section-header
https://linear.app/unleash/issue/2-2825/feature-flag-list-bottom-left-to-be-a-nav-section
Follow-up to: https://github.com/Unleash/unleash/pull/8663
Implements most of the remaining work for our flag overview page redesign.
Most of the code you see is a straight copy/paste from our older existing components, with the slight improvement here and there.
Includes some improvements to our vertical tabs component to suit our use case. 
Also updates the Demo flow accordingly. I did some manual tests and it seems to work decently in both scenarios, whether `flagOverviewRedesign` is enabled or not. The demo needs some love but that's a story for a different PR and a different time.
Once again, …
> chore: flag overview page redesign - environments

- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/FeatureToggleCell/FeatureToggleCell.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
Archived toggles will not show switch anymore, but a dash.
> feat: archived toggles do not show switch

- src/lib/features/project-status/project-lifecycle-summary-read-model.test.ts
- src/lib/features/project-status/project-lifecycle-summary-read-model.ts
- website/docusaurus.config.ts
This PR adds more tests to check a few more cases for the lifecycle calculation query. Specifically, it tests that:
- If we don't have any data for a stage, we return `null`.
- We filter on projects
- It correctly takes `0` days into account when calculating averages.
> tests: add more tests for the lifecycle avg calculation query

- src/lib/features/project-status/project-lifecycle-summary-read-model.test.ts
- src/lib/features/project-status/project-lifecycle-summary-read-model.ts
This PR adds the next query to the lifecycle read model: how many flags are in each stage.
> 1-3085: count flags in each stage

- frontend/src/component/filter/AddFilterButton.tsx
- src/lib/features/maintenance/maintenance-service.ts
The archived functionality has been moved into the feature list, and we are showing a tooltip. However, it doesn’t make sense to display it to new customers, as they wouldn’t be familiar with the previous behavior.
I've introduced a "new/old user" classification, where I’m setting 08.11.2024 as the dividing line. All customers created after 08.11.2024 will be considered new, and we won’t display the tooltip for them. Everyone else will be treated as old customers.
This approach means there will be a brief period from 08.11.2024 until the release date where any customers created during this time will be categorized as new, even if they still have access to the old archive. For simplicity, I’m willing to accept this risk, as it's likely that in 95% of cases, for those few customers (0–10), …
> feat: remove archive tooltip conditionally

- frontend/src/component/demo/demo-topics.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureReleasePlanCard/FeatureReleasePlanCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
- frontend/src/hooks/api/getters/useReleasePlanTemplates/useReleasePlanTemplates.ts
- frontend/src/hooks/usePlausibleTracker.ts
- frontend/src/utils/strategyNames.tsx
https://linear.app/unleash/issue/2-2817/expand-the-strategy-dropdown-with-release-plan-templates
Does what it says on the tin, lists release plan templates in the strategy popover.
I think we should improve this popover soon, at least behind the `flagOverviewRedesign` flag, but not in this PR.
> chore: list release templates in strategy popover

- src/migrations/20241111085745-release-plan-template-permissions.js
Due to the cascade on the permission in role_permission, the down migration does not need to remove the rows from role_permission.
> task: added migration for release plan template permissions

- src/lib/features/project-status/createProjectStatusService.ts
- src/lib/features/project-status/project-status-service.ts
- src/lib/features/project-status/projects-status.e2e.test.ts
- src/lib/openapi/spec/project-status-schema.ts
This PR hooks up the project lifecycle summary read model to the service and exposes the lifecycle summary data in the controller.
> feat(1-3085): hook up lifecycle read model data to endpoint

- website/docs/feature-flag-tutorials/use-cases/a-b-testing.md
Fix a minor misalignment in the AB testing doc => Value is a property of the payload, not of the variant.
> Move value to be a property of payload, not variant

- frontend/src/component/project/Project/ProjectStatus/ProjectActivity.tsx
Now the label for total activities is more correct.
> feat: define activity labels

- frontend/src/component/filter/AddFilterButton.tsx
Now when pressing on new feature or import button, the tooltip will stay in background.
> feat: now tooltip will not be over the main content

- frontend/src/component/project/Project/ProjectStatus/ProjectLifecycleSummary.tsx
Handle a couple edge cases related to project lifecycle metrics:
1. If the average time spent was less than a day, we'd show "0 days". Now we show "less than a day" instead.
2. If the number of flags grows very large, it'd start pushing out the lifecycle icon. Instead, we now format in nicely.
Before:
After:
> chore: handle edge cases

- src/lib/db/user-store.ts
- src/migrations/20241112113555-user-email-hash.js
- src/test/e2e/api/admin/user-admin.e2e.test.ts
Adding email_hash column to users table.
We will update all existing users to have hashed email. 
All new users will also get the hash.
We are fine to use md5, because we just need uniqueness. We have emails in events table stored anyways, so it is not sensitive.
> feat: email will be stored hashed now for all users

- frontend/src/component/project/Project/ProjectStatus/ProjectLifecycleSummary.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectStatusModal.tsx
This PR fixes three minor UI issues:
1. The modal is too wide. Turns out that `SidebarModal` has a fixed width of 1300. `DynamicSidebarModal` does not, so that switch makes it much leaner.
2. The lifecycle boxes should grow in width to fill whatever space they have available. 
3. If you have 1 flag in any of the stages, we should say "1 flag" instead of "1 flags".
Sidebar before:
Sidebar after:
The lifecycle boxes at their very widest:
> 1-3095: small UI tweaks sidebar boxes

- frontend/src/component/project/Project/ProjectStatus/ProjectHealth.tsx
- src/lib/features/project-status/project-status-service.ts
- src/lib/features/project-status/projects-status.e2e.test.ts
This PR rounds the average health score we show for a project. With fractional numbers, it'd often overflow the graph. It also doesn't really give you much extra info, so we can round it. The rounding is then used both in the text, in the graph, and to calculate the graph fill percentage.
Before:
After:
> 1-3093: round the project health

- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
- frontend/src/component/releases/ReleasePlanTemplate/CreateReleasePlanTemplate.tsx
- frontend/src/hooks/api/actions/useReleasePlanTemplatesApi/useReleasePlanTemplatesApi.ts
Create a new release template with name and description
Redirects to edit page for template and pops up a toast message
> feat: frontend initial page for creating release templates

- frontend/src/component/project/Project/ProjectStatus/LifecycleMessages.ts
- frontend/src/component/project/Project/ProjectStatus/ProjectLifecycleSummary.tsx
This PR is a preparation for adding lifecycle comments. It turns the Lifecycle boxes into buttons, using MUI's [`CardActionArea`](https://mui.com/material-ui/api/card-action-area/) component, and allows you to select one at a time.
I'm not convinced about the a11y of this approach, but it appears to be in line with what MUI suggests, so ...
I'll add the speech bubbles in a follow-up.
> chore: prepare for lifecycle comments

- frontend/src/component/project/Project/ProjectStatus/LifecycleMessages.ts
- frontend/src/component/project/Project/ProjectStatus/ProjectLifecycleSummary.tsx
This pr adds tooltips to lifecycle boxes when they're hovered or focused. There's also some small copy tweaks.
We decided to go with tooltips instead of buttons for this iteration because it'd be an easier thing to implement, especially in regards to keyboard navigation and avoiding overlapping other elements. 
I've also not changed the background color of the tooltips just yet. There's two reasons for this:
1. The practical reason is that our `HtmlTooltipComponent` doesn't allow you to do that and I didn't wanna start messing about with that.
2. If all our other tooltips follow this color scheme, why not do the same here? Especially because they're not buttons anymore, so using the same color as other tooltips seems sensible.
> feat: add tooltips to lifecycle boxes

- src/lib/metrics.test.ts
- src/lib/metrics.ts
We have the licensed users service implemented, this just spread the data to prometheus.
> feat: prometheus now gets licensed users data

- src/lib/db/session-store.ts
- src/lib/services/session-service.ts
- src/test/e2e/services/session-service.e2e.test.ts
- src/test/e2e/services/user-service.e2e.test.ts
Method that queries sessions for users returns empty array when no sessions. Previously it was throwing an error. Since it's not an exceptional scenario returning an empty list seems to be less surprising at call site (especially with a list semantics on the return side). 
Note: this method was used only in tests and my new code that I currently work on. The method is not used in the enterprise repo.
> refactor: sessions for user without error

- src/lib/db/session-store.ts
- src/lib/openapi/spec/user-schema.ts
- src/lib/services/session-service.ts
- src/lib/services/user-service.ts
- src/lib/types/experimental.ts
- src/lib/types/stores/session-store.ts
- src/server-dev.ts
- src/test/e2e/api/admin/user-admin.e2e.test.ts
- src/test/fixtures/fake-session-store.ts
Show info on how many devices a user is logged in to an admin.
> Count active browser sessions per user

- frontend/src/component/project/Project/ProjectStatus/ProjectHealth.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectResources.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectStatusModal.tsx
- frontend/src/component/project/Project/ProjectStatus/StaleFlags.tsx
This PR adds the stale flag component to the health grid. In doing so, it also reworks the layout of the health row (now a grid) and updates the health component.
In addition to removing the text from the component, I have adjust the SVG a bit to make it not shrink on smaller screens and have adjusted it's spacing, so that it's not full of dead space at the bottom. This makes it easier to style because it doesn't add 15px of invisible content.
This PR also touches up a few other visual issues I found, such as header level and sidebar width.
Wide:
Medium:
Narrow:
> feat: Add stale flags counter

- frontend/src/component/user/HostedAuth.tsx
- frontend/src/component/user/PasswordAuth.tsx
- frontend/src/hooks/api/actions/useAuthApi/useAuthApi.tsx
- frontend/src/openapi/models/userSchema.ts
- src/lib/openapi/spec/user-schema.ts
- src/lib/services/session-service.ts
- src/lib/services/user-service.ts
- src/lib/types/user.ts
- src/test/e2e/services/user-service.e2e.test.ts
After log in we show a toast telling user that they were logged out of stale sessions
Next steps:
* add tests for toast
> feat: show deleted user sessions

- frontend/src/component/admin/billing/Billing.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingDashboard.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingInformation/BillingInformation.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingDetails.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingDetailsPAYG.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingDetailsPro.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingPlan.tsx
- frontend/src/component/admin/users/CreateUser/SeatCostWarning/SeatCostWarning.tsx
- frontend/src/component/demo/DemoDialog/DemoDialogPlans/DemoDialogPlans.tsx
- frontend/src/component/environments/EnvironmentTable/OrderEnvironments/OrderEnvironmentsDialog/OrderEnvironmentsDialogPricing/OrderEnvironmentsDialogPricing.tsx
- frontend/src/component/insights/componentsStat/UserSeats/UserSeats.test.tsx
- frontend/src/component/insights/componentsStat/UserSeats/UserSeats.tsx
- frontend/src/hooks/api/getters/useInstanceStatus/useInstanceStatus.ts
- frontend/src/hooks/useUsersPlan.ts
- frontend/src/interfaces/instance.ts
https://linear.app/unleash/issue/CTO-95/unleash-billing-page-for-enterprise-payg
Adds support for PAYG in Unleash's billing page.
Includes some refactoring, like splitting Pro and PAYG into different details components. We're now also relying on shared billing-related constants (see `BillingPlan.tsx`). This should make it much easier to change any of these values in the future. I already changed a few that were static / wrongly relying on instanceStatus.seats (we decided we're not doing that for now).
> chore: PAYG billing

- frontend/src/component/project/Project/ProjectStatus/StaleFlags.tsx
Builds on the backend code added in https://github.com/Unleash/unleash/pull/8751
This wires up the front end to use the data returned from the API
> 3111-1: Wires up stale data from the API

- frontend/src/component/project/Project/ProjectStatus/ProjectHealth.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectLifecycleSummary.tsx
This PR fixes a few small UI issues reported by UX. It:
- Adds hover colors to the lifecycle boxes
- Adjusts the font size for the health widget to match project resources and lifecycle
- Makes the `view health over time tooltip` take you to the insights page with the current project preselected
> fix: Project Status UI fixes

- frontend/src/component/common/InstanceStatus/InstanceStatusBar.tsx
My intuition wanted to click on it to start paying, but it did not work. Changed condition to show it for pay as you go.
> feat: now pay as you go billing banner has link

- frontend/src/component/project/Project/ProjectStatus/ProjectStatusModal.tsx
This change makes it so that the project status sidebar will close
when you follow a link within it. We do that by using JS event
bubbling and attaching a handler on the modal parent. We can listen
for events and check whether the target is an anchor and, if so, close
the modal.
> 1-3073: close sidebar when you click a link within it

- frontend/src/component/feedbackNew/FeedbackComponent.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectHealthGrid.styles.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectStatusModal.tsx
- frontend/src/hooks/useSubmittedFeedback.ts
This PR adds the feedback component to the project status page. When you open the feedback modal, we close the status sidebar. Exiting the feedback modal takes you back to the project page.
As a bonus: fixes the background color of the health grid, which was a little bit off.
> feat: add project status feedback

- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
- frontend/src/hooks/api/getters/useActionableChangeRequests/useActionableChangeRequests.ts
Refetch actionable change requests whenever you perform an action on a change request. This ensures that the change request notifications are up-to-date for you. Of course, it can still get out of sync if someone else performs an action on the change request, but that's more of an edge case.
> 1-3122: refetch CR notifs on actions

- frontend/src/component/project/Project/Project.tsx
The changes are:
- Change "Flags" to "Overview"
- Also hide "Insights" and "Health"
- Change "Project settings" to "Settings"
> 1-3125: Update project navigation for the simplified view

- frontend/src/component/admin/users/UsersList/UserSessionsCell/UserSessionsCell.tsx
- frontend/src/component/admin/users/UsersList/UsersList.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
> feat: show users with multiple parallel sessions

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureReleasePlanCard/FeatureReleasePlanCard.tsx
- frontend/src/hooks/api/actions/useReleasePlansApi/useReleasePlansApi.ts
Implements the addReleasePlan api call and invoking it from FeatureReleasePlanCard.
Invokes the release-plan add event even if the call fails
> feat: implement call to add release-plan to feature environment

- frontend/src/component/project/Project/ProjectStatus/ProjectResources.tsx
- frontend/src/hooks/api/getters/useProjectStatus/useProjectStatus.ts
- frontend/src/openapi/models/projectStatusSchemaResources.ts
- src/lib/features/project-status/project-status-service.ts
- src/lib/features/project-status/projects-status.e2e.test.ts
- src/lib/features/project/project-store-type.ts
- src/lib/features/project/project-store.ts
- src/lib/openapi/spec/project-status-schema.test.ts
- src/lib/openapi/spec/project-status-schema.ts
- src/test/fixtures/fake-project-store.ts
Remove everything related to the connected environment count for project status. We decided that because we don't have anywhere to link it to at the moment, we don't want to show it yet.
> 1-3120: remove project connected environments

- frontend/src/component/project/Project/ProjectStatus/ProjectHealth.tsx
This change swaps out the color of the health chart "unfilled" section
for `theme.palette.background.application`. This is the same color
that's used in the sketches, so it should apply better for dark mode.
Why? I noticed that the graph looks choppy in dark mode, so figured
I'd go and investigate. This update makes it look a lot smoother.
Light mode looks the same as before.
Before (notice the leaking light grey):
After:
> fix: use the correct design token color for the health chart background

- src/migrations/20241119103819-make-potentially-stale-non-nullable.js
This change adds a db migration to make the potentially_stale column
non-nullable. It'll set any NULL values to `false`.
In the down-migration, make the column nullable again.
> 1-3131: db migration to make potentially stale non-nullable

- frontend/src/component/releases/ReleasePlanTemplate/CreateReleasePlanTemplate.tsx
- frontend/src/component/releases/ReleasePlanTemplate/EditReleasePlanTemplate.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneList.tsx
- frontend/src/component/releases/ReleasePlanTemplate/ReleasePlanTemplateAddStrategyForm.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm.tsx
- frontend/src/component/releases/hooks/useTemplateForm.ts
- frontend/src/interfaces/releasePlans.ts
Adding and editing milestones and their names
> feat: create and edit release plan template milestones

- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOverviewFilters.tsx
- src/lib/features/feature-search/feature-search-store.ts
- src/lib/features/feature-search/feature.search.e2e.test.ts
This PR adds the option to select potentially stale flags from the UI.
It also updates the name we use for parsing from the API: instead of `potentiallyStale` we use `potentially-stale`. This follows the precedent set by "kill switch" (which we send as 'kill-switch'), the only other multi-word option that I could find in our filters.
> feat: add potentially stale filter to flags filter

- frontend/src/component/admin/roles/RoleForm/RolePermissionCategories/RolePermissionCategories.tsx
Hides config of release plan template permissions behind a feature flag.
It's not the prettiest, it checks the label of the section and checks the flag. Happy to take thoughts on improving this
Does not hide any of the template permissions in the permission explanation in the table from roles that have been configured with these permissions even if flag is false.
Enabled permissions do not get removed if re-saved after flag has been turned off
> chore: hide release plan template permissions behind feature flag

- src/migrations/20241119105837-licensed-users-backfill.js
- src/test/e2e/licensed-users-backfill.test.ts
**This migration introduces a query that calculates the licensed user counts and inserts them into the licensed_users table.** 
**The logic ensures that:**
1. All users created up to a specific date are included as active users until they are explicitly deleted.
2. Deleted users are excluded after their deletion date, except when their deletion date falls within the last 30 days or before their creation date.
3. The migration avoids duplicating data by ensuring records are only inserted if they don’t already exist in the licensed_users table.
**Logic Breakdown:**
**Identify User Events (user_events):** Extracts email addresses from user-related events (user-created and user-deleted) and tracks the type and timestamp of the event. This step ensures the ability to differentiate between user …
> feat: backfill licensed users

- frontend/src/hooks/api/actions/useReleasePlansApi/useReleasePlansApi.ts
Updates the addReleasePlanToFeature api action to use a payload with templateId in instead of url
Also changes the requestId to something more sensible
> chore: addReleasePlan api hook use template id in payload

- frontend/src/component/project/Project/ProjectStatus/ProjectHealth.tsx
This change updates the "view unhealthy flags" link in the project
status sidebar to use the correct filter. The previous link was put in
before we had a filter for potentially stale, so this updates the link
to use that filter.
> fix: link to unhealthy flags filter

- src/lib/domain/project-health/project-health.ts
- src/lib/features/project-status/project-status-service.ts
- src/lib/routes/admin-api/project/health-report.ts
- src/lib/services/project-health-service.ts
This PR:
- conditionally deprecates the project health report endpoint. We only use this for technical debt dashboard that we're removing. Now it's deprecated once you turn the simplifiy flag on.
- extracts the calculate project health function into the project health functions file in the appropriate domain folder. That same function is now shared by the project health service and the project status service.
For the last point, it's a little outside of how we normally do things, because it takes its stores as arguments, but it slots in well in that file. An option would be to make a project health read model and then wire that up in a couple places. It's more code, but probably closer to how we do things in general. That said, I wanted to suggest this because it's quick and easy (why do …
> chore: minor cleanup of project health and status

- src/server-dev.ts
Disables the experimental flag overview redesign locally when doing dev in OSS
> chore: disable flagOVerviewRedesign on OSS

- frontend/src/component/personalDashboard/FlagMetricsChart.tsx
This PR fixes an issue where the personal dashboard would fail to render if the flag was called `.` (Curiously, it was not an issue with `..`; probably because they end up accessing different URLs).
I've taken the very pragmatic approach here of saying "right, we know that `.` and `..` cause issues, let's just not even try to fetch data for them".
The option, of course, is to bake in more error handling in the components, but due to how we've got hooks depending on each other, it's a bit of a rabbit hole to go down. I think this is a good compromise for now.
So now, you'll get this instead:
I've also gone and updated the text for when we get a metrics fetching error, because this probably isn't due to the flag name anymore. If it is, we want to know.
> fix: don't break personal dashboard charts if the flag is called `.`

- frontend/src/component/project/Project/ProjectStatus/ProjectHealth.tsx
This change updates how the health widgets are aligned with their
text. They used to be aligned towards the top; now, they're centered.
Before:
After:
> fix: center health widgets and text

- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingDetailsPAYG.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingDetailsPro.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingPlan.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/hooks/useTrafficData.test.ts
- frontend/src/hooks/useTrafficData.ts
https://linear.app/unleash/issue/2-2989/unleash-payg-auto-traffic-billing
Integrates auto traffic bundle billing with PAYG.
Currently assumes the PAYG traffic bundle will have the same `$5/1_000_000` cost as the existing Pro traffic bundle, with the same `53_000_000` included requests. However some adjustments are included so it's easier to change this in the future.
> chore: PAYG traffic bundles

- src/lib/features/project-status/project-lifecycle-read-model/project-lifecycle-summary-read-model.test.ts
- src/lib/features/project-status/project-lifecycle-read-model/project-lifecycle-summary-read-model.ts
This PR fixes three things that were wrong with the lifecycle summary count query:
1. When counting the number of flags in each stage, it does not take into account whether a flag has moved out of that stage. So if you have a flag that's gone through initial -> pre-live -> live, it'll be counted for each one of those steps, not just the last one.
2. Some flags that have been archived don't have the corresponding archived state row in the db. This causes them to count towards their other recorded lifecycle stages, even when they shouldn't. This is related to the previous one, but slightly different. Cross-reference the features table's archived_at to make sure it hasn't been archived
3. The archived number should probably be all flags ever archived in the project, regardless of whether …
> fix: count lifecycle more accurately

- frontend/src/component/project/Project/ProjectStatus/ProjectStatusModal.tsx
This PR improves handling of very narrow screens for the project status header:
- Add a right margin so that it won't overlap with the close button.
- Make it so the icon in the header doesn't shrink.
> fix: fix status sidebar top padding

- frontend/src/component/project/Project/Project.tsx
This way, we don't need to reload the entire project page just to
open/close it.
Will probably resolve the performance issues.
> 1-3144: extract project status into own component.

- frontend/src/component/admin/users/UsersHeader/LicensedUsersBox.tsx
- frontend/src/component/admin/users/UsersHeader/UsersHeader.tsx
This PR fixes the isOss check for the licensed users component. It also addresses two things in the UI:
1. It right-aligns the text on the button so that when we get narrower, the text doesn't slide to the center. There's a few more things that we can fix later, though. When you press it, it'll still show the entire button layout:
And when you focus it with a keyboard it still looks like a button. 
We can get around that by using a regular button and just styling it a bit, but making the text align will take some extra jimmying around (not done in this pr, but got stashed changes for it)
But this is what it'd look like now with centered text: 
2. It wraps the entire left column in a `p` tag, because they belong together. They're not two logical paragraphs. So instead, we wrap them in …
> fix: isOss check + minor UI things

- src/lib/openapi/validate.ts
This change opens up the possibility of using the "date" format for
strings in our OpenAPI spec. According to the official docs, [`date` is
a built-in string format](https://swagger.io/docs/specification/v3_0/data-models/data-types/#string-formats).
> chore: allow openapi "date" format of strings

- frontend/src/component/releases/ReleasePlanTemplate/MilestoneCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneList.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyMenuCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyMenuCards.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm.tsx
- frontend/src/interfaces/releasePlans.ts
Adds a dropdown for selecting which strategy type to add to the milestone
> feat: selector dropdown for milestone new strategy

- frontend/src/component/admin/users/UsersHeader/LicensedUsersChart.tsx
- frontend/src/component/admin/users/UsersHeader/LicensedUsersSidebar.tsx
- frontend/src/component/admin/users/UsersHeader/UsersHeader.tsx
- frontend/src/component/insights/components/LineChart/LineChartComponent.tsx
- frontend/src/component/insights/components/LineChart/createChartOptions.ts
- frontend/src/hooks/useLicensedUsers.ts
Currently showing 2 lines, because backend is not sorting the data.
> feat: licensed users chart

- frontend/src/component/releases/ReleasePlanTemplate/MilestoneCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneList.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm.tsx
- frontend/src/component/releases/hooks/useTemplateForm.ts
- frontend/src/interfaces/releasePlans.ts
Tracks changes using milestoneId and not index. creates a new temp id for new milestones
> chore: switch to using milestoneId instead of index

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx
When deleted strategy has variants show the deleted variants
> feat: deleting strategy variants indicator

- src/migrations/20241125080935-add-unique-idx-to-release-plan-discriminator.js
We want to prevent our users from defining multiple templates with the same name. So this adds a unique index on the name column when discriminator is template.
> task: added unique index for release plan templates

- frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx
No matter if you go back to the closed change requests from the change request itself or when you navigate to change requests table from the nav we should always remember your last selection of the change request type tab. What it means is that we check query param first and then local storage what was the last change request type (open | closed) selected.
> fix: keep change request type in table

- frontend/src/component/project/Project/ProjectStatus/ProjectLifecycleSummary.tsx
This change updates the stat for archived flags "this month".
Turns out we were accessing the wrong property on the data object.
Additionally, changes the label to say "last 30 days" instead of "this
month"  because that's more accurate.
> fix: show data for last 30 days where we say we do

- src/lib/addons/__snapshots__/feature-event-formatter-md.test.ts.snap
- src/lib/addons/feature-event-formatter-md-events.ts
- src/lib/addons/feature-event-formatter-md.test.ts
- src/lib/addons/slack-app-definition.ts
- website/docs/reference/integrations/slack-app.mdx
- Add `PROJECT_ARCHIVED` event on `EVENT_MAP` to use
- Add a test case for `PROJECT_ARCHIVED` event formatting 
- Add `PROJECT_ARCHIVED` event when users choose which events they send to Slack
- Fix Slack integration document by adding `PROJECT_ARCHIVED`
The example message looks like the image below. I covered my email with a black rectangle to protect my privacy 😄 
The link refers `/projects-archive` to see archived projects.
I considered the reason why Unleash didn't implement to send `PROJECT_ARCHIVED` message to Slack integration.
One thing I assumed that it is impossible to create a new project with open source codes, which means it is only enabled in the enterprise plan. However, [document](https://docs.getunleash.io/reference/integrations/slack-app#events) explains that users can …
> feat: Add PROJECT_ARCHIVED event to send message to Slack

- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyTitle.tsx
- frontend/src/component/releases/ReleasePlanTemplate/ReleasePlanTemplateAddStrategyForm.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm.tsx
Adding tabs and submit/save button to add strategy form
> chore: milestone strategy tabs

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureReleasePlanCard/FeatureReleasePlanCard.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentFooter/EnvironmentFooter.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/SectionSeparator/SectionSeparator.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/NewFeatureOverviewEnvironment/FeatureOverviewEnvironmentBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestone.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestoneStrategy.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanRemoveDialog.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneList.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyMenuCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyMenuCards.tsx
- frontend/src/component/releases/ReleasePlanTemplate/ReleasePlanTemplateAddStrategyForm.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm.tsx
- frontend/src/hooks/api/actions/useReleasePlansApi/useReleasePlansApi.ts
- frontend/src/hooks/api/getters/useReleasePlans/useReleasePlans.ts
- frontend/src/interfaces/releasePlans.ts
- frontend/src/utils/strategyNames.tsx
https://linear.app/unleash/issue/2-2816/add-release-plan-to-feature-flag-from-release-template
https://linear.app/unleash/issue/2-2818/list-release-plan-with-milestones-in-feature-flag-environment-section
https://linear.app/unleash/issue/2-2819/removing-release-plan-from-feature
Implements the release plan flow in the feature flag environment.
You can now manage release plans in a feature flag environment by adding or removing them, as well as start milestones.
https://github.com/user-attachments/assets/24db9db4-7c3a-463e-b48a-611358f2b212
> chore: release plans flow in flag environments

- frontend/cypress/integration/feature/feature.spec.ts
https://linear.app/unleash/issue/2-3028/fix-create-feature-flag-e2e-test
Fixes our failing [create feature e2e test](https://github.com/Unleash/unleash/actions/runs/12027120576/job/33527490303?pr=8843).
We were looking for the feature flag name in the URL, not the DOM. Previously, whenever we created a new feature flag, this would automatically redirect us to that flag's page. This is no longer the case if you use the "Create flag" button you see in the onboarding header, which is the one the test is now using.
I agree it makes sense not to redirect in this case, but the test should be adapted accordingly, and instead look for the feature flag name in the table.
> test: fix feature e2e test by checking flag name in a td instead of url

- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyConstraints.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategySegment.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategySegmentList.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyType.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyTypeFlexible.tsx
- frontend/src/component/releases/ReleasePlanTemplate/ReleasePlanTemplateAddStrategyForm.tsx
Adds different types of strategies and their properties to the strategy-add/edit dialog, along with constraints and segments
> feat: release plan template strategy types, constraints, segments

- src/migrations/20241127074206-milestone-strategy-title-nullable.js
Adds a migration that makes title property of milestone strategies nullable
> chore: make milestone_strategies.title nullable

- frontend/src/component/admin/billing/BillingDashboard/BillingInformation/BillingInformation.tsx
- frontend/src/interfaces/instance.ts
https://linear.app/unleash/issue/2-3030/improve-the-billing-page-behavior-for-instances-with-custom-billing
Adapts the billing page to support custom billing scenarios.
Here’s how it will appear in such cases (notice a new "Your billing is managed by Unleash" text, with no visible button to update billing information):
> chore: adapt billing page to custom billing scenarios

- frontend/src/component/admin/users/InviteLinkBar/InviteLinkBar.tsx
- frontend/src/component/admin/users/InviteLinkBar/InviteLinkBarContent.tsx
- frontend/src/component/admin/users/UsersHeader/LicensedUsersBox.tsx
- frontend/src/component/admin/users/UsersHeader/UsersHeader.tsx
This PR throws in a number of fixes to the UsersHeader's invite link and licensed users components:
- Change the border colors from the primary purple to being a standard border color
- Fix text / button wrapping in the invite link component. It now wraps such that the button goes onto the row below the text if it cannot fit on the same row. The text within the button will not wrap until it absolutely has to (and is on its own line).
- Fix the wrapping behavior of the licensed users box: the bottom row ("seats used 30 days" and "view graph over time") will now wrap at the same time as the other button in the other box.
- Fix some text sizes within the licensed users box
- Fix the button to look more like a link in the licensed users box
Most of it is pretty standard fare, but I've taken a …
> fix: user header layout on narrow screens

- frontend/src/component/project/Project/ProjectStatus/ProjectActivity.tsx
This PR adds a proper dark theme for the activity graph. We previously used the exact same theme for both light and dark modes.
Before:
After (different chart):
I'm also passing in the theme explicitly as the `colorScheme` property. Without that prop, the graph uses your system color scheme (according to the docs), which may not be the same as your Unleash theme color scheme.
A side effect of this, however, is that we're now getting small borders on the light theme dots. I haven't found a prop in the docs to control this, but I kinda like them.
Before:
After (different chart):
> fix: Use a proper dark theme for the activity graph

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.test.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx
- frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.tsx
- frontend/src/component/changeRequest/changeRequest.types.ts
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyExecution/StrategyExecution.tsx
Show correct title diff and payload diff (e.g. rollout %) when change request is applied
Previously we were always comparing title and payload against the current strategy. But after the strategy is applied there's no diff anymore. What's more when the strategy is updated in future we're diffing against a future value. This PR always looks at the snapshot for change request when the change request is applied.
I added tests showing both cases in detail. 
There will be another PR in the backend to take a snapshot when the CR is being applied. 
Also we should add snapshots for deleted strategies since so that we can show diffs for them after applying CRs.
Update: added delete strategies improvements and extract method refactor in this PR
> feat: Change request applied diff for update strategy

- frontend/src/component/admin/users/UsersHeader/LicensedUsersBox.tsx
This change adds actual data from the server to the licensed users box
in the users header.
It also extracts the open sidebar button into its own component so
that we don't re-fetch the data when we open the sidebar. That's the
same issue we've had with project status and project creation screens, etc.
> chore: add licensed user data to the licensed users box

- frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.test.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.test.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx
Test all variant change options in updateStrategy and deleteStrategy when CR is before applied state and after applied state
> test: strategy variant tests in CRs

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/SegmentChangeDetails.tsx
- frontend/src/component/changeRequest/ChangeRequest/SegmentTooltipLink.tsx
- frontend/src/component/changeRequest/changeRequest.types.ts
Changes:
* edit segment has the same View Diff as edit strategy
* removing snapshot from diff comparison. Segment snapshots broke diffs
Next PRs:
* take update segment snapshots on apply change request similarly to update strategy 
* add tests for this UI component
* consider removing delete segment CR visualization since we can only remove unused segments so CRs never take part in segments removal
> feat: view diff in edit segment CR

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.test.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx
Extract component for AddStrategy 
Also:
* added tests
* making diffing less magical (details inline)
> refactor: extract add strategy diff

- src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
- src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts
When you don't specify title on strategy create you get null stored in a DB.
However when reading it back for edit you get:
This is confusing since null got changed to empty string.
It also affects change request diffs:
I haven't changed the title but diff shows null to "" change
After this change when you edit strategy you get:
I was also considering turning nulls into removed fields in the read strategy response but current solution seems to be ok.
> fix: stop changing null to empty string when reading empty title

- frontend/src/component/admin/auth/OidcAuth/OidcAuth.tsx
- frontend/src/component/admin/auth/SamlAuth/SamlAuth.tsx
- frontend/src/component/admin/auth/SsoGroupSettings.tsx
- website/docs/reference/sso.md
- website/remote-content/edge-proxy.js
This PR contains two small fixes:
1. [SSO Overview](https://unleash-docs-git-docs-misc-quick-fixes-unleash-team.vercel.app/reference/sso): remove Google Authentication from the list of supported providers in the intro, as it has been deprecated.
2. [Unleash Proxy generated docs](https://unleash-docs-git-docs-misc-quick-fixes-unleash-team.vercel.app/reference/unleash-proxy): remove injected admonition containing tips. Proxy is now in maintenance mode, and we don't want other admonitions to distract from that message
> Remove admonitions from Proxy docs

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.test.tsx
- frontend/src/component/changeRequest/ChangeRequest/StrategyTooltipLink/StrategyTooltipLink.tsx
Backend does not guarantee segment order (segments are more like a set than a list) so very often in diff calculation we get those results even when no segments changed in the CR
After this fix we get info about no changes since we always sort segments before diffing
> fix: ignore segment order in diff calculation

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/NewFeatureOverviewEnvironment/FeatureOverviewEnvironmentBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestone.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestone/ReleasePlanMilestone.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestone/ReleasePlanMilestoneStatus.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestone/ReleasePlanMilestoneStrategy.tsx
- frontend/src/component/releases/ReleaseManagement/ReleasePlanTemplateCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/CreateReleasePlanTemplate.tsx
- frontend/src/component/releases/ReleasePlanTemplate/EditReleasePlanTemplate.tsx
https://linear.app/unleash/issue/2-3038/release-plans-misc-ux-improvements
Includes various UX improvements focused on release plans:
- **New milestone status:** Introduced a "Paused" status for milestones. A milestone is marked as "Paused" when it is active but the associated environment is disabled.  
- **Status display:** Paused milestones are labeled as "Paused (disabled in environment)" for clarity.  
- **Styling cleanup:** Removed unused disabled styling in the release plan component.  
- **Accordion stability:** Fixed visual shifting in milestone accordions when toggling.  
- **Strategy count:** Updated the "View Strategies" label to reflect the total number of strategies in the milestone.  
- **Edge case handling:** Improved rendering for milestones without strategies.  
- …
> chore: release plans small misc improvements

- frontend/src/component/common/PermissionButton/PermissionButton.tsx
- frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
https://linear.app/unleash/issue/2-3039/fix-the-tooltip-behavior-in-permission-buttons
Improves the tooltip behavior of our permission button component.
This is achieved by removing the extra `span` element that is wrapping the `Button` component.
The tooltip is not correctly aligned with the button. The lower section of the button is not clickable.
The tooltip is correctly aligned with the button. Every visible part of the button is clickable.
> fix: permission button tooltip behavior

- frontend/src/component/admin/users/UsersHeader/LicensedUsersBox.tsx
- frontend/src/component/admin/users/UsersHeader/LicensedUsersChart.tsx
- frontend/src/component/admin/users/UsersHeader/LicensedUsersSidebar.tsx
Changes "licensed users" to "seats used" as requested. Also slightly adjusts the copy a few other places.
> 1-3163: align copy to seats used and change in -> over

- website/docs/reference/api/legacy/unleash/admin/features-v2.mdx
Fixes a typo so we get a new hash
> docs: enviroment->environment

- src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
- src/migrations/20241128152334-features-view-filter-out-milestone-strategies.js
https://linear.app/unleash/issue/2-3033/filter-out-release-plan-milestone-strategies-from-admin-feature
Filters out milestone strategies from our `features_view`.
This felt like the most elegant way to address this, since it seems we only rely on this view to fetch the feature strategies in the admin UI.
```json
{
"name": "r-plan",
"type": "release",
"enabled": false,
"project": "default",
"stale": false,
"strategies": [
{
"name": "flexibleRollout",
"constraints": [
{
"values": [
"Portugal"
],
"inverted": false,
"operator": "IN",
"contextName": "country",
"caseInsensitive": false
},
{
"values": [
"Portugal",
"Norway"
],
"inverted": false,
"operator": "IN",
"contextName": "country",
"caseInsensitive": false
}
],
"parameters": {
"groupId": "newOverview",
"rollout": "100",
"stickiness": …
```
> chore: filter out milestone strategies in features_view

- frontend/src/hooks/useTrafficData.test.ts
This should make the test more consistent as we don't need to be super strict here.
Example of this failing: https://github.com/Unleash/unleash/actions/runs/12115287823/job/33773589104?pr=8900
> test: loosen up useTrafficData test

- frontend/src/component/feature/FeatureToggleList/FeatureToggleListActions/FeatureToggleActions.test.tsx
- frontend/src/component/feature/FeatureToggleList/FeatureToggleListActions/FeatureToggleListActions.tsx
- frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx
- frontend/src/component/project/Project/Project.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/features/export-import-toggles/export-import-controller.ts
- src/lib/features/export-import-toggles/export-import-permissions.e2e.test.ts
- src/lib/features/export-import-toggles/export-import.e2e.test.ts
- src/lib/types/experimental.ts
This PR removes all references to the `featuresExportImport` flag.
The flag was introduced in [PR #3411](https://github.com/Unleash/unleash/pull/3411) on March 29th 2023, and the flag was archived on April 3rd. The flag has always defaulted to true.
I think it's safe to remove now.
> 1-3060: remove features export import flag 

- frontend/src/component/layout/MainLayout/NavigationSidebar/IconRenderer.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateFormDescription.tsx
- frontend/src/utils/strategyNames.tsx
https://linear.app/unleash/issue/2-3042/update-release-plans-feature-icon
Updates the icon for the release plans feature.
> chore: update release plans icon

- frontend/src/component/events/EventTimeline/EventTimeline.tsx
- frontend/src/component/events/EventTimeline/EventTimelineEventGroup/EventTimelineEventCircle.tsx
- src/lib/addons/feature-event-formatter-md-events.ts
- src/lib/types/events.ts
https://linear.app/unleash/issue/2-3043/improve-release-plan-events-and-add-them-to-the-event-timeline
Improves release plan events and adds them to the event timeline.
This will break the events in Enterprise but that's okay, we can follow up with the Enterprise PR to fix them.
> chore: improve release plan events and add them to event timeline

- website/docs/reference/sdks/index.mdx
Updates our React Native / Expo community SDK entry from the deprecated **[@nunogois/proxy-client-react-native](https://github.com/nunogois/proxy-client-react-native)** to the new **[@nunogois/unleash-react-native](https://github.com/nunogois/unleash-react-native)**.
> docs: update React Native / Expo community SDK entry

- README.md
Proxy has been deprecated long ago and edge should be our main recommendation
> docs: switch recommendation from proxy to edge

- frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundCodeFieldset/PlaygroundCodeFieldset.tsx
This pull request enhances the Autocomplete component within the PlaygroundCodeFieldset to improve user interaction and visual clarity. 
Key updates include:
. Multiple Selections: Enabled multiple selections to allow users to choose more than one option.
. Tag Limitation: Implemented a tag display limit (limitTags={3}) to maintain a clean interface.
. Checkbox Integration: Added checkboxes to each option for better selection visibility.
These improvements aim to streamline the context selection process, making it more intuitive and user-friendly.
Closes: #8836 
. `frontend/src/component/playground/Playground/PlaygroundForm/PlaygroundCodeFieldset/PlaygroundCodeFieldset.tsx`: The main file where the Autocomplete component is updated.
. Are there any additional features or improvements that …
> Refactor Autocomplete component in PlaygroundCodeFieldset

- frontend/src/component/common/PermissionButton/PermissionButton.tsx
- frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
Follow-up to https://github.com/Unleash/unleash/pull/8882
The referenced PR caused an unintended behavior by making the button behave like a normal button would on certain parent containers. Previously, the span wrapper caused a side effect that restricted the button’s width, which we were relying on.
By setting some initial styling properties, this PR should hopefully satisfy both use cases.
> fix: permission button unintended full width behavior

- src/lib/features/client-feature-toggles/client-feature-toggle.controller.ts
- src/lib/features/client-feature-toggles/tests/client-feature-toggle.e2e.test.ts
- src/lib/types/experimental.ts
- src/test/e2e/api/client/feature.optimal304.e2e.test.ts
This adds a variant that allows us to control client refreshes in case of need.
> feat: add variant etag

- frontend/src/component/common/Table/FavoriteIconHeader/FavoriteIconHeader.tsx
- frontend/src/component/common/Table/cells/FavoriteIconCell/FavoriteIconCell.tsx
- frontend/src/component/project/Project/ProjectFeatureToggles/RowSelectCell/RowSelectCell.tsx
Adjust search favorite icon placement
but the the project table compact
> fix: adjust favorite icon placement

- src/lib/services/email-service.test.ts
Add header ability to add custom header to non-transactional email.
> feat(productivity-report): additional email headers test

- src/lib/services/email-service.test.ts
- src/lib/services/email-service.ts
- src/mailtemplates/productivity-report/productivity-report.html.mustache
Health rating has a color matching project status color
Details:
* mustache is a logic-less so had to move the logic into a function on the context object (https://github.com/janl/mustache.js?tab=readme-ov-file#functions)
> feat: health rating color in email

- .github/workflows/core-feature-alert.yml
- src/lib/features/client-feature-toggles/client-feature-toggle-service.ts
Adds a GH action that notifies us that core features were changed. The action listens on paths in the source code where our client api and frontend api are located. If there is a change to these files, we add a comment to the PR to review carefully and add principals and CTO as reviewers.
> feat: add core feature alert gh action

- frontend/src/component/admin/banners/Banners.tsx
- frontend/src/component/admin/maintenance/index.tsx
- frontend/src/component/admin/roles/RoleForm/RolePermissionCategories/RolePermissionCategories.tsx
- frontend/src/hooks/api/getters/useAuth/useAuthPermissions.ts
- frontend/src/interfaces/uiConfig.ts
- src/lib/features/maintenance/maintenance-controller.ts
- src/lib/types/experimental.ts
- src/lib/types/permissions.ts
- src/server-dev.ts
Custom root roles for changing maintenance mode state and banners.
Internal ticket: [CJUX-278](https://linear.app/unleash/issue/CJUX-278/[roles]-custom-root-roles-missing-admin-responsibilities)
> feat(cjux-278): maintenance root roles

- website/docusaurus.config.ts
The blocks with `diff` syntax didn't render correctly. This is a result of Docusaurus v3 [changing the included languages ](https://docusaurus.io/docs/migration/v3#prism-react-renderer-v20).
> docs: Fixed diff syntax

- src/lib/features/project/project-read-model.test.ts
- src/lib/features/project/project-read-model.ts
- src/migrations/20241211143944-events-index-project-feature-created.js
From 13 seconds to 0.1 seconds.
1. Joining 1 million events to projects/features is slow. **Solved by using CTE.**
2. Running grouping on 1 million rows is slow. **Solved by adding index.**
> fix: make project ui query optimized

- frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/ManageBulkTagsDialog.test.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/ManageBulkTagsDialog.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/TagTypeSelect.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/TagsInput.tsx
This PR fixes a bug wherein the list of tags to remove from a group of tags wouldn't be correctly updated.
- Add a console log line to  `frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/ManageBulkTagsDialog.tsx`'s `ManagebulkTagsDialog`. Log the value of the`payload` variable.
- Pick a flag with no tags.
- Add tag A -> before submitting, you should have one added tag and zero removed flags. After submitting, both should be empty.
- Now remove tag A -> before submitting, you should have one removed tag and zero added tag. After submitting, both should be empty
- Notice that removed flags hasn't been emptied, but still contains tag A.
- Now add tab B -> before submitting, you should have tag B in added and nothing in removed. Notice that tag A is still in removed. …
> fix(1-3173): clear "removed tags" when you bulk update tags

- package.json
- yarn.lock
My goal was to remove the "revalidator" dependency coming as a transitive dependency from db-migrate. Everything seems to still work on my machine...
> fix: remove unused vulnerable transitive dependency 'prompt'

- src/lib/features/client-feature-toggles/cache/client-feature-toggle-cache.ts
- src/lib/features/client-feature-toggles/cache/createClientFeatureToggleCache.ts
This feature is still in early alpha. We do not want to populate any cache on startup. We might not want to do it ever.
> fix: do not initialize cache when flag is off

- src/lib/features/client-feature-toggles/cache/client-feature-toggle-cache.ts
This PR changes the caching functionality so that we initialize the cache when we receive the first request instead of frontloading the caches.
> fix: initialize cache when we get the first request

- src/lib/features/client-feature-toggles/cache/client-feature-toggle-cache-read-model-type.ts
- src/lib/features/client-feature-toggles/cache/client-feature-toggle-cache-read-model.ts
- src/lib/features/client-feature-toggles/cache/client-feature-toggle-cache.ts
- src/lib/features/client-feature-toggles/cache/createClientFeatureToggleCache.ts
- src/lib/features/client-feature-toggles/tests/client-feature-toggles.e2e.test.ts
- src/lib/types/model.ts
This is based on the exising client feature toggle store, but some alterations.
1. We support all of the querying it did before.
2. Added support to filter by **featureNames**
3. Simplified logic, so we do not have admin API logic
- no return of tags
- no return of last seen
- no return of favorites
- no playground logic
Next PR will try to include the revision ID.
> feat: new read model for client feature toggle cache

- frontend/src/component/onboarding/dialog/ConnectSdkDialog.tsx
Fixes a bug where we'd call the project overview every second when on a project page.
The reason this happens is that the connect SDK dialog sets up a fetcher to re-fetch it every second. 
The request should only be fired when the dialog is open, but because of the way it's set up, we we're setting up the repeated fetch regardless of whether the dialog was open or not.
This PR moves the dialog and all it's content into a nested component that's only rendered if the dialog should be opened.
> fix: only call project overview from connect dialog when open

- frontend/src/component/releases/ReleasePlanTemplate/CreateReleasePlanTemplate.tsx
- frontend/src/component/releases/ReleasePlanTemplate/EditReleasePlanTemplate.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneList.tsx
- frontend/src/component/releases/ReleasePlanTemplate/ReleasePlanTemplateAddStrategyForm.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm.tsx
Milestone accordions no longer jump when opened and closed
The disturbing divider line is gone
Introduces an "edit mode" to the strategy, currently only affects button text.
You can now remove milestones from templates
Updates the text on the create/edit template save button
> Fix/template edit UI snags

- src/lib/features/client-feature-toggles/cache/client-feature-toggle-cache.test.ts
- src/lib/features/client-feature-toggles/cache/client-feature-toggle-cache.ts
- src/lib/features/client-feature-toggles/client-feature-toggle-service.ts
- src/lib/features/client-feature-toggles/client-feature-toggle.controller.ts
This is still raw and experimental.
We started to pull deleted features from event payload.
Now we put full query towards read model.
Co-Author:  @FredrikOseberg
> feat: deleted feature names should come from event

- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyType.tsx
resolves which component to load based on strategyName instead of name, as the former is always present
after switch
> fix: use strategyName instead of name property for component to load

- src/lib/db/client-applications-store.ts
According to some logs, sdks can be undefined:
```
TypeError: Cannot read properties of null (reading 'sort')\n    at /unleash/node_modules/unleash-server/dist/lib/db/client-applications-store.js:330:22\n 
```
> fix: can't sort on undefined sdks

- src/lib/features/client-feature-toggles/client-feature-toggle.controller.ts
- src/lib/metric-events.ts
- src/lib/metrics.ts
This PR adds prometheus metrics that allows us to see whether or not tags and namePrefix is used at all in our cloud offering.
> feat: add prom metrics

- src/lib/db/client-applications-store.ts
- src/lib/openapi/spec/application-environment-instances-schema.ts
We had some error logs, that when SDK is null, then the application overview query was failing.
This solves it
> fix: now null sdks will also be handled nicely

- src/lib/features/client-feature-toggles/client-feature-toggle-service.ts
- src/lib/features/client-feature-toggles/createClientFeatureToggleService.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta-controller.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta-read-model-type.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta-read-model.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.test.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
- src/lib/features/client-feature-toggles/delta/createClientFeatureToggleDelta.ts
- src/lib/features/client-feature-toggles/delta/revision-delta.test.ts
- src/lib/features/client-feature-toggles/delta/revision-delta.ts
- src/lib/routes/client-api/index.ts
- src/lib/types/model.ts
The cache is too generic, we will be using delta from now on.
> chore: rebrand cache to delta

- frontend/src/component/releases/ReleaseManagement/ReleaseManagement.tsx
- frontend/src/component/releases/ReleasePlanTemplate/CreateReleasePlanTemplate.tsx
- frontend/src/component/releases/ReleasePlanTemplate/EditReleasePlanTemplate.tsx
Hiding with enterprise tag in routes wasn't enough anymore as we're showing those to Pro with upgrade messages. This temporarily disables the UI completely.
Before
After
Also disables the create screen if you know the direct url:
> fix: check for enterprise in the create/edit templates UI

- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
- src/lib/features/client-feature-toggles/delta/createClientFeatureToggleDelta.ts
- src/lib/features/client-feature-toggles/tests/__snapshots__/client-feature-toggles.e2e.test.ts.snap
- src/lib/features/client-feature-toggles/tests/client-feature-toggles.e2e.test.ts
- src/lib/metric-events.ts
- src/lib/openapi/spec/client-features-delta-schema.ts
Now the delta endpoint also always returns all the segments.
> feat: segment delta

- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategyMenuCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneStrategySegmentList.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm.tsx
Changes the mouse pointer when selecting a strategy to add to milestone
Closes strategy edit when pressing esc or clicking outside
> feat:release templates strategy interaction improvements

- website/docs/feature-flag-tutorials/ruby/implementing-feature-flags-ruby.mdx
> docs: swapi.dev no longer exists

- frontend/src/component/events/EventLog/useEventLogSearch.ts
Default event log date range span is a 1 year moving window. Yesterday I set it to a month but it seems too short of a time period.
> chore: default event log span 1 year

- src/lib/features/client-feature-toggles/client-feature-toggle.controller.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
- src/lib/features/client-feature-toggles/delta/createClientFeatureToggleDelta.ts
- src/lib/features/client-feature-toggles/delta/revision-delta.ts
- src/lib/metric-events.ts
- src/lib/metrics.ts
When there is new revision, we will start storing memory footprint for old client-api and the new delta-api.
We will be sending it as prometheus metrics.
The memory size will only be recalculated if revision changes, which does not happen very often.
> feat: store memory footprints to grafana

- .github/workflows/docker_publish.yaml
We already have 20.18.1 set as the default in our Dockerfile, but we override it with an arg from the workflow, so this brings the workflow up to date with what we use as our default.
> chore: Use 20.18.1 instead of 20.14 as our node base image

- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestone/ReleasePlanMilestone.tsx
- frontend/src/component/releases/ReleasePlanTemplate/MilestoneCard.tsx
Removes the border from release plan in feature environment accordion, sets the milestone background to be white. fixes draggable grey-out indication. Changes milestone open-text to Hide/View depending on state of accordion
> feat: remove borders, improve draggable visibility etc

- src/lib/app.ts
- src/lib/routes/controller.ts
- src/lib/services/openapi-service.ts
I removed `idNumberMiddleware` and changed to use Open API validation process to validate path parameters in #8734 .
However, Express can't parse path parameters if they don't exist in the path, which is the first argument of the method such as `use`, hence it is impossible to parse them by using `useErrorHandler` method like the one below.
```TypeScript
useErrorHandler(app: Express): void {
// We need to pass a specific parameter such as `/:segmentId` as the first argument of the `use` method.
// ex. `app.use('/:segmentId/, (err, req, res, next) => { ... }`
app.use((err, req, res, next) => {
if (err?.status && err.validationErrors) {
const apiError = fromOpenApiValidationErrors(
req,
err.validationErrors,
);
res.status(apiError.statusCode).json(apiError);
} else {
next(err);
}
});
}
``` …
> fix: Change Open API validation middleware to specify and use path parameters

- package.json
- yarn.lock
Bump up unleash client with streaming client with no etag
> chore: streaming client no etag

- frontend/src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/LegalValueLabel/LegalValueLabel.styles.ts
- frontend/src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/RestrictiveLegalValues/RestrictiveLegalValues.tsx
Fixing styling of legal values in segments. 
Before
After
The styles are copied from a similar component we use in strategies.
The best long term solution would be using the same constraint accordion we have in strategies. Currently we use new accordion for strategies and old one for the segments. Now sure why the migration wasn't finished when we updates strategies. @FredrikOseberg do you know?
> fix: legal values styling in segments

- frontend/src/component/common/MultipleRoleSelect/MultipleRoleSelect.test.tsx
- frontend/src/component/common/MultipleRoleSelect/MultipleRoleSelect.tsx
Details:
* project roles and custom roles are grouped
* project roles (Owner,Member) always go first
* custom project roles are sorted alphabetically
* checkbox is aligned with top of the text
> feat: grouping of project level roles in autocomplete

- src/lib/features/client-feature-toggles/client-feature-toggle.controller.ts
Log out the diff and warn if there is gap between old logic and new delta.
> feat: log warning if there is diff between client/features and delta api

- frontend/src/component/common/UserAvatar/UserAvatar.tsx
https://linear.app/unleash/issue/2-3109/improve-avatar-tooltip
I noticed our current user avatar tooltip is a bit poor.
This PR tries to improve it a bit using only the data we already have available, without any drastic changes.
> chore: new user avatar tooltip

- frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCard.tsx
https://linear.app/unleash/issue/2-3111/improve-group-card-projects-tooltip
Slight improvement to the group card projects tooltip.
This handles very long project names a little bit better by allowing them to break into new lines.
> chore: improve group projects tooltip behavior

- src/lib/features/context/context-service.ts
- src/lib/features/context/context.test.ts
- src/lib/features/context/context.ts
- src/lib/services/context-schema.ts
Ability to add/update a single legal value for the context. 
Important decisions:
* since it allows to add a new legal value or update description of a single legal value I decided to go for the PUT method since we know the identity of the legal value (context name + legal value name combination is unique).
* in the event log I'm using the same CONTEXT_FIELD_UPDATED event instead of creating a new event for single legal value updates 
Addresses: https://github.com/Unleash/unleash/issues/8934
Followup PRs:
* add delete single legal value capability
* wrap all context updates in transactions since they touch context and event log
> feat: ability to upsert single legal values

- src/lib/features/client-feature-toggles/client-feature-toggle-service.ts
- src/lib/features/client-feature-toggles/delta/client-feature-delta-api.e2e.test.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta-controller.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta-read-model-type.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
- src/lib/openapi/spec/client-features-delta-schema.test.ts
- src/lib/openapi/spec/client-features-query-schema.test.ts
Our delta API was returning archived feature as updated. Now making sure we do not put `archived-feature `event into `updated` event array.
Also stop returning removed as complex object.
> fix: delta do not return archived as changed

- src/lib/features/feature-search/feature.search.e2e.test.ts
- src/lib/features/project/project-service.e2e.test.ts
- src/migrations/20241129102205-add-foreign-key-to-role-permissions.js
- src/test/e2e/helpers/database-init.ts
- src/test/e2e/services/access-service.e2e.test.ts
Creates a data migration that allows us to remove all hanging permissions tied to deleted environments. In addition, this migration adds a foreign key relationship to environment column that references environments name. See rationale [here](https://github.com/Unleash/unleash/pull/8271).
> feat: add migration

- frontend/src/component/admin/groups/GroupsList/GroupsList.tsx
https://linear.app/unleash/issue/2-3114/group-cards-should-have-a-consistent-height-in-their-grid
Makes the group cards height consistent in the grid.
> chore: make grid group cards have a consistent height

- package.json
- yarn.lock
Using https://github.com/Unleash/unleash-client-node/pull/690
> chore: upgrade node sdk with x-headers

- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneCard/MilestoneCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneCard/MilestoneCardName.tsx
Removes the darker background when the milestone name input is present and focused.
Clicking inside the milestone name input doesn't trigger the accordion.
Sizing tweaks to prevent content jumping around when editing milestone name
> chore: improve the accordion summary looks

- frontend/src/component/admin/auth/AuthSettings.tsx
- src/lib/types/experimental.ts
- src/lib/types/option.ts
https://linear.app/unleash/issue/2-3074/add-sign-in-with-google-to-our-hosted-instances-when-only-password-is
https://linear.app/unleash/issue/2-3078/allow-viewer-access-from-auth-app-for-payg
Adds support for a new unified hosted auth handler.
This new auth handler provides a Google sign in option in case you don't have an SSO provider configured. It also provides a way for auth-app to sign in with Unleash's read-only user for Pro and Enterprise PAYG instances.
Check the PR comments for more details.
> chore: new hosted auth handler

- src/lib/metrics.test.ts
- src/lib/metrics.ts
- src/lib/middleware/response-time-metrics.ts
- src/lib/types/experimental.ts
Enhancing request timing metrics with connection id (think instance id but guaranteed to be unique and handled internally by us). 
Details:
* I checked how appName was added in the first place: https://github.com/Unleash/unleash/pull/2117. Same tradeoffs apply here
* connection id is implemented here: https://github.com/Unleash/unleash-client-node/pull/690
* This is behind a flag to opt-into tracking and also it can be disabled with the killswitch for appName
* We have a new `x-unleash-appname` header that replaces `unleash-appname` but not all SDKs use it so we check both with preference given to the x-header
* I'm not using a new `x-unleash-sdk` header here to keep the metrics data as small as possible for now with the ability to track unique clients
Important:
* connection id has …
> feat: Unique connection tracking

- src/lib/metrics.test.ts
- src/lib/metrics.ts
- src/lib/middleware/response-time-metrics.ts
ConnectionId label could have very high cardinality: https://docs.victoriametrics.com/keyconcepts/#:~:text=By%20default%2C%20VictoriaMetrics%20limits%20label's,to%20a%20new%20time%20series
I keep the flag though for some other experiments in this area
> chore: remove connection id from tracking

- src/lib/types/experimental.ts
https://linear.app/unleash/issue/2-3106/clean-up-post-unified-auth-handler
Cleans up this flag that we never ended up using anyways.
> chore: remove unused newHostedAuthHandler flag

- frontend/src/component/admin/adminRoutes.ts
- frontend/src/component/admin/auth/AuthSettings.tsx
- frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
https://linear.app/unleash/issue/2-3124/mark-sso-as-an-enterprise-only-feature
For all intents and purposes, SSO seems to have always been an Enterprise only feature. It just wasn't very clear previously.
See: https://github.com/Unleash/unleash/pull/9045/files#r1899635618
> chore: mark SSO as an Enterprise only feature

- frontend/src/component/common/Table/cells/RoleCell/RoleCell.tsx
- frontend/src/component/project/ProjectAccess/ProjectAccessTable/ProjectAccessTable.tsx
Remove scrollbar in project settings - user roles
before:
after:
> fix: text overflow on project users access page

- src/migrations/20250109150818-unique-connections-table.js 
We need to store unique connections from SDKs.
The id will be current or previous string for current or previous hour. We only need to have 2 buckets for metrics reporting in grafana/victoriametrics.
The hll is hyperloglog bytes array used for the internal data structure of the HyperLogLog for unique connection tracking. We serialize it to a database because we want to have unique tracking across multiple pods. 
Extracted this migration from a bigger PR: https://github.com/Unleash/unleash/pull/9074
Actual usage of the byte array serialization/deserialization is shown here: https://github.com/Unleash/unleash/pull/9074/files#diff-309cb0c2c562243279e6a15f9d9d7f4ddd33ae6ba526016e1e1b708209ecb877R27
> feat: migration for unique connections

- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/TemplateForm.tsx
Improves the looks of the name and description fields of creating release-templates
> chore: improve create template fields for name+description

- frontend/src/component/releases/ReleasePlanTemplate/EditReleasePlanTemplate.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneCard/MilestoneCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneStrategy/ReleasePlanTemplateAddStrategyForm.tsx
- Add strategy button doesn't break up in narrower UIs
- Added description + docs link to add/edit strategy
- Fixed broken up text in segmentation/constraints UI
> chore: fix smaller broken UI things in release templates

- src/lib/features/client-feature-toggles/tests/client-feature-toggles.e2e.test.ts
- src/lib/types/experimental.ts
- src/test/e2e/api/admin/api-token.auth.e2e.test.ts
- src/test/e2e/api/admin/api-token.e2e.test.ts
Admin tokens have been [deprecated in previous versions](https://docs.getunleash.io/reference/api-tokens-and-client-keys#admin-tokens) encouraging the usage of personal access tokens for better traceability of changes within Unleash.
This removes the ability of creating them from the API
> feat: Remove create admin token from API

- src/lib/addons/__snapshots__/feature-event-formatter-md.test.ts.snap
- src/lib/addons/feature-event-formatter-md-events.ts
- src/lib/addons/feature-event-formatter-md.test.ts
We got an event for a scheduled application success today that looked a little something like this:
> Successfully applied the scheduled change request #1168 in the production environment in project eg by gaston in project eg.
Notice that we're stating the project twice (once with a link (removed here) and once without).
This PR removes the redundancy in CR events:
The project is already included in the `changeRequest` variable, which
is populated in `src/lib/addons/feature-event-formatter-md.ts` by
the `generateChangeRequestLink` function.
The (current) definition is:
```typescript
generateChangeRequestLink(event: IEvent): string | undefined {
const { preData, data, project, environment } = event;
const changeRequestId =
data?.changeRequestId || preData?.changeRequestId;
if (project && …
```
> fix(1-3247): remove explicit "in project" text from change request event text

- renovate.json
Hello, this is my first contribution here.
The last Renovate configuration was done 10 months ago and Renovate changed the configuration schema during this time. I made some schema changes for you. 
:point_right: When I was searching issues to work on, I noticed that renovate PRs are not labeled and this makes hard to filter dependency update PRs. I added global 'dependencies' label to all Renovate PRs, which is also used for Dependabot.
- Add JSON schema | A JSON best practice for working with structured datas.
- Migrate deprecated packageRules to new versions
- Rename `stabilityDays` to `minimumReleaseAge` | This is basically a modern version of #2768
- Rename `matchPackagePatterns` to `matchPackageNames`
- Add 'dependencies' label to renovate PRs
- …
> chore(renovate): Update renovate configuration json file

- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneCard/MilestoneCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneList.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneStrategy/ReleasePlanTemplateAddStrategyForm.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/TemplateForm.tsx
Refactor that moves strategy form into milestone card component, and tracks milestone expanded state so we can open it when adding strategies to it
> chore: move strategy UI into milestonecard and open milestone when adding strategy to it

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
Adds a text in the environment strategy separator between release plans and normal strategies that reads "Additional strategies"
> chore: feature release plans other strategies indicator

- src/lib/features/client-feature-toggles/client-feature-toggle-store.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta-read-model.ts
- src/lib/features/export-import-toggles/export-import-service.ts
- src/lib/features/feature-toggle/converters/feature-toggle-row-converter.ts
- src/lib/features/feature-toggle/feature-toggle-controller.ts
- src/lib/features/feature-toggle/feature-toggle-service.ts
- src/lib/features/feature-toggle/feature-toggle-store.ts
- src/lib/features/feature-toggle/feature-toggle-strategies-store.ts
- src/lib/types/model.ts
- src/lib/util/sortStrategies.test.ts
- src/lib/util/sortStrategies.ts
https://linear.app/unleash/issue/2-3100/sorting-issues-with-milestone-strategies-and-regular-strategies
This PR ensures that milestone strategies are always prioritized and evaluated before regular strategies. It ensures that the order displayed in the UI matches the internal evaluation order.
> chore: prioritize milestone strategies in sorting

- src/lib/features/dependent-features/dependent-features-service.ts
- src/lib/features/dependent-features/dependent.features.e2e.test.ts
Currently, every time you archived feature, it created feature-dependencies-removed event.
This PR adds a check to only create events for those features that have dependency.
> fix: feature-dependencies-removed event should not be created always

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyExecution/StrategyExecution.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestone/ReleasePlanMilestoneStrategy.tsx
Adds a condition `displayGroupId` to StrategyExecution that toggles showing group id in the rollout section
Enables `displayGroupId` in the feature release plan strategy-view
> feat: conditionally show groupId in StrategyExecution under rollout

- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanRemoveDialog.tsx
Only shows the active milestone warning in the delete release plan dialog if the feature environment is enabled
> chore: make remove release plan warning conditional on env. enabled

- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
The feature was getting into updated array due to feature-deleted event.
> fix: remove deleted event from being update event

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.test.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/FeatureLifecycleTooltip.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureLifecycle/LifecycleStage.tsx
New tooltips for lifecycle indicators.
- removed "timeline" lifecycle explanation
- new descriptions
- changed tooltip footer colors
- refactored "environments" section
> feat: update lifecycle tooltip style

- frontend/src/hooks/useTrafficData.ts
Dates are hard. For a lot of timezones new Date(Date.parse('2025-01-01T00:00:00.000Z')).getDate() could be returned as 31 and not 1
By using getUTCDate instead we now adjust accordingly and return the right day number.
> chore: fix traffic data timezone visualization issue with getUTCDate

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
This PR updates the tooltip date display in the traffic usage chart to use the user's chosen locale settings, falling back to en-US if the settings are unavailable or otherwise unset.
So, for instance, if I have set my locale to "ja-JP", I'd get this instead of the en US format:
> chore(1-3267): use the user's locale settings for formatting the tooltip date

- src/lib/__snapshots__/create-config.test.ts.snap
- src/lib/create-config.ts
- src/lib/services/user-service.ts
- src/lib/types/experimental.ts
- src/lib/types/option.ts
- src/test/e2e/services/user-service.e2e.test.ts
- website/docs/using-unleash/deploy/configuring-unleash.mdx
Removing deleteStaleUserSessions flag and introducing MAX_PARALLEL_SESSIONS config with env var.
Defaults:
* 100 for enterprise (considered undefined but a very high number leads to simpler code without special cases)
* 5 for pro and OSS
Self-hosted enterprise and OSS can override the env var.
What's the main use case for this env var? 1 parallel session enforcement for security purposes
> feat: max parallel sessions config

- frontend/src/component/admin/network/NetworkTrafficUsage/PeriodSelector.tsx
Fixes an issue where the buttons would be illegible in dark mode
because we don't set the color explicitly. It just happened to work in
light mode.
> fix: specify colors for buttons

- frontend/src/component/admin/network/NetworkTrafficUsage/PeriodSelector.tsx
Adds the same hover color as for the sidebar. Also adds a transition animation.
> fix: add a hover color for buttons in the period selectors.

- src/lib/features/traffic-data-usage/fake-traffic-data-usage-store.ts
- src/lib/features/traffic-data-usage/traffic-data-usage-store-type.ts
- src/lib/features/traffic-data-usage/traffic-data-usage-store.test.ts
- src/lib/features/traffic-data-usage/traffic-data-usage-store.ts
Add support for querying the traffic data usage store for the aggregated data for an arbitrary number of months back.
Adds a new `getTrafficDataForMonthRange(monthsBack: number)` method to the store that aggregates data on a monthly basis by status code and traffic group. Returns a new type with month data instead of day data.
> feat(1-3260): store support for data traffic from a range

- website/docs/reference/project-collaboration-mode.md
This PR fixes header levels in the Project Collaboration doc. The page now renders the title and other headings as expected.
Preview link: https://unleash-docs-git-melinda-fix-project-collab-40917f-unleash-team.vercel.app/reference/project-collaboration-mode
> Project collaboration mode docs: fix header levels

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureReleasePlanCard/FeatureReleasePlanCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanAddChangeRequestDialog.tsx
Displays a dialogue for user to confirm adding changes to draft when user adds release-plan to change request enabled feature environment.
Currently does nothing more than display a success toast when confirmed, pending remaining change request implementation
> feat: show a dialog when adding a release plan to a change request enabled feature environment

- website/src/css/custom.css
https://linear.app/unleash/issue/2-3191/align-table-of-contents-with-content
Vertically aligns the table of contents with the content, by adding some margin top.
> docs: align table of contents with content

- src/lib/routes/admin-api/api-token.test.ts
- src/lib/routes/admin-api/api-token.ts
- src/lib/types/experimental.ts
This was released with 6.6 and now this flag is no longer needed. The default value is already set to true, so it's the same as removing it
> chore: remove feature toggle kill switch for admin token UI

- src/lib/features/traffic-data-usage/fake-traffic-data-usage-store.ts
- src/lib/features/traffic-data-usage/traffic-data-usage-store-type.ts
- src/lib/features/traffic-data-usage/traffic-data-usage-store.ts
Add new methods to the store behind data usage metrics that accept date ranges instead of a single month. The old data collection methods re-route to the new ones instead, so the new methods are tested implicitly.
Also deprecates the new endpoint that's not in use anywhere except in an unused service method in Enterprise yet.
Should the new methods accept `from` and `to` as dates? Or as strings? If they're strings, there's a chance the parsing can go wrong, so dates feel safer to me.
There's *one* instance of a place where call the old daily data method (in `src/lib/features/instance-stats/instance-stats-service.ts`). Should we update that to use the new method? Should we keep the old one and have both?
> chore(1-3293): add new query for daily data that uses  date ranges

- src/lib/features/traffic-data-usage/fake-traffic-data-usage-store.ts
- src/lib/features/traffic-data-usage/traffic-data-usage-store-type.ts
- src/lib/features/traffic-data-usage/traffic-data-usage-store.ts
Correcting a slight oversight from when we created the new methods. This brings the name in line with the other store methods.
> fix:  correct name order -> traffic usage data -> traffic data usage

- frontend/src/component/App.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
- website/src/theme/Navbar/Content/styles.module.css
This PR sets up the application to accept a value from a variant we control to set the font size of the application on a global level. If it fails, the value falls back to the previously set CSS value.
> feat: configurable global font size

- website/src/css/custom.css
https://linear.app/unleash/issue/2-3200/update-docs-bottom-left-background-image-in-dark-mode
The background mountain texture was a bit too striking visually. We should set an opacity of `0.06` in dark mode, the same as in Unleash dark mode.
> docs: fix background img dark mode opacity

- src/lib/features/client-feature-toggles/client-feature-toggle.controller.ts
- src/lib/features/client-feature-toggles/delta/client-feature-delta-api.e2e.test.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta-types.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.test.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
- src/lib/features/client-feature-toggles/delta/delta-cache.test.ts
- src/lib/features/client-feature-toggles/delta/delta-cache.ts
- src/lib/features/events/event-store.ts
- src/lib/features/feature-toggle/configuration-revision-service.ts
- src/lib/features/segment/fake-segment-read-model.ts
- src/lib/features/segment/segment-read-model-type.ts
- src/lib/features/segment/segment-read-model.ts
- src/test/e2e/helpers/test-helper.ts
This is implementing the segments events for delta API. Previous version of delta API, we were just sending all of the segments. Now we will have `segment-updated` and `segment-removed `events coming to SDK.
> feat: segment implementation in delta

- frontend/src/component/project/Project/Project.styles.ts
- frontend/src/component/project/Project/Project.tsx
Fix an issue where tabs would fill out all available space, now it's left aligned: 
Previously:
> fix: tabs not growing to fill all available space

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/common/Chart/customHighlightPlugin.ts
This makes the width of the highlight bars in the network dynamic and based on the number of labels included in the chart.
Since the number of labels should always correspond to the number of data points, this seems like a sensible approach.
With this, the label width will now be calculated on the fly, so even if you resize the window or change the number of labels, the highlighting will still work as expected.
Daily view:
Monthly aggregate:
The labels are now a little narrower on the daily graphs, but it avoids them being super wide on the monthly graphs
> fix: dynamic highlight width

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/PeriodSelector.tsx
Wraps the datepicker in a popover, making it function largely the same as a dropdown list.
The dropdown displays one of:
- "current month" if you've selected the current month
- "<month> <year>" (e.g. "December 2024") if you've selected a month that isn't the current month
- "Last n months" (e.g. "Last 3 months") if you have selected a range
Additionally, the range selections have been updated to span the whole row, aligning with the look of generic dropdown lists.
Like with the rest of this file (`PeriodSelector`), the code is rough and not according to Unleash standards. However, I'm prioritizing fast changes so UX can have a look before I clean up the code to switch to using styled components etc later. It's still behind a flag, so I'm not very worried about it.
> feat(1-3281): wraps the new datepicker in a dropdown

- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneStrategy/MilestoneStrategyTypeFlexible.tsx
https://linear.app/unleash/issue/2-3101/ui-hint-for-gradual-rollout-groupid-magic-string-featurename
Explains the current release plan milestone gradual rollout strategy groupId behavior with an HelpIcon and a tooltip next to the field, when creating or editing a release plan template.
> chore: add hint to release plan template gradual rollout strategy groupId

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanAddChangeRequestDialog.tsx
- frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts
Implements sending the change request of add release plan when submitted
> feat: send the add release plan change request from dialog when submitted

- src/lib/metrics.ts
- src/lib/middleware/response-time-metrics.ts
We're dropping x- prefix from sdk uniqueness tracking. In a transitional period we support both variants.
We need this merged before we roll out SDK fixes.
> feat: drop x- header prefix

- frontend/src/component/admin/groups/GroupForm/GroupFormUsersSelect/GroupFormUsersSelect.tsx
- frontend/src/component/project/ProjectAccess/ProjectAccessAssign/ProjectAccessAssign.tsx
2 dropdowns in project users and group users have filtering limit. It means that we only render at most 100 items. When a user starts typing autocomplete text it searches across all users. Only the final render list is limited. It makes rendering of large user lists possible.
In the following PR we'll start adding virtualization.
> feat: limit user filter options

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsagePlanSummary.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/RequestSummary.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/average-traffic-previous-months.ts
- frontend/src/component/common/Badge/Badge.tsx
- frontend/src/hooks/useTrafficData.ts
Updates the existing number of requests and overage info boxes to the new design.
The existing versions of the boxes had some issues on narrower screens, so it was easier to just leave them as is and start from scratch.
The previous boxes on narrow screens:
The current ones (from wide to narrower):
Wide
Mid (the text should probably ideally wrap at the same time here, but I'm not sure how at the moment)
Narrow
Extra narrow:
There's still some work we **could** do, but we should have UX have a look first. In particular, it's about how the text wraps in certain places etc, but I think it's good enough for now.
I'll come back with tests for the calculations and some refactoring and cleanup in a followup.
> chore(1-3316): update request info boxes to new design

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
Makes it so that the dropdown menu sits below the dropdown button,
rather than being offset to the end of the containing flexbox.
The issue was caused by the surrounding container being a flexbox.
This caused the popover anchor to grow to the full height of the box,
making the menu look offset.
By using `align-items: start`, we get around this.
Before
After:
> fix(1-3334): re-align the dropdown menu with the dropdown

- frontend/src/hooks/useTrafficData.test.ts
The test was breaking because it assumed a month would have at least
30 days.
Because the test relies on the current month, this isn't necessarily true.
Further, there's parts of the code that relies on "impure" state via
the "current date" (which will change based on when you run it), so
setting a specific month in the test won't work.
As such, this test makes the calculation explicit and uses the number
of days in the current month.
> fix: make traffic usage test more robust by using this month's actual numbers

- frontend/src/component/banners/internalBanners/LicenseBanner.tsx
- frontend/src/hooks/api/getters/useLicense/useLicense.ts
This gives us the ability to communicate other license messages which are not errors. By default they'll be warning but I'm opening the possibility of using a backend-provided value to make them informative instead of warning.
The intention is to communicate things like:
- Your license is about to expire in x days.
- You are getting close to the maximum number of seats in your license
- etc
> feat: ability to communicate other license messages

- src/lib/services/user-service.test.ts
- src/lib/services/user-service.ts
- src/lib/types/user.ts
Validations in the constructor were executed on the way out (i.e. when reading users). Instead we should validate when we insert the users.
We're also relaxing the email validation to support top domain emails (e.g. `...@jp`)
> feat: move create user validations to the input

- frontend/src/component/admin/network/NetworkTrafficUsage/PeriodSelector.tsx
Refactors the period selector component now that the design / system is pretty much finished.
Main points are: change from using CSS selectors to using styled components; use props instead of classes. This is in keeping with the general Unleash approach.
There's two very slight visual changes here:
1. There is 4px of added space below the "range" "header" text.
2. The months in the grid are a little closer together and not as wide. This is because we remove the explicit column gap due to the grid having a set width. Previously the width was automatic, but because we want this to line up with the button, we need to set the width explicitly on both items. As such, with the padding, the grid was a little too wide, so there was too little padding on the right. This rectifies that.
> refactor: period selector component

- src/lib/features/client-feature-toggles/delta/client-feature-delta-api.e2e.test.ts
- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
- src/lib/features/client-feature-toggles/delta/delta-cache.ts
Now when customer is coming with revision ID that does not exist in cache, we return hydration.
> fix: now hydration event is being returned if revision does not exist in cache

- frontend/src/component/admin/network/NetworkTrafficUsage/endpoint-info.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/selectable-periods.ts
- frontend/src/hooks/api/getters/useInstanceTrafficMetrics/useInstanceTrafficMetrics.ts
- frontend/src/utils/traffic-calculations.test.ts
- frontend/src/utils/traffic-calculations.ts
Implements a function that cleans and filters incoming data from the
new traffic API.
Specifically, it:
- Removes `/edge` data points
- Removes any data from before may 2024, which is the first full month we have on record
Because all uses of the existing hook do this filtering themselves, I
have added the filtering at the hook level. This is to avoid
forgetting this filtering later. If we find out we need this data, we
can move the filtering.
> chore(1-3335): filters data coming from the API to remove data points we're not  interested in

- frontend/src/component/common/ToastRenderer/Toast/Toast.tsx
Toasts sometimes render messages that are in markdown format. This changes how we display them from 
to this:
> feat: render markdown in toats

- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingDetailsPAYG.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingDetailsPro.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/useOverageCost.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/hooks/api/getters/useInstanceTrafficMetrics/useInstanceTrafficMetrics.ts
Updates the existing BillingDetails pages (pro and payg) to use the new traffic search endpoint (and calculations) if the flag to do so is on. Otherwise, it falls back to using the existing method. 
I've extracted the overage calculation into a separate shared hook.
> chore(1-3342): extract into hook, use new endpoint if flag on

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/average-traffic-previous-months.ts
- frontend/src/hooks/useTrafficData.ts
- frontend/src/utils/traffic-calculations.test.ts
- frontend/src/utils/traffic-calculations.ts
Adds new monthly estimation functions that operate on raw usage data instead of chart data. This brings those methods in line with the rest of the traffic calculation functions that we have in that file and means we can remove other external dependencies. 
This is somewhat inspired by #9218, but not directly linked.
> refactor: add functions to estimate monthly usage from data directly

- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/useOverageCost.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/average-traffic-previous-months.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/chart-functions.test.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/chart-functions.ts
- frontend/src/hooks/api/getters/useInstanceTrafficMetrics/useInstanceTrafficMetrics.ts
- frontend/src/utils/traffic-calculations.test.ts
- frontend/src/utils/traffic-calculations.ts
Makes the data returned from the traffic search a union type to avoid
nasty object-is-undefined errors at runtime.
It requires more explicit handling, sure, but it means we don't need
to accept undefined.
> chore: use union type for traffic search data

- src/lib/db/user-store.ts
- src/migrations/20250205072305-clean-scim-id-from-deleted-users.js
users.scim_id is unique and will cause collision errors when reinserted.
PR adds a migration that clears scim_id and scim_external_id fields on deleted users, and clears scim_id and scim_external_id when deleting users through user store
> chore: clear scim fields when deleting user + migration for existing cases

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/FeatureChange.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ReleasePlanChange.tsx
- frontend/src/component/changeRequest/changeRequest.types.ts
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestone/ReleasePlanMilestone.tsx
https://linear.app/unleash/issue/2-3169/add-release-plan-ui-representation-in-change-request-ui
Adds visual representations for release plan change requests.
> chore: release plan changes in change request view

- frontend/src/component/common/SkipNavLink/SkipNavTarget.tsx
- frontend/src/component/layout/MainLayout/MainLayout.tsx
Fixes the issue where the skip link wouldn't take you to the main content of the page anymore.
Also includes a few related minor semantic and a11y improvements:
1. The `main` element now only surrounds the actual main content of the page. The sidebar is nav content and shouldn't be within it. The easiest way to do this was to change the element that was previously a `main` to a `div` and make the main content wrapper a `main` instead.
2. Makes the skip link target visible when focused. But invisible otherwise. This has two benefits:
1. It's immediately obvious that using the skip link has worked. It tells you that it's at the start of the main content.
2. Because the link now has text, it can be targeted by link search (e.g. in Firefox, press `'` to search for links (I use this **a …
> fix(1-3295): fix broken skip link

- frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
- frontend/src/component/releases/ReleaseManagement/ReleaseManagement.tsx
https://linear.app/unleash/issue/2-3093/sales-pitch-ui-for-release-management-to-show-non-enterprise-users
Marks Release Management as a premium Enterprise feature.
Once the `releasePlans` flag is enabled for everyone / removed, this is what non-Enterprise users will see:
> chore: mark release management as an enterprise feature

- frontend/src/component/personalDashboard/PersonalDashboard.tsx
Keeps it consistent with the previous title for this component and
with what it's known as in the docs.
> chore: changes the panel title to "Event timeline"

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureReleasePlanCard/FeatureReleasePlanCard.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
- frontend/src/component/releases/ReleaseManagement/ReleasePlanTemplateCard/ReleasePlanTemplateCardActions.tsx
- frontend/src/component/releases/ReleasePlanTemplate/CreateReleasePlanTemplate.tsx
- frontend/src/component/releases/ReleasePlanTemplate/EditReleasePlanTemplate.tsx
- frontend/src/hooks/usePlausibleTracker.ts
https://linear.app/unleash/issue/2-2834/plausible
Adds the following Plausible events to the Release management feature:
- Add plan
- Start milestone
- Remove plan
- Create template
- Edit template
- Delete template
> chore: release management plausible events

- frontend/src/component/events/EventLog/EventLog.tsx
- frontend/src/component/filter/FilterItem/FilterItemChip/FilterItemChip.tsx
When the filter chip is focused, adds a 1px solid outline in the theme's primary color. This makes it easier to tell when the chip has focused.
Additionally, adds a slight refactor in how we call the event log result component. I'm pretty sure I've seen react docs say that you should always use the component calling instead of a regular function call, so this does that.
Before (the first chip has focus; can you tell?):
After:
Optionally, we could do something similar to on hover (first one has focus again), but it's kinda subtle and .. I don't think it's a theme color we have defined:
> Adds a more visible focus indicator to the filter chips

- frontend/src/component/events/EventTimeline/EventTimelineHeader/EventTimelineHeader.tsx
- frontend/src/component/personalDashboard/PersonalDashboard.tsx
Removes the border between the accordion summary and its contents for the event timeline, and moves dropdown selectors to the right to avoid overcrowding on the left.
> chore(1-3349): no border for event timeline / dropdowns to the right

- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
- src/lib/features/segment/fake-segment-read-model.ts
- src/lib/features/segment/segment-read-model-type.ts
- src/lib/features/segment/segment-read-model.ts
Fixes an issue where segment-updated event would be added to cache even though there were no correlated events. Tests needs to be added in Enterprise.
> fix: return if empty array

- frontend/src/component/commandBar/CommandBar.tsx
Prevents tab from navigating you through the list of results. Instead
makes it so that the tab key always takes you to the next item in the
same hierarchy.
As a bonus: also automatically closes the menu when you navigate
away (the previous implementation has a bug where it wouldn't if you
shift-tab).
The behavior of not letting you navigate the list with tab is
consistent with native HTML select elements as well as MUI select
elements. You typically navigate them with the arrow keys.
> fix(1-3296): don't navigate through the list on tab

- package.json
I figured that many of our tests are timing out and we can solve this by increasing test timeout.
This is a signal that either our tests became slower or that our query performance got worse. On the first point it might be due to having more migrations than before and requiring more time.  The second point is harder to validate but something to keep an eye on
> chore: tests are timing out

- src/lib/__snapshots__/create-config.test.ts.snap
- src/lib/features/metrics/client-metrics/client-metrics-store-v2-type.ts
- src/lib/features/metrics/client-metrics/client-metrics-store-v2.ts
- src/lib/features/metrics/client-metrics/fake-client-metrics-store-v2.ts
- src/lib/features/metrics/client-metrics/metrics-service-v2.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
Adds a killswitch called "filterExistingFlagNames". When enabled it will filter out reported SDK metrics and remove all reported metrics for names that does not match an exiting feature flag in Unleash. 
This have proven critical in the rare case of an SDK that start sending random flag-names back to unleash, and thus filling up the database. At some point the database will start slowing down due to the noisy data. 
In order to not resolve the flagNames all the time we have added a small cache (10s) for feature flag names. This gives a small delay (10s) from flag is created until we start allow metrics for the flag when kill-switch is enabled. We should probably listen to the event-stream and use that invalidate the cache when a flag is created.
> fix: Killwitch to block usage-metrics from non-exiting flag-names

- frontend/src/component/personalDashboard/PersonalDashboard.tsx
- frontend/src/component/personalDashboard/useDashboardState.ts
Extracts each panel into its own component for the personal dashboard. This lets us use separate states for each panel, which in turn lets each panel change its open / close state without causing the other panels to re-render.
When you have a lot of flags and/or projects, the list to render becomes very long, which causes performance problems, especially when you need to rerender both flags and projects and the timeline whenever one of them changes.
The problems were especially noticeable in Firefox for me. Even with this, the event timeline is a little choppy. I suspect that's because of it might take a long time to paint? But we can look into that later.
Also updates the dashboard state hook to let you only pass in the flags/projects you want. We could extract this into three different …
> fix: open/close animation on personal dashboard is choppy

- frontend/src/component/admin/auth/ScimSettings/ScimDeleteUsersDialog.tsx
- frontend/src/component/admin/auth/ScimSettings/ScimSettings.tsx
- frontend/src/component/admin/groups/Group/Group.tsx
- frontend/src/component/admin/groups/GroupsList/GroupCard/GroupCardActions.tsx
- frontend/src/component/admin/users/UsersList/DeleteUser/DeleteUser.tsx
- frontend/src/component/admin/users/UsersList/UsersActionsCell/UsersActionsCell.tsx
- frontend/src/hooks/api/actions/useAdminUsersApi/useAdminUsersApi.ts
- frontend/src/hooks/api/actions/useGroupApi/useGroupApi.ts
- src/lib/db/group-store.ts
- src/lib/db/user-store.ts
- src/lib/routes/admin-api/user-admin.ts
- src/lib/services/group-service.ts
- src/lib/services/user-service.ts
- src/lib/types/events.ts
- src/lib/types/stores/group-store.ts
- src/lib/types/stores/user-store.ts
- src/test/e2e/api/admin/user-admin.e2e.test.ts
- src/test/e2e/api/admin/user-admin.scim.e2e.test.ts
- src/test/fixtures/fake-group-store.ts
- src/test/fixtures/fake-user-store.ts
Adds a way to remove SCIM entities if you're an admin
Groups and users can now be deleted if they originate from SCIM, the usual deletion buttons have just been re-enabled.
The UI for SCIM setup itself has been given two new buttons, one each for nuking all SCIM groups and users. This requires a [companion PR](https://github.com/bricks-software/unleash-enterprise/pull/35) on enterprise to work correctly. I've opted specifically to add these buttons to the SCIM setup interface because this is more a SCIM problem that a group/user problem from a user perspective and because this really shouldn't be part of the standard manage groups/users flow,
Group/user deletion code no longer rejects calls if the group/user is a SCIM entity.
A method for deleting all users has been added to the …
> feat: allow SCIM user deletion

- frontend/src/component/commandBar/CommandBar.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/ShowHide.tsx
- frontend/src/component/playground/Playground/PlaygroundGuidancePopper/PlaygroundGuidancePopper.tsx
Fixes a small number of accessibility issues that Firefox was complaining about (and some that I noticed myself):
1. In `CommandBar.tsx`, use a `Label` element instead of aria-label. We can hide it with the `ScreenReaderOnly` component.
2. Add an `aria-label` to the icon button in the sidebar. (side note: should we do any fancy detection on whether it's cmd + b or ctrl+b there? I think we do that in the command bar)
3. Update the playground guidance popper;
i. Add an aria-label to the icon button
ii. Make the popper a `Popover` instead. This fixes a few issues: It wasn't possible to focus or close just using the keyboard before. Because it didn't steal focus, it also meant that it'd cover other parts of the page. Now it traps focus so you can navigate to the close button, and escape will …
> fix: some accessibility issues

- frontend/src/themes/dark-theme.ts
This adds the same button stylings to the dark theme as we did to the
light theme in #9275.
> chore: add button styles to dark mode too

- frontend/src/component/feedback/FeedbackCES/__snapshots__/FeedbackCESForm.test.tsx.snap
- frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
- frontend/src/hooks/useThemeMode.ts
- frontend/src/themes/dark-theme.legacy.ts
- frontend/src/themes/theme.legacy.ts
Also, use extra css selectors to increase specificity so that this
takes precedence over the MUI themes.
I don't like that we need to do this weird selector thing, but hey, it
is what it is.
> fix: Use the right theme even if the payload is a variant.

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/chart-functions.ts
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
Network data usage may show connections instead of raw request count behind a flag. 
This PR adjusts chart data to visualize connections count (1 connection = 7200 requests per day) in a day or in a month
> feat: connection count usage

- frontend/src/component/common/ProjectSelect/ProjectSelect.tsx
This makes it the same size as the env selector, fixing a slight
visual misalignment.
Doing a reference check, I can't find any other uses of this selector,
so I'm making the changes directly.
Before:
After:
> fix: make the chip in the playground project selector small

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/CopyStrategyIconMenu/CopyStrategyIconMenu.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanelEnvironmentSwitches/FeatureOverviewSidePanelEnvironmentSwitch/FeatureOverviewSidePanelEnvironmentHider.tsx
Adds aria-labels to the env visibility toggle button and the "copy
env" button.
> fix: add some missing button labels on the project page

- website/docs/feature-flag-tutorials/javascript/implementing-feature-flags-js.md
Updates the JS tutorial with the following:
- Two functional changes:
-> (1) adding a `#` in the image tag src definition, as it doesn't work without
-> (2) adding `unleash.start()` in the code after initializing Unleash, as it doesn't work without
- Some other typos and writing style changes
[Page preview](https://unleash-docs-git-melinda-fix-js-tutorial-unleash-team.vercel.app/feature-flag-tutorials/javascript)
> Update js tutorial to fix bugs and writing style

- src/lib/features/client-feature-toggles/delta/delta-cache.test.ts
- src/lib/features/client-feature-toggles/delta/delta-cache.ts
We were not updating hydration event id. This fixes it.
> fix: hydration event should update with every event

- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
Nameprefix can remove events from result, so we should send 304 in that case.
> fix: return undefined from delta if no events

- frontend/cypress/integration/projects/access.spec.ts
Fix e2e test, failing because of subtle table syntax change. Nested `span`s are counted twice in Cypress `:contains`
> fix(1-3374): access e2e test

- frontend/src/component/feature/FeatureView/FeatureView.tsx
- src/server-dev.ts
Initial spike to add the new design for the flag header. This PR uses the flag and adds a new header if it's active.
As far as I can tell, all elements of the new header are present in this design.
Handle narrow window widths. There is no handling of narrow windows here and the entire thing is set as nowrap, so it ends up with the actions hiding the tabs:
However, we also don't handle this very well today:
That said, I think now woud be a good time to handle this.
Todays buttons for copying the flag, archiving it, etc, use `PermissionIconButton`. We want the same behavior, but without behavior checks. As far as I can tell, that's not a component we have today? (although I didn't look very hard). In this first instance, I've made a very simple version that's based on the permission icon …
> feat: new flag header

- src/lib/features/metrics/instance/instance-service.ts
- src/lib/metric-events.ts
- src/lib/metrics.ts
Adding a counter to track every time a client registers with Unleash.
> fix: add a metric to track client registrations

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/SegmentChangeDetails.tsx
- frontend/src/component/changeRequest/ChangeRequest/SegmentTooltipLink.tsx
- frontend/src/component/segments/RemoveSegmentButton/RemoveSegmentButton.tsx
- frontend/src/component/segments/SegmentDelete/SegmentDelete.tsx
- frontend/src/component/segments/SegmentDelete/SegmentDeleteConfirm/SegmentDeleteConfirm.tsx
- frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts
Fixing a bug where non admin users couldn't delete empty project segments in projects with change requests. The request was going directly to delete segment API instead of adding a change to the "shopping cart"
When deleting an empty project segment with change requests enabled you get add to draft option instead of instant delete:
Then the toast message is changed according to change request naming convention:
We already had delete segment UI in the "shopping cart" but I fixed the crossed out name when the change request is applied to read the data from the snapshot and not current strategy:
> fix: delete project segment with change request

- frontend/src/component/personalDashboard/MyFlags.tsx
- frontend/src/component/personalDashboard/MyProjects.tsx
Fixes a bug where the dashboard would scroll you down from the top of
the page on load if your window was too short too see both the
selected flag and the selected project.
This solves it by immediately scrolling to the top of the page after
scrolling your selected element into view. Because this hook only runs
on page load, it shouldn't be safe. (At least I couldn't make this
misbehave with manual testing).
It also changes the list scroll behavior to scroll your selected item
to the top of the list instead of to the bottom (effectively). During
testing, that seems like a better solution to me.
The dashboard's flag and projects panels stores your last selection,
so that when you return to the page you'll be shown what you were
looking at last. This is especially useful if you have a lot …
> fix(1-3375):   Fix unintended scroll on dashboard

- frontend/src/component/feature/Dependencies/AddDependencyDialogue.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/AddTagButton.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/Collaborators.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/DependencyRow.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.test.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/OldDependencyRow.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/TagRow.tsx
- website/docs/reference/feature-toggles.mdx
- updated spacing of elements
- modified header and "flag type" 
- added "collaborators"
- refactored tags
New design:
What's not done yet:
- dropdown for environments visibility
> feat: new flag info box

- frontend/src/component/feature/FeatureView/FeatureView.tsx
- frontend/src/component/feature/FeatureView/FeatureViewHeader.tsx
This PR moves the flag page header into a separate file, so that the overview file is more clearly focused on the overview.
Additionally, it moves the modals that are triggered from the header into the new file. This should give a nice little performance boost, as opening and closing these modals should no longer trigger a re-rendering of the full flag overview page, only the header.
> refactor: move feature overview header into separate file

- src/lib/features/client-feature-toggles/delta/client-feature-toggle-delta.ts
- src/lib/features/client-feature-toggles/delta/delta-cache.test.ts
- src/lib/openapi/spec/client-features-delta-schema.test.ts
- src/lib/openapi/spec/client-features-delta-schema.ts
Start sending out project for feature deleted, as we need it for edge to keep exact copy.
> feat: project field to feature removed event

- frontend/src/component/admin/apiToken/ApiTokenForm/useApiTokenForm.ts
- frontend/src/interfaces/uiConfig.ts
> chore: remove references to admin token kill switch

- src/lib/features/metrics/client-metrics/metrics-service-v2.ts
This fixes a problem where the yggdrasil-engine does not send the correct value for bucket.start. In practice clients sends metrics every 60s and it does not matter if we use start or the stop timestamp to resolve the nearest full hour.
> fix: use bucket stop as timestamp for metrics bucket

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/AddTagButton.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/EnvironmentVisibilityMenu/EnvironmentVisibilityMenu.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/EnvironmentVisibilityMenu/hooks/useEnvironmentVisibility.ts
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewSidePanel/FeatureOverviewSidePanel.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/LegacyFeatureOverview.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/NewFeatureOverviewEnvironment/FeatureOverviewEnvironmentBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/NewFeatureOverviewEnvironment/NewFeatureOverviewEnvironment.tsx
- frontend/src/component/feature/FeatureView/FeatureView.tsx
- frontend/src/hooks/useGlobalLocalStorage.ts
- frontend/src/hooks/useHiddenEnvironments.ts
- Button to show and hide environments
- Refactored hook storing state of hidden environments
- Changed the way flag is triggered for feature overview
- Visual updates for new page look
> feat: show and hide environments

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
Await adding changes and refetching change requests so that the banner can show up immediately after adding release plan changes
> chore: await so change requests banner shows up after adding release plans changes

- frontend/src/component/admin/adminRoutes.ts
- frontend/src/component/admin/network/Network.tsx
- frontend/src/component/admin/network/NetworkConnectedEdges/NetworkConnectedEdgeInstance.tsx
- frontend/src/component/admin/network/NetworkConnectedEdges/NetworkConnectedEdgeInstanceLatency.tsx
- frontend/src/component/admin/network/NetworkConnectedEdges/NetworkConnectedEdges.tsx
- frontend/src/component/admin/network/NetworkOverview/NetworkOverview.tsx
- frontend/src/component/admin/network/NetworkPrometheusAPIWarning.tsx
- frontend/src/component/admin/network/NetworkTraffic/NetworkTraffic.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/__snapshots__/NavigationSidebar.test.tsx.snap
- frontend/src/hooks/api/getters/useConnectedEdges/useConnectedEdges.ts
- frontend/src/hooks/api/getters/useInstanceMetrics/useInstanceMetrics.ts
- frontend/src/interfaces/connectedEdge.ts
- frontend/src/interfaces/uiConfig.ts
- src/lib/openapi/spec/ui-config-schema.ts
- src/lib/routes/admin-api/config.ts
- src/lib/types/experimental.ts
https://linear.app/unleash/issue/2-3233/visualize-connected-edge-instances
Adds a new tab in the Network page to visualize connected Edges.
This is behind a `edgeObservability` flag.
Also opens up the Network page even if you don't have a Prometheus API configured. When accessing the tabs that require it to set, and it isn't, we show some extra information about this and redirect you to the respective section in our docs.
> chore: visualize connected edges

- frontend/src/component/admin/network/NetworkPrometheusAPIWarning.tsx
- frontend/src/hooks/api/getters/useInstanceMetrics/useInstanceMetrics.ts
- frontend/src/hooks/api/getters/useUiConfig/defaultValue.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/openapi/spec/ui-config-schema.ts
- src/lib/routes/admin-api/config.ts
https://linear.app/unleash/issue/2-3290/rename-networkviewenabled-to-prometheusapiavailable
Follow-up to: https://github.com/Unleash/unleash/pull/9325
See: https://github.com/Unleash/unleash/pull/9325#discussion_r1960085303
Renames `networkViewEnabled` to `prometheusAPIAvailable`. This new name better reflects what it stands for.
> refactor: rename networkViewEnabled to prometheusAPIAvailable

- frontend/src/component/feature/FeatureView/FeatureViewHeader.tsx
Makes it so that the actions/tabs wrap on narrow width screens.
Constraints:
- When wrapping, the actions should go **before** the tabs, when not wrapping, they should be placed **after**
- Need to maintain a logical tab order for wrapping, so just using `flex-flow: row wrap-reverse` doesn't work because the tab order will be wrong
- When the elements switch, you shouldn't lose your tab place in the document
This solution uses container queries to determine the container size and uses that to set the wrapping. Falls back to media queries if container queries aren't supported (it's supported on >93% of browsers according to caniuse).
The wrapping points don't use predefined media queries because:
- containers don't care about the size of the screen. It's the intrinsic size of the container …
> chore(1-3380): handle narrow windows for the flag header.

- frontend/src/component/feature/FeatureView/FeatureViewHeader.tsx
Reduces the size of the tab buttons on the flag page:
- Sets the min width to 100px instead of 160px on md screens. No change for smaller screens
- Removes the min-height restriction imposed by theme.ts for the tab bar, instead relying on the tab buttons to determine the height (effectively changes the height from 70px to 62px).
Additionally: fixes an issue where the action buttons would overlap with the tab buttons before wrapping and makes the tab bar scrollable. I can no longer reproduce the issue where the action buttons force the tab bar to be too small, but even if they should do that now, the tab bar is scrollable so the remaining tabs are still accessible.
Because we only override the tabs' min-width on wider screens and mui sets a default min-width, I changed the `onNarrowHeader` …
> chore: reduce tab sizes on flag page + fix wrapping/overlapping issue with action buttons

- frontend/src/component/admin/network/NetworkConnectedEdges/NetworkConnectedEdgeInstance.tsx
- frontend/src/component/admin/network/NetworkConnectedEdges/NetworkConnectedEdgeInstanceLatency.tsx
https://linear.app/unleash/issue/2-3298/make-latency-table-clearer
Improves UX of the Edge observability latency table.
> chore: improve UX in the Edge observability latency table

- website/docs/how-to/how-to-setup-provisioning-with-entra.md
The workaround proposed by MS no longer seems to work. That now prevents users from being deprovisioned at all. This includes the steps to configure the SCIM compliance flag, which prevents Entra from sending incorrect data in the first place
> docs: entra scim setup now includes SCIM compliance flag

- frontend/src/component/common/DialogFormTemplate/ConfigButtons/ConfigButton.styles.tsx
- frontend/src/component/common/DialogFormTemplate/ConfigButtons/ConfigButton.tsx
- frontend/src/component/common/DialogFormTemplate/ConfigButtons/DropdownList.styles.tsx
- frontend/src/component/common/DialogFormTemplate/ConfigButtons/shared.styles.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/EnvironmentVisibilityMenu/EnvironmentVisibilityMenu.tsx
Makes the env selector on the flag page act the same way as the env selector on the new project page or any of the filterable buttons in the new project/flag dialogs. 
Also slightly changes the styles of the existing dropdown lists to bring them in line with the new env selector (more padding, full-width highlights).
Selector:
Project/flag creation:
Before:
After:
I was a little unsure how best to share the padding/spacing styles between the search field and popover at first (as was requested by UX). The easiest way (and most compliant with how we do it today) was to define the spacing in a variable and move the relevant components into the same file.
However, I actually think that using a CSS variable (e.g. `--popover-spacing`) would be "better" here, but we don't really use them much, …
> feat: make env selector filterable

- frontend/vite.config.mts
Updates the `vite.config.mts` file to include config for emotion,
telling it to add `<file name>--<component name>` to the class names
of generated components.
The class name modification only happens in development mode.
> chore: add file and component names to `styled` output class names in dev

- frontend/src/component/common/DialogFormTemplate/ConfigButtons/shared.styles.tsx
- frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewMetaData/FeatureOverviewMetaData.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
Addresses two issues related to flag names and descriptions overflowing:
1: In the project flag overview, long flag names push the environments off screen. This is handled by setting overflow-wrap: anywhere on the offending text. The text will now use ellipses instead.
Before full-width: 
Before narrower:
After full-width:
After narrower:
2: On the flag page, long descriptions are rendered in their entirety, even if that's not sensible. They are now truncated after five lines. There is a tooltip that shows the full text, or you can go the flag settings to see the full description.
Before:
After:
After (with tooltip):
---
Note, I don't think this is necessarily the perfect solution (it'd be nice to get tooltips for overflowing flag names a "show full description" disclosure button instead …
> fix: long flag names push table to overflow and flag descriptions are not truncated

- frontend/src/component/App.tsx
- frontend/src/component/banners/internalBanners/MonthsOldVersionBanner.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/__snapshots__/create-config.test.ts.snap
- src/lib/create-config.ts
- src/lib/openapi/spec/version-schema.ts
- src/lib/services/version-service.ts
- src/lib/types/option.ts
https://linear.app/unleash/issue/2-3309/warn-users-of-lagging-versions-3-months-old
Adds a banner warning users in case they are running an outdated Unleash version (>=3 months old) in case the build date data is present.
When clicking "Changelog" the users are redirected to https://github.com/Unleash/unleash/releases.
> chore: months old version banner

- src/lib/features/events/event-service.test.ts
- src/lib/features/events/event-service.ts
- src/lib/features/feature-toggle/feature-toggle-service.ts
- src/lib/features/feature-toggle/tests/feature-toggles.e2e.test.ts
- src/lib/features/segment/segment-service.ts
- src/lib/services/api-token-service.test.ts
- src/lib/services/api-token-service.ts
- src/lib/types/stores/store.ts
- src/test/fixtures/fake-api-token-store.ts
Some automation may keep some data up-to-date (e.g. segments). These updates sometimes don't generate changes but we're still storing these events in the event log and triggering reactions to those events.
Arguably, this could be done in each service domain logic, but it seems to be a pretty straightforward solution: if preData and data are provided, it means some change happened. Other events that don't have preData or don't have data are treated as before.
Tests were added to validate we don't break other events.
> feat: ignore events in log when nothing has changed

- frontend/src/component/commandBar/CommandBar.tsx
Lets you navigate to the top of the list when you're at the bottom,
and vice versa.
Arrow down at the end of the list takes you to the search field and
arrow up from the search field takes you to the end of the list.
> feat: allow command bar navigation to wrap around

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
Improves the semantic correctness of the strategy list by wrapping it
in an `ol` tag.
Strategy order matters (due to variant resolution etc), so the order
is important (hence the `ol` instead of a `ul`).
Dragging still works and it's visually the same.
> chore(1-3420): wrap strategy list in an ordered list

- frontend/src/component/common/StrategySeparator/StrategySeparator.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
Adjusts styling of the env dropdown now that we have both release plans and strategies.
Key points:
- simplifies strategy separator, removes inherent height. Also: extracts it from the draggable component (it has no business knowing whether to add that or not)
- Puts release plans and strategies in the same list so that it becomes:
```markdown
- Release plan
- strategy 1
- strategy 2
- (OR) Strategy A
- (OR) Strategy B
```
- Adjusts some padding around to make it line up properly
- Swaps a couple conditional renders for ternaries
Rendered:
Handle cases where you have >50 strats and we show the warning etc. It's a little trickier because of how it interacts with release plans, so I wanna leave that for later.
I'm also unsure about how we handle spacing today. All the little items have …
> chore: adjust env dropdown

- frontend/src/component/common/Card/Card.tsx
- frontend/src/component/project/ProjectCard/ProjectCardFooter/ProjectCardFooter.tsx
- frontend/src/themes/theme.ts
Deprecates the `envAccordion` colors (`expanded` and `disabled`) and updates the components that I do not expect to be deprecated as part of the strategy facelift project to use `elevation1` instead.
The difference is very slight. envAccordion.expanded:
Elevation 1:
> chore: deprecate `envAccordion` colors; update non-legacy components

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.tsx
Removes the `() => {} as any` args from the StrategyDraggableItem invocation when you have paginated strats. Instead makes all the drag params optional. It defaults to a no op if not provided.
Also, the reason it had to be typed as `any` before is probably because it was missing a function. The correct empty param is `() => () => {}` 💁
> refactor(1-3429): makes the drag args optional, defaulting to noops

- frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.test.tsx
Adds tests for the new version of components that were moved to legacy files in https://github.com/Unleash/unleash/pull/9361 and where there were tests already.
> chore(1-3423): adapt existing tests to new components

- frontend/src/component/releases/ReleaseManagement/ReleasePlanTemplateList.tsx
https://linear.app/unleash/issue/2-3328/release-template-cards-should-have-a-consistent-minimum-height
Sets a consistent min height in our release template cards.
> chore: release template card min height

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ReleasePlanChange.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanAddDialog.tsx
https://linear.app/unleash/issue/2-3099/when-attempting-to-add-a-release-plan-to-a-feature-environment-already
Adapts our UI to better provide hints about our release plan replacement behavior, both on the add dialog and change requests.
> chore: release plan replacement UI

- frontend/src/utils/traffic-calculations.ts
Fixes an issue with `estimates based on custom price and unit size` test failing every month that has 31 days.
We were not respecting the custom unit sizes when calculating overage
> fix: solve 31 day month issue by using trafficUnitSize and not constant 1_000_000

- frontend/src/component/changeRequest/ChangeRequestPermissions.test.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/CopyStrategyIconMenu/CopyStrategyIconMenu.tsx
When checking for permissions we were checking if the user was allowed to copy to other environments but it can also copy to the same environment.
Before the change: 
After the change:
> fix: copy strategy is allowed to copy to self (duplicate)

- frontend/src/component/changeRequest/ChangeRequestStatusBadge/ChangeRequestDraftStatusBadge.tsx
- frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/ProjectEnvironmentStrategyDraggableItem.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.test.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/LegacyStrategyItem.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyItem.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/NewFeatureOverviewEnvironment/FeatureOverviewEnvironmentBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/NewFeatureOverviewEnvironment/NewFeatureOverviewEnvironment.tsx
- frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/StrategyList/StrategyItem/FeatureStrategyItem.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironmentDefaultStrategy/ProjectEnvironmentDefaultStrategy.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneCard/MilestoneCard.tsx
Updates `StrategyDraggableItem` (and `StrategyItem`) to be project/env agnostic. They now instead expect you to pass in the required header items (CR badges, strategy actions) at the call site. Updates their usage in the feature env accordion, and the release plan card.
All components that have been updated are part of the new overview rework. The legacy components (which are used when the flag is off) remain untouched.
Also makes a few small tweaks explained in inline comments.
Milestone card (with flag on):
Milestone card (with flag off):
Feature env accordion (flag on (no change)):
Feature env accordion (flag off):
> refactor: strategy draggable item is now proj/env agnostic

- frontend/src/component/common/FormTemplate/FormTemplate.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneCard/MilestoneCard.tsx
Avoids absolutely positioning the drag handle by instead creating a two column grid where column 1 is the drag handle, column two is the milestone card. The grid has a negative margin based on the padding of the form container. I wanted to avoid modifying the form container component (because we use it in so many places), so I used css variables to store the information and hook into that further down the line.
Rendered:
Wide:
Narrow:
The current drag implementation has some issues if you try to drag something over a large, expanded card. They'll trade places visually, but when you let go, the revert back to where they were. We can avoid that by modifying the onDrop function in the drag handler, but I don't want to do that before checking all the other places where we do drag and drop …
> refactor: don't use absolute positioning for drag handle

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
For past months, customers can refer to their invoices instead. Hiding it when the selection is not the current month avoids weird things such as estimation errors due to to a month not having finished (vs what it actually *was* when it finished), potential changes in traffic package pricing, etc.
> fix: Only show accrued traffic charges and estimated overages for the current month

- frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.tsx
Constrains long custom strategy titles to a single line.
Before:
After:
> chore: Constrains custom strategy titles to a single line

- frontend/src/component/admin/cors/CorsForm.tsx
- frontend/src/component/admin/roles/RoleForm/RolePermissionCategories/RolePermissionCategories.tsx
- frontend/src/hooks/api/actions/useUiConfigApi/useUiConfigApi.ts
- frontend/src/interfaces/uiConfig.ts
- src/lib/routes/admin-api/config.test.ts
- src/lib/routes/admin-api/config.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
- removed a flag
- deprecated `POST /admin/ui-config` endpoint in favor of `POST /admin/ui-config/cors`
> chore: remove granularAdminPermissions flag

- frontend/cypress/integration/projects/access.spec.ts
- frontend/cypress/support/UI.ts
- frontend/cypress/support/commands.ts
The fix involved:
1. [Find the first button to click to create a feature flag](9b4500cded18e74fc66bbe7f555a70566694aef3) (there are 2)
2. [Find the button that's not disabled to remove access](fad627c6b3e1e3d244e58838602c90e086a25944)
3. [Don't wait for animations](5ce6ca59f5474745d2b96a09f7acf29b62202f0c) except in [this case](f4a7819ad1f134e61cc42f8d3e7e199b8a058f07)
> fix: frontend tests after Cypress upgrade

- src/lib/features/client-feature-toggles/client-feature-toggle-store.ts
- src/lib/features/client-feature-toggles/fakes/fake-client-feature-toggle-store.ts
- src/lib/features/client-feature-toggles/types/client-feature-toggle-store-type.ts
This method has been deprecated 2 years ago and is not used
> chore: remove deprecated getAdmin from client features store

- src/lib/types/model.ts
This has been deprecated 4 years ago and is not used
> chore: remove legacy feature type

- src/lib/features/project/project-service.e2e.test.ts
- src/lib/features/project/project-service.ts
- src/test/e2e/services/access-service.e2e.test.ts
Depends on https://github.com/bricks-software/unleash-enterprise/pull/137
This method has been deprecated and has an alternative. Migrating to that alternative
> chore: remove deprecated method from project-service

- .github/docker-compose.test.yml
- .github/workflows/e2e.frontend.yaml
This removes the need of running a heroku instance with enterprise to run frontend tests. We can also get rid of vercel deployments of the frontend for PRs (ofc we'd be loosing the preview if we do this)
It relies on the free enterprise docker image to spin up a clean Unleash instance on each frontend spec test.
It also seems to speed up tests, I guess because we don't have to wait for vercel deployment queue:
Compared with other recent PRs:
Unrelated to this PR but something is making the features spec tests very slow since Cypress upgrade: https://github.com/Unleash/unleash/actions/runs/13784760762/job/38550079932#step:4:138
> chore: use a local image of unleash enterprise for testing FE

- frontend/src/component/admin/users/UsersList/UsersActionsCell/UsersActionsCell.tsx
- frontend/src/component/admin/users/UsersList/UsersList.tsx
https://linear.app/unleash/issue/2-3342/new-entrance-point-create-dot-dot-dot-menu-instead-of-icons
Adds a new users actions menu.
Should this change be behind a flag? I'm leaning towards no, but if you think otherwise let me know.
> chore: users actions menu

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/PeriodSelector.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/RequestSummary.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/chart-data-selection.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/chart-functions.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/dates.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/hooks/useChartDataSelection.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/hooks/useStats.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/selectable-periods.ts
- frontend/src/utils/traffic-calculations.ts
Fixes a number of issues that would surface in UTC-n (where n > 1) timezones. I've not found a way to check this with tests (and it looks like [we weren't able to last time either](https://github.com/Unleash/unleash/pull/9110/files#r1919746328)), so all the testing's been done manually by adjusting my system time and zone. (From what I understand, you can't generate a Date with a specific TZ offset in JS: it's only utc or local time)
Resolved:
> fix: Data usage graphs don't work in UTC-n time zones

- frontend/src/component/admin/users/AccessOverview/AccessOverview.tsx
- frontend/src/component/admin/users/AccessOverview/AccessOverviewSelect.tsx
- frontend/src/component/admin/users/AccessOverview/AccessOverviewTable.tsx
- frontend/src/component/admin/users/UsersAdmin.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepActions/ProjectActionsActionItem.tsx
- frontend/src/hooks/api/getters/useServiceAccountAccessOverview/useServiceAccountAccessOverview.ts
- frontend/src/hooks/api/getters/useUserAccessOverview/useUserAccessOverview.ts
- frontend/src/interfaces/permissions.ts
- src/lib/routes/admin-api/user-admin.ts
- src/lib/services/access-service.ts
https://linear.app/unleash/issue/2-3344/new-name-access-overview-instead-of-access-matrix
Renames Access Matrix to Access Overview, both internally (code) and externally (UI).
> chore: rename access matrix to access overview

- frontend/src/component/commandBar/CommandBar.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/useRoutes.ts
- frontend/src/component/menu/Header/DrawerMenu/DrawerMenu.tsx
- frontend/src/component/menu/Header/Header.tsx
- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
- frontend/src/interfaces/route.ts
This PR aims to clean up a little in our frontend routing (mostly unused stuff)
- The old mobile menu is gone, the new one doesn't use the mobile: true attributes in the IRoute.menu
- admin links are not sourced from routes.ts anymore - so formatting that and returning a collection for it is no longer neccessary
- DrawerMenu doesn't use the routes provided to it - a sub component resolves its own routes from useRoutes. Removing that parameter and the providing of it in Header
- There's no 'advanced' menu anymore - the main menu is populated with items marked as menu.advanced: true however - so changing that to be menu.main: true.
- routes.ts getRoutes renamed to getNavRoutes and changed to just returning the routes with menu.main: true
> chore: clean up frontend routes

- .lycheeignore
It looks like it's not something we can validate
Closes #9519
> fix: ignore youtube embed from check links

- frontend/src/component/admin/users/AccessOverview/AccessOverview.tsx
- frontend/src/component/admin/users/AccessOverview/AccessOverviewAccordion/AccessOverviewAccordion.tsx
- frontend/src/component/admin/users/AccessOverview/AccessOverviewAccordion/AccessOverviewList.tsx
https://linear.app/unleash/issue/2-3346/only-show-description-and-not-permission-first-column-and-group
Categorizes the permissions in our Access Overview.
> chore: categorize access overview

- frontend/src/component/layout/MainLayout/MainLayout.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationList.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx
- src/server-dev.ts
This PR moves the admin section of the navigation sidebar into a separate component.
In that component we check if the flag is enabled, if so we change what we show in the menu to be a single link to admin settings. 
We also change the MainLayout where we remove the whole menu if the flag is enabled **and** we're visiting a /admin route. That's because we'll add a separate menu in a slightly different location later for just the menu sub section
> feat: rework navigation sidebar admin section

- frontend/src/component/commandBar/CommandBar.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/useRoutes.ts
- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
- frontend/src/interfaces/route.ts
Cleaning up mobile routes also removed the primary routes (what we call them in navigation sidebar) to be unresolvable, resulting in:
This PR fixes this by adding a menu property "primary?: boolean", and some code mapping matching items into a route collection for command bar. The collection should be reusable for menu-rendering in the future if we choose to
> chore: fix missing primary routes for commandbar

- frontend/src/component/common/ConstraintsList/ConstraintsList.tsx
- frontend/src/component/common/SegmentItem/SegmentItem.tsx
New approach (with flexbox highlighted)
Previous iteration
> fix: segment spacing in strategy constraints

- frontend/src/component/common/SegmentItem/SegmentItem.tsx
- frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureResultInfoPopoverCell.tsx
This adds two small visual changes:
1. Add some spacing to the playground header (so that the custom strategies info box (or other alerts) get some breathing room. (It slightly increases the text between the header and the flag result text, but I'll leave that as is unless we get told otherwise. It's partially because of extra padding on the close button etc, and will be more work than I wanna put in right now).
2. Style the "this segment has no constraints" text for empty segments to use a smaller, less prominent font.
Playground header before:
Playground header after:
Segments text before:
Segments text after:
> chore: add spacing to playground header + style segment's no constraints text

- frontend/src/component/common/PremiumFeature/PremiumFeature.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NewInUnleash/NewInUnleash.tsx
- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
- frontend/src/component/releases/ReleaseManagement/ReleaseManagement.tsx
renames release management to release templates:
- in the menu
- in the page title
- in the 'new in unleash'
- in the premium feature description
> chore: rename release management to release templates

- frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureResultInfoPopoverCell.tsx
- frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/PlaygroundResultsFeatureStrategyList.tsx
- frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/StrategyList/PlaygroundResultStrategyLists.tsx
Handle cases where flags have no strategies in the playground.
As part of this, also changes how we deal with the padding/margins in the playground: instead of making all but one items in the playground have to explicitly add padding, now we instead say that the only item that needs to do something is the list, which uses negative inline margins.
This also has the added benefit of adding all the top-level elements (that is: that's not part of the strategy lists) inside the same container, so we can control gaps between them with flex's gaps.
When you have no strategies (before):
When you have no strategies (after):
> chore(1 3493): handle cases with no strategies

- src/lib/features/feature-search/feature-search-store.ts
Fixes an issue where s was possibly null and Unleash would not build after turning on strictNullChecks.
> fix: s is possibly null

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx
- frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
Removes the cloud icon in the change request env header to better align with the new env headers in the flag environment overview.
Also hides strategy variants in favor of using the new strategy execution component.
As a bonus: also uses a link component instead of a button for navigating to the change request page.
With flag enabled:
> chore: Updates change request sidebar to remove env/cloud icon

- frontend/src/component/common/ConstraintsList/ConstraintsList.tsx
- frontend/src/component/common/ConstraintsList/StrategyEvaluationItem/StrategyEvaluationItem.tsx
- frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.tsx
- frontend/src/component/common/StrategyItemContainer/disabled-strategy-utils.ts
- frontend/src/component/common/StrategySeparator/StrategySeparator.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/ProjectEnvironmentStrategyDraggableItem.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyItem/StrategyExecution/StrategyExecution.tsx
Aligns the design of disabled strategies with the sketches. Most notable changes:
- makes the disabled badge warning yellow
- greys out the preceding "or" separator
- makes the segment "preview" button *not* grey (because it's still interactable)
As a bonus: uses a list for the constraint value lists instead of a div and updates the design to match the sketches (no chips). 
With strat variants:
Bonus fix: 
Lets the constraint value list wrap so that we avoid this kind of blowout:
Instead:
> chore: finish up disabled strategies

- frontend/src/component/admin/users/AccessOverview/AccessOverview.tsx
- frontend/src/component/user/Profile/ProfileTab/ProfileTab.tsx
https://linear.app/unleash/issue/2-3430/fix-undefined-in-access-overview-when-user-name-is-unavailable
Adds a fallback to email in case the name is not available.
Also switches the priority of the fallbacks to be consistent with other places in our codebase (email > username) and uses `||` instead of `??` because falsy values don't provide much informational value anyways.
> fix: access overview fallback to email

- frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/ProjectEnvironmentStrategyDraggableItem.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/StrategyDraggableItem.tsx
Makes it so that strategies project env strategies that aren't draggable don't get the drag icon. The reason it didn't work as expected was that we used fallback functions instead of keeping them undefined.
I discovered that we applied two dragging boxes, so I removed the outer layer one (specific to project envs) in favor of relying on the inner one. Most of the lines changed are just indentation as a result of this nesting going away.
Here's the diff. The top set of strategies aren't draggable; the lower ones are.
> chore: Don't use fallback functions for dragging

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentHeader/EnvironmentHeader.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
Adds an optional `environmentMetadata` property to the env header component, which is used to populate the release plan / strategy counter. If no env metadata is passed (such as for default strategy configuration) nothing is rendered.
With long env names, the project name will be cut off before the chip:
There's some issues with narrow screens, but I'll handle that in a follow-up:
> chore(1-3516): add release plan / strategy count to env header

- frontend/src/component/common/StrategyList/StrategyList.tsx
- frontend/src/component/common/StrategyList/StrategyListItem.tsx
- frontend/src/component/common/StrategySeparator/StrategySeparator.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanMilestone/ReleasePlanMilestone.tsx
- frontend/src/component/playground/Playground/PlaygroundResultsTable/FeatureResultInfoPopoverCell/FeatureStrategyList/StrategyList/PlaygroundResultStrategyLists.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneCard/MilestoneCard.tsx
Extracts the shared strategy list and list item into the `common` folder instead of living in the environment accordion body file. 
Also takes the disabled strategy handling that we use for `StrategySeparator` and moves it into the file itself. It might be something we want to decorate manually in the future, but we don't for now, so this was the most straight-forward way to make it work.
> refactor(1-3439): extract shared components and styling from Env Accordion Body to common

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentHeader/EnvironmentHeader.tsx
When the container is <500px, make it so that the strategy count wraps onto its own line to prevent it from obscuring the environment name.
I decided to go for 500px because that allows our default names to not get cut off before wrapping. It seems like a sensible default.
Before:
After:
It's still not perfect when you have envs without strategies, but it's better. We'll get back to that edge case later.
> fix: wrap env header grid on narrow containers

- frontend/src/component/environments/EnvironmentTable/EnvironmentTable.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/StrategyDraggableItem/ProjectEnvironmentStrategyDraggableItem.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneCard/MilestoneCard.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneCard/MilestoneCardDragHandle.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneList/MilestoneList.tsx
- frontend/src/hooks/useDragItem.ts
Fixes janky drag and drop behavior and updates the styling of the drag handle focus.
The solution uses the same method to prevent oscillation as we do for strategies. To get access to the same context, I've added some extra parameters to the OnMoveItem function and passed along the extra data from the `useDragItem` hook. No new information, just making more of it available, and turning it into an object so that you can declare the properties you need (and get rid of potential wrong ordering of drag/drop indices).
For the drag and drop behavior: If the dragged element is the same size or smaller than the element you're dragging over, they will swap places as soon as you enter that space. If the target element is larger, however, they won't swap until you reach the drag/drop handle, even if …
> Fix(1-3462)/janky drag n drop

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/LegacyReleasePlan.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
Removes the `releasePlanChangeRequests` flag and swaps existing references to it to the `releasePlans` flag instead
> chore: consolidate release plan flags

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
Adds a new button to the strategy options on the toggle config pane to be able to add a release plan directly
When clicked this just renders the usual popup but with only the release plans populated.
> feat: add use template button to strategies selector on flag config pane

- src/lib/db/feature-tag-store.ts
- src/lib/features/feature-search/feature-search-store.ts
- src/lib/features/feature-search/feature.search.e2e.test.ts
- src/lib/openapi/spec/deprecated-project-overview-schema.ts
- src/lib/openapi/spec/health-overview-schema.ts
- src/lib/openapi/spec/tag-schema.ts
- src/lib/types/model.ts
- src/test/e2e/api/admin/tags.e2e.test.ts
- src/test/e2e/stores/feature-tag-store.e2e.test.ts
This PR adds support for including tag color information when retrieving feature tags. The color information is propagated from the tag type to the feature tags, allowing the UI to display tags with their associated colors.
1. **Schema Updates**
- Updated `tag-schema.ts` to include color information in the tag schema
- Added tagSchema to schemas already using tagSchema but lacking the component import
2. **Store Updates**
- Modified `FeatureTagStore` to join with the `tag_types` table when retrieving feature tags and retrieve color
- Updated `getAllTagsForFeature` method to include color information from tag types
3. **Test Updates**
- Added new test case in `tags.e2e.test.ts` to verify color information propagation
- Added new test case in  `feature.search.e2e.test.ts` to verify color …
> feat: backend for retrieving tag colors

- website/docs/contributing/ADRs/ADRs.md
- website/docs/contributing/ADRs/overarching/logging-levels.md
This PR starts an ADR for logging levels, and how to make your coworkers' days who are on-call less noisy.
This is my initial suggestion. Please feel free to help me with fleshing out both the table for what log levels means to you or if you disagree with what I've put as a background.
My impression is that we are pretty good at this, but we could be better, and having an ADR to lean on when pushing back on PR's log levels could help us. 
Thanks to @kwasniew for the push to start the ADR.
Examples: 
* https://github.com/Unleash/unleash/blob/038c10f6125c4cce200a0bf49f38c7bddada7093/src/lib/db/account-store.ts#L164-L173
And probably the storeFootprint method in our client-feature-toggle-delta
* https://github.com/Unleash/unleash/blob/038c10f6125c4cce200a0bf49f38c7bddada7093/src/lib/features/ …
> feat(docs): Added ADR for logging levels

- frontend/src/component/admin/users/UsersHeader/UsersHeader.test.tsx
- frontend/src/component/admin/users/UsersHeader/UsersHeader.tsx
This component will be hidden for pro and payg, as they are not billed by 30 days window.
> feat: show seats used only for full enterprise customers

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
Changes the logic in when we display metrics for an env to not showing
them unless we have strategies.
>  Hide env metrics when an env has no strategies.

- frontend/src/component/admin/Admin.tsx
- frontend/src/component/admin/AdminIndex.tsx
- frontend/src/component/admin/adminRoutes.ts
- frontend/src/component/admin/auth/AuthSettings.tsx
- frontend/src/component/admin/auth/OldAuthSettings.tsx
- frontend/src/component/admin/oldAdminRoutes.ts
- frontend/src/component/admin/useAdminRoutes.ts
- frontend/src/component/layout/MainLayout/AdminMenu/AdminListItem.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminMenu.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminMenuIcons.tsx
- frontend/src/component/layout/MainLayout/MainLayout.tsx
Adds an admin menu to the page when visiting a /admin sub page
- introduces a new adminRoutes.ts and moves the existing usage to oldAdminRoutes.ts (we'll remove that when we remove the flag)
- introduces a new AuthSettings so that we can control page with a route - the old behavior is kept in OldAuthSettings.tsx which will be removed when we remove the flag
- also introduces a WrapIfAdminSubpage component that just renders the children prop if flag disabled or page not a sub page of /admin. This is the scariest part of this PR so if you want to be spending some extra time reviewing thoroughly - this is a good candidate for that time
> feat: admin menu

- frontend/src/component/environments/CreateEnvironment/CreateEnvironment.tsx
- frontend/src/component/environments/EditEnvironment/EditEnvironment.tsx
- frontend/src/component/environments/EnvironmentForm/ChangeRequestSelector.tsx
- frontend/src/component/environments/EnvironmentForm/EnvironmentForm.tsx
- frontend/src/component/environments/EnvironmentForm/EnvironmentTypeSelector.tsx
- frontend/src/component/environments/EnvironmentTable/EnvironmentActionCell/EnvironmentCloneModal/EnvironmentCloneModal.tsx
- frontend/src/component/environments/hooks/useEnvironmentForm.ts
- frontend/src/interfaces/environments.ts
- frontend/src/interfaces/uiConfig.ts
- src/lib/features/project-environments/environment-store.ts
- src/lib/types/model.ts
Can create and edit environment with required change request approvals
Details:
* change behind a flag
* current update needs to distinguish between ignoring field in update (undefined) and reseting field to null in update
> feat: create and edit environment required approvals

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
When there's no release templates and the user clicks 'Use Template'. They now get a little message telling them that and a link to where they can add one.
> chore: add a message stating no templates when there aren't any

- frontend/src/component/layout/MainLayout/AdminMenu/AdminListItem.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminMenu.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminNavigationItems.tsx
- frontend/src/component/menu/Header/DrawerMenu/DrawerMenu.tsx
- frontend/src/component/menu/Header/Header.tsx
Implements the admin menu behavior and style for mobile.
Moves some of the menu components into mobile/regular shared components for reuse, and adds a staticExpanded property that disables the expanding nature of the accordions (for mobile view only)
> feat: admin menu for mobile

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/releases/ReleaseManagement/ReleasesFeedback.tsx
- frontend/src/constants/links.ts
Adds a new link on the feature strategy that points to the feedback link (pops out new window, only renders if release plans are enabled). I moved the feedback link out to a constant but mostly only because I am 100% going to forget to update one of the places it exists
> chore: feedback link on feature strategy

- frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/ChangeRequestTable.tsx
- frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/ConfigButtons/ChangeRequestTableConfigButton.tsx
- frontend/src/component/project/Project/CreateProject/NewCreateProjectForm/CreateProjectDialog.tsx
Potential project environments with preconfigured change request approvals cannot be overwritten in the UI
We need to check if we need similar check in the backend. Currently it's a soft enforcement but advanced users of the API can override this behavior.
> feat: enforce change request settings in create project dialog

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
Fixes an issue where the new feedback button on the config strategy pane would affect environments without strategies configured
I've made the following changes here:
- The feedback button is now disabled by default, the parent needs to request that it be turned on and that's only done in one place
- CSS has been reworked so that it behaves when that component doesn't exist on the DOM (just flex align to the right and a spacer component that expands to eat whatever space it finds)
- Swapped the CSS on the parent that was originally causing the parent component not to fill the container (looks to be flex used to align on a different axis)
> fix: only display feedback component on opened strategy panes

- frontend/src/component/layout/MainLayout/AdminMenu/AdminMenu.tsx
- frontend/src/component/menu/Header/DrawerMenu/DrawerMenu.tsx
We accidentally used `location` (the browser variable) instead of the `const location = useLocation()` from react in 2 of 3 places. this results in main menu being hidden while admin menu not being shown
> fix: useLocation instead of browser location for resolving pathname

- frontend/src/component/layout/MainLayout/AdminMenu/AdminMenu.tsx
- frontend/src/component/layout/MainLayout/MainLayout.tsx
This cleans up the weird alignment of the main section for certain screen resolutions when the admin menu is up
before:
after:
> chore: fix weird alignment issue with main content and admin menu

- frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionView/ConstraintAccordionView.tsx
- frontend/src/component/common/StrategyItemContainer/StrategyItemContainer.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentHeader/EnvironmentHeader.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/FeatureOverviewEnvironment.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
Adds focus styles to the env accordion header only when the focus is on the header itself (not on the env toggle inside the header). The focus style is consistent with what we do for other accordions (dashboard, milestones).
Middle one is focused:
Focus is on the toggle inside the top one (yeh, we should have better focus styles for toggles; but that's not for now):
Open and focused: 
Getting the consistent background for the header when it's open is a little tricky because the accordion container and summary are split into different files. ~~This first iteration used a class name for the specific header (because envs can have multiple accordion headers inside them, e.g. release plans) and setting a CSS variable in the summary, so that the background matches.~~ I found out that I only …
> fix: focus styles for env headers

- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx
- frontend/src/component/menu/Header/DrawerMenu/DrawerMenu.tsx
Replaces a long list of admin links with a link to the /admin section
> feat: show only link to /admin in mobile menu

- frontend/src/component/admin/users/UsersList/UsersList.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
This is exposing information we already have about permissions in a UI that should help users have an overview of the permissions of a user with regards to projects and environments
> feat: remove access overview flag making it GA ready

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
This fixes the a react crash when we render more/fewer hooks than on the previous render if the flag state changes.
> Fix: Move hooks to before we bail if the flag is off.

- src/lib/features/ui-observability-controller/ui-observability-controller.ts
These errors are not acted upon and is not something we can act on. Reducing it's level to WARN following https://github.com/Unleash/unleash/blob/main/website/docs/contributing/ADRs/overarching/logging-levels.md
> chore: decrease ui observability to warn

- frontend/src/component/admin/AdminHome.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminListItem.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminMenuIcons.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminNavigationItems.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationList.tsx
- frontend/src/component/layout/components/EnterprisePlanBadge/EnterprisePlanBadge.tsx
- frontend/src/component/layout/components/EnterprisePlanBadge/useShowBadge.ts
Adds enterprise badge to menu items that are enterprise only when instance is pro
Also fixes Instance stats button in admin home
> chore: admin menu enterprise badge

- frontend/src/component/admin/adminRoutes.ts
makes sure network section routes/links are covered with the correct flags
> chore: add flags to control network route links from menu

- frontend/src/component/tags/TagTypeForm/TagTypeColorPicker.tsx
This PR refactors the color picker so we stick to one set of colors instead of changing available colors when theme changes. Colors picked also work in dark theme and is aligned with UX.
> refactor: colorpicker

- frontend/src/component/admin/AdminHome.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminMenu.tsx
- Fixes so Admin subpage doesn't stick to the left (with a huge open space to the right) in certain screen resolutions
- Fixes the breakpoints in admin home so we switch to having two columns of stats much sooner (avoids having orphaned fourth stat on second row)
> chore: admin menu main layout tweaks

- biome.json
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingDetailsPAYG.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/BillingDetailsPro.tsx
- frontend/src/component/admin/billing/BillingDashboard/BillingPlan/useOverageCost.ts
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
- frontend/src/component/commandBar/RecentlyVisited/CommandResultGroup.tsx
- frontend/src/component/common/Table/SearchHighlightContext/SearchHighlightContext.tsx
- frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.test.tsx
- frontend/src/component/common/Table/cells/FeatureOverviewCell/FeatureOverviewCell.tsx
- frontend/src/component/events/EventLog/EventLogFilters.test.tsx
- frontend/src/component/events/EventLog/EventLogFilters.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverview.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/EnvironmentAccordionBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentAccordionBody/LegacyEnvironmentAccordionBody.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/ManageBulkTagsDialog.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
- frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ManageTags.tsx
- frontend/src/component/project/Project/ProjectInsights/ProjectInsightsStats/ProjectInsightsStats.tsx
- frontend/src/component/project/Project/ProjectSettings/ChangeRequestConfiguration/ChangeRequestTable.tsx
React can crash an app if rules of hooks are broken. This occurs if there is a return statement before a hook, causing a different number of hook calls between component renders. To prevent this I'm reintroducing a linting rule. We probably had it before we switched from ESLint to Biome. This PR is also fixing all of the issues introduced in the code that where flagged by Biome.
> fix: linter rule for useHookAtTopLevel

- frontend/src/component/common/ConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditHeader/ConstraintAccordionEditHeader.tsx
- frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditHeader/ConstraintAccordionEditHeader.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectActions/ProjectActionsTable/ProjectActionsModal/ProjectActionsForm/ProjectActionsFormStep/ProjectActionsFormStepSource/ProjectActionsFilterItem.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
The flag has never made it out of dev, and has not been turned on consistently since 2023. There was a project for it, but we have since abandoned it.
> Remove caseInsensitiveInOperators flag

- frontend/src/component/menu/Header/Header.tsx
shows the unleash logo when admin menu is active
> feat: admin menu: unleash logo in header - links to dashboard

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureReleasePlanCard/FeatureReleasePlanCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureReleasePlanCard/OldFeatureReleasePlanCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCard/FeatureStrategyMenuCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCard/OldFeatureStrategyMenuCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/OldFeatureStrategyMenuCards.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ManageTagsDialog/ManageBulkTagsDialog.tsx
- frontend/src/component/project/Project/ProjectFeatureToggles/ProjectFeaturesBatchActions/ManageTags.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
1. Creating new component files to keep them behind flag
2. Long descriptions for cards are showed with ellipis and tooltip.
3. Renamed old components to format Old..., so we can track all the changes in new files.
> feat: new feature strategy menu

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureReleasePlanCard/FeatureReleasePlanCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCard/FeatureStrategyMenuCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
- Updated all card titles and descriptions to use `theme.typography.caption.fontSize` (12px)
- Added proper spacing between card sections with `marginBottom: theme.spacing(3)`
- Made the section scrollable
- Added info icons with helpful tooltips to all strategy sections:
- **Pre-defined strategy types**: "Select a starting setup, and customize the strategy to your need with targeting and variants"
- **Apply a release template**: "Use one of the pre-defined templates defined in your company for rolling out features to users"
- **Custom strategies**: "Custom strategies you have defined in Unleash"
- Fixed section organization by combining the default strategy with other predefined strategies under a single "Pre-defined strategy types" section
> feat: new styling for strategy selector

- frontend/src/component/layout/MainLayout/NavigationSidebar/IconRenderer.tsx
Updating `IconRenderer` component in the `NavigationSidebar`. It will fix icons not showing up for command bar search results.
> fix: add Project and Playground icons for command bar

- frontend/src/component/featureTypes/FeatureTypeEdit/FeatureTypeForm/FeatureTypeForm.tsx
Seems the previous value was hardcoded. Now we check the values you set instead.
> Fix: lifetime API command doesn't update.

- frontend/src/component/personalDashboard/ProjectSetupComplete.tsx
- frontend/src/component/project/Project/Project.tsx
Updates the link from the project dashboard page to take you to the project status modal instead of the old insights page.
We didn't have a way to auto-open the modal before, so I added a query param to control it.
> fix: link to "view more insights" from dashboard goes to status modal

- frontend/src/component/admin/useAdminRoutes.ts
- frontend/src/component/commandBar/ButtonItemIcon.tsx
- frontend/src/component/commandBar/CommandBar.tsx
- frontend/src/component/commandBar/CommandSearchPages.tsx
- frontend/src/component/commandBar/RecentlyVisited/CommandResultGroup.tsx
- frontend/src/component/commandBar/useCommandBarRoutes.ts
- frontend/src/component/layout/MainLayout/NavigationSidebar/IconRenderer.tsx
Depends on adminNavUI flag which adminRoutes (old or new) to fetch routes for Command Bar from.
with adminNavUI enabled introduces a searchable string to each route consisting of title, path, group key, group title (from admin ui 2.0), etc, else just title
> feat: command bar admin menu improvements

- frontend/src/component/layout/MainLayout/AdminMenu/AdminMenu.tsx
Fixes issues where very large popups get covered by the admin menu
> chore: remove z-index from sticky admin menu as its probably not needed

- frontend/src/component/personalDashboard/RoleAndOwnerInfo.tsx
- frontend/src/component/project/ProjectCard/ProjectCardFooter/ProjectCardFooter.tsx
- frontend/src/component/project/ProjectCard/ProjectCardFooter/ProjectOwners/ProjectOwners.tsx
Hides owner avatars in cases where the owner type is "system". Touches dashboard and project card owners.
Back when all projects required owners, we introduced the new project cards that have the owner listed in the footer. Because, theoretically, you weren’t allowed to create projects without owners, the only project that should ever be without an owner was the default project. So we thought it made sense to say that it was owned by the system.
But now that owners are optional, that doesn't necessarily make sense anymore. As such, we'll just hide their avatars to begin with.
Because the components expected the avatars to be there, we now need to set an explicit min-height on them, so that they don't collapse. Luckily, we can use the default avatar height (and also force that so that they …
> Fix(1-3564)/hide project owner if system

- frontend/src/component/project/Project/Project.tsx
- frontend/src/component/project/Project/ProjectStatus/ProjectStatusModal.tsx
Fixes a bug where project status modal links wouldn't work.
The reason they didn't work is because we modified the query params on modal close, and because we manually close the modal when you click a link (because otherwise it'd stay open when you navigated to other project pages), we inadverdently reset the URL.
I'm not entirely sure why setting the search params would modify the URL itself, but I'm guessing that's related to the implementation.
One way to solve this is to indicate whether we're closing the modal because a link was clicked or not, and only modify the query params if that is not the case.
> fix: project status modal links don't work

- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/RequestSummary.tsx
So this PR removes the purchased dt point, as well as the total available. Using the same check our overageCalculation does (it also only works on current month)
> we don't have historical data available for purchased traffic

- frontend/src/component/project/Project/ProjectFeatureToggles/FeatureToggleSwitch/FeatureToggleSwitch.tsx
Removes the "disableRipple" prop from the FeatureToggleSwitch component, thereby restoring its focus styles, so that keyboard users can see where their focus is at.
I don't know the reason this was added originally (the PR doesn't say anything about it), but the prop changes nothing when hovering with the mouse, but it does remove focus styles for keyboard navigation.
By removing it, we can bring the focus style back. As far as I can tell, there's no other difference between the two states.
Both of these screenies have focus on the toggle, but in the first screenie there's no way to tell. 
With the prop:
Without the prop:
Because the component is used in multiple places, this also fixes this issue in the project flag list (and maybe elsewhere too):
> fix: restore focus style to the env switch

- src/lib/features/feature-toggle/feature-toggle-service.ts
- src/test/e2e/api/admin/project/variants-sunset.e2e.test.ts
https://linear.app/unleash/issue/2-3483/variants-endpoint-should-return-400-or-other-more-appropriate-status
Throws BadDataError (returns 400) instead of 500 by wrapping the patch logic with a try catch. 
Added a test that validates the new behavior.
> fix: return bad data error when failing to patch env variants

- frontend/src/component/feature/FeatureView/FeatureNotFound/FeatureNotFound.tsx
If you try to visit an archived flag, you're told you can find it on the project archive page, but that page isn't visible by default anymore. This is an update to take you to the project overview with a filter for archived flags instead.
> fix: update link text for archived feature navigation

- frontend/src/component/common/AutocompleteBox/AutocompleteBox.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategySegment/FeatureStrategySegment.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneStrategy/MilestoneStrategySegment.tsx
Removing it from strategy and also from milestone creation.
> feat: remove + from the segment dropdown

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureReleasePlanCard/FeatureReleasePlanCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCard/FeatureStrategyMenuCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
- Significantly improved dialog navigation flow — the "Go back" button now properly returns users to the strategy menu instead of closing the preview dialog with no way to return
- Now release cards expand to 100% height if neighbour card has bigger height.
> feat: strategy menu interaction between two dialogues.

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentHeader/EnvironmentHeader.tsx
Solves an issue where the new buttons would potentially obscure the entire name of the env:
Now, instead of using grid and container queries to find the right point to break, we're using flex to always wrap before needing to truncate the environment name. The name will still truncate if necessary. 
Why didn't we do this originally? I ... couldn't think of a way to make flex work in a 2D layout, but the `width: 100%` property seems to do the trick 😄 
PS: the buttons only stack when they have to. They stay single-line for as long as possible. (just in case you were wondering).
> fix: wrap env data before truncating env name.

- src/lib/features/feature-search/feature-search-store.ts
- src/lib/features/feature-search/feature.search.e2e.test.ts
- src/lib/openapi/spec/feature-environment-schema.ts
- src/server-dev.ts
Feature search should include milestone name, milestone order and total number of milestones
@Tymek Jaanus has a good point that writing a query here allows for a faster iteration
@sjaanus please take a look at the query enhancement. I will be running explain plan for this part and change requests soon but I don't expect perf degradation due to early filtering happening before we join extra data.
@daveleek are you ok with me moving stores for release plans into OSS so that we can use them for the test setup? Also please check if the query makes sense to you since you know it well. I basically join two tables that you created with feature name and environments from the search result features.
> feat: add milestones to search results

- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneStrategy/ReleasePlanTemplateAddStrategyForm.tsx
Discovered we have exactly same implementation in release plan folder structure.
Changing it there also.
> feat: styling of info box for release plans

- website/docs/reference/sdks/index.mdx
https://linear.app/unleash/issue/2-3494/go-sdk-impression-event-support
Adds Go impression data support.
See: https://github.com/Unleash/unleash-client-go/pull/194
> docs: add Go impression data support

- frontend/src/component/admin/network/NetworkTrafficUsage/bar-chart-options.ts
- frontend/src/component/admin/network/NetworkTrafficUsage/hooks/useChartDataSelection.ts
As reported by Ivar, there's no point in displaying the average daily traffic when grouping monthly.
> fix(frontend): Now only shows average daily requests when viewing daily

- src/lib/services/project-health-service.ts
- src/test/e2e/api/admin/project/project.health.e2e.test.ts
setHealthRating job was running project health calculation for multiple projects in parallel. Now we spread it into single project chunks run every 5s.
Also adding some instrumentation for the function execution time and query execution time.
This is similar improvement to statusJob: https://github.com/Unleash/unleash/pull/9755
> fix: improve health rating job performance

- frontend/src/component/demo/demo-topics.tsx
https://linear.app/unleash/issue/2-3512/bug-flow-2-enable-for-a-specific-user-doesnt-work
https://linear.app/unleash/issue/2-3513/bug-flow-4-adjust-variants-doesnt-work
Fixes our demo topics by making them work with the new flag page design.
We achieve this by adding 2 new interactive steps in `demoApp.step2` and `demoApp.step4` to expand the respective environment accordions. We mark them as optional so they are not strictly required and will be skipped if not found. This means the demo will be resilient to rolling back the `flagOverviewRedesign` flag, for example.
We also mark 2 steps as optional: saving constraints in `demoApp.step2` and `demoApp.step4`. It seems like we no longer have an extra button to save the constraints after adding them, so by marking these steps as optional the …
> fix: demo topics should work with new flag design

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
This removes the add values nicely.
> feat: remove add values for legal values

- frontend/src/component/demo/demo-setup.ts
- frontend/src/component/demo/demo-topics.tsx
https://linear.app/unleash/issue/2-3512/bug-flow-2-enable-for-a-specific-user-doesnt-work
https://linear.app/unleash/issue/2-3513/bug-flow-4-adjust-variants-doesnt-work
Follow-up to #9765 
This should make the demo flow a bit more consistent with the new page design.
The page seems a bit slower in general, so we're being a bit more aggressive on the cleaning up of demo data to make it faster as well as adding some delays in key steps of the flow.
> fix: demo flow consistency with new flag page

- frontend/src/component/admin/adminRoutes.ts
- frontend/src/component/admin/auth/AuthSettings.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminListItem.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminMenuIcons.tsx
- frontend/src/component/layout/MainLayout/AdminMenu/AdminNavigationItems.tsx
- frontend/src/component/layout/MainLayout/MainLayout.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/IconRenderer.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationList.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.tsx
- frontend/src/component/menu/Header/DrawerMenu/DrawerMenu.tsx
- frontend/src/component/menu/Header/Header.tsx
- frontend/src/hooks/useNewAdminMenu.ts
Moves the links from the admin menu into the navigation sidebar instead, along with new styles and some refactorings to make that happen.
- /admin/auth now routes to /admin/auth/oidc which is the new oidc config
- New colours for admin nav items
- Fixes the menu group not being open when page loads at a /admin group sub page
- Fixes isActiveItem to also work when you're on a pages items-page (ie /admin/users/1 etc)
> feat: move admin menu into nav sidebar

- frontend/src/component/demo/DemoSteps/DemoStepTooltip/DemoStepTooltip.tsx
https://linear.app/unleash/issue/2-2576/make-back-button-less-dominant
Make demo "Back" button `variant='text'` so it's less predominant visually.
> chore: make demo back button variant text

- website/docs/understanding-unleash/hosting-options.mdx
Update Edge Cloud and Edge OSS comparison table with latency and client-side context changes
**[Docs preview](https://unleash-docs-git-docs-fix-hosting-strategie-d46596-unleash-team.vercel.app/understanding-unleash/hosting-options#unleash-enterprise-edge-vs-unleash-edge-open-source)**
> docs: hosting options - apply suggestions for latency and client-side context

- src/lib/create-config.test.ts
- src/lib/create-config.ts
- src/lib/server-impl.test.ts
- src/lib/server-impl.ts
- src/lib/services/api-token-service.test.ts
- src/lib/services/api-token-service.ts
- src/lib/services/user-service.ts
- src/test/e2e/helpers/test-helper.ts
Initially at Unleash we started using `process.nextTick` inside constructors to delay initialization of services. 
Later we stared using a pattern where we instantiate services multiple times. 
The problem is the first pattern implies we have singleton services, while the second pattern breaks the singleton.
There are reasons for both patterns, but we've decided that `process.nextTick` inside constructors is not something we want to keep as it creates side effects from creating objects. Instead this PR proposes a more explicit approach.
Fixes #9775
> fix: double token initialization

- frontend/src/component/demo/DemoSteps/DemoStepTooltip/DemoStepTooltip.tsx
- frontend/src/component/demo/DemoSteps/DemoSteps.tsx
- frontend/src/component/demo/demo-topics.tsx
https://linear.app/unleash/issue/2-2577/transition-screen-between-the-guides
https://linear.app/unleash/issue/2-2582/page-scrolls-in-back
Includes what should be the last batch of demo improvements at this stage:
- Visually aligns the Back button for consistent layout
- Replaces “Start” with “Start tutorial” for new topics
- Updates topic titles for clarity and consistency
- Applies bold styling to all step titles
- Prevents page scroll when the step target is set to body
> chore: demo misc improvements

- frontend/src/component/feature/FeatureView/FeatureCopyName/FeatureCopyName.tsx
- frontend/src/component/feature/FeatureView/FeatureViewHeader.tsx
- frontend/src/hooks/useKeyboardCopy.ts
- moved "copy flag name" action next to the flag name
- refactored this component into a separate file
- added "Ctrl+C" shortcut
> feat: move 'copy flag name' button

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddValuesWidget.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/ValueList.tsx
Removes the condition to hide the value list if we use legal values. 
In doing so, I also realized that focus handling when you delete the last item in the constraint values list doesn't work if the add values button isn't there (which it shouldn't be for legal values and more). So I've hidden the add values button when it doesn't do anythnig helpful (or for cases where we don't have designs yet). In cases where you don't have the add values button and you delete the last constraint value, we'll move the focus to the "delete constraint" button (that was easier than making sure we pass refs all the way down into the operator select, but we can change that later).
To facilitate this (refs coming from the parent component), I refactored the value list component to accept the add values …
> Always show the value list + hide "add values" on non-free text entries

- frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/RestrictiveLegalValues/RestrictiveLegalValues.tsx
We had issues, where when you selected the operator, these boxes were jumping up. The problem was that the illegal value checker was marking empty values as illegal also.
Now empty value is not included in illegal values.
> feat: remove warning boxes for empty values

- frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/RestrictiveLegalValues/RestrictiveLegalValues.tsx
Use event.preventDefault to prevent the app from trying to submit the legal values (or the strategy) form when you hit "enter" in the legal values filter input.
> Prevent legal value selection from triggering form submit

- src/lib/db/client-applications-store.ts
- src/lib/features/metrics/instance/instance-service.ts
- src/lib/features/scheduler/schedule-services.ts
- src/lib/types/experimental.ts
- src/lib/types/stores/client-applications-store.ts
- src/test/e2e/stores/client-application-store.e2e.test.ts
- src/test/fixtures/fake-client-applications-store.ts
Remove inactive applications (last_seen older than 30 days) from the application list
There is a delete cascade to client_applications_usage so this will be removed too.
The new capability is behind a flag.
There's seet_at and updated_at column and they seem to have the same value
> feat: remove inactive applications

- frontend/src/component/admin/filterAdminRoutes.test.ts
- frontend/src/component/admin/filterRoutesByPlanData.ts
- frontend/src/component/admin/useAdminRoutes.ts
- frontend/src/component/layout/MainLayout/AdminMenu/AdminNavigationItems.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/useRoutes.test.ts
- frontend/src/component/layout/MainLayout/NavigationSidebar/useRoutes.ts
https://linear.app/unleash/issue/2-2852/sidebar-bug-with-enterprisepro-only-route-constraints
Fixes an issue where admin routes didn't respect plan data if their flag was enabled.
First noticed here: https://github.com/Unleash/unleash/pull/8469#discussion_r1804361222
Issue was that only `adminRoutes` respected plan data. `mainNavRoutes` and `primaryRoutes` did not follow the same filtering logic.
We can probably clean this up even further in the future, but didn't want to extend the PR too much.
Also adds tests to validate the intended behavior.
> chore: fix admin routes should respect plan data

- frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/RestrictiveLegalValues/RestrictiveLegalValues.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraintWrapper.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/LegalValuesSelector.tsx
Fixes an issue with the new legal values selector where selecting an item from filtering or changing the checkbox state would move your focus to the top of the page. I think it's because we'd re-render the whole tree because of it, and this would clear your focus selection. To get around it, I've used the existing ResolveInput component. We might want to change this later as we get around to more input components (single values, etc), but for now, I think this is good enough.
As a bonus, I get to delete the most annoying part of the EditableConstraints file 😄 
The constraint still opens in edit mode for now, but I expect that to get resolved once we properly implement the split between editable and non-editable constraints that was started yesterday.
> 1-3658/fix legal values selector issues

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
Makes it so that the InputContainer is only rendered if we don't have the add values button up top. We might need to adjust this later (as we get more sketches for other input types, such as single numbers, single semvers etc), but it works for now.
With legal values  (no add values button)
Without legal values (but add values button)
Because we don't handle single value cases yet, some of those inputs are still stuck in an in-between state:
> Don't show extra input component if we have "add values" button

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/ConstraintOperatorSelect.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/ValueList.tsx
Fix a number of visual issues with the main editable constraint component.
I've introduced a few more layers of container nesting to make the layout break the right ways:
- Put everything on the same line when on wide.
- At 700px place selected values on the row below
- From 700px down, when necessary, also wrap operator options
Support super long context names without breaking layout
Wrap values at 700px width container:
Wrap operator options when necessary
Absolutely position delete button to allow to not push it out of the container on narrow screens: 
Remove extra focus styling from MUI (darken select background):
Before:
After:
> chore: second design pass for editable constraints

- frontend/src/component/layout/MainLayout/AdminMenu/AdminListItem.tsx
Hover text was black, now it's white
> chore: replace inherit color on menu item hover to common.white

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddSingleValueWidget.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddValuesPopover.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddValuesWidget.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/SingleValueWidget.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/ValueList.tsx
Adds an "add value" with popover input for single-value fields (numerical and semver operators).
The implementation re-uses the popover from the multi-value constraint operators, so I've extracted it for re-use.
All current input types:
For the new one, opening the popover when there's a value will pre-select the value, so you can override it by typing immediately:
Buttons look pretty identical:
I haven't set an input type anywhere on the popover yet. In theory, we could use input type "number" for numerical inputs and I think it's worth looking at that, but we don't do in the old implementation either. 
I've added a task for it.
This implementation uses a chip for the button/value display for the single. In almost all cases it works exactly as I'd expect, but closing the popover with esc …
> 1-3651/single value inputs

- frontend/src/component/common/Input/Input.tsx
- frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/DateSingleValue/DateSingleValue.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddValuesPopover.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/ConstraintDateInput.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
Adds a date input method for editable constraints.
Uses a modified version of `frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/DateSingleValue/DateSingleValue.tsx`, which has been marked as deprecated.
Wraps when necessary
Additionally, because I noticed how the old date input sets the error, I've switched to using the standard way of setting input errors in Unleash (and presumably for MUI)
> feat: add date type input field for constraints.

- frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/ResolveInput/ResolveInput.tsx
- frontend/src/component/common/NewConstraintAccordion/ConstraintAccordionEdit/ConstraintAccordionEditBody/useConstraintInput/useConstraintInput.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/resolve-legal-values.ts
Slight organizational update to get rid of the four different boolean states we had going on.
Primarily:
- creates `TopRowInput` component that gives you the right kind of input for the top row (all cases except for legal values, for which it returns null).
- Checks whether the input type is `legal values` before rendering the legal values input container.
Secondarily:
- Fixes the jank when adding new constraints
- extracts resolveLegalValues and improves performance (refer to the inline note)
> 1-3687/input mode separation

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddSingleValueWidget.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddValuesPopover.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddValuesWidget.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
Adds help text to the popover input for free text values, single numeric and semver values. The help text is in addition to the error text (so you can get both).
Also makes the add button a little narrower to better match sketches.
Multiple values (free text):
With error
Numeric operators:
SemVer operators:
> Add input help text

- frontend/src/component/feature/FeatureStrategy/FeatureStrategySegment/FeatureStrategySegment.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategySegment/RecentlyUsedSegments/RecentlyUsedSegments.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategySegment/RecentlyUsedSegments/useRecentlyUsedSegments.test.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategySegment/RecentlyUsedSegments/useRecentlyUsedSegments.ts
- frontend/src/hooks/api/actions/useFeatureStrategyApi/useFeatureStrategyApi.ts
Currently it is using the old badge, I need to create new or edit existing to support different actions.
> feat: recently used segments

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddSingleValueWidget.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/AddValuesPopover.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
Adds inputmode='decimal' to input fields with number input. As discussed on the [GOV.UK blog](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/), this finds a balance between giving numeric input options to mobile devices and improving validation / user experience.
They mention this bit in their [design system guideline](https://design-system.service.gov.uk/components/text-input/#numbers)
> Do not use `<input type="number">` unless your user research shows that there’s a need for it. With `<input type="number">` there’s a risk of users accidentally incrementing a number when they’re trying to do something else - for example, scroll up or down the page. And if the user tries to enter something that’s not a number, there’s no …
> chore(1-3679): use numeric input mode for numbers.

- src/lib/features/feature-toggle/feature-toggle-service.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
Cleans up the simplifyDisableFeature flag, and in doing so we're choosing the behavior that was put behind the flag.
This has been out for our hosted customers for a long time and we've not received any bug reports around it
> chore: flag cleanup simplifyDisableFeature

- frontend/src/component/providers/UnleashFlagProvider/UnleashFlagProvider.tsx
Did two things:
1. Use basePath to prefix the Unleash repo used with the Unleash Frontend SDK.
2. Use JSON.stringify as key for useEffect to avoid potential render loop
> fix: namespace flag-repo for unleash sdk

- src/lib/db/index.ts
- src/lib/features/metrics/client-metrics/metrics-service-v2.test.ts
- src/lib/features/metrics/client-metrics/metrics-service-v2.ts
- src/lib/features/metrics/unknown-flags/fake-unknown-flags-store.ts
- src/lib/features/metrics/unknown-flags/unknown-flags-controller.ts
- src/lib/features/metrics/unknown-flags/unknown-flags-service.ts
- src/lib/features/metrics/unknown-flags/unknown-flags-store.ts
- src/lib/features/scheduler/schedule-services.ts
- src/lib/metrics.ts
- src/lib/openapi/spec/index.ts
- src/lib/openapi/spec/unknown-flag-schema.ts
- src/lib/openapi/spec/unknown-flags-response-schema.ts
- src/lib/routes/admin-api/metrics.ts
- src/lib/services/index.ts
- src/lib/types/experimental.ts
- src/lib/types/services.ts
- src/lib/types/stores.ts
- src/migrations/20250424185110-unknown-flags.js
- src/server-dev.ts
- src/test/fixtures/store.ts
https://linear.app/unleash/issue/2-3406/hold-unknown-flags-in-memory-and-show-them-in-the-ui-somehow
This PR introduces a suggestion for a “unknown flags” feature.
When clients report metrics for flags that don’t exist in Unleash (e.g. due to typos), we now track a limited set of these unknown flag names along with the appnames that reported them. The goal is to help users identify and clean up incorrect flag usage across their apps.
We store up to 10 unknown flag + appName combinations, keeping only the most recent reports. Data is collected in-memory and flushed periodically to the DB, with deduplication and merging to ensure we don’t exceed the cap even across pods.
We were especially careful to make this implementation defensive, as unknown flags could be reported in very high …
> chore: unknown flags

- frontend/src/component/admin/apiToken/ApiTokenForm/TokenInfo/TokenInfo.tsx
- frontend/src/component/admin/apiToken/ApiTokenForm/useApiTokenForm.ts
- frontend/src/component/admin/apiToken/CreateApiToken/CreateApiToken.tsx
- frontend/src/component/environments/EnvironmentTable/EnvironmentActionCell/EnvironmentCloneModal/EnvironmentCloneModal.tsx
- frontend/src/component/onboarding/dialog/GenerateApiKey.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectApiAccess/CreateProjectApiTokenForm.tsx
- frontend/src/hooks/api/actions/useApiTokensApi/useApiTokensApi.ts
- frontend/src/hooks/api/actions/useProjectApiTokensApi/useProjectApiTokensApi.ts
PR: Stop using username and switch to tokenname when creating tokens in the frontend
Splitting up the work on API-Token username->tokenname refactor into separate PRs for separate things. This PR should be able to go to main since we've already introduced tokenname in the API and deprecated username.
> chore: use tokenname instead of username in frontend for api-token creation

- .lycheeignore
This url is used as an example in a page
> chore: ignore sample cdn url

- frontend/src/component/common/ConstraintsList/ConstraintItemHeader/isCaseSensitive.test.ts
- frontend/src/component/common/ConstraintsList/ConstraintItemHeader/isCaseSensitive.ts
- frontend/src/constants/operators.test.ts
- frontend/src/constants/operators.ts
This is a helper PR for a refactor I'm working on for the new constraint inputs. In the refactoring, it's useful to have individual subtypes for the various subgroups of operators and to be able to easily assert whether something is X operator or not.
The only change required in the code base is a single check for operators, which is now handled by using the new `isXOperator` functions instead.
Yes, the operator file in constants now includes functions, but it seemed useful to put the identification functions there instead of somewhere unrelated. The tests are primarily to ensure that the identifier function works, and I'd be happy to remove them if we think it's necessary. That said, they're pretty simple unit tests, so I think it's fine to leave them.
The main bulk of the change is: …
> chore: make operator checking more ergonomic and type-ful

- src/lib/features/metrics/unknown-flags/unknown-flags-store.ts
https://linear.app/unleash/issue/2-3561/fix-duplicate-key-errors-in-unknown-flags
This should prevent `duplicate_key` errors in unknown flags.
Follow-up to: https://github.com/Unleash/unleash/pull/9837
> chore: prevent duplicate key errors in unknown flags

- frontend/src/component/feature/StrategyTypes/FlexibleStrategy/FlexibleStrategy.tsx
- frontend/src/component/feature/StrategyTypes/RolloutSlider/ConditionalRolloutSlider.tsx
- frontend/src/component/feature/StrategyTypes/RolloutSlider/LegacyRolloutSlider.tsx
- frontend/src/component/feature/StrategyTypes/RolloutSlider/RolloutSlider.tsx
- frontend/src/component/feature/StrategyTypes/StrategyParameter/StrategyParameter.tsx
- frontend/src/component/releases/ReleasePlanTemplate/TemplateForm/MilestoneStrategy/MilestoneStrategyTypeFlexible.tsx
- src/lib/features/frontend-api/frontend-api-controller.ts
Add input box for gradual rollout slider.
Was not able to get it aligned nicely in the middle of horizontal slider, so its just inline with the row for now. Yes, just adding random padding did work, but that felt too artificial.
This is also behind feature flag. We can improve small CSS stylings in future iterations.
Added % also for the input, as it felt more correct.
> feat: add input box for gradual rollout slider

- frontend/src/component/menu/Footer/ApiDetails/ApiDetails.tsx
- frontend/src/component/menu/Footer/ApiDetails/__snapshots__/ApiDetails.test.tsx.snap
- frontend/src/component/menu/Footer/Footer.tsx
- frontend/src/component/menu/Footer/__snapshots__/Footer.test.tsx.snap
This will stop displaying the semver version for our hosted (i.e. managed) customers, as it has become less relevant over time. It remains valuable for self-hosted users.
> chore: remove semver version from footer and proxy from sdk list

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/legal-value-functions.test.ts
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/legal-value-functions.ts
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/useEditableConstraint.tsx
Extracts and tests the implementation of the functions to get deleted and invalid legal values.
This is pretty straightforward stuff and arguably not crucial, but it was an easy place to start and I don't think it hurts to have these in place anyway.
> Test(1-3733): get invalid and deleted legal values

- frontend/src/component/integrations/IntegrationList/AvailableIntegrations/AvailableIntegrations.tsx
- frontend/src/component/menu/Footer/ApiDetails/ApiDetails.tsx
- frontend/src/component/menu/Footer/ApiDetails/__snapshots__/ApiDetails.test.tsx.snap
- frontend/src/component/menu/Footer/Footer.tsx
- frontend/src/component/menu/Footer/__snapshots__/Footer.test.tsx.snap
Removing proxy from integrations as it's been deprecated while ago and currently unmaintained
> chore: remove proxy from integrations

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/constraint-reducer.test.ts
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/constraint-reducer.ts
Adds a fairly comprehensive test suite for the constraint reducer. I put in all cases I thought were relevant. 
As part of this, I discovered one bug, and changed two actions.
The bug was toggling on the wrong property when you tried to invert case sensitivity.
The action changes are:
- rename "remove value from list" to "remove value"
- remove "set value" in favor of instead letting "add value(s)" work in single-value constraints too.
> test(1-3734): test constraint reducer

- src/lib/services/user-service.ts
Part of: https://linear.app/unleash/issue/2-3560/payg-flow-sends-2-email-one-from-bluebird-and-one-from-unleash-we-want
This laxes our `user` argument in `newUserInviteLink` to just pick the id, since that's the only property we're interested in. This allows us to send `{ id }` when we don't have the full `IUserWithRootRole` available while keeping compatibility intact.
> refactor: lax newUserInviteLink user arg

- frontend/src/component/common/NewConstraintAccordion/NewConstraintAccordionList/NewConstraintAccordionList.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/FeatureStrategyConstraintAccordionList/FeatureStrategyConstraintAccordionList.tsx
Currently the issue was that if this flag gets removed, we will be still left with NewConstraintAccordionList, but we want to get rid of this.
Now when flag gets removed, we can remove that component and also if setConstraints is empty, we will just not render anything.
I tested manually and rendering null is appropriate in this current file.
> chore: fix setConstraints being undefined/null

- src/lib/features/project/project-store-type.ts
- src/lib/features/project/project-store.e2e.test.ts
- src/lib/features/project/project-store.ts
- src/test/fixtures/fake-project-store.ts
Add `getProjectLinkTemplates` method to ProjectStore and corresponding test. Ideally this should be in a read-model, but let's finish link templates end to end
> feat: add getProjectLinkTemplates method

- frontend/src/component/common/NewConstraintAccordion/ConstraintsList/EditableConstraintsList.tsx
- frontend/src/component/common/NewConstraintAccordion/NewConstraintAccordionList/NewConstraintAccordionList.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/useEditableConstraint.test.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/useEditableConstraint.tsx
Adds a test suite for the useEditableConstraint hook, attempting to test all the parts of it that we can't test in isolation. 
Plus: a few, small refactorings:
- Renames `onAutoSave` on `onUpdate` to better match `onDelete` (and because autosave doesn't really mean anything anymore).
- Simplifies and collapses some types
> test/refactor: useEditableConstraint hook

- .github/workflows/check_links.yaml
When being throttled assume the link is ok, eventually someday it will be checked
Already tested it works on this branch: https://github.com/Unleash/unleash/actions/runs/14993127371
> chore: accept 429 responses

- frontend/cypress/support/API.ts
- src/lib/features/project/project-service.ts
https://linear.app/unleash/issue/2-3363/remove-post-apiadminprojectsprojectidroleroleidaccess-deprecated-in
Removes POST `/api/admin/projects/{projectId}/role/{roleId}/access` which was deprecated in v5.5.
Also cleans up related code.
Needs follow up PRs.
> refactor: remove deprecated post project role access endpoint

- src/lib/routes/admin-api/strategy.ts
- website/docs/reference/activation-strategies.md
- website/docs/reference/custom-activation-strategies.md
Removes the deprecation notice on custom strategies, also removes these notices from docs
> chore: undeprecate custom strategies

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/LegalValuesSelector.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/constraint-reducer.test.ts
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/constraint-reducer.ts
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/useEditableConstraint.test.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/useEditableConstraint/useEditableConstraint.tsx
This PR implements a number of strategies to make the app perform better when you have large lists. For instance, we have a constraint field that has ~600 legal values. Currently in main, it is pretty slow and sloggy to use (about on par with what we see in hosted).
With this PR, it becomes pretty snappy, as shown in this video (should hopefully be even better in production mode?):
https://www.loom.com/share/2e882bee25a3454a85bec7752e8252dc?sid=7786b22d-6c60-47e8-bd71-cc5f347c4e0f
The steps taken are:
1. Change the `useState` hook to instead use `useReducer`. The reason is that its dispatch function is guaranteed to have a stable identity. This lets us use it in memoized functions and components.
2. Because useReducer doesn't update the state variable until the next render, we need to use …
> Chore(1-3688): improve performance for large lists of legal values

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
There can be any number of these on a page, so setting autofocus here is a Bad Idea (TM). It's probably a holdover from when the input was an accordion and we wanted to give you focus when you opened it (we do a similar thing for the popover, for instance).
This property will cause you to focus (and potentially scroll) to the last constraint on the page.
> fix(1-3740): Don't autofocus the editable constraint field.

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint.tsx
Uses a purple color for the hover underline. Also, sets it to be transparent when not-hovered, so that you get a nice fade in effect.
Focus (top) and hover (bottom) now have the same visual style, but different ways to get to that state (expansion vs fade-in):
> Make hover underline purple

- frontend/src/hooks/api/getters/useFeature/useFeature.ts
All our servers have had this for a while on every feature open.
This PR fixes it by making request only conditionally.
The featureFetcher function also specifically handles 404 responses by returning `{ status: 404 }`, which makes the behavior consistent whether the API returns a 404 or the condition prevents the API call from happening at all.
This approach avoids unnecessary API calls when parameters are missing and provides a consistent interface for handling "not found" scenarios in the component that uses this hook.
> fix: now feature is not pulled from server if not defined

- frontend/src/component/archive/ArchiveTable/ArchiveTable.test.tsx
- frontend/src/component/archive/ArchiveTable/ArchiveTable.tsx
- frontend/src/component/archive/ArchiveTable/FeatureArchivedCell/FeatureArchivedCell.tsx
- frontend/src/component/archive/FeaturesArchiveTable.tsx
- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
Related to:
- https://linear.app/unleash/issue/2-3366/remove-get-apiadminarchivefeatures-deprecated-in-4100
- https://linear.app/unleash/issue/2-3367/remove-get-apiadminarchivefeaturesprojectid-deprecated-in-4110
Brings back the overall flag archive page and table using the feature flag search endpoint.
> chore: revive archive page

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint/EditableConstraint.tsx
- src/lib/features/context/context.ts
- src/lib/features/feature-toggle/feature-toggle-service.ts
- src/test/e2e/api/admin/constraints.e2e.test.ts
Improves handling of constraints in use that have been deleted.
This change implments a few small changes on both the front and the back end on how we deal with constraints that have been deleted.
The most important change is on the back end, in the `/constraints/validate` endpoint. We used to throw here if the constraint couldn't be found, but the only reason we wanted to look for the constraint in the db was to check for legal values. Now, instead, we'll allow you to pass a constraint field that doesn't exist in the database. We'll still check the values against the operator for validity, we just don't control legal values anymore (because there aren't any).
On the front end, we improve the handling by showing the deleted context filed in the dropdown, both when the selector dropdown is …
> Fix(1-3485)/handle deleted constraints

- frontend/src/component/context/ContextList/ContextActionsCell.tsx
- frontend/src/component/context/ContextList/ContextList/ContextList.tsx
Blocks deletion of context fields from the UI if the context field has any usage.
> chore: disable delete button if a context field has usage

- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
- frontend/src/component/project/ProjectList/ProjectArchiveLink/ProjectArchiveLink.tsx
- frontend/src/component/project/ProjectList/ProjectList.tsx
https://linear.app/unleash/issue/2-3569/fix-hide-project-archive-in-oss
Hides "project archive" in OSS.
I believe this is a bug. OSS only has one project and the project archive was acting unexpectedly anyways since it was showing the same default project as being archived. This is because in OSS we use the OSS project-controller, not the Enterprise version (override) of it.
> fix: hide project archive in OSS

- src/lib/features/frontend-api/frontend-api.e2e.test.ts
- src/lib/features/metrics/client-metrics/fake-client-metrics-store-v2.ts
- src/lib/features/metrics/client-metrics/metrics-service-v2.test.ts
- src/lib/features/metrics/client-metrics/metrics-service-v2.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
- src/test/e2e/api/client/metrics.access.e2e.test.ts
- src/test/e2e/api/client/metricsV2.e2e.test.ts
https://linear.app/unleash/issue/2-3564/remove-filterexistingflagnames-feature-flag
We're removing the `filterExistingFlagNames` feature flag since we've decided we want this to be the default behavior.
We don't need to rush to merge it, just in case we need to disable this for any reason. However it should also be pretty easy to just revert if needed.
Changes in tests are a bit tricky since they assumed the previous behavior where we always registered metrics, even for non existing flag names. `cachedFeatureNames` is also memoized with a TTL of 10s, so the easiest way to overcome this was to override `cachedFeatureNames` to return what we expected. As long as they return the same flag names that we expect, we're able to register their metrics.
Let me know if you can think of a better …
> chore: remove filterExistingFlagNames feature flag

- src/lib/openapi/spec/health-check-schema.ts
- website/docs/reference/api/legacy/unleash/internal/health.md
Our health implementation always returns GOOD if the server is up: https://github.com/Unleash/unleash/blob/beb29f5b5bbff620097fa822e2dff6b68a11adab/src/lib/routes/health-check.ts#L46-L51
Currently our documentation of the endpoint is misleading saying that it will return BAD if unable to connect to PostgreSQL
Closes #9965
> docs: explain health API properly

- frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.test.tsx
- frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/IconRenderer.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationList.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/NavigationSidebar.test.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/__snapshots__/NavigationSidebar.test.tsx.snap
- frontend/src/component/menu/__tests__/__snapshots__/routes.test.tsx.snap
- frontend/src/component/menu/routes.ts
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/AvatarCell.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/features/feature-search/feature-search-store.ts
- src/lib/features/feature-search/feature.search.e2e.test.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
Removing the `flagsReleaseManagementUI` and `flagsOverviewSearch` feature flags - we're keeping these enabled.
Closes [internal ticket 1-3683](https://linear.app/unleash/issue/1-3683)
- `/src/unleash/core/frontend/src/component/feature/FeatureToggleList/FeatureToggleListTable.tsx` - large diff
> chore: remove flagsReleaseManagementUI and flagsOverviewSearch flags

- .github/workflows/docker_publish.yaml
We're building with node 22 locally, so our docker image should also use node 22. This PR bumps our docker workflow to use 22.15.1 image.
> task(ci): Bump base image for OSS docker

- package.json
- src/lib/addons/teams.ts
- src/lib/features/metrics/instance/metrics.ts
Make `start:dev` re-use `dev:backend`, the only difference is start:dev runs a clean before running
> chore: remove console.log and reuse package scripts

- frontend/src/component/insights/InsightsCharts.tsx
Removes the "median time to production" snapshot + graph when the lifecycleMetrics flag is active.
In other words: this entire box is gone 💨
> Remove entire row for median time to production

- frontend/src/component/insights/InsightsCharts.tsx
- frontend/src/component/insights/LegacyInsightsCharts.tsx
- frontend/src/component/insights/components/InsightsHeader/InsightsHeader.tsx
Creates sections for the insights dashboard and moves charts around into the same order as the sketches and into the right sections. There's no charts for the top section (lifecycle currently) yet, and the sections also don't have their own filters. 
To make this re-ordering easier, I've also moved the previous insights chart into a legacy file and set up a proxy component that handles switching based on the flag.
Next step is separating the filters.
> Chore(1 3755)/split insights in three

- src/lib/events/index.ts
- src/lib/server-impl.ts
Exposes configuration revision service UPDATE_EVENT constant so it can be used, and we also add a new event for cdn token created
> feat: add required cdn events

- package.json
https://github.com/Unleash/unleash/actions/runs/15298694489/job/43037677429#step:10:360 we are failing to copy docs because we removed them
> fix: removed docs folder and replaced with openapi-static

- src/lib/services/openapi-service.ts
As an example, I've deprecated the endpoint to get environments for a project and this is how it's reflected in the UI and the web console:
Also logs will output:
```
[2025-05-29T10:05:45.198] [WARN] openapi-service.ts - Deprecated endpoint: getProjectEnvironments at /project/default
```
> feat: fail in dev when usign deprecated endpoints

- frontend/src/component/common/ConstraintsList/ConstraintItemHeader/ConstraintItemHeader.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint/EditableConstraint.tsx
The case sensitive buttons looked off in dark mode because we'd forgotten to properly target the path element. We didn't notice, because they looked right in light mode.
Dark:
Light:
Dark:
Light:
> fix: case sensitive icon has wrong fill color in dark mode

- src/migrations/20250530103216-lifecycle-trends.js
Adding a single table to capture all lifecycle trends data.
One field presents a challenge: `median_time_in_stage_days`. This value is calculated per `stage`, not per `flag_type`. As a result, we would need to duplicate the total median time across each flag type. This isn’t a major issue.
An alternative would be to create a separate table solely for the median values, but that seems like overkill.
> feat: lifecycle trends migration

- frontend/src/hooks/api/getters/useInstanceTrafficMetrics/useInstanceTrafficMetrics.ts
https://linear.app/unleash/issue/2-3370/remove-get-apiadminmetricstrafficperiod-deprecated-in-680
Removes GET `/api/admin/metrics/traffic/{period}` which was deprecated in v6.8.
Also cleans up related code.
For OSS this means switching to `/traffic` using an expand and contract approach. We can drop the `/traffic-search` endpoint in Enterprise after this is merged.
> chore!: remove deprecated get metrics traffic

- Dockerfile
- docker/index.js
The docker image was trying to load as CJS module:
```
unleash-1  | node:internal/modules/cjs/loader:1404
unleash-1  |   throw err;
unleash-1  |   ^
unleash-1  | 
unleash-1  | Error: Cannot find module './build'
unleash-1  | Require stack:
unleash-1  | - /unleash/index.js
unleash-1  |     at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
unleash-1  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
unleash-1  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
unleash-1  |     at Function._load (node:internal/modules/cjs/loader:1211:37)
unleash-1  |     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
unleash-1  |     at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
unleash-1  |     at Module.require …
```
> fix: docker oss image now running with ESM

- src/migrations/20250604100546-lifecycle-trends-general.js
- **Updated `stage` column constraint**
- **Old values:** `'initial', 'develop', 'production', 'cleanup', 'archived'`
- **New values:** `'initial', 'pre-live', 'live', 'completed', 'archived'`
- **Replaced `flag_type` CHECK constraint with a foreign key**
- Removed hardcoded values: `'experimental', 'release', 'permanent'`
- Added foreign key:
```sql
FOREIGN KEY (flag_type) REFERENCES feature_types(id) ON DELETE CASCADE
```
- **Added down migration** to:
- Restore original `stage` constraint
- Drop the foreign key on `flag_type` and re-add the original CHECK constraint
- Align `stage` values with lifecycle model
- Use the `feature_types` table to ensure referential integrity
> feat: make lifecycle trends more detailed

- frontend/package.json
- frontend/src/component/insights/components/LifecycleChart/LifecycleChart.tsx
- frontend/src/component/insights/components/LifecycleChart/LifecycleChartComponent.tsx
- frontend/src/component/insights/sections/LifecycleInsights.tsx
- frontend/yarn.lock
Adds lifecycle trend graphs to the insights page.
The graphs are each placed within their own boxes. The boxes do not have any more information in them yet. 
Also, because the data returned from the API is still all zeroes, I've used mock data that matches the sketches.
Finally, the chart configuration and how it's split into a LifecycleChart that lazy loads a LifecycleChartComponent is based on the LineChart and LineChartComponent that we use elsewhere on the insights page.
Light mode:
We might want to tweak some colors in dark mode, but maybe not? 🤷🏼
> feat: add lifecycle trend graphs

- frontend/src/component/insights/components/InsightsHeader/InsightsHeader.tsx
- frontend/src/component/layout/MainLayout/NavigationSidebar/ListItems.tsx
Update the title of the insights / analytics page when the menu item changes
While the side menu item has already changed, this change also updates the page header and title.
Also fixes an error with a prop that shouldn't have been forwarded.
> chore: rename insights -> analytics

- frontend/src/component/common/HelpIcon/HelpIcon.tsx
- frontend/src/component/insights/componentsStat/FlagStats/FlagStats.tsx
Switches the "flags per user" box with a "total number of flags" label for the number in the box and an additional description available via the help icon.
To accurately label the help text and link it to the figure, I've added a tooltipId prop to the HelpIcon component.
> chore: replace flags per user with total number of flags

- frontend/src/component/insights/sections/LifecycleInsights.tsx
Updates the skeleton loading colors for the lifecycle trend tiles because the previous color was invisible on the median stats section in light mode. You also wouldn't see any movement in the total number of flags.
I have not touched the original skeleton color assignment because that might have unintended consequences throughout the app. Also, I'm not aware of a way (at the moment) that would do this automatically when necessary. As such, I have only touched the loading indicators in the lifecycle tile.
Light mode:
Dark mode:
Light mode:
Dark mode:
> chore: fix skeleton loading indicator colors for lifecycle trend tiles

- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
https://linear.app/unleash/issue/2-3602/clean-up-flag-enterprise-payg
Removes [enterprise-payg](https://app.unleash-hosted.com/hosted/projects/eg/features/enterprise-payg)
Doesn't seem like this is being used anywhere.
> chore: remove flag enterprise-payg

- src/lib/features/instance-stats/instance-stats-service.ts
- src/lib/services/version-service.test.ts
- src/lib/services/version-service.ts
Added two new fields to FeatureInfo (what gets reported as telemetry) reporting license type and hostedBy. Will be overriden in Enterprise.
> feat: report hostedBy and licenseType

- .github/workflows/dependency-review.yml
http://docs.python.org/license.html states that though GPL-compatible, PSF allows usage without having to redistribute own source code.
> chore: Add PSF to approved licenses list

- frontend/src/component/common/NewConstraintAccordion/ConstraintsList/EditableConstraintsList.tsx
- frontend/src/component/segments/EditSegment/EditSegment.tsx
This adds constraint ids to segment constraints used in editing segments. Without them, there was a bug where when you went to edit the segment, all constraints would be invisibly set to the same constraint.
This was extra insidious because the edit form would show you the correct set of constraints, but the API payload would update to only repeat the one constraint over and over again. You'd only notice the next time you went into the segment, when both constraints would be the same 🐛
> fix: constraint editing is broken in segment form

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint/useEditableConstraint/editable-constraint-type.test.ts
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint/useEditableConstraint/editable-constraint-type.ts
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint/useEditableConstraint/useEditableConstraint.test.tsx
Prevents the property order from changing when constraints are set from the editable constraint component. When we render out the API command, we don't specify the order of properties in the objects, which means that it can change dramatically, which can be a little jarring. 
As it is right now, it first renders in one order when you open the strategy form:
And when you navigate to the targeting section of the strategy form, it changes to:
This also applies to constraints in segments.
With this change, the order will remain the same before and after.
Additionally, there's some extra tests around constraint ids being kept the same and being set if it doesn't exist.
This came about as part of the issue we had with constraint editing in segments being broken as of now. As part of that, I …
> fix: Order properties correctly when mapping from Editable Constraint to IConstraint

- src/lib/__snapshots__/create-config.test.ts.snap
- src/lib/create-config.ts
- src/lib/types/option.ts
- src/server-dev.ts
API url, similar to `config.prometheusApi`, for impact metrics
> feat: add prometheusImpactMetricsApi option to configuration

- frontend/src/component/events/EventDiff/EventDiff.tsx
Contains several improvements for the new json diff render:
1. Removes extra left-inset of the +/- icons for changed lines. This means that the +/- icons will now show up in the change request popover, whereas they were hidden (pushed outside the frame) previously).
2. Change styling based on whether it's an edit or a full replacement. If it's an edit, keep the +/- icons per changed line. If it's a full replacement (e.g. the object has been created or deleted), don't show the +/- icons, and make the whole object the right color (specifically: this also colors the surrounding braces that weren't colored before). Not showing +/- for new/deleted objects is in line with how the previous system worked.
3. If there are no changes, show `(no changes)`, as we did before. Unfortunately, I don't …
> Chore(1 3836)/no changes in json diff

- src/lib/features/metrics/instance/metrics.ts
- src/lib/routes/client-api/index.ts
- src/lib/types/experimental.ts
Accepts the new impact metrics into the singleton registry and then does nothing with them. If the relevant flag is off, the metrics are stripped from the existing metrics data format and dropped on the floor
> feat: ingest new impact metrics

- src/migrations/20250623100820-cr-requested-approvals-add-notified-at-column.js
Adding this should allow us to only notify users that haven't been notified before.
Necessary because the change_added event does not include a preData that allowed us to diff requestedApprovers based on the event alone. 
Also added a index on this column, since we're going to be using it to filter.
> task: added notified at to change request requested approvals

- src/lib/db/transaction.test.ts
- src/lib/db/transaction.ts
Replace generating random number id based on timestamp and now use ulids.
> feat: transaction grouping, use ulids and strings

- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
This change adds the `crDiffView` flag to Unleash, potentially enabling the new JSON diff tab in change request changes instead of the "view json diff" hover functionality.
> add `crDiffView` to Unleash

- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestRequestedApprovers/ChangeRequestRequestedApprovers.tsx
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestReviewers/ChangeRequestReviewer.tsx
- frontend/src/component/changeRequest/ChangeRequestSidebar/DraftChangeRequestActions/DraftChangeRequestActions.tsx
- frontend/src/component/changeRequest/ChangeRequestSidebar/EnvironmentChangeRequest/EnvironmentChangeRequest.tsx
- frontend/src/hooks/api/actions/useChangeRequestApi/useChangeRequestApi.ts
- frontend/src/hooks/api/getters/useRequestedApprovers/useRequestedApprovers.ts
This adds requested approvers to change request overview
> feat(changerequests): add requested approvers to overview

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/EnvironmentStrategyExecutionOrder/EnvironmentStrategyExecutionOrder.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/EnvironmentStrategyExecutionOrder/EnvironmentStrategyOrderDiff.tsx
Adds the same tab interface to env execution order changes as to other diffable changes.  Instead of creating a new file, this one just duplicates and changes the component that we wanna touch.
Change 
Diff
> add tabs to strategy sort order

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/FeatureChange.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx
We don't want deleted strategies to have the red background color anymore with the new change/diff view. As such, we can remove it in the new component and add a todo to delete the css for it after it's gone.
> Remove the red coloration of deleted strategy change boxes

- frontend/src/component/events/EventLog/useEventLogSearch.ts
- src/lib/features/events/event-service.ts
- src/lib/openapi/spec/event-search-query-parameters.ts
- src/lib/types/stores/event-store.ts
- src/test/e2e/api/admin/event-search.e2e.test.ts
Now when you put group ID as query param, it will filter based on transaction id.
I am not sure if its best naming, whether it should be groupId or transactionId, I will leave as group for now, but its simple change later.
> feat: now it is possible to search events by group id

- frontend/src/component/events/EventLog/EventLogFilters.test.tsx
- frontend/src/component/events/EventLog/EventLogFilters.tsx
- frontend/src/component/events/EventLog/useEventLogSearch.ts
Also added ID as removable param, which can not be added from badge, but can be added as query param.
> feat: add id as removable param for event list

- src/lib/addons/webhook.test.ts
- src/test/e2e/services/playground-service.test.ts
One thing that can make tests fail is console.out, as it produces IO.
> fix: remove console log from tests

- src/lib/features/events/event-service.ts
- src/lib/services/addon-service.ts
This is attempt to fix tests, as I caught this service failing in the stacktrace.
Basically the event handlers were not cleaned up during stop.
1. Test ends → stopUnleash() is called
2. services.addonService.destroy() called → but this only destroyed addon providers, not event handlers
3. await db.destroy() called → destroys database connection pool
4. Event comes in → triggers handleEvent → calls fetchAddonConfigs() → tries to query destroyed database
5. Database query fails with "Error: aborted"
6. Node.js catches this → db-migrate's fatal handler → process.exit(1)
> fix: tear down also event handlers in addon service

- frontend/src/component/changeRequest/ChangeRequest/ChangeRequest.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/FeatureChange.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/LegacyStrategyChange.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/StrategyChange.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ToggleStatusChange.tsx
Updates handling of default changes by letting the change components themselves handle adding necessary text instead of passing it down as "actions" (when text isn't really an action ...).
There's two cases where we add default changes to a CR:
1. If you enable an environment that has no strategies, then we add the default strategy.
2. If you disable or remove the last strategy on an active environment (such that the environment would now have 0 active strategies), then we disable the environment too and add that to the change request.
Here's what they look like in the new design:
And because it seemed the easiest way to do it, I've also updated the old design to do the same thing. It looks the same as it used to:
> Add "feature status will change"

- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/ChangeSegmentName.tsx
- frontend/src/component/changeRequest/ChangeRequest/Changes/Change/SegmentChangeDetails.tsx
Fixes a bug where we wouldn't show the changed segment name in segment changes. This bug appears to have been around for a while, but this fix does not touch the legacy version. Reintroduces the ChangeSegmentName component to make the names stack correctly (vertically instead of horizontally)
Before: 
After:
> fix segment changed name not showing

- frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
The max width is set to `max(40vw, 1000px)`, so that if you're on a very wide window, then it'll take up at most 40% of the horizontal space. Once your window is smaller than 2500px, however, the sidebar will stop shrinking and stay at 1000px (or as close to that as the window allows). It'll keep shrinking with the window size.
This came up because in certain cases, such as if you have a release template with a long description, the modal would just keep growing until it took up 98% of the window width.
I have not set a min width for now. I don't think there is any need for it, but if we find there is, we can add it back later.
Before:
After:
> Set a max width on the CR sidebar instead of a min width.

- frontend/src/component/changeRequest/ChangeRequestSidebar/ChangeRequestSidebar.tsx
Uses a fixed-width sidebar component instead of the dynamic sidebar component for the change request sidebar. This fixes a case where the modal would suddenly grow narrower when a change was sent to review (introduced in https://github.com/Unleash/unleash/pull/10307):
Before submitting (in main)
After submission (in main)
Before submitting (on this branch)
After submission (on this branch)
I don't see any reason why the CR sidebar should be dynamic, so making it fixed width with the solution we already have seems pretty sensible to me. Keeps things consistent and prevents us from solving the same problem multiple times in multiple ways.
Yes this change makes the sidebar a little wider, but I think that's fine. It's also closer to what it was previously, I think. Again, we can rethink this …
> chore: Use fixed-width sidebar instead of dynamic modal.

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint/AddSingleValueWidget.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyConstraints/EditableConstraint/AddValuesPopover.tsx
Doesn't clear the value from the constraint input value popover if you close it and then re-open. In other words, if you accidentally click out, you don't lose your progress. Instead, the popover will open again, with the value you had when you closed it highlighted (so that it's easy to type over if you want to):
The reason I'm changing this now is because I noticed that the error wasn't cleared correctly when the popover was closed. If we do it this way instead, then that makes sense, because you can still see the value. This is also how the single-value popover has worked forever.
From some quick testing, the single value popover still works as expected: 
As a side note: I'm adding a comment to anyone coming after as to why focus handling on escape doesn't work correctly on the single …
> Chore(1 3895)/small input tweaks

- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
This moves the apply button to a separate section (when request approvers is enabled), to prevent accidentally applied CRs stemming from requesting more than necessary approvers and the extra approver arrives at an approved and ready CR and then accidentally clicks apply.
We move the Changes overview StyledPaper into a StyledDiv so we can stack StyledPapers as rows inside the column
> feat: move apply button to a separate section

- src/migrations/20250708173000-amend-users-created-events.js
- src/test/e2e/api/admin/user-admin.e2e.test.ts
Users could have been created in Unleash without a corresponding event (a.k.a. audit log), due to a non transactional user insert ([fix](https://github.com/Unleash/unleash/pull/10327)). This could have happened because of providing the wrong role id or some other causes we're not aware of.
This amends the situation by inserting an event for each user that exists in the instance (not deleted) and doesn't have it's corresponding user-created event. 
The event is inserted as already announced because this happened in the past.
The event log will look like this (simulated the situation in local dev):
```json
{
"id": 11,
"type": "user-created",
"createdBy": "unleash_system_user",
"createdAt": "2025-07-08T16:06:17.428Z",
"createdByUserId": null,
"data": {
"id": "6",
"email": "xyz@three.com"
}, …
```
> chore: amend user-created-missing events

- frontend/src/component/impact-metrics/ChartItem.tsx
- frontend/src/component/impact-metrics/types.ts
- frontend/src/hooks/api/getters/useImpactMetricsSettings/useImpactMetricsSettings.ts
Swap internal impl metric name for user provided name in the SDK
Details:
* ChartConfig type is used for writing new charts
* DisplayChartConfig is same as ChartConfig plus it has backend calculated human friendly display and metric type
> feat: use metric display name in impact charts

- frontend/src/component/impact-metrics/ImpactMetricsControls/ImpactMetricsControls.tsx
Include Show RPS checkbox only for counters as it doesn't make sense for gauges.
I am also planing another change to get rid of this boolean flag (booleans are usually a very poor modelling primitive).
What I want to have instead are unions for counters (total | rps) and gauges (sum | avg)
> feat: show rps only for counters

- src/lib/db/client-instance-store.ts
- src/lib/features/metrics/instance/instance-service.test.ts
- src/lib/features/metrics/instance/instance-service.ts
- src/lib/features/metrics/instance/metrics.ts
- src/lib/openapi/spec/create-application-schema.ts
- src/lib/types/model.ts
- src/test/e2e/api/admin/applications.e2e.test.ts
Fixes a bug where `registerInstance` and `register{Frontend|Backend}Client` would overwrite each other's data in the instance service, leading to the bulk update being made with partial data, often missing SDK version. There's a different issue in the actual store that causes sdk version and type to be overwritten when it's updated (because we don't use `setLastSeen` anymore), but I'll handle that in a different PR.
This PR adds tests for the changes I've made. Additionally, I've made these semi-related bonus changes:
- In registerInstance, don't expect a partial `IClientApp`. We used to validate that it was actual a metrics object instead. Instead, update the signature to expect the actual properties we need from the cilent metrics schema and set a default for instanceId the way Joi did. …
> fix: don't overwrite `seenClients` in instance-service; merge if same client appears again

- .github/workflows/build_doc_prs.yaml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e.frontend.yaml
Currently, if a PR is open and a push happens, the **e2e:frontend** workflow will start running. If, shortly after a subsequent push on the *same* PR happens, the workflow will start running again without cancelling the previous (now obsolete) run. With these changes, the first run would be cancelled, thus **saving compute resources** (see below for quantity) that can be used to **speed up your overall CI/CD**, without sacrificing functionality, since the second run will contain the changes from the first push as well. 🌱
Here is an example of the behaviour described above: the commit `b1b2e61` triggered [this](https://github.com/Unleash/unleash/actions/runs/14493085673/) workflow run, and shortly after the commit `9997fe1`, that happened on top of the first commit, triggered …
> [CI]: Cancel CI runs that become obsolete

- src/lib/features/metrics/client-metrics/metrics-service-v2.test.ts
- src/lib/features/metrics/client-metrics/metrics-service-v2.ts
- src/lib/features/metrics/instance/metrics.ts
- src/lib/features/metrics/unknown-flags/unknown-flags.e2e.test.ts
https://linear.app/unleash/issue/2-3705/only-emit-client-metrics-after-sifting-metrics
Only emits the `CLIENT_METRICS` event after metric sifting.
This ensures the event is emitted only for valid metrics tied to known flags, instead of all flags included in the metrics payload.
See: https://github.com/Unleash/unleash/pull/10375#discussion_r2218974109
> chore: emit CLIENT_METRICS event after sifting

- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
Adds flag to OSS for the new timestamps in CR timeline capability.
We might not need them in the UI, but might as well add it in case.
> Add timestampsInChangeRequestTimeline flag

- .github/workflows/build_coverage.yaml
- README.md
- package.json
- yarn.lock
We've been using vitest for coverage and we use a github action to push results to coveralls, so this should work just fine
Unlocks form-data to be able to fix https://github.com/Unleash/unleash/security/dependabot/267
Also, removing coverage from PRs to avoid running tests twice
> chore(security): remove coveralls dependency

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
https://linear.app/unleash/issue/2-3711/add-strategy-modal-shows-release-templates-section-for-non-enterprise
Fixes a bug for non-Enterprise where release templates were mentioned (and even linked to) even though they were not available for these plans. When following the link the result was a page that did not render.
Also slightly refactors and improves this component.
> fix: add strategy release templates visibility for non Enterprise

- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.test.tsx
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
- frontend/src/component/changeRequest/changeRequest.types.ts
Adds a timestamp for each state we have time (and that isn't a state downstream from the current state) in the CR timeline.
The timestamp respects the user's preferred locale and uses the `time` element.
I've used the current name of the API payload's timestamps as it stands on the enterprise main branch for now. This name is not set in any schemas yet, so it is likely to change. Because it's not currently exposed to any users, that will not cause any issues. Name suggestions are welcome if you have them.
We only show timestamps for states up to and including the current state. Timestamps for downstream states (such as "approved" if you're in the "in review" state), will not be shown, even if they exist in the payload. (There are some decisions to make on whether to include these in the …
> Show change request stage timestamps in UI

- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.test.tsx
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
As per UX's requests, this updates the placement and styling of the schedule information for scheduled change requests. Instead of being below the "stage entered time" and in "secondary" color, we place it above that timestamp and in the same color as the stage name. 
This change is not behind a flag, so the color change will go out immediately upon release.
Before:
After:
Same for failed/suspended. Before:
After:
> Place schedule information first and change color of schedule info

- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.test.tsx
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/change-request-timeline-steps.test.ts
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/change-request-timeline-steps.ts
Shows the cancelled state in the timeline for cancelled CRs. Extracts steps into a separate file.
Also, if timestamps are present, it will dynamically show the steps we have times for for rejected and cancelled CRs.
If we do not have timestamps, it'll use the old behavior for displaying rejected steps, but does add a new one for cancelled steps, which includes 'Draft', 'In review', 'Approved', 'Cancelled'. 
CRs can be cancelled after:
- In review
- Approved
CRs can be rejected after:
- In review
- Schedule
For other states, use the existing steps. Cancelled and Rejected are both terminal states, so there's no future steps to show.
Regardless of what we have timestamps for, always show 'Draft', 'In review' and the final state (Rejected | Cancelled). 
Cancellations
Rejections 
New cancelled …
> feat: Timeline for cancelled CRs

- src/lib/services/api-token-service.ts
When querying invalid tokens we might catch them for a while to reduce database load. Being able to identify the token can help understanding what's going on or the client using that token
Log looks like:
```
[INFO] /services/api-token-service.ts - Token default:development.3ef3... rate limited until: Tue Jul 29 2025 09:53:47 GMT+0000 (Coordinated Universal Time)
```
> chore: better logging of failed tokens

- README.md
- frontend/src/component/admin/apiToken/ApiTokenForm/useApiTokenForm.ts
- frontend/src/component/admin/apiToken/CreateApiToken/CreateApiToken.tsx
- frontend/src/component/common/ApiTokenTable/useApiTokenTable.tsx
- frontend/src/component/environments/EnvironmentTable/EnvironmentActionCell/EnvironmentCloneModal/EnvironmentCloneModal.tsx
- frontend/src/component/integrations/IntegrationList/AvailableIntegrations/AvailableIntegrations.tsx
- src/lib/openapi/spec/bulk-registration-schema.ts
- src/lib/openapi/spec/client-features-schema.ts
- src/lib/openapi/spec/resource-limits-schema.ts
- src/lib/openapi/util/openapi-tags.ts
Rebrand SDK tokens and SDK types to make it easier to onboard and use:
**Backend SDK Token**: Intended for server-side SDKs. It can be used to access:
- The Client Features API (/api/client/features) for fetching all flag configurations for local evaluation.
- The Frontend API (/api/frontend) for remote evaluation.
**Frontend SDK Token**: Intended for client-side/frontend SDKs. It is restricted and can only be used to access:
- The Frontend API (/api/frontend) for remote evaluation.
> feat: rebrand sdk tokens and sdk types

- frontend/src/component/segments/SegmentTable/SegmentTable.tsx
Fixing the issue where modal with an active segment (for deletion) can change which segment it's listing if a new segment that is alphabetically earlier than the original segment
> fix: segment row id for modals

- frontend/src/component/common/Table/SortableTableHeader/CellSortable/CellSortable.styles.ts
- frontend/src/component/common/Table/SortableTableHeader/CellSortable/CellSortable.tsx
- frontend/src/component/tags/TagTypeList/__tests__/__snapshots__/TagTypeList.test.tsx.snap
Sometimes, the horizontal scroll bar for flags was showing scroll way past where it should.
Internal ticket details: https://linear.app/unleash/issue/1-3779/horizontal-hyperscroll-on-project-flag-list
> Fix: Horizontal hyperscroll on project flag list

- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestOverview.tsx
- frontend/src/component/changeRequest/ChangeRequestOverview/ChangeRequestTimeline/ChangeRequestTimeline.tsx
- frontend/src/component/changeRequest/changeRequest.types.ts
We renamed the property returned from the API, so we also need to update the UI.
> Update `stateTransitions` property in UI to match new API prop

- src/lib/features/feature-toggle/feature-toggle-service.ts
- src/lib/features/feature-toggle/tests/feature-toggle-service.e2e.test.ts
Previous PR: https://github.com/Unleash/unleash/pull/10439 introduced a bug not allowing to update the strategy name
Because there was no test covering this, it was only caught later on integration.
This PR modifies a test to also validate the change of strategy and fixes the problem
> fix: should be allowed to change strategy

- frontend/src/component/project/ProjectCard/ProjectArchiveCard.tsx
- frontend/src/component/project/ProjectCard/ProjectCard.styles.ts
- frontend/src/component/project/ProjectCard/ProjectCard.tsx
- frontend/src/component/project/ProjectCard/ProjectCardFooter/ProjectCardFooter.tsx
- frontend/src/component/project/ProjectList/ProjectGroup.tsx
- frontend/src/component/project/ProjectList/ProjectList.tsx
- frontend/src/component/project/ProjectList/ProjectsListHeader/ProjectsListHeader.tsx
- frontend/src/component/project/ProjectList/ProjectsListSort/ProjectsListSort.tsx
https://linear.app/unleash/issue/2-3743/overhaul-project-list-pages
This is essentially scouting work on our project list pages so we have a better baseline before proceeding with the cards/list view toggle.
Includes refactoring, fixes and visual improvements ensuring better consistency and alignment with our designs.
Took some liberties, so feel free to tell me I'm wrong.
> chore: overhaul project list pages

- frontend/src/openapi/models/bulkRegistrationSchema.ts
- frontend/src/openapi/models/clientFeaturesSchema.ts
- frontend/src/openapi/models/edgeTokenSchema.ts
- frontend/src/openapi/models/edgeTokenSchemaType.ts
- frontend/src/openapi/models/resourceLimitsSchema.ts
- frontend/src/openapi/models/unknownFlagSchema.ts
- frontend/src/openapi/models/unknownFlagsResponseSchema.ts
Update documentation to replace 'server-side' with 'backend' in API schemas
> chore: re-generate openapi

- frontend/src/component/project/ProjectList/ProjectList.tsx
- frontend/src/component/project/ProjectList/ProjectsListHeader/ProjectsListHeader.tsx
- frontend/src/component/project/ProjectList/ProjectsListSort/ProjectsListSort.tsx
- frontend/src/component/project/ProjectList/ProjectsListViewToggle/ProjectsListViewToggle.tsx
- frontend/src/component/project/ProjectList/hooks/useProjectsListState.ts
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
https://linear.app/unleash/issue/2-3746/add-project-list-view-toggle-with-respective-flag
Adds a project list view toggle hidden behind a feature flag: `projectListViewToggle`.
This is already part of the persistent project list page state.
Even though the view mode switching logic is in place, this isn't really doing anything else. We'll leave the actual visual changes (tables) for a follow up PR.
> chore: add project list view toggle with respective flag

- .github/workflows/ai-flag-cleanup-pr.yml
https://linear.app/unleash/issue/2-3749/prevent-ai-flag-cleanup-from-removing-the-wrong-flag
This slightly refines our prompt so we're strictly focusing on the relevant flag, instead of mistakenly targeting other flags.
Also includes:
- Adding our prompt to our output so we can more easily debug it 
- Only grab the last cleanup summary in case there are multiple (more than one step from the agent)
- Add a warning to the summary in case the agent couldn't find conditional logic related to the flag, only definitions / configurations
Did a few manual tests and it seemed to work correctly. Example: https://github.com/Unleash/unleash/pull/10461
> chore: AI flag cleanup should focus on relevant flag

- frontend/src/component/project/ProjectList/ProjectsListViewToggle/ProjectsListViewToggle.tsx
- frontend/src/hooks/usePlausibleTracker.ts
https://linear.app/unleash/issue/2-3754/add-plausible-event-project-list-view-toggle-with-view
Adds a `project-list-view-toggle` Plausible event with a `view` prop so we can track if and how the new toggle is used.
> chore: add project-list-view-toggle Plausible event

- frontend/src/component/feature/FeatureView/CleanupReminder/CleanupReminder.tsx
- frontend/src/component/feature/FeatureView/CleanupReminder/useReminders.test.tsx
- frontend/src/component/feature/FeatureView/CleanupReminder/useReminders.ts
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectCleanupReminder/ProjectCleanupReminder.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
Introduction of cleanup reminders at the project level to help identify flags that haven't been used recently. Uses the existing reminder system with snooze functionality.
Key changes:
- Renamed `useFlagReminders` to `useReminders` to make it more generic and reusable
- Added `ProjectCleanupReminder` component
> feat: project-level cleanup reminders

- frontend/src/component/environments/EnvironmentTable/EnvironmentNameCell/EnvironmentNameCell.tsx
https://linear.app/unleash/issue/2-3758/fix-environment-name-cell-after-the-latest-changes-to-textcell
Noticed the environment name cell acted differently after [adjusting](https://github.com/Unleash/unleash/pull/10466/files#diff-485a5be6a3a5d639b56c3b29488125db051ce6b8a0e3561368d657d62dee4975R28) the span inside TextCell to be `display: inline-flex`.
By wrapping the contents of our TextCell here into a single div we explicitly declare this to be a single row of elements.
> fix: environment name cell

- src/migrations/20250813125755-backfill-lifecycle-trends-fix.js
It is using almost same logic as https://github.com/Unleash/unleash/pull/10476, but week range is correct.
> fix: week range for lifecycle backfill

- src/lib/features/events/event-store.ts
- src/test/e2e/api/client/feature.optimal304.e2e.test.ts
This ignores Change Request event types when calculating the etag because Change Request events don't change data.
They were being included when the change request event contained a featureName. After this change, those should be excluded.
> chore: ignore CR events with feature name

- frontend/src/component/insights/componentsChart/CreationArchiveChart/CreationArchiveChart.tsx
This PR removes the flags archived / flags created trend line as well as the right-hand column.
Before:
After:
I'm not deleting the tooltip yet, because I think we'll want to re-use that for the group tooltip.
> Remove ratio graph & column to the right

- src/lib/features/client-feature-toggles/client-feature-toggle.controller.ts
- src/lib/features/feature-toggle/configuration-revision-service.ts
- src/lib/types/experimental.ts
Add some **info** logs prefixed with `[etag]` so que can control them and with this investigate the increase in traffic after the new etag implementation.
> chore: add some debug statements controlled by a flag

- frontend/src/component/common/Table/PaginationBar/PaginationBar.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
* make sure that only page limit available in the UI can be selected and choose 25 otherwise. This will solve a problem when someone has bookmarked URL with limit=1 or has this value in local storage
* make sure that when paginating to next pages we see loading placeholder instead of "No feature flags available"
This is what we have now when changin a page on slow connection
Another issue when paginating is that total count drops to 0 for a short period. I know we had a cache component for this but it doesn't seem to be working anymore.
> fix: pagination limit and placeholder

- src/lib/features/client-feature-toggles/client-feature-toggle.controller.ts
- src/lib/features/feature-toggle/configuration-revision-service.ts
This is a follow-up on the comments in https://github.com/Unleash/unleash/pull/10512
Mostly using get and set when accessing the Map
> chore: Etag log and code improvements

- frontend/src/component/commandBar/CommandBar.tsx
https://linear.app/unleash/issue/2-3819/disable-browser-autocomplete-on-our-command-bar
Disables browser autocomplete on our CommandBar:
> chore: disable browser autocomplete on commandbar

- frontend/src/component/admin/instance-admin/InstanceStats/InstanceStats.tsx
- frontend/src/openapi/models/instanceAdminStatsSchema.ts
- src/lib/features/instance-stats/createInstanceStatsService.ts
- src/lib/features/instance-stats/instance-stats-service.ts
- src/lib/openapi/spec/instance-admin-stats-schema.ts
- src/lib/routes/admin-api/instance-admin.ts
- src/lib/services/version-service.test.ts
- src/lib/services/version-service.ts
- src/test/e2e/api/admin/instance-admin.e2e.test.ts
- src/test/fixtures/store.ts
Adds two fields to the instance stats:
releaseTemplates
and releasePlans
> chore: add release plans/templates count to instance stats

- frontend/src/component/insights/componentsChart/CreationArchiveChart/CreationArchiveChart.tsx
You can't archive half a flag.
Closes 1-4034.
> Chore: Use step size of 1 for created vs archived.

- src/lib/features/instance-stats/instance-stats-service.ts
- src/test/e2e/api/admin/instance-admin.e2e.test.ts
Rolls back hashing of the newly added releasePlans and releaseTemplates fields
> chore: rollback hashing of release-plans and templates

- src/lib/features/metrics/unknown-flags/unknown-flags-controller.ts
- src/lib/openapi/util/openapi-tags.ts
https://linear.app/unleash/issue/2-3832/promote-api-to-a-stable-openapi-tag
Promotes the Unknown Flags API to a stable OpenAPI tag as we prepare for GA.
> chore: promote unknown flags to a stable OpenAPI tag

- src/migrations/20250827135502-add-impact-metrics.js
We want to store impact metrics configuration per flag. Previously we were storing impact metrics in global settings. This new table will accommodate both metrics for a flag and global ones (null feature field).
I decoded to model config as JSONB since we're not going to do any joins and we need to store data of this shape:
```
{
id: string;
selectedSeries: string;
selectedRange: 'hour' | 'day' | 'week' | 'month';
beginAtZero: boolean;
aggregationMode: string;
selectedLabels: Record<string, string[]>;
title?: string;
}
```
This is basically CRUD for this screen
> feat: impact metrics migration

- frontend/src/component/admin/network/NetworkTrafficUsage/BackendConnections.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/FrontendNetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/NetworkTrafficUsage.tsx
- frontend/src/component/admin/network/NetworkTrafficUsage/networkTrafficUsageHighlightPlugin.ts
- frontend/src/component/common/Chart/customHighlightPlugin.ts
- frontend/src/component/insights/components/LineChart/LineChartComponent.tsx
- frontend/src/component/insights/componentsChart/CreationArchiveChart/CreationArchiveChart.tsx
Uses the same custom highlighter that we've used for the other analytics charts, but customizes it for the archive : creation ratio chart. Also removes the color change on hover from the bars.
Because this plugin (or a version of it) is also used in the network traffic graphs, I've consolidated all the uses into a more configurable one (because I was mistakenly working in the wrong file).
Before:
After:
> chore: Use custom highlighter for archive:creation chart

- frontend/src/component/insights/GraphCover.tsx
- frontend/src/component/insights/components/LineChart/LineChartComponent.tsx
- frontend/src/component/insights/componentsChart/CreationArchiveChart/CreationArchiveChart.tsx
- frontend/src/component/insights/componentsChart/CreationArchiveChart/placeholderData.ts
Adds a cover to the archived vs created flag chart if we don't have enough data or if the data is loading. Follows the pattern established in the other analytics charts.
Because the values for a placeholder bar chart are different than for a placeholder line chart, I've added in actual placeholder values. This also makes the gives the chart in question two bars per category, even in the placeholder data, which matches nicely with the actual graph.
Before:
After: 
In context with the other charts:
> chore: Add a cover for when we don't have enough data to show the chart

- frontend/src/component/insights/componentsChart/CreationArchiveChart/CreationArchiveChart.tsx
The previous implementation had a small bug where it would show "not enough data" even if the graph was loading. This commit fixes that.
While working, I thought that maybe we should keep the current data while we're fetching new data instead of adding a cover, but all the other graphs use a cover when loading, so I've not made any changes to that effect.
> fix: Only show "not enough data" text when there isn't enough data.

- website/src/components/VideoContent.jsx
- website/src/theme/Root.tsx
CookieYes was throwing an uncaught error triggered by GA and GTM scripts. We don't want analytics to run in development anyway, so I disabled them in these environments.
> fix: only load ga and gtm in production

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/LegacyFeatureStrategyMenuCards/LegacyFeatureStrategyMenuCards.tsx
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
https://linear.app/unleash/issue/2-3865/add-newstrategymodal-feature-flag
Adds `newStrategyModal` feature flag.
The approach here is to duplicate the existing `FeatureStrategyMenuCards` into a `LegacyFeatureStrategyMenuCards`. We'll continue working on the `FeatureStrategyMenuCards` component while leaving `LegacyFeatureStrategyMenuCards` untouched. Once we're done with the implementation and remove the flag we can drop the legacy file.
I think it's easier to reduce our add strategy buttons to a single one right away (like we did with the `addConfiguration` flag in https://github.com/Unleash/unleash/pull/10420). This allows us to focus on the end result instead of having to implement things like "clicking the 'add release template' button should show the modal filtered to only release …
> chore: add newStrategyModal flag

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
https://linear.app/unleash/issue/2-3870/new-modal-design
New "add strategy" modal base design.
We're still missing a few details, like the new card design and the filters at the top, but those will come in follow-up PRs.
> chore: new add strategy modal design

- src/lib/db/aws-iam.ts
- src/lib/db/db-access-checker.ts
- src/lib/db/db-pool.ts
- src/lib/server-impl.ts
https://linear.app/unleash/issue/2-3874/add-verbose-logs-to-aws-iam-auth-logic-including-a-db-access-checker
Adds verbose logs to our new AWS IAM DB auth logic. Also adds a DB access checker that runs before our migrator and fails fast in case something is wrong with DB access.
This should not affect the regular auth path.
> chore: add verbose logs to AWS IAM auth logic, add DB access checker

- frontend/src/component/common/QuickFilters/QuickFilters.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCardsReleaseTemplates.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCardsSection.tsx
https://linear.app/unleash/issue/2-3868/add-strategy-filters-at-the-top
Adds quick filters to our "add strategy" modal.
`FeatureStrategyMenuCards.tsx` was getting increasingly complex, so this includes some refactoring.
My quick filters implementation was generic enough that I added `QuickFilters.tsx` as a common component, maybe we can reuse it in the future.
> chore: add quick filters to add strategy modal

- frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/FeaturesCell.tsx
Updates the features cell text when you have lots of flags affected.
Looks like we missed this one in a previous renaming attempt.
Before:
After:
> chore: Update from "toggles" to "flags"

- frontend/src/component/changeRequest/ProjectChangeRequests/ChangeRequestsTabs/ChangeRequestsTabs.tsx
For some reason, the two change request tabs are called "Change Requests" and "Closed", instead of "Open" and "Closed".
I suspect this may be an error, but this fixes it. 
Before:
After:
> chore: change from "change requests" to "open" in project change request tabs

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlanReviewDialog.tsx
https://linear.app/unleash/issue/2-3878/persist-strategy-filter-when-going-back-from-the-release-template
Persists the strategy filter in the new "add strategy" modal when going back from the release template preview modal.
This is done by moving the filter to the parent component, so the filter state persists across these navigations.
Also updates the button text in the release templates preview to say "Apply template" for consistency, but only if the `newStrategyModal` flag is enabled.
> chore: persist strategy filter when going back from release template preview

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenu.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCard/FeatureStrategyMenuCard.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/LegacyReleasePlanReviewDialog.tsx
https://linear.app/unleash/issue/2-3888/update-the-release-templates-preview-dialog-to-match-the-new-designs
Updates the release template preview dialog when using the new "add strategy" modal, so it better matches the new design.
Used the legacy file pattern to leave the previous modal component unchanged.
> chore: update release template preview dialog

- src/lib/features/metrics/client-metrics/metrics-service-v2.ts
- src/lib/features/metrics/impact/batch-histogram.test.ts
- src/lib/features/metrics/impact/batch-histogram.ts
- src/lib/features/metrics/impact/impact-metrics.e2e.test.ts
- src/lib/features/metrics/impact/metrics-translator.test.ts
- src/lib/features/metrics/impact/metrics-translator.ts
- src/lib/features/metrics/shared/schema.ts
Extends the impact metrics ingestion to support histograms, enabling SDKs to send pre-aggregated histogram data to Unleash.
Key Changes
- MetricsTranslator enhancements: Added histogram translation with proper label management and registry reuse pattern (consistent with counters/gauges)
- Schema validation: Extended Joi schemas to validate histogram samples including support for +Inf bucket boundaries
- Label encoding fix: Switched from string concatenation to JSON encoding for label keys to safely handle special characters (colons, URLs)
> feat: histogram impact metric ingestion

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCard/FeatureStrategyMenuCard.tsx
- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCardsReleaseTemplates.tsx
https://linear.app/unleash/issue/2-3898/update-the-design-of-the-view-more-button
Updates the design of the "view more templates" button in the new "add strategy" modal.
> chore: update view more templates button design

- frontend/src/component/feature/FeatureStrategy/FeatureStrategyMenu/FeatureStrategyMenuCards/FeatureStrategyMenuCards.tsx
https://linear.app/unleash/issue/2-3896/add-quick-filter-for-custom-strategies
Adds a quick filter for custom strategies in the new "add strategy" modal.
> chore: add quick filter for custom strategies

- frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.test.tsx
- frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts
- frontend/src/hooks/useClearSWRCache.test.ts
- frontend/src/hooks/useClearSWRCache.ts
Fixes an issue where the project feature list (and potentially other places in the app that use the `useClearSWRCache` hook) would end up in an infinite loading screen because the latest entry that we want to show was overwritten.
The primary reason this happened is that we used `keysToDelete = array.slice(SWR_CACHE_SIZE - 1)`. Because the map keys are returned in insertion order, this would make us never delete the oldest keys, but always anything after the cache reached it's maximum size. The fix was to instead do `slice(0, -(SWR_CACHE_SIZE - 1))`, unless that is `0, 0`. If so, then just delete the entire filtered keys set. 
As a bonus: this PR also deduplicates cache entries that have the same query params but in different order for the feature search. This further reduces the cache …
> fix: cache eviction bug and the eternal loading screen

- frontend/src/hooks/api/getters/useChangeRequestSearch/useChangeRequestSearch.ts
- frontend/src/hooks/api/getters/useEventSearch/useEventSearch.ts
- frontend/src/hooks/api/getters/useFeatureSearch/useFeatureSearch.ts
- frontend/src/hooks/api/getters/usePaginatedData/usePaginatedData.ts
- frontend/src/hooks/api/getters/useSignalQuery/useSignalQuery.ts
- frontend/src/hooks/useClearSWRCache.test.ts
- frontend/src/hooks/useClearSWRCache.ts
With three and four different parameters (of which two are strings that are easily interchanged), it makes sense to rewrite these two functions to take named parameters instead. This is a follow-up to https://github.com/Unleash/unleash/pull/10689 based on one of the review comments.
> chore: use params object for swr cache clearing functions

- frontend/src/hooks/useClearSWRCache.ts
entriesToLeave is more ambiguous than entriesToKeep, so let's go with the latter.
> chore: rename variable for clarity

- frontend/src/component/common/LifecycleFilters/LifecycleFilters.tsx
If the total number of flag is undefined, we've previously shown "0 of undefined". However, I don't think that's sensible. Instead, we should show "0".
Before:
After:
> fix: fall back to count === 0 if undefined / don't show "0 of undefined"

- frontend/src/component/changeRequest/ChangeRequests/ChangeRequestFilters.tsx
- frontend/src/component/changeRequest/ChangeRequests/ChangeRequests.tsx
Adds filter buttons for filtering between "CRs created by me" and "CRs where I've been requested as an approver".
The current implementation is fairly simplistic and the buttons are not connected to the actual table state directly (instead being set up with their own simple state and onChange hooks), but it covers the simple scenario. I want to defer a more complex solution until we know we need it and until we know exactly what we need. The implementation is based on the lifecycle filters that we have on the project flags page.
The current logic is such that: when you land on the page, there's no query params in the URL, but the data fetch applies `createdBy:IS<your user>`. If you switch to "approval requested" (and back again), the URL will reflect this.
For reference, the github …
> feat: add change request table filter buttons

- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOverviewFilters.tsx
Archived flags link will now it will show up on the right side, next to import/export, which makes it more in line with flags overview.
> feat: change "archived" flags filter placement on project flags list

- src/migrations/20251002095623-not-null-constraints.js
In our code, we're not expecting constraints to be null: https://github.com/search?q=repo%3AUnleash%2Funleash%20jsonb_array_elements(constraints)&type=code
It's unlikely to get a null value in constraints when using our API or UI, but there might be cases where this can happen, as we saw in our logs:
```
error: select "context_fields"."name", "context_fields"."description", "context_fields"."stickiness", "context_fields"."sort_order", "context_fields"."legal_values", "context_fields"."created_at", COUNT(DISTINCT CASE
WHEN features.archived_at IS NULL
THEN feature_strategies.project_name
END) AS used_in_projects, COUNT(DISTINCT CASE
WHEN features.archived_at IS NULL
THEN feature_strategies.feature_name
END) AS used_in_features from "context_fields" LEFT JOIN feature_strategies ON EXISTS ( …
```
> fix: constraints should not be null

- src/lib/features/users/user-updates-read-model.test.ts
- src/lib/features/users/user-updates-read-model.ts
We could have users updated at the exact same time, so we need to include that timestamp in the next fetch to avoid missing users, but also include the latest user id so we can exclude the ones already fetched.
The following test shows how to process pages with this new method:
https://github.com/Unleash/unleash/blob/c03df86ee006f531024137a1cfc846eb282ab672/src/lib/features/users/user-updates-read-model.test.ts#L39-L65
> chore: new method that considers users updated at the same time

- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.test.tsx
- frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
"Lifecycle" filter should never be enabled when viewing archive.
> fix: clearing lifecycle filter when switching to archived view

- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentHeader/EnvironmentHeader.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentHeader/EnvironmentStrategySuggestion/EnvironmentStrategySuggestion.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/EnvironmentHeader/LegacyEnvironmentHeader/LegacyEnvironmentHeader.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironment/LegacyFeatureOverviewEnvironment/LegacyFeatureOverviewEnvironment.tsx
- frontend/src/component/feature/FeatureView/FeatureOverview/FeatureOverviewEnvironments/FeatureOverviewEnvironments.tsx
- frontend/src/component/project/Project/ProjectSettings/ProjectDefaultStrategySettings/ProjectEnvironment/ProjectEnvironment.tsx
- frontend/src/hooks/usePlausibleTracker.ts
- frontend/src/interfaces/uiConfig.ts
- src/lib/types/experimental.ts
- src/server-dev.ts
This adds a default-strategy suggestion banner to the bottom of empty feature environments (envs without strategies)
> feat: add a suggestion banner at the bottom of empty feature-environments

- src/lib/openapi/spec/patch-schema.ts
This would allow users to add test statements to protect from concurrent modifications. From https://github.com/orgs/Unleash/discussions/10707#discussioncomment-14602784
E.g.
If you had this feature flag configuration
```
{
"name": "flexibleRollout",
"constraints": [
{
"contextName": "a",
"operator": "IN",
"values": [
"100", "200", "300", "400", "500"
],
"caseInsensitive": false,
"inverted": false
}
],
"parameters": {
"rollout": "100",
"stickiness": "default",
"groupId": "api-access"
},
"variants": [],
"segments": [
122
],
"disabled": false
}
```
And you'd like to remove the value 300 from the constraints, you'd have to first get the current values and then PATCH the strategy with the following body:
```
[{ "op": "remove", "path": "/constraints/0/values/2" }]
```
This could fail in case …
> feat: allow test operation for patch

- frontend/src/component/insights/componentsChart/CreationArchiveChart/CreationArchiveChart.tsx
- frontend/src/component/insights/componentsChart/CreationArchiveChart/CreationArchiveRatioTooltip.tsx
- frontend/src/component/insights/componentsChart/CreationArchiveChart/batchWeekData.test.ts
- frontend/src/component/insights/componentsChart/CreationArchiveChart/batchWeekData.ts
- frontend/src/component/insights/componentsChart/CreationArchiveChart/types.ts
- frontend/src/component/insights/hooks/useInsightsData.ts
- frontend/src/component/insights/sections/PerformanceInsights.tsx
Implements batching of data points in the archived:created chart: when there's 12 or more weeks of data, batch data into batches of 4 weeks at a time. When we batch data, we also switch the labeling to be month-based and auto-generated (cf the inline comment with more details).
The current implementation batches into groups of 4 weeks, but this can easily be parameterized to support arbitrary batch sizes.
Because of the batching, we also now need to adjust the tooltip title in those cases. This is handled by a callback.
> feat: batch week data if the shown time span is greater than 12 weeks.

- src/lib/db/feature-environment-store.ts
- src/lib/features/release-plans/release-plan-store.ts
- src/lib/types/stores/feature-environment-store.ts
- src/test/e2e/stores/feature-environment-store.e2e.test.ts
https://linear.app/unleash/issue/2-3932/cloned-environments-enable-disabled-strategies-unexpectedly
Cloning environments didn't work as expected. This fixes a few of issues:
- Disabled strategies remain disabled after cloning
- All strategy properties are cloned (including e.g. title)
- Strategy cloning respects the selected projects
- Release plans and their milestones are now correctly cloned
> fix: clone environments

- website/docs/topics/feature-flags/feature-flag-best-practices.mdx
We've run an AI workflow to find frequently asked questions around feature flagging on community forums.
This change adds these FAQs at the bottom of our 11 principles page to help with discoverability and LLM search.
Preview: https://unleash-docs-git-docs-add-faqs-to-11-principles-unleash-team.vercel.app/topics/feature-flags/feature-flag-best-practices#frequently-asked-questions-faqs
> docs: add FAQs to 11 principles page
